### ISSUE TITLE
Excessively wordy hang/crash dialogue box on Windows

### ISSUE THREAD

**Issue by mcl21014** [bleachbit/bleachbit#1000]
See the image. On Windows 10 64 bit. 4.1.0 beta. Seems the description for BleachBit is used in the crash dialogue, and it's quite wordy. Screenshot will show the exact text. A good way to reproduce is to have an older computer (think two cores or less), a ton of cleaners with extra downloaded cleaners enabled in Settings, and click preview and click the program when it's processing.
![image](https://user-images.githubusercontent.com/3611312/91754899-3847b000-eb98-11ea-88c8-35ebdf7b692e.png)

**Comment by az0** [comment]
@mcl21014 
Please see comment here https://github.com/bleachbit/bleachbit/issues/1109#issuecomment-1304874311

Please try that build and provide a new screenshot

**Comment by az0** [comment]
Fixed: https://github.com/bleachbit/bleachbit/issues/1134#issuecomment-1374545142

**Comment by az0** [comment]
I am splitting apart milestones 4.6 and 5.0 where 4.6 still has Python 3.4 and 5.0 has Python 3.10, which is not ready yet, and this issue goes with 5.0.

**Comment by az0** [comment]
Two options to try for anyone having this issue

[Build 2584](https://ci.bleachbit.org/?prefix=dl/4.6.1.2584-processname/). This is the latest version of BleachBit (4.6.x) using the old framework (Python 3.4, GTK 3.24).

[Build 2467](https://ci.bleachbit.org/?prefix=dl/4.4.2.2467-mkhon-python310/) uses the new framework (Python 3.10.7), but it has an old build date July 2023. This build has known issues, so it's just for testing, so I recommend portable (zip) over installer (exe).  Once ready, this will be BleachBit 5.0.

Each build may have an improved process name in a different way.

Google Chrome may show safety warnings for the site ci.bleachbit.org . This is a false positive, but they won't give me details on the issue.

For cross referencing, here are related issues:  https://github.com/bleachbit/bleachbit/issues/617 https://github.com/bleachbit/bleachbit/issues/1000 https://github.com/bleachbit/bleachbit/issues/1109 https://github.com/bleachbit/bleachbit/issues/1134 https://github.com/bleachbit/bleachbit/issues/1655

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) has a fix for a shorter process name. If you still see an issue with the process name, reopen this issue.**

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
