### ISSUE TITLE
DNF autoremove subprocess still running after completion

### ISSUE THREAD

**Issue by terrycloth** [bleachbit/bleachbit#1001]
I'm testing BleachBit 4.1.0 beta on Fedora 32 Workstation x86\_64.

After installing [the 4.1.0-1.1.fc32 RPM from Sourceforge](https://master.dl.sourceforge.net/project/bleachbit/bleachbit/4.1.0/bleachbit-4.1.0-1.1.fc32.noarch.rpm), I:

1. ran `sudo bleachbit`.
1. unchecked all cleaners except DNF autoremove.
1. clicked Preview. It said it could free about 8 MB, but didn't list which packages it would remove.
1. started a regular DNF autoremove from the terminal to see make sure it wouldn't remove anything I needed, canceled that, then back in BB, clicked Clean. It said it removed about 8 MB, but still didn't list which packages it removed.
1. noticed that BleachBit says in red text in the main window (and repeats in the terminal output) that `subprocess 154036 is still running`.

When I check the processes running on my system, I see

```
USER         PID    PPID NICE %CPU %MEM STAT     ELAPSED COMMAND
root      154036  153904    0 30.5  0.0 Z+         00:25 [dnf] <defunct>
```

until BleachBit exits.

...The leftover process probably isn't all that big a deal, since it does exit when BleachBit exits, although the red font in the BleachBit window probably makes it _seem_ pretty bad to the typical end-user. However, more information about which packages are getting removed would be nice. BleachBit even shows a confirmation dialog suggesting the user review the packages before removing, but then doesn't say what those packages are :stuck_out_tongue_closed_eyes:

**Comment by az0** [comment]
I fixed the subprocess problem. One way to test it (without waiting for a new RPM package) is to overwrite the changed code using this command

`sudo wget https://raw.githubusercontent.com/bleachbit/bleachbit/72150a8a74b9cb6e0fb01a8748c4fe896321f904/bleachbit/Unix.py /usr/share/bleachbit/Unix.py`

The other part, identifying the packages, is a separate issue, so perhaps you could file a separate ticket.
