### ISSUE TITLE
Web launcher fails

### ISSUE THREAD

**Issue by cliftonprince** [bleachbit/bleachbit#1003]
Bleachbit > About Bleachbit > website > click link ... 

"Could not show link
failed to execute helper program (invalid argument)"

Screenshot attached 
![Annotation 2020-09-02 110316](https://user-images.githubusercontent.com/17009729/92007733-ede74000-ed0b-11ea-9611-1f827adc9d11.png)

**Comment by az0** [comment]
@cliftonprince 
This looks like issue https://github.com/bleachbit/bleachbit/issues/918 that you filed in May. Please try updating to [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta), and let me know how it goes.

**Comment by cliftonprince** [comment]
Fixt :) 

Solved, Beta 4.1.0.1723 release web launcher does launch properly for me. And WHOOPS, sorry to repeat-post it, didn't realize I'd already reported it "officially" like that, my bad.

**Comment by az0** [comment]
Thank you for confirming it is fixed
