### ISSUE TITLE
BleachBit killed Wi-Fi

### ISSUE THREAD

**Issue by Translator5** [bleachbit/bleachbit#1006]
BleachBit version 4.0.0
Kernel: 5.8.3
Product: Wi-Fi 6 AX200
Manjaro Linux

After running BleachBit once with all checked and restarting the PC, wifi do not work any longer.
product: Wi-Fi 6 AX200

sudo lshw -C network
*-network UNCLAIMED       
       description: Network controller
       product: Wi-Fi 6 AX200
       vendor: Intel Corporation

**Comment by az0** [comment]
I can't think of any way that BleachBit, even with all options enabled, affects wi-fi. (Nine years ago someone asked for the ability to flush DNS on Windows. This was never added, but this is the closest thing I can think of.) If you have an idea how this might have happened, please let me know.

About the time this happened, did you do any other system maintenance, update software, change drivers, or adjust system settings? Did you change the version your Linux kernel? Change secure boot?

**Comment by Translator5** [comment]
May this was also caused by any issue regarding dualboot and window's auto-correction of partitions - so sorry.
