### ISSUE TITLE
winapp2.ini sections are numbers instead of names (Bug in Beta BeachBit 4.1.0)

### ISSUE THREAD

**Issue by kc9nrb** [bleachbit/bleachbit#1007]
Noticed this when I installed the beta. It only relates to the Edge Browser stuff.

![Bug Report Bleach Bit](https://user-images.githubusercontent.com/70806254/92305321-caaad380-ef4b-11ea-863e-1d63eb171f1d.png)

**Comment by az0** [comment]
@kc9nrb 
I could use some more information. Would you please do this?

1. Click the **Help** menu
2. Click **Diagnostics**
3. Copy the the information to the clipboard 
4. Paste it here in GitHub (at least the lines with version numbers)

**Comment by az0** [comment]
I am closing because of no response. If you have the information, please post it here and re-open the issue ticket.
