### ISSUE TITLE
How to install English-only Portable?

### ISSUE THREAD

**Issue by hced** [bleachbit/bleachbit#1008]
Downloaded the portable of BleachBit, but can't get rid of my own locale. Is there a way to accomplish this? (Don't want to use installer due to registry clogging.)

**Comment by az0** [comment]
After unpacking the portable archive, delete the directory `share\locale` with has all the translations.

(Inside the `locale` folder, there are many subdirectories such as `af`, `ar`, `ast`, `be`, and so on.)
