### ISSUE TITLE
Wipe Process & Vol Free Space

### ISSUE THREAD

**Issue by Surfride10** [bleachbit/bleachbit#1011]
I am testing 4.1.0.1723, target is Window Server 2012r2.

GIVEN:
Tested with a single vol,  Because this is a production server and the wipe process is not throttled, drive utilization was 100% adversely effecting server performance. I attempted to cancel the wipe process by closing the ui; bleachbit.exe   The bleachbit process continued to run without the ui and I decided best to let it run to completion.  

ISSUE:
Overnight the server generated out of space errors for background processes because the free space on drive c was zero upon completion of the wipe process.  Currently the drive has a 206gb file created at 11:47:49p EST from the root named: C3FZSTVFKW3WIUVT6O8FFLWCMYPAQRY7XRDY6WPA1FIW28Z6CNBIU5JAUK3HXAKY7Z4NBOU2LKOBMTD (.c3FZsTVfkW3wiuVt6O8fflWCMYpAqry7xrdy6wPA1fIW28Z6cNBiu5jaUk3hXaKY7Z4nBoU2lKObMTDeMutwOuqCxVVULBeO9l3zA3ngpmtm4SZ5WSt5GLJljXih2iPE3WOD_ngGEcrxAe5LeplIQ2XIo6kFCihv)  

ACTION:
restore server operation by moving the file to a free vol 
confirm free space was wiped via winhex.

WISHLIST:
Throttle the wipe process to a user configurable max utilization rate.

Hopefully this is helpful, appreciate what you do!

~David

**Comment by az0** [comment]
Thank you for testing, David, and sorry about the out of space errors.

In case of emergency, you could terminate the BleachBit process. If killed, it cannot clean up after itself, but you can manually clean up by deleting the kind of file you mentioned. This kind of file contains nothing valuable and does not need to be saved nor moved to another volume.

Regarding your wishlist, you could file a new ticket at https://github.com/bleachbit/wishlist/issues and I could close this one, or I could move this ticket over there. Let me know.

Here is a related wishlist item: https://github.com/bleachbit/wishlist/issues/71

**Comment by Surfride10** [comment]
I understand this event was of my own making and I appreciate what you do...  When I terminated thread 0, the spawned worker threads were not killed.  Perhaps a semaphore to warn the user its still working, then if killed outside the UI, preventing a new instance when an orphaned process is still running as in this case, or perhaps namedpipes allowing the UI to re-establish communication with the orphaned worker process, just a thought, please do not take my comment as criticism...  Throttling would be helpful, happy to open request in wishlist.  Again, I appreciate what you do and thank you.

**Comment by az0** [comment]
> WISHLIST:
> Throttle the wipe process to a user configurable max utilization rate.

Which do you mean

1. Do the "wipe free space" process slowly, so it does not slow down other system processes, _OR_
2. Do not consume 100% of the free space. Allow user to preserve some space (maybe 1%, 5%, 1GB, or something like that)

**Comment by az0** [comment]
Closing because of no response
