### ISSUE TITLE
Pale moon clean error (4.1.0 beta): sqlite3.OperationalError: no such table: moz_origins

### ISSUE THREAD

**Issue by PrefixCoder** [bleachbit/bleachbit#1012]
### Version
bleachbit 4.1.0.1723
Windows 10
Pale Moon 28.13.0.win64

### Message
```
Error: palemoon.url_history: Function: Clean file: C:\Users\Winda\AppData\Roaming\moonchild productions\pale moon\Profiles\brzyhnx1.default\places.sqlite
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 440, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_origins

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 311, in delete_mozilla_url_history
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 448, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_origins: C:\Users\Winda\AppData\Roaming\moonchild productions\pale moon\Profiles\brzyhnx1.default\places.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'
```
### Steps
1. Select "Pale Moon/URL history" section
2. Click "Clean"
3. The error message is shown beside other (successful) operations
**Problem is reproducible:**
4. Click "Clean" again
5. The error message is shown, again

**Comment by az0** [comment]
Good detail in this bug report. Thank you. It also looks like https://github.com/bleachbit/bleachbit/issues/1002

**Comment by az0** [comment]
CI build 4.1.0.1732 has the fix, and it's building now. Would you please [visit the CI site](https://ci.bleachbit.org/), download this version or a newer version, test it, and write a comment here whether the fix helped?

**Comment by PrefixCoder** [comment]
Tested portable. Problem is fixed.

Btw win defender SmartScreened installer. I ran it through VirusTotal: 
https://www.virustotal.com/gui/file/56294fdc4ed88cb9f07dba4f2b4ab2cc8e6ee055d968639971f6d644898a61e5/detection

Sorry if it's unethical to send intermediate versions to virustotal.

**Comment by az0** [comment]
> Tested portable. Problem is fixed.

Thank you for checking.

> Btw win defender SmartScreened installer. I ran it through VirusTotal:
> https://www.virustotal.com/gui/file/56294fdc4ed88cb9f07dba4f2b4ab2cc8e6ee055d968639971f6d644898a61e5/detection
> 
> Sorry if it's unethical to send intermediate versions to virustotal.

Feel free to check anytime, but here's what to expect. The files on ci.bleachbit.org will trigger SmartScreen because of its popularity heuristic. They aren't popular like final releases, so they trigger a warning. Many beta and final releases will have one or two false positives on virustotal, and I will report them to the vendors. I probably won't do anything about false positives for normal releases on ci.bleachbit.org . If you have a related issue to false positives about a final or beta release, open a new ticket.
