### ISSUE TITLE
Bleachbit 4 doesn't start in Windows 10 (slow start without feedback to user)

### ISSUE THREAD

**Issue by gitthepie** [bleachbit/bleachbit#1013]
I recently tested Bleachbit 4 in Windows 10, but it didn't start at all. I believe I had the latest version; I installed it within the past 48 hours, unless you've updated Bleachbit within that time frame. In case it becomes important, I was running Windows 10 version 1909.

I do see a bleachbit.exe process in Task Manager, but no Bleachbit window opens. Running bleachbit_console.exe just opens a blank black window that does nothing. Bleachbit 2.0 ran just fine on the same installation of Windows, but I'd rather not have to go back to that.

**Comment by gitthepie** [comment]
I just wanted to provide an update on my situation. I have expanded my test to a clean installation of Windows 10 version 2004 (newer than version 1909) on a different computer. I experienced the same problem. I then tested BleachBit 3.2 as well and found that it still didn't open.

**Comment by Samuelms79** [comment]
I noticed that the program also takes a long time to open even using SSD, 4x longer if using a PC with HDD. This behavior extends to several PCs with Windows 7 and Windows 10, both updated and with Beachbit 4.0.0 program.

**Comment by az0** [comment]
Which antivirus software do you both use? For troubleshooting, are you able to pause the antivirus or put it into game mode? (To be safe, please be sure you have the authentic BleachBit that is available on www.bleachbit.org and [digitally signed](https://docs.bleachbit.org/doc/install-on-windows.html).)

**Comment by Samuelms79** [comment]
I will try to summarize the answer to your question: All tested PCs have
different antivirus software, but all in their free version.  The tests
were also done with clean installations in VirtualBox, both with Windows 7
and Windows 10. The problem seems to be the delay in starting the program
after the system is started and restarted.  Curious that in any Linux
distro this behavior does not occur.

Em sex, 6 de nov de 2020 12:37, Andrew Ziem <notifications@github.com>
escreveu:

**Comment by az0** [comment]
@Samuelms79 

For troubleshooting, please try two things.

1. Delete the winapp2.ini file under `%appdata%\bleachbit\cleaners`
2. Run `bleachbit_console.exe` instead of `bleachbit.exe` because it may give more information
3. While starting BleachBit, check the Windows Task Manager for high CPU and disk I/O


Please try that. If step 2 gives more info, please paste it here or add a screenshot.

If step 3 hows high usage, a screenshot of that would be nice too

>: All tested PCs have different antivirus software, but all in their free version. 

Which antivirus?

**Comment by Samuelms79** [comment]
It was several free antivirus: Avira Free, Panda Dome Free, Kaspersky Free,
Avast Free, AVG Free, Windows Defender and in the case of Windows 7, I
tested without any antivirus.

Em ter, 10 de nov de 2020 13:22, Andrew Ziem <notifications@github.com>
escreveu:

**Comment by Woundorf** [comment]
I have the same issue with Windows 10 20H2. Antivirus is the default Windows Defender included in W10; disabling it doesn't solve the problem.

The folder `%appdata%\bleachbit\cleaners` does not exist but I tried deleting file `bleachbit.ini` in `%appdata%\bleachbit` instead. It's recreated when launching BleachBit again but the problem persists.

With the above file deleted, `bleachbit_console.exe` shows briefly the following text:

> Preservant idioma automàtic ca.
> Preservant idioma automàtic en.

Then closes and opens another window with no text.

Both `bleachbit.exe` and `bleachbit_console.exe` use 100% of one CPU core while they are running until I decide to kill the process. There is no significant disk I/O (the system has a SSD and an HDD and BleachBit is installed in the SSD).

**Comment by Woundorf** [comment]
Update: after leaving it running for some long time (I left the computer alone for more than 2 hours) I see it has finally opened.

**Comment by gitthepie** [comment]
The computer in question is using Comodo Antivirus. I will disable it and try again and report back. Meanwhile, should I also attempt the "troubleshooting" steps or were those steps only intended for Samuelms79?

**Comment by rados** [comment]
@az0
Hey guys I can help with this one. I have development environment under Windows 10 and can try to reproduce this. At the moment Bleachbit app works fine on my machine, both from source and from the installation. I don't have external anti-virus software, I use the embedded "Virus and Threat protection" software which includes Windows Defender as far as I know. My Windows 10 version is 20H2. And yes, there is a delay on app startup but it should happen only when the app is started for the very first time, any subsequent runs shouldn't be delayed.

**Comment by Samuelms79** [comment]
> 
> 
> @az0
> Hey guys I can help with this one. I have development environment under Windows 10 and can try to reproduce this. At the moment Bleachbit app works fine on my machine, both from source and from the installation. I don't have external anti-virus software, I use the embedded "Virus and Threat protection" software which includes Windows Defender as far as I know. My Windows 10 version is 20H2. And yes, there is a delay (less than 1 min) on app startup but it should happen only when the app is started for the very first time, any subsequent runs shouldn't be delayed.

This is exactly the problem. I tested this program in several situations:

* Different antivirus (Kaspersky Free, Windows Defender, Avira Free, Panda Free, Bitdefender Free).
* Basic and gamer PCs.
* Without antivirus software.
* Linux (Mint Mate, Mint Cinnamon, Fedora Workstation).
* Windows (7, 7 SP1, 10 1903, 10 1908 and 10 20h2).

Regardless of what I do, it always takes a while to start up, even if it's not the first time.

**Comment by abitrolly** [comment]
> Update: after leaving it running for some long time (I left the computer alone for more than 2 hours) I see it has finally opened. After this it launches immediately every time.

Might be some issue with font generation.

**Comment by rados** [comment]
> Might be some issue with font generation.

Yes, this is what I suspect but on my machine it happens only on the very first run and the waiting time is less than a minute.

**Comment by abitrolly** [comment]
Font caching time depends on installed fonts. https://snapcraft.io/blog/the-hunt-for-rogue-time-how-we-investigated-and-solved-the-chromium-snap-slow-startup-problem lists `google-noto` font family as a time bomb that adds 45 seconds to the caching.

**Comment by abitrolly** [comment]
A metrics about time used to build the fonts would be nice.

**Comment by XhmikosR** [comment]
I personally sort of can reproduce the issue if the Local AppData fontconfig folder does not exist or if the font cache needs to be updated; it takes like 10-15 sec the first time I run BleachBit. Subsequent runs are faster, like ~3 sec. But maybe that's also a lot since I'm using an M2 drive.

**Comment by abitrolly** [comment]
@XhmikosR what is the CPU, memory and disk usage during that process? I suspect that the bottleneck is CPU.

**Comment by abitrolly** [comment]
@rados do you know if the `fontconfig` regenerates cache data for all fonts it had found? Maybe is it possible to limit caching to actual fonts that we use?..

**Comment by XhmikosR** [comment]
i7 7700K at 4.5 GHz, not a bottleneck IMHO. Happens with newer processors
too.

**Comment by abitrolly** [comment]
@XhmikosR by bottleneck I mean that no matter which CPU is in use, it is 100% busy all these 15 seconds during BleachBit startup. If the bottleneck was in IO, then mem or M2 would be full with the CPU mostly idle.

**Comment by XhmikosR** [comment]
I don't see anything using a full core at 100%.

**Comment by rados** [comment]
@gitthepie @Woundorf @Samuelms79 @XhmikosR 

Hey guys, I think I've found something. Could you try one simple change? In "Program Files (x86)\BleachBit\etc\fonts\fonts.conf" file just remove or comment out the line reading <dir>WINDOWSFONTDIR</dir> and reapeat your tests from beginning (you'll need admin rights). This change fixed the latency on my machine.

**Comment by XhmikosR** [comment]
It does speed things up but the UI is using the wrong font then.

**Comment by rados** [comment]
> It does speed things up but the UI is using the wrong font then.

Yes, this is expected. If we all agree that this is a good direction I will adjust the font itself.

**Comment by gp1019** [comment]
Bleachbit (v. 4.2.0) isn't working for me on Windows 10. It's not a slow start, it just won't open or shred. Antivirus isn't blocking it. Hope this gets fixed soon. Unless if there is a way for me to resolve it. Has been happening since I updated.

**Comment by az0** [comment]
> Bleachbit (v. 4.2.0) isn't working for me on Windows 10. It's not a slow start, it just won't open or shred. Antivirus isn't blocking it. Hope this gets fixed soon. Unless if there is a way for me to resolve it. Has been happening since I updated.


@gp1019 

Your issue sounds different, so I encourage you to open a [separate bug ticket](https://github.com/bleachbit/bleachbit/issues/new/choose) for better tracking and troubleshooting.

**Comment by az0** [comment]
Rados made a fix for the issue that font caching causes slow start-up, and I accepted the fix. It works only when BleachBit is installed. (It does not work in portable mode.)

Here's how to test:

1. Uninstall BleachBit
2. Delete the folder `%userprofile%\AppData\Local\fontconfig`
3. Install BleachBit 4.2.0.1837 or later from the [CI build site](https://ci.bleachbit.org/)
4. Start BleachBit
5. Let us know  how it went by adding a comment here

**Comment by az0** [comment]
I haven't seen a reply to the request for testing (March 26), so I will assume gitthepie's issue was fixed. If the same issue is not fixed, please reopen this issue.

**Comment by barragh** [comment]
I had this issue too of trying to start it and getting nothing. I uninstalled it with Revo Uninstaller and downloaded and ran the portable version. There was a minutes delay but it works fine after that.
