### ISSUE TITLE
Internal and external hard drive not recognized due to bleachbit shutdown

### ISSUE THREAD

**Issue by Bellevillehillls** [bleachbit/bleachbit#1016]
Hello, for a few days I have encountered a major problem with my PC, it is constantly running with its fans at maximum. I think I know the reason, finally I identified two;
- the first, it is possible that I selected the experimental garbage collection
- the second it's also possible that I interrupted the running program.

I am really not a geek and I am hardly new to Linux, while browsing the forums I think I found a lead. This was someone with the same problem and someone replied that due to an early interruption bleacbit created a file in the root folder. I did not understand more.

Hope you can help me, thank you all.

**Comment by az0** [comment]
If the BleachBit is forcibly killed during during the "wipe free space" process, it may leave a large file behind. The file uses disk space, but I don't think this would affect fan speed. If you think this may have happened, see the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html) for "Q: I closed BleachBit while it was working for a long time, and now my hard drive is full. How do I fix it?"

On Linux, BleachBit has an option to wipe memory. If this is interrupted, you may be missing a swap partition, but again, I think this wouldn't affect the fan. Even before using BleachBit, not everyone needs, wants, or has a swap partition. To check whether you have one now, you can run the swapon command. It might look like this

````
$ swapon
NAME      TYPE SIZE USED PRIO
/swapfile file   2G   0B   -2
````

Let me know if you have more questions.

**Comment by az0** [comment]
No reply in 130 days
