### ISSUE TITLE
Missing icons for Firefox bookmarks with BleachBit 4.1.0 Beta 

### ISSUE THREAD

**Issue by Team-Sys** [bleachbit/bleachbit#1017]
Upon using said beta version, and then later opening Firefox, I immediately noticed that all my bookmark icon in the bookmark bar were generic blank icons instead of the respective websites' official icons. Using Windows 10 2004 update on Dell E-7440.
Feel free to message me if you need any other system information or files to fix this issue.

Edit: To clarify, I did confirm that it is BleachBit 4.1.0 Beta that deletes bookmark icons. The current stable version of BleachBit does not do this. Furthermore, I had ALL of Firefox's checkboxes unchecked and yet beta v1.4.0 still somehow causes the Firefox bookmark icon deletion.

**Comment by az0** [comment]
> Furthermore, I had ALL of Firefox's checkboxes unchecked and yet beta v1.4.0 still somehow causes the Firefox bookmark icon deletion.

Hmm, this is the strange part.

**Comment by Rb3rt** [comment]
Works as intended for me on Win10 deleting URL history completely on version 4.1.0.1725 (thanks for fixing that, Andrew). I whitelisted "favicons.sqlite" so favicons would'nt have to regenerate. Maybe a separate checkbox for "Favicons" would help, if possible.

**Comment by az0** [comment]
I confirm the issue. After version 4.0.0, there was a change 60d60ba1437e2aedede055265309f40279a09fc4 to delete  `favicons.sqlite`, which is enabled only when the Firefox option "URL history" is checked. (In older versions of Firefox, favicons data was in another file.)

**Comment by zero77** [comment]
I am using Debian with v4.1.0

After whitelisting favicons.sqlite, bleachbit does not delete it under the "Vacuum" list.

But, it still deletes it under the "URL history" list even when favicons.sqlite is whitelisted.

**Comment by rados** [comment]
Hey guys, I can trace this further.

**Comment by az0** [comment]
@rados 
Great. You may have already figured this out, but a good solution is to write a SQLite DML statement to delete the rows in `favicons.sqlite` that are not bookmarks in `places.sqlite`.  There's old code in `Special.py` that does the same thing for Google Chrome, but now it's needed for Firefox. The final piece is to replace the delete statement with a new special action.

**Comment by az0** [comment]
@Team-Sys 
Rados coded a fix such that the bookmarked favicons will be preserved, so you don't need to whitelist any file. Please try build 
4.1.0.1756 or newer from the CI [build site](https://ci.bleachbit.org/), try it out, and post a comment here to let me know how it went.

@zero77 
To test on Debian, you can get the code from GitHub or wait for the next beta release. (I will post .deb packages then.)

**Comment by Team-Sys** [comment]
This fixed the issue for me, thanks.

**Comment by rados** [comment]
@Team-Sys May I ask you for one more test since I introduced a better fix for this a couple of days ago. You can try those builds here: 
https://ci.bleachbit.org/?prefix=dl/4.2.0.1807-master/
