### ISSUE TITLE
"Explorer MRU Extras" updated tooltip? resets custom folder view columns

### ISSUE THREAD

**Issue by LazyRam** [bleachbit/bleachbit#1022]
Can you add a tool-tip or similar for "Explorer MRU Extras", it resets file explorer's custom folder view columns.
example custom : Name | Date last saved | Size | Date created | File version | Owner | File extension
example normal : Name | Date modified | type | size

**Comment by az0** [comment]
Thanks for your patience, as I catch up with my email inbox.

"Explorer MRU Extras" comes from Winapp2.ini (a separate project), so please submit this request through their repository here:https://github.com/MoscaDotTo/Winapp2
