### ISSUE TITLE
Free space is not de-counted after cleaning

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#1026]
Hello

I am using BleachBit v4.0.0 on Windows 10 64-bit.

I wrote a small script in .vbs that displays the total free space of my 2 hard drives, including 1 SSD (Start-up).
This script calculates the difference between a scan and the scan done just before. This allows me to know what space is released after the launch of a cleaning program.

1/ I launch my script .vbs
2/ I launch BleachBit which cleans for 32.3 MB
3/ I restart my script which calculates only a difference of 1.2 MB when this difference should be about 32.3 MB

TEST - I think my script calculates correctly because I launched the same sequence with the Privazer program and the difference is right. I also tested by deleting files for about 1 GB and the difference displayed by my script is about 1 GB.

Do you have any idea why the space freed up is not counted by Windows?

I hope you'll take a moment to respond to my request,
best regards,
Nico
N.B. Attachments to a screenshot of Bleachbit and the result of my script .vbs

![BleachBit_clean_32-3MB_OK](https://user-images.githubusercontent.com/22394276/94947557-19fa0a80-04de-11eb-97f4-a7c63eff700c.jpg)
[bleachbit_av-ap.txt](https://github.com/bleachbit/bleachbit/files/5319229/bleachbit_av-ap.txt)

**Comment by az0** [comment]
Some possibilities

1. On Windows, BleachBit calculates size of file change using the Windows API `FindFilesW`.  This is not apples to apples comparison with free space, which is measured by blocks. For example, a 1 byte file occupies a full 4KB block. When a 1B file is deleted, BleachBit reports 1B, while the OS reports that 4KB was freed. However, this is the opposite of what you're seeing.

2. When BleachBit shrinks a file by less than the block size 4KB, you will get the opposite effect as #1. BleachBit may report, for example, 4000 bytes saved, but this is less than the block size 4KB, so according to Windows, zero blocks were freed. This can happen with SQLite, JSON, and XML files. It does not happen when the BleachBit log indicates "delete."

3. A background process (e.g., Windows system log or downloading Windows updates) created new files at the same time that BleachBit was deleting other files.

4. BleachBit marked files to be deleted when the system reboots.  They aren't deleted yet, but BleachBit still counted them. In the BleachBit log, look for "marked for deletion."

Does this help?

**Comment by nico92GitHub** [comment]
Thank you for your return with this informations.

1. I know this notion of blocks as a unit of measurement and the errors/differences that this can generate.

2. I take note.

3. I know this occasional circumstance. I wrote a script (.vbs) that measures free space, before and after a deletion. There is almost always a small difference.

----->> 4. It is this condition that, in my view, is the cause of the problem that I have indicated.
However, questions come to me:
> are you sure a reboot is needed for **all files** that are marked "Mark for Deletion"?
> do you have a project to avoid this and process all deletions at the same time?

Waiting for you to come back,
Thank you for your attention,
Nico

**Comment by az0** [comment]
> However, questions come to me:
> 
> > are you sure a reboot is needed for **all files** that are marked "Mark for Deletion"?
> > do you have a project to avoid this and process all deletions at the same time?

Before Windows 10, I checked the case of Internet Explorer. If I remember correctly, it had a process explorer.exe shared with the file browser. As long as the process was running, it could not be avoided. It was possible to terminate the process, clean the file, and restart the process. However, it seemed users may not appreciated this because it was invasive. It even closed the Windows task bar.

**Comment by nico92GitHub** [comment]
Hello!
Thank you for your information.

No, I don't have any suggestions. It's beyond my skills, I'm just a user.
The problem we are talking about is just an observation that I cannot control (due to the reboot) the result.

However, I use 2 other cleaning software, "PrivaZer" and "PrivacyEraser".
I also always have the "Yale" utility which tells me in real time the total free space for all my disks. See Attachment.
![yale](https://user-images.githubusercontent.com/22394276/99141660-cc7ccb80-264d-11eb-8b87-e182c4b82356.jpg)

So, Yale therefore allows me to check before and after cleaning the disk space thus recovered. Unfortunately, Bleachbit is the only one that which does not allow me to control the freed space.
---> This is not very important, as long as you confirm to me that the indicated space is freed after reboot.

**Comment by az0** [comment]
> ---> This is not very important, as long as you confirm to me that the indicated space is freed after reboot.

Yes, files marked for deletion are deleted on reboot. By then, the file size may grow or shrink, so the size that is actually deleted may differ from the initial report. In rare cases, the file might have been deleted after the report but before a reboot, but it will still try to delete it again during the reboot.

My understanding is we cleared up how this all works, so I will close the ticket
