### ISSUE TITLE
Bleachbit console corrupt.

### ISSUE THREAD

**Issue by stan-tech48** [bleachbit/bleachbit#1028]
I just installed Bleachbit 4.0 on a Windows 10 machine (x64 version 2004 with the latest patches) and when I bring up the interface I get nothing but squares instead of characters. I've tried both the full and portable versions of the app with the same result. Attaching screen snap of console the debugger. Can anyone assist in identifying the cause of this?
![Capture](https://user-images.githubusercontent.com/72564405/95475535-4e454f00-0954-11eb-9bb7-0bd2d4cdf77b.PNG)

**Comment by Rb3rt** [comment]
[https://github.com/bleachbit/bleachbit/issues/901](url)
Try using the latest build: [https://ci.bleachbit.org/?prefix=dl/4.1.0.1730-master/](url)
![Screenshot (1)](https://user-images.githubusercontent.com/71883881/95568430-38866700-09f2-11eb-89f7-fb17646bb652.png)

**Comment by stan-tech48** [comment]
This appears to have corrected the console corruption issue. Thanks much for the timely response. Take care Rb3rt.

**Comment by az0** [comment]
Thank you both
