### ISSUE TITLE
bleachbit did not remove windows old files

### ISSUE THREAD

**Issue by liar666** [bleachbit/bleachbit#1031]
Same problem as described here:
https://www.bleachbit.org/forum/bleachbit-did-not-remove-windows-old-files

Just upgraded Win10 1909 to 2004 and ran BB => Windows.old directory is still here and takes 8Gb++

Would be great to have an option like in the 'great competitor' app :)

**Comment by az0** [comment]
Good idea. According to some quick research, a user can delete the `windows.old` folder simply after changing its permissions.

**Comment by az0** [comment]
Test BleachBit 4.4.2.2477 which will be available soon at the [BleachBit CI](https://ci.bleachbit.org/) site

**Comment by az0** [comment]
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.
