### ISSUE TITLE
My Ubuntu crashed during use of BleachBit. Issue with boot. Black screen

### ISSUE THREAD

**Issue by Slavomir9** [bleachbit/bleachbit#1033]
Hello,
I use actual Ubuntu with nevest version of Bleachbit.
I have similar issue as here
https://www.bleachbit.org/forum/bleachbit-occupies-entire-free-disk-space-after-wipe-swap-and-free-space
But during clearing all clearing options as root, it write „full HDD“, then I saw black screen, then I restart PC, but boot of PC do not work, I see black screen.
 BleachBit makes me HDD partition full
Photos from screen are here
https://drive.google.com/drive/folders/1_HjkZfxtgX6ToZPeo-qGby0dJLbQE-20?usp=sharing
Go to Ubuntu recovery mode is for me possible.
**Can you me please help it repair?**
Sorry for me english
Thank you very much for help

**Comment by az0** [comment]
Please try the solution from the FAQ

https://docs.bleachbit.org/doc/frequently-asked-questions.html

>Q: I closed BleachBit while it was working for a long time, and now my hard drive is full. How do I fix it?

>A: Run BleachBit, and clean the option System - Temporary Files. On Linux, also clean System - Cache. This will delete one or more files that are gigantic and have random filenames.

>In case you are using the command line or another application to delete these files, the default location on Linux is ~/.cache/. If it is not the same partition, /tmp/ is also used. On Windows, the default locations are %TMP%. If there are other fixed drives such as D:, they are also used.

>If you changed the default options under Preferences - Drives, look there for the large files.


You can do this from recovery mode.

**Comment by az0** [comment]
No response
