### ISSUE TITLE
Root installation directory is deleted during uninstallation

### ISSUE THREAD

**Issue by maxhaz** [bleachbit/bleachbit#1040]
I have version 4.0.0.1628, Windows 10.
I want to uninstall but if I do, it starts deleting unrelated files and folders (from the same folder as the bleachbit install folder).
That's scary (I have to kill the process to stop the deletion, I already lost many files).

What should I do to uninstall Bleachbit?

**Comment by az0** [comment]
> it starts deleting unrelated files and folders (from the same folder as the bleachbit install folder).

You mean it is deleting files and folders from `c:\program files (x86)\bleachbit` that you want to keep? Could you please provide a screenshot?

**Comment by maxhaz** [comment]
I installed bleachbit on a custom folder where I install many other software `C:\myprograms\`.

The files and folders deleted are all the files and folder from `C:\myprograms\`, starting in alphabetical order (I could kill the uninstall process while deletion reached the letter M). Deleted files and folder include `C:\myprograms\7-Zip`, `C:\myprograms\agentransack`, ``C:\myprograms\FileZilla FTP Client`, `C:\myprograms\Firefox` etc ...

I have no screenshot and I don't want to re-run the bleachbit uninstaller until I know what is going on.

Thank you for looking into this issue.

**Comment by az0** [comment]
You installed BleachBit in a sub folder like `c:\myprograms\bleachbit` or something like that, right?

When originally installed, did you choose "all users" or "only current user" option?

**Comment by maxhaz** [comment]
> You installed BleachBit in a sub folder like c:\myprograms\bleachbit or something like that, right?

yes, that's correct.

> When originally installed, did you choose "all users" or "only current user" option?

Sorry, I don't remember.

**Comment by az0** [comment]
If you do not mind the BleachBit entry staying in the control panel, you could just delete its folder `c:\myprograms\bleachbit`. The Windows installer doesn't do much more than copy files here.

Later I can look into this further.

**Comment by abitrolly** [comment]
I think that could happen if BleachBit was installed into `C:\myprograms\` without `bleach` subdir. However, I need a Windows box to test how installer works.

The recursive delete is then made by this line.
https://github.com/bleachbit/bleachbit/blob/4fb8845661ab6a726338ef4855fd75bea4d640d6/windows/bleachbit.nsi#L434

The installer could be modified to uninstall only installed files.
https://nsis.sourceforge.io/Uninstall_only_installed_files

**Comment by rados** [comment]
Hey guys, I have a Windows machine so I could trace it.

**Comment by rados** [comment]
@abitrolly, @az0 

"BleachBit was installed into C:\myprograms\ without bleach subdir" - seems like this suggestion is valid. 

I've just tested it and when I've installed the app in 'test\bleachbit' folder the removal was as expected - all objects in 'test' folder remained except the 'bleachbit' subfolder. Then I installed again the app but this time directly in 'test' folder (without 'bleachbit' subfolder) and as expected on removal the uninstaller removed all objects in 'test' folder.

So what should we do? Should we fix the installer or advice the user to use subfolders...

**Comment by az0** [comment]
@rados 

>Should we fix the installer or advice the user to use subfolders? I personally think that subfolders should be used in any case...

If it is not a large effort, how about both? 

This is not a common problem, and because it is not caused by a bug, I removed the high priority label.  I will adjust the issue title to reflect the new understanding.

**Comment by maxhaz** [comment]
Thank you all for the effort. Yes, it seems that it is what happened to me: I probably installed Bleachbit without creating a subfolder. 

At least, if the installer could automatically propose to install in the subfolder even if the user change the default install path, that would help to avoid careless mistake like mine.

Then, deleting only installed files/folders would probably be the safest solution.

**Comment by rados** [comment]
@maxhaz 
I've just implemented a fix by appending 'BleachBit' at the end of the path. If you like, you can try this build and see if the issue is solved:
https://ci.appveyor.com/api/buildjobs/7d1lf190okordbfu/artifacts/BleachBit-4.3.0.1859-setup.exe
