### ISSUE TITLE
4.1.1 in GitHub proposes 4.0.0 as new

### ISSUE THREAD

**Issue by abitrolly** [bleachbit/bleachbit#1047]
I've just got this screen when running `./bleachbit.py` from clean local checkout.

![image](https://user-images.githubusercontent.com/8781107/98657705-3302a080-2353-11eb-8d6e-c8aeaac336b4.png)

When actual version is this.

![image](https://user-images.githubusercontent.com/8781107/98657882-6d6c3d80-2353-11eb-8706-519d5e780fd6.png)

Will investigate further. It would be nice to get both versions displayed in the update dialog.

**Comment by az0** [comment]
Good catch. I added 4.1.1 to the script on the update server, so it should be fixed now. If not, please reopen.

**Comment by abitrolly** [comment]
@az0 maybe add a version comparison on a client?
