### ISSUE TITLE
why does bleachbit consume a ton of CPU resources?

### ISSUE THREAD

**Issue by dippybud400** [bleachbit/bleachbit#1050]
i just installed bleachbit into my computer and as soon i started the first system cleanup, the system was alredy slow and bleachbit started consuming a ton of CPU resources.
what's up with that?, even ccleaner and stacer do a better job without actually forcing the CPU into oblivion.
anyways...
ended up uninstalling bleach and using ccleaner instead

**Comment by az0** [comment]
Are you on Windows 10? Could you post a screenshot from the Windows Task Manager showing the list of running applications while also showing the BleachBit window to show what it was doing at the same time?

**Comment by dippybud400** [comment]
> 
> 
> Are you on Windows 10? Could you post a screenshot from the Windows Task Manager showing the list of running applications while also showing the BleachBit window to show what it was doing at the same time?

![imagen](https://user-images.githubusercontent.com/63476414/98879104-b7881880-2452-11eb-9e1b-f09b351ca551.png)
sorry if the entire thing is in spanish

**Comment by az0** [comment]
For troubleshooting, would you please also try these steps?

1. Delete or rename the folder `%appdata%\bleachbit` to reset its settings
2. Launch the [BleachBit debugging terminal](https://docs.bleachbit.org/doc/troubleshooting.html). (Alternatively, follow the steps to record the log, which you can attach here.)
3. If there is any interesting information in the terminal window that shows up, please include it as a screenshot or as copy and paste

**Comment by indig0F10w** [comment]
> i just installed bleachbit into my computer and as soon i started the first system cleanup, the system was alredy slow and bleachbit started consuming a ton of CPU resources.

In screenshot you posted BleachBit uses 1,5% CPU. Your disk drive is at 100% usage because it is cleaning free disk space and this is drawing your system to a halt.

I translated the message at top which prompts you: "Clearing free disk space. About 7 minutes remaining."

Be careful on what you select for cleaning.

This is not an issue and should be closed.

**Comment by abitrolly** [comment]
Does BleachBit do free space operation in a separate process?

**Comment by az0** [comment]
As of the current version, the only operation that uses a separate process
is the RAM cleaner for Linux. In a future release it could be useful to do
all the cleaning from a separate process.

**Comment by az0** [comment]
@indig0F10w 
Thank you for pointing that out.

@dippybud400 
Next time, uncheck under the "system" category for wiping free space. It can be extremely slow and resource intensive.
