### ISSUE TITLE
Error in 4.1.1.1770 when cleaning Firefox bookmarks

### ISSUE THREAD

**Issue by Ivan75** [bleachbit/bleachbit#1058]
The same amount of deleted data with the same error shown multiple times, shown on the first SS

The second SS shows the results after restarting the system.

![Screenshot (27)](https://user-images.githubusercontent.com/39677610/100488760-6f364f00-3110-11eb-953f-c11a0de9fd31.png)
![Screenshot (28)](https://user-images.githubusercontent.com/39677610/100488765-75c4c680-3110-11eb-9acc-5a677b3ea208.png)

**Comment by rados** [comment]
@Ivan75 May I ask you to test something, just delete your tubecast bookmark manually and try again to run Bleachbit app. 'javascript:location.href="tubecast:link="+location.href;'

Thanks.

**Comment by Ivan75** [comment]
@rados 

Thanks, I did it, it helped with firefox but some errors remained.

**Comment by az0** [comment]
@Ivan75 

Thanks for running that test. The new error seems unrelated to the Firefox bookmark problem, so let's consider that a separate issue/ticket.

Would you please run another test? Add the YouTube JavaScript bookmark that you removed earlier. Install [build 1778](https://ci.appveyor.com/project/az0/bleachbit/builds/36702913/artifacts), and clean Firefox -  URL History. The `OperationalError` message should not appear.

**Comment by Ivan75** [comment]
Thanks for replying, I can't make another test for the next few days, my PC is in repair.
Ivan

**Comment by az0** [comment]
> Thanks for replying, I can't make another test for the next few days, my PC is in repair.
@Ivan75 
I'm just following up. Did you get your PC back? I hope it's better :)
