### ISSUE TITLE
BleachBit-4.1.1.1770 Beta Error: firefox.url_history

### ISSUE THREAD

**Issue by sperglord8008s** [bleachbit/bleachbit#1059]
**Log of print out** 

Error: firefox.url_history: Function: Clean file: C:\Users\Usern\AppData\Roaming\Mozilla\Firefox\Profiles\bmso88xa.default-release-1587222501240\favicons.sqlite
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 440, in execute_sqlite3
sqlite3.OperationalError: unrecognized token: "'javascript:(function(){l=[].map.call(document.querySelectorAll("span.ytd-thumbnail-overlay-time-status-renderer"),function(e){l=e.innerHTML.trim().split(":").map(function(t){return parseInt(t)}).reduce(function(p,c){return p*60+c})"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 344, in delete_mozilla_favicons
  File "bleachbit\FileUtilities.pyo", line 448, in execute_sqlite3
sqlite3.OperationalError: unrecognized token: "'javascript:(function(){l=[].map.call(document.querySelectorAll("span.ytd-thumbnail-overlay-time-status-renderer"),function(e){l=e.innerHTML.trim().split(":").map(function(t){return parseInt(t)}).reduce(function(p,c){return p*60+c})": C:\Users\User\AppData\Roaming\Mozilla\Firefox\Profiles\bmso88xa.default-release-1587222501240\favicons.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Diagnostics Screen -** 
BleachBit version 4.1.1
Build number 1770
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.33.0
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\User\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\User\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_AU', 'cp1252')
os.getenv('APPDATA') = C:\Users\User\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\User\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\User\AppData\LocalLow
os.getenv('Music') = C:\Users\User\Music
os.getenv('USERPROFILE') = C:\Users\User
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\User\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\User
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\BleachBit.exe']
sys.executable = C:\Program Files (x86)\BleachBit\BleachBit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by az0** [comment]
@rados 
@rados 
This is another issue like https://github.com/bleachbit/bleachbit/issues/1058

@sperglord8008s 
Good bug report

It looks like you have a JavaScript bookmark for YouTube. For testing purposes, would you please delete the bookmark and clean Firefox - URL History? Does deleting the bookmark make the error go away?

**Comment by az0** [comment]
@sperglord8008s 

Ideally you could run two tests now

1. (same as my last comment) Using build 1770 that you already have, remove the JavaScript bookmark for YouTube, clean Firefox - URL History, and the `OperationalError` message should disappear.

2. Put the YouTube JavaScript bookmark back. Install [build 1778](https://ci.appveyor.com/project/az0/bleachbit/builds/36702913/artifacts), and clean Firefox -  URL History. The `OperationalError` message should disappear.

**Comment by rados** [comment]
@sperglord8008s 
I introduced a better fix for this a couple of days ago. You can check those builds if you would like:

https://ci.bleachbit.org/?prefix=dl/4.2.0.1807-master/
