### ISSUE TITLE
Bleachbit not displaying properly

### ISSUE THREAD

**Issue by alih252** [bleachbit/bleachbit#1063]
In the last couple of days, the programme is not displaying correctly - I re-installed the latest version, but it made no difference.
I have attached a screen shot - trust it can be sorted.
Thanks

Alistair Hall
![Screenshot 2020-12-07-bleachbit](https://user-images.githubusercontent.com/75635900/101388357-bca48000-38b7-11eb-904e-ad9e3e9819d5.png)

**Comment by abitrolly** [comment]
I see the fonts problem here. I am unable to give any advice for Windows, but if you paste the output of `bleachbit --sysinfo` here, it will help others to see what might be wrong.

**Comment by alih252** [comment]
Hi Abitrolly
Where do I get the output from?

**Comment by az0** [comment]
This looks like the same issue as
https://github.com/bleachbit/bleachbit/issues/967

For a fix please try version 4.1.1 beta
https://www.bleachbit.org/news/bleachbit-411-beta . This is currently the
latest release.


Andrew

**Comment by alih252** [comment]
Hi Andrew

Thanks for that – I have installed the beta, and it’s back to normal.

Regards

Alistair Hall

Sent from Mail for Windows 10
