### ISSUE TITLE
I got Swedish language

### ISSUE THREAD

**Issue by GiganteX** [bleachbit/bleachbit#1070]
I installed the latest version, downloaded 5 mins ago. Unchecked the "Translations" checkbox as I hate translations. But after installing, everything is in Swedish!

Yes, I AM Swedish, and I am IN Sweden, but that does in NO WAY imply that I want my software to talk Swedish to me. Unless I have selected Swedish specifically, do not assume and make the selection for me, please. That's rude.

Also, why do I get the Swedish translation after unchecking the Translations during installation? Surely English is default and Swedish is considered a translation?

I can find no way to switch to English after the installation.

**Comment by az0** [comment]
This looks like this other issue that was fixed: https://github.com/bleachbit/bleachbit/issues/770 . Try the fix in [BleachBit 4.1.1 beta](https://www.bleachbit.org/news/bleachbit-411-beta).

**Comment by az0** [comment]
By the way, an alternative to upgrading BleachBit is to delete the locale folder ([more detail here](https://github.com/bleachbit/bleachbit/issues/770#issuecomment-585548131)).
