### ISSUE TITLE
bleachbit issue with version 4.0 and beta 4.1

### ISSUE THREAD

**Issue by hmirakhur** [bleachbit/bleachbit#1071]
hi 

i am facing the same issue in version 4.0.0 and the latest beta and the portable version also

i hav ebeen directly using v 4.0.0 from.past 2 months perfectly with winapp2.ini but from past 2 days everything is not working properly.

i have the somewhat getting same issue as in https://www.bleachbit.org/forum/error-while-trying-start

i tried usinstalling v4 via revo uninstaller then restart the computer, then reinstall from.bleachbit website v4, but again the same isaue persists.

moreover the issue got involved in the portable version also........also in portable version i am facing issue where cleaning icons are disappearing until i drag my mouse over the cleaning section and some of the cleaners name appear but not all.

uninstalling and reinstalling not rectifying issue in both installer based and portable based version 4.

i use eset internet security and even disabling that did not work

**Comment by az0** [comment]
@hmirakhur 
So your problem is that you get a pop-up window with the error message `See the logfile 'C:\Program Files (x86)\BleachBit\bleachbit.exe.log' for details`, correct?

**Comment by hmirakhur** [comment]
system information through bleachbit

BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.31.1
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\Anil\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\Anil\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_IN', 'cp1252')
os.getenv('APPDATA') = C:\Users\Anil\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\Anil\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\Anil\AppData\LocalLow
os.getenv('Music') = C:\Users\Anil\Music
os.getenv('USERPROFILE') = C:\Users\Anil
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\Anil\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\Anil
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo





**ALSO ATTACHING SCREENSHOT OF ERROR SINCE DID NOT FOUND THE LOG FILE IN THE LOCATION STATED BY YOU
![Capture](https://user-images.githubusercontent.com/76260133/102701372-67377e00-427c-11eb-8a21-31517d364484.PNG)
![rPNG](https://user-images.githubusercontent.com/76260133/102701374-6999d800-427c-11eb-9056-cfdea20b5594.PNG)

**

**Comment by hmirakhur** [comment]
also attaching configuration files bleachbit.ini & winapp2.ini in zip
[BleachBit.zip](https://github.com/bleachbit/bleachbit/files/5720307/BleachBit.zip)

**Comment by hmirakhur** [comment]
@az0 any update !

**Comment by abitrolly** [comment]
Hi @hmirakhur. Are you concerned about the errors written in red on the screenshot? Because in initial description I see only reference to forum topic, where people complain that they can not start BleachBit at all. In your case the BleachBit it started successfully, but seems not doing what you want.

So what do you want to do?
What do you expect to happen?

**Comment by hmirakhur** [comment]
@abitrolly i am concerned about the error because on the other laptop i have same set of software installed , somewhat both laptop have same specs, but on other laptop it is cleaning all the stuffs without any error, but in this particular laptop bleachbit is not cleaning anything and showing these red errors, even after uninstalling the issue persists, the issue even persists with portable version when used instead of the installation version

**Comment by abitrolly** [comment]
@hmirakhur it would help if you can copy paste these error message into issue description. Then people with similar problems will be able to find it and add more info. Python 3.4 that is being used is quite old, but the missing part here are very first three error messages in the log.

**Comment by abitrolly** [comment]
Let's hope @hmirakhur had found the reason.

**Comment by az0** [comment]
The interesting error from the log in the screenshot was `ValueError timezone name gmt standard time not found`. It's strange this happens in `getsize()` when trying to find the size of a file.

I wonder whether the operating system or file system had a strange time zone.

In any case, the user's GitHub account was deleted, so we can't communicate anymore.
