### ISSUE TITLE
Improve startup time with solving fontconfig cache issues under Windows

### ISSUE THREAD

**Issue by rados** [bleachbit/bleachbit#1072]
This is separate ticket about generating fontconfig cache causing app to be slow on startup. It is probably related with #1013.

Some guidelines:

1. Can the caching be avoided altogether because we need only certain fonts?
2. Are there cases where fc-cache fails to cache, so it tries to cache every time the application starts?
3. Can we give the user visual feedback that caching is in progress?
4. Can we run fc-cache from the installer without causing problems for special cases such as multi-user systems and silent installation mode?

**Comment by az0** [comment]
Fixed

**Comment by rados** [comment]
Reopen the issue because of this omission in the portable application.
https://github.com/bleachbit/bleachbit/pull/1144#issuecomment-813365114

**Comment by az0** [comment]
@rados  Can this be closed because of 133f2ab7307b7ff9547d51a012dbd002e841db0c ?

**Comment by rados** [comment]
> @rados Can this be closed because of [133f2ab](https://github.com/bleachbit/bleachbit/commit/133f2ab7307b7ff9547d51a012dbd002e841db0c) ?

Yes, exactly.
