### ISSUE TITLE
On Windows context menu command not executed while the Bleachbit application is running

### ISSUE THREAD

**Issue by rados** [bleachbit/bleachbit#1073]
When the app is running and I right click over a file in Explorer and execute the context menu command "shred with bleachbit" the Bleachbit main window come to front but never executes the shred command itself.

**Comment by az0** [comment]
Related problem: user cannot select multiple files in Windows Explorer for use with "shred with BleachBit" context menu.

**Comment by q1nt** [comment]
I had the same problem after upgrading to 4.2.0 on Windows 10: clicking Shred with Bleachbit in the context menu resulted in the confirmation dialog briefly flashing followed by the program force quitting. Uninstalling and reverting to 4.0.0 fixed the problem

**Comment by az0** [comment]
I still see this problem on Windows 10 with build 1835 with commit "Fix Windows explorer context menu command and add a test for it"

**Comment by rados** [comment]
@az0 @abitrolly 
Here I suggest running a separate process (with its own GUI, etc.) in parallel only for the context menu command execution. One easy way to achieve it is by giving a special application id when Gtk.Applicaiton is initialized in GUI.py Bleachbit class:

 Gtk.Application.__init__( self, application_id='org.gnome.Bleachbit', ...)

I tried it and it worked. We need something like this because I couldn't find a way to transfer command line arguments to a running process. Maybe we can write into a file the file name of the context menu command and then read it in the running instance or use another form of inter process communication but all of these seem too complex. So just starting a second instance of the app for the short duration of the context menu command seems reasonable.

**Comment by abitrolly** [comment]
Instead of trying of here and there, I'd like to understand what's going on before I can provide any weighted opinion. I ditched Windows a few years ago, and will unable to test how it work, but I do know something about WinAPI, mutexes and stuff. What I would do is the minimal reproducible example without the weight of complete BleachBit codebase.

1. A minimal `shredbug.py` script that misbehaves the same as BleachBit
2. Helper script that adds and removes `shredbug.py` as context menu handler

At the very least the popup dialog should stay no matter what to let user understand what's going on. Add a `catch-all` exception handler that pauses and waits for keypress before terminating may help. Dumping exceptions into obligatory `%TMP%` log or precreated file may help.

**Comment by az0** [comment]
> Here I suggest running a separate process (with its own GUI, etc.) in parallel only for the context menu command execution.

This is OK and would be an improvement.

> We need something like this because I couldn't find a way to transfer command line arguments to a running process

In the future, I would like to separate the GUI from the worker process (to not lock up the GUI and as a possibly better way to escalate privileges), so IPC will be critical then.

On Linux with GTK, it seems a normal option for the IPC needed for the context menu would be to use DBus for IPC ([reference](https://stackoverflow.com/questions/62089364/how-to-send-signal-to-running-gtk-process)). I'm not familiar with DBus, especially on Windows. The [DBus page](https://www.freedesktop.org/wiki/Software/dbus/) states it works on Windows, but the [bindings on pypi](https://pypi.org/project/dbus-python/) are inactive. Windows supports named pipes for IPC. Based on a quick look, zeromq is useful, and it can send Python objects over a named pipe ([example](https://github.com/zeromq/pyzmq/blob/master/examples/gevent/simple.py)).

**Comment by unbob** [comment]
> 
> 
> I had the same problem after upgrading to 4.2.0 on Windows 10: clicking Shred with Bleachbit in the context menu resulted in the confirmation dialog briefly flashing followed by the program force quitting. Uninstalling and reverting to 4.0.0 fixed the problem

Exact same problem for me on Windows 10 Home. I also reverted to v4.0.0 which fixed the problem. Any progress on resolving this problem on the latest release?

**Comment by rados** [comment]
@unbob
It should be fixed in our latest unstable build:
https://ci.bleachbit.org/?prefix=dl/4.3.0.1872-master/

**Comment by unbob** [comment]
Thanks rados! I'll wait for the stable build. Meantime, v4.0.0 works fine for me.

**Comment by rados** [comment]
@az0 
I've found that context menu command doesn't work when we install the app only for the current user (not for all users). And I've checked that the installer doesn't write the needed entries in the registry. Is this behavior intentional? The fix seems not complex.

**Comment by az0** [comment]
> I've found that context menu command doesn't work when we install the app only for the current user (not for all users). And I've checked that the installer doesn't write the needed entries in the registry. Is this behavior intentional? The fix seems not complex.

@rados 

No, that's not intention. As you probably know, it's a matter of writing the registry key. The "for current user only" installation is often used without administrator privileges, so the user may not have access to write to HKCR. Feel free to add an issue.

**Comment by rados** [comment]
@az0 
I've decided to fix this with the simplest option - to just run a second instance. It has seemed to me that IPC options are quite an effort for this task. Once we have more reasons to adopt IPC we can improve this as well. The PR is #1165.
