### ISSUE TITLE
Uninstalled apps are still present in BleachBit.

### ISSUE THREAD

**Issue by cgcgcgcgcg** [bleachbit/bleachbit#1074]
I installed several browsers to test (Arch Linux) and I now see Epiphany, SeaMonkey, and WaterFox in Bleachbit. They are all uninstalled.
Can I manually remove them?
For example, I checked everywhere for Epiphany traces and nothing is there, so somewhere in BleachBit there must be the solution.

System information:

`BleachBit` version 4.0.0
GTK version 3.24.24
GTK theme = oomox-k17
GTK icon theme = oomox-k17
GTK prefer dark theme = False
SQLite version 3.34.0
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/k/.config/bleachbit
personal_cleaners_dir = /home/k/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = openbox
os.getenv('LOGNAME') = k
os.getenv('USER') = k
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/k
platform.linux_distribution() = ('arch', '', '')
platform.platform = Linux-5.10.3-zen1-1-zen-x86_64-with-glibc2.32
platform.version = #1 ZEN SMP PREEMPT Sun, 27 Dec 2020 12:04:22 +0000
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0]
__file__ = `/usr/share/bleachbit/Diagnostic.py``

**Comment by az0** [comment]
If you expect to not need any Epiphany files, try deleting its trace like this

`rm -rf ~/.gnome2/epiphany `~/.cache/epiphany-browser ~/.config/epiphany/ ~/.local/share/webkitgtk/localstorage`

Does this make Epiphany go away?

**Comment by cgcgcgcgcg** [comment]
> If you expect to not need any Epiphany files, try deleting its trace like this
> 
> `rm -rf ~/.gnome2/epiphany `~/.cache/epiphany-browser ~/.config/epiphany/ ~/.local/share/webkitgtk/localstorage`
> 
> Does this make Epiphany go away?

Thank you, it was the ~/.local/share/webkitgtk/localstorage part that probably caused that.
That leaves SeaMonkey and WaterFox, but I'll probably use locate to find all possible traces.

**Comment by cgcgcgcgcg** [comment]
SeaMonkey trace (I'm possibly going blind) was in ~/.mozilla/ and WaterFox in ~/.waterfox.

**Comment by az0** [comment]
OK. In case you come across something similar, check the paths in the cleaner XML files. (That's how I found that path.)

Also, https://github.com/bleachbit/wishlist/issues/7 would help with this problem

**Comment by cgcgcgcgcg** [comment]
> OK. In case you come across something similar, check the paths in the cleaner XML files. (That's how I found that path.)
> 
> Also, [bleachbit/wishlist#7](https://github.com/bleachbit/wishlist/issues/7) would help with this problem

Thank you.
