### ISSUE TITLE
Broken Link/Page not found on bleachbit.org/help

### ISSUE THREAD

**Issue by muessli** [bleachbit/bleachbit#1079]
The Link _guidelines_ does not work:
Does something seem broken? Report a bug in GitHub after reading the **[guidelines](https://github.com/bleachbit/bleachbit/blob/master/CONTRIBUTING.md)** please.

**Comment by az0** [comment]
@muessli 

Good catch! It recently moved, so I updated the location, and I will run a link checker in case there are others.

**Comment by az0** [comment]
Fixed earlier
