### ISSUE TITLE
Found an error in your 4.2 (delete_mozilla_favicons)

### ISSUE THREAD

**Issue by mo-moxi** [bleachbit/bleachbit#1082]
BB reported:

Error: firefox.url_history: Function: Clean file: /home/mem/.mozilla/firefox/wv22741z.default-esr//favicons.sqlite
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 346, in delete_mozilla_favicons
    FileUtilities.execute_sqlite3(path, None, cmds_as_list=cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 443, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.Warning: You can only execute one statement at a time.
---------------------------------------------------------------------------------------------------------------------------
Diagnostic showed :

BleachBit version 4.2.0
Git revision d929e94
GTK version 3.24.5
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.27.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/**/.config/bleachbit
personal_cleaners_dir = /home/**/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_**', 'UTF-8')
os.getenv('DESKTOP_SESSION') = gnome
os.getenv('LOGNAME') = **
os.getenv('USER') = **
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/**
platform.linux_distribution() = ('debian', '10.7', '')
platform.platform = Linux-4.19.0-13-amd64-x86_64-with-debian-10.7
platform.version = #1 SMP Debian 4.19.160-2 (2020-11-28)
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by abitrolly** [comment]
Look related to https://github.com/bleachbit/bleachbit/pull/1062

CCing @rados

**Comment by rados** [comment]
@abitrolly @az0, yes looks related. I am on it.

**Comment by rados** [comment]
@mo-moxi 
Please note that this has been fixed some time ago. You can try the fix with running from source. Let us know if you need assistance.

**Comment by az0** [comment]
@mo-moxi 
This article has  instructions on how to [run from source](https://docs.bleachbit.org/dev/running-from-source-code.html), and here is the tldr version

```
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python3 bleachbit.py
```

Once you have the requirements installed, it's quick and easy. Alternatively, you can wait for the beta release.

If you have problems with this version, please reopen the ticket.
