### ISSUE TITLE
BleachBit 4.2 doesn't work in administrator mode on Debian 10 Wayland

### ISSUE THREAD

**Issue by mo-moxi** [bleachbit/bleachbit#1084]
Thought you should know that Bleachbit 4.2 doesn't work in administrator mode on Debian 10 xWayland from the desktop icon and throw this error when run from the console:

root@asus:~# bleachbit
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(bleachbit:11850): Gdk-CRITICAL **: 16:57:27.525: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
Unable to init server: Could not connect: Connection refused

(bleachbit:11850): Gtk-WARNING **: 16:57:27.531: cannot open display: 

Profile is as previous post earlier today.

M

**Comment by az0** [comment]
Looks like https://github.com/bleachbit/bleachbit/issues/1045 . Let's keep both open as we research, fix, and confirm the fix.

**Comment by rados** [comment]
@az0 
I've verified that the application doesn't start as root but starts otherwise. I'm available to trace further.

**Comment by az0** [comment]
@rados 
Thank you

**Comment by rados** [comment]
@mo-moxi 
I've found a way to run it. It works on my machine. The article bellow describes it:

xhost si:localuser:root
sudo bleachbit

https://wiki.archlinux.org/title/Running_GUI_applications_as_root

**Comment by abitrolly** [comment]
If BB can detect the condition, it can show this way to users.

**Comment by rados** [comment]
@abitrolly @mo-moxi 
Just to warn you that this solution presents security risk:

"All of the following methods have security implications that users should be aware of. As put by Emmanuele Bassi, a GNOME developer: "there are no *real*, substantiated, technological reasons why anybody should run a GUI application as root. By running GUI applications as an admin user you are literally running millions of lines of code that have not been audited properly to run under elevated privileges; you are also running code that will touch files inside your $HOME and may change their ownership on the file system; connect, via IPC, to even more running code, etc. You are opening up a massive, gaping security hole"

**Comment by abitrolly** [comment]
@rados yes, this warning could be shown too. Although I would say that the major security risk is stealing SSH keys and private documents, and that doesn't require root access. BB does a great job by being open source, but it also need sponsors for bounty hunting programs to cover a;; possible attack vectors.
