### ISSUE TITLE
BleachBit-4.2.0-setup.exe will not work in the context menu and installation blocked by WIndows Defender

### ISSUE THREAD

**Issue by ballsar** [bleachbit/bleachbit#1086]
Installed BleachBit-4.2.0-setup.exe on Widows 10 Pro. It seemed to install correctly. I then tried to delete file using the context menu. BleachBit opened and immediately closed without the deleting file. I re-installed it and then Windows Defender blocked it. I had to override to get it to install again. Tried deleting from context menu and same reaction. When I say it opened and immediately closed, it just flashed the BleachBit start screen for a millisecond. 

I then installed 4.1.0.1723 and again got a Windows Defender block popup. Overrode it again and this version works perfectly, as it always had in the past.

**Comment by az0** [comment]
Have you tried version 4.2.0 by launching it normally using its shortcut? In other words, don't use the Windows shell integration to delete files in Explorer.

Also please try launching the [debugging terminal ](https://docs.bleachbit.org/doc/troubleshooting.html)which might have more information. If this needs more explanation, let me know.

**Comment by az0** [comment]
I am closing because no reply in a month, but feel free to re-open this issue if the problem continues

**Comment by az0** [comment]
@ballsar 
The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.
