### ISSUE TITLE
Microsoft Edge (running process cleaned) issue (4.2.0)

### ISSUE THREAD

**Issue by WildByDesign** [bleachbit/bleachbit#1090]
**Describe the bug**
On the latest stable release, 4.2.0, a new cleaner was introduced for cleaning the Chromium-based version of Microsoft Edge. The new cleaner works great, but I just noticed one possibly urgent issue. The cleaner is causing BleachBit to forcefully clean Microsoft Edge while the process is actually running which could potentially cause corruption of the profile.

**To Reproduce**
1. Ensure that Microsoft Edge is running.
2. Run the BleachBit cleaning as per normal.
3. Notice that BleachBit churns away at cleaning the profile of a running browser.

The error happens every time.

**Expected behavior**
Normally, you should get the error message _**"Microsoft Edge cannot be cleaned because it is currently running.  Close it, and try again"**_, but that is not occurring.

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit) Version 20H2
 - BleachBit version: 4.2.0

**Additional context**

**Specific Issue:** https://github.com/bleachbit/bleachbit/blob/master/cleaners/microsoft_edge.xml#L25

**Fix:** Replace **_edge.exe_** with **_msedge.exe_** (**_msedge.exe_** is the correct process name).

Cheers!

**Comment by rados** [comment]
@az0 
Just reproduced it. I can fix it.

**Comment by az0** [comment]
@WildByDesign 

Good catch. Rados fixed it. Please try the fix by downloading [build 1819 or later from the CI site](https://ci.bleachbit.org/). Alternatively, you can download the [raw XML file](https://github.com/bleachbit/bleachbit/blob/a30811491b215bc451ed11d88c547f4cfe5702e4/cleaners/microsoft_edge.xml) and replace it with the one on your system under `c:\program files (x86)\bleachbit\share\cleaners`.

**Comment by az0** [comment]
@WildByDesign 

The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.

**Comment by WildByDesign** [comment]
@az0  That fix worked. Cheers!
