### ISSUE TITLE
BleachBit 4.2.0 SHA256sum don't match websites

### ISSUE THREAD

**Issue by CyberPunkInterface** [bleachbit/bleachbit#1095]
I downloaded BleachBit 4.2.0 for Windows and then checked the SHA256sum with the website.
the website says:
>> 85699e6d5c29d2e163e775eec060a34171066968561e665907a73346590e5345  BleachBit-4.2.0-setup.exe

When checking I got 03fb4dcede9843a22f5c488de6124d80c0427d9a80c0f6e21466bd83c39ee360 SHA256

>PS C:\Users\Admin\Downloads> CertUtil -hashfile BleachBit-4.0.0-setup.exe SHA256
>SHA256 hash of BleachBit-4.0.0-setup.exe:
>03fb4dcede9843a22f5c488de6124d80c0427d9a80c0f6e21466bd83c39ee360
>CertUtil: -hashfile command completed successfully.
>PS C:\Users\Admin\Downloads> Get-filehash BleachBit-4.0.0-setup.exe
>
>Algorithm       Hash                                                                   Path
>---------       ----                                                                   ----
>SHA256          03FB4DCEDE9843A22F5C488DE6124D80C0427D9A80C0F6E21466BD83C39EE360       >C:\Users\Admin\Downloads\Blea...

They don't match?
I didn't install because of this isssue.

**Comment by abitrolly** [comment]
Because you are comparing wrong versions. :D You've downloaded 4.0.0

**Comment by CyberPunkInterface** [comment]
I really need to need to not rush things!

**Comment by az0** [comment]
Besides the SHA256 checksums, another way to verify the integrity is to check the digital signature, and it should indicate the verified publisher is Andrew Ziem.
