### ISSUE TITLE
Chrome Code and Service Worker Cache not Removed

### ISSUE THREAD

**Issue by LifeIsADeflatingVest** [bleachbit/bleachbit#1099]
**Describe the bug**
Selecting the option to clear the Chrome cache results in the Code and Service Worker Caches not being removed.

**To Reproduce**
1. Select Google Chrome > Cache in the relevant option
2. Perform the cleaning process
3. Check on file explorer (C:\Users\[UserName]\AppData\Local\Google\Chrome\User Data\Default)
4. The caches are still there (on my disk they were several GB in size).

The error happens every time.

**Expected behavior**
If the "Cache" option is selected, these caches should be removed. They **are** removed by using Chrome's native "Clear Browsing Data" option, so I see no reason why BleachBit can't do it.

**Desktop (please complete the following information):**
 - Windows 10
 - BleachBit version 4.2.0

**Comment by az0** [comment]
I tested Google Chrome 87 and latest BleachBit (just after version 4.2.0) on Ubuntu 20.10. When I ask Google Chrome to delete cache, it deletes most of Code Cache (under ~/.cache/google-chrome) except the index files, but it doesn't touch Service Worker (under ~/.config/google-chrome). BleachBit deletes both, including the index files.

On Windows 10 with Google Chrome 88, I got the same results when asking Google Chrome to delete cache. BleachBit deletes the Service Worker directory, but it doesn't touch the code cache.

This is one of the folders that BleachBit cleaned
`%userprofile%\AppData\Local\Google\Chrome\User Data\Default\Service Worker\CacheStorage`

@LifeIsADeflatingVest 
On Windows, I can reproduce only half the problem.

**Comment by az0** [comment]
I commited a fix for the Code Cache on Windows. You can either replace your `c:\program files (x86)\bleachbit\share\cleaners\google_chrome.xml` file with the [latest file](https://github.com/bleachbit/bleachbit/blob/master/cleaners/google_chrome.xml), or you can download the whole application from the [CI site](https://ci.bleachbit.org/) as version 4.2.0.1814 or later.

**Comment by LifeIsADeflatingVest** [comment]
I can't reproduce the Service Worker part anymore either, so probably there was some error on my side. I'd consider this bug closed. Thanks for the updated chrome.xml
