### ISSUE TITLE
Show and remove unavailable packages on ubuntu based distros

### ISSUE THREAD

**Issue by soredake** [bleachbit/bleachbit#1102]
**Describe the bug**
On ubuntu you can list and then remove (`apt remove`) unavailable packages using `ubuntu-security-status --unavailable` or `deborphan` command, i want similar functionality in bleachbit.

**To Reproduce**

The error happens (sometimes/every time).

**Expected behavior**
Having ability to show and delete unavailable packages.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.10
 - BleachBit version: 3.9.0

**Additional context**

**Comment by az0** [comment]
Ideally the preview and cleaning modes would list each package by name (as a separate line in the log).

**Comment by soredake** [comment]
I've lost interest in linux a long time ago.
