### ISSUE TITLE
Missing Signatures for BleachBit 4.2.0

### ISSUE THREAD

**Issue by CyberPunkInterface** [bleachbit/bleachbit#1105]
There is no detached signatures for verification of the newest version of BleachBit(4.2.0)?

>please add and update detached signatures folder on SF or on Website for BleachBit 4.2.0 <

**Comment by az0** [comment]
Good catch. I just [uploaded them](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.2.0/detached_signatures/). In case you have a problem downloading, allow a little time for them to mirror across the download servers.
