### ISSUE TITLE
poor documentation on running and var

### ISSUE THREAD

**Issue by pas-calc** [bleachbit/bleachbit#1111]
**Issue**
Both `running` and `var` are not [documented in CleanerML](https://docs.bleachbit.org/cml/cleanerml.html) language.

**Example**
the cleaner `/usr/share/bleachbit/cleaners/thunderbird.xml` uses `var` (sets a variable) and `running` (checks that a process is currently not running = the program for which it is cleaned).

**Expected behavior**
- `var` is for variable setting (that can be addressed using double dollar `$$..$$`)
- `running` checks for running programs so that the cleaner wont be executed if a match is found

**Comment by az0** [comment]
I documented the [running element and os attribute](https://github.com/bleachbit/docs/commit/246ed99f21fcb5c2e7a43b1c3407cbd6ea5068f7). The var element (multi-values variables) was already documented. From the page you referenced, see click on [variables](https://docs.bleachbit.org/cml/variables.html) and scroll down to the section called [multi-value variables](ulti-value-variables).

Better?

**Comment by pas-calc** [comment]
> Better?

Thanks, that's perfectly fine!
(even though the "multi-value variables" are explained in terms of examples , that should be understandable by means of inductive abstract thinking)
