### ISSUE TITLE
Shred with Bleachbit Option force closes before execution

### ISSUE THREAD

**Issue by dashriprock007** [bleachbit/bleachbit#1116]
When I use the option to shred a file by right-clicking....using Windows 10 latest...It FC's unless I get lucky and click the delete button before it disappears.

I have uninstalled/reinstalled etc.

Anyone else?

**Comment by az0** [comment]
This seems like these issues

https://github.com/bleachbit/bleachbit/issues/893
https://github.com/bleachbit/bleachbit/issues/993
https://github.com/bleachbit/bleachbit/issues/1086

**Comment by dashriprock007** [comment]
> This seems like these issues
> 
> #893
> #993
> #1086

Yes....so this is a work in progress?

**Comment by az0** [comment]
@dashriprock007 

Yes, a work in progress. Thank you for your patience

**Comment by KaizenLouie** [comment]
@az0 I love this product. Just wanna ask if theres any update? downloaded the latest version as of 3/25/2021, when I use the context menu when shredding, before I get to click the Ok button, it closes immediately. Using Win 10 version 2004

**Comment by az0** [comment]
@KaizenLouie 

Rados just submitted a fix for it, but I started reviewing it. If you would like early-access testing, there is a binary you can download on [AppVeyor as build 1835](https://ci.appveyor.com/project/az0/bleachbit/builds/38362048/artifacts). Soon I will take a closer look, and it's likely I will merge this code.

**Comment by KaizenLouie** [comment]
@az0 Thanks Andrew. Just tried the build 1835 and the fix worked like a charm. I guess ill stick around with this test build while theres still no official release yet.

**Comment by rados** [comment]
> @az0 Thanks Andrew. Just tried the build 1835 and the fix worked like a charm. I guess ill stick around with this test build while theres still no official release yet.

Thanks for confirming it should be safe to use this version. Just to let you know that this fix affected also the functionality of 'Shred settings and quit' so if you use this operation you might want to check it as well.

**Comment by az0** [comment]
I merged the fix, so it is available in build 4.2.0.1838 and later from the [CI build site](https://ci.bleachbit.org/). Please allow a few minutes for it to upload. If you are able to test, please add a comment here to confirm it's fixed. This fix will also be in the next beta release.

**Comment by az0** [comment]
@dashriprock007 
The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.

**Comment by az0** [comment]
@dashriprock007 
The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.
