### ISSUE TITLE
Bleachbit for Flathub?

### ISSUE THREAD

**Issue by A3E3A** [bleachbit/bleachbit#1119]
Hi just recently found out about Bleachbit and tried it out and was blown away by how good it is for system maintenance! I'm on Clear Linux was wondering if it could be submitted to Flatpak? It would be great to be able to use it in other distributions. 

[https://github.com/flathub/flathub/wiki/App-Submission](url)
Thank you guys for your time and effort.

**Comment by az0** [comment]
I'm glad you like BleachBit. Please see https://github.com/bleachbit/bleachbit/discussions/1123
