### ISSUE TITLE
Scroll bar blocking selections. Ubuntu 20.04

### ISSUE THREAD

**Issue by Trueabdrahim** [bleachbit/bleachbit#1126]
Scroll bar blocking selections. Ubuntu 20.04
![Screenshot from 2021-02-13 20-55-49](https://user-images.githubusercontent.com/79030674/107866357-eb058500-6e3d-11eb-8487-9f44eba0cf6b.png)

Cannot make selections. This occurs full screen or otherwise.

**Comment by az0** [comment]
I didn't notice this when I regularly used Ubuntu 20.04, and I don't see it now on Ubuntu 20.10. Do you have any non-default configuration regarding themes or display?

**Comment by Trueabdrahim** [comment]
Not that I am aware of. This may have been a problem in 19.1 also. It has been quite a while. It is very difficult to make any changes in the selections. This occurs on multiple machines.
________________________________

**Comment by rados** [comment]
@az0 
I can trace this further...

**Comment by rados** [comment]
![Screenshot from 2021-03-31 04-47-55](https://user-images.githubusercontent.com/332322/113078908-b3c81900-91dc-11eb-8f89-05ccf39e4db8.png)

I could imitate something similar (screenshot attached) with following this simple guide: 
https://ubuntu-mate.community/t/tweaking-your-scrollbar-settings/16161

@Trueabdrahim 
Could you try to change the style of the scroll bar in a similar way?

**Comment by az0** [comment]
@Trueabdrahim 
I am closing this because there was no reply to Rado's question since March 30. If you still have the same problem after trying his suggestion, reopen the issue.
