### ISSUE TITLE
Bleachbit (v4.2.0) not Opening or Shredding on Windows 10

### ISSUE THREAD

**Issue by gp1019** [bleachbit/bleachbit#1127]
**Describe the bug**
Attempted to open Bleachbit but there is no popup, and no sign of it working in the background processes or currently running apps in Task Manager. The shredding feature also doesn't work.

**To Reproduce**
Go to shortcut or:
1. Go to 'File explorer'
2. Click on 'C:\Program FIles(86)\Bleachbit'
3. Scroll down and click to 'bleachbit.exe'
4. Error: No popup/window

Or

1. Shred a file/folder you don't need

The error happens every time.

**Expected behavior**
Bleachbit window popping up/launched.
File/Folder should be removed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version 4.2.0

**Additional context**
Uninstalling and reinstalling didn't work. Ran as administrator to see if it worked, but it didn't. Antivirus (Windows Defender) isn't preventing it from running.

**Comment by az0** [comment]
Thanks for the bug report.

Please try this

1. Hold down the Windows key while pressing the R button. This brings up the Run dialog.
1. Type or paste the command `"%ProgramFiles(x86)%\BleachBit\bleachbit_console.exe" --gui --debug-log=%USERPROFILE%\desktop\bleachbit.log`
1. Click Run
2. Look on the desktop for `bleachbit.log` which might have useful info

As an alternative on #2, you can run it from the Windows Console or Windows Terminal. There might be information printed to the console.

If you have trouble with this procedure, let me know.

**Comment by gp1019** [comment]
Thank you for the info! Got to the log file and bleachbit console. Although, I'm not sure what information I need to look for to identify the problem. There's an error on bleachbit console that says: `ValueError: Not a boolean: ['False']` as the last line of the console if that helps. If not, I can provide a screenshot of the log and console side by side.

As for #2 (if I didn't already do this), may need some assistance.

**Comment by gp1019** [comment]
It seems to work like normal again, thanks you.
