### ISSUE TITLE
Two unit test decorators doesn't work correctly

### ISSUE THREAD

**Issue by rados** [bleachbit/bleachbit#1132]
**Describe the bug**
The two decorators skipIfWindows  and skipUnlessWindows doesn't work correctly.

**To Reproduce**
Just start unit tests under Windows and check that the decorated methods with skipUnlessWindows are not executed at all and check that the decorated with skipIfWindows are displayed with status 'ok' instead of status 'skipped...'

I already fixed this and will create a PR.

**Comment by az0** [comment]
Good catch, Rados.
