### ISSUE TITLE
Bug in new 4.2 BleachBit [sqlite.Warning when cleaning Firefox]

### ISSUE THREAD

**Issue by ancar7** [bleachbit/bleachbit#1135]
I've been using BleachBit 4.0 for some time with NO error messages, but just downloaded and installed BleachBit 4.2 and now I always get the following error message (in red), which I've never seen before installing 4.2:

![New error message in BleachBit 4 2](https://user-images.githubusercontent.com/80509928/110908652-c08bd800-82d4-11eb-8703-9a8fe1c1195c.PNG)

**Comment by rados** [comment]
@ancar7, thanks for this report. If you use Windows you can try the latest unstable build, it should contain the fix for the issue: https://ci.bleachbit.org/?prefix=dl/4.2.0.1833-master/
If you use Linux you can try running from source. Let me know if you need further assistance.

**Comment by ancar7** [comment]
@rados, thank you for your help. However, 4.2.0.1833-setup.exe triggers an immediate WS.Reputation.1 quarantine by Symantec Endpoint Protection on my Windows 10 OS and will not permit this unstable version to be installed. Until this is settled, I feel safer just re-installing Bleach-Bit 4.0.0 for now. Thanks again, Ancar7

**Comment by az0** [comment]
@ancar7 For now you can update to [BleachBit 4.2.0 (final) ](https://github.com/bleachbit/bleachbit/pull/1093)or wait for the next beta version. Beta and final versions are digitally signed, so they are less likely to trigger warnings from antivirus software.

For searching, here is the error `sqlite3.Warning: You can only execute one statement at  time`

For cross reference, I think this was the fix: https://github.com/bleachbit/bleachbit/pull/1093

**Comment by az0** [comment]
I am marking this fixed because the fit was committed, and it will be in the next beta release.

**Comment by az0** [comment]
@ancar7 
The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.
