### ISSUE TITLE
Use separate Bleachbit.ini files for unit tests.

### ISSUE THREAD

**Issue by rados** [bleachbit/bleachbit#1141]
Currently the unit tests modify the production version of the Bleachbit.ini file and this forms a kind of dependency between some of the unit tests. Also it affects the saved changes user has made on the computer that tests are executed. So we decided to split the file to two versions - one production version as it is currently in use and one test version. The idea is to have a command line option to override options_dir, which also sets the personal_cleaners_dir and affects the local copy of winapp2.ini.

**Comment by rados** [comment]
@az0 
Seems like implementing command line option is not so simple. We would need a bit of refactoring to initialize the three variables with a function call through CLI.py file. Also we would need some special way to start the unit tests. Seems like environment variable suits better in our case. Should I try it?

**Comment by az0** [comment]
That makes sense. Yes, please try the environment variable. There are
already one or two special environment variables used for unit testing


Andrew
