### ISSUE TITLE
Please add support for google chrome unstable under linux

### ISSUE THREAD

**Issue by pitsi** [bleachbit/bleachbit#1147]
**Describe the bug**
Please add support for google chrome unstable under linux.

**To Reproduce**
1. Have an existing google chrome unstable installation
2. Run bleachbit with any of the options for google chrome, e.g. `bleachbit -c google_chrome.cache`
3. Notice that nothing is cleaned

The error happens every time.

**Expected behavior**
Bleachbit should clean the stuff of google chrome unstable that lie under ~/.config/google-chrome-unstable and ~/.cache/google-chrome-unstable.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Debian testing/unstable x64
 - BleachBit version 3.9.0

**Additional context**
Adding the forementioned support is as simple as adding this line under line 34
`<value os="linux">$XDG_CONFIG_HOME/google-chrome-unstable/Default</value>`
and this one under line 54
`<action command="delete" search="walk.files" path="$XDG_CACHE_HOME/google-chrome-unstable/"/>`

Thank you in advance.

p.s. I have no idea about the paths in other operating systems.

**Comment by az0** [comment]
@pitsi 
Thank you
