### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by ashlyrclark** [bleachbit/bleachbit#1151]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

**To Reproduce**

The error happens (sometimes/every time).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]

**Additional context**

**Comment by az0** [comment]
The issue body looks like the original template, so there is no information here. If you have more information, please re-open the ticket.
