### ISSUE TITLE
windll' is not defined

### ISSUE THREAD

**Issue by teratano** [bleachbit/bleachbit#1153]
Getting an error from bleachbit.py today - from Archlinux associated w/ windll. See below.
I use  the latest since - I want to clean brave browser (not in 4.2)
I love -> Bleachbit - thx
=Don/

python bleachbit.py
Traceback (most recent call last):
  File "/home/kir/build/bleachbit/bleachbit.py", line 44, in <module>
    app = bleachbit.GUI.Bleachbit()
  File "/home/kir/build/bleachbit/bleachbit/GUI.py", line 121, in __init__
    copy_fonts_in_portable_app(auto_exit)
  File "/home/kir/build/bleachbit/bleachbit/Windows.py", line 596, in copy_fonts_in_portable_app
    windows_fonts_folder = get_known_folder_path('Fonts')
  File "/home/kir/build/bleachbit/bleachbit/Windows.py", line 419, in get_known_folder_path
    _CoTaskMemFree = windll.ole32.CoTaskMemFree
NameError: name 'windll' is not defined
====
python bleachbit.py --sysinfo
BleachBit version 4.3.0
GTK version 3.24.28
GTK theme = Adwaita-dark
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.35.5
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/yyy/.config/bleachbit
personal_cleaners_dir = /home/yyy/.config/bleachbit/cleaners
system_cleaners_dir = /home/yyy/build/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = gnome
os.getenv('LOGNAME') = yyy
os.getenv('USER') = yyy
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/yyy
platform.linux_distribution() = ('arch', '', '')
platform.platform = Linux-5.11.16-arch1-1-x86_64-with-glibc2.33
platform.version = #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000
sys.argv = ['bleachbit.py', '--sysinfo']
sys.executable = /usr/bin/python
sys.version = 3.9.3 (default, Apr  8 2021, 23:35:02) 
[GCC 10.2.0]
__file__ = /home/yyy/build/bleachbit/bleachbit/Diagnostic.py
==
python --version
Python 3.9.3

**Comment by abitrolly** [comment]
@az0 I see that we only run tests on Windows. Let me add unit testing on Linux through GitHub Actions to see if this bug manifests during tests run. Sounds good?

**Comment by az0** [comment]
What do you think of Travis?

https://travis-ci.org/github/bleachbit/bleachbit

**Comment by abitrolly** [comment]
@az0 it needs to be reenabled for this repo. I don't see it contributes to commit statuses - https://github.com/bleachbit/bleachbit/commits/master - it is definitely failing, but all checks are green.

**Comment by rados** [comment]
Yes, this line: "windows_fonts_folder = get_known_folder_path('Fonts')" should be inside the "if" bellow it. This way we will execute it only if we are in portable_mode which means we are under Windows. Should I fix it?

Thanks @teratano :)

**Comment by teratano** [comment]
I verified that - works.
Thx,

diff -Naur Windows.py Windows.py.orig
--- Windows.py 2021-04-24 13:20:41.863205368 -0500
+++ Windows.py.orig 2021-04-24 13:23:03.717092905 -0500
@@ -593,13 +593,12 @@
# Fix #1040: copy only two fonts in order to escape huge default fontconfig caching.
# We do this here only for portable app as for the installed app we do it through the installer.

- #windows_fonts_folder = get_known_folder_path('Fonts')
+ windows_fonts_folder = get_known_folder_path('Fonts')
if (
hasattr(sys, 'frozen') and
bleachbit.portable_mode and
not auto_exit
):
- windows_fonts_folder = get_known_folder_path('Fonts')
os.makedirs(_GTK_FONTS_FOLDER, exist_ok=True)
for font in [_SEGOEUI, _TAHOMA]:
gtk_font_path = os.path.join(_GTK_FONTS_FOLDER, font)

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by az0** [comment]
I noticed it was fixed in this branch https://github.com/rados/bleachbit/commit/caea4a576524076460db7a94cfcba0cd34df60f9 which is part of a bigger PR

**Comment by abitrolly** [comment]
I would prefer the fix to be independent PR, so that it won't be rollbacked together with #1146 if #1146 turns out to be problematic for the next release.

**Comment by abitrolly** [comment]
@rados can you do this?

**Comment by az0** [comment]
> I would prefer the fix to be independent PR, so that it won't be rollbacked together with #1146 if #1146 turns out to be problematic for the next release.

I cherry picked it

**Comment by abitrolly** [comment]
@az0 I gave it one more turn in #1155
