### ISSUE TITLE
Error when setting the default drives to shred.

### ISSUE THREAD

**Issue by Dilbao** [bleachbit/bleachbit#1169]
**Describe the bug**
I am getting this error when I launch the exe:

```
--- Logging error ---
Traceback (most recent call last):
Error when setting the default drives to shred.
Traceback (most recent call last):
  File "logging\__init__.pyo", line 978, in emit
  File "logging\__init__.pyo", line 828, in format
  File "logging\__init__.pyo", line 565, in format
  File "logging\__init__.pyo", line 328, in getMessage
ValueError: unsupported format character 'T' (0x54) at index 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Options.pyo", line 263, in restore
  File "bleachbit\FileUtilities.pyo", line 573, in guess_overwrite_paths
  File "logging\__init__.pyo", line 1291, in warning
  File "logging\__init__.pyo", line 1414, in _log
  File "logging\__init__.pyo", line 1424, in handle
  File "logging\__init__.pyo", line 1486, in callHandlers
  File "logging\__init__.pyo", line 853, in handle
  File "logging\__init__.pyo", line 984, in emit
  File "logging\__init__.pyo", line 906, in handleError
  File "traceback.pyo", line 170, in print_exception
  File "bleachbit\Log.pyo", line 46, in write
IndexError: string index out of range
```

**To Reproduce**
1. Download portable zip
2. Extract
3. Run bleachbit.exe

The error happens every time.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1809
 - BleachBit version 4.2.0 portable

**Additional context**
I also tried the non portable installer and I am still getting the same error.

However;
I tried previous versions. This error **_not_** occuring with v3.2.0 but I am getting the error every version after that.
This error **_not_** occuring on a Windows 10 virtual machine running on the same host device.

I need some help to track this any further.

**Comment by rados** [comment]
@az0 
I've reproduced it and I am ready to trace it further.

**Comment by rados** [comment]
@Dilbao
Thanks for finding this.

As a quick fix you can create a Temp folder as this one:
C:\Users\<current_username>\AppData\Local\Temp

Then the error should not appear. Please inform us if this doesn't help.

**Comment by Dilbao** [comment]
Thanks for the pointer. I inspected that folder and I think I know why this is happening now. If user's Temp folder is symbolic linked to a ramdisk, this error happens. But only when Preferences\Drives tab is empty.

**Steps to reproduce:**
1- Make a ramdisk (R:), create Temp folder on it (R:\Temp)
(ImDisk Toolkit is a free tool this but I tried with another similar software and problem appeared with it too)
2- Rename user's Temp folder
(ren Temp TempOld)
3- create a symlink to ramdisk's Temp folder
(mklink /D Temp R:\Temp)
4- Delete or empty bleachbit.ini
5- Run bleachbit.exe

I did not see any error if temp folder is symlink to another physical drive. It only appears with a ramdisk.

Also, if you manually add any folder to Preferences\Drives, error disappears.

This could be a very minor problem that effect very small percent of the users. But thanks a lot for the help.

**Comment by az0** [comment]
@rados 

If you see a quick/safe fix, let's do it now. Otherwise, let's target this for the next cycle.

**Comment by rados** [comment]
> @rados
> 
> If you see a quick/safe fix, let's do it now. Otherwise, let's target this for the next cycle.

I've fixed this by removing '%' symbol from the wrong place of the log warning message (and its translations). So it shouldn't throw this exception anymore (PR #1170). About handling of ram disks, I think we don't need to do anything for them as they are erased after a power loss. But there might be a situation where shredding them could be useful, but this should be a rare case...

**Comment by az0** [comment]
@rados 

Thank you for the fix. FYI: The translations have a one-way sync from Launchpad to GitHub, so later translators will need to re-translate this string. 

@Dilbao 

Thank you for the report. In a few minutes, the fixed version will upload to the [BleachBit CI site](https://ci.bleachbit.org/) as version 4.3.0.1911. Would you please test it and let us know how it works?

**Comment by Dilbao** [comment]
I just tried the v4.3.0.1911 (portable and installer) and no error so far. I can confirm that problem is fixed. Thank you so much!
