### ISSUE TITLE
Complete data is not loaded on the side nav unless minimizing a tab

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1179]
**Describe the bug**
Complete data is not shown unless the user has clicked the minimize button on any tab

**To Reproduce**

1. Open the application
2. Scroll down to the side nav
3. Minimize any tab
4. Scroll down to the side nav

The error happens every time.

**Expected behavior**
It should show complete data on the side nav 

**Screenshots**
http://recordit.co/uRq0WBCVoL

**Desktop**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
Thank you. Your video is helpful to demonstrate, and I attached the video here in case recordit.co maybe would delete it later

https://user-images.githubusercontent.com/933680/122628576-085c9100-d074-11eb-999a-2b7483d7698f.mp4

**Comment by abitrolly** [comment]
That's a weird behavior. Nice catch.
