### ISSUE TITLE
Make file via make chaff function not working properly if number of files value is low

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1181]
**Describe the bug**
If the number of files is low then the function does not create files. An example is if the value is 25 nothing happens upon completing.

**To Reproduce**
1. Open the application
2. Click BleachBit Icon on the top right
3. Select Make Chaff
4. Change number of files
5. Click Make Files

The error happens every time

**Expected behavior**
Prevent users to input below the minimum value. The value would not go lower than the required value.

**Screenshots**
http://recordit.co/znoW3NflIl

**Desktop**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**
I suggest preventing users to input below the required value

**Comment by az0** [comment]
My guess is that the process in BleachBit happens so far that the file browser doesn't have time to show it, but I will take a closer look. 

It may help to enable debug logging in the BleachBit preferences, and then start BleachBit with the console (`bleachbit_console.exe`).

**Comment by az0** [comment]
The files are created and destroyed more quickly than Windows File Explorer can show. One way to see it is by choosing the option in BleachBit to not delete the files
