### ISSUE TITLE
Website text on About BleachBit is not clickable

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1182]
**Describe the bug**
The website text looks like a link but is not clickable.  This should be clickable and would open up to the website page.

**To Reproduce**

1. Open the application
2. Click BleachBit Icon on the top right
3. Select About BleachBit
4. Click Website text

The error happens every time.

**Expected behavior**
The link should be clickable and would open up to the about BleachBit on the website.

**Screenshots**
http://recordit.co/pCU35tefM6

**Desktop**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
Your screen recording makes sense. It looks like a hyperlink, so it should be clickable.

On Ubuntu 20.10 with git revision 3b0b1cd054d00672623a015fdbfff681c4cc1663 (just after 4.3.0 beta) the same hyperlink works, so maybe it's a Windows problem

@banaagravrommel Did you use the BleachBit installer or portable mode?

**Comment by banaagravrommel** [comment]
I used BleachBit installer.

**Comment by abitrolly** [comment]
This should have been fixed in https://github.com/bleachbit/bleachbit/pull/952 but 

@banaagravrommel do you run BB as an administrator?

**Comment by banaagravrommel** [comment]
Yes, I did.

**Comment by abitrolly** [comment]
@banaagravrommel if it doesn't repeat when you run BB as ordinary user, then the title should be changed to reflect that.

**Comment by banaagravrommel** [comment]
@abitrolly I checked it just now and it's working fine for both users.

**Comment by abitrolly** [comment]
@banaagravrommel do you mean that nothing had changed and it worked all of the sudden?

**Comment by banaagravrommel** [comment]
Yep, I tried just earlier and it worked perfectly. That's weird I haven't
done anything but it is working now.

**Comment by az0** [comment]
@banaagravrommel 
Thank you for letting us know, and now I am closing this issue.
