### ISSUE TITLE
Add title for help menu popup

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1188]
**Describe the bug**
There is no title on help menu

**To Reproduce**

1. Open the application
2. Click BleachBit Icon on the top right
3. Select Help

The error happens every time.

**Expected behavior**
A title should be present on help menu popup

**Screenshots**
https://ibb.co/X8Bw5VF

**Desktop (please complete the following information):**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
OK, this makes sense.

I uploaded your imagine in case ibb.co later deletes it

![github_1188_missing_title](https://user-images.githubusercontent.com/933680/122653603-de05e480-d102-11eb-95cb-e4071090715a.png)

**Comment by az0** [comment]
Fixed in 87aeb26dab9bc41985418ff903071029e2dbd725
