### ISSUE TITLE
Title name inconsistenc on Diagnostics menu

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1189]
**Describe the bug**
Menu name is "Diagnostics" and title bar name is "Systems information" it would be better to be consistent. I suggest using the Systems Information instead

**To Reproduce**

1. Open the application
2. Click BleachBit Icon on the top right
3. Select Diagnostics

The error happens every time.

**Expected behavior**
The title name should be consistent.

**Screenshots**
![m2](https://user-images.githubusercontent.com/51908980/122656342-2ddcbe00-d18c-11eb-94d6-e19b82b58bca.PNG)

**Desktop**
OS: Windows 10
BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
This makes sense. Good catch. In the future, please attach screenshot to GitHub using drag and drop onto the text area where you type your comment.

**Comment by banaagravrommel** [comment]
Okay got it

**Comment by abitrolly** [comment]
Pasting screens from clipboard into edit form works too.

**Comment by az0** [comment]
> Pasting screens from clipboard into edit form works too.

@abitrolly 
You mean it is not read only?

**Comment by abitrolly** [comment]
![image](https://user-images.githubusercontent.com/8781107/122684986-8a35f100-d211-11eb-9c6e-10ea1899bd27.png)

I mean you can do Ctrl+Shift+PrtScr and then Ctrl+V directly into issue comment.

**Comment by az0** [comment]
> I mean you can do Ctrl+Shift+PrtScr and then Ctrl+V directly into issue comment.

Nice!
