### ISSUE TITLE
Mac OSx  Support - Enhancement

### ISSUE THREAD

**Issue by brahmastra2016** [bleachbit/bleachbit#119]
Love to see Mac OSX Support.

i started working on it but love to see more people helping me with the effort , i am beginner python coder
so it might be over ambitious project.

**Comment by tiemay** [comment]
Related [necropost](https://www.bleachbit.org/forum/porting-bleachbit-mac-os-x)

**Comment by brahmastra2016** [comment]
it is exactly same as below bug on Linux and same workaround works too.

https://bugs.launchpad.net/bleachbit/+bug/1464299

Workaround : 
Disable "Overwrite files to hide contents".

**Comment by az0** [comment]
Was comment 3 meant for issue #120 ?

Regarding comment 1, would you plan to use PyGTK on Mac OS X?

**Comment by brahmastra2016** [comment]
Yes i have started working on it using PyGTK , let see how far can i take it :)

**Comment by az0** [comment]
To make it easier to review and merge, I suggest proceeding in stages: stage 1 is getting the console to work and pass unit tests. Stage 2 is the GUI. Stage 3 is an installer package. 

Besides breaking things up like this, it will also help me merge your changes if you include unit tests that pass on Mac for stage 1.

Also, I would appreciate not introducing any dependencies or major changes to the Linux and Windows versions, but if impacts are needed, please let me know.

Thank you, brahmastra2016

**Comment by bschumacher** [comment]
Saw the clothes, loved it. Will help with Mac OS X support.

**Comment by az0** [comment]
@bschumacher Your help is appreciated!

**Comment by tstenner** [comment]
Maybe you should start with the GTK3 port directly, if you need any help (that I don't need a mac for) I'll be glad to help

**Comment by brahmastra2016** [comment]
coming back from hibernation :)
again i will start working on this project.

**Comment by ROCKNROLLKID** [comment]
That's good to hear. I wish you luck.

**Comment by brahmastra2016** [comment]
GTK seem to have stop working on OSX 10.10.5 (Yosemite) , even simple hello.py does not show any windows.

import pygtk
pygtk.require('2.0')
import gtk

class Base:
    def __init__(self):
        self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.show()

    def main(self):
        gtk.main()

print __name__
if __name__ == "__main__":
    base = Base()
    base.main()

Spent couple of day but still cant figure out what is going on. 

Any suggestion ?

**Comment by az0** [comment]
That hello world does not show any Windows on Ubuntu either. How about this?
http://pygtk.org/pygtk2tutorial/examples/helloworld.py

**Comment by brahmastra2016** [comment]
That too does not work.

**Comment by bschumacher** [comment]
PyQT would work a bit better probably.

**Comment by bschumacher** [comment]
or https://docs.python.org/2.7/library/tkinter.html#module-Tkinter should just work without any setup.

**Comment by bschumacher** [comment]
There's also https://pythonhosted.org/pyobjc/

**Comment by brahmastra2016** [comment]
figured it out that i was doing something really silly.my second monitor was connected and active i was under impression i have disconnected it and for some reason python windows was showing up on that monitor.

silly me.

**Comment by MattHardcastle** [comment]
@brahmastra2016 have you made any progress with GTK? I got Bleachbit running under it but the style wasn't native. By default It looked like a Linux app ported to macOS. What do you think about rewriting the UI in pyobjc for Mac? pyobjc is a bridge to Foundation and the rest of macOS's native API so it will look and feel like a native macOS app. It will, of course, mean rewriting all the UI code.

**Comment by brahmastra2016** [comment]
i agree with you the look and feel is not of native macosx but I did not
really spent any time in changing the UI , but we could surely work on it.

**Comment by tstenner** [comment]
@MattHardcastle Did you test the GTK 2 version or the newer GTK 3 version?

**Comment by brahmastra2016** [comment]
I am been using pygtk 2.24

**Comment by tstenner** [comment]
@brahmastra2016 Could you try the branch at https://github.com/tstenner/bleachbit/tree/modernization2016 ?

**Comment by az0** [comment]
This branch has active GTK 3 development
https://github.com/bleachbit/bleachbit/tree/gtk3

**Comment by kdeldycke** [comment]
FYI, I'm trying to package BleachBit for brew at: https://github.com/Homebrew/homebrew-core/pull/56538

**Comment by NaderDroid** [comment]
Hi, I believe I was able to locate the package in brew before, but not anymore. Was it removed from brew or something going on with my machine?

**Comment by CouldBeThis** [comment]
Hello,

I think your website should be updated to indicate this package is no longer available on brew, for example this page: https://www.bleachbit.org/download/mac

Sorry I do not have anything more helpful to contribute than that!

**Comment by az0** [comment]
> I think your website should be updated to indicate this package is no longer available on brew, for example this page: https://www.bleachbit.org/download/mac

OK, I added a note
