### ISSUE TITLE
Add manual update button in "About BleachBit" popup

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1190]
**Describe the bug**
There is no manual update button on the application. This would be ideal in the future as sometimes automatic updates do not work properly and if users want to update the application instantly.

**To Reproduce**

1. Open the application
2. Click BleachBit Icon on the top right
3. Select About BleachBit

The error happens every time.

**Expected behavior**
There should be a manual update function in the application.

**Screenshots**
https://ibb.co/cv3LcD0

**Desktop**

- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
BleachBit has automatic notification of updates, but this opens a web browser for the user to manually download and install, so it seems this isn't necessary.

**Comment by banaagravrommel** [comment]
Okay sure
