### ISSUE TITLE
Improve process flow on preference menu

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1191]
**Describe the bug**
Currently, every change saves automatically. The process should be different, there should be a save button, default button, and reset button.

**To Reproduce**

1. Open the application
2. Click BleachBit Icon on the top right
3. Select Preference
4. Change any setting

**Expected behavior**
The process is much more optimized with data not saving automatically and has new functionalities namely the save button, reset button, and default button.
**Screenshots**
https://ibb.co/vXwQrvf

**Desktop**
- OS: Windows 10
- BleachBit version 4.3.0

**Additional context**

**Comment by az0** [comment]
In the GNOME Human Interface Guidelines the preferences [dialog ](https://developer.gnome.org/hig/stable/dialogs.html.en)is a presentation dialog, and it gives this guidance

>Presentation dialogs are either instant or explicit apply. In instant apply dialogs, changes to settings or values are immediately updated. In contrast, explicit apply dialogs include a button for applying changes.

> Instant apply should be used wherever possible. Instant apply presentation dialogs have a close button in their header bar, like a primary window.

BleachBit doesn't fully support macOSX, but as a "second opinion" from a company known for good user design, here is what Apple recommends for [preference dialogs](https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/preferences/)

>Apply preference changes immediately. Users expect preference changes to take effect as soon as they’re changed.

**Comment by rados** [comment]
@az0 
I agree with the immediately apply style but I liked the option to reset to defaults. 'Shred settings and Quit' menu command is not obvious way for resetting the preferences...
