### ISSUE TITLE
Add Cleaning support for additional web browsers

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#1198]
Hello Team,

I have shared below the link which has installers for web browser (both online and standalone installer). These web browser have been searched from filehorse.com and then the setup files have been downloaded from the original developer websites. The web browser may feature beta, developer, canary as well as stable build of same web browser. Kindly release cleaning support for the undetected browser. 

Web browser collection (latest builds only) : https://drive.google.com/file/d/1Wxv8LK6VpQWYJEetwX9JGljtflwd__fZ/view?usp=sharing

Thanks for the support

**Comment by az0** [comment]
Link is a multi-gigabyte file---This is not helpful. Also, the user rkher95 is now a ghost, so closing
