### ISSUE TITLE
Release v4.4 not marked as latest on GitHub

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#1200]
Just FYI, even though v4.4 has been officially released, it's not marked as the latest release on GitHub.

**Comment by az0** [comment]
Thank you. I fixed it https://github.com/bleachbit/bleachbit/releases/tag/v4.4.0

**Comment by Gitoffthelawn** [comment]
@az0 You're welcome!  Thanks for the thanks.  Thanks for fixing it.  Thanks for new version! :) :) :)
