### ISSUE TITLE
v4.4.0 - Scrolls to wrong section when previewing via context menu

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#1201]
**Describe the bug**
Scrolls to wrong section when previewing via context menu.

**To Reproduce**
1. Scroll down in the left pane.
2. Right-click on any item.
3. Click the preview menuitem.
4. Repeat steps 1-3 as needed.
5. Notice that the left pane scrolls unexpectedly.

The error happens every time.

**Expected behavior**
Left pane to not scroll except when directed by user.

**Desktop (please complete the following information):**
 - OS: Win7
 - BleachBit version 4.4.0

**Comment by az0** [comment]
Thank you for the bug report. Yes, I observe that the left pane unexpectedly scrolls to the top when following your procedure. I am on Ubuntu 20.10 with BleachBit 4.4.0.

**Comment by Gitoffthelawn** [comment]
You're welcome, and thanks for the thanks.  AFAIK, it's likely a regression with 4.4.0, but that is from my memory, and not formal comparative testing.

**Comment by rados** [comment]
@az0
I've reproduced the bug. Seems related with #1203 & #1179 so I can take this one as well.

**Comment by az0** [comment]
I tested the fix from Rados on Ubuntu 20.10 and Windows 10 21H1, and this is fixed.

@Gitoffthelawn 
Would you also please give it a test? Try [build 1946](https://ci.bleachbit.org/?prefix=dl/4.4.1.1946-master/) or newer at the [CI build site](https://ci.bleachbit.org/).

**Comment by OmarNamis** [comment]
@az0 I tested on Windows 10 20H2 and I can confirm it's fixed.

**Comment by az0** [comment]
> I can confirm it's fixed.

Thank you for testing, @OmarNamis

**Comment by OmarNamis** [comment]
I just tested the latest beta, everything is still working fine.

**Comment by az0** [comment]
> I just tested the latest beta, everything is still working fine.

That's reassuring. Good to hear, @OmarNamis

**Comment by Gitoffthelawn** [comment]
I tested BleachBit 4.4.1 beta on Win7 for this issue, and it now WFM.  Thanks.

**Comment by az0** [comment]
> I tested BleachBit 4.4.1 beta on Win7 for this issue, and it now WFM. Thanks.

Thank you for confirming, @Gitoffthelawn
