### ISSUE TITLE
Scrollbar broken on release 4.4

### ISSUE THREAD

**Issue by Olaf987** [bleachbit/bleachbit#1203]
Dear all:

For me Bleachbit 4.4.0 is working quite well except that I now have an annoying bug in the interface. The scrollbar that allows you to scroll the settings in the left pane up or down is not working. The scroll drag thingy is not present. You can only get to the to other parts of the setting by clicking an item and then using the arrow keys. This does not break the tool, but it is rather annoying.

I have so far tried this on 2 computers, both with windows 10 21H1.

**Comment by abitrolly** [comment]
I can confirm this on Linux with latest source as well.

![Screenshot from 2021-06-28 13-30-23](https://user-images.githubusercontent.com/8781107/123622556-07b2c000-d815-11eb-9556-64a1ee4ba307.png)

Looks like duplicate for https://github.com/bleachbit/bleachbit/issues/1179 and if it doesn't repeat with 4.2 then the regression is likely caused by https://github.com/bleachbit/bleachbit/commit/d8c33f873845de00dd50033d60509fe0bacd73b0

**Comment by Martii** [comment]
@abitrolly 

Would you please try collapsing one or more of the down arrows... mine just freed up and scrolling works again. Not sure if I can reproduce this... but it's worth a shot.

**Comment by abitrolly** [comment]
@Martii yes, collapsing arrows helps as well as scrolling with arrow keys.

**Comment by Martii** [comment]
@abitrolly 

Thanks. Weird GTK bug.

**Comment by abitrolly** [comment]
@Martii just a wild guess that padding box that is added at https://github.com/bleachbit/bleachbit/commit/d8c33f873845de00dd50033d60509fe0bacd73b0 is not updated to the correct size why element is initialized.

**Comment by Martii** [comment]
@abitrolly 

Possibly... but even if you resize the window the event isn't translated to that `Box`. I'm curious if #1034 will rebreak. I've never seen that particular issue but I'm also under KDE... might be some slight difference with this WM. \*shrugs\*.

**Comment by Olaf987** [comment]
> 
> 
> @abitrolly
> 
> Would you please try collapsing one or more of the down arrows... mine just freed up and scrolling works again. Not sure if I can reproduce this... but it's worth a shot.

I can confirm that opening and closing a few arrows restores the slider thingy in the scrollbar on windows 10 21H1

**Comment by francoism90** [comment]
A workaround is toggling `Hide irrelevant cleaners`  in Preferences and click Close (Linux/GNOME.

The scrollbar on the cleaning log seems to work fine for me.

**Comment by m0lz** [comment]
Can confirm, also on Win 10 21H1 OS Build 19043.1081
Middle mouse wheel does not work but using keyboard cursor keys as a workaround does.

**Comment by az0** [comment]
Sorry for this regrettable bug. We'll fix this ASAP. 

Until then, I documented the problem and your helpful workarounds in the[ known issues](https://www.bleachbit.org/news/bleachbit-440#known_issues) section of the release notes.

**Comment by az0** [comment]
This happens also on Ubuntu 20.10 with GNOME. Because it's not Windows specific, I will edit the title of this issue.

**Comment by rados** [comment]
@az0 
I can take this one.

**Comment by sunshinecorp** [comment]
I confirm this on LMDE 4 (Debian 10 based).

**Comment by az0** [comment]
This was fixed in https://github.com/bleachbit/bleachbit/pull/1208 , thanks to Rados. For Linux users, it is fairly easy to test by [running from source ](https://docs.bleachbit.org/dev/running-from-source-code.html) in Git.

```
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
python3 bleachbit.py
```

If you are on Windows, get the latest build from the [BleachBit CI site](https://ci.bleachbit.org/).

If you are able to please test, please post a comment here with your results.

**Comment by Len1069** [comment]
Same issue with Windows 10 21H1 19043.1110 
The up and down arrows work but the mouse doesnt work.

**Comment by m0lz** [comment]
@az0

Just tried ..

BleachBit-4.4.1.1982-setup-English.exe (Build from the CI Site),

on Windows 10 21H1 19043.1151

Scrolling with the mouse is fixed 👍

**Comment by Len1069** [comment]
OK. Where do you download the 4.4.1.1982 file from?
The latest I found was 4.4.1.1976 and that was in the Unstable builds of Bleachbit for Windows.

**Comment by az0** [comment]
@Len1069 
Use this link https://ci.bleachbit.org/?prefix=dl/4.4.1.1982-master/

If you don't see it try refreshing the page, or make sure that JavaScript isn't blocked in the browser

**Comment by az0** [comment]
> I have tested this with 4.4.1 beta. The bug seems to be fixed. Both on Windows and Linux Mint Mate.

Thank you for the diligent testing, @Olaf987 . Great to hear.

**Comment by m0lz** [comment]
I also tested with the newer 4.4.1 beta, no issues on windows 10 home, 21H1, OS build 19043.1348

**Comment by az0** [comment]
> I also tested with the newer 4.4.1 beta, no issues on windows 10 home, 21H1, OS build 19043.1348

Thank you for testing, @m0lz !
