### ISSUE TITLE
The program [fonts] turns to garbage

### ISSUE THREAD

**Issue by chandy89830** [bleachbit/bleachbit#1214]
When it is installed on Win 7, whatever language I choose, The program just dispaly in garbage

**Comment by rados** [comment]
@chandy89830 
Thanks for reporting this. If you can try the following it might help. Set Windows display language in English, remove Bleachbit, restart computer, install Bleachibit.

**Comment by XhmikosR** [comment]
Not sure if it's the same issue, but I was wondering if there's any way to skip the automatic language detection apart from deleting the Bleachbit locale files? I hate it that it defaults to the OS locale and there's no way to change the language through the UI :/

**Comment by elslobbo** [comment]
Hello, I am on Win10Pro 21H1 build 19043.1083, Japanese display, and everything appears in Unicode-ish blocks, like this. アクセスが拒否されました actually displays as per the attached screenshot. Note that I could copy the blocks and paste them here and they displayed correctly.
![image](https://user-images.githubusercontent.com/87376448/125462179-726e9a09-cded-44ef-b075-9e82fd99223c.png)

**Comment by rados** [comment]
@elslobbo 
You can fix this by copying a Japanese font in "Program Files (x86)\Bleachbit\share\fonts" folder.

**Comment by az0** [comment]
I added this to the release notes for BleachBit version 4.4.0 as a notable [known issue](https://www.bleachbit.org/news/bleachbit-440#known_issues).

**Comment by az0** [comment]
> Not sure if it's the same issue, but I was wondering if there's any way to skip the automatic language detection apart from deleting the Bleachbit locale files? I hate it that it defaults to the OS locale and there's no way to change the language through the UI :/

No, there's no way to choose the language in the BleachBit preferences or through the command line as an option.

BleachBit uses the standard gettext system for localization, so besides deleting the locale directory, you could try setting Windows environment variables. For example (not tested)

`set LANG=en_US.UTF-8`

Windows also has a GUI configuration to set environment variables globally.

**Comment by elslobbo** [comment]
Thank you. I confirm that copying a local language font to the share folder fixes the issue.

**Comment by az0** [comment]
> Thank you. I confirm that copying a local language font to the share folder fixes the issue.

Thank you for letting us know. Would you let me please know the name of the font file? Is this the same font file that you think other users with Windows set to Japanase would use ? (For example, is it a standard font that comes with Windows.)

**Comment by elslobbo** [comment]
Meiryo works nicely, and is standard issue on Windows. So if your installer can copy that over, it should work. Alternately MS Gothic and MS Mincho are used by everyone and should be on all machines.
