### ISSUE TITLE
Garbled characters appear on BleachBit 4.4.0 Japanese

### ISSUE THREAD

**Issue by duke1203** [bleachbit/bleachbit#1216]
![image](https://user-images.githubusercontent.com/87215495/125149063-d7e2b100-e160-11eb-997a-919a70cb1dc6.png)
Who can help me?

**Comment by rados** [comment]
@duke1203 
Thanks for reporting this issue. Most probably it is because we introduced some optimizations and missed to add support for all possible languages. You should be able to fix it with setting the display language to English and restart the application. Or you can copy a font from Windows\Fonts dir to Bleachbit\share\fonts dir a font that supports your language setting. We are in the process of fixing this and thanks again for your support.

**Comment by az0** [comment]
@duke1203
Are you using Microsoft Windows set to simplify Chinese? Are you using the
portable or installed version?

**Comment by elslobbo** [comment]
I confirm that the fix of copying the font works.

**Comment by az0** [comment]
@elslobbo 
I made a fix for Simplified Chinese, Traditional Chinese, and Japanese for BleachBit whether installed or in portable mode. Would you please be willing to test? The instructions are here: https://github.com/bleachbit/bleachbit/issues/1207#issuecomment-883870262

After testing, please reply in your original issue here (#1216) with information on whether it helped, and let me know which language you use.

**Comment by az0** [comment]
I saw in another issue https://github.com/bleachbit/bleachbit/issues/1214#issuecomment-879099107 that you are using Win10Pro 21H1 build 19043.1083 with Japanese, so I am making a note here for reference

**Comment by abitrolly** [comment]
Interesting if it is possible to detect missing glyphs in gettext / Gtk before rendering? This may help to search for system fonts at runtime.

**Comment by elslobbo** [comment]
Hello, I tried with BleachBit-4.4.1.1973-setup.exe, using the default selection of Japanese, and it does not work. I checked the shared fonts and they are just segoeui and tahoma.
<img width="368" alt="2021-07-21_22-24-56" src="https://user-images.githubusercontent.com/87376448/126496716-1e1435dc-a3f4-4f1a-8a83-60043f972cf5.png">

**Comment by rados** [comment]
@elslobbo @az0 
Just created a PR that fixes the Japanese font.

**Comment by az0** [comment]
@elslobbo 
That is good information. Thank you for testing.

@elslobbo @duke1203 
[Build 1975](https://ci.bleachbit.org/?prefix=dl/4.4.1.1975-master/) has a better fix in the Windows installer from Rados for Japanese fonts. This is better than build 1973.

**Comment by elslobbo** [comment]
@rados @az0 
I installed BleachBit-4.4.1.1975-setup.exe and ran the installer on default, and I confirm that the display is correct now, in Japanese. Thank you!
