### ISSUE TITLE
Nightly version of Firefox and Brave are not detected in 4.4.0

### ISSUE THREAD

**Issue by Rtizer-9** [bleachbit/bleachbit#1231]
I've the nightly version of Brave and Firefox installed which are not getting detected in version 4.4.0's application list. Please make the appropriate changes.

**Comment by az0** [comment]
@Rtizer-9 

Are you on Linux or Windows? 

For Firefox, please use the [Mozillazine KB](https://kb.mozillazine.org/Profile_folder_-_Firefox) to find the location of the folder, and please write it here. Feel free to mask your username.

For Brave, visit the special URL `chrome://version/`, look for the line labeled "Profile Path," and please include that here too.

**Comment by Rtizer-9** [comment]
I just rechecked on version 4.4.2 and yes both of them are detected and getting cleaned as expected. I'll close the issue for now and reopen incase it's needed. Thanks

PS : I'm on Linux.
