### ISSUE TITLE
Linux Ubuntu 20.04: Snap Firefox not found on 4.4.0

### ISSUE THREAD

**Issue by Lazorne** [bleachbit/bleachbit#1237]
OS: Ubuntu 20.04 Budgie
BleachBit version 4.4.0

Problem:
Firefox is not found when installed as a snap 

Installed with sudo snap install firefox. 
No additional PPA's where used and is configured in distro default

**Comment by az0** [comment]
Commit 4f0dee513 added support for cleaning Firefox as a snap. To test, download the raw [firefox.xml ](https://raw.githubusercontent.com/bleachbit/bleachbit/master/cleaners/firefox.xml) file, and replace it with the file already on your system.

If you are not sure where to put it, 

1. Open BleachBit
2. Click the hamburger menu
3. Click System Information
4. Find the line starting *system_cleaners_dir*

**Comment by az0** [comment]
@Lazorne  

It would be helpful if you could please test. (See comment from January 2). Add comment here to confirm.

As is, I will assume it is fixed, but if not, please reopen this issue.
