### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Vicantropo** [bleachbit/bleachbit#1238]
BleachBit doesn't work when right clickling in the archive to be deleting and using the option "shared with bleachbit", just to notice this option work fine before in other versions.
![Captura de pantalla 2021-07-30 171950](https://user-images.githubusercontent.com/63147055/127718098-b0ac8ebc-a70e-4b0f-aa4b-85febae84912.jpg)
![Captura de pantalla 2021-07-30 173324](https://user-images.githubusercontent.com/63147055/127718099-b46100e9-f525-4471-9386-527fe24a8060.jpg)

**Comment by az0** [comment]
@Vicantropo  

Thank you for the bug here. I have a few questions to help understand the situation.

1. Which version of BleachBit?
1. When you launch BleachBit using "shred with BleachBit," do you next see the Windows User Account Control (UAC) dialog that asks you for permission? 
2. If so, do you grant permission?
3. Have you made any changes to your Windows registry or setting related to the UAC system?

This issue may be related to https://github.com/bleachbit/bleachbit/issues/1227

**Comment by Vicantropo** [comment]
> 
> 
> @Vicantropo
> 
> Thank you for the bug here. I have a few questions to help understand the situation.
> 
>     1. Which version of BleachBit?
> 
>     2. When you launch BleachBit using "shred with BleachBit," do you next see the Windows User Account Control (UAC) dialog that asks you for permission?
> 
>     3. If so, do you grant permission?
> 
>     4. Have you made any changes to your Windows registry or setting related to the UAC system?
> 
> 
> This issue may be related to #1227

R1: The latest one 4.4.0
![Captura de pantalla 2021-07-30 175738](https://user-images.githubusercontent.com/63147055/127720825-0b7ba7be-cb85-46e4-b860-d522f8fa6875.jpg)
![Captura de pantalla 2021-07-30 182728](https://user-images.githubusercontent.com/63147055/127720835-ab7a72c0-5457-4520-a744-66c90801e7cd.jpg)
![Captura de pantalla 2021-07-30 182759](https://user-images.githubusercontent.com/63147055/127720842-11f29bf7-12ff-420f-be21-ff35902ec4fe.jpg)

R2: YES

R3: yes i do, if i don't grant permission, the program doensn't open
![IMG_20210730_181113809](https://user-images.githubusercontent.com/63147055/127720787-755f9e40-314f-4ab9-a1ce-1f9064d5a8bf.jpg)

R4: I have not, i'm very carefully with make changes in the registry, as a mention before, with lder versions i haven't had this problem, i can bleach archives and folders, but i need to star the program (giving the  Windows UAC permissions) and do it by the menu.

**Comment by Vicantropo** [comment]
Maybe this probably can help, i have 2 screenshot:

1.- Right click "shred with Bleachbit", the error i found is like the route is like duplicates
![Captura de pantalla 2021-07-31 021937 RE](https://user-images.githubusercontent.com/63147055/127732446-7ee97fbb-7aee-404d-9856-bc9aa5470769.jpg)

at the end the error is " the system cannot found the specific route"


2.- Shred via the program menu, the route is correct and the shredded works ok:
![Captura de pantalla 2021-07-31 022135 REOK](https://user-images.githubusercontent.com/63147055/127732475-2985a2c5-d2ca-4c57-bba7-21c7c25798bf.jpg)
![Captura de pantalla 2021-07-31 022247 REOKSHD](https://user-images.githubusercontent.com/63147055/127732484-80d563d1-4b26-4b0d-85e0-c97f6ee83230.jpg)

**Comment by rados** [comment]
@az0 
I am on it.

**Comment by rados** [comment]
@Vicantropo 
If you like, you can try the following. In this registry key just change the triple quotes to single quotes, i.e.:

Computer\HKEY_CLASSES_ROOT\AllFilesystemObjects\shell\shred.bleachbit\command

 from this

... --gui --shred --exit """%1"""

it becomes:

... --gui --shred --exit "%1"

It would be really helpful, thanks in advance.

**Comment by Vicantropo** [comment]
> 
> 
> @Vicantropo
> If you like, you can try the following. In this registry key just change the triple quotes to single quotes, i.e.:
> 
> Computer\HKEY_CLASSES_ROOT\AllFilesystemObjects\shell\shred.bleachbit\command
> 
> from this
> 
> ... --gui --shred --exit """%1"""
> 
> it becomes:
> 
> ... --gui --shred --exit "%1"
> 
> It would be really helpful, thanks in advance.

It works!!! Thanks 😎🤘🤓🧐👾👍
