### ISSUE TITLE
安装中文版打开出现乱码

### ISSUE THREAD

**Issue by n1ckzhao** [bleachbit/bleachbit#1242]
**Describe the bug**
encode

The error happens every time

**Expected behavior**
中文版打开出现乱码

**Desktop (please complete the following information):**
 - OS:Windows 10
 - BleachBit version 4.4.0

**Comment by moxuanyuan** [comment]
the same

**Comment by rados** [comment]
@moxuanyuan @n1ckzhao 
Thanks for reporting this. Basically there are two quick solutions to the problem:

- You can manually copy msyh.ttc and msyhbd.ttc from Windows\Fonts folder to the <install dir>\Bleachbit\share\fonts folder and restart the application. 

- You can use the latest build that contains exactly the same fix. It is here: https://ci.bleachbit.org/?prefix=dl/4.4.1.1976-master/

**Comment by n1ckzhao** [comment]
it works.
