### ISSUE TITLE
[Windows] Do not create "Uninstall" shortcut in Start Menu 

### ISSUE THREAD

**Issue by craigacgomez** [bleachbit/bleachbit#1244]
**Describe the bug**
The "Uninstall" shortcut in the Windows Start Menu is very redundant and quite unnecessary since Windows has had a centralised place to uninstall all apps. 

In fact, the Microsoft UI fundamentals documentation specifically states that this should be avoided ("Do not place shortcuts to documents, help or uninstall in the Start menu")
https://docs.microsoft.com/en-us/previous-versions/ms954377(v=msdn.10)?redirectedfrom=MSDN

**To Reproduce**
1. Install BleachBit (Windows)
2. Open Windows Start Menu
3. Expand the BleachBit folder
4. Notice the "Uninstall" shortcut

**Expected behavior**
No uninstall shortcut is created in the Windows Start Menu.

**Desktop:**
 - OS: Windows 10
 - BleachBit 4.4.0

**Additional context**
N/A

**Comment by az0** [comment]
That was well articulated, Craig. Thank you. I also removed the hyperlink, as suggested by the documentation.

**Comment by craigacgomez** [comment]
> I encourage you to test this fix in [BleachBit 4.4.1 beta](https://www.bleachbit.org/news/bleachbit-441-beta). If it works, please post a comment here to confirm. If it does not work, let's take another look.

Works as expected! Cheers for the fix/update

**Comment by az0** [comment]
> Works as expected! Cheers for the fix/update
@craigacgomez 
Thank you for confirming
