### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by Sly-McNasty** [bleachbit/bleachbit#1245]
Is there a stable, unbuggy version of BleachBit released?  I just installed 4.4.0 and it has issues.  Is there an earlier version without issues?  If so, where do I get it?

**Comment by az0** [comment]
Yes, see the  [known issues](https://www.bleachbit.org/news/bleachbit-440#known_issues) section of the release notes for a link to the [old versions](https://www.bleachbit.org/download/old).
