### ISSUE TITLE
Exclusion in winapp2.ini not honoured

### ISSUE THREAD

**Issue by livingentity** [bleachbit/bleachbit#1247]
**Describe the bug**
An excluded file in winapp2.ini is still deleted.

**To Reproduce**
1. Look at Firefox/Mozilla, Updates. It has `FileKey1=%CommonAppData%\Mozilla\updates|*.*|RECURSE` but also `ExcludeKey1=FILE|%CommonAppData%\Mozilla\updates\*\|update-config.json`.
2. The file gets deleted when cleaning. 

The error happens every time.

**Expected behavior**
The file should not be deleted.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version 4.4.1

**Comment by rados** [comment]
@az0 
I can trace this one.

**Comment by livingentity** [comment]
Fixed in PR [#1249](https://github.com/bleachbit/bleachbit/pull/1249).

**Comment by az0** [comment]
Normally we wait to close the issue until the PR is merged, so I will reopen it for now. 

Thank you for working on this, livingentity. 

Now the change needs some review. Ideally you would add a new unit test (in `tests/TestWinapp.py`) such that it fails without the PR and passes with the new code. You can run the tests for this module by running `python3 -m unittest tests.TestWinapp` from the project's root directory. The test makes it easier to review.

**Comment by livingentity** [comment]
I'm _not_ a programmer. I don't know about python or github either.
I just sat there, searched the project for 'ExcludeKey', found the right place and went through it line by line while looking up things in a python manual until I found the bug. Then I iteratively tried to find a fix which caused all this mess of a commit.

I would much prefer that someone with programming knowledge takes it from here.
(The actual issue is just that the very last backslash in `ExcludeKey1=FILE|%CommonAppData%\Mozilla\updates\*\|update-config.json`  is optional, so both cases, with or without it, need to be taken into account.)

PS: I reopen it because az0 wanted to do it but actually didn't.

**Comment by rados** [comment]
@livingentity 
For non programmer you are pretty good. :)

**Comment by livingentity** [comment]
Thanks again rados, I'm trying.

**Comment by az0** [comment]
> I'm not a programmer. I don't know about python or github either.

Python uses duck typing: "If it walks like a duck, and it quacks like a duck, then it must be a duck.”  By this logic, if someone writes programs, then he is a programmer. 

> For non programmer you are pretty good. :)

I agree!
