### ISSUE TITLE
[Windows 10] [4.4.0] Cleaner list doesn't scroll all the way down using mouse wheel

### ISSUE THREAD

**Issue by willbprog127** [bleachbit/bleachbit#1253]
**Describe the bug**
When running Bleachbit 4.4.0 on Windows 10 v21H1 64-bit, the cleaner list doesn't scroll all the way down when using the mouse wheel.

**To Reproduce**
* Start Bleachbit
* Position mouse over cleaner list on the left
* Attempt to scroll all the way down to the bottom of the list of cleaners
* Cleaner list only scrolls a very small amount, not reaching the bottom

This happens every time.

**Expected behavior**
The cleaner list should scroll all the way to the bottom when using the mouse wheel, like in v4.2.0.

**Desktop**
 - OS: Windows 10 v21H1 64-bit
 - BleachBit version 4.4.0

**Additional context**
Version 4.2.0 worked properly in this regard, so the issue only started with v4.4.0.  If you click an item in the cleaner list then try to scroll with the mouse wheel, it still fails.  If you click an item in the cleaner list and use the 'down arrow' or 'page down' on the keyboard, it _does_ scroll the list.

**Comment by az0** [comment]
Sorry about the problem. Please see the known issues section of the release
notes

https://www.bleachbit.org/news/bleachbit-440#known_issues

Andrew

**Comment by willbprog127** [comment]
> Sorry about the problem. Please see the known issues section of the release notes https://www.bleachbit.org/news/bleachbit-440#known_issues Andrew

@az0 Thanks for the response.  I thought I looked at that before, but maybe it was a while ago.  Sorry for the repeat issue.  Will close.

**Comment by willbprog127** [comment]
Also, I did do a search through the github issues system and nothing relevant came up.  Please forgive the noise.  Thanks :smiley:

**Comment by az0** [comment]
>@az0 Thanks for the response. I thought I looked at that before, but maybe it was a while ago. Sorry for the repeat issue. Will close.

No worries. Sorry about this annoying bug. 

>Also, I did do a search through the github issues system and nothing relevant came up. Please forgive the noise. Thanks smiley

By default, it defaults to open issues, so you may not have seen it because it was closed or because of the particular keywords. If nothing else, another issue makes it easier for the next person to find.
