### ISSUE TITLE
WinError 3 

### ISSUE THREAD

**Issue by i0629** [bleachbit/bleachbit#1273]
I recently downloaded and ran bleachbit and chose multiple boxes in the "System" section including "Free Disk Space." However, an error message appeared which read:

[WinError 3] The system cannot find the path specified: 'D': Function: Overwrite free disk space D:\

Does this mean that my free disk space could not be overwrote?
![bleachbiterror](https://user-images.githubusercontent.com/90865260/133666904-603f4c2b-5fc7-4cbf-9b71-5b61140b8be1.PNG)

**Comment by rados** [comment]
@i0629 
Seems like you have D drive but the app cannot access it. Probably there is something not so typical about the D drive. If you could share what is written under [list/shred_drives] section in C:\Users\username\AppData\Roaming\Bleachbit\Bleachbit.ini file might help.

**Comment by az0** [comment]
@i0629 
A simple solution that might fix this is this
1. Open BleachBit
2. Click the application icon (logo in the top left) to open the application menu
3. Click the "shred settings and quit" option
4. Restart BleachBit
5. Try again

Whether that works or not, please post a follow-up comment here to let me know. Then we'll go from there

**Comment by cwade585** [comment]
> @i0629 A simple solution that might fix this is this
> 
> 1. Open BleachBit
> 2. Click the application icon (logo in the top left) to open the application menu
> 3. Click the "shred settings and quit" option
> 4. Restart BleachBit
> 5. Try again
> 
> Whether that works or not, please post a follow-up comment here to let me know. Then we'll go from there

I tried this and it worked for me! Thanks.

**Comment by az0** [comment]
@cwade585 
Thank you for confirming.

I made a code change so the error message is clearer.

**Comment by az0** [comment]
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.
