### ISSUE TITLE
Quick Filter in Thunderbird auto-enabling itself

### ISSUE THREAD

**Issue by eleius** [bleachbit/bleachbit#1276]
Every time I use Bleachbit 4.4, I find the Quick Filter button enabled in Thunderbird (latest version, Arch Linux) the next time I run the program. I guess something changed recently in TB as it never happened before. All checkboxes are enabled in Bleachbit for TB except for "Passwords".

**Comment by bryce-lynch** [comment]
Bleachbit deletes session.json, inside there's a "quickFilter" key that stores its current status. No session.json = filter enabled (by default)
