### ISSUE TITLE
SyntaxWarning: "is not" with a l iteral. Did you mean "!="?

### ISSUE THREAD

**Issue by maravento** [bleachbit/bleachbit#1277]
**version**
```
BleachBit version 3.9.0
Ubuntu 20.04.3 LTS
```

**install**
```
sudo apt install bleachbit
```

**Describe the bug**
```
Configurando bleachbit (3.9.0-1) ...
/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a l
iteral. Did you mean "!="?
  if msgctxt is not None and msgctxt is not "":
```

**Comment by az0** [comment]
This was fixed in [BleachBit 4.2.0](https://www.bleachbit.org/news/bleachbit-420) released January 2021. Ubuntu has a "no rolling release" policy, so it does not upgrade BleachBit. Instead, I recommend you always get the latest version from www.bleachbit.org/download . Now the latest is 4.4.0
