### ISSUE TITLE
Scroll bar disappears and hard to reappear once user clicks on the right side of the modal

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1285]
**Describe the bug**
Scroll button disappears when the user clicks on the right modal and from some cases when the user hovers on the scrollbar it does not appear

**To Reproduce**
1. Open the app
2. Click on the right side of the modal
3. Click the scroll bar or hover into it

The error happens every time

**Expected behavior**
The scroll bar should not disappear and it should appear once the user hovers into the scroll bar section.

**Screenshots**
https://user-images.githubusercontent.com/51908980/139386917-615485b1-e522-4fe4-b069-6e66d10cd9d7.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10, Ubuntu 20.04]
 - BleachBit version [4.4.1]

**Additional context**
Test the usability of it, the user should be able to scroll properly even doing any actions like clicking on the right side of the modal.

**Comment by az0** [comment]
This seems like GTK's "overlay scrollbars. The site linuxuprising.com explains it as

>the scrollbars are hidden by default, being partially shown when the pointer is moved, and being completely visible only when placing the mouse near the scrollbar.

Basically, it auto-hides, but it scrolling should always work.

Does this fit the description of what you see?

**Comment by az0** [comment]
This was fixed in build 4.4.1.2135 by disabling the GTK overlay scrollbar feature.

@banaagravrommel 
Would you please test? It's available on the [CI build ](https://ci.bleachbit.org/ )site.

**Comment by rados** [comment]
Just noticed that after the fix we have a kind of a second parallel line on the left of the scroll bar which as tick as the scroll bar line. Probably we should consider an improvement.

![image](https://user-images.githubusercontent.com/332322/147856247-42bbec48-94ee-4279-b3ca-8a7c14368ea9.png)
