### ISSUE TITLE
Language is not showing up in the preference section in Windows

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1286]
**Describe the bug**
Language is not showing up in the preference section in Windows 10. 

**To Reproduce**
1. Open the app
2. Click the menu button
3. Click preference

The error happens every time

**Expected behavior**
The language tab should show up in the preference modal

**Screenshots**
https://user-images.githubusercontent.com/51908980/139387940-c6ef09e9-03c3-414b-b32c-8f914c148de9.mp4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - BleachBit version [4.4.1]

**Additional context**
None

**Comment by az0** [comment]
@banaagravrommel 
Interesting bug report.

On Windows, please try two things

1. Drag the corner of the preferences dialog to expand it, in case the tab is hiding
2. In the first tab of preferences, enable debug logging. Then start bleachbit_console.exe to look for any error messages that might explain this

**Comment by banaagravrommel** [comment]
@az0 Tried those 2 things still not appearing on my end. Is it showing up on your side?

https://user-images.githubusercontent.com/51908980/139530867-3de0bd3e-37d1-43c9-94ae-c3b58a3ea4e8.mp4

**Comment by az0** [comment]
Ahh, this feature is not supported on Windows, so it makes sense the tab is missing. It corresponds with the Locations option under the System category, so that should be missing on Windows too.

On Linux, they are an advanced sort of "localepurge," but localization on Windows is usually very different.

**Comment by az0** [comment]
P.S., for future troubleshooting the `bleachbit_console.exe` can help. I didn't see it in the recording. It is like a "DOS" or "terminal" window separate from the normal GUI.

To start it, look for the shortcut called "BleachBit debugging terminal" or run the separate exe. It sometimes has more log information.
