### ISSUE TITLE
add psutil to the deb/rpm package requirements.

### ISSUE THREAD

**Issue by banaagravrommel** [bleachbit/bleachbit#1296]
**Describe the bug**
On Ubuntu (20.04.3) when I try to free up space it says that "To get the file system type from the given path, you need to install psutil package" can we automate this scenario.

**To Reproduce**
1. Click the menu
2. Click Wipe Free Space
3. Select a folder

The error happens every time on my end.

**Expected behavior**
An error message will not appear as psutil package is installed in the package requirements

**Screenshots**
https://user-images.githubusercontent.com/51908980/140720929-02492f01-b659-4b5a-a5bf-2fcec088f3d7.mp4

**Desktop**
Ubuntu (20.04.3) 

**Additional context**

**Comment by samueltuyizere** [comment]
I am getting the same error on Elementary OS 7,also I can't launch bleachbit as root.
