### ISSUE TITLE
False Positive Report

### ISSUE THREAD

**Issue by erfan132** [bleachbit/bleachbit#1308]
hi my application  after protect with vmprotect got detected by k7gw 
Hash: Instapair.exe(c56265ad90df9e443a390a9d4353b4cee46cf5eacb16476d17d9905e95abbe1b)

InstaPairConsole.exe(73e75cbff12ddccc429a194f84a2c0ef8c8fe89da91ac092a62474b68da5635c)

Filename : instapair.exe,instapairconsole.exe

VirusTotal Link (Optional): https://www.virustotal.com/gui/file/73e75cbff12ddccc429a194f84a2c0ef8c8fe89da91ac092a62474b68da5635c/detection

https://www.virustotal.com/gui/file/c56265ad90df9e443a390a9d4353b4cee46cf5eacb16476d17d9905e95abbe1b/detection
Signer (Optional):my program after protection with vmprotect got detected as virus

**Comment by abitrolly** [comment]
@erfan132 I am pretty sure you've reported it to the wrong tracker. This tracker is for BleachBit,

**Comment by erfan132** [comment]
Rights :) sorry
