### ISSUE TITLE
Security threat detected by Norton 360?

### ISSUE THREAD

**Issue by Starburster** [bleachbit/bleachbit#1309]
Hi there!

Usually I don't post about security threats and/or malware on formus and bulletin boards, I usually contact the creators/adminstrators in order to avoid unnecessary virus scares and give them a chance to act and mitigate. But there is no such choice so here we go:

I'm not sure it's a bug but my Norton 360 removed your update file BleachBit-4.4.2-setup.exe after detecting a threat in the installation file:

File name: BleachBit-4.4.2-setup.exe
Detected threat: WS.Reputation.1
C:\Users\admin\Downloads\BleachBit-4.4.2-setup.exe
Threat type: Insight - network threat. There are several indications that this file is unreliable and therefore not secure.

Thought you might like to know.
Starburster

**Comment by az0** [comment]
Did you download this file from www.bleachbit.org or another source? 

Do you know how to calculate the file hash or check the digital signature? These can be used to verify its authenticity (i.e., that it is not a fake and was not tampered with). If you like, I can give you instructions.

The site VirusTotal.com [scanned this file](https://www.virustotal.com/gui/file/5e1e6e2e269216a8c40ab1dbba26b1b7d53f1f9f106cb94abbe7a4d1f38eb460) with 63 scanners and found it safe.

**Comment by az0** [comment]
> And no, I don't know how to calculate the file hash but I would really like to know how to do that. The digital signature is checked automatically I think, but every other way to be absolutely sure of what you are downloading and from were would be very helpful, too.

The digital signature is a great way to verify the integrity. Basically you will see the authorized publisher with my name ([example screenshot](https://docs.bleachbit.org/doc/install-on-windows.html)).

After that, calculating the hash is redundant, but here's how to do it

1. Look up the hashes for the latest release. Example: [BleachBit 4.4.2](https://sourceforge.net/projects/bleachbit/files/bleachbit/4.4.2/bleachbit-4.4.2-sha256sum.txt.asc/view)

2. Use a utility to calculate the **sha 512** hash of the file you have. (This is not equivalent to md5, sha256, or other hashes.) There are many tools. to do this. Here's [one guide](https://www.nextofwindows.com/5-ways-to-generate-and-verify-md5-sha-checksum-of-any-file-in-windows-10).

3. Verify the hashes match

Either way will give you confidence you have the original file.


> By the way: Thank you for an excellent and very useful application. Every now and then and when I can spare the money I throw some 5$ your way for charma, so keep up the good work!

Thank you for the compliment and for the donation!
