### ISSUE TITLE
[Minor question] Missing release for version 4.4.2 ?

### ISSUE THREAD

**Issue by gizmecano** [bleachbit/bleachbit#1328]
It seems that the version 4.4.2 was not considered as a [distinct release](https://github.com/bleachbit/bleachbit/releases) on this repository, even if [the tag has been created](https://github.com/bleachbit/bleachbit/releases/tag/v4.4.2) and [the changelog has been updated](https://www.bleachbit.org/news/bleachbit-442): is there a particular reason for that?

(I noticed that the version 4.4.1 was missing previously, but as this version [was mentionned as a beta release](https://www.bleachbit.org/news/bleachbit-441-beta) and not a final one, it wasn't specifically unexpected).

**Comment by abitrolly** [comment]
I couldn't find the description of the release process to say if there was a missing step. The process might need a change if we want the front page of repository to say that 4.4.2 is the latest release. Right now the block says this.

![image](https://user-images.githubusercontent.com/8781107/147662540-fec73809-7b27-4407-a66e-f38e570fe20a.png)

**Comment by az0** [comment]
The release page is not commonly used, but I updated it now https://github.com/bleachbit/bleachbit/releases/tag/v4.4.2

**Comment by gizmecano** [comment]
> The release page is not commonly used, but I updated it now

Thank you for this clarification. I understand that release features are not commonly used: maybe [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) ([launched some months ago](https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/)) can help on this point.
