### ISSUE TITLE
Latest version fails to install on Windows 11

### ISSUE THREAD

**Issue by tastyminerals** [bleachbit/bleachbit#1332]
**Describe the bug**
Fail to install the latest version on Windows 11

**To Reproduce**
Run the Windows installer.

The error happens (sometimes/every time).

**Expected behavior**
The app gets installed.

**Screenshots**
<img width="387" alt="Screenshot 2022-01-07 125441" src="https://user-images.githubusercontent.com/7676160/148540675-cfcfcdb3-10b2-4166-943b-a7f1289758e6.png">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - BleachBit version: 4.4.2

**Additional context**

**Comment by tastyminerals** [comment]
Closing, the previous version was running instead. It appears that it takes quite some time for it to start on Windows. It would be nice to optimize the startup time...

**Comment by abitrolly** [comment]
@tastyminerals the startup time should be better for a new version - https://github.com/bleachbit/bleachbit/issues/1072

In any case BleachBit should not be slow on the second start once the font cache is built.
