### ISSUE TITLE
Rounded corners to match Windows 11

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#1339]
![UX 1](https://user-images.githubusercontent.com/87981739/150644229-320eb092-e258-4458-a569-e827b38d4b0c.png)

As you see in the picture above the app has sharp rectangular corners in Windows. If you are a Windows 11 user, it will be uncomfortable if you get used to rounded corners in other applications.

So, It would be great to have rounded corners and if @az0 (Maintainer) of the Blechbit if you feel you want some uniformity across Windows 10 and 11. I suggest you to add an option for enabling those rounded corners in preferences and not to push this thing out to the Stable channel by default.

**Comment by abitrolly** [comment]
@Loki-L1130 can you find other GTK 3 apps that have rounded corners on Windows? BleachBit uses https://pygobject.readthedocs.io/en/latest/ which is Python interface for GTK, and it is GTK who draws all that rounded stuff.

**Comment by Loki-L1130** [comment]
@abitrolly I am not sure of what you are saying, Could you explain it a bit more in Detail.

**Comment by abitrolly** [comment]
@Loki-L1130 yea, https://en.wikipedia.org/wiki/GTK is a library that BleachBit uses to draw User Interface - windows with buttons you can click, widgets, etc.

**Comment by Loki-L1130** [comment]
So, You mean. Making rounded corners depends on GTK ?

**Comment by abitrolly** [comment]
Right. GTK draws them.

**Comment by az0** [comment]
I agree it depends on GTK or the GTK theme. 

The user who requested this was deleted from GitHub (now "ghost"). So far there is not much demand for this enhancement, which does not change the function, so I will close this. Other users are welcome to comment.
