### ISSUE TITLE
A possible bug? [false positive with AVAST]

### ISSUE THREAD

**Issue by 1938tony** [bleachbit/bleachbit#1340]
I run Windows 10.  I have both AVAST and Bleachbit 4.4.2 on my system.  Both have worked happily for years together.  Today AVAST blocked Bleachbit noting: "libgio-2.0-0.dll  Blocked".  "Infected with IDP Generic" .  I have tried re-installing Bleachbit, but I get the same result.  I am no computer 'wizz kid' (I come in the 'Oldie' bracket!) but I just thought  that someone should know that this has happened and, other than by using GitHub, there doesn't seem to be a simple way of reporting this type of problem. 

1938tony

**Comment by az0** [comment]
Are you still seeing this issue? It looks like a problem called a false positive where an antivirus program marks a file as bad even though it's safe.  I uploaded that file from the same version (BleachBit 4.4.2) to virustotal, and it was found safe by all 67 virus scanners from all major vendors. Here is the report: https://www.virustotal.com/gui/file/6348f0d8b3c4f7d039813adb6961670f6e2b311b36a7e87e76c18c98d345bf4d

Sometimes the false positive does not last long, and it goes away by itself. In other cases, either the user (you) or the developer (me) reports the problem to the antivirus vendor (AVAST) to resolve the problem.
