### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by BYTEMEE1** [bleachbit/bleachbit#1341]
Although I'm sure somebody has asked this question, I've done a quick, non-exhaustive. search and not found an answer: can anybody show me a quick XML example of how to add searching for and deleting file wild cards with Bleachbit, assuming the files are, say in the path: D:\MYPROGRAMS\*.tmp and where would I put the resulting xml file?

**Comment by az0** [comment]
Where to start for learning CleanerML https://docs.bleachbit.org/cml/cleanerml.html

Place the file in the cleaners directory. The location is documented in the _storage_ section in the link above.

The command you want is a glob like this

https://github.com/bleachbit/bleachbit/blob/404ad468ff419137c254f13982bb2c8f631510ca/doc/example_cleaner.xml#L74

You might start by copying a simple cleaner such as [adobe_reader.xml](https://github.com/bleachbit/bleachbit/blob/master/cleaners/adobe_reader.xml). Make sure to change the main label and id.
