### ISSUE TITLE
bleachbit gets stuck at start image on windows 2019

### ISSUE THREAD

**Issue by Fantu** [bleachbit/bleachbit#1345]
**Describe the bug**
Bleachbit gets stuck at start image on windows 2019, I waited also some minutes and after I had to terminate it from task manager to close it.
After tried also another time with same result.

**Desktop (please complete the following information):**
 - OS: Windows 2019 build 17763.2366
 - BleachBit version 4.4.2

If you need more information tell me and I'll post them.
Thanks for any reply and sorry for my bad english.

**Comment by rados** [comment]
@Fantu, Thanks for this report. Can you place a screenshot?

**Comment by Fantu** [comment]
@rados thanks for reply, for now I uninstalled it to avoid terminal users try to start it, anyway there was only starting image and no warning/error or other useful information (otherwise I had already taken the screenshot)

**Comment by rados** [comment]
@Fantu, Sometimes it is need to wait a bit more (like 5 or 10 mins) in order for the app to build the font cache. It happens only on the very first run.

**Comment by Fantu** [comment]
@rados thanks for reply, I saw fc-cache.exe blocked for some minutes on install and I terminate it manually, I suggest to add atleast "a warning" that can take many minutes (I saw no output in cmd window and thinked that was an "enexpected case")
reinstalled, waited more minutes on fc-cache.exe, install finished withut do nothing and now start correctly

**Comment by rados** [comment]
@Fantu, nice to hear that. The issue is a tough one. I agree the app should be more informative. Thank you and happy cleaning. ;)

**Comment by az0** [comment]
In the Windows installer, I clarified the message

Old

>The next step is building font cache, during which you may see a black window for one minute.

New

> The next step is building font cache, during which you may see a black window.
> It usually finishes in one minute, but sometimes it takes ten minutes.
