### ISSUE TITLE
Paid version in Microsoft Store?

### ISSUE THREAD

**Issue by mirronake** [bleachbit/bleachbit#1346]
![image](https://user-images.githubusercontent.com/96698262/156862927-a26e4b68-8308-40ef-8a82-84b6794b12b3.png)
https://www.microsoft.com/store/productId/9N8XKNHZSB5M

**Comment by az0** [comment]
That's _not_ the official version, and I never heard of mscware.

In general, the [GNU GPL license allows, and even encourages, selling software](https://www.gnu.org/philosophy/selling.en.html) under certain conditions. It's certainly another thing if the software has been tampered with or contains malicious code. (I have seen shady sites advertising "BleachBIt Keygen + full crack.") I don't suppose you used this app on the Windows store? Of course anyone who spends a moment searching can find the official BleachBit site with a free download.

**Comment by abitrolly** [comment]
They should at least distribute the source code or else it is a violation of GPL.

**Comment by az0** [comment]
Someone want to ask mscware for the source code and see what happens? Their executables are different from the official versions (www.bleachbit.org), but I am not sure by how much.

**Comment by catalin560** [comment]
sadly it isn't the only software that suffers from this: https://odysee.com/@AlphaNerd:8/don't-pay-for-free-software-(donate-to:e

I've done my part and reported the app and I encourage you to do the same, maybe if we make enough noise then the lizard people at Microsoft will act on it...

**Comment by az0** [comment]
Related article: [Will Microsoft Ban Commercial Open Source from Its App Store?](https://news.slashdot.org/story/22/07/09/0247213/will-microsoft-ban-commercial-open-source-from-its-app-store)

>A few weeks ago, Microsoft quietly [updated its Microsoft [app] Store Policies](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies-change-history), adding [new policies](https://web.archive.org/web/20220702074228/https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies) (which go into effect next week), that include this text:

>all pricing ... must ... [n]ot attempt to profit from open-source or other software that is otherwise generally available for free [meaning, in price, not freedom].
