### ISSUE TITLE
internet explorer not cleaning due to:

### ISSUE THREAD

**Issue by papafenrir** [bleachbit/bleachbit#1347]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

**To Reproduce**

The error happens (sometimes/every time).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]

**Additional context**

**Comment by papafenrir** [comment]
Run external command: taskkill.exe /f /IM explorer.exe 0B 
Run external command: C:\Windows\explorer.exe C:\Windows\explorer.exe 0B 

at the moment 17.6 Mb of cache remain

**Comment by az0** [comment]
>Run external command: taskkill.exe /f /IM explorer.exe 0B
Run external command: C:\Windows\explorer.exe C:\Windows\explorer.exe 0B

In the comment you wrote `taskkill.exe /f /IM explorer.exe 0B` which refers to Windows Explorer, but in the title you wrote, Internet Explorer. Please confirm which one you mean.

>at the moment 17.6 Mb of cache remain

Would you please post a screenshot? If you copy it to your clipboard, then position the cursor in your reply, and  just press CTRL+V . It will paste the image in your reply. Or, you can attach a file.

**Comment by papafenrir** [comment]
Delete 307B C:\Users\papaf\Local Settings\Temporary Internet Files\IE\IUMST1SS\Windows[1].json
Delete 0B C:\Users\papaf\Local Settings\Temporary Internet Files\IE\IUMST1SS
Delete 0B C:\Users\papaf\Local Settings\Temporary Internet Files\IE\container.dat
Delete 0B C:\Users\papaf\Local Settings\Temporary Internet Files\Content.IE5
Delete 0B C:\Users\papaf\Local Settings\Temporary Internet Files\IE
Delete 8.2kB C:\Users\papaf\AppData\Local\Microsoft\Windows\WebCache\V01.chk
Mark for deletion 524.3kB C:\Users\papaf\AppData\Local\Microsoft\Windows\WebCache\V01.log
Mark for deletion 524.3kB C:\Users\papaf\AppData\Local\Microsoft\Windows\WebCache\V01tmp.log
Mark for deletion 26.7MB C:\Users\papaf\AppData\Local\Microsoft\Windows\WebCache\WebCacheV01.dat
Mark for deletion 16.4kB C:\Users\papaf\AppData\Local\Microsoft\Windows\WebCache\WebCacheV01.jfm
Delete 0B C:\Users\papaf\Cookies\ESE\container.dat
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\databases\Databases.db
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\History
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Favicons
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Local State
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Preferences
Vacuum 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\History
Vacuum 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Vacuum 0B C:\Users\papaf\AppData\Local\Microsoft\Edge\User Data\Default\databases\Databases.db
Clipboard 0B 
Mark for deletion 0B C:\Windows\Debug\PASSWD.LOG
Delete 5kB C:\Windows\Prefetch\CONHOST.EXE-0C6456FB.pf
Delete 7.7kB C:\Windows\Prefetch\DLLHOST.EXE-4B6CB38A.pf
Delete 58.8kB C:\Windows\Prefetch\EXPLORER.EXE-D5E97654.pf
Delete 2.1kB C:\Windows\Prefetch\NET.EXE-0225D674.pf
Delete 2.1kB C:\Windows\Prefetch\NET1.EXE-091D8149.pf
Delete 33.7kB C:\Windows\Prefetch\STARTMENUEXPERIENCEHOST.EXE-DF593AF9.pf
Delete 4.5kB C:\Windows\Prefetch\SVCHOST.EXE-BF11D6E4.pf
Delete 3.8kB C:\Windows\Prefetch\SVCHOST.EXE-F0617438.pf
Delete 4.8kB C:\Windows\Prefetch\TASKKILL.EXE-0ECD41EC.pf
Delete 25.8kB C:\Windows\Prefetch\TEXTINPUTHOST.EXE-58D1C3A3.pf
Delete 5.8kB C:\Windows\Prefetch\TIWORKER.EXE-C8892FA4.pf
Delete 3.9kB C:\Windows\Prefetch\TRUSTEDINSTALLER.EXE-766EFF52.pf
Mark for deletion 788.4kB C:\Windows\temp\DESKTOP-49E3BJM-20220308-2208.log
Mark for deletion 0B C:\Windows\temp\FXSAPIDebugLogFile.txt
Mark for deletion 0B C:\Windows\temp\FXSTIFFDebugLogFile.txt
Mark for deletion 0B C:\Windows\temp\officeclicktorun.exe_streamserver(2022030822082811EC).log
net stop cryptsvc 0B 
net start cryptsvc 0B 
Delete registry key 0B HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{CEBFF5CD-ACE2-4F4F-9178-9926F41749EA}\Count
Delete registry key 0B HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\UserAssist\{F4E57C4B-2036-45F0-A9AB-443BCFE33D9F}\Count
Delete registry key 0B HKCU\Software\Microsoft\Windows\Shell\Bags
Delete registry key 0B HKCU\Software\Microsoft\Windows\Shell\BagMRU
Delete registry key 0B HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\BagMRU
Run external command: taskkill.exe /f /IM explorer.exe 0B 
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_1280.db
Delete 1MB C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_16.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_1920.db
Delete 1MB C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_256.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_2560.db
Delete 1MB C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_32.db
Delete 1MB C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_48.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_768.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_96.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_custom_stream.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_exif.db
Delete 7.4kB C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_idx.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_sr.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_wide.db
Delete 24B C:\Users\papaf\AppData\Local\Microsoft\Windows\Explorer\thumbcache_wide_alternate.db
Run external command: C:\Windows\explorer.exe C:\Windows\explorer.exe 0B 
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\History
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Favicons
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Preferences
Vacuum 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\History
Vacuum 0B C:\Users\papaf\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\places.sqlite
Clean file 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\favicons.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\favicons.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\permissions.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\places.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\protections.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\storage-sync-v2.sqlite
Vacuum 0B C:\Users\papaf\AppData\Roaming\Mozilla\Firefox\Profiles\w81363o2.default-release\storage.sqlite

Disk space recovered: 33MB
Files deleted: 43
Special operations: 49

**Comment by papafenrir** [comment]
internet Explorer 27.8MB
Cache                   27.8MB
no change after cleaning

**Comment by papafenrir** [comment]
![Capture](https://user-images.githubusercontent.com/101057102/158792720-1f904074-33f7-415b-afaf-1977452ed69c.PNG)
![Capture1](https://user-images.githubusercontent.com/101057102/158792760-ff214ed8-6fa4-4da7-a939-8de56eb42ea4.PNG)

**Comment by papafenrir** [comment]
is this what you wanted
