### ISSUE TITLE
Bleachbit not cleaning custom added folder

### ISSUE THREAD

**Issue by peter099** [bleachbit/bleachbit#1351]
I have installed Bleachbit 3.9.0 on MX Linux. I have partition that is mounted in /media/data1. In Bleachbit preferences i added this folder path to be cleaned: /media/data1/.Trash-1000. But the folder is not deleted when i run Bleachbit.

**Comment by abitrolly** [comment]
I believe BleachBit is unable to remove mount points. If `rmdir /media/data1` doesn't work then BleachBit won't remove that too.

**Comment by peter099** [comment]
This work: `rm -r /media/data1/.Trash-1000`

**Comment by az0** [comment]
@peter099 
On the main screen, did you check the box _custom_ under the category _system_?

**Comment by peter099** [comment]
No, i didn't know i have to check this option. After selecting it the /media/data1/.Trash-1000 folder was deleted. Thanks.
