### ISSUE TITLE
[Version 4.4.2 Windows 10] Install error

### ISSUE THREAD

**Issue by nignog8655** [bleachbit/bleachbit#1354]
When I run the installer and get to the last part it says:

Error opening file for writing: 
C:\Program Files (x86)\BleachBit\.\pythoncom34.dll

Im not sure why it's happening because the file exists and im running it as an admnistrator

Any help is greatly appreciated!

**Comment by az0** [comment]
Please verify that BleachBit is not already running. Maybe check the Windows Task Manager for BleachBit.exe in case it's not visible, which is unusual.

If this does not work, reboot the operating system and try again.

**Comment by az0** [comment]
There was no response in a month, so I will close this. If you still have this problem and want to continue, please type a comment in GitHub and hit the reopen button to reopen the issue.
