### ISSUE TITLE
Windows 11 [WinError 21]

### ISSUE THREAD

**Issue by GFHaze** [bleachbit/bleachbit#1358]
I ran BleachBit overnight to clean my hard drive and woke to this message:
Overwrite free disk space C:\Users\Gary\AppData\Local\Temp 0B 
[WinError 21] The device is not ready: 'E': Function: Overwrite free disk space E:\

**Comment by az0** [comment]
Garth,

What kind of E: drive do you have? Is it a removable drive like a MicroSD
or removable USB drive?

**Comment by GFHaze** [comment]
Yes it is a removable drive I use for my backups that was not connected.
Does that mean it completed the C: drive that I was trying to do?

**Comment by az0** [comment]
It looks like C: was correctly wiped. A clue is that it typically takes a very long time, depending on the amount of free space and hardware performance.

To avoid this error next time, go into BleachBit preferences, open the drives tab, and remove the E: drive.

Alternatively, go into the application menu and choose "shred settings and quit" to reset all settings.

**Comment by GFHaze** [comment]
Andrew,
Thanks very much for your input. I usually run the free space wipe
just before heading to bed so the length of its run is lost on me.
I followed your instructions and was able to get E;\: removed.
I also ran the shred & quit.
Thanks again for your assistance, stay safe,
Gary
