### ISSUE TITLE
Wrong informations, build number and platform versions, reported

### ISSUE THREAD

**Issue by Ricky-Tigg** [bleachbit/bleachbit#1359]
**Describe the bug**
Wrong informations, **Build number** and **platform versions**, reported by BleachBit; relevant parameters are shown in bold.

- System informations as reported by Windows

_Edition	Windows **11** Home
Version	21H2
Installed on	‎17.‎4.‎2022
OS build	**22000.613**
Experience	Windows Feature Experience Pack 1000.22000.613.0_

- System informations as reported by BleachBit

_BleachBit version 4.4.2
**Build number** 2142
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.36.0
local_cleaners_dir = F:\BleachBit-Portable\cleaners
locale_dir = F:\BleachBit-Portable\share\locale\
options_dir = F:\BleachBit-Portable
personal_cleaners_dir = F:\BleachBit-Portable\cleaners
system_cleaners_dir = F:\BleachBit-Portable\share\cleaners\
locale.getdefaultlocale = ('fi_FI', 'cp1252')
os.getenv('APPDATA') = C:\Users\vince\AppData\Roaming
os.getenv('cd') = F:\BleachBit-Portable
os.getenv('LocalAppData') = C:\Users\vince\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\vince\AppData\LocalLow
os.getenv('Music') = C:\Users\vince\Music
os.getenv('USERPROFILE') = C:\Users\vince
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\vince\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\vince
**platform.win32_ver[1](**) = 10.0.22000
**platform.platform** = Windows-10-10.0.22000
**platform.version** = 10.0.22000
sys.argv = ['F:\\BleachBit-Portable\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = F:\BleachBit-Portable\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = F:\BleachBit-Portable\library.zip\bleachbit\SystemInformation.pyo_

**Desktop:**
 - OS: Windows 11
 - BleachBit version:  4.4.2

**Expected behavior**
Correct informations to be reported by BleachBit

**Additional context**
_Windows 10_, which was the edition originally installed, was upgraded to the edition _Windows 11_. That last was activated with a digital license linked to my Microsoft account.

**Comment by az0** [comment]
The build number 2142 refers to an internal (i.e., BleachBit-only) build number as seen on the [CI build site](https://ci.bleachbit.org/), and it's not expect to match Windows.

The Windows platform showing 10 instead of 11 should be fixed by updating the [Python framework](https://github.com/bleachbit/bleachbit/issues/848).

**Comment by Ricky-Tigg** [comment]
No surprise. Even without investigating, i could easily suspect that many issues that might occur in your project are and will be related to highly old components as version numbers indicate it; GTK, SQLite., and Python's one, mentioned by you elsewhere.
