### ISSUE TITLE
Wrong locale applied in BleachBit UI

### ISSUE THREAD

**Issue by Ricky-Tigg** [bleachbit/bleachbit#1360]
**Describe the bug**
Hello. Wrong locale applied in BleachBit UI, for instance the system's original locale instead of the one currently applying, which is supported as well by BleachBit.

**Desktop:**
 - OS: Windows 11
 - BleachBit **portable** version: 4.4.2

**Expected behavior**
Correct locale for BleachBit UI to be applied, which is therefore expected to be according  to the one as current system locale.

**Additional context**
_Windows 10_, which was the edition originally installed, was upgraded to the edition _Windows 11_. That last was activated with a digital license linked to my Microsoft account. 

- Original locale applying at system installation: **Finnish**
- Current  locale applying in system: **English**; which was installed afterwards to my system, for eventual troubleshooting material to be sent upstream.

**Comment by az0** [comment]
BleachBit is running in Finnish, while Windows itself is running in English, and you want BleachBit to be in English too. Is this correct?

**Comment by Ricky-Tigg** [comment]
Sure, this is correct. I omitted to mention relevant details. _Finnish_ applies solely to that domain:

![Windows_11_language_region_1](https://user-images.githubusercontent.com/26058215/169480061-9def1e19-95c5-4a38-b646-dbfc977bca6a.png)

 _English_ applies solely to those domains:

![Windows_11_language_region_2](https://user-images.githubusercontent.com/26058215/169480553-ecb18f56-7030-4957-8b18-01c9289f7068.png)

**Comment by Ricky-Tigg** [comment]
Sure, this is correct. I omitted to mention relevant details; here they are:

![Windows_11_language_region_1](https://user-images.githubusercontent.com/26058215/169480061-9def1e19-95c5-4a38-b646-dbfc977bca6a.png)
![Windows_11_language_region_2](https://user-images.githubusercontent.com/26058215/169480553-ecb18f56-7030-4957-8b18-01c9289f7068.png)

**Comment by az0** [comment]
BleachBit uses a system called gettext that detects the language and presents the user language. For more troubleshooting, would you please ..

1. Open BleachBit
2. Open the application menu
3. Choose System Information
4. Copy either all the lines or at least those that start with locale and platform
5. Paste them here

As a quick workaround, there are some options in the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html)

>To force BleachBit to always show in English, download and install the English installer instead of the regular installer. If using the regular (non-English-only) installer, uncheck the option to install translations.

Another option is to delete the directory `c:\program files(x86)\bleachbit\share\locale` which has the translations.

**Comment by Ricky-Tigg** [comment]
_System Information_; here it is with _locale_ and _platform_ filtered:

```
locale_dir = D:\BleachBit-Portable\share\locale\
locale.getdefaultlocale = ('fi_FI', 'cp1252')
platform.win32_ver[1]() = 10.0.22000
platform.platform = Windows-10-10.0.22000
platform.version = 10.0.22000
```
_Note:_ invalid value of parameter `platform.platform`; Windows gets a valid one, then that issue is on BleachBit's side.

Values reported by _Msinfo32.exe_ (partial selection): 
```
OS Name	Microsoft Windows 11 Home
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
Locale	Finland
```
There the original locale is **invariably** reported, be it the current locale or not, even with _Finland_ and _Finnish (Finland)_ being selected respectively for _Country or region_ and _Regional format_. I have reason to suspect that your program is getting its information in this regard at the same source that Windows does. In case it does so, that would exclude the issue to be on BleachBit's side and make it on Microsoft's side.

**Comment by az0** [comment]
> _Note:_ invalid value of parameter `platform.platform`; Windows gets a valid one, then that issue is on BleachBit's side.

The bad platform value is probably because BleachBit 4.4.2 has an old version of Python, and [updating Python in BleachBit](https://github.com/bleachbit/bleachbit/issues/848) is a work in progres.

> [...]

> There the original locale is **invariably** reported, be it the current locale or not, even with _Finland_ and _Finnish (Finland)_ being selected respectively for _Country or region_ and _Regional format_. I have reason to suspect that your program is getting its information in this regard at the same source that Windows does. In case it does so, that would exclude the issue to be on BleachBit's side and make it on Microsoft's side.

I would like to retest after updating Python in BleachBit.
