### ISSUE TITLE
Special Operations

### ISSUE THREAD

**Issue by Jayson900** [bleachbit/bleachbit#1364]
What exactly are the Special Operations in BleachBit after the preview of the system runs?

**Comment by abitrolly** [comment]
Screenshot for the reference.

![image](https://user-images.githubusercontent.com/8781107/167348458-c1ece281-4d96-4192-90f9-c407602e64ba.png)

**Comment by abitrolly** [comment]
The value is summed up from `n_special` field in https://github.com/bleachbit/bleachbit/blob/master/bleachbit/Command.py but I don't see any explanation so far.

**Comment by abitrolly** [comment]
@az0 ?

**Comment by Jayson900** [comment]
Aight good looking.

**Comment by az0** [comment]
Non-special commands include: delete, truncate, and shred.

Special commands are any others, which include: run any external process (such as dnf, apt, or yum), edit JSON file, edit INI file, delete registry key, and edit SQLite3 database.

**Comment by abitrolly** [comment]
@az0 added your clarification with edits to source code in #1373.
