### ISSUE TITLE
I get an error message every time I use Bleachbit to wipe the free space in memory.

### ISSUE THREAD

**Issue by fnfontana** [bleachbit/bleachbit#1368]
**Describe the bug**
When I use Bleachbit to wipe the free space in memory, it displays some error messages.

**To Reproduce**
Just use Bleachbit to wipe out the free space in memory of any disk.

The error happens every time, and with every drive/disk.

**Expected behavior**
I think the task should be accomplished without error messages.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 19044.1645
 - Bleachbit version: 4.4.2

**Additional context**
I'm using the GUI in PT-BR language, that's the error message that is presented at the end of the task:

`Erro: _gui.free_disk_space: Function: Sobrescrever o espaço livre no disco em C:\
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 145, in execute
  File "bleachbit\Cleaner.pyo", line 724, in wipe_path_func
  File "bleachbit\FileUtilities.pyo", line 1013, in wipe_path
KeyError: 'arquivos'`

**Comment by az0** [comment]
The error is caused by the PT-BR translation

Original text 

> Wrote {files:,} files and {bytes:,} bytes in {seconds:,} seconds at {rate:.2f} MB/s

Translation

>Escreveu {arquivos:,} arquivos e {bytes:,} bytes em {segundos:,} segundos a {taxa: .2f} MB/s

The text in brackets must be in English, so that causes the KeyError.

Would you mind making this change in [BleachBit's translation to Portuguese (Brazil)](https://hosted.weblate.org/projects/bleachbit/glossary/pt_BR/)?

**Comment by fnfontana** [comment]
> Would you mind making this change in [BleachBit's translation to Portuguese (Brazil)](https://hosted.weblate.org/projects/bleachbit/glossary/pt_BR/)?

Hi, I'm on vacations now, if those files still need translation I'm with spare time to translate it. Just let me know how to proceed.

**Comment by fnfontana** [comment]
I'm still facing the issue:
```
Erro: _gui.free_disk_space: Function: Sobrescrever o espaço livre no disco em H:\
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 145, in execute
  File "bleachbit\Cleaner.pyo", line 724, in wipe_path_func
  File "bleachbit\FileUtilities.pyo", line 1013, in wipe_path
KeyError: 'arquivos'
```

Which files do I need to change to fix the translation to Portuguese (Brazil)?

**Comment by az0** [comment]
> > Would you mind making this change in [BleachBit's translation to Portuguese (Brazil)](https://hosted.weblate.org/projects/bleachbit/glossary/pt_BR/)?
> 
> Hi, I'm on vacations now, if those files still need translation I'm with spare time to translate it. Just let me know how to proceed.

Yes

1. Please visit the [BleachBit's translation to Portuguese (Brazil)](https://hosted.weblate.org/projects/bleachbit/glossary/pt_BR/)
2. Create an account in that system (Weblate)
3. Find the string that looks like "Wrote {files:,} files and {bytes:,} bytes in {seconds:,} seconds at {rate:.2f} MB/s". (Make sure you are in the pt-BR language.)
4. Un-translate the text inside the brackets, so it is English

**Comment by az0** [comment]
I fixed it https://hosted.weblate.org/translate/bleachbit/main/pt_BR/?q=wrote&sort_by=-priority%2Cposition&offset=1

I did not see any related issues in the same language
