### ISSUE TITLE
Free disk space

### ISSUE THREAD

**Issue by Abhishek460099** [bleachbit/bleachbit#1374]
**Describe the bug**
Its a hell of a problem man. tried cleaning the free disk space but saw my storage space getting occupied. my disk was 185 GBs free out of 228  but now it is 145 GBs. At first it took about something like 40 minutes to clean up then I aborted, I didn't wanted to wait 40. It was now it was 145 instead of 185. I tried it again this time kept my pc stay awake for 30 minutes. guess what showed up, entire storage gone, 0 bytes left free. Restarted and then got to 145v again. I couldn't find a solution. hope u guys will, soon.

**To Reproduce**
1. Go to 'System'
2. Click on 'free disk space'
3. Click clean
4. Abort in between the process.

The error happens (every time).

**Expected behavior**
should be precise.

 Windows 11 pro
 - BleachBit version 4.2.0

**Comment by az0** [comment]
From the [BleachBit FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html)

>Q: Why does BleachBit take a long time (more than five minutes) while filling up by hard drive?

>A: You enabled the option to System - Free disk space to wipe free disk space for privacy. This works basically by creating a large, empty file (see [Shred files and wipe disks](https://docs.bleachbit.org/doc/shred-files-and-wipe-disks.html) for more information). When the hard drive is full, the file will be deleted immediately, and there will be no net change in disk space (you will be back where you started). It is generally recommended you disable this option.

**Comment by abitrolly** [comment]
@az0 I don't see this option in 4.4.2

![image](https://user-images.githubusercontent.com/8781107/169685997-b1e1e670-68af-4873-a84b-867e2bb9c8ca.png)

**Comment by az0** [comment]
@abitrolly 

It means the "free disk space" cleaner in the system category

![image](https://user-images.githubusercontent.com/933680/169703900-04e6486d-329b-4e5a-a01a-36213f4b98f5.png)

**Comment by abitrolly** [comment]
Is it the same as `Wipe Free Space` in the menu?

![image](https://user-images.githubusercontent.com/8781107/169750651-ee2bd209-0224-4952-8fcb-99b248c88ec8.png)

**Comment by az0** [comment]
@abitrolly It's another way of accessing it. The "free disk space" checkbox under "system" can be activated by using the clean button on the toolbar, and it will affect the directories chosen in the preferences. In the application menu you posted, it will prompt you for a directory.

**Comment by abitrolly** [comment]
@az0 I feel like this option is special enough to have its own category, which will provide some explanations for a better UX. Like that running this choice alone may take up to 40 minutes. And that it actually wipes the disk for security, not just cleans up recoverable file entries in free space.
