### ISSUE TITLE
Make wiping out step optional

### ISSUE THREAD

**Issue by yuchdev** [bleachbit/bleachbit#1379]
After cleaning up, wiping out is not always necessary.
Can we add an option to skip this step?
If you don't mind, I can add it it and create a PR (I have Windows only for testing though).

**Comment by az0** [comment]
By "wiping out," do you mean wiping free disk space, which can take a
long time? This is optional.

Andrew

**Comment by abitrolly** [comment]
I guess it is this option. Then ensure it is not checked.

![image](https://user-images.githubusercontent.com/8781107/180015735-5cea4837-135c-4b91-92f8-dfd83fe91788.png)
