### ISSUE TITLE
Firefox Cleaner Rewritten

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#138]
I have rewritten Firefox cleaner and made few changes:
Added telemetry data cleaner
Changed in paths "_.default_" to "*"
Changed "~/.cache/mozilla" to "~/.cache/mozilla/firefox/" in cache cleaner
Propably messed up cache and vacuum cleaner

[https://gist.github.com/devmapper0/e9e21ac211461d438ad2a6f7d68ca678](https://gist.github.com/devmapper0/e9e21ac211461d438ad2a6f7d68ca678)

**Comment by nodiscc** [comment]
@devmapper0 your gist is unreachable

@az0 currently the main problem with the Firefox cleaner is it assumes the only profile directory is at `$USERPROFILE\\Application Data\\Mozilla\\Firefox\\Profiles\\*.default*\\` on Win, and `~/.mozilla/firefox*/*.default*/` on Linux: https://github.com/az0/bleachbit/blob/master/bleachbit/Cleaner.py#L225

Same for the `cachebase` which Bleachbit expects to be at `$localappdata\\Mozilla\\Firefox\\Profiles\\*.default*` : https://github.com/az0/bleachbit/blob/master/bleachbit/Cleaner.py#L245

 - [ ] When other profiles are created through the profile manager, they are placed at `Profiles\*.profilename`, and therefore are not cleaned.

Can you show me how to fix it? I think `profile_dir` and `cachebase` need to be declared as lists, and a `for` loop added at https://github.com/az0/bleachbit/blob/master/bleachbit/Cleaner.py#L247. I have tried to fix this, and failed.

**Comment by devmapper0** [comment]
@nodiscc Link is working now.

**Comment by ROCKNROLLKID** [comment]
Andrew was, at one time, talking about moving all the cleaners to CleanerML, so it might be a good idea just to do that.

**Comment by ROCKNROLLKID** [comment]
Does this relate to tiemays work? https://github.com/az0/bleachbit/issues/89

**Comment by devmapper0** [comment]
@ROCKNROLLKID I just run my cleaner in BleachBit 1.12-1 on Debian Testing and there are no errors. I do not used `command="mozilla_url_history"` anywhere in cleaner. I was rewriting directly from [Cleaner.py](https://github.com/az0/bleachbit/blob/master/bleachbit/Cleaner.py).
