### ISSUE TITLE
"The specified module could not be found."

### ISSUE THREAD

**Issue by zero5zero6zero7** [bleachbit/bleachbit#1384]
Launching from same folder (E:\X\Z Backup Settings\_Tools\BleachBit), except I moved the folder to a new HDD and then renamed the new HDD back to letter to "E" (since last one was dying), I'm getting this error. All other portable apps in this folder launch fine.

I did NOT get this error before (launched from same location, portable version) and the app still launches despite the error. This makes no sense. All security settings are provided, even as admin launch the app still gives this launch error.

I saw it on Bleachbit forums that it's the space in names of folder causing this error (even though it didn't before). So I moved the portable folder to "E:\X\BleachBit-Portable" and launched it, there was no error. But now that means I'm moving it out of folder where all portable apps are, which is a bit annoying but I guess I'll have to live with this since the error was reported in [2019](https://www.bleachbit.org/forum/specified-module-cannot-be-found) and not really fixed. 

While we're at it, extracting portable files into same folder and overwriting basically erased all previous settings (same version). That kinda makes the portable version pointless if it just wipes the settings in same folder.

**Comment by abitrolly** [comment]
Can you post a full traceback here? And try running with `--debug` if it gives nothing.

**Comment by zero5zero6zero7** [comment]
Heh, was confused about debug command, until I realized it's the console EXE that is run with it (sandbox doesn't make it clear).

Anyway, here's the log:

`BleachBit version 4.4.2
Build number 2142
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.36.0
local_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\cleaners
locale_dir = E:\X\Z Backup Settings\_Tools\BleachBit\share\locale\
options_dir = E:\X\Z Backup Settings\_Tools\BleachBit
personal_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\cleaners
system_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_IN', 'cp1252')
os.getenv('APPDATA') = C:\Users\WTF\AppData\Roaming
os.getenv('cd') = E:\X\Z Backup Settings\_Tools\BleachBit
os.getenv('LocalAppData') = C:\Users\WTF\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\WTF\AppData\LocalLow
os.getenv('Music') = C:\Users\WTF\Music
os.getenv('USERPROFILE') = C:\Users\WTF
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\WTF\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\WTF
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['E:\\X\\Z Backup Settings\\_Tools\\BleachBit\\bleachbit_console.exe', '--gui', '--debug-log=C:\\Users\\WTF\\desktop\\bleachbit.log']
sys.executable = E:\X\Z Backup Settings\_Tools\BleachBit\bleachbit_console.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = E:\X\Z Backup Settings\_Tools\BleachBit\library.zip\bleachbit\SystemInformation.pyo
BleachBit version 4.4.2
Build number 2142
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.36.0
local_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\cleaners
locale_dir = E:\X\Z Backup Settings\_Tools\BleachBit\share\locale\
options_dir = E:\X\Z Backup Settings\_Tools\BleachBit
personal_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\cleaners
system_cleaners_dir = E:\X\Z Backup Settings\_Tools\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_IN', 'cp1252')
os.getenv('APPDATA') = C:\Users\WTF\AppData\Roaming
os.getenv('cd') = E:\X\Z Backup Settings\_Tools\BleachBit
os.getenv('LocalAppData') = C:\Users\WTF\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\WTF\AppData\LocalLow
os.getenv('Music') = C:\Users\WTF\Music
os.getenv('USERPROFILE') = C:\Users\WTF
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\WTF\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\WTF
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['E:\\X\\Z Backup Settings\\_Tools\\BleachBit\\bleachbit_console.exe', '--gui', '--no-uac', '--gui', '--debug-log=C:\\Users\\WTF\\desktop\\bleachbit.log']
sys.executable = E:\X\Z Backup Settings\_Tools\BleachBit\bleachbit_console.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = E:\X\Z Backup Settings\_Tools\BleachBit\library.zip\bleachbit\SystemInformation.pyo
`

**Comment by abitrolly** [comment]
Yes. It is also possible to paste in into message.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

But I don't see the error here. Maybe post screenshot?

**Comment by zero5zero6zero7** [comment]
Here's the screenshot.

Do note, the app still works, after closing the error. 
![BLEACH](https://user-images.githubusercontent.com/48183861/183960659-0d2b9fad-c0fd-4210-9c38-81a7519ab467.png)

**Comment by abitrolly** [comment]
No idea. Maybe there is an error loading `__file__ = E:\X\Z Backup Settings\_Tools\BleachBit\library.zip\bleachbit\SystemInformation.pyo`. I would try https://www.dependencywalker.com/ but the error occurs after BleachBit started, so it is unlikely to help here.

It maybe be possible to `set PYTHONVERBOSE=1` environment variable in console before running. Python should give more info about what is it doing, and the last lines may show the problem.

**Comment by zero5zero6zero7** [comment]
OK, so running the app as it is (despite the error) and cleaning things, I noticed one error showing up (which never did before) in red:

> Error: winapp2_windows.windows_logs: Command to delete C:DumpStack.log
> Traceback (most recent call last):
>   File "bleachbit\Worker.pyo", line 87, in execute
>   File "bleachbit\Command.pyo", line 79, in execute
>   File "bleachbit\FileUtilities.pyo", line 548, in getsize
> pywintypes.error: (123, 'FindFirstFileW', 'The filename, directory name, or volume label syntax is incorrect.')

Anyway, I'll just move Bleachbit folder since I can't be arsed with changing 50 other sandbox tools/utilities shortcuts in that folder.

**Comment by abitrolly** [comment]
Does that `FindFirstFileW` error happen only if BleachBit is in spaced folder?

I am not on Windows, but I would try to run BleachBit from source https://github.com/bleachbit/bleachbit#running-from-source and then try to replace the line https://github.com/bleachbit/bleachbit/blob/9f70f6191a554027549ca1487f578d41165aa603/bleachbit/FileUtilities.py#L548 with
```python
finddata = False
```
Just to see if the error will gone.

If it is gone, then insert
```python
print(extended_path(path))
```
there to see what it shows

**Comment by rados** [comment]
@zero5zero6zero7 I could reproduce the RunDLL error message. Will continue tracing the issue.

**Comment by rados** [comment]
@zero5zero6zero7 Seems like this build with the new Python, etc. solves the problem. You might want to check... 
[build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/)?

**Comment by zero5zero6zero7** [comment]
> @zero5zero6zero7 Seems like this build with the new Python, etc. solves the problem. You might want to check... [build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/)

Yeah, can confirm, the issue is solved in this build.

**Comment by zero5zero6zero7** [comment]
> @rados good question
> 
> @zero5zero6zero7 thank you for confirming
> 
> Closing as resolved by #848


4.6.0

This problem is back. :(
