### ISSUE TITLE
Add "shred with bleachbit" to the right click context menu

### ISSUE THREAD

**Issue by Quill4769** [bleachbit/bleachbit#1391]
Is there a way to add the "shred with bleachbit" option to the right click context menu on linux. I am using KDE on Arch and would like to have the same feature from windows. Would it be possible to add a setting for this in preferences?

**Comment by abitrolly** [comment]
I have no experience with KDE and Arch packaging. If KDE supports this feature, with proper references/tutorials it is real.

**Comment by kenrap** [comment]
@Quill4769 I'm using KDE on NixOS and I'm looking into implementing this.

I got two questions though:
1. Should the menu option open a terminal window to display the bleachbit output?
2. Should the user be prompted with a Yes/No response before attempting it?
    - At least for preventing accidental left clicking on the shred option for safety?
