### ISSUE TITLE
Firefox 104 not being cleaned

### ISSUE THREAD

**Issue by hypnotist57** [bleachbit/bleachbit#1397]
On the last new installs of Ubuntu 22.04.1, with  Bleachbit 4.4.2 no longer lists Firefox version 104 the latest, in the left pane to tick options to clean?

If you go to preferences and un-tick irrelevant  cleaners it does indeed show Firefox in the left pane with a long list of other options, If you then tick which parts of Firefox you want clean and then press clean it never shows anything cleaned or any results. 
Ubuntu is just the latest version 104 and a standard install with Firefox pre-loaded in the operating system.

Now I build lots of computers and never had any problems previous to the last 4 I built, all on Ubuntu 22.04.1 using Bleachbit the latest version 4.4.2.

Anyone shed any light on the issue?

This is only happening over the last 2 weeks, new Motherboards, CPU,RAM and HDD, ever tried a fresh install on my own new laptop with the same results, no listing for firefox or anything cleaned.

**Comment by justa-rowdy** [comment]
I believe I am having the same issue with Firefox not being cleaned?

Believe problem started occurring after updating to Firefox 104.0.2 (64-bit).  Using BleachBit 4.2.2,  Windows Windows 10 Pro Version 21H2

Get the following (same or similar) error messages every time when running BleachBit.

Error: firefox.url_history: Function: Clean file: C:\Users\????????\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default\places.sqlite
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 313, in delete_mozilla_url_history
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places: C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default\places.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'
 
Hope this helps...

**Comment by justa-rowdy** [comment]
Did 3 things since I sent the above comment.  

1) Went into BleachBit Preferences and checked the box to Download and update cleaners from the community (winapp2.ini)
Resulted in same error reported in previous comment.

2) Downloaded the firefox.xml referenced above and replaced the one in the system cleaners directory.
Resulted in same error reported in previous comment.

3) Searched Firefox directory on "places.sqlite"
Resulted in two matches.
a. C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\6xdcjkfn.default-release
b. C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default

The "places.sqlite" file is in two different directories under Firefox Profiles.

**Comment by az0** [comment]
> I believe I am having the same issue with Firefox not being cleaned?
> 
> Believe problem started occurring after updating to Firefox 104.0.2 (64-bit). Using BleachBit 4.2.2, Windows Windows 10 Pro Version 21H2
> 
> Get the following (same or similar) error messages every time when running BleachBit.

Could you please make this a new issue about "no such table"?  The original post here is that Firefox doesn't show in the list of cleaners, so a new issue will make it easier to triage and manage.

**Comment by justa-rowdy** [comment]
Will do!

**Comment by az0** [comment]
I have not heard back from @hypnotist57  about the new firefox.xml file, but it looks good, so closing as fixed

**Comment by Jesusguy340** [comment]
Where do I put the firefox.xml file?

**Comment by rados** [comment]
@Jesusguy340, in the installation folder, most probably: C:\Program Files (x86)\BleachBit\share\cleaners
