### ISSUE TITLE
Missing icons with 2265 Python 3.10 build with natively installed vcruntime140.dll

### ISSUE THREAD

**Issue by kenrap** [bleachbit/bleachbit#1409]
I found two consecutive and related bugs with the latest 2265 build using an already installed Visual C++ 2015-2022 Redistributable package in a Windows 11 VM. With regards to #1407, the 2015 Redistributable is what specifically provides the necessary vcruntime140.dll to run the build. This report will cover the first bug.

**Steps to reproduce the behavior**
1. Make sure to have (at least) the Visual C++ 2015 Redistributable installed.
2. Download [BleachBit-4.4.2.2265-setup-English.exe](https://ci.bleachbit.org/dl/4.4.2.2265-mkhon-python310/BleachBit-4.4.2.2265-setup-English.exe).
3. Run installer, keep clicking next to install.
4. Open the application the first time. Accept the Windows UAC (User Account Control) if prompted.
5. See the applicable screenshot for the result.

**Expected behavior**
Should look as if running it in Linux with the icons provided by the Adwaita theme.

**Screenshot**
![bug](https://user-images.githubusercontent.com/101818165/196367970-5d83f445-e1bd-4f7b-aecd-5efa12f49967.png)

**Desktop Specs**
 - OS: Windows 11 (via qemu-kvm using virt-manager to manage passthrough configurations)
 - BleachBit 4.4.2.2265

**Comment by az0** [comment]
Regarding missing icons, see PR comment https://github.com/bleachbit/bleachbit/pull/1403

> vcpkg gdk-pixbuf lacks svg support (this is being worked on) so some icons are not loaded. See also microsoft/vcpkg#8015

**Comment by mkhon** [comment]
This should be fixed now (svg pixbuf loader is now fixed) in this PR: #1439

**Comment by az0** [comment]
Looks good in build 2310

@kenrap 
Good bug report. Perhaps you want to verify and continue bug hunting with [build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/).

@mkhon 
Thank you for the fix

**Comment by az0** [comment]
[BleachBit 4.9.1 alpha](https://www.bleachbit.org/news/bleachbit-491-alpha) was released with this fix. This is digitally signed, unlike the CI builds.
