### ISSUE TITLE
Bleachbit not cleaning Firefox

### ISSUE THREAD

**Issue by 0rezer0** [bleachbit/bleachbit#1412]
OS: Xubuntu 22.04.1
Bleachbit: 4.4.2
Firefox: 106.0.1 (64 bit) Snap canonical-002 - 1.0

I don't know if this is due to the Snap package that Canonical is using or what but Bleachbit doesn't seem to be cleaning FF. This was a clean install of Xubuntu and as usual I installed Bleachbit from the latest .deb from the website. At first Firefox didn't even show up until I un-hid all of the cleaner options. I use the default preferences with the exception of "Overwrite contents..." and "Check for beta...".  As far as Firefox options, I choose everything but Passwords. I don't get it, it's always worked great in the past. Any help or info is greatly appreciated. Thank you for your time and have a great day! 

Edit:  Just saw there might be a similar issue and someone suggested to use an updated .xml file. I ran the diff command and indeed there were a couple differences, some that mentioned snaps.

**Comment by abitrolly** [comment]
Should be fixed in #1363.

@az0 maybe release new version to avoid duplicates?

**Comment by 0rezer0** [comment]
It seems that the new .xml file with updated paths to snap did the trick.  I'll consider this fixed on my end and close this issue.  Thank you again.
