### ISSUE TITLE
AttributeError and OperationalError when cleaning Firefox places

### ISSUE THREAD

**Issue by sktrotter** [bleachbit/bleachbit#1423]
Hello, I get the following error when running bleachbit. Also, sometimes the icons on my desktop will start flashing continually after bleachbit completes until I reboot.

Error: firefox.url_history: Function: Clean file: C:\Users\s-tro\AppData\Roaming\Mozilla\Firefox\Profiles\ihkv64ph.default\places.sqlite
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 313, in delete_mozilla_url_history
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places: C:\Users\s-tro\AppData\Roaming\Mozilla\Firefox\Profiles\ihkv64ph.default\places.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by abitrolly** [comment]
@sktrotter which BleachBit version do you run?

**Comment by sktrotter** [comment]
I'm running version 4.4.2 on windows 11 22h2.
________________________________

**Comment by rados** [comment]
@sktrotter And what checkboxes do you check for cleaning? I mean only those Firefox related...

**Comment by abitrolly** [comment]
@rados looks like the SQLite code might need to check for known database structure. I have a code that draws the diagram at https://github.com/abitrolly/sqlite2png that can help with troubleshooting what is wrong with different Firefox versions.

**Comment by az0** [comment]
@sktrotter 

Do you often use Firefox? Which version of Firefox?

**Comment by az0** [comment]
Two things

First, a few people have reported this, but I haven't been able to naturally reproduce it, so would you be willing to privately send me a copy of your file `C:\Users\s-tro\AppData\Roaming\Mozilla\Firefox\Profiles\ihkv64ph.default\places.sqlite` to my email ahz001 at gmail dot com?

Second, would you please test [build 2307](https://ci.bleachbit.org/?prefix=dl/4.4.2.2307-moz_no_places/)? It has a special fix that is not in the main-line code yet. Note: it will modify the places.sqlite file, but it is okay to send the file after cleaning it.

**Comment by az0** [comment]
It would be helpful if you could please test. (See comment from January 1). Add a comment here to confirm.

As is, I will assume it is fixed, but if not, please reopen this issue.
