### ISSUE TITLE
Ubuntu 22.04 bleachbit does not display Firefox

### ISSUE THREAD

**Issue by devhost80** [bleachbit/bleachbit#1431]
Bleachbit does not properly work on Ubuntu 22.04, it does not display Brave nor Firefox, it only displays both browsers when I click hidden sources, but even then it does not delete the selected data.

I first tried downloading from Ubuntu Store and then uninstalled after I realized it didn't work and then I installed through apt and it still did not work.

Can someone please immediately have a look into into this please, pretty please with a cherry on top.

**Comment by az0** [comment]
>Bleachbit does not properly work on Ubuntu 22.04, it does not display Brave nor Firefox, it only displays both browsers when I click hidden sources, but even then it does not delete the selected data.

For Firefox, see https://github.com/bleachbit/bleachbit/issues/1397#issuecomment-1247536246

Regarding Brave: please file just one concern per issue ticket, so it is easier to manage. I will change edit the title so this is about Firefox.

**Comment by az0** [comment]
@devhost80 

Are you able to test the fix in https://github.com/bleachbit/bleachbit/issues/1397#issuecomment-1247536246 ? Or would it help if there were a .deb installation package?

**Comment by az0** [comment]
@devhost80 

It would be helpful if you could please test. (See comment from January 1). Add comment here to confirm.

As is, I will assume it is fixed, but if not, please reopen this issue.
