### ISSUE TITLE
Clean up filled the the disk instead of cleaning disk 

### ISSUE THREAD

**Issue by Sir-Thom** [bleachbit/bleachbit#1449]
**Describe the bug**
the program seem to have create some file  over and over again 

**To Reproduce**
1. open gui
2. select those all of the  options in those categories:
    Deep scan,Discord,Firefox,Gwenview,journald,LibreOffice,System,Thumbnails,VIM,VLC,yum
4. click on clean 
5. wait for system to fill up

The error happens every time it shred files 

**Expected behavior**
I expected to reduce use capacity of  my disk 

** ScreenShot **
![image](https://user-images.githubusercontent.com/90110920/213273163-8d0d443a-daf3-42bd-967a-fe76bb93a8a0.png)

**Desktop **t work in most c
 openSUSE Tumbleweed 20230116
BleachBit version 4.4.2
FileSystem: btrfs
**Additional context**
system information for bleachbit 
I have also delete every in tpm and in the cache  but it not enough because I was at 490 Gb of space and it is at 847Gb

notice it seem the system have create a snapshots during  the clean and save it and it caused the disk to be full

BleachBit version 4.4.2
GTK version 3.24.35
GTK theme = Breeze
GTK icon theme = breeze-dark
GTK prefer dark theme = True
SQLite version 3.40.1
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/thomas/.config/bleachbit
personal_cleaners_dir = /home/thomas/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = /usr/share/xsessions/plasma5
os.getenv('LOGNAME') = thomas
os.getenv('USER') = thomas
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/thomas
platform.linux_distribution() = ('', '', '')
platform.platform = Linux-6.1.4-1-default-x86_64-with-glibc2.36
platform.version = #1 SMP PREEMPT_DYNAMIC Mon Jan  9 11:00:31 UTC 2023 (4b9b43c)
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.10.9 (main, Dec 08 2022, 14:49:06) [GCC]
__file__ = /usr/share/bleachbit/SystemInformation.py

**Comment by az0** [comment]
Under system category, do you have the "free disk space" option checked?

**Comment by Sir-Thom** [comment]
yes

**Comment by az0** [comment]
See the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html) question called: ["Why does BleachBit take a long time (more than five minutes) while filling up by hard drive?"](https://docs.bleachbit.org/doc/frequently-asked-questions.html#:~:text=Q%3A%20Why%20does%20BleachBit%20take%20a%20long%20time%20(more%20than%20five%20minutes)%20while%20filling%20up%20by%20hard%20drive%3F)

Does this help?
