### ISSUE TITLE
Improvement - Read external language file to test new localization

### ISSUE THREAD

**Issue by bovirus** [bleachbit/bleachbit#1454]
@az0

**Describe the bug**

Add an option to read an external language file (.po or .qm language file) to enable to etst a localization.

A clear and concise description of what the bug is (about one sentence long).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 64bit pro italian
 - BleachBit version 4.4.2

**Additional context**

**Comment by bovirus** [comment]
@az0 

I can convert .po to .ts ./ qm and viceversa.

I have Poedit to edit .po file.

Please chech this issues

https://github.com/bleachbit/bleachbit/issues/1455

It seems that there is a mismatch about string list between Weblate and .pot template file.

In .pot template file there are some strings not recognzied by weblate.

Thanks.

**Comment by az0** [comment]
When translating on Weblate, you can export to MO format and copy the file to a certain folder. See [Translate: Verifying translations](https://www.bleachbit.org/contribute/translate).

If you have a local po file, use an [online po to mo converter](https://www.google.com/search?q=convert+po+mo+online+gettext+OR+translation) and then follow the same procedure as above.

>Please chech this issues
> https://github.com/bleachbit/bleachbit/issues/1455
> It seems that there is a mismatch about string list between Weblate and .pot

OK, let's keep the issues separate.

**Comment by bovirus** [comment]
@az0 

It's enough to laod in POedit ansd save as .mo file.

Then copy .mo file in program fodler.

Thanks.

**Comment by az0** [comment]
@bovirus 

OK, it sounds like you have a solution for testing, so I would like to close this issue. Okay?

**Comment by bovirus** [comment]
Yes. Please close this issue.
