### ISSUE TITLE
Weblate - Italian translation false error

### ISSUE THREAD

**Issue by bovirus** [bleachbit/bleachbit#1456]
@az0 

Wrong alignment english / other language number of strings
Consider error for italian language but is not true

**Describe the bug**

Weblate consider errto where there is no error

**To Reproduce**

In weblate there are some issues about Italian translation (but could be equal for other languages) to fix

https://hosted.weblate.org/projects/bleachbit/main/it/

Weblate consdier an error is source and target strings are equal. Ex:

"Multimedia" - Error because is equal in English and in Italian. It's right.

The long string "Credits" created a lot of false failed checks about double spaces, wrong checks, failed chefks, ignored checks.
Please add relative exclusion for these two items.

https://hosted.weblate.org/projects/bleachbit/main/it/

Italian - 353 strings - 100% translated

![image](https://user-images.githubusercontent.com/1262554/214628755-3bd2631c-0ac1-43fd-8ecb-96f0eea51853.png)

English - 358 string - 100% translated

![image](https://user-images.githubusercontent.com/1262554/214628819-04e99402-f84a-45ca-baa2-cfb10a6650ce.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 64 pro italian
 - BleachBit version 4.4.2

**Additional context**

**Comment by bovirus** [comment]
@az0 

This the answer by Weblate support team.
Currently in your Weblate project the .po files are not synchronzied with template file (.pot).

To sync the .po files with .pot template you need to install an add-on, see

https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge

All the information are availble on

https://docs.weblate.org/en/latest/faq.html#does-weblate-update-translation-files-besides-translations

Pelase enable ita soon as.

Thanks.

**Comment by bovirus** [comment]
@az0 

Please enable the plugin in Weblate.
It's quite easy and required a very short time.
In this way you enable the alignment of all languages to the master language (template).

Thanks.

**Comment by az0** [comment]
OK, I enabled "Update PO files to match POT (msgmerge)" with default options

* Keep previous msgids of translated strings : enabled
* Remove locations of translated strings: disabled
* Use fuzzy matching: enabled

Did this help?

**Comment by bovirus** [comment]
@az0 

I didn't see any changes in the structure of the strings.

Example: if master english has a total of 360 string I believe that also all other languages should have a total number of strings of 360.

I suggest you to write to weblate support to ask if it's enough.

**Comment by az0** [comment]
The string "S_ystem Information" was added to `po/it.po` in this commit: https://github.com/bleachbit/bleachbit/commit/9ed0f40cf563def218afeda1d4e94b48faa26e02#diff-15b3c8931fed1524ca3c16709564c6149ceea8a52daac0c0f4b0da14100108c5R2038

**Comment by bovirus** [comment]
@az0 

.po in github repositories are written by weblate strings?

then weblate is source an .po file are destinatuion?

Thanks.

**Comment by az0** [comment]
Yes, the system works like this

1. When manually executed, one tool extracts strings from source code to make `bleachbit.pot`.
2. A developer commits the new `bleachbit.pot` to git and pushes it to GitHub.
3. Weblate reads `bleachbit.pot` from GitHub.
4. Weblate adds new strings from `bleachbit.pot` to each .po file, and it creates git commits like in my last comment.  (This is the new add-on.)
5. When a user makes a translation in Weblate, it creates a git commit.
6. When there is a new git commit (either from Weblate or a developer), AppVeyor builds the application for Windows and publishes it to https://ci.bleachbit.org for testing. This takes fewer than 10 minutes.

**Comment by bovirus** [comment]
@az0 

On the same time the weblate system should set to align all not english language in weblate to english .pot template.
Then if now the template ion weblate has a total of 360 strings all language should have a total amount of 360 strings.,

Please take ane xample of italian language.
The italian language on weblate has 352 strings (not 360 strings as english template).
If i try to uplaod the enw language files with 360 strings (aligned with amster english template) weblate discard new 8 strings.

The settings that  I posted get from weblate team should set this job.

Pelase write to care  at weblate.com to help you to setup the weblate project to do it.

**Comment by az0** [comment]
> The settings that I posted get from weblate team should set this job.

Which settings?

**Comment by bovirus** [comment]
@az0

The settings for do this job with your project.

We can just wait the answer by Weblate support team.

Because it's important that weblate language file are aligned to the master.

**Comment by bovirus** [comment]
@az0 

Now seems that all languages are aligned to 360 strings.... except italian (352 strings).

please check.

**Comment by bovirus** [comment]
Please close this issue.
