### ISSUE TITLE
Hope to add a cleaner for Microsoft Edge(Chromium) on Linux

### ISSUE THREAD

**Issue by aoguang** [bleachbit/bleachbit#1493]

**Comment by az0** [comment]
I added support for Edge (beta), and I tested Ubuntu 22.04. You can try it now by downloading [microsoft_edge.xml](https://raw.githubusercontent.com/bleachbit/bleachbit/bc81da0c6eb22a577d5d16599ec68338db0f2944/cleaners/microsoft_edge.xml) and replacing the one that's already on your system. Let me know how it goes

**Comment by aoguang** [comment]
It can work on my Rocky Linux, but there is a small problem, it can not clear "Recently closed" (which can be seen after pressing Ctrl + H)
