### ISSUE TITLE
How to Automatically Clean unnecessary files using Bleachbit

### ISSUE THREAD

**Issue by rattansca** [bleachbit/bleachbit#1496]
Hi,

I would like to clean selected unnecessary files regularly using bleachbit from my Windows 10 and 11 PC.

Could you please tell, how this can be automated? Can this be done using Task Scheduler? or is there any other procedure?

Thanks
RD

**Comment by az0** [comment]
Yes, you can use the[ command line interface](https://docs.bleachbit.org/doc/command-line-interface.html) and Windows Task Scheduler.

Another option is to create a batch (.bat) file with the CLI options you want, and place it in the Windows startup folder `C:\Users\(username)\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.  (Replace with your Windows username.) Then, Windows will run it every time you log in.
