### ISSUE TITLE
Microsoft Edge error

### ISSUE THREAD

**Issue by geo711** [bleachbit/bleachbit#1503]
"Microsoft Edge cannot be cleaned because it is currently running.  Close it, and try again."

I use the portable version of Bleachbit 4.4.2 and I see this error even though Edge is not open or running.

**Comment by rados** [comment]
@geo711, thank you for the report. What happens when you restart the computer?

**Comment by tonyping** [comment]
@geo711 Is Edge's "Quick Startup" feature turned on? 

This setting means that Edge is always running in the background, regardless if you ever launched Edge. 

From MS: ```

Startup boost helps Microsoft Edge start up quicker. It keeps the browser running in the background with minimal resources, so Microsoft Edge will start quickly when opened after a device reboot or after you reopen it. 

```

So try turning this off, then rebooting before launching the cleaner.

**Comment by geo711** [comment]
Thanks Tony! You nailed it. I disabled "fast start" and that resolved the issue and BleachBit ran through with no errors. I don't use MS Edge as my default browser. I use Firefox so I was not aware of this setting. Thanks again.

**Comment by az0** [comment]
@geo711  Thank you for confirming

@tonyping  Good suggestion
