### ISSUE TITLE
Can't run Bleachbit at all in Windows 11.

### ISSUE THREAD

**Issue by barragh** [bleachbit/bleachbit#1507]
Hi, I have installed the latest version Bleachbit but it won't start at all or starts in the background (it's listed on Tast Manager) but nothing happens. User Account Control pops up when I start it and I click Ok but there is nothing after that. I have tried portable version and 4.2.20 (2021) version but neither works. I went through other peoples issue reports and used the console to start (which also did nothing), Deleted the ini file in APPDATA (still didn't work) and did 3 fresh installs (none of them worked). I am starting to think something in Windows has changed and it will never work again. I've run out of ideas on how to fix this.

**Comment by tonyping** [comment]
Which branch of Windows 11 are you running?

I've been using Windows 11 (canary builds, 10.0.25xxx) and haven't run into any issues regarding Bleachbit not launching. 

Have you perhaps tried checking your Windows Defender logs? There might be something in there that shows Bleachbit being silently blocked by Defender. 

Also, do you have any of the following Microsoft enhanced security features, like Virtualization-based Security, Core Isolation, Firmware Protection, LSA, or Vulnerable Device Driver Blocklist enabled? 

I have most of them on, but not all. But I thought that's another useful avenue for you to check, as they're still sorta in the experimental stage, while also being specifically software-blocking features.

**Comment by az0** [comment]
@barragh  Have you installed many extra fonts on your computer? BleachBit uses a toolkit called GTK which on a few systems has a long, one-time delay. dO YOU SEE high disk usage and/or CPU usage in Task Manager?

If so, one option is to just wait a long time.  A second option is to try the latest pre-release version from https://ci.bleachbit.org . Google incorrectly flags this site as dangerous, but this should be fixed soon. See https://github.com/bleachbit/bleachbit/issues/1506 for details.

**Comment by Bastigonzales** [comment]
same issue here.

>Windows 11 Home
Version	22H2
OS build	22621.2134

**Comment by az0** [comment]
Please test [BleachBit 4.5.0 beta](https://www.bleachbit.org/news/bleachbit-450-beta). Let me know how it goes.

If the application fails to open or takes too long, please answer these questions

1. Have you installed many extra fonts on your computer?
2. Do you see high disk usage and/or CPU usage in Windows Task Manager?

**Comment by Bastigonzales** [comment]
> Please test [BleachBit 4.5.0 beta](https://www.bleachbit.org/news/bleachbit-450-beta). Let me know how it goes.
> 
> If the application fails to open or takes too long, please answer these questions
> 
>     1. Have you installed many extra fonts on your computer?
> 
>     2. Do you see high disk usage and/or CPU usage in Windows Task Manager?

I works great now!! Thank you.

**Comment by az0** [comment]
@Bastigonzales 
Thank you for confirming!

@barragh 
Could you please test the new version?  See previous comment

**Comment by az0** [comment]
No reply from barragh, so I assume it's fixed like for other users.

**Comment by barragh** [comment]
Appologies, I have been very busy offline with my health so my head has been elsewhere. Anyway, your suggestion to wait a while worked and you are correct; The problem is solved now! Again, I am sorry for the delay and the silence.
