### ISSUE TITLE
Strange update error at BleachBit startup on Windows 10

### ISSUE THREAD

**Issue by Gantz5** [bleachbit/bleachbit#1508]
Hi everyone, starting yesterday this strange red message appears everytime I open Bleachbit. The issue start with a problem with Google search (too many search queries and the "I am not a bot" captcha).
BleachBit worked fine before, but when I tried to clean the pc due to this persistent google search behaviour this message appear. Maybe it is a coincidence and they are not related.

I also used CCLeaner due to that Google captcha, maybe it is CCleaner that broke BleachBit? But it never happen before and I have both installed for years... 

Resetting the settings don't solve the issue. Checking the box to update the Winapp2.ini seems to solve the issue yesterday, but today the problem is the same (and now I can search with Google fine).

This is the error message:

```
The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
```

**Comment by az0** [comment]
It has been a few days, and do you still have this error?

Do you know of any firewall or other security software that would stop BleachBit from accessing https://update.bleachbit.org ?

**Comment by az0** [comment]
Closing because no response and not reproducible
