### ISSUE TITLE
Bleachbit clean error [WinError 5] Access denied with Windows Defender

### ISSUE THREAD

**Issue by geo711** [bleachbit/bleachbit#1512]
Just began seeing these errors recently when running Bleachbit clean and the error happens every time.

The Firefox error is because I had it open when I ran the clean process. I am not able to open Windows Defender sub-folders even though I am the only user and have administrator privileges. Not sure if the screenshot worked so I copied the errors from the clean process.

**Screenshots**
![Bleachbit Errors](https://github.com/bleachbit/bleachbit/assets/83181428/9ff06b1f-2a28-4a6d-b9af-3ebc9cfe512b)

Mark for deletion 0B C:\WINDOWS\temp\officeclicktorun.exe_streamserver(202307311239281180).log
[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\History.Log
[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\Unknown.Log
Mark for deletion 433.3kB C:\ProgramData\Microsoft\Windows Defender\Support\MPLog-20230731-123928.log

**Desktop (please complete the following information):**
 - OS: Window 10 Home version 22H2 build 19045.3271
 - BleachBit version 4.4.2

**Comment by igorog** [comment]
OS: Arch Linux x86_64 
      Kernel: 6.4.8-arch1-1

`Error during operation 'system': '[Errno 13] Access denied: '/proc/519/fd/0''
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 345, in run_operations
    for _dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 159, in clean_operation
    for cmd in backends[operation].get_commands(option_id):
  File "/usr/share/bleachbit/Cleaner.py", line 499, in get_commands
    is_open = FileUtilities.openfiles.is_open(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/FileUtilities.py", line 170, in is_open
    self.scan()
  File "/usr/share/bleachbit/FileUtilities.py", line 163, in scan
    for filename in open_files():
  File "/usr/share/bleachbit/FileUtilities.py", line 136, in open_files
    target = os.path.realpath(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 476, in _joinrealpath
PermissionError: [Errno 13] Access denied: '/proc/519/fd/0'`

**Comment by az0** [comment]
@geo711 
There is a past report (https://github.com/bleachbit/bleachbit/issues/1385) of WinError 5 with Windows Defender which has some special settings to protect its files. For now, you can ignore these lines about Windows Defender, or you can disable it by unchecking the box labeled Windows Defender.

The rules for cleaning Windows Defender come from the winapp2.ini file, which is maintained by the community and used in multiple cleaning applications.

@igorog 
Please open a separate ticket because the original issue here is specific to Windows Defender and the Windows platform

**Comment by geo711** [comment]
@az0 Thank you for the reply and the explanation. I will close this issue. Strangely, I am able to open the Windows Defender sub-folders i.e. scan and quarantine on my laptop, but not on my desktop computer. ??
