### ISSUE TITLE
Correct %WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\

### ISSUE THREAD

**Issue by elgatov** [bleachbit/bleachbit#1514]
Hi,

I believe 
`%WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\`, should be corrected to:
`%WinDir%\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\`. 

When I changed it in my `internet_explorer.xml`, bleachbit was able to find the folder and clean it.

Regards.

**Comment by az0** [comment]
Fixed in 12faf534b888ea5f43e71b2bbb2e66e89a150548

**Comment by az0** [comment]
@elgatov 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix for MS Internet Explorer.  Please test and let me know how it goes.

**Comment by elgatov** [comment]
will report as soon as i can

thanks!

**Comment by elgatov** [comment]
> @elgatov [BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix for MS Internet Explorer. Please test and let me know how it goes.

v4.5.0 beta correctly found and deleted all the files in `%WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\`, so it's **fixed**

thank you!

**Comment by az0** [comment]
@elgatov 
Thank you for confirming the fix.
