### ISSUE TITLE
Error during operation 'system': '[Errno 13] Access denied

### ISSUE THREAD

**Issue by igorog** [bleachbit/bleachbit#1515]
OS: Arch Linux x86_64
Kernel: 6.4.8-arch1-1
BleachBit version 4.4.2

`Error during operation 'system': '[Errno 13] Access denied: '/proc/519/fd/0'' Traceback (most recent call last): File "/usr/share/bleachbit/Worker.py", line 345, in run_operations for _dummy in self.clean_operation(operation): File "/usr/share/bleachbit/Worker.py", line 159, in clean_operation for cmd in backends[operation].get_commands(option_id): File "/usr/share/bleachbit/Cleaner.py", line 499, in get_commands is_open = FileUtilities.openfiles.is_open(path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/share/bleachbit/FileUtilities.py", line 170, in is_open self.scan() File "/usr/share/bleachbit/FileUtilities.py", line 163, in scan for filename in open_files(): File "/usr/share/bleachbit/FileUtilities.py", line 136, in open_files target = os.path.realpath(filename) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen posixpath>", line 416, in realpath File "<frozen posixpath>", line 476, in _joinrealpath PermissionError: [Errno 13] Access denied: '/proc/519/fd/0'`

Appeared after the recent rolling update. I suspect that there is some kind of incompatibility in the Python code. There were no such error messages before.

**Comment by tekstryder** [comment]
Seeing this recently myself.

```
Exception while running operation 'system': '[Errno 13] Permission denied: '/proc/1257/fd/0''
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 345, in run_operations
    for _dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 159, in clean_operation
    for cmd in backends[operation].get_commands(option_id):
  File "/usr/share/bleachbit/Cleaner.py", line 499, in get_commands
    is_open = FileUtilities.openfiles.is_open(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/FileUtilities.py", line 170, in is_open
    self.scan()
  File "/usr/share/bleachbit/FileUtilities.py", line 163, in scan
    for filename in open_files():
  File "/usr/share/bleachbit/FileUtilities.py", line 136, in open_files
    target = os.path.realpath(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 476, in _joinrealpath
PermissionError: [Errno 13] Permission denied: '/proc/1257/fd/0'
```

**Comment by Ciniko** [comment]
Debian 13 XFCE
Kernel 6.4.0-2-amd64
BleachBit 4.4.2



Exception while running operation 'system': '[Errno 13] Permission denied: '/proc/939/fd/0''
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 345, in run_operations
    for _dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 159, in clean_operation
    for cmd in backends[operation].get_commands(option_id):
  File "/usr/share/bleachbit/bleachbit/Cleaner.py", line 499, in get_commands
    is_open = FileUtilities.openfiles.is_open(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 170, in is_open
    self.scan()
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 163, in scan
    for filename in open_files():
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 136, in open_files
    target = os.path.realpath(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 476, in _joinrealpath
PermissionError: [Errno 13] Permission denied: '/proc/939/fd/0'


And trash is not being cleaned

**Comment by Winterhuman** [comment]
Also experiencing this issue: Arch Linux, `linux 6.4.12-arch1-1`, `bleachbit 4.4.2` (identical logs to the above reports down to the problematic lines printed, with only the PID value being different)

To add to this report, the PID it's complaining about turns out to be `/usr/lib/systemd/systemd --user`, not sure what to make of this

**Comment by az0** [comment]
You can [try this patch](https://github.com/bleachbit/bleachbit/commit/a00790997dfd57da9a44255477548d7297525ef1) by [running from source](https://docs.bleachbit.org/dev/running-from-source-code.html), simply editing the FileUtilities.py file with a text editor, or waiting for the next release

**Comment by tekstryder** [comment]
Confirmed applying this patch on top of bleachbit 4.4.2 no longer generates this error. Thanks!

**Comment by Ciniko** [comment]
Got the message forgot my manners. 

"simply editing the FileUtilities.py file with a text editor"

 did the trick, thank you.
