### ISSUE TITLE
Error cleaning Chrome for "autofill_profile_names"

### ISSUE THREAD

**Issue by francis670** [bleachbit/bleachbit#1518]
Hi everyone, since this morning I have Bleachbit (last version from the main site, no beta) raising a single red error (code at the end of the post) after the cleaning process. I'm on Windows 10 64 bit.

I uninstalled and reinstalled Bleachbit two times, I cleaned and resetted the Bleachbit settings but the error persist. The issue is still there and yesterday evening was not present (0 error last night vs 1 error this morning).

I tried opening with the notepad the file cited in the code below (Web Data), the format is messy but some writings state that it is some sort of sqlite database (I'm not in IT, I only tried to open it). If I search into this file for "autofill_profile_names", the notepad search result in nothing found. So maybe the error is because indeed that line of text/table/"whatever it is" is missing in Web Data?

This morning Chrome prompted me to personalise my settings with a giant popup after I launched the browser. I click Skip since I don't want to personalise or put personal information into Chrome.
I have now version 116, maybe they changed something and now that particular line is outdated?

As I've already said, I'm not in IT so I'm only brainstorming.
I've run Windows defender to stay safe, thinking maybe it was a malware that edited or tried to steal some Chrome configuration files or session information... If I google for "autofill_profile_names" I found something called Acridrain that in 2018 was used to steal cookie, session token, password, autofill information like credit card and address and so on.

I don't use Chrome with personal information (I disable most settings) and three differetn AV scans found nothing, so I start to think that it is related to Chrome itself.

Can someone actually confirm if this error is due to Chrome update, maybe also on their system, or is something affecting my machine only? I use this PC as a teacher so I would like some reassurance that the problem was indeed not a real problem but only Google changes...

Thanks

This is the red message:

```
Error: google_chrome.form_history: Function: Clean the file: C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'
```

**Comment by Tianle-Leviathan** [comment]
Google has changed the autofill related table names in version 116.
- autofill_profile_emails
- autofill_profile_names
- autofill_profile_phones
becomes 
- autofill_model_type_state
- autofill_sync_metadata

**Comment by 0pLuS0** [comment]
It's not just a Google issue, I get thos also for MS Edge.

https://github.com/bleachbit/bleachbit/issues/1529

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release.

**Comment by az0** [comment]
@francis670 
@Tianle-Leviathan 

For the "no such table" issue, there is a fix available for testing. Windows users can find a link to the binaries on the release notes page where it mentions the ["no such table" issue](https://www.bleachbit.org/news/bleachbit-442#no_such_table). Let me know how it goes.
