### ISSUE TITLE
Error: brave.form_history

### ISSUE THREAD

**Issue by Krakensnv** [bleachbit/bleachbit#1520]
Hello there,

After last Brave-Browser update I got this Error message:
------------------------------------------------------------------------------------
Error: brave.form_history: Function: Clean file: /home/agnes/.config/BraveSoftware/Brave-Browser/Default/Web Data
Traceback (most recent call last):
  File "/usr/share/bleachbit/FileUtilities.py", line 474, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 106, in delete_chrome_autofill
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 482, in execute_sqlite3
    '%s: %s' % (exc, path))
sqlite3.OperationalError: no such table: autofill_profile_names: /home/agnes/.config/BraveSoftware/Brave-Browser/Default/Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    if -1 == e.message.find('file is encrypted or is not a database') and \
AttributeError: 'OperationalError' object has no attribute 'message'
-----------------------------------------------------------------------------------------------------
I've been using Brave and BleachBit for years without any issues. Do I understand well that Brave has changed or removed  the table name? Is it possible to change it in BleachBit files?
Thanks in advance for your reply.
Regards,

**Comment by dmitriy1980** [comment]
From another post:

Google has changed the autofill related table names in version 116.

autofill_profile_emailsautofill_profile_namesautofill_profile_phones
becomesautofill_model_type_stateautofill_sync_metadata

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release.

**Comment by az0** [comment]
@Krakensnv 

[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.  Please test and let me know how it goes.
