### ISSUE TITLE
Unstable v4.5.0.2 485 - Prompting to update to 4.4.2

### ISSUE THREAD

**Issue by m0lz** [bleachbit/bleachbit#1521]
Win 11 fresh install.
Installed for the first time Bleachbit Unstable version 4.5.0.2 485.
After installing and doing its first run on this machine .. It immediately prompts me to "Update Bleachbit. A new version is available. v4.4.2", which is older than the installation.

**Comment by az0** [comment]
Thank you for the report.

I fixed it. There's no need for you to update or reinstall anything: just open the application.

**Comment by m0lz** [comment]
Fix confirmed :) (I have not updated)
I no longer get the prompt to update.
