### ISSUE TITLE
Unstable v4.5.0.2 485 - Error when cleaning: "sqlite3.OperationalError: no such table"

### ISSUE THREAD

**Issue by m0lz** [bleachbit/bleachbit#1522]
Win 11 fresh install of the OS
Brave browser being used as default Browser.

Bleachbit v4.5.0.2 485 configured to clean ..
Brave Cache / Cookies / Dom storage / Form history / History

When cleaning I receive the following error ..

Error: brave.form_history: Function: Clean file: C:\Users\terri\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 164, in execute
  File "bleachbit\Special.pyo", line 119, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\terri\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 166, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by 0pLuS0** [comment]
I see the same type of issue with MS Edge, with the stable version, this doesn't seem like a coincidence.

https://github.com/bleachbit/bleachbit/issues/1529

**Comment by dmitriy1980** [comment]
Root case was explained here: https://github.com/bleachbit/bleachbit/issues/1518#issuecomment-1684691066

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release.

**Comment by az0** [comment]
@m0lz 

For the "no such table" issue, there is a fix available for testing. Windows users can find a link to the binaries on the release notes page where it mentions the ["no such table" issue](https://www.bleachbit.org/news/bleachbit-442#no_such_table). Let me know how it goes.

**Comment by m0lz** [comment]
Fix confirmed on Brave, using BleachBit-4.5.0.2493-setup-English.exe :)
Thank you.

**Comment by az0** [comment]
@m0lz 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix, plus it has changes since the original fix.  Please test and let me know how it goes.

**Comment by m0lz** [comment]
Yep I am on 4.5.0.2499 for the last week, no further issues found so far.

**Comment by az0** [comment]
@m0lz 
Thank you
