### ISSUE TITLE
Error in Google Chrome when cleaning: "sqlite3.OperationalError: no such table"

### ISSUE THREAD

**Issue by githubgomer** [bleachbit/bleachbit#1523]
I've starting getting the error shown in the accompanying screen shot. Any idea what's wrong?
![Capture](https://github.com/bleachbit/bleachbit/assets/89647126/32e2cee7-43d9-4ae1-8537-afaadbc5253f)

**Comment by rados** [comment]
@githubgomer, thank you for this report.

@az0 Seems like this happens often. I can work on it. There are three more issues related - #1522, #1520, #1518.

**Comment by 0pLuS0** [comment]
Add another issue related...

https://github.com/bleachbit/bleachbit/issues/1529

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release.

**Comment by az0** [comment]
@githubgomer 

For the "no such table" issue, there is a fix available for testing. Windows users can find a link to the binaries on the release notes page where it mentions the ["no such table" issue](https://www.bleachbit.org/news/bleachbit-442#no_such_table). Let me know how it goes.

**Comment by az0** [comment]
@githubgomer 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.  Please test and let me know how it goes.
