### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

### ISSUE THREAD

**Issue by nico92GitHub** [bleachbit/bleachbit#1527]
Hello dev
v4.4.2.0, win10, something is wrong at start, see below...;

The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by Demonbob** [comment]
Having the Same Error 
V4.4.2.0, Windows 11 i uninstalled restarted and Reinstalled but the Error is still there.

The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by nico92GitHub** [comment]
Yes, I did like you (uninstall/reinstall) and the error recurs, BUT not on every launch?
I'm not sure, but it's likely that when the error happened once, on the next launch it doesn't happen...
Nico

**Comment by az0** [comment]
Does it go away if you turn off the preference option to check for updates, close the application, and restart the application?

**Comment by nico92GitHub** [comment]
As I said above, the error does not occur on every startup.
In order to try your proposal to uncheck the search for updates, during this launch there was no error.
However, as I launch Bleachbit several times a day, I will come back to you to tell you the result over a longer period.

**Comment by az0** [comment]
@nico92GitHub @Demonbob 

What does [this update page](https://update.bleachbit.org/update/4.4.2) look like when you open it in a web browser? Does it look like this? 

![image](https://github.com/bleachbit/bleachbit/assets/933680/aeb058dd-45e3-442a-91de-95a2847240ce)

**Comment by az0** [comment]
Do you use a VPN or Tor? If so, does this error still happen without it?

**Comment by nico92GitHub** [comment]
@nico92GitHub @Demonbob 

What does [this update page](https://update.bleachbit.org/update/4.4.2) look like when you open it in a web browser? Does it look like this? 

![image](https://github.com/bleachbit/bleachbit/assets/933680/aeb058dd-45e3-442a-91de-95a2847240ce)

**Comment by nico92GitHub** [comment]
Sorry, no VPN or Tor. No installation of new software.

My configuration is the same as when there was not this error.
![ScreenShot_001](https://github.com/bleachbit/bleachbit/assets/22394276/e57345b4-edd6-4ed3-ac6b-3bb60b014278)

I confirm, this error does not reproduce systematically, with or without the search for a new update.

[BleachBit.pdf](https://github.com/bleachbit/bleachbit/files/12467817/BleachBit.pdf)

**Comment by az0** [comment]
I made a change on the update server. Have you seen this error in the last ~36 hours?

**Comment by nico92GitHub** [comment]
No, no errors for at least 36 hours, with and without the option to check for updates.
Andrew, I believe you found the origin :) cross fingers!
