### ISSUE TITLE
BleachBit errors at cleaning time: "The update information does not parse"

### ISSUE THREAD

**Issue by MichelRobitaille** [bleachbit/bleachbit#1528]
Just want to make you aware of errors.
Regards,
Michel

When Bleachbit is launched with Clean there is a list of errors such as 

The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by az0** [comment]
@MichelRobitaille 
Are you on Windows or Linux? Are you using BleachBit version 4.4.2 (stable)?

**Comment by MichelRobitaille** [comment]
I am on Windows 11 fully patched e.g., 22H2 installed on 5/‎18/‎2023
OS Build 22621.2215
Windows Feature Experience Pack 1000.22662.1000.0

Running BleachBit 4.4.2 (stable)

Regards,

**Comment by az0** [comment]
@MichelRobitaille 

What does [this update page](https://update.bleachbit.org/update/4.4.2) look like when you open it in a web browser? Does it look like this, or at least close? 

![image](https://github.com/bleachbit/bleachbit/assets/933680/aeb058dd-45e3-442a-91de-95a2847240ce)

Does this error happen every time you open BleachBit? Other people reported it happens only sometimes.

Does it happen if you pause/disable any antivirus/security/firewall?  It is happening when BleachBit is contacting a server to check for updates, so a workaround is to disable the preference to check for updates.

**Comment by MichelRobitaille** [comment]
Hi,

I will answer through your message see below

**Comment by MichelRobitaille** [comment]
I don't use VPN and Tor.

**Comment by az0** [comment]
I made a change on the update server. Have you seen this error in the last ~36 hours?

**Comment by MichelRobitaille** [comment]
No. I think the change you made resolved the issue.

I will watch over the next few days and if I see it, I will contact you.

After if I don't write to you, consider this as fixed.

Regards,

**Comment by MichelRobitaille** [comment]
Hello,

The error disappeared as I mentioned before.

That said over the last 2-3 days this one appeared (no idea)

Regards,

Error: microsoft_edge.form_history: Function: Clean file: C:\Users\User\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\User\AppData\Local\Microsoft\Edge\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by rados** [comment]
@MichelRobitaille, this is a famous one, we are working on a fix.

**Comment by MichelRobitaille** [comment]
Thanks.

Good luck.

Regards,

**Comment by az0** [comment]
I made a change that some users confirmed, so I am closing this. If you see the same "update information does not parse" error, reopen this ticket or make a new one
