### ISSUE TITLE
Error MS Edge - Windows 11 22H2: "sqlite3.OperationalError: no such table"

### ISSUE THREAD

**Issue by 0pLuS0** [bleachbit/bleachbit#1529]
**Describe the bug**

I'm using Windows 11 Home 22H2 with Bleachbit 4.4.2 I believe a recent Windows update has now broken Bleachbit support for MS Edge. 

When I added all of MS Edge in Bleachbit and run Bleachbit, I always receive an error message. I uninstalled and reinstalled Bleachbit it did not help, I still receive the message in Bleachbit.

**To Reproduce**
1. Add MS Edge in Bleachbit
2. Click Preview then Click Clean
3. Now the error message appears.

Error: microsoft_edge.form_history: Function: Clean file: C:\Users\FOO\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\FOO\AppData\Local\Microsoft\Edge\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**The error happens (sometimes/every time).**

This error happens every time.

**Expected behavior**

I should not see this error message.

**Screenshots**
I pasted the output above, it looks exactly the same...

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 22H2
 - BleachBit version 4.4.2

**Additional context**
Nothing...

```There's nothing wrong with my system, I've been using Bleachbit in Windows 11 for as long as it's been around. I only started to see this message in the past few months. I believe a Windows update broke this...```

``` What's the worst case scenario using the Unstable Builds in Windows, that can happen to the system? I was thinking to just use these, as I didn't think an app like this can destroy anything in the system, or can it? I was hoping maybe this is corrected in an Unstable Build?```

```Also, besides only have Unstable Builds, what about Releasing a Beta Version, that won't mess up anything as bad as Alpha might?```

**Comment by dmitriy1980** [comment]
Root case was explained here: https://github.com/bleachbit/bleachbit/issues/1518#issuecomment-1684691066

**Comment by 0pLuS0** [comment]
> Root case was explained here: [#1518 (comment)](https://github.com/bleachbit/bleachbit/issues/1518#issuecomment-1684691066)

I have no idea what this ```Root Case``` means, since that post is about Chrome, my issue is with MS Edge.

**Comment by dmitriy1980** [comment]
What it essentially is saying is that Chrome has changed the internal structure in how they store the autofill-related data like emails, names, etc. Since MS Edge is a Chromium-based browser (it's internal engine is based on Chrome) just like Brave and many others, they are all impacted and have the same issue.

Correct, Bleachbit will need to make changes to reference the elements provided in the link. Hope this gives a bit more clarity on the issue.

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release. If more detail is needed for the notice, let me know.

**Comment by az0** [comment]
@0pLuS0 

For the "no such table" issue, there is a fix available for testing. Windows users can find a link to the binaries on the release notes page where it mentions the ["no such table" issue](https://www.bleachbit.org/news/bleachbit-442#no_such_table). Let me know how it goes.

**Comment by az0** [comment]
@0pLuS0 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.  Please test and let me know how it goes.
