### ISSUE TITLE
4.4.2 The update information does not parse

### ISSUE THREAD

**Issue by bulgin** [bleachbit/bleachbit#1530]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

**To Reproduce**

The error happens (sometimes/every time).
every time running as root in ubuntu 22.04
**Expected behavior**
I do not expect to see:
The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - Ubuntu 22.04
 - BleachBit version [e.g., 4.2.0]
4.2.2
**Additional context**

**Comment by bulgin** [comment]
Full response when running BleachBit as root on ubuntu 22.04.
The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb"
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Update.py", line 165, in check_updates
    dom = xml.dom.minidom.parseString(doc)
  File "/usr/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by Mattdp13** [comment]
I have this same issue:
The update information does not parse: <<long string>>
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Update.py", line 165, in check_updates
    dom = xml.dom.minidom.parseString(doc)
  File "/usr/lib/python3.10/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.10/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by Mattdp13** [comment]
I am using Linux (Mint 21.1) and using 4.4.2 stable.  update page matches what you (az0) posted.

Note: the issue I reported seems to have "disappeared" -- I've launched bleachbit a number of times (regular user and as root) and am no longer getting the error....  ;)

**Comment by az0** [comment]
FYI: I added a [notice to the BleachBit v4.4.2 release notes](https://www.bleachbit.org/news/bleachbit-442#does_not_parse). This error is not consistently reproducible, and the root cause is still under investigation.

**Comment by az0** [comment]
Do you use a VPN or Tor? If so, does this error still happen without it?

**Comment by Mattdp13** [comment]
I am still not getting the error message when I run bleachbit -- Up until yesterday afternoon --> I was getting the message each and every time I launched bleachbit.  I normally do not use TOR/VPN... but I did try with VPN just now and no error message.

**Comment by az0** [comment]
I made a change on the update server. Have you seen this error in the last ~36 hours?

**Comment by bulgin** [comment]
No I have not and wondered what happened? I guess you;ve fixed it?
 Thank you.

-----Original Message-----
From: Andrew Ziem ***@***.***>
Reply-To: bleachbit/bleachbit
***@***.***>
To: bleachbit/bleachbit ***@***.***>
Cc: bulgin ***@***.***>, Mention ***@***.***>
Subject: Re: [bleachbit/bleachbit] 4.4.2 The update information does
not parse (Issue #1530)
Date: Thu, 31 Aug 2023 19:37:13 -0700

I made a change on the update server. Have you seen this error in the
last ~36 hours?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by Mattdp13** [comment]
I have not seen the error...
Thank you.

**Comment by az0** [comment]
@Mattdp13 
Thank you for confirming.

By the way, you might want to try the new release https://www.bleachbit.org/news/bleachbit-450-beta
