### ISSUE TITLE
Every time I open BleachBit I get a lot of error messages in red: "The update information does not parse"

### ISSUE THREAD

**Issue by BillyBobMcInbredYahoo** [bleachbit/bleachbit#1532]
I'm using BleachBit on Windows 10 Home.

Every time I open BB I get the following wall of text in red:

The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

I have BB set to accept updates.

Firstly, what does all that text above mean?

And secondly how can I get the issue(s) fixed so that I don't see these messages every time I open BB?

**Comment by az0** [comment]
See the known issues section of the [BleachBit version 4.4.2 release notes](https://www.bleachbit.org/news/bleachbit-442#does_not_parse).

If you can think of any information that can explain why it happens to you (sometimes or always) to help reproduce the issue, let me know.

Does it happen every time you open BleachBit?

Do you use a VPN or Tor?

Do you use any network security software that may block or interfere with BleachBit's attempts to check for updates?

**Comment by BillyBobMcInbredYahoo** [comment]
Thanks for your reply. My mistake, I was being gormless, I wasn't even online at the time.
However, it would be useful for BleachBit to say "You're not online numbnuts, so can't update".
Or to have a setting that allows cleaning without updating first.
Or both.

Btw what's the BB setting that deals with icons in the Firefox Bookmarks Toolbar? - some but not all of the icons have been replaced with a generic one (why only some?), but when I go to the site in question the icon is replaced with the correct one (obviously).

One last question:
I get these error messages when running BB:
Error: google_chrome.form_history: Function: Clean file: C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

---

Re "sqlite3.OperationalError: no such table", why is BB trying to clean a non-existent table?

Re "AttributeError: 'OperationalError' object has no attribute 'message'", could explain what that means please? And what might be causing that issue?

Thanks.

**Comment by az0** [comment]
>My mistake, I was being gormless, I wasn't even online at the time.
>However, it would be useful for BleachBit to say "You're not online numbnuts, so can't update".


When the user starts BleachBit while the user is offline, the expected error message is this:

> Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [Errno 11001] getaddrinfo failed>

After disconnecting the network, I just tested it with BleachBit version 4.4.2 on Windows, and it worked. 

Other users are reporting the "does not parse" error message even when they seem to be online. I made a change on the update server. Have you seen this error in the last ~36 hours? If you see the "does not parse" again, please reply here in ticket 1532.

> Or to have a setting that allows cleaning without updating first. 

After showing either the "does not parse" or "error when opening a network connection" message, BleachBIt should continue to work just fine.

>One last question:
>I get these error messages when running BB:
>Error: google_chrome.form_history: Function: Clean file: C:\Users\User\AppData\Local\Google\Chrome\User >Data\Default\Web Data
>Traceback (most recent call last):
>File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
>sqlite3.OperationalError: no such table: autofill_profile_names

To help manage issues, let's limit each ticket to one problem. 

For more information about the "no such table," please see the [release notes: no such table](https://www.bleachbit.org/news/bleachbit-442#no_such_table)

**Comment by BillyBobMcInbredYahoo** [comment]
"When the user starts BleachBit while the user is offline, the expected error message is this:

    Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [Errno 11001] getaddrinfo failed>"

Yeah, that's what I'm seeing now when I'm offline.

"Other users are reporting the "does not parse" error message even when they seem to be online. I made a change on the update server. Have you seen this error in the last ~36 hours? If you see the "does not parse" again, please reply here in ticket 1532."

No, I've not seen the "does not parse" error message in the past couple of days, so it seems you've fixed the issue. Thanks.

"To help manage issues, let's limit each ticket to one problem."

OK I'll open another ticket for the other issue.

"For more information about the "no such table," please see the [release notes: no such table](https://www.bleachbit.org/news/bleachbit-442#no_such_table)"

OK good, so it'll be fixed in the next update.
Thanks again.

**Comment by BillyBobMcInbredYahoo** [comment]
This issue can be closed now as it's been resolved. Thanks.

**Comment by Jigoku** [comment]
This is still an issue in 4.6.0. It happened to me just now: 
![image](https://github.com/bleachbit/bleachbit/assets/1535179/7391a038-d33f-42be-b7da-56e10bcb3b88)
