### ISSUE TITLE
AttributeError: 'OperationalError' object has no attribute 'message'

### ISSUE THREAD

**Issue by BillyBobMcInbredYahoo** [bleachbit/bleachbit#1534]
When running a BB clean I get the following error message:

During handling of the above exception [no such table (in Chrome)], another exception occurred:

Traceback (most recent call last):
File "bleachbit\Worker.pyo", line 87, in execute
File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

The error happens every time I run a BB cleanup.

**Expected behavior**
Not to see this error message.

**Screenshots**
I tried to drag and drop a JPEG screenshot but got this error message:
![BB error message](https://github.com/bleachbit/bleachbit/assets/143556946/f427be42-4312-432b-93bc-f71201ec3bc4)

Tried to copy & paste the screenshot and got this error message:
![BB error message](https://github.com/bleachbit/bleachbit/assets/143556946/f946067b-e5d6-439f-9494-5023d3e9a700)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (up to date)
 - BleachBit version: 4.4.2

Well that's weird, I got error messages trying to add the screenshots, but they showed up find after clicking on "Comment".
The error messages were:
"![BB error message](https://github.com/bleachbit/bleachbit/assets/143556946/f427be42-4312-432b-93bc-f71201ec3bc4)"
"![BB error message](https://github.com/bleachbit/bleachbit/assets/143556946/f946067b-e5d6-439f-9494-5023d3e9a700)"

I can't even tell you the error messages by putting them in quotes.
OK, let's try removing the exclamation mark and BB error message part in square brackets, and removing the start of the web address:
/bleachbit/bleachbit/assets/143556946/f427be42-4312-432b-93bc-f71201ec3bc4)
/bleachbit/bleachbit/assets/143556946/f946067b-e5d6-439f-9494-5023d3e9a700)

**Comment by az0** [comment]
@BillyBobMcInbredYahoo 

For the "no such table" issue, there is a fix available for testing. Windows users can find a link to the binaries on the release notes page where it mentions the ["no such table" issue](https://www.bleachbit.org/news/bleachbit-442#no_such_table). Let me know how it goes.

**Comment by BillyBobMcInbredYahoo** [comment]
Thank you so much, I installed the fix and am now getting no error messages at all.
Wow, you fixed that fast. Kudos.

FYI, I scanned the exe file (BleachBit-4.5.0.2493-setup.exe) using VirusTotal and 2 antimalware companies (that I've never heard of) flagged it as malware. I contacted them to report a possible false positive. This happens sometimes, especially with the lesser known malware companies.

A couple of questions:

- Any idea what was going on with the error messages when I was trying to add the screenshots? I got error messages when trying to drag & drop and paste the screenshots, but after clicking on "Comment" the screenshots appeared just fine.

- How come you put the fix on Appveyor and not Github?

- I still have an issue where some of the icons in the Bookmarks Toolbar in Firefox are replaced with generic icons after running a BB cleanup (generally Gmail, Mojeek and Amazon Prime Video, plus a couple of other ones). It's not a huge issue, but I'm confused as to (a) what's causing this (which Firefox tickboxes in BB?) and (b) why only some of the bookmark icons are replaced with generic ones, not all of them.

Thanks again

**Comment by az0** [comment]
> Thank you so much, I installed the fix and am now getting no error messages at all. Wow, you fixed that fast. Kudos.

You are welcome, and thank you for confirming.

> FYI, I scanned the exe file (BleachBit-4.5.0.2493-setup.exe) using VirusTotal and 2 antimalware companies (that I've never heard of) flagged it as malware. I contacted them to report a possible false positive. This happens sometimes, especially with the lesser known malware companies.

Yes, that's an ongoing issue with so many malware scanners that use heuristics. Thanks for reporting it.

> 
> * Any idea what was going on with the error messages when I was trying to add the screenshots? I got error messages when trying to drag & drop and paste the screenshots, but after clicking on "Comment" the screenshots appeared just fine.

It sounds like you got an error from GitHub, but I see the same screenshot of BleachBit posted multiple times. No, I am not sure what happened.

> * How come you put the fix on Appveyor and not Github?

AppVeyor builds binaries for Windows for every commit to BleachBit. If they are not pull requests, they are published also on https://ci.bleachbit.org . This CI system provides rapid testing.

> * I still have an issue where some of the icons in the Bookmarks Toolbar in Firefox are replaced with generic icons after running a BB cleanup (generally Gmail, Mojeek and Amazon Prime Video, plus a couple of other ones). It's not a huge issue, but I'm confused as to (a) what's causing this (which Firefox tickboxes in BB?) and (b) why only some of the bookmark icons are replaced with generic ones, not all of them.

Hmm, please create a separate ticket, so I can close this one out for the original issue "no such table."

**Comment by BillyBobMcInbredYahoo** [comment]
"You are welcome, and thank you for confirming."

No probs.

"Yes, that's an ongoing issue with so many malware scanners that use heuristics. Thanks for reporting it."

You're welcome.

"It sounds like you got an error from GitHub, but I see the same screenshot of BleachBit posted multiple times. No, I am not sure what happened."

Could you please contact GitHub to try and determine the cause of this problem? And how to fix it?

As I wrote earlier:

I can't even tell you the error messages by putting them in quotes.
OK, let's try removing the exclamation mark and BB error message part in square brackets, and removing the start of the web address:
/bleachbit/bleachbit/assets/143556946/f427be42-4312-432b-93bc-f71201ec3bc4)
/bleachbit/bleachbit/assets/143556946/f946067b-e5d6-439f-9494-5023d3e9a700)

That may not mean anything to you, but maybe it might to someone (clued-up) from GitHub?

Have **you** ever experienced the same issue when trying to drag & drop or paste a screenshot?
I don't know if it's relevant, but I use uBlock Origin in Firefox on Windows 10.

"AppVeyor builds binaries for Windows for every commit to BleachBit. If they are not pull requests, they are published also on https://ci.bleachbit.org/ . This CI system provides rapid testing."

Um, I can't say I understand that, but thanks for the reply anyway!
Terms I don't understand:
- binary (does that mean an exe file?)
- commit
- pull request
- CI system (what does CI stand for?)

If you could explain those terms to me like I'm 5 years old, great, but if you're too busy, fine.

"Hmm, please create a separate ticket, so I can close this one out for the original issue "no such table.""

OK, will do.

Thanks again.

**Comment by BillyBobMcInbredYahoo** [comment]
Screenshot of screenshot errors!


![Screenshot](https://github.com/bleachbit/bleachbit/assets/143556946/d3a2b898-8470-4eb3-9b02-b88cd3d0c06b)

**Comment by az0** [comment]
> "It sounds like you got an error from GitHub, but I see the same screenshot of BleachBit posted multiple times. No, I am not sure what happened."
> 
> Could you please contact GitHub to try and determine the cause of this problem? And how to fix it?

Your screenshot helped. The text you are seeing is called Markdown. It's a sort of code for formatting including bold, italics, lists, and images, so it looks normal.

> "AppVeyor builds binaries for Windows for every commit to BleachBit. If they are not pull requests, they are published also on https://ci.bleachbit.org/ . This CI system provides rapid testing."
> 
> Um, I can't say I understand that, but thanks for the reply anyway! Terms I don't understand:
> 
> * binary (does that mean an exe file?)
> * commit
> * pull request
> * CI system (what does CI stand for?)

Yes, binary is an exe. It's easy for end users (like yourself) to use.

Commit: a small unit of code tracked in GitHub. It's themed around a small purpose, like fixing one bug.

Pull request: a set of commits from a third party contributor, like a volunteer

CI system: AppVeyor is a continuous integration system that runs automated tests and builds binaries, so users who want bleeding-edge (untested) versions can test them. It's like Mozilla Nightly: you can try whatever code changes just happened. It might be broken, or it might have something useful.

**Comment by BillyBobMcInbredYahoo** [comment]
Thanks for the explanations re the terminology.

"Your screenshot helped. The text you are seeing is called Markdown. It's a sort of code for formatting including bold, italics, lists, and images, so it looks normal."

Yeah my mistake. These aren't error messages as I originally thought, but I was expecting the screenshot to appear in the comment box the moment I dragged & dropped it (or pasted it) as opposed to that Markdown text appearing. As things currently stand, the screenshot only appears after clicking on the Comment button, which is unusual behaviour since I'm used to images appearing in emails the moment I paste them.

Could you have a word with GitHub please and get them to change it so that the screenshot appears the moment it's dropped or pasted?
