### ISSUE TITLE
It's almost two years without any stable releases

### ISSUE THREAD

**Issue by gracie95** [bleachbit/bleachbit#1538]
Some cleaning options might be not work and too many warnings after cleaning.

**Comment by az0** [comment]
>It's almost two years without any stable releases 

Yes, I am working on a beta release.

> Some cleaning options might be not work and too many warnings after cleaning.

OK, please file one ticket for each kind of issue.

**Comment by az0** [comment]
@gracie95 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has been released
