### ISSUE TITLE
No new Releases since Nov 14, 2021

### ISSUE THREAD

**Issue by Anutrix** [bleachbit/bleachbit#1540]
**Describe the bug**
There haven't been any releases in the past 2 years despite there being commits.

**To Reproduce**
1. Go to https://github.com/bleachbit/bleachbit/releases.
2. Find out that latest version 4.4.2 is from Nov 14, 2021.

The error happens (sometimes/every time).

**Expected behavior**
A new release at least once a year. There have been lot's of commits since last release.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04] Windows/NA
 - BleachBit version [e.g., 4.2.0] 4.4.2

**Additional context**
If there's some be refactor going on for 5.0, wish it was a pinned issue or mentioned in the README.md.

**Comment by rados** [comment]
Good ideas. :)

**Comment by az0** [comment]
Yes, it has been too long, and I would like to release more often than once per year. Try [BleachBit 4.5.0 beta](https://www.bleachbit.org/news/bleachbit-450-beta)

**Comment by hbednar** [comment]
@az0 
Have you considered using github actions, as it may make things quicker and easier.

**Comment by az0** [comment]
Use them for what?

**Comment by hbednar** [comment]
> Use them for what?

To automate the build and release process and if possible schedule it to happen automatically.

**Comment by az0** [comment]
> To automate the build and release process and if possible schedule it to happen automatically.

Have you seen the [CI build site](https://ci.bleachbit.org/)?

**Comment by hbednar** [comment]
No i haven't thanks. So you are using your own infrastructure to do this already.

Unless i have missed them they only seem to be Windows packages and no Linux.

**Comment by az0** [comment]
Yes, this is Windows only. The plan for Linux was to[ integrate with the OBS](https://github.com/bleachbit/bleachbit/issues/1171)
