### ISSUE TITLE
Module not Found (BleachBit version 4.5.0 beta) 

### ISSUE THREAD

**Issue by Utenet** [bleachbit/bleachbit#1543]
bleachbit_4.5.0-0_all_ubuntu2004.deb
bleachbit_4.5.0-0_all_debian12.deb   
bleachbit_4.5.0-0_all_ubuntu2304.deb
bleachbit_4.5.0-0_all_ubuntu1804.deb

All 4.5.0 betas above appear to install with GDebi without any errors, but later exit without cleaning:

`user@lap:~$ bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 28, in <module>
    from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
user@lap:~$`

================================================================
System:
  Kernel: 5.15.0-83-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

**Comment by Utenet** [comment]
UPDATE:
======

Had previously been using GDebi packages. Recently used no-Debi "bleachbit-4.5.0.tar.gz" `[ https://download.bleachbit.org/beta/4.5.0/bleachbit-4.5.0.tar.gz ].`

This seems to work with no problems. I'll test more and report any issues.

**Comment by az0** [comment]
I am hearing you resolved this yourself, so I will close this ticket.

**Comment by Utenet** [comment]
Sure Andrew,

I wasn't sure whether to close it or not. The flatpaks still don't work for me.
My solution was just to use the Mint Package Manager version (non-flatpak).

------- Original Message -------
