### ISSUE TITLE
BleachBit error at cleaning time other scripts issues

### ISSUE THREAD

**Issue by MichelRobitaille** [bleachbit/bleachbit#1544]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).
There are a series of scripts errors at execution time when Delete is activated.

**To Reproduce**
1. Start BleachBit in administrator mode
2. Click on "Delete@
4. The error  shows up such as 
Clean file 0B C:\Users\User\AppData\Local\Microsoft\Edge\User Data\Default\databases\Databases.db
Error: microsoft_edge.form_history: Function: Clean file: C:\Users\User\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\User\AppData\Local\Microsoft\Edge\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'
The error happens (sometimes/every time).

**Expected behavior**
There should be no such error.

**Desktop (please complete the following information):**
 - OS: Windows 11 fully up-to-date 
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎5/‎18/‎2023
OS build	22621.2215
Experience	Windows Feature Experience Pack 1000.22662.1000.0

 - BleachBit version 4.2.0

No matter what each time BleachBit is executed the error is still present.

**Comment by az0** [comment]
The "no such table" issue is documented in the [BleachBit version 4.4.2 release notes](https://www.bleachbit.org/news/bleachbit-442#no_such_table), and there is a fix in [BleachBit 4.5.0 beta](https://www.bleachbit.org/news/bleachbit-450-beta). If this does not help fix  the "no such table" issue, add a comment here.

**Comment by MichelRobitaille** [comment]
It works.

Thanks!

**Comment by az0** [comment]
@MichelRobitaille 
You are welcome. I am glad to hear it works for you.
