### ISSUE TITLE
[Bug] 4.5.0 beta - No module

### ISSUE THREAD

**Issue by hbednar** [bleachbit/bleachbit#1550]
**Describe the bug**
When i run bleachbit 4.5.0 i get the below error:

**To Reproduce**
1.update to 4.5.0 beta
2. run bleachbit
3. See error

The error happens (every time).

**Expected behavior**
No error

**Screenshots**
```
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 28, in <module>
    from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
```

**Desktop (please complete the following information):**
 - OS: Debian sid
 - BleachBit 4.5.0

**Additional context**

**Comment by tekstryder** [comment]
Just built bleachbit from commit 3ee901c35fb81c866f6acfc682a5222b96e46248 and ran into this as well.

**Comment by az0** [comment]
Did this error happen with BleachBit 4.4.2 (stable)?

**Comment by tekstryder** [comment]
> Did this error happen with BleachBit 4.4.2 (stable)?

Not in my case.

**Comment by TuxNuX** [comment]
download https://github.com/bleachbit/bleachbit/archive/refs/heads/master.zip
unzip and in console
```
make -C po local
python3 bleachbit.py &
```

**Comment by hbednar** [comment]
I am only getting this error with 4.5.0 both stable and unstable versions before worked.

**Comment by rados** [comment]
@az0 I can trace this one.

**Comment by az0** [comment]
I could not reproduce on [debian-live-testing-amd64-gnome.iso](https://cdimage.debian.org/cdimage/weekly-live-builds/amd64/iso-hybrid/debian-live-testing-amd64-gnome.iso).

```
sudo apt install git gettext vim
git clone https://github.com/bleachbit/bleachbit.git
cd bleachbit
make -C po local
python3 bleachbit.py -p firefox.cookies # CLI
python3 bleachbit.py -c firefox.cookies
python3 bleachbit.py # GUI
```

@hbednar
Your traceback shows the path `/usr/bin`, so I am wondering (1) whether you previously had BleachBit installed system wide from .deb or source and (2) whether the current installation was from .deb or source. How did you do step 1 (update to 4.5.0)?

@tekstryder 
The commit you referenced https://github.com/bleachbit/bleachbit/commit/3ee901c35fb81c866f6acfc682a5222b96e46248 makes me wonder whether I created some circular dependency or import error, but I do not see it yet. What if you do `git checkout a00790997dfd57da9a44255477548d7297525ef1` to get the previous version?

**Comment by hbednar** [comment]
@az0 
I have only installed bleachbit with the deb package and the two directories below are being used is that correct. 
One is the binary and one has python scripts.

```
/usr/bin/bleachbit 
/usr/share/bleachbit
```

**Comment by tekstryder** [comment]
> @tekstryder The commit you referenced [3ee901c](https://github.com/bleachbit/bleachbit/commit/3ee901c35fb81c866f6acfc682a5222b96e46248) makes me wonder whether I created some circular dependency or import error, but I do not see it yet. What if you do `git checkout a00790997dfd57da9a44255477548d7297525ef1` to get the previous version?

I am building the bleachbit package in a clean chroot, and it builds without issue.

<details>
<summary>Build Log</summary>
``
# "binary"
mkdir -p /build/bleachbit/pkg/bleachbit/usr/bin
install -m 644 bleachbit.py /build/bleachbit/pkg/bleachbit/usr/bin/bleachbit
chmod 0755 /build/bleachbit/pkg/bleachbit/usr/bin/bleachbit
# application launcher
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/applications
install -m 644 org.bleachbit.BleachBit.desktop /build/bleachbit/pkg/bleachbit/usr/share/applications/
# AppStream metadata
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/metainfo
install -m 644 org.bleachbit.BleachBit.metainfo.xml /build/bleachbit/pkg/bleachbit/usr/share/metainfo/
# Python code
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/bleachbit/markovify
install -m 644 bleachbit/*.py /build/bleachbit/pkg/bleachbit/usr/share/bleachbit
install -m 644 bleachbit/markovify/*.py /build/bleachbit/pkg/bleachbit/usr/share/bleachbit/markovify
#note: compileall is recursive
cd /build/bleachbit/pkg/bleachbit/usr/share/bleachbit && \
python3 -O -c "import compileall; compileall.compile_dir('.')" && \
python3 -c "import compileall; compileall.compile_dir('.')"
Listing '.'...
Compiling './Action.py'...
Compiling './CLI.py'...
Compiling './Chaff.py'...
Compiling './Cleaner.py'...
Compiling './CleanerML.py'...
Compiling './Command.py'...
Compiling './DeepScan.py'...
Compiling './DesktopMenuOptions.py'...
Compiling './FileUtilities.py'...
Compiling './GUI.py'...
Compiling './General.py'...
Compiling './GuiBasic.py'...
Compiling './GuiChaff.py'...
Compiling './GuiPreferences.py'...
Compiling './Log.py'...
Compiling './Memory.py'...
Compiling './Options.py'...
Compiling './RecognizeCleanerML.py'...
Compiling './Special.py'...
Compiling './SystemInformation.py'...
Compiling './Unix.py'...
Compiling './Update.py'...
Compiling './Winapp.py'...
Compiling './Windows.py'...
Compiling './WindowsWipe.py'...
Compiling './Worker.py'...
Compiling './__init__.py'...
Compiling './_platform.py'...
Listing './markovify'...
Compiling './markovify/__init__.py'...
Compiling './markovify/chain.py'...
Compiling './markovify/splitters.py'...
Compiling './markovify/text.py'...
Compiling './markovify/utils.py'...
Listing '.'...
Compiling './Action.py'...
Compiling './CLI.py'...
Compiling './Chaff.py'...
Compiling './Cleaner.py'...
Compiling './CleanerML.py'...
Compiling './Command.py'...
Compiling './DeepScan.py'...
Compiling './DesktopMenuOptions.py'...
Compiling './FileUtilities.py'...
Compiling './GUI.py'...
Compiling './General.py'...
Compiling './GuiBasic.py'...
Compiling './GuiChaff.py'...
Compiling './GuiPreferences.py'...
Compiling './Log.py'...
Compiling './Memory.py'...
Compiling './Options.py'...
Compiling './RecognizeCleanerML.py'...
Compiling './Special.py'...
Compiling './SystemInformation.py'...
Compiling './Unix.py'...
Compiling './Update.py'...
Compiling './Winapp.py'...
Compiling './Windows.py'...
Compiling './WindowsWipe.py'...
Compiling './Worker.py'...
Compiling './__init__.py'...
Compiling './_platform.py'...
Listing './markovify'...
Compiling './markovify/__init__.py'...
Compiling './markovify/chain.py'...
Compiling './markovify/splitters.py'...
Compiling './markovify/text.py'...
Compiling './markovify/utils.py'...
# cleaners
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/bleachbit/cleaners
install -m 644 cleaners/*.xml /build/bleachbit/pkg/bleachbit/usr/share/bleachbit/cleaners
# menu
install -m 644 data/app-menu.ui /build/bleachbit/pkg/bleachbit/usr/share/bleachbit
# icon
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/pixmaps
install -m 644 bleachbit.png /build/bleachbit/pkg/bleachbit/usr/share/pixmaps/
# translations
make -C po install DESTDIR=/build/bleachbit/pkg/bleachbit
make[1]: Entering directory '/build/bleachbit/src/bleachbit/po'
* Generating af.mo
* Generating ar.mo
* Generating ast.mo
msgfmt --statistics -o af.mo af.po
* Generating be.mo
msgfmt --statistics -o ar.mo ar.po
* Generating bg.mo
* Generating bn.mo
msgfmt --statistics -o ast.mo ast.po
msgfmt --statistics -o be.mo be.po
* Generating bs.mo
msgfmt --statistics -o bg.mo bg.po
msgfmt --statistics -o bn.mo bn.po
msgfmt --statistics -o bs.mo bs.po
* Generating ca.mo
msgfmt --statistics -o ca.mo ca.po
* Generating da.mo
* Generating cs.mo
msgfmt --statistics -o da.mo da.po
msgfmt --statistics -o cs.mo cs.po
* Generating de.mo
msgfmt --statistics -o de.mo de.po
* Generating el.mo
msgfmt --statistics -o el.mo el.po
* Generating en_AU.mo
msgfmt --statistics -o en_AU.mo en_AU.po
* Generating en_GB.mo
* Generating en_CA.mo
msgfmt --statistics -o en_GB.mo en_GB.po
145 translated messages, 15 fuzzy translations, 204 untranslated messages.
msgfmt --statistics -o en_CA.mo en_CA.po
250 translated messages, 24 fuzzy translations, 90 untranslated messages.
355 translated messages, 3 fuzzy translations, 6 untranslated messages.
* Generating eo.mo
205 translated messages, 31 fuzzy translations, 128 untranslated messages.
msgfmt --statistics -o eo.mo eo.po
349 translated messages, 5 fuzzy translations, 10 untranslated messages.
360 translated messages, 1 fuzzy translation, 3 untranslated messages.
352 translated messages, 5 fuzzy translations, 7 untranslated messages.
* Generating es.mo
* Generating et.mo
msgfmt --statistics -o es.mo es.po
msgfmt --statistics -o et.mo et.po
* Generating eu.mo
msgfmt --statistics -o eu.mo eu.po
* Generating fa.mo
msgfmt --statistics -o fa.mo fa.po
* Generating fi.mo
msgfmt --statistics -o fi.mo fi.po
* Generating gl.mo
msgfmt --statistics -o gl.mo gl.po
* Generating fr.mo
352 translated messages, 5 fuzzy translations, 7 untranslated messages.
msgfmt --statistics -o fr.mo fr.po
360 translated messages, 1 fuzzy translation, 3 untranslated messages.
360 translated messages204 translated messages, 34 fuzzy translations, 1 fuzzy translation, 126 untranslated messages.
, 3 untranslated messages.
281 translated messages, 6 fuzzy translations, 77 untranslated messages.
352 translated messages, 5 fuzzy translations, 7 untranslated messages.
360 translated messages, 1 fuzzy translation, 3 untranslated messages.
* Generating hi.mo
msgfmt --statistics -o hi.mo hi.po
* Generating he.mo
302 translated messages, 1 fuzzy translation, 61 untranslated messages.
msgfmt --statistics -o he.mo he.po
364 translated messages.
204 translated messages, 35 fuzzy translations, 125 untranslated messages.
344 translated messages, 5 fuzzy translations, 15 untranslated messages.
355 translated messages, 3 fuzzy translations, 6 untranslated messages.
* Generating hr.mo
* Generating id.mo
* Generating hu.mo
msgfmt --statistics -o hr.mo hr.po
msgfmt --statistics -o hu.mo hu.po
msgfmt --statistics -o id.mo id.po
333 translated messages, 2 fuzzy translations, 29 untranslated messages.
* Generating ia.mo
msgfmt --statistics -o ia.mo ia.po
338 translated messages, 3 fuzzy translations, 23 untranslated messages.
* Generating it.mo
105 translated messages, 16 fuzzy translations, 243 untranslated messages.
360 translated messages, 1 fuzzy translation, 3 untranslated messages.
* Generating ja.mo
* Generating ie.mo
msgfmt --statistics -o it.mo it.po
* Generating ku.mo
msgfmt --statistics -o ie.mo ie.po
msgfmt --statistics -o ja.mo ja.po
* Generating ko.mo
msgfmt --statistics -o ku.mo ku.po
msgfmt --statistics -o ko.mo ko.po
* Generating ka.mo
msgfmt --statistics -o ka.mo ka.po
348 translated messages, 6 fuzzy translations, 10 untranslated messages.
* Generating ky.mo
msgfmt --statistics -o ky.mo ky.po
364 translated messages.
250 translated messages, 24 fuzzy translations, 90 untranslated messages.
* Generating lt.mo
307 translated messages, 11 fuzzy translations, 46 untranslated messages.
msgfmt --statistics -o lt.mo lt.po
* Generating ms.mo
* Generating lv.mo
msgfmt --statistics -o lv.mo lv.po
msgfmt --statistics -o ms.mo ms.po
* Generating my.mo
msgfmt --statistics -o my.mo my.po
364 translated messages.
* Generating nb.mo
201 translated messages, 2 fuzzy translations, 161 untranslated messages.
166 translated messages, 31 fuzzy translations, 167 untranslated messages.
msgfmt --statistics -o nb.mo nb.po
* Generating nds.mo
msgfmt --statistics -o nds.mo nds.po
* Generating nl.mo
270 translated messages, 5 fuzzy translations, 89 untranslated messages.
msgfmt --statistics -o nl.mo nl.po
* Generating nn.mo
msgfmt --statistics -o nn.mo nn.po
* Generating pl.mo
msgfmt --statistics -o pl.mo pl.po
352 translated messages, 3 fuzzy translations, 9 untranslated messages.
* Generating pt_BR.mo
msgfmt --statistics -o pt_BR.mo pt_BR.po
* Generating pt.mo
349 translated messages, 5 fuzzy translations, 10 untranslated messages.
msgfmt --statistics -o pt.mo pt.po
364 translated messages.
347 translated messages, 6 fuzzy translations, 11 untranslated messages.
93 translated messages, 271 untranslated messages.
120 translated messages, 25 fuzzy translations, 219 untranslated messages.
364 translated messages.
* Generating ro.mo
325 translated messages, 2 fuzzy translations, 37 untranslated messages.
msgfmt --statistics -o ro.mo ro.po
* Generating ru.mo
msgfmt --statistics -o ru.mo ru.po
130 translated messages, 24 fuzzy translations, 210 untranslated messages.
* Generating se.mo
152 translated messages, 21 fuzzy translations, 191 untranslated messages.
33 translated messages, 5 fuzzy translations, 326 untranslated messages.
msgfmt --statistics -o se.mo se.po
* Generating sl.mo
msgfmt --statistics -o sl.mo sl.po
* Generating sk.mo
363 translated messages, 1 fuzzy translation.
* Generating sr.mo
* Generating sq.mo
msgfmt --statistics -o sk.mo sk.po
msgfmt --statistics -o sq.mo sq.po
msgfmt --statistics -o sr.mo sr.po
45 translated messages, 7 fuzzy translations, 312 untranslated messages.
* Generating te.mo
* Generating sv.mo
364 translated messages.
msgfmt --statistics -o sv.mo sv.po
msgfmt --statistics -o te.mo te.po
* Generating ta.mo
364 translated messages.
msgfmt --statistics -o ta.mo ta.po
* Generating th.mo
* Generating tr.mo
msgfmt --statistics -o th.mo th.po
364 translated messages.
msgfmt --statistics -o tr.mo tr.po
* Generating ug.mo
msgfmt --statistics -o ug.mo ug.po
354 translated messages, 3 fuzzy translations, 7 untranslated messages.
* Generating uk.mo
msgfmt --statistics -o uk.mo uk.po
* Generating uz.mo
msgfmt --statistics -o uz.mo uz.po
* Generating vi.mo
msgfmt --statistics -o vi.mo vi.po
* Generating yi.mo
msgfmt --statistics -o yi.mo yi.po
276 translated messages, 6 fuzzy translations, 82 untranslated messages.
42 translated messages, 7 fuzzy translations, 315 untranslated messages.
245 translated messages, 27 fuzzy translations, 92 untranslated messages.
364 translated messages.
* Generating zh_CN.mo
msgfmt --statistics -o zh_CN.mo zh_CN.po
* Generating zh_TW.mo
msgfmt --statistics -o zh_TW.mo zh_TW.po
221 translated messages, 21 fuzzy translations, 122 untranslated messages.
348 translated messages, 3 fuzzy translations, 13 untranslated messages.
352 translated messages, 5 fuzzy translations, 7 untranslated messages.
261 translated messages364 translated messages.
, 10 fuzzy translations, 93 untranslated messages.
232 translated messages, 25 fuzzy translations, 107 untranslated messages.
364 translated messages.
257 translated messages, 3 fuzzy translations, 104 untranslated messages.
364 translated messages.
110 translated messages, 13 fuzzy translations, 241 untranslated messages.
347 translated messages, 6 fuzzy translations, 11 untranslated messages.
50 translated messages, 6 fuzzy translations, 308 untranslated messages.
364 translated messages.
358 translated messages, 3 fuzzy translations, 3 untranslated messages.
echo "* Installing in /build/bleachbit/pkg/bleachbit/usr/share/locale"
* Installing in /build/bleachbit/pkg/bleachbit/usr/share/locale
for MO in af.mo ar.mo ast.mo be.mo bg.mo bn.mo bs.mo ca.mo cs.mo da.mo de.mo el.mo en_AU.mo en_CA.mo en_GB.mo eo.mo es.mo et.mo eu.mo fa.mo fi.mo fr.mo gl.mo he.mo hi.mo hr.mo hu.mo ia.mo id.mo ie.mo it.mo ja.mo ka.mo ko.mo ku.mo ky.mo lt.mo lv.mo ms.mo my.mo nb.mo nds.mo nl.mo nn.mo pl.mo pt.mo pt_BR.mo ro.mo ru.mo se.mo sk.mo sl.mo sq.mo sr.mo sv.mo ta.mo te.mo th.mo tr.mo ug.mo uk.mo uz.mo vi.mo yi.mo zh_CN.mo zh_TW.mo; do \
	lang=`basename $MO .mo`; \
	DST=/build/bleachbit/pkg/bleachbit/usr/share/locale/$lang/LC_MESSAGES/; \
	mkdir -p $DST; \
	cp $MO $DST/bleachbit.mo; \
done
make[1]: Leaving directory '/build/bleachbit/src/bleachbit/po'
# PolicyKit
mkdir -p /build/bleachbit/pkg/bleachbit/usr/share/polkit-1/actions
install -m 644 org.bleachbit.policy /build/bleachbit/pkg/bleachbit/usr/share/polkit-1/actions/
``
</details>

Built from a00790997dfd57da9a44255477548d7297525ef1 and still the same issue when attempting to launch the application.

**Comment by rados** [comment]
@tekstryder, thank you for the report. Would you be able to run it from source (not from a build)?

**Comment by tekstryder** [comment]
> @tekstryder, thank you for the report. Would you be able to run it from source (not from a build)?

Looks like @az0 couldn't reproduce from source. 

I was just looking to take the beta for a spin. I'll package the final release, or let the distro packagers handle that when the time comes.

I don't really have a suitable test environment currently available to test running from source.

**Comment by rados** [comment]
@hbednar, If you have an easy way to try it from source that would facilitate my debugging...

**Comment by tekstryder** [comment]
@rados , same error when running from source here:

```
$ python3 bleachbit
Traceback (most recent call last):
  File "/tmp/ramdisk/chroot/myusername/build/bleachbit/pkg/bleachbit/usr/bin/bleachbit", line 28, in <module>
    from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
```

**Comment by rados** [comment]
@tekstryder, thank you very much. And would you share the exact version of Arch Linux? I would like to simulate your environment.

**Comment by tekstryder** [comment]
Thanks. Arch is a rolling release. 

Doesn't sound like this is Arch-specific though as the reporter ran into this on Debian Sid.

**Comment by rados** [comment]
@tekstryder I've run it on Debian 10.7 from source - no crash.

**Comment by tekstryder** [comment]
> @tekstryder I've run it on Debian 10.7 from source - no crash.

This appears to be an issue with built/packaged versions, included those provided on the bleachbit.org site:
https://download.bleachbit.org/beta/4.5.0

Were you able to install and run bleachbit via the beta package for Debian 10?

**Comment by rados** [comment]
@tekstryder yes that's right - I could reproduce the error from the build (on Debian 10.7). Thank you.

**Comment by rados** [comment]
@az0 Could reproduce it on Ubuntu 20 as well, from the build.

**Comment by az0** [comment]
I retested on the same system (debian-live-testing-amd64-gnome.iso)

* bleachbit_4.4.2-0_all_debian11.deb: does _not_ have the error
* bleachbit_4.5.0-0_all_debian12.deb: has the error

**Comment by tekstryder** [comment]
> I retested on the same system (debian-live-testing-amd64-gnome.iso)
> 
>     * bleachbit_4.4.2-0_all_debian11.deb: does _not_ have the error
> 
>     * bleachbit_4.5.0-0_all_debian12.deb: has the error

Awesome, thanks! I built with git master @commit https://github.com/bleachbit/bleachbit/commit/f8045b770ab4bb6b19c865888d06736607fb391a and can confirm it builds/installs/runs great without any errors.

**Comment by az0** [comment]
@tekstryder 
Thank you for quickly testing, and it's good to hear that it worked.
