### ISSUE TITLE
Bug with Microsoft Edge

### ISSUE THREAD

**Issue by LVS04** [bleachbit/bleachbit#1554]
Hello guys,
Since some days, an error has appeared concerning Microsoft Edge. See screenshot.
![BleachBit_Edge](https://github.com/bleachbit/bleachbit/assets/22444859/b5b2cf89-3c0b-4c92-9387-1580c7ea74a8)
Thanks!
Laurent

**Comment by rados** [comment]
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta)has this fix.

**Comment by LVS04** [comment]
Great! Thanks!
