### ISSUE TITLE
Bleachbit 4.5.0.2499 error when starting the software: certificate verify failed

### ISSUE THREAD

**Issue by hibonox705** [bleachbit/bleachbit#1559]
### BleachBit 4.5.0.2499 in use.

I run windows 11 pro build 22631.2361 version 23H2 and just did a clean install.
And I just installed Bleachbit with no firewall or anything and yet I get an error when launching it

### Problem:

The problem is that when i start the software I directly get a error message saying the following:
Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

And like I said I have no firewall on and just reporting in since it's in the beta version so it can be fixed.

**Comment by hibonox705** [comment]
Also at first I had to install msvcr100.dll because it was missing. I don't know if it's a problem with the windows-x-lite build I'm using but wanted to share it also

**Comment by hibonox705** [comment]
Is there anyone that can help me with this situation please?

**Comment by az0** [comment]
1. Did you have this issue with [previous versions such as 4.4.2](https://www.bleachbit.org//download/windows)?
2. Go to [time.is](https://time.is/) and look near top. Mine states, "The difference from Time.is was +0.001 seconds (±0.033 seconds)."  Within a few seconds is fine. What is your clock error?
3. Does this happen with newer versions such as [build 2513](https://ci.bleachbit.org/?prefix=dl/4.5.0.2513-master/)?
4. In your web browser, are you able to open [this update web page](https://update.bleachbit.org/update/4.5.0)? It should be an short XML document. It should look like this

```xml
<updates>
<latest-version>4.4.2</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/>
</updates>```

**Comment by hibonox705** [comment]
> 1. Did you have this issue with [previous versions such as 4.4.2](https://www.bleachbit.org//download/windows)?
> 2. Go to [time.is](https://time.is/) and look near top. Mine states, "The difference from Time.is was +0.001 seconds (±0.033 seconds)."  Within a few seconds is fine. What is your clock error?
> 3. Does this happen with newer versions such as [build 2513](https://ci.bleachbit.org/?prefix=dl/4.5.0.2513-master/)?
> 4. In your web browser, are you able to open [this update web page](https://update.bleachbit.org/update/4.5.0)? It should be an short XML document. It should look like this
> 
> ```
> <updates>
> <latest-version>4.4.2</latest-version>
> <winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/>
> </updates>```
> ```

Hi thanks for the answers

1. No I didn't have the issue before but I updated to a new windows version so it may be the cause of problems
2. Just looked it up and it's showing : Accuracy of synchronization was ±0.023 seconds
3. Just tried it and no it's working perfectly fine with this new version
4. When opening the link I see the following : 

![capture](https://github.com/bleachbit/bleachbit/assets/116116660/1333aeef-67e6-4e17-ab29-0f26f295fc27)

**Comment by az0** [comment]
I hear it's working, so I am going to close this. In case this comes up again, enable debug info in the preferences. Then you will see some more info like this (requires build 4.5.0.2520 or later)

>Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'update.bleachbit.org'. (_ssl.c:1007)>
> URL https://update.bleachbit.org/update/4.5.0 has IP address 1.2.3.4

Please include this info in a future ticket.

**Comment by hibonox705** [comment]
> I hear it's working, so I am going to close this. In case this comes up again, enable debug info in the preferences. Then you will see some more info like this (requires build 4.5.0.2520 or later)
> 
> > Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'update.bleachbit.org'. (_ssl.c:1007)>
> > URL https://update.bleachbit.org/update/4.5.0 has IP address 1.2.3.4
> 
> Please include this info in a future ticket.

Okay thanks, I'll take it in notes if there's a next time

**Comment by az0** [comment]
[BleachBit 4.9.2](https://www.bleachbit.org/news/bleachbit-492-beta) contains fixes for errors like the following when starting the application and checking for updates
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)> `
