### ISSUE TITLE
Repackage Bleachbit with Flatpack, Appimage, or both

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#1560]
You should repackage this great program in a universal package form factor like flatpack and/or appimage.  It will run universely everywhere on the linux ecosystem and you don't have to waste time and resources writing a program for every major linux distribution.  Flatpacks are the future of linux package distribution, and its time that Bleachbit adopts it,  so every user on any linux disto can run the latest stable release.

Thank you

**Comment by az0** [comment]
duplicate
