### ISSUE TITLE
bleachbit v4.5.0.2499 - Still shows options for un-installed Browser

### ISSUE THREAD

**Issue by m0lz** [bleachbit/bleachbit#1562]
![Untitled](https://github.com/bleachbit/bleachbit/assets/20239221/833969b7-97f4-4c0a-9ecc-53dc7145a553)
**Describe the bug**
I previously had the Brave Browser (Chrome variation) installed.
I used Windows 11 Settings/Apps/Brave Uninstall.
I then went to all <Username>AppData\ .. Local/Low/Roaming folders, and deleted anything Brave related.
I then restarted the PC.
Loaded up Bleachbit 4.5.0.2499, which has the setting "Hide irrelevant cleaners" enabled
.. And Bleachbit still lists Brave Browser to be cleaned

I have seen this many times when uninstalling Chrome variations (Iron Browser, Chromium, Google Chrome and now also Brave)

The new browser I install becomes detected and gives me all the usual options to clean, but the previous and now uninstalled Chrome variant remains in Bleachbit as something to clean out .. Which is not the case.

I have found Bleachbit.ini in C:\Users\<username>\AppData\Roaming\BleachBit

And edited that file to delete any line with Brave.whatever - This gets rid of Bleachbit trying to clean an old but uninstalled browser, but I imagined that having the setting "Hide irrelevant cleaners" would have done that for me?

I don't know how I am going to be able to help you follow up on this issue, as the previous Browser, and the entries in Bleachbit.ini have now been eradicated.

**Comment by az0** [comment]
What is going on is that uninstalling the software does not completely remove it. Normally there is still profile data, and some users may still want to clean it. BleachBit handles this in a generic way across different applications.

Using the file browser (Windows Explorer) delete `%LocalAppData%\BraveSoftware\Brave-Browser\User Data`. Does this help with Brave?

**Comment by m0lz** [comment]
Ah sorry but as part of troubleshooting something with Brave, I used Revo uninstaller to eradicate everything related to Brave.
And prior to that I also edited Bleachbit.ini to get rid of all the brave.nnn entries.
So I have nothing left to test Bleachbit with.

But thank you, I understand about profiles and left behind data you cannot account for.

**Comment by az0** [comment]
OK, so I'll close this ticket.

By the way, there's an item on the to-do list called the "nuclear option" that would allow BleachBit to delete an application's data and settings, and then it would no longer show up in BleachBit.
