### ISSUE TITLE
Bug once again with network connection with debug informations

### ISSUE THREAD

**Issue by hibonox705** [bleachbit/bleachbit#1570]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

Installed on the brand new windows version

The error happens every time.

**Expected behavior**
Being able to connect to internet normally and update Bleachbit

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 Pro
 - BleachBit version 4.51.2523 & 4.51.2524

**Additional context**
Last time it happened and after updating the software it work fine. Now with the latest version it's happening again unfortunately.
The debug informations are the following:

already an admin (UAC not required)
closest monitor (0) geometry = (0, 0)+(1536, 864), window geometry = (368, 132)+(800, 600)
automatically hiding cleaner 'adobe_reader'
automatically hiding cleaner 'amule'
automatically hiding cleaner 'brave'
automatically hiding cleaner 'discord'
automatically hiding cleaner 'filezilla'
automatically hiding cleaner 'firefox'
automatically hiding cleaner 'flash'
automatically hiding cleaner 'gimp'
automatically hiding cleaner 'google_chrome'
automatically hiding cleaner 'google_earth'
automatically hiding cleaner 'google_toolbar'
automatically hiding cleaner 'gpodder'
automatically hiding cleaner 'hexchat'
automatically hiding cleaner 'hippo_opensim_viewer'
automatically hiding cleaner 'java'
automatically hiding cleaner 'libreoffice'
automatically hiding cleaner 'microsoft_edge'
automatically hiding cleaner 'microsoft_office'
automatically hiding cleaner 'midnightcommander'
automatically hiding cleaner 'miro'
automatically hiding cleaner 'octave'
automatically hiding cleaner 'openofficeorg'
automatically hiding cleaner 'opera'
automatically hiding cleaner 'paint'
automatically hiding cleaner 'palemoon'
automatically hiding cleaner 'pidgin'
automatically hiding cleaner 'realplayer'
automatically hiding cleaner 'safari'
automatically hiding cleaner 'screenlets'
automatically hiding cleaner 'seamonkey'
automatically hiding cleaner 'secondlife_viewer'
automatically hiding cleaner 'silverlight'
automatically hiding cleaner 'skype'
automatically hiding cleaner 'slack'
automatically hiding cleaner 'smartftp'
automatically hiding cleaner 'teamviewer'
automatically hiding cleaner 'thunderbird'
automatically hiding cleaner 'tortoisesvn'
automatically hiding cleaner 'vim'
automatically hiding cleaner 'vlc'
automatically hiding cleaner 'vuze'
automatically hiding cleaner 'warzone2100'
automatically hiding cleaner 'waterfox'
automatically hiding cleaner 'winamp'
automatically hiding cleaner 'windows_defender'
automatically hiding cleaner 'windows_media_player'
automatically hiding cleaner 'winrar'
automatically hiding cleaner 'winzip'
automatically hiding cleaner 'wordpad'
automatically hiding cleaner 'yahoo_messenger'
automatically hiding cleaner 'zoom'
Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
URL https://update.bleachbit.org/update/4.5.1 has IP address ***.**.**.***

And I tried turning off my firewall, nothing change. Adding a specific rule for BleachBit and nothing change either

**Comment by az0** [comment]
>URL https://update.bleachbit.org/update/4.5.1 has IP address ...**

Did you redact the IP address, or was it printed like that? I added this information to the debugging log just for this issue. If you have it, please provide the IP address from this line. It is a public IP address of the BleachBit update server, so it's not specific to any users.

Also, let me know whether your [system has IPv6](https://test-ipv6.com/).

**Comment by hibonox705** [comment]
> > URL https://update.bleachbit.org/update/4.5.1 has IP address ...**
> 
> Did you redact the IP address, or was it printed like that? I added this information to the debugging log just for this issue. If you have it, please provide the IP address from this line. It is a public IP address of the BleachBit update server, so it's not specific to any users.
> 
> Also, let me know whether your [system has IPv6](https://test-ipv6.com/).

Oh yeah sorry, to keep it secure I redacted it because I thought it was mine
URL https://update.bleachbit.org/update/4.5.1 has IP address 172.67.201.162

And yes I have IPv6

**Comment by az0** [comment]
Would you be able and willing to temporarily disable Windows IPv6 and test again? Here is [one way to disable it](https://superuser.com/questions/1545288/disable-ipv6-connectivity-on-windows-without-restarting-the-computer).

If it works with ipv6 disabled, then it will give me some direction on how to add a workaround.

**Comment by hibonox705** [comment]
> That is the legit ipv4 address, though it will show the ipv4 address there even if using ipv6 where it fails.
> 
> Would you be able and willing to temporarily disable Windows IPv6 and test again? Here is [one way to disable it](https://superuser.com/questions/1545288/disable-ipv6-connectivity-on-windows-without-restarting-the-computer).
> 
> If it works with ipv6 disabled, then it will give me some direction on how to add a workaround.

Yeah of course I'm open to it.
Just disabled it and unfortunately it doesn't work

already an admin (UAC not required)
closest monitor (0) geometry = (0, 0)+(1536, 864), window geometry = (368, 132)+(800, 600)
automatically hiding cleaner 'adobe_reader'
automatically hiding cleaner 'amule'
automatically hiding cleaner 'brave'
automatically hiding cleaner 'discord'
automatically hiding cleaner 'filezilla'
automatically hiding cleaner 'firefox'
automatically hiding cleaner 'flash'
automatically hiding cleaner 'gimp'
automatically hiding cleaner 'google_chrome'
automatically hiding cleaner 'google_earth'
automatically hiding cleaner 'google_toolbar'
automatically hiding cleaner 'gpodder'
automatically hiding cleaner 'hexchat'
automatically hiding cleaner 'hippo_opensim_viewer'
automatically hiding cleaner 'java'
automatically hiding cleaner 'libreoffice'
automatically hiding cleaner 'microsoft_edge'
automatically hiding cleaner 'microsoft_office'
automatically hiding cleaner 'midnightcommander'
automatically hiding cleaner 'miro'
automatically hiding cleaner 'octave'
automatically hiding cleaner 'openofficeorg'
automatically hiding cleaner 'opera'
automatically hiding cleaner 'paint'
automatically hiding cleaner 'palemoon'
automatically hiding cleaner 'pidgin'
automatically hiding cleaner 'realplayer'
automatically hiding cleaner 'safari'
automatically hiding cleaner 'screenlets'
automatically hiding cleaner 'seamonkey'
automatically hiding cleaner 'secondlife_viewer'
automatically hiding cleaner 'silverlight'
automatically hiding cleaner 'skype'
automatically hiding cleaner 'slack'
automatically hiding cleaner 'smartftp'
automatically hiding cleaner 'teamviewer'
automatically hiding cleaner 'thunderbird'
automatically hiding cleaner 'tortoisesvn'
automatically hiding cleaner 'vim'
automatically hiding cleaner 'vlc'
automatically hiding cleaner 'vuze'
automatically hiding cleaner 'warzone2100'
automatically hiding cleaner 'waterfox'
automatically hiding cleaner 'winamp'
automatically hiding cleaner 'windows_defender'
automatically hiding cleaner 'windows_media_player'
automatically hiding cleaner 'winrar'
automatically hiding cleaner 'winzip'
automatically hiding cleaner 'wordpad'
automatically hiding cleaner 'yahoo_messenger'
automatically hiding cleaner 'zoom'
Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>
URL https://update.bleachbit.org/update/4.5.1 has IP address 172.67.201.162

**Comment by az0** [comment]
Hmm, this is interesting. I will sum up where we are at

* User's clock does not have drift ([previous ticket](https://github.com/bleachbit/bleachbit/issues/1559#issuecomment-1766770455))
* User has ipv6 but problem happens with ipv4
* ipv4 IP address resolves correctly
* "no firewall on" ([previous ticket](https://github.com/bleachbit/bleachbit/issues/1559#issue-1942668234))
* coincided with (1) Windows 11 clean install and (2) new BleachBit version
* went away when updating build 2499 to 2513 but then came back

>BleachBit version 4.51.2523 & 4.51.2524

Are you using the digitally signed version of[ BleachBit 4.5.1 (build 2523)](https://download.bleachbit.org/beta/4.5.1/)? Which  security software product do you use (e.g., Windows Security, McAfee, Avast)?

Please try 

1. Use the  4.5.1 (signed)
2. Temporarily  disable Windows Security or any other malware protection. (Remember to turn it on a few minutes later.)
3. When BleachBit starts and asks whether you want to use administrator privileges, answer no. It will startup without the privileges.

Sometimes BleachBit gets flagged by security software as a false positive. Using the digitally-signed version prevents some false positives by security software, and running without admin privileges may help too. Normally there is an explicit error from the security software, but there have been some strange side effects, like not being able to load the sqlite3.dll file, which  feels passive aggressive.

If the BleachBit update check does not error out, then you [can add an exclusion ](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26), and I can submit the issue to the security software vendor.

**Comment by hibonox705** [comment]
> Hmm, this is interesting. I will sum up where we are at
> 
> * User's clock does not have drift ([previous ticket](https://github.com/bleachbit/bleachbit/issues/1559#issuecomment-1766770455))
> * User has ipv6 but problem happens with ipv4
> * ipv4 IP address resolves correctly
> * "no firewall on" ([previous ticket](https://github.com/bleachbit/bleachbit/issues/1559#issue-1942668234))
> * coincided with (1) Windows 11 clean install and (2) new BleachBit version
> * went away when updating build 2499 to 2513 but then came back
> 
> > BleachBit version 4.51.2523 & 4.51.2524
> 
> Are you using the digitally signed version of[ BleachBit 4.5.1 (build 2523)](https://download.bleachbit.org/beta/4.5.1/)? Which security software product do you use (e.g., Windows Security, McAfee, Avast)?
> 
> Please try
> 
> 1. Use the  4.5.1 (signed)
> 2. Temporarily  disable Windows Security or any other malware protection. (Remember to turn it on a few minutes later.)
> 3. When BleachBit starts and asks whether you want to use administrator privileges, answer no. It will startup without the privileges.
> 
> Sometimes BleachBit gets flagged by security software as a false positive. Using the digitally-signed version prevents some false positives by security software, and running without admin privileges may help too. The [builds on the CI site](https://ci.bleachbit.org/) are prone to false positives because (1) not digitally signed and (2) low popularity. Normally there is an explicit error from the security software, but there have been some strange side effects, like not being able to load the sqlite3.dll file, which feels passive aggressive.
> 
> If the BleachBit update check does not error out, then you [can add an exclusion ](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26), and I can submit the issue to the security software vendor.

Just tried it, with the sign verison with everything turned off and no antivirus or anti malware software installed yet. And I still get the same error message unfortunately

**Comment by hibonox705** [comment]
Also sometimes I get a different ip adress
I get the following:
URL https://update.bleachbit.org/update/4.5.1 has IP address 104.21.36.254

**Comment by az0** [comment]
Yes, those two IPv4 addresses are normal. As of now, it should be just those two in that context. In another context, there can be ipv6.

I created a [special build 2533](https://ci.bleachbit.org/?prefix=dl/4.5.1.2533-certificate_verify/) to run some tests and log more information. It may look like this

```
heck_updates(True, False, ...)
debug_check_no_verify() started
calling urlopen() without SSL verification
calling handle.read()
read document of size 313: b'<?xml version="1.0" encoding="utf-8"?><updates>\n<latest-version>4.4.2</latest-version>\n<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>'
debug_check_requests() started
sock.getpeername()
requests IP address: ('104.21.36.254', 443)
requests status code: 200
requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
<latest-version>4.4.2</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
debug_check_ipv4() started
debug_check_requests() started
sock.getpeername()
requests IP address: ('104.21.36.254', 443)
requests status code: 200
requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
<latest-version>4.4.2</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
ipv4: restoring allowed_gai_family
```

Ignore the "automatically hiding" lines because they are not relevant.

If this build crashes, as in the whole program just disappears during startup, then please try again two more times.

**Comment by hibonox705** [comment]
> Yes, those two IPv4 addresses are normal. As of now, it should be just those two in that context. In another context, there can be ipv6.
> 
> I created a [special build 2533](https://ci.bleachbit.org/?prefix=dl/4.5.1.2533-certificate_verify/) to run some tests and log more information. It may look like this
> 
> ```
> heck_updates(True, False, ...)
> debug_check_no_verify() started
> calling urlopen() without SSL verification
> calling handle.read()
> read document of size 313: b'<?xml version="1.0" encoding="utf-8"?><updates>\n<latest-version>4.4.2</latest-version>\n<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>'
> debug_check_requests() started
> sock.getpeername()
> requests IP address: ('104.21.36.254', 443)
> requests status code: 200
> requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
> <latest-version>4.4.2</latest-version>
> <winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
> debug_check_ipv4() started
> debug_check_requests() started
> sock.getpeername()
> requests IP address: ('104.21.36.254', 443)
> requests status code: 200
> requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
> <latest-version>4.4.2</latest-version>
> <winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
> ipv4: restoring allowed_gai_family
> ```
> 
> Ignore the "automatically hiding" lines because they are not relevant.
> 
> If this build crashes, as in the whole program just disappears during startup, then please try again two more times.

Hi, thanks for the help, the first time it works then it crashed. And now it's working again.

The informations I get with the debug setting on is the following:

already an admin (UAC not required)
closest monitor (1) geometry = (1920, 0)+(1920, 1080), window geometry = (2763, 178)+(800, 600)
automatically hiding cleaner 'adobe_reader'
automatically hiding cleaner 'amule'
automatically hiding cleaner 'brave'
automatically hiding cleaner 'discord'
automatically hiding cleaner 'filezilla'
automatically hiding cleaner 'firefox'
automatically hiding cleaner 'flash'
automatically hiding cleaner 'gimp'
automatically hiding cleaner 'google_chrome'
automatically hiding cleaner 'google_earth'
automatically hiding cleaner 'google_toolbar'
automatically hiding cleaner 'gpodder'
automatically hiding cleaner 'hexchat'
automatically hiding cleaner 'hippo_opensim_viewer'
automatically hiding cleaner 'java'
automatically hiding cleaner 'libreoffice'
automatically hiding cleaner 'microsoft_edge'
automatically hiding cleaner 'microsoft_office'
automatically hiding cleaner 'midnightcommander'
automatically hiding cleaner 'miro'
automatically hiding cleaner 'octave'
automatically hiding cleaner 'openofficeorg'
automatically hiding cleaner 'opera'
automatically hiding cleaner 'paint'
automatically hiding cleaner 'palemoon'
automatically hiding cleaner 'pidgin'
automatically hiding cleaner 'realplayer'
automatically hiding cleaner 'safari'
automatically hiding cleaner 'screenlets'
automatically hiding cleaner 'seamonkey'
automatically hiding cleaner 'secondlife_viewer'
automatically hiding cleaner 'silverlight'
automatically hiding cleaner 'skype'
automatically hiding cleaner 'slack'
automatically hiding cleaner 'smartftp'
automatically hiding cleaner 'teamviewer'
automatically hiding cleaner 'thunderbird'
automatically hiding cleaner 'tortoisesvn'
automatically hiding cleaner 'vim'
automatically hiding cleaner 'vuze'
automatically hiding cleaner 'warzone2100'
automatically hiding cleaner 'waterfox'
automatically hiding cleaner 'winamp'
automatically hiding cleaner 'windows_defender'
automatically hiding cleaner 'windows_media_player'
automatically hiding cleaner 'winrar'
automatically hiding cleaner 'winzip'
automatically hiding cleaner 'wordpad'
automatically hiding cleaner 'yahoo_messenger'
automatically hiding cleaner 'zoom'
check_updates(False, True, ...)
debug_check_no_verify() started
calling urlopen() without SSL verification
calling handle.read()
read document of size 313: b'<?xml version="1.0" encoding="utf-8"?><updates>\n<latest-version>4.4.2</latest-version>\n<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>'
debug_check_requests() started
sock.getpeername()
requests IP address: ('172.67.201.162', 443)
requests status code: 200
requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
<latest-version>4.4.2</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
debug_check_ipv4() started
debug_check_requests() started
sock.getpeername()
requests IP address: ('104.21.36.254', 443)
requests status code: 200
requests text length (313): <?xml version="1.0" encoding="utf-8"?><updates>
<latest-version>4.4.2</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/winapp2-2021-11-22.ini" sha512="a4cc6eb829cd4818dae12de88a9cd0865a1fdd270c2f5c0e7a6d15791fb40a0803b1296f5f551531a9ed2b8bdaa140362dbf4a18fce7beb12826cf6f4247fc70"/></updates>
ipv4: restoring allowed_gai_family

**Comment by az0** [comment]
At first glance, that looks normal and good, but I don't see why you have been having intermittent issues. Maybe try this build every once in a while to see if you can get the [SSL: CERTIFICATE_VERIFY_FAILED]  to come back.

I noticed our preferences for beta version and Winapp2 are backwards, so in the "regular" version (i.e.. digitally signed version 4.4.2 final or 4.5.1 beta; not build 2533), you might try to see if that makes a difference to toggle those options in the BB preferences.

I edited your comment because some data was not showing properly, and some data wasn't needed. I removed the "automatically" lines, and I formatted it using the "code" option to show the XML data that was missing.

**Comment by az0** [comment]
I bumped target from 4.6 to 5.0 because this is idiocratic. A potential solution is to refactor three places that make calls to web sites to be based on a single function, while updating the code from from the _urllib_ to _requests_ library.

**Comment by Espionage724** [comment]
With multiple Windows installs in a week, I frequently get the SSL cert verify error, but only sometimes. I'm getting it now on 4.6.0 and it seems to be the worst session yet as I'm still not able to get past the SSL error with reboots (usually solves it), reconnects, HOSTS, and DNS flush.

> Error message: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)>

**Comment by az0** [comment]
For [BleachBit 4.9.1 alpha](https://www.bleachbit.org/news/bleachbit-491-alpha), I overhauled how it connects to to network resources (3ee0d4a94d), so it should take care of the "SSL: CERTIFICATE_VERIFY_FAILED" error.

If you have a chance, try this release and comment here with your observations regarding the "SSL: CERTIFICATE_VERIFY_FAILED]" error.
