### ISSUE TITLE
list index out of range in is_linux_display_protocol_wayland

### ISSUE THREAD

**Issue by k1gen** [bleachbit/bleachbit#1578]
**Describe the bug**
Bleachbit v4.6.0 doesn't start on Wayland (Gnome)

**To Reproduce**
Install Bleachbit (tested on Arch) and try to launch it on from command line on Wayland
The error happens every time.

**Expected behavior**
A window appears.

**Screenshots**

**Desktop:**
 - OS: Arch Linux
 - BleachBit version: 4.6.0

**Additional context**
stdout:
```
$ bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 40, in <module>
    bleachbit.Unix.is_display_protocol_wayland_and_root_not_allowed()
  File "/usr/share/bleachbit/Unix.py", line 746, in is_display_protocol_wayland_and_root_not_allowed
    bleachbit.Unix.is_linux_display_protocol_wayland() and
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/Unix.py", line 732, in is_linux_display_protocol_wayland
    session = result[1].split('\n')[1].strip().split(' ')[0]
              ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by fabiscafe** [comment]
This function

https://github.com/bleachbit/bleachbit/blob/master/bleachbit/Unix.py#L729-L732

Only tries to catch the output of `loginctl`, the sessions part. I guess you're not using logind as sessionlauncher for some reason.

So the output of 

    loginctl

and 

    loginctl session-status

Would be good to know.

**Comment by az0** [comment]
See also https://github.com/bleachbit/bleachbit/pull/1577/files

**Comment by k1gen** [comment]
so I should wait until 5.0 is released or there will be a backport?

**Comment by az0** [comment]
I'm considering doing a 4.6.2 stable release with this and a DLL fix for Microsoft Windows, but I'd like to take a closer look at this before merging.

**Comment by az0** [comment]
I commited a change to help: https://github.com/bleachbit/bleachbit/commit/0e710eb4186d967f048ed54bb6499b7469a26e0f . I'm considering a follow-up change to handle another scenario, so you can either test now or when that is ready.

**Comment by az0** [comment]
If you are able to test, try https://github.com/bleachbit/bleachbit/commit/15f8b0f7f86fdb61f4008f0d5e72968fb68046ac

**Comment by k1gen** [comment]
@az0 tested, on cfbeb783f1c1101e29b7ee7cf6ab5ba864298f3a everything works fine

**Comment by marek22k** [comment]
I have the same problem. I get BleachBit 4.6.0-2 from Arch extra.
```
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 40, in <module>
    bleachbit.Unix.is_display_protocol_wayland_and_root_not_allowed()
  File "/usr/share/bleachbit/Unix.py", line 746, in is_display_protocol_wayland_and_root_not_allowed
    bleachbit.Unix.is_linux_display_protocol_wayland() and
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/Unix.py", line 732, in is_linux_display_protocol_wayland
    session = result[1].split('\n')[1].strip().split(' ')[0]
              ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Is there a workaround?

**Comment by fabiscafe** [comment]
@marek22k I guess without being able to recreate it, the best workaround is to stay on a development snapshot.

[printresult.patch.txt](https://github.com/bleachbit/bleachbit/files/15276288/printresult.patch.txt)

Not a workaround but maybe we can get some infos about whats happening here. You can download the patch (github wouldnt let me put it online as .patch file, but patch.txt.. doesnt matter) and apply via

    sudo patch --forward --strip=1 --input=printresult.patch.txt /usr/share/bleachbit/Unix.py

If you then run `bleachbit` from a terminal there should be a few new lines of output right before it crashes. Would be good to have them

example:
```
result: (0, 'SESSION   UID USER   SEAT  TTY  STATE  IDLE SINCE\n      3 60172 fabian seat0 tty2 active no   -\n\n1 sessions listed.\n', '')
result[1]: SESSION   UID USER   SEAT  TTY  STATE  IDLE SINCE
      3 60172 fabian seat0 tty2 active no   -

1 sessions listed.

result[1].split[1]:       3 60172 fabian seat0 tty2 active no   -
```

----- 
You can revert this by uninstalling and installing bleachbit via pacman.

**Comment by az0** [comment]
Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has this fix for Wayland.

**Comment by Eefreeth** [comment]
Hi there I have this issue with the latest update.- sudo bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 40, in <module>
    bleachbit.Unix.is_display_protocol_wayland_and_root_not_allowed()
  File "/usr/share/bleachbit/Unix.py", line 775, in is_display_protocol_wayland_and_root_not_allowed
    bleachbit.Unix.root_is_not_allowed_to_X_session()
  File "/usr/share/bleachbit/Unix.py", line 761, in root_is_not_allowed_to_X_session
    result = General.run_external(['xhost'], clean_env=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/General.py", line 147, in run_external
    p = subprocess.Popen(args, stdout=stdout,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xhost'

Before this update 4.6.1-1, the bleachbit was amazing with sudo on Linux arch based EndeavourOs, please fix this one...
