### ISSUE TITLE
Bleachbit 4.6.0 on MX Linux 23.1 Minimum

### ISSUE THREAD

**Issue by Ozzlaw** [bleachbit/bleachbit#1588]
**Describe the bug**
Bleachbit 4.60 does not load / start after installation in MX Minimum 23.1. Last versio that runs is Bleachbit 4.4.2. 
**To Reproduce**
1. Install Bleachbit 4.6.0
2. Try running from either link in panel or from whisker menu. Nothing happens. No error message or anything - just nothing.
3. Check Task Manager and Bleachbit does not appear as running
4. No error message appears.

This happens all the time.

**Expected behavior**
Previous versions opened the Bleachbit window or the Authentication window if running the "Administrator" version.
**Screenshots**
No screenshots available of Bleachbit 4.6.0 as nothing happens.
**Desktop (please complete the following information):**
Mx Linux 23.1 Minimal respin
**Additional context**

**Comment by hopeless-attempt** [comment]
MX-23.1, KDE Plasma 5.27.5, debian 12.2, systemd.

Bleachbit 4.6.0 runs fine as user, but is totally unresponsive if run as root.
Reverted to 4.4.2.

**Comment by az0** [comment]
@Ozzlaw  @hopeless-attempt 
Are you using Wayland?

@Ozzlaw 
Did you get BleachBit 4.6.0 from the [bleachbit.org official site](https://bleachbit.org/download/linux) or a third party repository (e.g., MX, FlatHub)?

What happens if you initiate BleachBit from a terminal? This might show text that could troubleshoot the issue. Please copy and paste that here.

**Comment by hopeless-attempt** [comment]
Not using Wayland. Using x11.

Got bleachbit 4.6.0-0.3~mx23.1 from MX Package Installer (Test repo).

When I first installed it it worked as user but not as root. I did run it as sudo in the terminal and it did throw an error message. As I was using the Test repo version I wasn't expecting it to be fault free so I ignored the error message and just reverted  back to 4.4.2.

After seeing that you had raised this issue on GitHub I tried again and this time the new version worked fine and throws no errors as sudo.

**Comment by Ozzlaw** [comment]
Thanks hopeless-attempt. I followed your suggestion and got it installed and working on the third go. Haven't tried running it today as I'm using a windows machine at the moment, but will check it again tomorrow.

**Comment by hopeless-attempt** [comment]
MX-23.1, KDE Plasma 5.27.5, debian 12.2, systemd, x11.

Hi,

Just updated bleachbit using MX Package Installer (Test Repo).

Updated to 4.6.1~beta20231207-0.1~mx23+1 from 4.6.0-0.3~mx23.1.

Works perfectly as both the user and root.

Thanks very much.

**Comment by az0** [comment]
Closing because multiple confirmations here that it works. Thank you for confirming.
