### ISSUE TITLE
MSVCR.100.dll not found

### ISSUE THREAD

**Issue by rev55** [bleachbit/bleachbit#1591]
**Describe the bug**
MSVCR.100.dll not found after trying to install Bleachbit 4.6.0. five times.

**To Reproduce**
1. Download BB 4.6.0
2. Click on 'downloaded file to install'
3. Follow on screen prompts.
4. See error message midway through the install process. See error message every time I ran BB. Uninstall BB and install again. Repeat. 

The error happens every time.

**Expected behavior**
A clear and concise description of what you expected to happen. I thought it would be simple to install. Honestly I've been using BB for a couple of years and I've never had any luck installing your updates.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version [e.g., 4.6.0]

**Additional context**
I spent 4 hours online trying to figure out how to replace the 'missing' MSVCR.100.dll. I tried downloading and running Microsoft Build Tools 2015 Update 3 and Microsoft Visual C++ 2010 Service Pack 1 Redistributable Package MFC Security Update. Installed both and ran both a few times. No luck. I gave up on BB and downloaded one of your competitors software: 'Wise Disk Cleaner'. 

Then I decided to run a Google search to see if anyone else was having this problem which led me to your page that gave me the option to download 4.2. I did and it works fine. I'll stick with the older software for now even though I get an error message every time I run it. Then I'll wait for you to debug the new one. 

Lesson learned: Don't update an app for a few months and let other users suffer with the debugging process.

**Comment by az0** [comment]
Thanks for filing a ticket, and I am sorry to hear about the hassle. 

The next release BleachBit 4.6.2 will work the way 4.4.2 worked, but until then, I have an option that may help.

You mentioned trying MS Visual C++ 2010 SP 1. Was that the x64 or x86? In case it was x64, please try [Visual Studio 2010 (VC++ 10.0) SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe) as the x64 will have no effect.

In general, look at the [known issues](https://www.bleachbit.org/news/bleachbit-460#known_issues) section of the [release notes](https://www.bleachbit.org/news/bleachbit-460) for any tips like this.

**Comment by HeadMoose** [comment]
I have the same issue.  Note that Version 4.4.2 installs and runs just fine, so I will have to stick with that version.

**Comment by az0** [comment]
Yes, fix already committed.

**Comment by diamond-one** [comment]
This issue is still occurring - and the result is that BleachBit is unable to be used 

Version: BleachBit-4.6.0

**Comment by az0** [comment]
> This issue is still occurring - and the result is that BleachBit is unable to be used
> 
> Version: BleachBit-4.6.0

@diamond-one 

Did you install the the Visual Studio 2010 x86 or x64? Though you probably have a 64-bit Windows system, BleachBit requires the 32-bit runtime. Here is a direct link: [Visual Studio 2010 (VC++ 10.0) redistributable SP1 x86](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe)

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has the fix for the error "msvcr100.dll was not found."**  (A separate installation of the Microsoft Visual Studio runtime is no longer needed.) If you still see an issue with msvcr100.dll, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
