### ISSUE TITLE
Vivaldi Missing From Cleaning List in 4.6.0

### ISSUE THREAD

**Issue by UnrealDrumpf** [bleachbit/bleachbit#1592]
BleachBit 4.6.0 (portable, Windows 11 installation) does NOT offer Vivaldi as a program to clean, although it DOES offer at least two other Chromium-variant browsers. This is an unwanted regression from 4.4.2 (same machine), which did.

Reproduction steps:
Maintain existing Vivaldi installation.
Install BleachBit 4.6.0 portable (build 2537) on Windows 11 machine. 
Run in administrator mode. 
Uncheck Preferences | Hide irrelevant cleaners. 
No subset for Vivaldi is included (although it was in 4.4.2). However, subsets for Brave, generic Chromium, Google Chrome, and Microsoft Edge ARE included.
Effect test: Run Vivaldi, close without clearing any history. Run BleachBit 4.6.0, ensuring that clearing of history is checked under generic Chromium. Run Vivaldi, and history from prior session is still there (BleachBit did not clear).

Suggested solution:
Reinstate prior Vivaldi subset from 4.4.2 in 4.6.0. This may be a porting error or a bit selection in the build's configuration.

**Comment by rados** [comment]
@az0 I can trace this one.

**Comment by az0** [comment]
@UnrealDrumpf 

Did you have a chance to try the suggestion from rados? Try to re-download winapp2.ini.  Also please try BleachBit 4.6.1 (beta) or BleachBit 4.6.2 (stable---available soon).

I haven't heard back in a while, so I will close this. If you continue to experience the same issue, reopen this issue ticket.
