### ISSUE TITLE
Shred context menu missing

### ISSUE THREAD

**Issue by tiltfactory1** [bleachbit/bleachbit#1597]
I just ugpraded to 4.6.0 and now when I right click a folder/file in Windows Explorer, the "Shred with Bleachbit" context menu option is missing.  I don't see any setting to turn this on besides the KDE Plasma Specific one which doesn't help.  How do I get this context menu option back?

**Comment by tiltfactory1** [comment]
found issue: https://github.com/bleachbit/bleachbit/issues/1166

**Comment by tiltfactory1** [comment]
found the issue: https://github.com/bleachbit/bleachbit/issues/1166

**Comment by az0** [comment]
Thank you for the follow up
