### ISSUE TITLE
Error sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by pitsi** [bleachbit/bleachbit#1601]
**Describe the bug**
I am getting the forementioned error when running 'bleachbit -c firefox.vacuum', but for a very specific file from my profile.

**To Reproduce**
1. On linux, and with firefox already installed, open a terminal and run `bleachbit -c firefox.vacuum`.
2. Notice the error mentioned below.

The error happens every time for the last 20 days to 1 month. I did not check it earlier than that.

**Expected behavior**
It should run the vacuum function on that file too.

**Screenshots**
Terminal output instead of screenshot 
```
$ bleachbit -c firefox.vacuum
Error: firefox.vacuum: Function: Vacuum: /home/user/.mozilla/firefox/bcqy1g9e.default/storage.sqlite
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 474, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.DatabaseError: database disk image is malformed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 1043, in vacuum_sqlite3
    execute_sqlite3(path, 'vacuum')
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 484, in execute_sqlite3
    raise sqlite3.DatabaseError(
sqlite3.DatabaseError: database disk image is malformed: /home/user/.mozilla/firefox/bcqy1g9e.default/storage.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 162, in execute
    if -1 == e.message.find('file is encrypted or is not a database') and \
             ^^^^^^^^^
AttributeError: 'DatabaseError' object has no attribute 'message'
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/cookies.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/protections.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/favicons.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/content-prefs.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/formhistory.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/permissions.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/storage-sync.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/credentialstate.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/storage-sync-v2.sqlite
Vacuum 0B /home/user/.mozilla/firefox/bcqy1g9e.default/places.sqlite
Disk space recovered: 0B
Files deleted: 0
Special operations: 10
Errors: 1
```

**Desktop (please complete the following information):**
 - OS: Debian testing/unstable x64
 - BleachBit version: 4.4.2

**Additional context**
A few days ago I thought something was wrong with my sqlite3 not being on the latest version available from the repo (3.44.**2** vs 3.44.0 I had). But it got updated to that latest one and the issue persists.

**Comment by az0** [comment]
1. Which version of Firefox? I do not see "database disk image is malformed" with Firefox 120.0 on Ubuntu 22.04.
2. Is Firefox completely closed when this happens? One way to check is `ps -ef |grep firefox`

**Comment by az0** [comment]
`storage.sqlite` is not a primary database, and besides vacuuming, BleachBit 4.4.2 does not do anything to it. When cleaning history and bookmarks, other files are cleaned instead, so as a test, try this: 

1. Close Firefox
2. Create a good backup of the whole `~/.mozilla` directory
3. Delete or rename the `storage.sqlite` file
4. Open Firefox to recreate the file and check what has changed (e.g., bookmarks, history)
5. Close Firefox
6. Run BleachBit again. Does the error happen again?

If you lose something important, restore the backup.

**Comment by pitsi** [comment]
About that... and why I want to avoid it.
I once copied my entire profile folder, ~/.mozilla/firefox/whatever.default/, to another location to back it up and when I moved it back in place, ff started with everything at default values, as if the profile folder was not there. Recovering my favorites and history from that backed up folder and importing it to the new profile was a huge amount of work I do not plan on repeating, ever (maybe because my bookmarks count in tens of thousands now).

As for the file itself, I copied it to my home and ran the following which is supposed to fix it
```
$ sqlite3 storage.sqlite "PRAGMA integrity_check;"
*** in database main ***
Tree 5 page 357: btreeInitPage() returns error code 11
Tree 5 page 350: btreeInitPage() returns error code 11
Tree 5 page 346: btreeInitPage() returns error code 11
Tree 5 page 354: btreeInitPage() returns error code 11
Tree 5 page 356: btreeInitPage() returns error code 11
Tree 5 page 347: btreeInitPage() returns error code 11
Tree 5 page 349: btreeInitPage() returns error code 11
Tree 5 page 355: btreeInitPage() returns error code 11
Tree 5 page 352: btreeInitPage() returns error code 11
Tree 5 page 345: btreeInitPage() returns error code 11
Tree 5 page 358: btreeInitPage() returns error code 11
Tree 5 page 348: btreeInitPage() returns error code 11
Tree 5 page 351: btreeInitPage() returns error code 11
Tree 5 page 359: btreeInitPage() returns error code 11
Tree 5 page 360: btreeInitPage() returns error code 11
Tree 5 page 353: btreeInitPage() returns error code 11
Tree 5 page 68: btreeInitPage() returns error code 11
Tree 5 page 67: btreeInitPage() returns error code 11
Tree 5 page 72: btreeInitPage() returns error code 11
Tree 5 page 65: btreeInitPage() returns error code 11
Tree 5 page 70: btreeInitPage() returns error code 11
Tree 6 page 66: btreeInitPage() returns error code 11
Tree 6 page 71: btreeInitPage() returns error code 11
Tree 6 page 69: btreeInitPage() returns error code 11
Error: stepping, database disk image is malformed (11)
```
but vaccuming it still fails
```
$ sqlite3 storage.sqlite "VACUUM;"
Error: stepping, database disk image is malformed (11)
```
I have no idea how sqlite3 works, the above is just commands I found online and I think I executed them correctly.
If there is no way of recovering it, I can close this and give up. I have a lot more than a problematic database to think these days :(

**Comment by az0** [comment]
Thanks for the follow up
