### ISSUE TITLE
Broken desktop files on Linux Mint 21.2

### ISSUE THREAD

**Issue by michalkvasnicka** [bleachbit/bleachbit#1603]
BleachBit 4.6.0 (via flathub installer) propose to delete most of my desktop files at: 
~/.local/share/applications 
and  at: 
~/.config/autostart

```
Delete 4.1kB /home/kva/.local/share/applications/matlabR2023b.desktop
Delete 4.1kB /home/kva/.local/share/applications/Vmware.cinnamon-generated.desktop
Delete 4.1kB /home/kva/.local/share/applications/com.github.xournalpp.xournalpp.desktop
Delete 4.1kB /home/kva/.config/autostart/guake.desktop
Delete 4.1kB /home/kva/.config/autostart/insync.desktop
Delete 4.1kB /home/kva/.config/autostart/remotepc.desktop

Disk space to be recovered: 24.6kB
Files to be deleted: 6

```
But these files are definitely not broken!!!

The only solution is to uncheck System - Broken desktop files item

Any idea what is wrong?

**Comment by az0** [comment]
[BleachBit 4.9.1 alpha](https://www.bleachbit.org/news/bleachbit-491-alpha) was released with fixes for detecting errors in .desktop files. If you notice a .desktop file that is incorrectly classified as being broken, then please submit a sample of the .desktop file.
