### ISSUE TITLE
close running process 

### ISSUE THREAD

**Issue by brahmastra2016** [bleachbit/bleachbit#162]
i have made code change to close running application and continue cleaning process , wanted people feedback and comment before i create pull request.

OS : Unix / Mac OSx.
Windows : Will add latter on.

user can select this option via GUI preference.

GuiPreferences.py --

        # Close the running application and continue cleaning.
        cb_exit = gtk.CheckButton(_("Close Running Application"))
        cb_exit.set_active(options.get('close_run'))
        cb_exit.connect('toggled', self.__toggle_callback, 'close_run')
        vbox.pack_start(cb_exit, False)

Cleaner.py  --
                    print "debug: process '%s' is running" % pathname
                    if options.get("close_run"):
                        if not subprocess.mswindows:
                            print "debug: Closing process '%s'" % pathname
                            subprocess.check_output(["killall", "-9", pathname])
                            return False

**Comment by az0** [comment]
Looks good. A few smaller points
* Use a logger instead of print
* After attempting to kill, re-check whether the process is running. If still running, skip the cleaner as before.
* Default the option to disabled in `Options.py`

**Comment by ROCKNROLLKID** [comment]
Is there anyway you can restart the process after the cleaner ran successfully?

Yes, I would highly recommend you make this default disabled.

**Comment by brahmastra2016** [comment]
thanks for input.

yes I have set the default to disable and user will have select if they
choose to use.

I personally like to restart the application (if needed) as most of this
running app are like browser \editor.

I would like to add option to prompt user confirmation popup but still yet
to figure out as how I can achive it via cleaner.py.

**Comment by az0** [comment]
To prompt for confirmation one option is creating a callback function, and the confirmation dialog would be different in GUI and CLI modes. In CLI it could either always answer no, or it could detect whether there is an interactive shell vs. batch shell.

**Comment by az0** [comment]
Closed by pending #157
