### ISSUE TITLE
Random GUI crash on Win 10?

### ISSUE THREAD

**Issue by killdashnine420** [bleachbit/bleachbit#1634]
Hello,

Been awhile since I was last on here, I couldn't get into my old account known as "Theatre-X".

Got BB 4.6.0 running on my parents' Win 10 desktop. Keeps crashing for reasons beyond my knowledge. My responses will be spotty so please be patient.

Here's what I got:

Traceback (most recent call last):
  File "bleachbit_console.py", line 61, in <module>
  File "bleachbit\CLI.pyo", line 282, in process_cmd_line
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "bleachbit\GUI.pyo", line 32, in <module>
  File "bleachbit\Options.pyo", line 163, in get
  File "configparser.pyo", line 801, in getboolean
  File "configparser.pyo", line 775, in _get
  File "configparser.pyo", line 1132, in _convert_to_boolean
ValueError: Not a boolean: ['False']

--------------------------------------------

BleachBit version 4.6.0
Build number 2537
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.43.2
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\FOOBAR\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\FOOBAR\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_US', 'cp1252')
os.getenv('APPDATA') = C:\Users\FOOBAR\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\FOOBAR\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\FOOBAR\AppData\LocalLow
os.getenv('Music') = C:\Users\FOOBAR\Music
os.getenv('USERPROFILE') = C:\Users\FOOBAR
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\FOOBAR\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\FOOBAR
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit_console.exe', '--gui', '--debug-log=C:\\Users\\FOOBAR\\desktop\\bleachbit.log']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit_console.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\SystemInformation.pyo

**Comment by az0** [comment]
The error you are reporting `ValueError: Not a boolean: ['False']` was reported a while back. Here are some examples:

https://github.com/bleachbit/bleachbit/issues/562
https://github.com/bleachbit/bleachbit/issues/580
https://github.com/bleachbit/bleachbit/issues/1127

Two options

1. Send me the bleachbit.ini file for analysis. If you need it, I can provide my email address, or you can rename the .ini file to .txt and attach it here.
2. Close BleachBit, delete the bleachbit.ini file, and restart BleachBit

**Comment by killdashnine420** [comment]
I ended up deleting the cfg file in the AppData folder and now it works. I meant to make a copy to send to you. Thank you for your help!

**Comment by az0** [comment]
@killdashnine420 
Thank you for letting me know it works. If it comes up again, please send the file
