### ISSUE TITLE
Bleachbit 4.60 Errors

### ISSUE THREAD

**Issue by wsmith031874** [bleachbit/bleachbit#1641]
Error 1 from delete list:

Error: firefox.url_history: Function: Clean file: C:\Users\Will\AppData\Roaming\Mozilla\Firefox\Profiles\nb0jc1hi.default\places.sqlite
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 478, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_historyvisits

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 166, in execute
  File "bleachbit\Special.pyo", line 350, in delete_mozilla_url_history
  File "bleachbit\FileUtilities.pyo", line 486, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_historyvisits: C:\Users\Will\AppData\Roaming\Mozilla\Firefox\Profiles\nb0jc1hi.default\places.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 168, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

Error 2 from delete list:

[WinError 3] The system cannot find the path specified: '\\\\?\\C:\\WINDOWS\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5': Command to delete C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

**Comment by az0** [comment]
@wsmith031874 
Have you used Firefox recently?
[Which version](https://www.whatsmybrowser.org/) of Firefox?

I am not seeing this on Firefox 123.0 on Ubuntu or Windows, but I can still work on it

**Comment by rados** [comment]
I couldn't replicate it as well - Win 11 & Firefox 124.

**Comment by az0** [comment]
@wsmith031874 

As we cannot reproduce this and have not heard back from you, I am closing this ticket. If this problem continues or if you have more info, please add a comment to this issue ticket.
