### ISSUE TITLE
i can't open the software

### ISSUE THREAD

**Issue by jersup** [bleachbit/bleachbit#1656]
when i try to open bleachbit i always get a message that it can't open correctly
it's weird because it fuction before
at least when i first got it
so yeah i need help please

**Comment by az0** [comment]
Please include the error message verbatim here

**Comment by cpari44** [comment]
_I have Bleachbit (not portable) version 4.6.0.2537 installed on a Win10 (x64) PC. 
After opening up cmd from the Search box and navigating to C:\Program Files (x86)\BleachBit\bleachbit_console.exe 
below is what it printed out:_

C:\Program Files (x86)\BleachBit\bleachbit_console.exe
Traceback (most recent call last):
  File "bleachbit_console.py", line 56, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "bleachbit\GUI.pyo", line 32, in <module>
  File "bleachbit\Options.pyo", line 163, in get
  File "configparser.pyo", line 801, in getboolean
  File "configparser.pyo", line 775, in _get
  File "configparser.pyo", line 1132, in _convert_to_boolean
ValueError: Not a boolean: ['False']

_Before trying to run Bleachbit (v4.4.2) I updated my Python software to version 3.12.3150.0 and PyCharm CE to version 241.14494.241._

_What can I do to fix this issue?_
_Bleachbit (v4.4.2) ran fine before I updated it, the Python software and PyCharm CE to their latest versions._
_I reinstalled Bleachbit version 4.4.2 which results in the same issue of not running with the Python software version 3.12.3150.0 and PyCharm CE version 241.14494.241 still intact. Maybe Bleachbit conflicts with the latest versions of Python and/or PyCharm CE?_

**Comment by rados** [comment]
@cpari44 Thank you for this report. It seems like a separate problem, so you can open a separate issue here. This way it will be easier for us to sort it out.

**Comment by cpari44** [comment]
> @cpari44 Thank you for this report. It seems like a separate problem, so you can open a separate issue here. This way it will be easier for us to sort it out.

I'm new to Github. Should I submit my issue as a bug report?

**Comment by az0** [comment]
@jersup 
I haven't heard back, so for now will close this ticket. Feel free to reopen it if you more info. (See comment from two weeks ago.)
