### ISSUE TITLE
BleachBit is deleting saved Brave passwords

### ISSUE THREAD

**Issue by Dryopteroid** [bleachbit/bleachbit#1659]
Hi, I'm a new user of Bleachbit and so far I'm very impressed with it - except for one thing.
It has deleted almost all of my saved passwords even though I have left the Passwords field unchecked, as shown in my screenshot. Passwords only remain for sites I have set Brave to keep cookies for, i.e. my email.
I tested it just now by manually typing my username and password on a site I use regularly, then I ran BleachBit. When I checked, the saved password was gone.
Can you advise if there is anything else I should uncheck, please?
![2024 04 13 16 32](https://github.com/bleachbit/bleachbit/assets/166935478/f21db29b-6d1e-4b04-9321-25aba2dd8d6d)

I am using a laptop with Windows 10 Pro 10.0.19045 Build 19045 (it updated 2 days ago) , my BleachBit version is 4.6.0 and Brave is version 1.64.122 Chromium 123.0.6312.122 (Official Build) (64-bit).

**Comment by az0** [comment]
If you have the winapp2.ini setting enabled, please check for any Brave-related checkboxes under other sections

**Comment by Dryopteroid** [comment]
Thank you for such a quick response! You pointed me in the right direction. What has cured my issue was simply unchecking Brave in the winapp2.ini section. Maybe some of the sub-items could have remained checked, I don't know, I don't have the experience to tell (82 y.o.) but I'll let them take care of themselves.
Thanks again.

**Comment by az0** [comment]
I am glad this helped, and thank you for letting me know. Have a nice day.
