### ISSUE TITLE
Locale dependency of subprocesses

### ISSUE THREAD

**Issue by tstenner** [bleachbit/bleachbit#167]
This problem should appear any time we rely on english strings in the output of subprocesses, but I noticed it in the swap handling code:

    Error  
    Traceback (most recent call last):  
      File "/home/tristan/arbeit/bleachbit/tests/TestMemory.py", line 49, in test_get_proc_swaps  
        "Unexpected first line in swap summary '%s'" % ret)  
    RuntimeError: Unexpected first line in swap summary '
    Dateiname				Typ		Größe	Benutzt	Priorität  
    /zram0                                 	partition	1000468	0	32767'

Changing the environment to {'LC_ALL':'C'} resolves this error, but fails on travis (I think because the PATH variable gets overwritten, see also 45546b941).

**Comment by az0** [comment]
As the comment in `Memory.py` indicates, reading the subprocess output was not my first choice. Originally I was reading from `/proc/swaps`.  Is `/proc/swaps` in English on your system?

**Comment by tstenner** [comment]
Files in `/proc` can't be localized, as opening a file doesn't pass any environment variables, furthermore Linus is quite vocal about kernel changes breaking user space, so the file format shouldn't change.
Reading `/proc/swaps` again would solve this problem (while breaking lvm-configurations), but any other called processes could still be localized. 

Maybe taking the calling environment and replacing the locale variables would help?
