### ISSUE TITLE
Bleachbit default setting

### ISSUE THREAD

**Issue by VincyDude** [bleachbit/bleachbit#1674]
What is Bleachbit default setting?

**Comment by VincyDude** [comment]
Do I still need to use Iobit Advanced Systemcare as well as Bleachbit on the same laptop?

**Comment by az0** [comment]
Are you wanting to revert all setting to defaults? Or what is your goal?

**Comment by az0** [comment]
I am closing because (1) the nature of the issue is unclear and (2) no response since May 20. If you have a response to the May 20 questions, reopen this issue ticket.
