### ISSUE TITLE
OK, I am trying to abide by the posting guidelines...

### ISSUE THREAD

**Issue by brownie-hawkeye** [bleachbit/bleachbit#1682]
**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

**To Reproduce**

The error happens (sometimes/every time).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]

**Additional context**

**Comment by az0** [comment]
I am closing because (1) this looks like a generic template and (2) no response since May 28
