### ISSUE TITLE
Shredding and Cloning

### ISSUE THREAD

**Issue by kenstj** [bleachbit/bleachbit#1689]
I have 3 disks - main and 2 clones. If I shred a folder on the main disk and clone it, will the cloned disk be "safe" too??
Ken

**Comment by az0** [comment]
Windows or Linux?

What method or software are you using to clone (e.g., dd, regular Windows file copy and paste)? 

Are you concerned about any residual data that was on the clone or just the main disk?

**Comment by kenstj** [comment]
Hi Andrew – thanks for the reply. I use Macrium Reflect for cloning. I am questioning whether a clone of a disk that has had a folder shredded would still have residual data. I.e.:

 

Disks 2 and 3 are clones of disk 1. Therefore disks 2 and 3 have all the folders of disk 1.

A folder on disk 1 is shredded. Disks 2 and 3 are then cloned from disk 1. Are there residual remanants/artifacts of this folder on disk 2 and 3?

Ken

**Comment by az0** [comment]
No, there should be no residual data from disk 1 to cloned disks 2 or 3.  It was permanently removed from disk 1, so it cannot be cloned.

This assumes that cloned disks 2 or 3 did not already have this residual data from previous cloning. If so, you would want to do a full disk wipe (the kind for unformatted disks) on cloned disks before re-cloning. Tip: if it the full-disk wipe process happens in less than five minutes, it may not be wiping the full drive. BleachBit does not do this kind of wipe. It is the most effective, but you cannot keep any data. I have not used [ShredOS](https://github.com/PartialVolume/shredos.x86_64), but it is an example of how to do this using nwipe. A single pass is plenty.

Note: the BleachBit wiping process wipes all the free space on the partition (disk 1), regardless of the folder. For example, if you wipe d:\my\folder , it would also wipe files that were previously deleted from d:\other\folder , but it would not wipe files deleted earlier from c:\ . The  significance of the folder is that you have permission to write: a normal Windows user may not be able to write to c:\ (root) without admin rights, but can write to his user folder under c:\users\username .

**Comment by kenstj** [comment]
Perfect – thanks Andrew!

**Comment by az0** [comment]
Closed because question was answered
