### ISSUE TITLE
I accidentely deleted too much files and files that are in write protected folders - v.4.6.0-win10-portable

### ISSUE THREAD

**Issue by cxbignekoc** [bleachbit/bleachbit#1700]
Bleachbit has accidentally deleted a lot of files i use.
I try to hold back my tears... (it's been a while since my last backup)

```
win10
BB 4.6.0 portable
winapp2.ini
```

BB touched mostly Folders and Files from this write protected Folder:

**C:\Users\username\Documents\***

Some Folders are left but are mostly empty.

What is **not touched**:

**C:\Users\username\AppData\Roaming\***

What selection in BB prevents erasing write protected files in this folder, except mark this folders they should be untouched?
I know this function and i had no issues before, after i installed the winapp2.ini to have more options.
So simewhere i use bb the wrong way or set up a wron checkmark.

How to find the Issue? (except the issue right in front of the computer)

**Comment by az0** [comment]
One way to troubleshoot is to select one group (e.g., Google Chrome) or individual options (e.g., Google Chrome - History) and run a preview for each one. Then search the preview for the paths that are affected. 

Tip: You can copy the BleachBit log to a text editor like Notepad, and then use the search in Notepad.

If you do find any option that would delete c:\users\username\documents, please let me know.
