### ISSUE TITLE
Adobe CC / clean support

### ISSUE THREAD

**Issue by TheAresjej** [bleachbit/bleachbit#171]
Add clean support to Adobe CC: folders "Tempzxpsign..." [...] - random
C:\Users\user\AppData\Local\Tempzxpsign...

**Comment by ROCKNROLLKID** [comment]
You can write your own cleaner with CleanerML. Please read here: http://docs.bleachbit.org/doc/cleanerml.html

You are probably better off writing your own cleaner because most of us probably are not knowledgeable of the program and don't really know what needs to be cleaned and what shouldn't be.

**Comment by az0** [comment]
Yes, the two options are 
1. To write your own cleaner in CleanerML, as ROCKNROLLKID suggested
2. Suggest this to be added to Winapp2. That is another GitHub repository

Thanks!
