### ISSUE TITLE
whenever i open bleachbit portable it shows this in red

### ISSUE THREAD

**Issue by AZTRA081** [bleachbit/bleachbit#1711]
The update information does not parse: b'\n<!doctype html>\n<html lang="en">\n<head>\n    <meta charset="utf-8">\n    <meta name="robots" content="noindex, nofollow">\n    <title>One moment, please...</title>\n    <style>\n    body {\n        background: #F6F7F8;\n        color: #303131;\n        font-family: sans-serif;\n        margin-top: 45vh;\n        text-align: center;\n    }\n    </style>\n    </head>\n<body>\n    <h1>Please wait while your request is being verified...</h1>\n    <form id="wsidchk-form" style="display:none;" action="/z0f76a1d14fd21a8fb5fd0d03e0fdc3d3cedae52f" method="GET">\n    <input type="hidden" id="wsidchk" name="wsidchk"/>\n    </form>\n    <script>\n    (function(){\n        var west=+((+!+[])+(+![]+[])+(+![])+(+![]+[])+(+!+[]+!![]+!![])+(+!+[]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![])+(+!+[]+!![]+[])),\n            east=+((+!+[])+(+!+[]+[])+(+!+[])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])+(+!+[]+!![])+(+!+[]+!![]+!![]+!![]+[])+(+!+[]+!![])+(+!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[])),\n            x=function(){try{return !!window.addEventListener;}catch(e){return !!0;} },\n            y=function(y,z){x() ? document.addEventListener(\'DOMContentLoaded\',y,z) : document.attachEvent(\'onreadystatechange\',y);};\n        y(function(){\n            document.getElementById(\'wsidchk\').value = west + east;\n            document.getElementById(\'wsidchk-form\').submit();\n        }, false);\n    })();\n    </script>\n</body>\n</html>'
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 189, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: syntax error: line 2, column 0

**Comment by az0** [comment]
For troubleshooting, please this

1. On the same computer and using the same network (ISP),  open a web browser
2. Visit https://update.bleachbit.org/update/4.6.0

You should see a brief document like this. I replaced a few parts with XXX

```
<updates>
<latest-version>4.6.0</latest-version>
<winapp2 url="https://download.bleachbit.org/winapp2/XXX" sha512="XXX"/>
</updates>
```

In your web browser, do you see this update document? If not, please copy what you see, and paste it here.

**Comment by az0** [comment]
There was no response in a month, so I am closing this issue. If you have more info about this issue, please add a comment to this issue and reopen it.
