### ISSUE TITLE
Message about anti-virus software could be in better English

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [bleachbit/bleachbit#1713]
The file In GUI.py (at line 877) speaks of 'the antivirus software'. The definite article (i.e., the 'the') suggests that a mention has been made already to the user of some (more or less definitely existing) anti-virus software. The following formulation would be better.

> There was an error loading the SQLite module; antivirus software may have blocked it.

(This bug report began as [this comment-upon-a-commit](https://github.com/bleachbit/bleachbit/commit/9ed80f11d12bd9af9f7598447e8e27757cc974a1#commitcomment-145806595).)

**Comment by az0** [comment]
@LinuxOnTheDesktop 
This change was released in [BleachBit 4.9.0 alpha](https://www.bleachbit.org/news/bleachbit-490-alpha)
