### ISSUE TITLE
unable to install or run on Windows 11

### ISSUE THREAD

**Issue by bfree61** [bleachbit/bleachbit#1717]
The code execution cannot proceed because MSVCR100.dll was not found.

I tried reinstalling.  I also tried the portable version.  Same applies

Older portable versions taken from my old notebook do work

Brian

**Comment by BPanther** [comment]
You need to install the vb runtimes.

**Comment by bfree61** [comment]
Sorry, but how do I do that?

**Comment by az0** [comment]
@bfree61
Which version are you using? What is the filename of the installer?

**Comment by bfree61** [comment]
Thank you so much.

Got it sorted now.

Thanks again

Brian

**Comment by bfree61** [comment]
My email was just saying thanks for the solution. It worked
