### ISSUE TITLE
WIndows 11 latest update

### ISSUE THREAD

**Issue by YouGetTheWetSpot** [bleachbit/bleachbit#1723]
Simply put it doesn't install correctly. I've tried it on 3 different machines. Both portable and normal install.

Just an fyi

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]

**Additional context**

**Comment by az0** [comment]
Tell me more. Does the installers start at all? Does the installer finish? Are there any error messages at any point? If there's an error message, please either transcribe it verbatim or paste a screenshot. 

Do all the machines have the same antivirus software? What is the brand of antivirus software? Please check the antivirus logs for any errors or warnings.

**Comment by az0** [comment]
When BleachBit 4.6.2 was first launched, its newness could have triggered [problems with SmartScreen](https://www.bleachbit.org/microsoft-defender-smartscreen). What happens if you try again now?

**Comment by az0** [comment]
SmartScreen should not be causing issues anymore for the official 4.6.2 release. If you have follow up information or questions on this topic, please reopen this issue ticket.
