### ISSUE TITLE
Running in a Standard User (Windows 11 64-bit)

### ISSUE THREAD

**Issue by tester06140** [bleachbit/bleachbit#1726]
When you run BleachBit in a standard user of Windows 11 and you answer YES in the user account control, you have to enter the password of an administrator. Then BleachBit deletes temporary files of the administrator not those of the current user (the standard user).

When you run BleachBit in a standard user of Windows 11 and you answer NO in the user account control, BleachBit deletes some files of the current user, but many errors are displayed in the results.

**Comment by az0** [comment]
The [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html) includes this

>Q: Why do I see permission denied errors on Windows?

>This happens when cleaning certain files, such as Windows system logs under c:\windows. A: When you first launch BleachBit it should prompt you with the User Access Control dialog, which asks, “Do you want to allow the following program to make changes to this computer.” Answer Yes to grant BleachBit the privileges to modify all files.

>If you answer No, then BleachBit will start, and it will still be able to clean data under your user profile. However, it will not have access to clean system data.

Does this help resolve your issue?

**Comment by az0** [comment]
If you have a follow up on this topic, reopen this issue.
