### ISSUE TITLE
Ctrl+Q to exit program

### ISSUE THREAD

**Issue by toboil-features** [bleachbit/bleachbit#1747]
Program can't be closed by Ctrl+Q, so I wish it would be able to.

![Showcase](https://github.com/user-attachments/assets/2e85eb47-387f-45a5-8d8d-d4fb643b2a4e)

**Comment by az0** [comment]
I added this for the classic GUI (as seen in BleachBit 4.6.2) but not the next-gen GUI. If you are on Linux, you can [run from source](https://docs.bleachbit.org/dev/running-from-source-code.html) (using the Git version). If you are on Windows, you can try a [CI build](https://ci.bleachbit.org/).

Later when [next-gen GUI](https://github.com/bleachbit/bleachbit_gui_next_gen) is ready, check again on this feature.

**Comment by az0** [comment]
@toboil-features 
This feature was released in [BleachBit 4.9.0 alpha](https://www.bleachbit.org/news/bleachbit-490-alpha)
