### ISSUE TITLE
Error wiping encrypted swap on Ubuntu

### ISSUE THREAD

**Issue by new2ubuntu2** [bleachbit/bleachbit#186]
I have been asked to create a bug report regarding errors that I am receiving in Bleachbit.  Below are details of the error that I have received and posted in the forum:

About to execute bleachbit.
This command needs root privileges to be executed.
Using sudo...
Enter xxxxx password at prompt.
[sudo] password for xxxxx:

(bleachbit:4424): IBUS-WARNING **: The owner of /home/xxxxx/.config/ibus/bus is not root!
debug: DeepScan.scan: searches= {'/home/xxxxx': [u'^\\.DS_Store$', u'\\.[Bb][Aa][Kk]$', u'[a-zA-Z]{1,4}~$', u'^~wr[a-z][0-9]{4}\\.tmp$', u'^ppt[0-9]{4}\\.tmp$', u'^Thumbs\\.db$', u'^Thumbs\\.db:encryptable$']}
debug: DeepScan.scan: searches= {'/home/xxxxx': [u'^\\.DS_Store$', u'\\.[Bb][Aa][Kk]$', u'[a-zA-Z]{1,4}~$', u'^~wr[a-z][0-9]{4}\\.tmp$', u'^ppt[0-9]{4}\\.tmp$', u'^Thumbs\\.db$', u'^Thumbs\\.db:encryptable$']}
Error in execution of
Traceback (most recent call last):
File "/usr/share/bleachbit/bleachbit/Worker.py", line 84, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/bleachbit/Command.py", line 146, in execute
self.func(self.path)
File "/usr/share/bleachbit/bleachbit/Special.py", line 280, in delete_mozilla_url_history
FileUtilities.execute_sqlite3(path, cmds)
File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
'%s: %s' % (Common.decode_str(exc), path))
DatabaseError: UNIQUE constraint failed: moz_hosts.host: /home/ghost/.mozilla/firefox/sw06euev.default/places.sqlite
directory is not empty: /home/xxxxx/.cache/wallpaper
debug: DeepScan.scan: searches= {'/home/xxxxx': [u'^\\.DS_Store$', u'\\.[Bb][Aa][Kk]$', u'[a-zA-Z]{1,4}~$', u'^~wr[a-z][0-9]{4}\\.tmp$', u'^ppt[0-9]{4}\\.tmp$', u'^Thumbs\\.db$', u'^Thumbs\\.db:encryptable$']}
debug: running cmd ['swapon', '-s']
debug: detected swap devices: None
debug: wipe_memory() pid 4424 waiting for child pid 4450
debug: new nice value 19
debug: dropping privileges of pid 4450 to uid 1000
debug: physical free: 1,78GB (1779470336 B)
info: allocating and wiping 711,6MB (711584972 B) of memory
debug: physical free: 1,07GB (1066520576 B)
info: allocating and wiping 426,6MB (426608230 B) of memory
debug: physical free: 652,8MB (652779520 B)
info: allocating and wiping 261,1MB (261080678 B) of memory
debug: physical free: 410,8MB (410820608 B)
info: allocating and wiping 164,3MB (164328243 B) of memory
debug: physical free: 257,9MB (257896448 B)
info: allocating and wiping 103,2MB (103158579 B) of memory
debug: physical free: 262,9MB (262934528 B)
debug: freeing 164,3MB of memory
debug: physical free: 428,1MB (428085248 B)
debug: freeing 261,1MB of memory
debug: physical free: 689,6MB (689639424 B)
debug: freeing 426,6MB of memory
debug: physical free: 1,12GB (1117097984 B)
debug: freeing 711,6MB of memory
debug: physical free: 1,83GB (1829531648 B)
wrote 1 files and 278141722624 bytes in 4895 seconds at 56.82 MB/s
20480 bytes and 1333 inodes available to non-super-user
20480 bytes and 1333 inodes available to super-user
wrote 2 files and 24232226816 bytes in 322 seconds at 75.24 MB/s
0 bytes and 1730773 inodes available to non-super-user
1627389952 bytes and 1730773 inodes available to super-user
debug: re-enabling swap
Error in execution of
Traceback (most recent call last):
File "/usr/share/bleachbit/bleachbit/Worker.py", line 84, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/bleachbit/Command.py", line 134, in execute
for func_ret in self.func():
File "/usr/share/bleachbit/bleachbit/Memory.py", line 283, in wipe_memory
enable_swap_linux()
File "/usr/share/bleachbit/bleachbit/Memory.py", line 101, in enable_swap_linux
raise RuntimeError(outputs[1].replace("\n", ""))
RuntimeError: swapon: stat of /dev/mapper/cryptswap1 failed: No such file or directory
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
Incorrect password or command failed. Try again? (y/N)

**Comment by az0** [comment]
Try unchecking the two options circled in red in the following screenshot. Then you should no longer get the error about cryptswap1. You do not need those because your system is already encrypted.

https://snag.gy/Qgq7oT.jpg

I work work to prevent the error about cryptswap1

**Comment by az0** [comment]
Fixed in commit 2f7f3ac0.

@new2ubuntu2 
If you are able to test, let me know, and I'll send you instructions. I would appreciate your help.

**Comment by az0** [comment]
You could test the fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
