### ISSUE TITLE
Reminiscent easytag data

### ISSUE THREAD

**Issue by tiemay** [bleachbit/bleachbit#20]
`~/.easytag/easytagrc` will store some usage history, but it also stores user settings. Does someone know of a way to clean this without deleting the settings?

To recreate the data I’m talking about, select an album, click the “Write Playlist” button, (optionally) select “Use mask” and enter whatever you want, save, and whatever was in the “Use mask” field will be written to easytagrc as `playlist_name=<whatever you entered>`. The next time you go to create a playlist, this data will be recalled to the “Use Mask” field, and will be used to recreate play_list_name.mask if that file was deleted.

This is limited to the last entry, and I suspect something similar is happening with playlist_content.mask

**Comment by az0** [comment]
Sorry for the lack of response. If this still an issue, please reopen the ticket.
