### ISSUE TITLE
Move the "free disk space" option

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#201]
It seems like it is getting more and more common that people are just randomly checking entries in BleachBit without really knowing what they do, and one of the entries is the "free disk space" entry. It is also in a bad location and people are probably treating it like a normal cleaning rule, when it is not.

I think it's about time we consider moving it to a tab section with maybe a first time use warning message that explains exactly what this does. Since we have been doing some GUI updates, this might be a good time to do this.

**Comment by theatre-x** [comment]
Do you have a link to some of the GUI changes? I'm curious.

**Comment by az0** [comment]
@theatre-x  You asked about the GUI changes. There is probably a much better screenshot somewhere, but here is a screenshot for GTK 3 https://github.com/bleachbit/bleachbit/issues/331 

There is also an open pull request here for some changes https://github.com/bleachbit/bleachbit/pull/347

**Comment by az0** [comment]
I added a explainatory note to the log when the process starts. The risk is also mitgated because now there is a "stop" button.
