### ISSUE TITLE
BleachBit should remember window size and position

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#204]
Discussed here: https://www.bleachbit.org/forum/request-mantain-size

**Comment by az0** [comment]
Mentioned here
https://www.bleachbit.org/forum/bb-does-not-remember-win-sizepos

**Comment by az0** [comment]
This might be helpful for a developer https://wiki.gnome.org/HowDoI/SaveWindowState

**Comment by az0** [comment]
This feature is ready for testing with [BleachBit CI build 2.3.1150](https://ci.appveyor.com/project/az0/bleachbit/history) and most later builds
