### ISSUE TITLE
Application freezes with LANG=C scanning filename with non-ASCII characters

### ISSUE THREAD

**Issue by thezilion** [bleachbit/bleachbit#209]
Version: 1.17
System: Gentoo with Kernel 4.10.4

Log of error:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/bleachbit/Worker.py", line 255, in run
    for dummy in self.run_deep_scan():
  File "/usr/lib64/python2.7/site-packages/bleachbit/Worker.py", line 314, in run_deep_scan
    for path in ds.scan():
  File "/usr/lib64/python2.7/site-packages/bleachbit/DeepScan.py", line 87, in scan
    for (dirpath, dirnames, filenames) in normalized_walk(top):
  File "/usr/lib64/python2.7/site-packages/bleachbit/DeepScan.py", line 61, in normalized_walk
    for result in os.walk(top, **kwargs):
  File "/usr/lib64/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 73: ordinal not in range(128)

Bleachbit freezing while cleaning. I run on terminal and show this message /\

**Comment by az0** [comment]
This is good information, so thank you for reporting it. It looks like the application failed when processing a path in the user directory during the deep scan operation. The pathname has a non-ASCII character. This may be enough information to reproduce and fix the issue. A temporary workaround is uncheck all the deep scan options (or to rename the path).

**Comment by thezilion** [comment]
Right.. thanks!

**Comment by az0** [comment]
In a terminal would you please run the command `locale`, copy the output, and paste it here?

I am not seeing this error here with `LANG=en_US.UTF-8`

**Comment by thezilion** [comment]
Of corse.

LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE=C
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

**Comment by thezilion** [comment]
I modified my locale to en_US.UTF-8 and worked.

**Comment by az0** [comment]
This can be fixed later because there is a workaround: change LANG from C to en_US.UTF-8 or something like that

**Comment by az0** [comment]
I fixed this a few weeks ago. Are you able to test by applying the patch for commit 7f7451f? Alternatively you can download the whole[ DeepScan.py ](https://raw.githubusercontent.com/bleachbit/bleachbit/7f7451ffaf6a0a045509dd228dd30aab4b7f6065/bleachbit/DeepScan.py)file and overwrite your copy. If you have further issues, please reopen the ticket.

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.
