### ISSUE TITLE
BleachBit forgets preferences

### ISSUE THREAD

**Issue by BBProblem** [bleachbit/bleachbit#211]
Using BleachBit 1.12 on Windows 7/64.
Setting preferences such as 'exit after cleaning' are never remembered. Aggravating and time consuming problem when cleaning large numbers of files.

**Comment by ROCKNROLLKID** [comment]
I can't replicate this on my Windows 10 system. Can you try BleachBit 1.17 beta and see if it still happens there. https://www.bleachbit.org/news/bleachbit-117-beta

**Comment by az0** [comment]
Dear BBProblem,

Are you using the portable or installed version?

Do you use the menu option "Shred Settings and Quit"?

Is the computer a personal computer or part of a corporate network?

**Comment by az0** [comment]
I am closing because of lack of response after 263 days. If you have new information about this issue, please reopen this issue
