### ISSUE TITLE
No description of "shred settings and quit"

### ISSUE THREAD

**Issue by bendover22** [bleachbit/bleachbit#216]
AFAIK, there's no description anywhere of menu option "shred settings & quit."
Users may learn what it does - the hard way, but it's ambiguous.  There should be a tooltip and / or basic description of menu options in the documentation.

**Comment by ROCKNROLLKID** [comment]
We had something similar planned for a future BleachBit, to have a first startup guide that goes through many of the settings and such.

**Comment by mkhon** [comment]
It does not look that gio.MenuModel allows to specify tooltips:

The ‘standard’ attributes and link types have predefined names: Gio.MENU_ATTRIBUTE_LABEL, Gio.MENU_ATTRIBUTE_ACTION, Gio.MENU_ATTRIBUTE_TARGET, Gio.MENU_LINK_SECTION and Gio.MENU_LINK_SUBMENU.

See also: https://gitlab.gnome.org/GNOME/gtk/issues/785

**Comment by az0** [comment]
Thanks for the research, Max. How about adding a string of text to the
confirmation dialog?

Text would be something like: "This function deletes all BleachBit's
settings and then quits the application. Use this to hide your use of
BleachBit or to reset its settings. The next time you start it, the
settings will initialize to default values."
