### ISSUE TITLE
Remove "Start with computer"

### ISSUE THREAD

**Issue by tstenner** [bleachbit/bleachbit#218]
For some reason the test for the autostart option is failing. Since (at least as far as I see it) people who use bleachbit either want less autostarts or are computer savvy enough to run the it as a scheduled task via the CLI I'd suggest removing it altogether.

**Comment by ROCKNROLLKID** [comment]
I suggested to switch that to a "Run at Windows shutdown", like a lot of other cleaners do, as I too didn't think a "Start with computer" option wasn't necessary.

**Comment by az0** [comment]
OK. Do you want to submit a pull request?

**Comment by tstenner** [comment]
I'll do it on the weekend
