### ISSUE TITLE
error chromium

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#220]
Clean file 0 /home/user/.config/chromium/Default/History
Error in execution of <bleachbit.Command.Function instance at 0xb039580c>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 156, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 164, in delete_chrome_favicons
    raise RuntimeError('%s is version %d' % (path, ver))
RuntimeError: /home/user/.config/chromium/Default/Favicons is version 33
Delete 4,1kB /home/user/.config/chromium/Default/History Provider Cache

BleachBit version 1.17
GTK version 2.24.30
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = xfce
platform.linux_distribution() = ('LinuxMint', '18.1', 'serena')
platform.platform = Linux-4.4.0-79-generic-i686-with-LinuxMint-18.1-serena
platform.version = #100-Ubuntu SMP Wed May 17 19:57:27 UTC 2017
sys.executable = /usr/bin/python
sys.version = 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

Chromium
Version 58.0.3029.110 Built on Ubuntu , running on LinuxMint 18.1

**Comment by az0** [comment]
Thank you for the good bug report. I confirmed with 58.0.3029.110  on Ubuntu 16.04

**Comment by az0** [comment]
Fixed in commit dca5493a0b0f9725883a7d6abdec9030a8468c4f
