### ISSUE TITLE
[Installation] Missing Description of Components

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#221]
During the installation progress I can't see the description of the components when I hover the mouse over single components, even if I click on them.

Details:

- Windows 10 Pro
- BleachBit v1.12

**Comment by ROCKNROLLKID** [comment]
That's weird. They should show when you click on the entries. Maybe try uninstalling and reinstalling BleachBit?

**Comment by az0** [comment]
The installer gives instructions "position your mouse over a component to see its description," but I think the descriptions are not set up.  I see this on Windows XP with BleachBit 1.17.

Here is a counterexample
http://nsis.sourceforge.net/mediawiki/images/e/e8/Cmpntdescrtf.png

We can add these

**Comment by mkhon** [comment]
The descriptions of sections will be displayed on the components page, when the user hovers the mouse over a section. If you don't want to use descriptions, use the MUI_COMPONENTSPAGE_NODESC interface setting.

To set a description for a section, you have to add an additional parameter to the Section commmand with a name for the define that should contain the section number.

Section "Section Name 1" Section1
...
SectionEnd

Use these macros to set the descriptions:

LangString DESC_Section1 ${LANG_ENGLISH} "Description of section 1."
LangString DESC_Section2 ${LANG_ENGLISH} "Description of section 2."

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
!insertmacro MUI_DESCRIPTION_TEXT ${Section1} $(DESC_Section1)
!insertmacro MUI_DESCRIPTION_TEXT ${Section2} $(DESC_Section2)
!insertmacro MUI_FUNCTION_DESCRIPTION_END

For the uninstaller, use the MUI_UNFUNCTION_DESCRIPTION_BEGIN and MUI_UNFUNCTION_DESCRIPTION_END macros.

**Comment by az0** [comment]
Let's briefly hold work on this until this PR is done: https://github.com/bleachbit/bleachbit/pull/1461

**Comment by sanjaykaria** [comment]
Seems this issue is fixed by [PR 1468](https://github.com/bleachbit/bleachbit/pull/1468)

**Comment by az0** [comment]
The original user who submitted this no longer has an account, but I will have someone else test during beta.

> Seems this issue is fixed by [PR 1468](https://github.com/bleachbit/bleachbit/pull/1468)

@sanjaykaria 
Thanks, I added a cross link (the development section, next to milestone).
