### ISSUE TITLE
Security issue ? (Windows)

### ISSUE THREAD

**Issue by mlrx** [bleachbit/bleachbit#224]
BleachBit version 1.12 (portable)
MS Windows 7 x64 Pro
In a "Restricted user" environment
-------------------------------------

Hello,
When I use a cleanup option which by necessity will have to restart the "explorer.exe" process, sometimes
this one seems to be restarted with administrator rights.
This seems logical if the process obtains an elevation of privileges by filiation.

Do you think, as I do, that there is a (limited ?) security problem there?

Thank you all for your work.
Best Regards,
mlrx.

**Comment by ROCKNROLLKID** [comment]
This was fixed in the beta release here: https://www.bleachbit.org/news/bleachbit-117-beta

Can you try that and see if it still happens?

**Comment by mlrx** [comment]
Indeed, this does not seem to be happening anymore with the new version.
Thank you very much for your fast response.

Regards,
mlrx.

**Comment by az0** [comment]
ROCKNROLLKID: Thank you for pointing out the fix

mlrx: Thank you for verifying the fix
