### ISSUE TITLE
Error in execution of <bleachbit.Command.Function instance at 0x7fb97483d4d0>

### ISSUE THREAD

**Issue by vladislavyuzbekov** [bleachbit/bleachbit#225]
Bleachbit 1.17 Ubuntu 17.04

apt-get autoclean 0 
Error in execution of <bleachbit.Command.Function instance at 0x7fb97483d4d0>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 138, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 608, in apt_autoremove
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get --yes autoremove':
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  linux-headers-4.10.0-24 linux-headers-4.10.0-24-generic
  linux-headers-4.10.0-25 linux-headers-4.10.0-25-generic
  linux-headers-4.10.0-26 linux-headers-4.10.0-26-generic
  linux-image-4.10.0-24-generic linux-image-4.10.0-25-generic
  linux-image-4.10.0-26-generic linux-image-extra-4.10.0-24-generic
  linux-image-extra-4.10.0-25-generic linux-image-extra-4.10.0-26-generic
0 upgraded, 0 newly installed, 12 to remove and 0 not upgraded.
After this operation, 923 MB disk space will be freed.
dpkg: error: PATH is not set
E: Sub-process /usr/bin/dpkg returned an error code (2)

**Comment by az0** [comment]
Thank you for the report, @vladislavyuzbekov . I confirm this bug with BleachBit 1.17 (git commit e93e453e5fa78e224fbdf0dc1d0f5d20343476d5) on Ubuntu 16.04.

**Comment by az0** [comment]
Fixed in Git commit 71f418cba29ebc7b9d84ef9ecfc6c4521abac4e8 for the next release

**Comment by az0** [comment]
You can test this in [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta)
