### ISSUE TITLE
Creating exe using python setup.py py2exe throws error

### ISSUE THREAD

**Issue by atishagrawal** [bleachbit/bleachbit#227]
I tried creating exe from the source code by using this command
`python setup.py py2exe`

I got this error

`C:\bleachbit>setup.py py2exe`
`running py2exe`
`running build_py`
`*** searching for required modules ***`
`error: [Errno 2] No such file or directory: 'bleachbit_console.py'`

**Comment by az0** [comment]
Atish,

Please see how it is done here

https://github.com/bleachbit/bleachbit/blob/master/appveyor.yml

**Comment by az0** [comment]
I have not heard back in eight days, so I assume this is resolved. Closing
