### ISSUE TITLE
bleach bit winapp.ini error on close

### ISSUE THREAD

**Issue by stevengregory2007** [bleachbit/bleachbit#240]
Once I download the winapp.ini update with Bleachbit I start getting an error upon closing Bleachbit.  “Errors Occurred;  see the log file …….”.   

Log File:
Traceback (most recent call last):
  File "bleachbit\Winapp.pyo", line 153, in __init__
  File "bleachbit\Winapp.pyo", line 271, in handle_section
  File "bleachbit\Winapp.pyo", line 194, in excludekey_to_nwholeregex
NotImplementedError: REG not supported in ExcludeKey

**Comment by ROCKNROLLKID** [comment]
The issue is that there is a entry in Winapp2 with a exclude key pointing at a registry key, but BleachBit doesn't know what this means.

What BleachBit version are you using?

Can you try BleachBit 1.17 beta and see if this issue still happens: https://www.bleachbit.org/news/bleachbit-117-beta

**Comment by az0** [comment]
Thanks for the report

For now I fixed this by removing the one cleaner that uses the unsupported option and by creating a script to detect this in the future
https://github.com/bleachbit/winapp2.ini/commit/5fd9f8a3bae359e0bba1b5361e720dc265bc2108
https://github.com/bleachbit/winapp2.ini/commit/9b237f33e7ddaaa294ca7bdffef0a5b846793c1f


I filed a separate issue to support the REG
https://github.com/bleachbit/bleachbit/issues/241

I'm pushing out the new Winapp2.ini now

**Comment by stevengregory2007** [comment]
Thank you guys.   That fixed it!!!!
