### ISSUE TITLE
Google Chrome / Error in execution of <bleachbit.Command.Function instance at 0x03465788>

### ISSUE THREAD

**Issue by Braed** [bleachbit/bleachbit#244]
This error hasn't affected my ability to use BleachBit but I thought i'd report it to you anyway.  
Not sure how much of the log you want, but here's a section surrounding the error:

````
Mark for deletion 0 C:\WINDOWS\temp\FXSTIFFDebugLogFile.txt
net stop wuauserv 0 
Delete 0 C:\WINDOWS\SoftwareDistribution\Download\SharedFileCache
Delete 0 C:\WINDOWS\SoftwareDistribution\Download
net start wuauserv 0 
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Preferences
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\databases\Databases.db
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\History
Error in execution of <bleachbit.Command.Function instance at 0x03465788>
Clean file 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Web Data
Vacuum 0 C:\Users\Brad\AppData\Local\Google\Chrome\User Data\Default\Cookies
````

**Comment by az0** [comment]
Thanks for the bug report. This is related to Google Chrome, based on the context you provided.

Which version of BleachBit?

Do you have this in [BleachBit version 1.17](https://www.bleachbit.org/news/bleachbit-117-beta)?

I am working on preparing the next public beta, but it's delayed because of a security certificate renewal. If you would like it sooner, you can try version 1.17.553 or newer from the [CI site](http://ci.bleachbit.org/).  

Note: Version 1.7.553 is much newer than 1.17 beta

**Comment by az0** [comment]
@Braed 
Have you had a chance to read my last message and test a newer version?

**Comment by az0** [comment]
Please test [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta) and reply in this bug ticket with how it goes. Also, please reopen this ticket if the error messages continues.

**Comment by Braed** [comment]
No errors with the latest update. "Free disk space" did cause windows to freeze for a while (I actually had to end the bleachbit process and clean again with this disabled).

Sorry for such a delayed response, i forgot to check my GitHub notifs.
