### ISSUE TITLE
Does BleachBit check for Wow6432Node automatically for Winapp2?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#247]
It has been suggested over at the Winapp2 thread to help trim Winapp2 a bit by removing all detect for Wow6432Node because CCleaner automatically checks for that already. I just wanted to know if BleachBit does, too. If not, it might be a good idea as there are many entries with these detects and could help save some Winapp2 space.

Related: https://forum.piriform.com/index.php?showtopic=32310&p=288038

**Comment by az0** [comment]
I think you mean like this
https://github.com/MoscaDotTo/Winapp2/commit/84be743b5214071f5e9f9f0708bcbd16fbc7114d#diff-9dc8dfcda6088a592d7e1c8ea13cc70bL7647

No, it is not explicitly checked. It may be implicit, but I am not sure.

**Comment by ROCKNROLLKID** [comment]
Yes those are also still related. The left over detects should still work for most systems, but it is highly recommend for compatibility to maybe do a check automatically.

**Comment by az0** [comment]
It seems to be working well
