### ISSUE TITLE
Evolution Cache Problem

### ISSUE THREAD

**Issue by returning2linux** [bleachbit/bleachbit#249]
Evolution is an email client and personal information manager for Linux. Per request, I am submitting a new bug report based on a comment that I made to an existing thread on Launchpad.

[https://bugs.launchpad.net/bleachbit/+bug/1537299](https://bugs.launchpad.net/bleachbit/+bug/1537299)

Enabling system -> cache activates the reset of Evolution's cache, even if the evolution -> cache box is unchecked. This problem persists in BleachBit versions 1.12 and 1.17beta. Please find my system information below. Thank you.

BleachBit version 1.17
GTK version 2.24.30
local_cleaners_dir = /usr/share/cleaners
locale_dir = /usr/share/locale/
options_dir = /home/bob/.config/bleachbit
personal_cleaners_dir = /home/bob/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = /usr/bin/startxfce4
os.getenv('LOGNAME') = blank
os.getenv('USER') = blank
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/blank
platform.linux_distribution() = ('Ubuntu', '16.04', 'xenial')
platform.platform = Linux-4.8.17-galliumos-x86_64-with-Ubuntu-16.04-xenial
platform.version = #1 SMP PREEMPT galliumos4 Thu Feb 23 02:27:28 UTC 2017
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python
sys.version = 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by az0** [comment]
@returning2linux 

Are you able to please test? In Git commit 2415b44db5199d366920f43aa6f08725c1e7eab7 there is a one-line change to `Cleaner.py`. You can make the edit on your system, or you can copy the whole file from GitHub to replace your `Cleaner.py` file.

Here's the whole file https://github.com/bleachbit/bleachbit/blob/2415b44db5199d366920f43aa6f08725c1e7eab7/bleachbit/Cleaner.py

If you need more help or another way to test, let me know

**Comment by returning2linux** [comment]
Thanks for the change. I don't have systems with Evolution to test any
more, but know that other users will benefit from the fix.
