### ISSUE TITLE
error: Konqueror is not running 

### ISSUE THREAD

**Issue by thomasleecraven** [bleachbit/bleachbit#253]
Password: 
linux:~ # ps -ef |grep konq
craven    2662  2524  0 05:19 ?        00:00:00 /usr/bin/konqueror -session 10e4696e75000151024870800000025410054_1510571925_958944
craven    2668     1  0 05:19 ?        00:00:00 /usr/bin/konqueror --preload
root      4394  4354  0 05:41 pts/2    00:00:00 grep --color=auto konq
linux:~ #

**Comment by az0** [comment]
Which version of BleachBit?

Which Linux distribution and version?

Is BleachBit refusing to clean Konqueror because it's running? Do you mean it's always running because it's a basic part of the operating system?

**Comment by Tobias-B-Besemer** [comment]
Close this issue, too ???

**Comment by az0** [comment]
No response to the question from 2018
