### ISSUE TITLE
Bleachbit 1.12

### ISSUE THREAD

**Issue by rhinbc** [bleachbit/bleachbit#255]
When I run Bleachbit 1.12 on Windows 10 Pro 1703, I have to logoff and back on because all the desktop icons flash until I do.
Any idea why?
Thanks.

**Comment by az0** [comment]
This sounds like an issue fixed in [BleachBit 1.17](https://www.bleachbit.org/news/bleachbit-117-beta)

It's this issue
>Clean Windows Explorer - Thumbnails, and explorer.exe should restart without administrator privileges.

If this doesn't help, please reopen the ticket

**Comment by rhinbc** [comment]
Thanks Andrew...
I just tried 1.17, and it does the same thing.
I also checked 1.12, and I have Thumbnails cleaning turned off,
and also in 1.17.
No problem... it’s a minor detail considering the good cleaning Bleachbit does.

**Comment by rhinbc** [comment]
I turned off all cleaning for Windows Explorer 
and   no more desktop icons flashing. so I will run it that way.
Thanks.
