### ISSUE TITLE
Freeze with preview or cleaning of Steam games (via Winapp2.ini)

### ISSUE THREAD

**Issue by vgturtle127** [bleachbit/bleachbit#257]
This issue occurs on a Windows 10 laptop running BleachBit 1.12. This has been happening for awhile, but I thought it was an issue with the Winapp2.ini so I didn't report it. Then I realized it shouldn't matter what's in the file, it still shouldn't crash, heh.

It should be noted I can't duplicate this on systems without Steam, Origin, etc. So it has to be an issue with deleting things that are there because if they aren't there it runs fine.

I can run all of the other options in BleachBit, but if I choose any of the options within the games category, the crash happens the second the games category starts cleaning.

The only thing I can do to clean my system is uncheck the games category.

I'm not really sure what other information I can give, so if you need anything else please let me know. I have included the log file here.

[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/1524430/bleachbit.exe.log)

UPDATE: This issue occurs on Windows 10 regardless of version, and occurs on BleachBit 1.12 and the latest commit built from GitHub.

The issue is with the "Steam Games", "Steam Installers", and "Steam Logs" entries.

Those entries contain these values:

[Steam Games*]
Section=Games
Detect=HKCU\Software\Valve\Steam
Default=False
FileKey1=%ProgramFiles%\Steam\steamapps|*.mdmp;*.tmp;*.dmp;*.icns;.DS_Store;logfile.*;*.log;text.txt;output_log.txt;*log.txt;log*.txt|RECURSE
FileKey2=%ProgramFiles%\Steam\steamapps\common\*\Cache|*.*|RECURSE
FileKey3=%ProgramFiles%\Steam\steamapps\common\*\config\html|*.*|RECURSE
FileKey4=%ProgramFiles%\Steam\steamapps\common\*\DebugData|*.*|RECURSE
FileKey5=%ProgramFiles%\Steam\steamapps\common\*\docs|*.*|RECURSE
FileKey6=%ProgramFiles%\Steam\steamapps\common\*\*\downloads|*.*|RECURSE
FileKey7=%ProgramFiles%\Steam\steamapps\common\*\EULA|*.*|RECURSE
FileKey8=%ProgramFiles%\Steam\steamapps\common\*\Manual|*.*|RECURSE
FileKey9=%ProgramFiles%\Steam\Steamapps\temp|*.*|RECURSE
ExcludeKey1=PATH|%ProgramFiles%\Steam\steamapps\common\Supreme Ruler 1936\Cache\|*.*
ExcludeKey2=PATH|%ProgramFiles%\Steam\steamapps\common\Supreme Ruler Cold War\Cache\|*.*
ExcludeKey3=PATH|%ProgramFiles%\Steam\steamapps\common\Supreme Ruler Ultimate\Cache\|*.*

[Steam Installers*]
Section=Games
Detect=HKCU\Software\Valve\Steam
Warning=Run this entry AFTER you have launched all of your steam games once, as they will not be able to load for the first time. After the first launch, these files become useless.
Default=False
FileKey1=%ProgramFiles%\Steam\Steamapps\common|*redist.msi*;dosbox*.tar.gz;*redist*.exe;*setup*.msi;*pbsvc*.exe;*UPlay*Installer*.exe;WMFADist.exe;SPInstaller.exe;python*.msi;bitmap2substance_installer.exe;perforce*.exe;p4vinst*.exe;mcpp*.*;firewallinstallhelper.dll;gameuxinstallhelper.dll;eadm-installer.exe;wmpappcompat.exe;umdf.exe;Microsoft .NET Framework*.cmd;Microsoft .NET Framework*.bat;NDP*.exe;WMFDist*.exe;PhysX*.msi;PhysX*.exe;*d3dx11*.cat;*d3dx11*.inf;prompt.bat;GDFInstall.exe;DSInstaller.exe;d3d*.exe;directx*.exe;*.msu;Windows*-KB*.exe;cmp.bat;PVRTexTool.exe;wmp11-windowsxp-x86-enu.exe;*.vdk;RGB9RAST*.msi;WIC*.exe;XPSEPC*.exe;msxml6.msi;AdbeRdr*.*;*inst*.vdf;*.cab;*.msp;ac3filter*.exe;GamesExplorerIntegrationTool.exe;install.ini;globdata.ini;install.exe;install.res.*.dll;eula.*.*;DSETUP.DLL;oalinst.exe;dsetup32.dll;D3D*Install.exe;D3D*Install*.dll;dotnetfx*.exe;*vc*red*.exe;*vc*red.msi;WindowsInstaller*.exe;locdata.*.ini;setupres.*.dll;*setup*.exe;wapres.*.dll;*NetFx*.*|RECURSE

[Steam Logs*]
Section=Games
Detect=HKCU\Software\Valve\Steam
Default=False
FileKey1=%AppData%\SteamVR\Logs|*.*|REMOVESELF
FileKey2=%ProgramFiles%\Steam|*.log;*log.last;connection_log_*.txt;*_log.txt;remote_connections.txt;vr*_*.txt|RECURSE
FileKey3=%ProgramFiles%\Steam\logs|*.*
FileKey4=%ProgramFiles%\Steam\vr\runtime\logs|*.*|RECURSE
FileKey5=%LocalAppData%\VirtualStore\Program Files*\Steam|*.log;*log.last;connection_log_*.txt;*_log.txt;remote_connections.txt;vr*_*.txt|RECURSE

**Comment by ROCKNROLLKID** [comment]
If you uncheck only "Steam Games", "Steam Installers", and "Steam Logs" entries, does it still happen?

Your issue sounds like it is related to this: https://bugs.launchpad.net/bleachbit/+bug/1265963

**Comment by az0** [comment]
1. What exactly does the crash look like? Perhaps you can post a screenshot or the verbatim error message.
1. Does the crash happen with a preview of the games category?
2. How many objects does the preview show of the games category? I wonder if there are very many.
3. Would you please try [BleachBit 1.17.553 from the CI site](http://ci.bleachbit.org/)? This is the latest version, and I hope to soon publish it as a beta and then the final BleachBit 2.0.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Yeah, just unchecking those mitigates the issue, so it narrows it down a little at least.

@az0 
1. The application softlocks and then the Windows error for reporting issues comes up.
2. Yes.
3. I don't know, it crashes before I can see the results. It would be nice to see the results because maybe it is creating a billion entries or something and it can't handle all of it or something.
4. That version crashes on previewing and on cleaning...

**Comment by az0** [comment]
By soft lock, you mean the "application is not responding" message?

**Comment by vgturtle127** [comment]
@az0 Well, not at first. It locks up and does nothing until you click within the window. But yes, after that the "application is not responding" message appears.

**Comment by az0** [comment]
OK, all this information does help narrow it down. I agree that this issue does seem like that old Launchpad ticket. I thought that issue was related to many files, but when I tested cleaning a folder (not Steam) with many files, it seemed quick on my system, so I need a way to reproduce this or to get more specific on what Steam is doing.

Perhaps someone could run a preview of Steam using one of the non-BleachBit application that works with Winapp2.ini (there are three others), grabbing the list of files, and attaching them? (GitHub allows txt, log, and zip attachments up to 25MB)

**Comment by vgturtle127** [comment]
@az0 Do you mean CCleaner, System Ninja, etc.?

**Comment by vgturtle127** [comment]
@az0 It's odd, but CCleaner and System Ninja don't find anything...

**Comment by az0** [comment]
Yes, I thought one of those applications would find many files. Hmm

**Comment by vgturtle127** [comment]
@az0 Me too. Is there anything else I can do to help?

**Comment by az0** [comment]
vgturtle127: I need a way to reproduce it. At the moment I am not sure what
is most efficient way, but maybe you could look at sending me the Steam
files that should be matched by the Winapp2.ini files. Do you know how to
find the,? Then I could unpack them here and try to reproduce it on my
system.

**Comment by ROCKNROLLKID** [comment]
I am pretty sure his issue is the same as mine. The best way to reporoduce this is with a bunch of games installed through Steam. Try going around Steam and install 5+ free (big) games to it. Make sure to run each of them at least once before testing. Then run a preview of "Steam Games", "Steam Installers", "Steam Logs" and you will see that it runs super slow. The more games that are installed, the slower it goes.

For me, it takes a very long time to complete and I have 15 games installed currently.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Do you have a pretty decent system? The system I am working on is a somewhat low-end laptop...

**Comment by ROCKNROLLKID** [comment]
Yes, I am on a 840 EVO 1TB SSD.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID I am using a system with a dual-core 2.16GHz CPU, 4GB of RAM, and a hard drive. Maybe BleachBit runs out of RAM?

**Comment by ROCKNROLLKID** [comment]
Unlikely, BleachBit is only 32-bit on Windows, so it is not going to use more then 4gb regardless.

This issue has been around awhile, but we never been able to determine the cause. We once had a bounty for this, but had no luck finding anyone (we had one, but he backed out without reason).

Your system seems decent enough for BleachBit. I mean a hard drive is obviously going to make BleachBit slower then a SSD because BleachBit heavily depends on disk speeds, but other then that I do not see  anything wrong with your system.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Yeah...Hm...

Steam is closed when you tried the cleaning, right?

**Comment by ROCKNROLLKID** [comment]
Yes.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Do you run BleachBit as admin?

**Comment by ROCKNROLLKID** [comment]
Doesn't matter. The issue is most likely a internal issue and not a user caused one.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Alright. Thought maybe I was on to something. Heh.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID @az0 Could it be that the recursive function of the entries is causing it to crash with too many subdirectories? Perhaps special characters in the folder names?

The file types seem to be mostly log files, but there are memory dumps. I think CCleaner or System Ninja had issues with crashing while deleting memory dumps because they were protected by Windows, and they had to fix the issue in an update.

Just spitballing until I can pull the code to my drive.

**Comment by ROCKNROLLKID** [comment]
Unlikely either. There is a separate memory dump cleaner for Windows that runs fine for me. BleachBit already knows how to handle locked files.

I believe the issue is with the preview part, not the cleaning part. I am actually not a programmer, so I do not know for sure.

Feel free to take a crack at this if you know Python code.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID If you just hit clean, it skips the preview part though, doesn't it?

**Comment by ROCKNROLLKID** [comment]
No, it has scan (aka preview) the files before cleaning anything. Otherwise it won't know if there are any junk files.

**Comment by vgturtle127** [comment]
@ROCKNROLLKID Ah, I see what you're saying. Sorry, I'm a bit slow today. Ha.

**Comment by az0** [comment]
Would you please try this?

1. Download and install [BleachBit 2.0.683](https://ci.appveyor.com/project/az0/bleachbit/build/2.0.683/artifacts). This is a special build with extra logging. It also has two performance improvements, but it is doubtful they will help this scenario

2. Follow the instructions to [use --debug-log](https://docs.bleachbit.org/doc/troubleshooting.html)

3. Attach the log or email it to me

If this does not reveal the issue, I can add even more logging

**Comment by ROCKNROLLKID** [comment]
[BleachBit Debug.zip](https://github.com/bleachbit/bleachbit/files/1817466/BleachBit.Debug.zip)

Attached is the debug information along with my system information.

**Comment by vgturtle127** [comment]
@az0 I will try that, but I have to wait until I get access to the computer again, it isn't my personal machine.

BleachBit 2.0 stable is out, should I try that instead of the latest commit?

**Comment by vgturtle127** [comment]
@az0 @ROCKNROLLKID Good news, version 2.0 fixes the issue! It cleans the Steam games without issue! Thanks for the help, guys! 😄

**Comment by ROCKNROLLKID** [comment]
Interesting, then your issue must have been different then mine as my issue is still happening with 2.0 stable and any of the development builds.

@az0 Did you get anything from the debug logs I sent you? Would you like to setup another remote service on my system as the issue seems to be easily reproducible?

**Comment by ROCKNROLLKID** [comment]
@vgturtle127 Have you already cleaned out Steam logfiles/cache files/redist files? If so, then usuallyBleachBit runs a lot faster when Steam has already been cleaned, either by BleachBit or another program.

If you did, try running a "verify integrity of game files" options on ALL of your games. This will restore all the redist files back. After that, run all your games at least once. Does this issue happen again?

**Comment by az0** [comment]
@ROCKNROLLKID  The log had little information, so I did not get anything useful. Feel free to open your own ticket, if you do not already have one. If you have one on Launchpad, perhaps you can move it to GitHub. I will consider a better way to debug and get back with you. In your ticket, let me know how many total files are in `%ProgramFiles%\Steam` .

**Comment by vgturtle127** [comment]
@ROCKNROLLKID No, I hadn't cleaned out the Steam files on this machine, and it had more Steam games on it than before, so it was a worse case scenario, really.

And I did verify integrity of all the games before, and the games had been run before.

@az0 We can just re-open this issue, if you want, it is similar enough that I think it would be beneficial.

**Comment by az0** [comment]
@vgturtle127  So you are still having the issue just during the first clean after "verify integrity of game files"? If it is still not working well, reopen the issue.

**Comment by vgturtle127** [comment]
@az0 No, everything on my end is completely fixed. I was just saying that the first run that I did was basically a worst case scenario test. I hadn't run CCleaner, System Ninja, or any other cleaner, all the games had been verified and run more than once, and there were more games on it than before when I was using BleachBit 1.12. Went from like 4 games to like 9.

I was saying we don't necessarily have to open another issue if @ROCKNROLLKID is still having issues, so we can help him in this issue as opposed to adding another issue. Everything works perfect here, though. 😄

**Comment by az0** [comment]
OK, thanks for your flexibility :) He already opened #325 . This should work out fine

**Comment by vgturtle127** [comment]
@az0 Alright, thanks for everything! 😃
