### ISSUE TITLE
Renew code signing certificate for Windows

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#259]

**Comment by ROCKNROLLKID** [comment]
Microsoft has a habit of making this a utterly long and complicated process, even though in my opinion, it's pretty pointless. Because of this, I would suggest you only do this with stable builds and not alpha/beta/daily/nightly builds.

**Comment by az0** [comment]
This is my third time going through the process with the same third-party vendor (not directly Microsoft), and this year it is the longest process by far. I should be almost done, though.

**Comment by az0** [comment]
Fixed
