### ISSUE TITLE
TrendMicro-HouseCall false positive

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#267]
BleachBit-1.19-setup.exe

SHA-256 | cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea

TrendMicro-HouseCall: Suspicious_GEN.F47V1230

https://www.virustotal.com/#/file/cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea/detection

**Comment by az0** [comment]
I submitted the False Detection/Re-Classify Request

**Comment by az0** [comment]
As of today the results improved for the TrendMicro-HouseCall scanner on VirusTotal.com

BleachBit-1.19-setup.zip: clean
BleachBit-1.19-setup.exe: clean
BleachBit-1.17-setup.exe: Suspicious_GEN.F47V1221

Because version 1.17 is obsolete and uses a different certificate, this is sufficient, so I am closing this ticket.

**Comment by az0** [comment]
The false positive is back

>SHA-256 | cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea
>Analysis Date 2018-01-05 02:04:40 UTC
>TrendMicro-HouseCall: Suspicious_GEN.F47V1230

**Comment by az0** [comment]
I submitted a  False Detection/Re-Classify Request for  BleachBit-1.19-portable.zip

**Comment by az0** [comment]
I submitted BleachBit-1.19-setup.exe using a different browser

**Comment by az0** [comment]
I resubmitted the 1.19 executables and got a "success" confirmation on the page

**Comment by az0** [comment]
Issue remains

>BleachBit-1.19-setup.exe
>Analysis timestamp: 2018-02-01 17:46:41 UTC
>TrendMicro-HouseCall Suspicious_GEN.F47V1230

Also for portable
>BleachBit-1.19-portable.zip
>2018-02-01 17:50:25 UTC
>Suspicious_GEN.F47V1230

**Comment by ROCKNROLLKID** [comment]
It is getting increasingly hard for cleaning tools such as BleachBit to keep on AVs good sides. CCleaner had similar issues in the past and I am sure it will happen again.

**Comment by az0** [comment]
Yes, with the number of antivirus tools on VirusTotal, the probability of any one returning a false positive increases. Virus Total (now owned by Google) introduced a program to help software developers with this false positives, but it is expensive. Contacting the antivirus vendors the traditional way is a fair amount of work

**Comment by az0** [comment]
Issue remains

**Comment by az0** [comment]
I submitted it another way, now by email.

**Comment by az0** [comment]
These email addresses bounce back

virus@trendmicro.com
virus_doctor@trendmicro.com
support@support.trendmicro.com

I am trying one more address

**Comment by az0** [comment]
Two days ago from Consumer Support Team

> We submitted your file reclassification request and I am glad to inform you that the file should no longer be detected by the Trend Micro House Call.

However, VirusTotal still reports the false positive. According to VT, they update signatures every 15 minutes

**Comment by az0** [comment]
TrendMicro claims they fixed it on their end and that the issue is with VirusTotal. TM will contact VT.

**Comment by az0** [comment]
The false positive remains in VT, but I will close this ticket here in GH because version 1.19 is obsolete
