### ISSUE TITLE
eGambit false positive

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#269]
SHA-256 | cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea
BleachBit-1.19-setup.exe

eGambit: Unsafe.AI_Score_93%

https://www.virustotal.com/#/file/cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea/detection

**Comment by az0** [comment]
I contacted TEHTRIS

**Comment by az0** [comment]
The results are not yet improved on VirusTotal
BleachBit-1.17-setup.exe: Unsafe.AI_Score_93%
BleachBit-1.19-setup.zip: Unable to process file type
BleachBit-1.19-setup.exe: Unsafe.AI_Score_93%

**Comment by az0** [comment]
I also submitted v1.12

>SHA-256 | ade7c8286daeeb240c2fc216eeb4ed403dffe538bcc5df533decaf19871e1254
>BleachBit-1.12-setup.exe
>Unsafe.AI_Score_72%

**Comment by ROCKNROLLKID** [comment]
This false positive is gone as of today: 
1.12: https://www.virustotal.com/#/file/ade7c8286daeeb240c2fc216eeb4ed403dffe538bcc5df533decaf19871e1254/detection

1.19: https://www.virustotal.com/#/file/3716c8832f7521a448f90c89c5114a50fc66bff650d35673e5120265488b48ca/detection

**Comment by az0** [comment]
Yes, thank you for noticing. I will close this

**Comment by az0** [comment]
> SHA-256 | cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea
> BleachBit-1.19-setup.exe
> 
> eGambit: Unsafe.AI_Score_93%
> 
> https://www.virustotal.com/#/file/cbf6b921d794ddf13da7a6c34ba416d273fdb171a928ff630e31e755dbf1e2ea/detection

A four-month old scan showed the false positive, but a few days ago Tehtris wrote me back about many of my submissions. Now, VirusTotal shows that eGambit no longer detects this one.

**Comment by VoxNiphili** [comment]
https://www.virustotal.com/gui/file/bb69d916e788c6a658e4b75e945efd6960ce4ddef1f5cc0ce6db86efccbe8113/detection
