### ISSUE TITLE
Baidu false positive  for BleachBit-1.12-setup.exe

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#275]
https://www.virustotal.com/#/file/ade7c8286daeeb240c2fc216eeb4ed403dffe538bcc5df533decaf19871e1254/detection

>ade7c8286daeeb240c2fc216eeb4ed403dffe538bcc5df533decaf19871e1254
>Last analysis | 2018-01-04 12:21:20 UTC
>Baidu Win32.Trojan.WisdomEyes.16070401.9

Submitted to vendor

**Comment by az0** [comment]
Still an issue

> Win32.Trojan.WisdomEyes.16070401.9500.9685
>Analysis date | 2018-02-01 17:58:52 UTC

**Comment by ROCKNROLLKID** [comment]
It seems Baidu might be discontinued. It's last updates was in 2015. If it is discontinued, there might not be anyone to fix this. I would say you could probably just ignore it.

**Comment by az0** [comment]
I see http://antivirus.baidu.com/en/ still mentions 2015, but it seems they are still active. Earlier I submitted through a web form, and today I tried an email address

**Comment by az0** [comment]
I cleared the 2.0 milestone because this does not affect the latest 1.19 beta

**Comment by az0** [comment]
I am closing because this is for the old version of BleachBit
