### ISSUE TITLE
Error cleaning Google Chrome version 64

### ISSUE THREAD

**Issue by jugocas** [bleachbit/bleachbit#279]
Got this error

Limpiar archivo 0 C:\Users\pcx1\AppData\Local\Google\Chrome\User Data\Default\History
**Error in execution of <bleachbit.Command.Function instance at 0x05779AD0>**
Eliminar 4B C:\Users\pcx1\AppData\Local\Google\Chrome\User Data\chrome_shutdown_ms.txt

using 1.19 on w.10 as admin

**Comment by az0** [comment]
Good bug report. Thanks. Does this happen with only Google chrome cleaning enabled? Also which version of Google chrome?

**Comment by jugocas** [comment]
Only happend with chrome

Tested with firefox 56.0, opera (50.0.2762.67 (PGO)
 ,ie and chrome (Versión 64.0.3282.119 (Build oficial) (64 bits)

I don't know how fix it, tested some old versions of that with the same report bug. Also tested with clean w10 and only chrome installed.

best regards

**Comment by jugocas** [comment]
I'm still testing some options to get the bug error. Show that error only appear when mark the option called "historial" (history)

**Comment by jugocas** [comment]
Will get new reelease soon?

**Comment by az0** [comment]
I will try to get a new release out soon

**Comment by az0** [comment]
I committed a fix that should help. Would you please soon test [BleachBit build 1.19.646](http://ci.bleachbit.org/?prefix=1.19.646/) (or newer)? Let me know.

**Comment by jugocas** [comment]
I'm glad to help us. This version 1.19.646 is working without any error, thanks so much for your work =) Have a nice day!

**Comment by az0** [comment]
Thank you for quickly testing, Jugocas.
