### ISSUE TITLE
Update Linux release and installation packages on bleachbit.org

### ISSUE THREAD

**Issue by sueridgepipe** [bleachbit/bleachbit#282]
All the install packages for Bleachbit Linux refer to v1.12, which is 18 months old, thus all Linux distros are stuck running 1.12.

https://www.bleachbit.org/download/linux
https://rpmfind.net/linux/rpm2html/search.php?query=bleachbit
https://packages.debian.org/search?keywords=bleachbit
https://launchpad.net/ubuntu/+source/bleachbit
https://packages.gentoo.org/packages/sys-apps/bleachbit
https://slackware.pkgs.org/14.2/slacky-x86_64/bleachbit-1.12-x86_64-1sl.txz.html

Arch User Repository has a bleachbit-git package that allows use of the most up to date development release, but doesn't solve the out of date bleachbit versions used across pretty much the entire Linux ecosystem.

Looks like repository maintainers are using your bleachbit.org downloads page as the definitive bleachbit version.

Possible to update this page to the last stable version of bleachbit, and thus propogate through the Linux ecosystem?

**Comment by az0** [comment]
Yes, I agree this is important and overdue. I am trying to "tie up a few loose ends," and get this out soon.

**Comment by az0** [comment]
By the way, you may have noticed [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta). This is pretty stable, and it will be similar to version 2.0 stable.

**Comment by az0** [comment]
Fixed
https://www.bleachbit.org/news/bleachbit-20
