### ISSUE TITLE
Error cleaning Google Chrome version 64 (Ubuntu 17.10)

### ISSUE THREAD

**Issue by soundchekk** [bleachbit/bleachbit#286]
Hi.

This is a known issue and was supposed to be resolved in 1.19. 
Just installed 1.19 on Ubuntu 17.10
Chrome is: Version 64.0.3282.140 (Official Build) (64-bit)

######

Error in execution of <bleachbit.Command.Function instance at 0x7f2464ad6d88>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 156, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 165, in delete_chrome_favicons
    raise RuntimeError('%s is version %d' % (path, ver))
RuntimeError: /home/klaus/.config/google-chrome/Default/Favicons is version 38

#######

And. Thx for your great tool.

**Comment by az0** [comment]
I confirm with Google Chrome  v64.0.3282.167. 

Thanks for the report. I'll fix this ASAP

**Comment by az0** [comment]
I published a fix.

Please see [bleachbit_1.19_all.deb](https://download.opensuse.org/repositories/home:/andrew_z/xUbuntu_17.10/all/). The version now is dated 22-Feb-2018 21:25.

Please let me know here how it goes.

**Comment by soundchekk** [comment]
Doesn't work.

------------------------------------------------------------------------------------------------------------

Clean file 0 /home/klaus/.config/google-chrome/Default/History
Error in execution of <bleachbit.Command.Function instance at
0x7fe910a5d7a0>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 156, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 165, in
delete_chrome_favicons
    raise RuntimeError('%s is version %d' % (path, ver))
RuntimeError: /home/klaus/.config/google-chrome/Default/Favicons is version
38
Clean file 0 /home/klaus/.config/google-chrome/Default/Preferences

----------------------------------------------------------------------------------------------------------------

bleachbit --version
No protocol specified

BleachBit version 1.19
Copyright (C) 2008-2017 Andrew Ziem.  All rights reserved.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html
>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

---------------------------------------------------------------------------------------------------------------
Chrome
Version 64.0.3282.186 (Official Build) (64-bit)

----------------------------------------------------------------------------------------------------------------

**Comment by az0** [comment]
Thank you. OK,  I saw a problem. I fixed it here: [bleachbit_1.21_all.deb ](https://download.opensuse.org/repositories/home:/andrew_z/xUbuntu_17.10/all/bleachbit_1.21_all.deb), and it works in my testing

**Comment by soundchekk** [comment]
Looks good.

However. Now, with 1.21, at startup a message pops up that a new version
"1.12" would be available

**Comment by az0** [comment]
OK, great. 

I will soon fix the "update is available" as a separate issue. For now, please ignore.
