### ISSUE TITLE
Provide a way to specify which account of Thunderbird you want to clean

### ISSUE THREAD

**Issue by WPFilmmaker** [bleachbit/bleachbit#287]
As version 1.19 if you clean Thunderbird you cannot decide which account to clean, as result Bleachbit cleans everything.

Thunderbird however works with account, like email 1, email 2, feed rss, chat account and so on. Whenever I clean bb on tb I always end up with the deletion of how many days to keep the rss returned to default.

I never understood which option (data or cache) stored such information, but I think it would be handy for the user to let him select on which tb account bb should work.

**Comment by chiwaka** [comment]
It works that way for security and privacy reasons (mainly security reasons).

**Comment by chiwaka** [comment]
Fine with me!!!

**Comment by az0** [comment]
OK, I will close according to your conversation. Thank you :)
