### ISSUE TITLE
Error when cleaning Firefox

### ISSUE THREAD

**Issue by minermark** [bleachbit/bleachbit#288]
Error in execution of <bleachbit.Command.Function instance at 0x034C0D50>

**Comment by az0** [comment]
To look into this, I need more information please. First, which version of BleachBit? Check in the Help menu under About,

Second, please paste the log directly before and after this error message.

**Comment by minermark** [comment]
Today i uninstalled the last verision of BB.
Then installed this new one 1.12
Then i kicked you down a couple bucks for a great cleaner!
Thanx    Mark 


Delete 229.4kB C:\Users\MB\Application Data\Mozilla\Firefox\Profiles\zagvsypo.default\content-prefs.sqlite
Error in execution of <bleachbit.Command.Function instance at 0x021BF558>
Vacuum 0 C:\Users\MB\Application Data\Mozilla\Firefox\Profiles\zagvsypo.default\favicons.sqlite

**Comment by chiwaka** [comment]
Make sure that firefox is not running or running in background and retry.

**Comment by az0** [comment]
The error is with Firefox. Please try [BleachBit version 1.19](https://www.bleachbit.org/news/bleachbit-119-beta) which has fixes for Firefox support that may help. Version 1.19 has been very solid in testing.

I just tested Firefox 58.0.2 on Windows 10 (1709), and it worked without errors.

Thanks for the donation :)

**Comment by az0** [comment]
@minermark  Have you had a chance to test BleachBit version 1.19?

**Comment by minermark** [comment]
BleachBit version 1.19?
I moused / clicked all over every damm page on The BB website.
Click on anything that states 1.19 and or Beta 1.19, i get 1.12 or nothing.
Still have the error here on the Mancave Pc as well as in the house, Win 7, NO FOX running.

**Comment by az0** [comment]
Sorry it is hard to find. Here are the links

BleachBit version 1.19 beta released 12/30/2017
https://www.bleachbit.org/news/bleachbit-119-beta

BleachBit build 1.19.646 released today
http://ci.bleachbit.org/?prefix=1.19.646/

The second is a bit newer with a few more fixes, but it is not digitally signed, so Windows may complain about an "untrusted application." The first link is signed (trusted) and should fix your issue.

**Comment by Tobias-B-Besemer** [comment]
@minermark, do you still have this issue?

**Comment by minermark** [comment]
Seems to have cleared up. was playing around with a VPN and that was when errors pop up.Thanx for the check up. M

    On Sunday, February 17, 2019, 11:34:13 PM PST, Tobias B. Besemer <notifications@github.com> wrote:  
 
 
@minermark, do you still have this issue?
