### ISSUE TITLE
Temporary files on Windows are not cleaned

### ISSUE THREAD

**Issue by chiwaka** [bleachbit/bleachbit#289]
Bleachbit does not delete temp files in %temp% directory.

**Comment by az0** [comment]
1. Which version of BleachBit? In BleachBit click Help and then About.

2. Which version of Windows?

3. Did you check the box System - Temporary Files?

**Comment by chiwaka** [comment]
1. I use BleachBit 1.19 beta
2. Windows 10
3. And yes, I did several times to make sure and it never deleted them.

But it seems it doesn't get *.log *.txt *.tmp files.

**Comment by az0** [comment]
1. Do the files show in the preview?

2. When you do the clean operation, do you get errors? These are marked in red in the log.

**Comment by chiwaka** [comment]
1. No they don't.
2. No, I don't

**Comment by ROCKNROLLKID** [comment]
I just tried the latest development build of 1.19, but I am not seeing this issue. I created 3 test files with random data in them, one .log, one .tmp, and one .txt.

Can you try manually deleting all the files in the temp folder and see if that resolves the issue?

If not, are you sure the files are not being used by a program? BleachBit won't be able to delete them if they are.

If none of the above works, then try uninstalling BleachBit and installing the latest development buld from here: http://ci.bleachbit.org/  See fi the issue still happens.

**Comment by chiwaka** [comment]
Yes, if I do it manually it works of course. But I thought BB would delete them using the Temporary Files option. No big issue. I just didn't know if it was my problem or a BleachBit problem.
This ticket (issue) can be closed.

Thanks for y'alls help!

**Comment by az0** [comment]
All files in `%TEMP%` should show in a preview, even if used by another application. During the clean operation, BleachBit should delete each file, mark it for deleting after a reboot, or throw an error. They should not just disappear.

I tested this also on Windows 10 with the extensions log, tmp, and txt, and it worked. Do you have any clues as to how your system is different?

Do you know how to check whether `%USERPROFILE%\Local Settings\Temp` is the same as `%TEMP%`? If not, I can walk you through it.

**Comment by chiwaka** [comment]
I tried it again. Here is a screenshot

![imagen](https://user-images.githubusercontent.com/33347027/36508666-a614954c-175d-11e8-8a88-a640fceb94a6.png)

**Comment by chiwaka** [comment]
None of the logs on the right appear in bleachbit. This is what I meant and NO they are not being used by another process or application.

**Comment by az0** [comment]
@chiwaka  I committed code to troubleshoot and fix this. Would you please try  [BleachBit build 1.19.640](http://ci.bleachbit.org/?prefix=1.19.640/)?

When you run it, you should see a log like this:
````
Windows temporary directory 1: c:\some dir
Windows temporary directory 2: c:\some other directory
Windows temporary directory 3: c:\another place
````
My guess is on your system the first directory does not exist, but the second directory is what your screenshot is showing. Please check if you can open the first directory by pasting its path into the Run dialog or into the Windows Explorer address bar.

On my system (Windows 10) they have different names, but they point to the same location because of a junction (link).

**Comment by az0** [comment]
P.S. to see the debugging messages, start BleachBit like this
1. Click the Windows Start menu
2. Type "BleachBit debugging"
3. Click on "BleachBit debugging terminal"

Thanks in advance for trying it out

**Comment by chiwaka** [comment]
I tried the 1.19.640 you gave me and it works. It deletes now all files in %temp% file for example and everything in the file.

**Comment by az0** [comment]
Good to hear, Andrew. 

Would you be able to please run the diagnostic test? I am curious why your system is different. This is the procedure

1. Click the Windows Start menu
2. Type **BleachBit debug** to search for the launcher
3. Click on **BleachBit debugging terminal** to launch BleachBit in a special mode with two windows
4. Clean **System - Temporary files**
5. Preview **System - Temporary Files**
6. Look in the second BleachBit window for three lines like `Windows temporary directory 1: c:\users\...`
7. Please let me know the paths for the first two directories

**Comment by chiwaka** [comment]
Sorry, but I windows can't find BleachBit debug. Or do you mean for me to run bleachbit_console.exe command?

**Comment by az0** [comment]
@chiwaka  Yes, actually the shortcut called **BleachBit Debugging Terminal** just points to `bleachbit_console.exe`

If you do not have the shortcut, you could file that as a separate issue ([screenshot of finding the shortcut](https://i.snag.gy/TmId1D.jpg))

**Comment by chiwaka** [comment]
[bb-log.log](https://github.com/bleachbit/bleachbit/files/1749556/bb-log.log)
Is this what you wanted?

**Comment by az0** [comment]
Really close. In this session did you preview or clean **system - temporary files**? I did not see a log entry for that.
