### ISSUE TITLE
remove Windows XP support

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#290]

**Comment by ROCKNROLLKID** [comment]
In this discussion https://github.com/bleachbit/bleachbit/issues/163 we agreed to using Python 3.4 to maintain XP support. We have to think that is also effects ReactOS users, too, so I think it is too early to drop XP support. I say if BleachBit can still run on XP, then leave it alone.

**Comment by az0** [comment]
So an application that requires Windows Vista or Windows 7 will fail on ReactOS?

For example, ReactOS does not run Firefox version 53 or Google Chrome 50?

**Comment by ROCKNROLLKID** [comment]
Some developers are writing NT6 compatibility for ReactOS, but most of it is still very much NT5.1/5.2.

**Comment by chiwaka** [comment]
Why not make a version for each option? Would it not be easier?

**Comment by az0** [comment]
OK, I will try best effort

BTW, I think issue #289 relates to XP support

**Comment by az0** [comment]
@ROCKNROLLKID  Does this change the need for Windows XP support?
>With software specifically leaving NT5 behind, ReactOS is expanding its target to support NT6+ (Vista, Windows 8, Windows 10) software

Source: [OSNews:  ReactOS 0.4.8 released](http://www.osnews.com/story/30268/ReactOS_0_4_8_released)

**Comment by ROCKNROLLKID** [comment]
Yes ReactOS is working on NT6+ support, but I don't see them getting full support for another few years. No one is working on it full time.

If you do plan on dropping XP, then I would recommend at least making a stable version for XP users, so that they can use that for a while.

**Comment by az0** [comment]
BleachBit 2.2 supports Windows XP, but versions versions may not
