### ISSUE TITLE
Zemana anti-malware/logger false positive

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#291]
Zemana anti-malware/logger is detecting BleachBit 1.19 as suspicious. They are not on Virus total, but I have gone ahead and sent them a false positive ticket. Just waiting for response.

**Comment by az0** [comment]
Thank you. I added the false positive label and assigned this to you.

**Comment by az0** [comment]
Just wonder: how did you find it? Do you normally use Zemana?

**Comment by ROCKNROLLKID** [comment]
I have Zemana anti-logger installed.

**Comment by ROCKNROLLKID** [comment]
The false positive is gone for all versions of BleachBit, including the latest development build. I will go ahead and close and reopen if it comes back.
