### ISSUE TITLE
Wrong sha256 for bleachbit_2.0_all_ubuntu1604.deb

### ISSUE THREAD

**Issue by WPFilmmaker** [bleachbit/bleachbit#302]
According to your site the sha256 should be:
53418c12d6da899e145e20cd0ee565e34e1840dbfb74b95e796eb50a4137d084

But verifying it online it gives:
6D62F153B84A7756705BCC4EB916A8F1CB457CEC505BAEB9152F384A68D2228E

When I tried again (with an online check) it gave:
53418C12D6DA899E145E20CD0EE565E34E1840DBFB74B95E796EB50A4137D084

I am puzzled.

**Comment by az0** [comment]
I downloaded bleachbit_2.0_all_ubuntu1604.deb from download.bleachbit.org, and its sha25sum was correct: 53418c12d6da899e145e20cd0ee565e34e1840dbfb74b95e796eb50a4137d084

I calculated it online using the download.bleachbit.org URL, and also got the right result: https://www.online-convert.com/result/ee191a2c-f673-4d79-9a5a-f969b2dd0258

Which online tool did you use? Did you upload the file from your machine, or did you pass it the URL? If by URL, was it the www.bleachbit.org URL or download.bleachbit.org URL?

**Comment by WPFilmmaker** [comment]
I redownloaded it and I got the right checksum,

I used http://onlinemd5.com/ and uplodaded it from my pc after downloading it from: https://www.bleachbit.org/download/file/t?file=bleachbit_2.0_all_ubuntu1604.deb

As I said it seemed weird as I got different checksums...maybe it was just my problem.

**Comment by az0** [comment]
I'm glad you are using the checksums. If this issue happens more reliability, please let me know. Until then I will close the ticket.
