### ISSUE TITLE
[RFE] Support dnf autoremove on Fedora

### ISSUE THREAD

**Issue by AsciiWolf** [bleachbit/bleachbit#306]
Consider adding support for `dnf autoremove` on Fedora just like it is with `apt autoremove` on Ubuntu. GNOME Software/KDE Discover does not uninstall dependencies so this feature could be useful for many users.

**Comment by az0** [comment]
Originally requested by No Name Dot C at https://bugs.launchpad.net/bleachbit/+bug/1615433 . I will close that to move issues to GitHub

**Comment by nonamedotc** [comment]
While adding dnf support, please do not remove yum support. RHEL 7.x still uses yum and we have packages for RHEL as well (on EPEL repo).

Thanks for your work!

**Comment by AsciiWolf** [comment]
Any news about this feature? :-)

**Comment by az0** [comment]
Sorry, no progress so far. Feel free to submit a code change or I will try
to get to it later.

A recent version of BleachBit added s way to run external commands through
CleanerML so maybe it won't be much work

**Comment by az0** [comment]
It seems we lost all Fedora support because they dropped Python 2.x. BleachBit will update to Python 3 soon but not quite yet. Therefore, dnf support will also have to wait.

**Comment by az0** [comment]
There is a pull request to fix this https://github.com/bleachbit/bleachbit/pull/709

Also, I was wrong because BleachBit apparently does work in recent Fedora versions, if it has the right dependencies

**Comment by AsciiWolf** [comment]
Code from the linked PR seems to add support only for cleaning package cache. Not for autoremoving unused dependencies.

**Comment by az0** [comment]
Fixed by 665be5824686b8a6af87e9ce6c78a953c0f12c13

**Comment by az0** [comment]
The RPM and DEB packages are now available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)
