### ISSUE TITLE
Re-enable strip and UPX optimizations for Windows with GTK+ 3

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#316]

**Comment by az0** [comment]
Fixed in 51ddfc2f

commit 469c2e2a
AppVeyor 2.3.1281
BleachBit-2.3-portable.zip (14,057,900 bytes)
BleachBit-2.3-setup-English.exe (10,973,619 bytes)
BleachBit-2.3-setup.exe (11,081,581 bytes)

commit 51ddfc2f  (upx branch)
AppVeyor build 2.3.1282
upx reduced size of the dist directory by 16,875,008 B from 33,939,596 B to 17,064,588 B in 57.9 s
BleachBit-2.3-portable.zip (12,491,213 bytes)
BleachBit-2.3-setup-English.exe (11,560,518 bytes)
BleachBit-2.3-setup.exe (11,665,918 bytes)

**Comment by Tobias-B-Besemer** [comment]
az0, the EXE files got a bit bigger...
Do you know why?

**Comment by az0** [comment]
The EXE installers have better compression than the ZIP portable file. However, applying compression to files that are already compressed can make the archive bigger. (You might see this also when zipping multimedia files such as .jpg.) What's more important is that the contents are smaller, and that's shown here (grabbed directly from the build logs). This is more important because the installer is typically used temporarily and then deleted, while the installation is more permanent.

2.3.1281
Final size of the dist folder: 33,827,044

2.3.1282
Final size of the dist folder: 16,952,200

Therefore, the improvement is significant: 16,874,844 bytes  (49.9%).

**Comment by Tobias-B-Besemer** [comment]
If you want use (Windows) features like "Repair", or "Add/Remove Component" the installer must persist... However, we talk about MBs in times of TB HDDs... so it doesn't really matter IMHO, if later some MBs more or less are used on the HDD...
Anyway, we want to deliver "perfect" (as possible) software, right?
So two other questions to this, too...
Do you pack the headers of the EXEs like bleachbit.exe and bleachbit_console.exe, too?
And I saw there are lots of "Themes" in the BB folder, but BB seems to use just one (on Win7)... Are they for Win10, or are Themes for e.g. Linux and other OSes included, too?

**Comment by az0** [comment]
>Do you pack the headers of the EXEs like bleachbit.exe and bleachbit_console.exe, too?

The command is `upx.exe --best --crp-ms=999999 --nrv2e`

>And I saw there are lots of "Themes" in the BB folder, but BB seems to use just one (on Win7)... Are they for Win10, or are Themes for e.g. Linux and other OSes included, too?

BleachBit for WIndows ships with one icon theme in `share/icons/Adwaita/`
