### ISSUE TITLE
UnicodeDecodeError while running deepscan

### ISSUE THREAD

**Issue by thecsw** [bleachbit/bleachbit#317]
Hello there! 
So I run Arch Linux and have bleachbit installed. I use it for ~2 years now and I was always happy with it. However, lately I have a serious problem with it. It runs into some unicode problem and refuses to do anything else.
```
> $ bleachbit                                                                                                                             [±master ✓]
/usr/share/bleachbit/GUI.py:809: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  self.window = gtk.Window()
/usr/share/bleachbit/GUI.py:809: GtkWarning: Unable to locate theme engine in module_path: "murrine",
  self.window = gtk.Window()
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 254, in run
    for dummy in self.run_deep_scan():
  File "/usr/share/bleachbit/Worker.py", line 313, in run_deep_scan
    for path in ds.scan():
  File "/usr/share/bleachbit/DeepScan.py", line 85, in scan
    for (dirpath, dirnames, filenames) in normalized_walk(top):
  File "/usr/share/bleachbit/DeepScan.py", line 59, in normalized_walk
    for result in os.walk(top, **kwargs):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 35: invalid continuation byte`
```

Thanks.

**Comment by thecsw** [comment]
Also, I can't even find the file maybe with a broken name. I don't think that I have any file with non-UTF8 symbols and else. Thanks! If anything else is needed, please contact me!

**Comment by az0** [comment]
I will check it out. Thanks for the report. In the meanwhile, you may consider disabling the deepscan options.

**Comment by az0** [comment]
I think I found the problem. This will help me confirm.

1.    Open BleachBit
2.    Click on the Help menu
3.    Click on System Information
4.   Click the Copy button to copy the information the clipboard.

Then paste the information in your help request.

Alternatively,  just paste that one line that starts like this 
````
locale.getdefaultlocale = ('en_US', 'UTF-8')
````

Or maybe like this
````
locale.getdefaultlocale = (None, None)
````

**Comment by thecsw** [comment]
Hi, sorry for the delay! Haven't seen the notification. Sure!

```
BleachBit version 2.0
GTK+ version 2.24.32
SQLite version 3.22.0
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/thecsw/.config/bleachbit
personal_cleaners_dir = /home/thecsw/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = thecsw
os.getenv('USER') = thecsw
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/thecsw
platform.linux_distribution() = ('', '', '')
platform.platform = Linux-4.15.12-1-ARCH-x86_64-with-glibc2.2.5
platform.version = #1 SMP PREEMPT Wed Mar 21 15:14:56 UTC 2018
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python2
sys.version = 2.7.14 (default, Jan  5 2018, 10:41:29) 
[GCC 7.2.1 20171224]
__file__ = /usr/share/bleachbit/Diagnostic.pyc
```

**Comment by az0** [comment]
I will look into this. Thanks

**Comment by az0** [comment]
I fixed it. Are you able to test by applying the patch for commit 7f7451ffaf6a0a045509dd228dd30aab4b7f6065? Alternatively you can download the whole DeepScan.py file and overwrite your copy.

If you have further issues, please reopen the ticket.

**Comment by thecsw** [comment]
ooh, thanks!
I will check it out rn!

**Comment by thecsw** [comment]
Hey! I know this is kind of off-topic, I compiled it from source but now I have this strange error:
`ModuleNotFoundError: No module named 'gtk'`
I have gtk2, gtk3 and pygtk installed with pacman and pygtk with pip. Strange. I will check it during evening!
Thanks!

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.

**Comment by DrakeChao** [comment]
It still happens to me on windows

**Comment by az0** [comment]
> It still happens to me on windows. Wasn't this supposed to be fixed a long time ago?

If you see it with BleachBit 6.0.0 (which has a different fix for UnicodeDecodeError) or later version, please open a new ticket.
