### ISSUE TITLE
deep scan does not shred

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#321]

**Comment by mkhon** [comment]
@az0 can you clarify this?

**Comment by az0** [comment]
@mkhon 
Deep scan operations do not obey the preference for shredding files vs. unlinking them. This is the option that can be set in the GUI preferences or via the command line (`--shred`).

**Comment by mkhon** [comment]
@az0 I do not see such option in GUI preferences.
Also, --shred just shreds the files - it does not enable "shred" option.

May be you meant command="shred" option for search="deep"?

**Comment by az0** [comment]
On the command line, I meant `--overwrite`. For the rest of the session, it changes `command="delete"` to `command="shred"` Similarly, enabling overwriting in the preferences does the same thing as long as the option is enabled.

From what I remember, deep scan ignores these options.

When I get a chance, I will look at your PR.

**Comment by mkhon** [comment]
@az0 --overwrite (and corresponding preferences settings) enables 'shred' option which leads to FileUtilities.delete() to do shred even if command="delete" is used.

So this one does not depend on command="delete" support for command="shred"
