### ISSUE TITLE
APT autoremove shows 0 packages to be deleted/deleted

### ISSUE THREAD

**Issue by AsciiWolf** [bleachbit/bleachbit#322]
The previously [broken](https://github.com/bleachbit/bleachbit/issues/168) APT autoremove function is now fixed in BleachBit 2.0, but it now shows 0 deleted packages every time (the packages are correctly deleted, just not shown in the log):

`apt-get autoremove 0`

`Disk space recovered: 0`
`Files deleted: 0`
`Special operations: 1`

OS: Ubuntu 18.04 beta; Czech language.

**Comment by az0** [comment]
I'd like to fix this, but it's cosmetic. There's are urgent issues, such as migrating to Python 3, so I delayed the milestone.
