### ISSUE TITLE
Desktop icon has low resolution on Linux

### ISSUE THREAD

**Issue by AsciiWolf** [bleachbit/bleachbit#323]
Icon used in the BleachBit desktop file has low resolution on Linux.

![bleachbit_icons](https://user-images.githubusercontent.com/2339930/37714551-1367dc18-2d1a-11e8-8660-552d9c5327d3.png)

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Soon the fix will be published also in BleachBit 2.2 final.
