### ISSUE TITLE
bleachbit hangs in the "deep scan" preview. 

### ISSUE THREAD

**Issue by roseswe** [bleachbit/bleachbit#324]
Doesn't react, you only can terminate the program.

bleachbit-2.0-1.1.opensuse422.noarch.rpm
4.4.104-18.44-default #1 SMP Thu Jan 4 08:07:55 UTC 2018 (05a9de6) x86_64 x86_64 x86_64 GNU/Linux

**Comment by az0** [comment]
Please try running deep scan while BleachBit is running in a console, and do you get an UnicodeDecodeError like issue #317 ? If so, could you please send me the `getdefaultlocale` as described there?

**Comment by roseswe** [comment]
Seems to be the same issue like in #317!

0:~ > bleachbit 
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 254, in run
    for dummy in self.run_deep_scan():
  File "/usr/share/bleachbit/Worker.py", line 313, in run_deep_scan
    for path in ds.scan():
  File "/usr/share/bleachbit/DeepScan.py", line 85, in scan
    for (dirpath, dirnames, filenames) in normalized_walk(top):
  File "/usr/share/bleachbit/DeepScan.py", line 59, in normalized_walk
    for result in os.walk(top, **kwargs):
  File "/usr/lib64/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 1-2: invalid continuation byte

locale.getdefaultlocale = ('en_US', 'UTF-8')

**Comment by az0** [comment]
Thanks for checking. I will leave this open in case I have any questions and also to verify the fix works for you.

**Comment by az0** [comment]
I fixed it. Are you able to test by applying the patch for commit 7f7451ffaf6a0a045509dd228dd30aab4b7f6065? Alternatively you can download the whole DeepScan.py file and overwrite your copy.

If you have further issues, please reopen the ticket.

**Comment by plul** [comment]
If the fix works, then it would be nice to see it in a new release.

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.
