### ISSUE TITLE
Preview time is slow when there are many files to compare

### ISSUE THREAD

**Issue by ROCKNROLLKID** [bleachbit/bleachbit#325]
As requested by Andrew, I am moving the old launchpad ticket from here: https://bugs.launchpad.net/bleachbit/+bug/1265963 to here.

Currently, I have 123,661 files in my Steam directory and BleachBit experiences a slow down when trying to clean the Steam directory.

Let me know if you want to do a remote connection again, as it is pretty reproducible now.

**Comment by az0** [comment]
Is **Steam** the slowest steam option? In other words, I mean the option named just **Steam** and not Steam Games, Steam Caches, and so on.

How long does a preview take when only **Steam** is selected?

**Comment by ROCKNROLLKID** [comment]
"Steam" and "Steam Games" goes by relatively quick (maybe around 20-30 seconds each). "Steam Installers" seems to take significantly longer (maybe +2 minutes).

**Comment by ROCKNROLLKID** [comment]
I wonder if the same happens with "Origin Installers" if someone owns a lot of Origin games, as that has a large check just like "Steam Installers" does, but I do not own any Origin games in order to test that.

**Comment by az0** [comment]
I just merged a change from Paweł Polewicz that addresses this, and I measured an 86% improvement in a simulated scenario like this. 

@ROCKNROLLKID I have not heard from you from a while. Thanks for your patience with this one. Would you please test build 2.3.1128 from https://ci.bleachbit.org/ ?
