### ISSUE TITLE
GTK+3 : TypeError: Gtk.Widget.destroy() takes exactly 1 argument (3 given)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#333]
Error seen in console

`TypeError: Gtk.Widget.destroy() takes exactly 1 argument (3 given)`

To reproduce

1. Start application
2. Preview something
3. Close application

Error seen on Ubuntu 16.04 (commit ede855c883126c9b8ec7cf3d5fd5676e0a271498) and Windows 10

**Comment by az0** [comment]
I confirmed this still happens for branch gtk3 as of commit 3a3d923

**Comment by mkhon** [comment]
Also does not happen on Debian buster, will try on Ubuntu 18.04

**Comment by mkhon** [comment]
Can not reproduce on Ubuntu 18.04 as well

**Comment by az0** [comment]
I tested on Ubuntu 18.10, and I do see the error.  I run `python bleachbit.py` without installing BleachBit

For what it's worth, there is no traceback. The error shows in the terminal.

You are on the **gtk3** branch, right?

**Comment by az0** [comment]
This also happens on Windows 10 with GTK 3.24 and Python 2.7. The BleachBit git revision is 0ca3b347

![VirtualBox_Windows 10 OEM GTK 3_21_04_2019_07_59_40](https://user-images.githubusercontent.com/933680/56471469-313f5800-6410-11e9-86a9-bec29013ee2a.png)

**Comment by mkhon** [comment]
Still can not reproduce (Ubuntu 18.04, Windows 10 + gtk 3.18).

1) Do you quit the app using X (window button) or using Quit menu item?

2) Can you specify which cleaners you select on step 2 (Preview something)

**Comment by az0** [comment]
This no longer happens. I tested on Ubuntu 18.10 and Windows 10 as of Git commit d5ab76fd71698d3170e58ed53c3129f86dbd399c

I tried three ways to close: X window button, Quit menu, and keyboard shortcut

**Comment by az0** [comment]
I can reproduce this now

1. Start BleachBit
2. Preview something by right clicking on it entry (not by using the menubar to preview)
3. Close application

Environment:

- Ubuntu 19.04, GTK 3.24.8
- Windows 10, GTK 3.18.9
