### ISSUE TITLE
Release package support

### ISSUE THREAD

**Issue by TerkiKerel** [bleachbit/bleachbit#342]
Hi,

Is there any possibility to create one or more packages for:

snap
nix
appimage
flatpack

Thank you

**Comment by az0** [comment]
For each system, do you know the answers to these questions?

1. Does the user have to have any dependencies installed, such as a package manager?
2. Does it inherently automatically the application?
3. Does it have a sandbox or virtualization that prevents the application from modifying other parts of the system?
4. Can the application still be run with root privileges?

**Comment by TerkiKerel** [comment]
There is no must to support all these package types. But at least if we can one or more, that would be great.

1- Does the user have to have any dependencies installed, such as a package manager?
except AppImage all requires package manager.

2- Does it inherently automatically the application?
I did not understant the question.

3- Does it have a sandbox or virtualization that prevents the application from modifying other parts of the system?
Every app can modify the other parts of system. I have examples of them. But the only thing that can be change is $HOME path which can be fetch by another way. like another environment variable or something...

4- Can the application still be run with root privileges
Nix can run with root privileges. I don't know the others. but for the case of Belachbit can run both root and as regular user. It is not %100 important to run as root. Some people like me, runs it only as regular user (to clean only my user's $Home folder)

**Comment by az0** [comment]
About question 2: is it like a Linux package repository such as Ubuntu's apt repositories?

About question 3: it would be a problem for some users to not modify outside of $HOME

**Comment by TerkiKerel** [comment]
2- Yes there are main repositories which users can directly download it . Or you can add another independed server-url users.

3- No that will not be a problem. If you user will set $HOME before start bleachbit, than bleachbit will use this directory. If they not set it, blenachbit will get the current user home. 

(There are many apps which works inside container. This is not a new thing. If they can, so we can. If you will need test, I'm ready for it.)

**Comment by az0** [comment]
Sorry I don't have time to research all these

**Comment by WPFilmmaker** [comment]
IMHO flatpak seems to be the most popular and once you have a flatpak installer bleachbit can be added to flathub.org

**Comment by az0** [comment]
The problem with pushing BleachBit to a repository such as flathub.org is that automatic updates dries up the revenue that funds the project's development. As a user, I appreciate the convenience, but I also want to continue to  pay for contractors. For example, I am in the middle of a contract that started a week ago.  I would rather not have automatic updates like .rpm and .deb packages, and this is one aspect I haven't had time to research.

Of course this is an open source project, so I am not going to stop someone else from doing this, and many repositories already provide automatic updates (e.g., Chocolatey, Ubuntu, Arch).  I'm not going to shoot myself in the foot, but other people are free to shoot.

**Comment by az0** [comment]
[BleachBit version 6.0.1 beta](https://www.bleachbit.org/news/bleachbit-601-beta) was released with AppImage. When you have a chance, try it out. Thanks for your patience
