### ISSUE TITLE
Add packages for Ubuntu 18.04/18.10 to official site

### ISSUE THREAD

**Issue by TotalCaesar659** [bleachbit/bleachbit#343]
Hello, could you add version for Ubuntu 18.04 to official site (https://www.bleachbit.org/download/linux)? The last one is only 17.10.

**Comment by az0** [comment]
ok

**Comment by az0** [comment]
And Ubuntu 18.10 ! :)

**Comment by az0** [comment]
I released Ubuntu 18.04 and 18.10 here https://www.bleachbit.org/news/bleachbit-21-beta

And they will released with 2.2 beta too

**Comment by Tobias-B-Besemer** [comment]
Any chance to get BleachBit (in future) into the repos of Ubuntu?
https://askubuntu.com/questions/16446/how-to-get-my-software-into-ubuntu/16456#16456

Should we fill a new wish-issue for it?

**Comment by az0** [comment]
For many years BleachBit has been in the Debian and Ubuntu repositories. Example: https://packages.ubuntu.com/search?keywords=bleachbit

The only issue is they are often behind with an old release, but that's their policy

**Comment by Tobias-B-Besemer** [comment]
https://bugs.launchpad.net/ubuntu/+source/bleachbit

You monitor this page?

**Comment by Tobias-B-Besemer** [comment]
https://launchpad.net/ubuntu/+source/bleachbit

Maybe you should ask to maintain th package self?

**Comment by az0** [comment]
No
