### ISSUE TITLE
Password screen (for root) in Bleachbit does not appear in Ubuntu Budgie 18.04

### ISSUE THREAD

**Issue by Der-Bauer** [bleachbit/bleachbit#346]
Ubuntu Budgie 18.04 minimal install 

Hey I have one  problems, i installed Bleachbit version 2.02 from the official repository in Ubuntu 18.04 
 and if i want to start bleachbit (root) i expected to enter my password but nothing happen.If i got to the terminal and run sudo bleachbit it works.(sorry for my english).

**Comment by oserdavid** [comment]
Problem seems to be with Budgie's menu and Plank. There is no problem with Bionic when using Ubuntu or Gnome desktops with 'Dash to Dock' as alternatives to my default Budgie login. Just to be sure that makes sense I should add that I have installed these alternative desktop logins in Budgie-Ubuntu. Otherwise I find the Budgie desktop by far the best of the three

**Comment by Der-Bauer** [comment]
With docky it does not work either no login prompt in

bleachbit as root 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.05.18, 19:29, oserdavid <notifications@github.com> schrieb:
Problem seems to be with Budgie's menu and Plank. There is no problem with Bionic when using Ubuntu or Gnome desktops with 'Dash to Dock' as alternatives to my default Budgie login. Just to be sure that makes sense I should add that I have installed these alternative desktop logins in Budgie-Ubuntu. Otherwise I find the Budgie desktop by far the best of the three

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-391432713","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-391432713","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bleachbit/bleachbit","title":"bleachbit/bleachbit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bleachbit/bleachbit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@oserdavid in #346: Problem seems to be with Budgie's menu and Plank. There is no problem with Bionic when using Ubuntu or Gnome desktops with 'Dash to Dock' as alternatives to my default Budgie login. Just to be sure that makes sense I should add that I have installed these alternative desktop logins in Budgie-Ubuntu. Otherwise I find the Budgie desktop by far the best of the three"}],"action":{"name":"View Issue","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-391432713"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [bleachbit/bleachbit] Password screen (for root) in Bleachbit does not appear in Ubuntu Budgie 18.04 (#346)",
"sections": [
{
"text": "",
"activityTitle": "**oserdavid**",
"activityImage": "https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png",
"activitySubtitle": "@oserdavid",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/bleachbit/bleachbit/issues/346#issuecomment-391432713"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 333880029\n}"
}
],
"themeColor": "26292E"
}

**Comment by WPFilmmaker** [comment]
@az0 Don't know if it matters but this issue is not present when running BB on Lubuntu 18.04, installed with the 17.10 deb. However I noticed that there is no BB icon..:  http://www.upl.co/uploads/scree1528127014.png (should I open a new ticket?)

**Comment by queeup** [comment]
Same problem on 16.04 package too. I am using ElementaryOS. I change execute line as follows and It works.
```Exec=sh -c "pkexec bleachbit"```

**Comment by Der-Bauer** [comment]
Where do you change the execute line and how 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.06.18, 15:56, queeup <notifications@github.com> schrieb:
Same problem on 16.04 package too. I am using ElementaryOS. I change execute line as follows and It works.
Exec=sh -c "pkexec bleachbit"

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397304777","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397304777","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bleachbit/bleachbit","title":"bleachbit/bleachbit","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bleachbit/bleachbit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@queeup in #346: Same problem on 16.04 package too. I am using ElementaryOS. I change execute line as follows and It works.\r\n```Exec=sh -c \"pkexec bleachbit\"```"}],"action":{"name":"View Issue","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397304777"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [bleachbit/bleachbit] Password screen (for root) in Bleachbit does not appear in Ubuntu Budgie 18.04 (#346)",
"sections": [
{
"text": "",
"activityTitle": "**queeup**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@queeup",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397304777"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 333880029\n}"
}
],
"themeColor": "26292E"
}

**Comment by queeup** [comment]
```
/usr/share/applications/bleachbit-root.desktop
```

**Comment by Der-Bauer** [comment]
Thank you it works finally
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 15.06.18, 07:39, queeup <notifications@github.com> schrieb:
/usr/share/applications/bleachbit-root.desktop


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397518929","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397518929","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bleachbit/bleachbit","title":"bleachbit/bleachbit","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bleachbit/bleachbit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@queeup in #346: ```\r\n/usr/share/applications/bleachbit-root.desktop\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397518929"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [bleachbit/bleachbit] Password screen (for root) in Bleachbit does not appear in Ubuntu Budgie 18.04 (#346)",
"sections": [
{
"text": "",
"activityTitle": "**queeup**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@queeup",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"bleachbit/bleachbit\",\n\"issueId\": 346\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/bleachbit/bleachbit/issues/346#issuecomment-397518929"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 333880029\n}"
}
],
"themeColor": "26292E"
}

**Comment by az0** [comment]
I am closing because the last comment was that "it works"

**Comment by queeup** [comment]
> Same problem on 16.04 package too. I am using ElementaryOS. I change execute line as follows and It works.
> `Exec=sh -c "pkexec bleachbit"`

Still need this modification to work.

Just Installed bleachbit_2.2_all_ubuntu1804.deb to elementary OS .0.5 and It's not working!
