### ISSUE TITLE
PGP fingerprint

### ISSUE THREAD

**Issue by ofereitan** [bleachbit/bleachbit#350]
Could you publish your pgp key fingerprint so we could verify the validity of the key (because the key is delivered over plain http, its vulnerable to mitm attack), preferably on a platform such as keybase that links the key to multiple identities (your github account,social media, bleachbit.org website, etc...).

Thx,
Ofer

**Comment by az0** [comment]
Keybase is a good idea, so here it is: https://keybase.io/andrewziem

By the way, it was already here http://bleachbit.sourceforge.net/bleachbit_public.key

**Comment by ofereitan** [comment]
Looks great!
Thx
