### ISSUE TITLE
BB20 - Chrome cookies and site data not bleached properly

### ISSUE THREAD

**Issue by soundchekk** [bleachbit/bleachbit#351]
Ubuntu 18.10  - Chrome  Version 67.0.3396.87 - BB20

I just noticed that BB won't delete "All cookies and site data" properly.
All Chrome options were selected and a bleach executed and I still ran into site restriction issues.

And just to mention it - Chrome was down during the beach!

Inside that Chrome menu it became obvious that the list "All cookies and site data" wasn't cleaned up (properly) by BB.

After manually removing "All cookies and site data"  from inside Chrome my issues were gone.

**Comment by soundchekk** [comment]
It's me again.

I just installed bleachbit from latest git sources.
I can't reproduce the issue anymore. Probably the Ubuntu .deb wasn't really  up2date.

Perhaps it's time to release 2.1.

The issue can be closed.

**Comment by az0** [comment]
The Git version has many changes to improve Google Chrome since BleachBit 2.0. Yes, I agree that soon I should release a new version. Thanks for checking Git and for letting me know.
