### ISSUE TITLE
Bleach Bit 2.0 64bit on windows 8.1 doesn't delete History file in Chrome

### ISSUE THREAD

**Issue by 6has6ceh** [bleachbit/bleachbit#352]
I've tested this several time, but BB is not deleting C:\Users\profilename\AppData\Local\Google\Chrome\User Data\Profile 1\History file.  It wouldn't delete it also when I added the above path to Custom locations in preferences.

**Comment by az0** [comment]
BleachBit version 2.0 cleans only the Default profile for Google Chrome. The history file specifically is `%localappdata%\Google\Chrome\User Data\Default\History`

If you add the file to the custom location in the preferences, it will be cleaned by selecting the option **Custom** under the section **System**. (In other words, the section for Google Chrome does not clean the custom options in the preferences menu.)  Please let me know whether this helps.

**Comment by 6has6ceh** [comment]
If you look at my question, you'll see that I said I put it in the custom locations in the preferences.  It still doesn't erase it or touch it.  Is there a specific way you have to use the custom area?  I added the custom path as shown above, but it doesn't even try to delete it.

**Comment by az0** [comment]
Yes, I understand you put it under the custom location in the preferences. Yes, there is a way you have to use the custom area. Check the checkbox called **Custom** under the section **System**. Please try this and let me know how it goes.

**Comment by 6has6ceh** [comment]
Thank you for the patience, that did the job.

**Comment by 6has6ceh** [comment]
Thanks for the patience, that did the job.
