### ISSUE TITLE
Portable deployment: Inconsistency for search/find and execute cleanup 

### ISSUE THREAD

**Issue by RaiKoHoff** [bleachbit/bleachbit#354]
Using a portable installation and a custom `Cleaner`:
```
<cleaner id="my_portableapps" os="windows">
  <label>_My_PortableApps</label>
  <description>Cleanup my PortableApps directory</description>
  <option id="lng">
    <label>Language Files</label>
    <description>Delete all not needed Language Files</description>
    <action command="delete" search="walk.files" path="..\CDExPortable\App\CDex\lang" regex="(?!deutsch\b|english\b)\b.+\.cdex\.lang$"/>
  </option>
</cleaner>
```
The search path and regex filter work fine on selecting files to be removed,
but the preview/execution of cleanup does not accept the relative path:

![image](https://user-images.githubusercontent.com/8806350/41771066-38cd31d6-7614-11e8-895c-15725a427599.png)
.
[log.zip](https://github.com/bleachbit/bleachbit/files/2127293/log.zip)

**Comment by az0** [comment]
I added an environment variable `%cd%` environment variable that has the current directory. In about ten minutes, you can download 2.0.725 from https://ci.bleachbit.org/ . Try it and let me know how it works

**Comment by RaiKoHoff** [comment]
Works like a charm. Thank you for this solution.
