### ISSUE TITLE
BleachBit cannot remember checked preferences

### ISSUE THREAD

**Issue by valex777** [bleachbit/bleachbit#356]
Have used BB for some time (several versions) and now using version 2.0 on windows 10.

BB has never been able to 'remember' the preferences checked in the drop-down, specifically, in my case, the preference to "Exit After Cleaning".
It may, successfully, close a few times when deleting several, individually selected files, but, in general, if I'm removing batches of 15 at a time (another issue, altogether), I'll have to reset the preferences at least once per batch.

Also, why is the limit of individually selected files only 15?

**Comment by az0** [comment]
Do you mean BleachBit closes itself before deleting all the files it should when there are many files to delete?

**Comment by az0** [comment]
Closing because no response since June
