### ISSUE TITLE
iTunes entries in winapp2.ini not working

### ISSUE THREAD

**Issue by sshermz** [bleachbit/bleachbit#358]
bleachbit 2.0 on windows 7 (installed as administrator).

Cleaning generally is working as expected.

The issue is that I have the latest iTunes 12.7.5.9 installed, and the iTunes cleaning entries are present in the official, auto-downloaded winapp2.ini. However, even after restarting the latest v2.0 bleachbit.exe app, those entries do not appear in the left pane of the UI as expected.

I confirmed that the latest winapp2.ini is being downloaded to C:\Users\<username>\AppData\Roaming\BleachBit\Cleaners\, and that the iTunes cleaning entries are present in the downloaded file in this location.

I tried unchecking "Hide irrelevant cleaners", restarted, but the iTunes entries still don't appear in the UI. 

Despite the entries not appearing in the UI, I tried running Preview and then Clean anyway. But the iTunes files, per winapp2.ini, were not deleted by BB.

**Comment by Tobias-B-Besemer** [comment]
WinApp2.ini can only clean iTunes on Win10.

**Comment by sshermz** [comment]
Thanks Tobias, but why is that? Bleachbit is supported on W7 per the download page. It's totally useless if it doesn't work with winapp2.ini.

**Comment by Tobias-B-Besemer** [comment]
It works with WinApp2.ini! WinApp2.ini is a separate project (https://github.com/MoscaDotTo/Winapp2) and this special rule you ask for (iTunes) is only written for Win10...

...but I will write you a rule set for iTunes in CleanerML, the markup language of BleachBit! Just give me some time...

**Comment by Tobias-B-Besemer** [comment]
OK, sorry, I was wrong! WinApp2.ini have two rule sets for iTunes... One is called "iTunes" and also for older OSes, the other is called "Apple iTunes" and is only for Win10...

...anyway: I write you a solution in CleanerML... ;-)

**Comment by Tobias-B-Besemer** [comment]
OK, you can try this cleaner:
https://raw.githubusercontent.com/az0/cleanerml/091eabd622666e137ab7bf9514f68f125fc6567b/pending/itunes.xml
Works on my PC with Win7...
Please give a feedback how it works! Thank you!

**Comment by sshermz** [comment]
I see now. Thanks for explaining the difference between WinApp2.ini and CleanerML.

Thank you so much! It works!

I think you just need to add a rule for "%AppData%\Apple Computer\iTunes\iPhone Updater Logs".

**Comment by Tobias-B-Besemer** [comment]
That's great to hear! :-)

Here is a new version that includes your suggestion... ;-)
https://raw.githubusercontent.com/az0/cleanerml/130bcaa6b20261b0e5202a28e5c4b3f4737822de/pending/itunes.xml

If you find more, we can/should clean, let me know! :-)

**Comment by sshermz** [comment]
Great! Thanks again Tobias.

**Comment by Tobias-B-Besemer** [comment]
No prob! You're welcome! :-)
