### ISSUE TITLE
Bleachbit cleans only the default profile in Firefox

### ISSUE THREAD

**Issue by bryce-lynch** [bleachbit/bleachbit#359]
I'm running the latest Firefox on Linux and have 2 profiles listed in profiles.ini. Only the first one is cleaned by Bleachbit (on my machine, at least).

I saw an old report [here](https://www.bleachbit.org/forum/bleachbit-finds-only-default-profile-firefox) and was wondering if the bug has been fixed at some point?

**Comment by az0** [comment]
Short answer, no, this feature is not ready.

Longer answer is a few months ago I made a significant improvement that will serve as a foundation for this feature.

**Comment by az0** [comment]
@bryce-lynch 

Are both your profiles in the directory `~/.mozilla/firefox/`?

**Comment by bryce-lynch** [comment]
@az0 yes.

**Comment by az0** [comment]
There was a fix for this, so would you please try the latest version from Git? It's rather easy to [run from Git or source](https://docs.bleachbit.org/dev/running-from-source-code.html) without installation

**Comment by bryce-lynch** [comment]
Just cloned the latest version, it successfully detected and cleaned both profiles and seems to work fine. Thank you! (You can close the issue if you don't have any questions.)

**Comment by az0** [comment]
FYI

The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). 
Soon the fix will be published also in BleachBit 2.2 final.
