### ISSUE TITLE
Linux: 'bleachbit as root' does not work on Mint 19

### ISSUE THREAD

**Issue by CottonEaster** [bleachbit/bleachbit#362]
'bleachbit as root' does not work on Linux Mint 19, i.e. that menu command does not work. In a terminal, though, `pkexec bleachbit` does work.

Mint 19 Cinnamon.2.0
Bleachbit

**Comment by RonCam** [comment]
@CottonEaster:
Is this a version 2.0 problem that you didn't have with version 1.1?  If yes, then [check this link for a possible solution.](https://github.com/bleachbit/bleachbit/issues/377)

**Comment by CottonEaster** [comment]
Running bleachbit as root, from a menu, now works - without, it seems, my having to do anything. Perhaps some Mint (or polkit) update fixed things. The working menu command is: pkexec bleachbit.
