### ISSUE TITLE
Thunderbird columns reset

### ISSUE THREAD

**Issue by Gittyperson** [bleachbit/bleachbit#363]
One of the selected options below resets the user set column configuration (on/off, position, sorting). Can you please tell me which one and consider adding a warning for this?

Thanks for the excellent BleachBit.

BB 2.0 portable, W10 x64, winapp2.ini enabled

![thunderbird selections](https://user-images.githubusercontent.com/7165208/43249038-4c3ac102-90c2-11e8-9b2b-f6428e0fadec.png)

**Comment by az0** [comment]
@Gittyperson  Are you able to please test each one individually?  Then I will add a warning

**Comment by Gittyperson** [comment]
Ok, I tested all of the above options (except Passwords). It's "Index" that causes this. "Email Index" does not reset the columns.

**Comment by evitalis** [comment]
I had this same issue and would like to see a warning if possible on the option.

**Comment by az0** [comment]
Thank you all for your patience.

>  It's "Index" that causes this

@Gittyperson  Thank you for testing. OK, let's add a warning for this soon.

**Comment by az0** [comment]
Thank you all for your patience. You can test this as build 4.3.0.1876 or newer from the [CI Build](url) site. (Please allow a few minutes for it to upload there.) The fix will also be in the next beta and final releases. If you have a chance to test it, let me know how it goes.
