### ISSUE TITLE
CLI: Enable all options that do not present a warning

### ISSUE THREAD

**Issue by zero77** [bleachbit/bleachbit#365]
Can you add a command line option to clean all entries without errors.
Thanks

**Comment by az0** [comment]
Do you mean "without printing the error messages" or "in case of error while processing an option, then skip the option"?

**Comment by zero77** [comment]
@az0 
"in case of error while processing an option, then skip the option"?

yes, essentially just skip any entries that have errors.

**Comment by Tobias-B-Besemer** [comment]
Just for my curiosity: Can someone attach a screenshot of such an error?

**Comment by zero77** [comment]
@Tobias-B-Besemer 
![error](https://user-images.githubusercontent.com/16563034/54869973-2bfed700-4d98-11e9-8b89-df70b6f5fdad.jpg)

**Comment by Tobias-B-Besemer** [comment]
@zero77, thank you very much! I understand now! It's not an error, it's called "warning"...

**Comment by Tobias-B-Besemer** [comment]
Also: I don't think you want the option skipped - I think you want the warning skipped, right?

**Comment by zero77** [comment]
@Tobias-B-Besemer 
> thank you very much! I understand now! It's not an error, it's called "warning"...

Yes, i just realized this after i posted the image above.

> Also: I don't think you want the option skipped - I think you want the warning skipped, right?

Yes, that would be a more accurate way of putting it.

**Comment by Tobias-B-Besemer** [comment]
@zero77, how many warnings do you get at the moment?

You want to run all cleaners with all options, but get no warnings, right?

You know, that e.g. the Deep Scan takes long?
You know, that when you don't run the Deep Scan every time, BleachBit will finish much faster?
You know, that the Deep Scan will bring you normally no new results, when you run it?

**Comment by Tobias-B-Besemer** [comment]
@zero77, just for my better understanding:
You use BB on Linux, right?
Do you run BB with GUI, or from Command Line?
Have you already tried to run BB from CL?

**Comment by Tobias-B-Besemer** [comment]
@zero77, or let me ask this way:
Do you want to run BB with CL, or with GUI?

Also: Can you tell me whats your native language is?
Do you use BB in you native language?
Is the translation to your native language OK/good?

And: BB v2.2 was released those days...
Have you already downloaded & installed it?
Is the translation good/better?

**Comment by zero77** [comment]
@Tobias-B-Besemer 
Right now i use BB in English with gui but i want to move to cli.

I run BB in gui because, i can check all options and cancel all the options that have a warning and just use the entries that are left but, i want to do this in cli instead.
I hope that makes sense as i am not sure how well i explained this before.

**Comment by Tobias-B-Besemer** [comment]
To be true: I'm not new to BB, but to CLI, too. ^^

But I had a look on the CLI... started it with "--help"... and...
1.) I guess you never get a warning on CLI;
2.) You can run it with "-c --preset"... ;-)

Did you knew that?

**Comment by Tobias-B-Besemer** [comment]
Btw.: Maybe you should switch the language of BB to your language that the warnings make sense and help you... ??? With which warnings do you have to handle on your system beside the Deep Cleaner ???

**Comment by Tobias-B-Besemer** [comment]
And ones again to the Deep Scan: You can run them e.g. every 6 months, or ones a year, but don't have to do it every week...

**Comment by Tobias-B-Besemer** [comment]
@alvis05, do you have the same issue, or something else?

**Comment by Tobias-B-Besemer** [comment]
OK, I think from every issue can be something learned... And maybe we should learn to improve the description of the Deep Scanner... So I filled issue #511...

**Comment by zero77** [comment]
@Tobias-B-Besemer 
> OK, I think from every issue can be something learned... And maybe we should learn to improve the description of the Deep Scanner... So I filled issue #511 

I think this would definitely be of help but, it doesn't fully resolve the issue.

> And ones again to the Deep Scan: You can run them e.g. every 6 months, or ones a year, but don't have to do it every week...

This is one of the reasons why i want to skip all entries with warnings and just use the ones without.

I generally go through the entries with warnings manually from gui every so often but, definitely not automated via the cli.

> 2.) You can run it with "-c --preset"... ;-)

I didn't see that last time i checked the cli, is there any way to do a dry run to see what's going to be cleaned before actually cleaning.

**Comment by Tobias-B-Besemer** [comment]
`--help`

&

`--preview`

**Comment by zero77** [comment]
@Tobias-B-Besemer 
In an indirect way i think this may achieve what i am looking for.
Thanks for the help.

Although, the `--preview` option is a bit messy and difficult to read, and i think #511 would definitely be worth implementing.

**Comment by Tobias-B-Besemer** [comment]
No prob! You're welcome!

**Comment by az0** [comment]
I renamed to the issue to "Enable all options that do not present a warning." If this doesn't capture the intention, let me know.

**Comment by zero77** [comment]
@az0 
Yes, i think that covers it but, perhaps CLI should be mentioned.

**Comment by az0** [comment]
@zero77 
Thank you for the suggestion. I added the new CLI option `--all-but-warning` to do this. You can get it now by [running from source](https://docs.bleachbit.org/dev/running-from-source-code.html) (relatively easy on Linux), getting a Windows binary from the [CI build site](https://ci.bleachbit.org/), or waiting for the beta release. 

Try it out, and let me know how it goes.
