### ISSUE TITLE
Please indicate that the program will be cleaning registry keys.

### ISSUE THREAD

**Issue by shimizurei** [bleachbit/bleachbit#367]
I just downloaded Ver 2.0 and I used it to clean my Win 7x64 system. I didn't realize it would clean up registry keys. I looked for an option to turn off that feature and I couldn't find it. I don't want anything touching my registry. Please add an option for registry stuff.

**Comment by az0** [comment]
BleachBit does not have a what many people call a "registry cleaner" that "optimizes your computer" or "fixes error." Instead, a typical use in BleachBit is to delete Most Recently Used lists (in other words, history), which are often stored in the Windows registry.

The preview function shows the registry keys that will be cleaned. The log entry starts clearly with "Delete registry key," and it gives the exact name of the key.

For an example, preview **Windows Explorer - Most Recently Used**.
