### ISSUE TITLE
parsing error in section Windows ShellBags *

### ISSUE THREAD

**Issue by Symbai** [bleachbit/bleachbit#369]
Used Bleachbit for the first time on Windows 10 and it crashed on exit. Log file:

```
parsing error in section Windows ShellBags *
Traceback (most recent call last):
  File "bleachbit\Winapp.pyo", line 151, in __init__
  File "bleachbit\Winapp.pyo", line 268, in handle_section
  File "bleachbit\Winapp.pyo", line 191, in excludekey_to_nwholeregex
NotImplementedError: REG not supported in ExcludeKey
```

**Comment by az0** [comment]
@Symbai 
Where did you get this this Winapp2.ini file? Did you get it by checking the box *Download and update cleaners from community (winapp2.ini)* or did you install the Winapp2.ini file yourself?

**Comment by Symbai** [comment]
No, the documentation says it supports Winapp from CCleaner so I took my existing winapp from CCleaner which I mostly got from https://github.com/MoscaDotTo/Winapp2/

**Comment by az0** [comment]
The support in BleachBit version 2.0 for the popular community Winapp2.ini is roughly 99.9%, but here are some unsupported entries: https://github.com/bleachbit/winapp2.ini/commit/d066caae39ff1a71abde7f5f4a676aed09186f35

My process is to grab the "upstream" community file, remove a few unsupported entries, remove some parts that do nothing, run some checks, and then publish this version to BleachBit users.
