### ISSUE TITLE
Updates to run on OpenBSD?

### ISSUE THREAD

**Issue by evitalis** [bleachbit/bleachbit#371]
Looks like the `__init__.py` is missing a directive, though one exists for NetBSD. I did PR #370  to help this.

In `FileUtilities.py` there are explicit checks for Linux or Mac systems. Will either of these be viable for OpenBSD?

I do not mind testing possible resolutions to this.

**Comment by evitalis** [comment]
Reopening this as it is not solved. There is still an issue with the `FileUtilities.py` module. 

The application hits an error when the scan is done. It looks like it is due to being able to check for running applications, but I am not 100%.

**Comment by az0** [comment]
I reopened this and assigned it to you. Is that OK?

What exactly is the error? Is there a traceback?

**Comment by evitalis** [comment]
I have been looking into this. There is traceback and it is simply an error saying unsupported OS.

The issue is with scanning for open file handles. On OpenBSD the `/proc` filesystem does not exist and `lsof` is deprecated. After some research I found both of these methods are not ideal to test for open files anyway. The files may not be opened at the second the report is checked, but can be immediately after. This makes both methods inaccurate, and renders them unusable with OpenBSD.

The application still seems to run but does result in errors.

https://github.com/bleachbit/bleachbit/blob/master/bleachbit/FileUtilities.py#L77

You may consider printing the error or a warning here, but this should have a try/except block to prevent the application from crashing.

**Comment by evitalis** [comment]
@az0 Any thoughts on my last post? I don't mind simply setting a `pass` if OpenBSD is detected but that may not be the right solution. Given the information provided though it seems as though this issue could affect any OS if the state of a file pending deletion is changed after analysis.

**Comment by evitalis** [comment]
Sorry it has been awhile on this. I still find that cleaning ends up being broken due to the lack of method for finding open files on OpenBSD. My suggestion would be to specifically exclude this action. @luoliyan any thoughts on this?

**Comment by az0** [comment]
I believe currently this is needed only for cleaning system.tmp. Is this where you see "being broken"?

I suggest a warning on OpenBSD.

**Comment by evitalis** [comment]
@az0 You are correct, sorry for leaving that out. On OpenBSD /tmp is cleaned automatically at each reboot. It is possible to clear files before then but there is no way to tell if they are open or not so applications may run into errors. I will need to test this further.

Is it possible to simply disable that cleaner on OpenBSD out of the box?

**Comment by evitalis** [comment]
@az0 I have not used OpenBSD in awhile, it may make sense to remove me as the assignee of this issue. Anyone else is welcome to pick it up but I don't even run the OS anymore to test with.
