### ISSUE TITLE
I got bleachbit error "_socket.pyd" at install

### ISSUE THREAD

**Issue by charlesfinney** [bleachbit/bleachbit#374]
I uninstalled Beachbit in order to install version 2. But as soon as I tried to open the set up exe, I got bleachbit error "_socket.pyd" https://snag.gy/DBNydp.jpg

**Comment by az0** [comment]
Did the uninstall succeed without errors?

Are you using Windows 10?

This looks like a permissions issue. My first suggestion is to make sure that you are installing with administrator privileges. You might have to right-click on the BleachBit installer exe and choose an option "run as administrator" from the popup menu. Try this and let me know how it goes either way.

**Comment by az0** [comment]
The general advice for reporting bugs is in [CONTRIBUTING.md](https://github.com/bleachbit/bleachbit/blob/master/CONTRIBUTING.md), but just like reporting an issue with the right level of detail can be tricky, so can be writing a guide. :) The screenshot was helpful.  Either way,  no worries. 

Your "first issue" means you had an older version of BleachBit (older than 2.0) that installed fine?

Two things to try

First, reboot Windows and try installation again. Maybe something locked the files.

Second, which security/antivirus software do you use? If you can find out how, try to temporarily disable it. This feature may be called "game mode," and it may help the installation. Before you do this, make sure you downloaded the BleachBit installer from www.bleachbit.org, and Windows should tell you that it is digitally signed with my name such as in this [example screenshot](https://docs.bleachbit.org/doc/install-on-windows.html). After installation, turn the security software back on.

**Comment by az0** [comment]
Closing for no response. If this is still a problem, feel free to reopen with more information
