### ISSUE TITLE
Installing v2.0 overwrites Menu entry for running as Root (GNU/Linux) which may cause problems in some systems

### ISSUE THREAD

**Issue by RonCam** [bleachbit/bleachbit#377]
Running Bleachbit as root (from the Menu selection with 'Administrator' in it) stopped working after upgrading to the most recent version 2.0.

Running _MenuLibre_ to examine the entry for running Bleachbit as root showed that version 2.0's installation had overwritten the previously-working menu command, with one that wouldn't work, at least, on my system.

Specifically, `su-to-root -X -c bleachbit` had been overwritten with `pkexec bleachbit`.

My fix, on my system (older version of Bodhi Linux based on Trusty, with Enlightenment 17 environment) was to find the file running that Menu entry, and edit its Properties to replace the new (non-working) command with the original one.

Now, selecting Bleachbit as Root (Administrator) starts the program as perfectly in version 2.0 as it had, before the upgrade.

The new run-as-root command may be working on some systems so it's likely only a Bug for some people, but not for others?  However, in my pre-posting search to see if others had encountered a problem with the new command, [it seems to be affecting a user who is running a distro based upon the most recent Ubuntu version.  ](https://github.com/bleachbit/bleachbit/issues/362)

**Comment by az0** [comment]
Ubuntu supports Trusty 14.04 through April 2019, so not that much longer. :)

Did you get the BleachBit .deb package from this site or from elsewhere?

**Comment by RonCam** [comment]
Hi @az0,
Yes, downloaded from this site and the checksum verified as OK.

But, on my desktop system,  _the new command to start bleachbit  as root works perfectly._

The desktop is running Linux Mint 17.3, _also_ based on Ubuntu Trusty.  I have no idea why there should be a difference.  

@CottonEaster (linked post) reports _pkexec_ has spontaneously started to work normally on his system, and guesses that _Mint_ may have received a patch that fixed it.  Perhaps _Bodhi_ did not?

Off topic: thanks so much for _bleachbit_ and its ability to 'vacuum' SQLite databases. It helps keep Firefox running smoothly!  I looked into how to do this manually, and using your program makes it much easier.
