### ISSUE TITLE
Bleachbit fails to run since microsoft 10 update 

### ISSUE THREAD

**Issue by zoonytoons** [bleachbit/bleachbit#378]
Traceback (most recent call last):
  File "bleachbit.py", line 45, in <module>
  File "bleachbit\GUI.pyo", line 902, in __init__
  File "bleachbit\GUI.pyo", line 832, in create_window
  File "bleachbit\GUI.pyo", line 482, in create_operations_box
  File "bleachbit\GUI.pyo", line 71, in __init__
  File "bleachbit\GUI.pyo", line 101, in refresh_rows
  File "bleachbit\Options.pyo", line 126, in get
  File "ConfigParser.pyo", line 370, in getboolean
ValueError: Not a boolean: ['True']

I have a 64bit pc with a program files 86. bleachbit tries to put the 86 version in rather than the 64bit one

thanks

**Comment by az0** [comment]
BleachBit 2.0 is a 32-bit application, so it would normally be in the x86 Program Files folder instead of the 64 Program Files folder. Please try this

1. Open File Explorer (also called Windows Explorer)
2. Navigate to %APPDATA%\BleachBit
3. Delete or rename bleachbit.ini (because it seems to be corrupt)
4. Start BleachBit

**Comment by az0** [comment]
I have not heard back in ~10 months, so I am closing the ticket. 

This seems like these issues
https://github.com/bleachbit/bleachbit/issues/562
https://github.com/bleachbit/bleachbit/issues/560

I posted a workaround that you can test from here. It will automatically delete a corrupt configuration
https://ci.bleachbit.org/

If you could provide more information, please reopen the ticket. In particular, did you install BleachBit using Chocolately?  This was the apparent cause in #560.

Or, do use AVG or Avast? There are repots of these [security programs corrupting the Firefox configuration](https://www.ghacks.net/2019/06/14/if-you-lost-all-passwords-in-firefox-read-this/
).

**Comment by az0** [comment]
@zoonytoons 
Are you using BleachBit in English, or is BleachBit translated?
