### ISSUE TITLE
Feature Request: Lighter CLI only version

### ISSUE THREAD

**Issue by stephenjudge** [bleachbit/bleachbit#380]
I wanted to use BleachBit on a remote server but when I saw the huge list of dependency packages that it needed, nearly 100MB of extra space be used I decided against it. From a look at the dependency packages needed it seemed their were only needed to allow the GUI to operate and so nearly a whole desktop interface was being downloaded.

Would you consider releasing a CLI only version that has no GUI dependencies which would be better suited to remote Linux servers?

**Comment by az0** [comment]
For now, some options are
1. You could install the GUI packages but not use them. BleachBit runs in CLI-only mode.
2. I think you can force an install (in apt or yum) without loading the dependencies, though that could cause problems for the package manager.
3. You can [run BleachBit from source](https://www.bleachbit.org/documentation/running-source-code). It does not need to be compiled or even installed.

Which Linux distribution do you use? Did you install BleachBit using a package from the www.bleahbit.org site?

**Comment by az0** [comment]
No response since 2018, so closing
