### ISSUE TITLE
UAC inconsistent in running tasks

### ISSUE THREAD

**Issue by MusiqueGraeme** [bleachbit/bleachbit#382]
I have a bat file that runs bleachbit_console on logon.

Sometimes this runs without problem on Windows 10 or 8.1 computers. Sometimes the same task doesn't run and the user is asked to enter his password. The bat file doesn't seem to run.

Why is this and how could it be avoided?

**Comment by az0** [comment]
I am not sure why it would be inconsistent. Do you want to ask BleachBit to not show the UAC? If so, add the `--no-uac` option to the command line, and BleachBit will not try to elevate its privileges. This can still clean user files, such as the browser, but it won't clean system logs.

Let me know

**Comment by az0** [comment]
No response since June 2019, so closing. If you want to continue the discussion, just add a comment to this issue
