### ISSUE TITLE
Not delete Opera data

### ISSUE THREAD

**Issue by Anirbansingha1** [bleachbit/bleachbit#389]
Hi I am using windows 8 and opera mini browser. I select all data except password but it's not delete any of opera mini data. I hope you will fix this. 

BTW, it's very much simple and power-full app. I really like this software.

**Comment by az0** [comment]
The modern Opera (released a few years ago) is not fully supported in BleachBit 2.0 (the stable release), but in May I started making good progress on it. You can preview it here: https://ci.bleachbit.org/

**Comment by az0** [comment]
Please try BleachBit version 2.0.739 or later, and let me know how it goes. It's available from https://ci.bleachbit.org  . I just added much more cleaning for Opera 56

**Comment by az0** [comment]
Please reopen this ticket if this happens in BleachBit 2.0.741 from https://ci.bleachbit.org or in final release BleachBit 2.2 or later.

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.
