### ISSUE TITLE
Modernization rebase: verify changes survived

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#39]

**Comment by moimael** [comment]
So did the changes survived ? :)

**Comment by tstenner** [comment]
I tried to rebase the branch on the weekend and so far, some things work, some don't. Considering there have been almost 2 years of improvements it's impressive that most things work. I'll try to make the rest work on the weekend.

**Comment by ROCKNROLLKID** [comment]
Thanks @tstenner Appreciate your work.

**Comment by az0** [comment]
Changes to `GUI.py` and `GuiBasic.py` look OK
