### ISSUE TITLE
Delete storage in Firefox 62

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#392]
example

$$profile$$/storage/default/https+++www.kaggle.com/cache/caches.sqlite

docs
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria

**Comment by Tobias-B-Besemer** [comment]
Why does this not work?
`<action command="delete" search="walk.all" path="%LocalAppData%\Mozilla\Firefox\Profiles\*\storage\default\*\cache\"/>`
`<action command="delete" search="glob" path="%LocalAppData%\Mozilla\Firefox\Profiles\*\storage\default\*\cache\"/>`

What's about a deep scan?

**Comment by Tobias-B-Besemer** [comment]
And when I add this line...
`<action command="delete" search="deep" path="%LocalAppData%\Mozilla\Firefox\Profiles\*\storage\default\*\cache"/>`
...I get no error msg or something like that, no, the complete option just disappear! :-/

**Comment by az0** [comment]
Fixed in b33e863f27ecceeb82c1b6f630764498a519361a
