### ISSUE TITLE
Bleachbit Not delete Detectify Cookie

### ISSUE THREAD

**Issue by Anirbansingha1** [bleachbit/bleachbit#394]
Hi Bleachbit Team,

I'm using firefox ESR 60 in kali linux. When I delete Cookie using your software it's misses detectify cookie.

**Comment by az0** [comment]
There has been no response, so for now I'll close the ticket

Please try BleachBit version 2.1 and try again. The latest version includes changes for Firefox, and there is also this issue that will be fixed soon: https://github.com/bleachbit/bleachbit/issues/392

BleachBit 2.1 is not yet released, but you could check it out from Git or wait for the beta release, which will include .deb packages. If the same problem continues, please reopen the ticket with more information (see earlier comment).
