### ISSUE TITLE
BkleachBit finds no files to delete when run from root in Ubuntu 18.04

### ISSUE THREAD

**Issue by rlvitalo** [bleachbit/bleachbit#398]
The bug appears in Ubuntu 18.04 using gnome interface. I use BleachBit 2.0. It occurs when running BleachBit from root. It worked fine in 16.04. 
I would download BleachBit from Software apps (Ubuntu). It always present two BleachBit options - one was run from root. That's what I always installed - but I think both were automatically downloaded.

Whenever I ran BleachBit from root in 16.04, it worked fine. Found files and deleted them. No problems.
But afetr I upgraded to 18.04 and ran BleachBit 2.0 from root, the Preview ceased to list any files for deletion. I deleted the app and deleted a left over config file. Reinstalled BleachBit from root. The same problem happened. 

I could not find any guidance as to what to do, so I returned to 16.04. BleachBit from root worked fine once again afetr I installed it. Then - for a number of  reasons - I had to upgrade to 18.04 again. No choice.

Installed the "BleachBit from root" version. Ran it. Same issue - no files found to delete. So, stumbling around, I ripped it all out (i.e., BleachBit) and this time - for the hell of it - I installed the non-root version of BleachBit. Again, both versions seem to come down anyway. BUT, I tried running the BleachBit "not from root" version and, voila!  It's back to working as usual. The files that BleachBit from root could not find all appeared! 

It works fine. Appreciate the app very much.  I have my work-around but I thought I should report this.
It's a great product and the only one that offers all its functionality in Ubuntu.

Raphael

**Comment by az0** [comment]
Basically, I think this is not a bug.

**First**
Installing BleachBit normally installs both the "BleachBit" and "BleachBit as root" icons. 

**Second**
Older versions of BleachBit used pkexec for "BleachBit as root," while newer versions use PolicyKit. Each of these work differently and can explain the results you are seeing. Please see the entry **Q: On Linux do I need to run BleachBit both as a normal user and as an administrator?** in the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html).

If the FAQ does not explain what you are seeing or if it is unclear, let me know
