### ISSUE TITLE
update Windows installer for GTK+ 3

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#40]
@moimael :  I am guessing you do not want to work on this one.

**Comment by az0** [comment]
My next step is to try py2exe/cx_freeze on a  "hello world" GTK+ 3 app.

**Comment by az0** [comment]
As an exercise, I froze a ["hello world" GTK+ v3 and Python 2.7 app for Windows](https://github.com/az0/frozen_pgtk3), and it is 93MB. The next step is cutting back the size. The directory ```build/exe.win32-2.7/share/locale``` alone is 48MB and looks like a good place to start.

**Comment by ROCKNROLLKID** [comment]
Just curious, how far along is GTK3 to be added to BleachBit? Will we see it in 2.0 or will it take a little longer?

**Comment by az0** [comment]
I haven't had time yet to shrink the Windows installer to a manageable size. It will probably not happen for version 2.0

**Comment by ROCKNROLLKID** [comment]
@az0 Maybe you can try this to help shrink the installer: http://wixtoolset.org/

**Comment by az0** [comment]
I used WiX a long time ago, and while it would be interesting to switch from a .exe to .msi installer, the issue isn't so much how the files are bundled (like, using NSIS, WiX, InnoSetup, etc.). The issue is that before being packed up, they are huge because of the giant GTK+ version 3 runtime, so unnecessary files need to be deleted (like I do today with the GTK+ 2 runtime). If that is not enough, it may be necessary to alter files (like I do now also with some GTK+  2 files), or recompile GTK+ 3 to remove unneeded code, or install GTK+ 3 separately. Each of these has its costs and tradeoffs.

**Comment by az0** [comment]
This was implemented. For example, here are some GTK3+ Windows builds (alpha level)

https://ci.appveyor.com/project/az0/bleachbit/build/2.0.682/artifacts
