### ISSUE TITLE
Some cleaners missing on recent dev builds on Windows

### ISSUE THREAD

**Issue by WildByDesign** [bleachbit/bleachbit#400]
On the most recent few dev builds on Windows, chromium.xml, google_chrome.xml, thunderbird.xml (and possibly more) cleaners from the Windows packages. They are missing from the portable zip and the installers. The builds from 2.0.750 are the last to contain these cleaners. Therefore, 2.0.751 and 2.1.752 are both missing them.

There could be more cleaners missing, but those three mentioned above are cleaners which I am most familiar with and therefore notice right away if they are missing.

Thank you for your time.

**Comment by az0** [comment]
@WildByDesign  Thanks for the bug report. Build 2.1.757 (or later) should work better
