### ISSUE TITLE
Unable to run Bleachbit 2.0 from crontab

### ISSUE THREAD

**Issue by isleno** [bleachbit/bleachbit#402]
Unable to run Bleachbit 2.0 from crontab. No problem running 2.0 from GUI or from command line. Also no problem running older version of Bleachbit (1.12-1.el7 from epel repo) from crontab.

OS version is CentOS Linux 7.5.1804
Installation file is bleachbit-2.0-1.1.centos7.noarch.rpm

Error text and crontab entries are attached for review. Have tried running with both sh and bash shells specified, and with the first three lines of crontab entries commented out entirely, with same result.

Thanks for looking...

[bleachbit_error.txt](https://github.com/bleachbit/bleachbit/files/2529659/bleachbit_error.txt)
[crontab.txt](https://github.com/bleachbit/bleachbit/files/2529660/crontab.txt)

**Comment by az0** [comment]
Thanks for reporting this, @isleno . I believe it's fixed in the commit that was referenced here. Perhaps you can apply the simple patch to your system or wait for the next beta or stable release. If not, a workaround for running any GUI program without X is  `xvfb`.

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.

**Comment by isleno** [comment]
Good morning.

2.1 beta works for me, runs great from crontab. Many thanks!

Just fyi, still seeing firefox vacuum errors when running via the gui
interface (seems to be a long-standing problem). I pasted the error info
below just in case you want to take a look.

Overall, this is a great product. Many thanks once again!

Best regards -- Kimball Anderson

/*******************************/

Error: firefox.vacuum: Function: Vacuum:
/home/anderskg/.mozilla/firefox/rqyuxae6.default/favicons.sqlite
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/FileUtilities.py", line 879, in vacuum_sqlite3
    execute_sqlite3(path, 'vacuum')
  File "/usr/share/bleachbit/FileUtilities.py", line 347, in execute_sqlite3
    '%s: %s' % (bleachbit.decode_str(exc), path))
DatabaseError: malformed database schema (moz_icons_to_pages) - near
"WITHOUT": syntax error:
/home/anderskg/.mozilla/firefox/rqyuxae6.default/favicons.sqlite

Error: firefox.vacuum: Function: Vacuum:
/home/anderskg/.mozilla/firefox/2be17rqj.default/kinto.sqlite
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/FileUtilities.py", line 879, in vacuum_sqlite3
    execute_sqlite3(path, 'vacuum')
  File "/usr/share/bleachbit/FileUtilities.py", line 347, in execute_sqlite3
    '%s: %s' % (bleachbit.decode_str(exc), path))
DatabaseError: malformed database schema (collection_metadata) - near
"WITHOUT": syntax error:
/home/anderskg/.mozilla/firefox/2be17rqj.default/kinto.sqlite

Error: firefox.vacuum: Function: Vacuum:
/home/anderskg/.mozilla/firefox/2be17rqj.default/favicons.sqlite
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/FileUtilities.py", line 879, in vacuum_sqlite3
    execute_sqlite3(path, 'vacuum')
  File "/usr/share/bleachbit/FileUtilities.py", line 347, in execute_sqlite3
    '%s: %s' % (bleachbit.decode_str(exc), path))
DatabaseError: malformed database schema (moz_icons_to_pages) - near
"WITHOUT": syntax error:
/home/anderskg/.mozilla/firefox/2be17rqj.default/favicons.sqlite
