### ISSUE TITLE
Data Recovery

### ISSUE THREAD

**Issue by aawheatley** [bleachbit/bleachbit#406]
I don´t know if it´s a bug or what.
Today I decided to see if some data is recoverable using the overwrite option from bleachbit and using a data recovery tool. It was a success but I´m very disappointed that the data is able to be recovered knowing that bleachbit is a tool to safely delete your personal files and documents.

I´m using the latest version of bleachbit.
On windows 10

**Comment by aawheatley** [comment]
THIS ISSUE HAS BEEN RESOLVED!

**Comment by az0** [comment]
Thx for the update, Andrew!
