### ISSUE TITLE
Clearing free space does not destroy erased data

### ISSUE THREAD

**Issue by torerobo** [bleachbit/bleachbit#412]
Hello!
I have a 32GB flash drive where I deleted the "Lazagne" data
I wanted to permanently delete the data of "Lazagne" without the possibility of recovery, so I did a "Clear free space on the flash drive" in bleachbit.
After a successful cleanup operation, which lasted about 30 minutes. I launched the data recovery program R-studio. I scanned the flash drive and found data on it that is possible to restore "Lazagne". I did recover the data and they partially recovered ~ 100% successfully (1.31 MB).
I repeated the operation “cleaning free space on the flash drive”, after waiting another 30 minutes, I restarted the scan of the data recovery program “R-studio” and I again found the data and again was able to recover it.
I tried it in GNU / Linux Debbian 9 (Root).
I tried it in Windows 7 64Bit (Root).

I did not expect this behavior from bleachbit, while if you delete files or directories through software, they cannot be restored, but if you first delete files using standard tools., they are restored and Bleachbit does not help.
![1](https://user-images.githubusercontent.com/35532898/48977493-46f06180-f0ac-11e8-9666-6591b220b3d6.jpg)

**I did the operation “cleaning free space” on a 32 GB flash drive in the “CCleaner”. After cleaning the disc, I could not find deleted files and directories (Lazagne).**
![2](https://user-images.githubusercontent.com/35532898/48978306-b3725d00-f0ba-11e8-848d-0363edcc6c17.jpg)

**Comment by torerobo** [comment]
I tried another experiment.
Linux I deleted the standard files on the disk (ext4). I deleted the standard files from / .Trash-0. I started BB as root and did "clear free space."
After cleaning, I booted into Windows> R-studio, scanned the disk (ext4), found the deleted files and was also able to recover them successfully.

I come to the conclusion that BB is not safe when cleaning the HDD free space.

**Comment by az0** [comment]
You wrote, "They partially recovered ~ 100% successful," so was it partial or 100%?

You wrote that you tried this from Windows 7 and Debian 9. Did you use the ext4 file system in all cases, including on Windows with ext4? Did you use BleachBit version 2.0 in all cases?

You wrote that the files were covered. Did you check that the contents, not just the filenames, were recovered? For example, if you recovered a JPG, I would check that the "recovered" JPG looks OK when viewed in an image viewer.

**Comment by torerobo** [comment]
> You wrote, "They partially recovered ~ 100% successful," so was it partial or 100%?

I wrote ambiguously true.
Because the python script was deleted and restored. And its functionality was not damaged. I wrote partly because I checked the size of the deleted .py script and the size of the restored .py script (the restored script had a slightly larger recovery size, so I partially wrote it).

> You wrote that you tried this from Windows 7 and Debian 9. Did you use the ext4 file system in all cases, including on Windows with CCleaner? Did you use BleachBit version 2.0 in all cases? On Debian 9, did you install BleachBit from the Debian repository or from the package on www.bleachbit.org?

I am sorry. I used version 2.0. -2 Linux package was already pre-installed from the test branch (I found this with apt-get purge bleachbit (bleachbit (2.0-2))). Yes, free space cleaning did not work with ext4 or ntfs. Ie, I successfully recovered files after cleaning BB.

Ccleaner cleared ntfs without problems (it doesn’t know how to work with ext4).

> You wrote that the files were covered. Did you check that the contents, not just the filenames, were recovered? For example, if you recovered a JPG, I would check that the "recovered" JPG looks OK when viewed in an image viewer.

Yes, of course I checked, for convenience I attached a screenshot (the second screenshot) which shows that 11.cfg was successfully restored and contains text strings (this is the grub.cfg file), it was the same with .png
__________________________________________________
I deleted the package in linux
apt-get purge bleachbit (bleachbit (2.0-2))

Now I have installed the bleachbit 2.0 package from here.
https://www.bleachbit.org/download/file/t?file=bleachbit_2.0_all_debian9.deb

I again conducted experiments: deleting files on ext4 ntfs, cleaning free space, restoring files in r-studio.
The result has changed: now I could not recover a single file. BB worked honestly! It turns out the problem was in the BB 2.0-2 package from the test branch of your sheet (Parrot).

But I have not checked it yet on flash drives.

**Comment by az0** [comment]
Using "wipe free space" to erase metadata (in other words, filenames) is not implemented yet in BleachBit 2.0, but it should wipe the contents. You had success with the .deb from this site, so how about we close this bug ticket for now? Feel free to reopen it if the contents are not wiped.

**Comment by torerobo** [comment]
Yes, I had success with the BB 2.0 version. from the official website of the BB package. What about other users? and you saw the screenshots from my first appeal, it was obviously a bug, and a critical bug. I wanted to understand BB vB v2.0-2 is a test package or in the package BB 2.0-2 there was a "program bug" from the developers of OS Parrot. Or some other explanation for this should be the same.?

I agree to close the question, but first I would like to find the answer: what was it really?

**Comment by az0** [comment]
I took a quick look at the package, and it looks like the one distributed by Debian. I'm not sure what was wrong. It may not have been the package. 

When wiping free space, here are some tips

1. It works on a partition basis. For example, some Linux systems have separate partitions for / and /home, and each would need to be wiped separately. As you know, removable drives are separate partitions too.

2. Before wiping free space, this is a good time to delete any files you do not want recovered. This is better than wiping the free space, which takes a while, and then remembering some files that were not deleted.

3. Wiping free space does not delete metadata in BleachBit 2.0. If a recovery program claims to have recovered the data, check the contents are intact.

4. Allow time for it to run. It is slow. It is best to not run other applications that use the disk at the same time.

5. If you find you need to do it often, consider using encryption instead.
