### ISSUE TITLE
Module gtk not imported

### ISSUE THREAD

**Issue by msalini** [bleachbit/bleachbit#413]
Hi,

I am have a LInux Mint distro 18.3 (Sylvia, based on Ubuntu 16.04)
I have just installed the latest version of BB and I get this error:

> Traceback (most recent call last):
>   File "/usr/bin/bleachbit", line 38, in <module>
>   import gtk
> ImportError: No module named gtk

However, I do have ``python-gtk2`` (version 2.24) installed  via `apt`.
I tried to run also a local instance of BB, with the same error.
The previous version was working like a charm.
Any idea?
Thanks

**Comment by az0** [comment]
@msalini Are you launching BleachBit from the GUI or from the console? If from the console, which exact command do you type?

Did you install BleachBit from the Linux Mint repository or from the .deb package on www.bleachbit.org?

**Comment by msalini** [comment]
I upgraded using the standalone .deb package and installed it using `gdebi` (not `dpkg`).

First I tried to launch it via menu, with no result.
Then I tried via console both the commands
- `bleachbit`
- `pkexec bleachbit`

giving me the same error for both

**Comment by az0** [comment]
Would you please try this command to show the Python version and let me know which it is?

`python -V`

Then please try this command in case it gives better results

`/usr/bin/python2.7  /usr/bin/bleachbit`

**Comment by az0** [comment]
My guess is that on your system Python 3 is the default instead of Python 2, but the GTK package you installed was only for Python 2. BleachBit 2.0 was designed only for Python 2

For root you could try `pkexec /usr/bin/python2.7 /usr/bin/bleachbit`

**Comment by msalini** [comment]
_My guess is that on your system Python 3 is the default instead of Python 2,_

Unlikely, or else ``python -V`` would return 3.5
Besides, before the upgrade, BB was working alright (defaulting to 2.7) and I didn't touch python before or after the upgrade.

Your command to open BB root gives me this error:
> /usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
>   warnings.warn(str(e), _gtk.Warning)
> Could not open X display

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.
