### ISSUE TITLE
[Feature Request] Option to specify the system partition (hook OS)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#420]
IMHO it would be nice, if BleachBit is able to "hook" a OS Partition (Option to specify the system partition).
The idea is, that the user can select the drive letter, where the system partition is and therefor "hook a OS".
If this would be possible, then BleachBit can be shipped e.g. on maintenance Boot-CDs/DVDs to clean up a system that should be maintained.
Therefor BleachBit must be able to handle a Windows Registry that is not the one with which BleachBit got started.
But there are also other programs that can do that... I know this technic e.g. from the old program 'Registry Editor PE'... http://regeditpe.sourceforge.net/

**Comment by az0** [comment]
It's an interesting idea, but I wouldn't implement it soon. If you want to discuss submitting a pull request or know someone who does, reopen the issue
