### ISSUE TITLE
Two categories with the same name

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#426]
I have in BleachBit two categories ('Thunderbird') with the same name. Seems one category/one part is already translated into German, the other not... BleachBit seems to make two splited categories out of it...

![2018-12-19 14_15_51-bleachbit](https://user-images.githubusercontent.com/11881073/50257352-3ad19880-03fb-11e9-9da6-40f463be3a2a.jpg)

**Comment by az0** [comment]
The top group is from Winapp2.ini, which does not support translation, and the bottom group comes from `thunderbird.xml` (CleanerML), which does support translation.
