### ISSUE TITLE
Idea: Internal rules (blacklist) to deactivate WinApp2.ini rules

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#431]
I have now written CleanerML rules for 'XnView Classic for Windows' & 'XnView MP'.
No, normally, the 'XnView' rule from WinApp2.ini should be deactivated by a internal blacklist.
Also: The WinApp2.ini-Team have mixed up 'XnView Classic for Windows' & 'XnView MP', but this are two separate programs that don't belong (beside producer & name) together!

**Comment by az0** [comment]
For issues with Winapp2.ini, please see https://github.com/bleachbit/winapp2.ini#reporting-bugs

About the blacklist, file an issue here  https://github.com/bleachbit/wishlist/ (one concern per issue ticket---not "also...")

**Comment by Tobias-B-Besemer** [comment]
My 'Also:' should maybe be a 'One Reason:'.
I discussed this problem with the "WinApp2.ini-Team", but it seems it is now like they wont...
https://github.com/MoscaDotTo/Winapp2/pull/344
