### ISSUE TITLE
Bleachbit 2.0 break dependency: libharfbuzz

### ISSUE THREAD

**Issue by fjrg76mx** [bleachbit/bleachbit#432]
Today I tried to run Bleachbit but I got this error in the console:

```
$ bleachbit 
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 38, in <module>
    import gtk
  File "/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py", line 40, in <module>
    from gtk import _gtk
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
$ bleachbit --version

BleachBit version 2.0
Copyright (C) 2008-2018 Andrew Ziem.  All rights reserved.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ python --version
Python 2.7.15rc1
$ 
```

Then I removed it and installed it again, but the error is still there. Bleachbit was working nicely until today. I was running Linux Mint 19.0 Cinnamon.

Any advices?

**Comment by az0** [comment]
Please check that PyGTK+ is working on your system for other applications. You could test any application listed by this command

````
apt-cache rdepends python-gtk2
````
One possibility is 

````
sudo apt-get install fslint
/usr/bin/fslint-gui
````

**Comment by fjrg76mx** [comment]
Hi,

This is what I got:

`$ sudo apt-cache rdepends python-gtk2
python-gtk2
Reverse Depends:
  python-glade2
  nemo-dropbox
  dia-common
  dropbox
  python-notify
  bleachbit
  gimp
  keepnote
$`


From that list, Does it run?:

  python-glade2 _Can't say_
  nemo-dropbox _Cant' say_
  dia-common _Yes_
  dropbox _Yes_
  python-notify _Cant' say_
  bleachbit _No_
  gimp _Yes_
  keepnote _No (same output as when bleachbit is run in a console)_

_Can't say_ means it's not an executable, e.g. it's a plugin or I couldn't find the executable.

**Comment by az0** [comment]
I think this is not specific to bleachbit.  

See for example here or search the error on Google

https://github.com/kovidgoyal/kitty/issues/595
