### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbe in position 1: invalid start byte

### ISSUE THREAD

**Issue by Ub3rZ4cH** [bleachbit/bleachbit#434]
Had this issue before, not sure how but it went away, now its come back.

> Traceback (most recent call last):
>   File "/usr/share/bleachbit/Worker.py", line 254, in run
>     for dummy in self.run_deep_scan():
>   File "/usr/share/bleachbit/Worker.py", line 313, in run_deep_scan
>     for path in ds.scan():
>   File "/usr/share/bleachbit/DeepScan.py", line 85, in scan
>     for (dirpath, dirnames, filenames) in normalized_walk(top):
>   File "/usr/share/bleachbit/DeepScan.py", line 59, in normalized_walk
>     for result in os.walk(top, **kwargs):
>   File "/usr/lib/python2.7/os.py", line 296, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/usr/lib/python2.7/os.py", line 296, in walk
>     for x in walk(new_path, topdown, onerror, followlinks):
>   File "/usr/lib/python2.7/os.py", line 286, in walk
>     if isdir(join(top, name)):
>   File "/usr/lib/python2.7/posixpath.py", line 73, in join
>     path += '/' + b
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xbe in position 1: invalid start byte

Seems its something related to deep-scan, when disabling deep scan category it works fine.

Using the latest Bleachbit 2.0 from github release, running as sudo.

**Comment by az0** [comment]
Hmm, this looks just an issue that was fixed in April in commit 7f7451ffaf6a0a045509dd228dd30aab4b7f6065, and the traceback above looks like it is the old BleachBit version 2.0 (for example line 85 https://github.com/bleachbit/bleachbit/blob/38136abc0a277b0c2fe754969d1b3fd9ff52403f/bleachbit/DeepScan.py#L85) instead of the latest version.

Please make sure you don't have the old version installed at all. If you click **Help - About**, it should read BleachBit 2.1, if you are using the latest from Git.

**Comment by Ub3rZ4cH** [comment]
That's odd I thought I had the latest one, is the one in the releases not the latest? I needed to wget the git or use the clone thing right ? 

Werid thing is it's started working again but I press help and about and it's version 2.0

**Comment by az0** [comment]
Ahh, it depends what you mean by latest. Version 2.0 in the GitHub releases is the latest, stable release, but it's about 11 months behind the master branch. 

Yes, git clone is one way to get the latest development release. There are docs here: [Running from source](https://docs.bleachbit.org/dev/running-from-source-code.html). For testing this bug, BleachBit is easy to run from source in just a few lines without installation.

**Comment by az0** [comment]
I think it's fixed here https://www.bleachbit.org/news/bleachbit-21-beta

If not, please reopen the ticket
