### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [bleachbit/bleachbit#435]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by Twig6943** [comment]
Flatpak: https://flathub.org/apps/org.bleachbit.BleachBit

**Comment by az0** [comment]
[BleachBit version 6.0.1 beta](https://www.bleachbit.org/news/bleachbit-601-beta) was released with AppImage. When you have a chance, try it out. Thanks for your patience
