### ISSUE TITLE
[Windows] Installer option to skip desktop icon

### ISSUE THREAD

**Issue by teknowledgist** [bleachbit/bleachbit#437]
It is fairly common for installers to have an option to skip the creation of a desktop icon.  Software deployed via SCCM or KACE or other enterprise methods are installed on systems on which most/all users are not administrators and often don't have a say as to what is installed even if they will never use it.  An icon placed in the public desktop cannot be removed by non-administrators, so the user has no choice.  

Admins can script the install to remove an icon immediately after the install, but that's "messy".  It would be nice if that were built into the installer as an option.

Thanks.

**Comment by Tobias-B-Besemer** [comment]
This seems to be fixed - can we close the issue?

**Comment by az0** [comment]
No. He wants a new switch for the automated Windows installer.

**Comment by Tobias-B-Besemer** [comment]
@teknowledgist, this is fixed in my latest builds. You can download them from here:
https://drive.google.com/drive/folders/1ZbzJimB2rPPaC9zen-5_8frIX5RlCN4M?usp=sharing

**Comment by teknowledgist** [comment]
I'm disappointed that this fairly simple request and common feature that @Tobias-B-Besemer solved (or claims too -- I haven't tested it) 6 months ago wasn't included in the major release.  Resolving it shouldn't have delayed the release more than a couple days at worst and now the world will have to wait who knows how many more months.

**Comment by az0** [comment]
I understand you're disappointed. I would have liked to add several more things to the release, but I also wanted to get it released months earlier.

I haven't had time to review Tobias's installer, which is a complete overhaul. I would a accept a patch that does just this---this simple change would be much easier to review.

**Comment by Tobias-B-Besemer** [comment]
The prob is, it wasn't a simple change!
Parameters are till now done by a external plugin.
But we add here a new parameter!
Means: I had to capture all parameters and handle them!
This is one big reason, why the installer written by me is a complete overhaul!

**Comment by Tobias-B-Besemer** [comment]
I made a new version of the new installer with BB3.0. The files you can use are in the folder NSIS.UMUI.Gray and you can download them here:
https://drive.google.com/drive/folders/1ZbzJimB2rPPaC9zen-5_8frIX5RlCN4M

If you have to roll out many installs of BB in a company environment, you should use this installer!
He solves your issue!

**Comment by az0** [comment]
Let's look at this for the next release. 

By the way, I would be interested if you have any other feedback to make BleachBit better for enterprises. Please create separate issues.

**Comment by az0** [comment]
@rados 
I assigned to you because you opened a PR.

@teknowledgist  @Tobias-B-Besemer 
There is a build available with this improvement. Are you available to test it please? If so, I will send more details

**Comment by teknowledgist** [comment]
@az0 Hi.  Sorry for the delayed response.  I can test the installer, sure.

**Comment by az0** [comment]
@teknowledgist 

Please download a recent build from the [BleachBit CI site](https://ci.bleachbit.org/), and install with this command (assuming you get build 1946)

`BleachBit-4.4.1.1946-setup.exe /S /NoDesktopShortcut`

**Comment by az0** [comment]
Correction: you have to add a third parameter, it is case sensitive, and the order matters.

To install for current user only:
`BleachBit-4.4.1.1946-setup.exe /S /NoDesktopShortcut /CurrentUser`

To install for all users, but it requires the calling process to have admin privileges. 
`BleachBit-4.4.1.1946-setup.exe /s /NoDesktopShortcut /AllUsers`

It is so silent that no error message is given if you forget the last parameter.

**Comment by j10k** [comment]
I have tested this with BleachBit-4.4.0-setup, and the parameter had no effect whatsoever (even in the correct order and the correct case). Will retry later.
