### ISSUE TITLE
GtkWarning: inner_clipboard_window_procedure: assertion `success' failed

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#440]
GtkWarning: inner_clipboard_window_procedure: assertion `success' failed

[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/2857013/bleachbit.exe.log)

**Comment by az0** [comment]
Have to seen this since BleachBit 3.0?

**Comment by abitrolly** [comment]
Any news on that?

**Comment by az0** [comment]
There has been no response for ~1.5 years, so I will close it. Thank you, Anatoli for pointing out this old issue. If Tobias still has this issue, he is welcome to reopen this issue ticket.
