### ISSUE TITLE
command="delete" search="folder" ?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#446]
There are some cases where I want to write a CleanerML rule to delete a folder with his content.
Is it possible that this scenario isn't supported, yet?
"walk.all" seems to just delete the content of a folder, but even with wildcard in the naming it doesn't delete the folder itself...
"glob" it seems I still don't really understand - maybe because you point to python in the documentation and I can't program in python... Seems "glob" doesn't delete folders at all?
Wouldn't be a 'command="delete" search="folder"' not consequent and helpful?

**Comment by az0** [comment]
search=glob is how it finds a path, and command is what it does with it, so this is why glob doesn't delete it.

See my comment in https://github.com/bleachbit/bleachbit/issues/447

Changing the behavior of something already in use (walk.all) could break all the cleaners that already use it

**Comment by az0** [comment]
OK, I'll add something like search=folder to delete the folder and all its contents

**Comment by Tobias-B-Besemer** [comment]
Thx! :-)

**Comment by Tobias-B-Besemer** [comment]
When `search="walk.top"` is now implemented, then close this issue?
