### ISSUE TITLE
"walk.all" used with wildcards should also delete the folders found, not just the content

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#447]
Example:
`<action command="delete" search="walk.all" path="%LocalAppData%\Temp\i2p-*"/>`
...deletes the content of the folder...
`i2p-7ZYgtGhs.tmp`
...but not the folder itself.

**Comment by az0** [comment]
I am not sure I agree with the "should," but if this is your goal, what if you do this?

```
<action command="delete" search="walk.all" path="%LocalAppData%\Temp\i2p-*"/>
<action command="delete" search="file" path="%LocalAppData%\Temp\i2p-*"/>
````

**Comment by Tobias-B-Besemer** [comment]
Unfortunately `i2p-7ZYgtGhs.tmp` is a folder... :-/

What's about this:
`<action command="delete" search="walk.all" path="%LocalAppData%\Temp\i2p-*"/>
<action command="delete" search="glob" path="%LocalAppData%\Temp\i2p-*"/>`

**Comment by Tobias-B-Besemer** [comment]
I figured out, that when I add a "\*" at the end of a path by walk.all, nothing gets deleted!
IMHO you should really document that for the people who wanna write rules with it!
If you host your documentation on GitHubPages, I will add my experiences...

I attach some screenshots from what I had/did...
![2019-02-18 06_53_45-i__work_cleaner_bleachbit_my_windows_memory_dumps xml - notepad administrator](https://user-images.githubusercontent.com/11881073/52930978-e7bc8900-334a-11e9-9a4d-b1f418b6411c.jpg)
![2019-02-18 06_53_02-bleachbit](https://user-images.githubusercontent.com/11881073/52930984-ec813d00-334a-11e9-9c2d-7ad420effeae.jpg)
![2019-02-18 06_56_22-i__work_cleaner_bleachbit_my_windows_memory_dumps xml - notepad administrator](https://user-images.githubusercontent.com/11881073/52930986-f014c400-334a-11e9-8127-cd095b3ec594.jpg)
![2019-02-18 06_56_04-bleachbit](https://user-images.githubusercontent.com/11881073/52930989-f30fb480-334a-11e9-809c-d1032b359634.jpg)

**Comment by Tobias-B-Besemer** [comment]
And this doesn't work...
![2019-02-18 06_56_22-i__work_cleaner_bleachbit_my_windows_memory_dumps xml - notepad administrator](https://user-images.githubusercontent.com/11881073/52931783-e80a5380-334d-11e9-8794-3f345849623c.jpg)

...but this work...
![2019-02-18 07_20_15-i__work_cleaner_bleachbit_my_windows_memory_dumps xml - notepad administrator](https://user-images.githubusercontent.com/11881073/52931791-efc9f800-334d-11e9-9a8f-3e429b65ccdb.jpg)

**Comment by az0** [comment]
Yes, this looks OK. The second command will delete any directory or file that matches the glob, but it won't look inside any directories.
````
<action command="delete" search="walk.all" path="%LocalAppData%\Temp\i2p-*"/>
<action command="delete" search="glob" path="%LocalAppData%\Temp\i2p-*"/>
```

The documentation is here https://github.com/bleachbit/docs

When search="walk.all" is used with a glob pattern in the `path`, it does this. First, it expands the pattern to find directories, and then it walks the directory. If the glob pattern matches a file, nothing is supposed to happen because it expects directories.

It sounds like you figured it out, so I will close this

**Comment by Tobias-B-Besemer** [comment]
> The documentation is here https://github.com/bleachbit/docs

I started here a fork with a first draft:
https://github.com/Tobias-B-Besemer/docs/blob/cleanerml-examples/_posts/cleanerml-examples.md

Maybe we can work together on it, that it fits your needs and you can check it in?

**Comment by az0** [comment]
OK, let's work on improving the docs. Thanks for starting it. Later I'll check it out in more detail
