### ISSUE TITLE
Some special characters in INI-files break cleaners completely

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#448]
I figured out, that some special characters in INI-files like the German ä, ö, ü, ß, break the cleaners completely. In one case I had a special character like a special space or line break, that was not visible for me. After copy the INI-file into the clipboard and pasted it again into the INI-file, all worked well. But I was not able to figure out, which special character it was.
Also: It doesn't matter on which position the special character is. No matter if this part get cleaned or not, the cleaner gets broken completely!

This is how it looks like, when the cleaner get "broken":
![2019-02-16 21_18_26-bleachbit](https://user-images.githubusercontent.com/11881073/52929610-6a424a00-3345-11e9-9c2c-7093e078ec36.jpg)

**Comment by az0** [comment]
Could you please try to get more log information about this error? Here's some instructions https://docs.bleachbit.org/doc/troubleshooting.html

Ideally there would be a traceback message. This other bug has an example of what a traceback looks like: https://github.com/bleachbit/bleachbit/issues/327

**Comment by Tobias-B-Besemer** [comment]
Next bug: Seems the log don't capture the error...

[bleachbit-debug-2019-02-15.log](https://github.com/bleachbit/bleachbit/files/2899167/bleachbit-debug-2019-02-15.log)

...but I mad a screenshot of the console... ;-)
![2019-02-25 06_59_38-administrator_ c__windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/53317265-45148500-38cb-11e9-82b1-6b69a72fdebc.jpg)

**Comment by Tobias-B-Besemer** [comment]
The log says 'utf8', but the file is 'ansi'... :-/

**Comment by az0** [comment]
@Tobias-B-Besemer 
Rado is working on a fix for this too. We'll let you know when it's ready for testing

**Comment by rados** [comment]
@Tobias-B-Besemer 

I am Rado and I am happy to work with you. :)

I think I've found a clue. It is about how the ini file is being saved. I noticed that when I save it with the Notepad and give ANSI encoding the app produces exactly the same problem as described. So, may I ask you to check how do you save the ini file? (It should be saved with UTF8.)

**Comment by Tobias-B-Besemer** [comment]
Hi @rados!

Nice to meet you! :)

As the INI files get produced by the apps I/we want to clean, I have no chance to change on how they do it  (how they save it).

Greets, Tobias.

**Comment by Tobias-B-Besemer** [comment]
Btw.: The prob appeared by Total Commander (but can appeare by each other prog, too).
I can make a "bug report" to Total Commander... but it's proprietary and I don't know if they care about it... :-/

**Comment by rados** [comment]
Okay, I see. Then could you upload this ini so that I would be able to get some more information hopefully...

**Comment by Tobias-B-Besemer** [comment]
Guess, after I documented the issue, I cleaned the INI and moved on... So the original INI is lost!

But as I figured it out - "special characters in INI-files like the German ä, ö, ü, ß" - with that info you should be able to reproduce the issue.

**Comment by rados** [comment]
@Tobias-B-Besemer, thanks, I managed to replicate the issue.

@az0 As it is not trivial to determine the ini file encoding I think we can use external library for this: https://pypi.org/project/chardet/. What do you think?

**Comment by az0** [comment]
@rados  That makes sense because .ini doesn't have explicit encoding. OK to the chardet package. I can see it's in pypi and Ubuntu, so it should be fine. Would you please see these two commits about adding it

First, adding dependencies 159cd3bce9e8d836ec1afe7488166502b5a9b896

Second, adding fallback 039500e5419baa5bfbe4042c3c26bb1bbcab7611

**Comment by az0** [comment]
Rados made a fix for this, and I merged it. It will be build 2.3.1251.  His approach was to automatically detect the encoding

@Tobias-B-Besemer If you could please test, I would appreciate it.

**Comment by Tobias-B-Besemer** [comment]
@rados & @az0, OK, as I be in normal life (when I don't spend my spear-time to FOSS) a excited SQC Freelancer, I would like to fix this issue on both sides, here at BleachBit and at https://www.ghisler.com. Because as far as I understand it, Total Commander saves in a ANSI INI File in some cases special characters that are in this way not allowed in ANSI Files, right? They normally should switch to a UTF8 INI File, right?
So if it's OK for you Andrew, I will point the Ghisler Support to this issue. Is this OK for you?

I will also do some tests with the Total Commander Cleaner, look that I get some German special characters into the INI File and have a look if BB still crash...
...if not, what I expect, then I think you Andrew can check in my cleaner https://github.com/az0/cleanerml/pull/166 and maybe move it to https://github.com/bleachbit/bleachbit/tree/master/cleaners because Total Commander is now already ~25yo (https://en.wikipedia.org/wiki/Total_Commander) and should have millions of users worldwide. What do you think about it ???

**Comment by Tobias-B-Besemer** [comment]
OK, unfortunately it still break in my test! :-/

![2019-09-10 23_29_58-BleachBit](https://user-images.githubusercontent.com/11881073/64652044-333b9f00-d423-11e9-84d2-d0dabff916cf.jpg)

![2019-09-10 23_30_22-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/64652054-39ca1680-d423-11e9-9552-9a0e28e27aaa.jpg)

**Comment by Tobias-B-Besemer** [comment]
OK, sorry! My fault! It works! I forgot to update to the latest build... ^^

**Comment by rados** [comment]
@Tobias-B-Besemer,

Thanks for the feedback and glad to see fixed. In my opinion it is not needed to contact Total Commander team. They save the ini in proper encoding - windows1251 or other that corresponds to the system language setting. It was tricky on our side to determine the exact encoding but we've found a way. :)

**Comment by Tobias-B-Besemer** [comment]
@rados, thank you very much for your feedback! :)
