### ISSUE TITLE
UnicodeDecodeError in Console when executing dism.exe

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#451]
Code is:
`<action command="process" wait="true" cmd="dism.exe /online /cleanup-image /spsuperseded"/>`

Console says:
![2019-02-26 06_12_03-bleachbit](https://user-images.githubusercontent.com/11881073/53389390-7060a800-398f-11e9-922a-1827ce5162fd.jpg)

And nothing gets saved in the log/debug file!

**Comment by az0** [comment]
Please disregard my note in https://github.com/bleachbit/bleachbit/issues/457 about `DISM.EXE` . I can see you tried that :)

Yes, this Unicode error needs fixed

**Comment by Tobias-B-Besemer** [comment]
As I wrote in #457: The problem is, not this feature in Win7...

**Comment by az0** [comment]
I would still like to fix this properly, so I will leave this issue open. As a temporary workaround, try the two tricks from #457: `cmd.exe /c` and start

**Comment by Tobias-B-Besemer** [comment]
Sorry, no luck!

![2019-02-27 06_32_40-bleachbit](https://user-images.githubusercontent.com/11881073/53468353-20024c80-3a5a-11e9-8d22-d783ca2c207c.jpg)

![2019-02-27 06_36_03-_i__work_cleaner_bleachbit_my_windows_update xml - notepad administrator](https://user-images.githubusercontent.com/11881073/53468358-24c70080-3a5a-11e9-98c7-d8bf7887c66f.jpg)

**Comment by az0** [comment]
@Tobias-B-Besemer  
I have a contractor (different than the Vuze issue) working on a fix for this and related internationalization issues. I'll let you know when it's ready

**Comment by az0** [comment]
@Tobias-B-Besemer 

Would you please test Rado's fix in [build 2.3.1194](https://ci.appveyor.com/project/az0/bleachbit/builds/26483244/artifacts)? This patch is not merged, so for now the fix won't be in other builds.

**Comment by az0** [comment]
Based on unit test by Rados, it seems this is fixed

**Comment by az0** [comment]
Fix by Rados was merged into the master branch

**Comment by Tobias-B-Besemer** [comment]
Sorry for always being late! ^^
I will test a new built and look if it works.
