### ISSUE TITLE
glob doesn't work in %WINDIR%\System32\config\

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#455]
I have the following block of rules:

`<action command="delete" search="glob" path="%WINDIR%\*.log"/>`
`<action command="delete" search="glob" path="%WINDIR%\System32\config\*.log"/>`
`<action command="delete" search="glob" path="%WINDIR%\System32\config\*.log1"/>`
`<action command="delete" search="glob" path="%WINDIR%\System32\config\*.log2"/>`
`<action command="delete" search="glob" path="%SystemDrive%\Boot\*.log"/>`
`<action command="delete" search="glob" path="%SystemDrive%\Boot\*.log1"/>`
`<action command="delete" search="glob" path="%SystemDrive%\Boot\*.log2"/>`

Here are getting line 1 & 5-7 executed, while line 2-4 are not! And I have no clue why!

**Comment by Tobias-B-Besemer** [comment]
Btw.: Nothing in the console...

**Comment by az0** [comment]
If you open `%WINDIR%\System32\config\` are there files directly in that folder? On my Windows 10 machine there are none there.

If yes, perhaps you could attach a screenshot of the contents of that folder

**Comment by Tobias-B-Besemer** [comment]
![2019-02-27 05_05_01-c__windows_system32_config](https://user-images.githubusercontent.com/11881073/53465243-59808b00-3a4d-11e9-880a-f6eab4ebe3bc.jpg)

**Comment by az0** [comment]
That's interesting. For testing purposes, would you please rename one of those to be all lowercase OR create a new file with a lowercase name such as `temp.log`. Does BleachBit find the lowercase log?

**Comment by Tobias-B-Besemer** [comment]
Can do this, but the files deleted in the other lines had also high case...

**Comment by Tobias-B-Besemer** [comment]
![2019-02-27 05_31_29-c__windows_system32_config](https://user-images.githubusercontent.com/11881073/53466163-204a1a00-3a51-11e9-94d2-34656faafa3c.jpg)

![2019-02-27 05_31_55-bleachbit](https://user-images.githubusercontent.com/11881073/53466169-25a76480-3a51-11e9-99f4-bf169b4c70f2.jpg)

**Comment by az0** [comment]
The root cause is that Microsoft Windows performs sneaky folder redirection for 32-bit applications on a 64-bit operation system. Documentation: https://docs.microsoft.com/en-us/windows/desktop/winprog64/file-system-redirector

It's easy to bypass it by substituting `sysnative` for `system32`. I tested it, and it works. When you do this, please add an XML comment with a brief note and link to the Microsoft article.

**Comment by Tobias-B-Besemer** [comment]
> It's easy to bypass it by substituting `sysnative` for `system32`. I tested it, and it works. When you do this, please add an XML comment with a brief note and link to the Microsoft article.

Sorry, I don't know how this works...

**Comment by az0** [comment]
Use this code
````
<!--
64-bit Windows redirects %windir%\sysnative\ for 32-bit applications to %windir%\system32 
https://docs.microsoft.com/en-us/windows/desktop/winprog64/file-system-redirector
-->
<action command="delete" search="glob" path="%WINDIR%\sysnative\config\*.log"/>
<action command="delete" search="glob" path="%WINDIR%\sysnative\config\*.log1"/>
<action command="delete" search="glob" path="%WINDIR%\sysnative\config\*.log2"/>
````

**Comment by Tobias-B-Besemer** [comment]
Yeah, this works! :-)
