### ISSUE TITLE
BB don't delete files that are write protected

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#456]
BleachBit don't delete files that are write protected even it says it does!

**Comment by az0** [comment]
Which file exactly?

Does the BleachBit log state "Delete" or "Marked for deletion"?

If "marked for deletion," did you check after rebooting?

**Comment by Tobias-B-Besemer** [comment]
I had it in two cases... Once was the BOOTLOADER.BAK (?) in C:\...
I removed write protection and AFAIK it worked afterwards...

**Comment by az0** [comment]
BleachBit should delete write-protected files on Windows. The BleachBit log will indicate "Marked for deletion" instead of "Deleted," and the files are deleted when Windows reboots. This is necessary, for example, with Internet Explorer. 

If you see otherwise, please re-open the issue. Please include the line from the BleachBit log for this file.

**Comment by Tobias-B-Besemer** [comment]
I tested it again with a fresh copy of BOOTSECT.BAK...

I get this msg in BB:
![2019-02-27 12_37_03-bleachbit](https://user-images.githubusercontent.com/11881073/53487770-b6e7fc80-3a8c-11e9-80c8-c9609cb75a17.jpg)

Translated it means: "Select for deletion", what maybe is a not so good translation... ;-)

My question is now: Why can't BB delete BOOTSECT.BAK immediately ??? It's just a hand-made copy and a BAK-File...

**Comment by Tobias-B-Besemer** [comment]
Also irritating: Last line says "Deleted files"...

**Comment by Tobias-B-Besemer** [comment]
![2019-02-27 15_43_59-bleachbit](https://user-images.githubusercontent.com/11881073/53498588-e3a90d80-3aa6-11e9-844e-47143768fa38.jpg)
Same issue in %WINDIR%\sysnative\config\ - *.log2 are old backup-log-files and shouldn't be looked by the system...

**Comment by Tobias-B-Besemer** [comment]
But it seems BOOTSECT.BAK and the *.log2-files have in common, that they are hidden...

**Comment by az0** [comment]
If the file is not immediately deleted, first make sure you running BleachBit as administrator. Second, check whether another Windows process has the file open. Windows doesn't like multiple processes messing with the same file ([obligatory comic](obligatory)).  In the second case, use [Microsoft Process Explorer to identify which program is using the file](https://www.techsupportalert.com/content/how-find-out-which-windows-process-using-file.htm).

If you are running BleachBit as administrator and you confirm no other process is using the file, then reopen the issue and let me know the filename.

**Comment by Tobias-B-Besemer** [comment]
OK, I'm running BB as admin. Microsoft Process Explorer doesn't work, because it is intended for DLLs (seems so). If I try to point to the file in Explorer, Explorer Window gets marked and after that shown in Microsoft Process Explorer.
But a easy try: I can't delete the file. I open the settings of the file and the file is write-protected & hidden. I remove write-protect (maybe the other way works, too!) and after that BleachBit can delete the file!
Guess it's the combination of write-protected & hidden!

Desktop.ini-files maybe also write-protected & hidden!
See issue #460.

**Comment by Tobias-B-Besemer** [comment]
OK, a other try:
I created a empty file called BOOTSECT.BAK in C:\. I set the settings to write-protected & hidden. Run BB. BB can't delete! Remove hidden. BB can't delete! Remove write-protected. BB _can_ delete!

**Comment by az0** [comment]
I'll check into write protected files. Thanks for the report

**Comment by az0** [comment]
I see the error when the file is read only, when shred is enabled, and when the user is an administrator. 

````
======================================================================
ERROR: test_delete_read_only (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for delete() with read-only file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests\TestFileUtilities.py", line 387, in test_delete_read_only
    delete(fn, shred=True)
  File "bleachbit\FileUtilities.py", line 286, in delete
    wipe_contents(path)
  File "bleachbit\FileUtilities.py", line 671, in wipe_contents
    file_wipe(path)
  File "bleachbit\WindowsWipe.py", line 917, in file_wipe
    file_handle = open_file(file_name, GENERIC_READ | GENERIC_WRITE)
  File "bleachbit\WindowsWipe.py", line 432, in open_file
    OPEN_EXISTING, 0, None)
error: (5, 'CreateFileW', 'Access is denied.')
````

**Comment by az0** [comment]
Fixed
