### ISSUE TITLE
command="process" don't open the GUI of the program

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#457]
`<action command="process" cmd="Cleanmgr.exe"/>`

I don't get the GUI of the program...

**Comment by az0** [comment]
`command="process"` is intended for non-interactive processes. BleachBit is sometimes used in automated scripts (from its own command line), and an interactive process would hang BleachBit. 

Also, this avoids an awkward pop-up window when launching a non-interactive process while a user is present.

**Comment by Tobias-B-Besemer** [comment]
That's sad! Cleanmgr.exe seems to be the only offer I can make a Windows 7 user for cleaning up his WinSxS Cache... And we talk about gigabytes that get cleaned up this way!

**Comment by az0** [comment]
Have you tried dism.exe? 
https://www.laptopmag.com/articles/clean-winsxs-folder-to-save-space

**Comment by Tobias-B-Besemer** [comment]
dism.exe have this feature only from Windows Version 8 on...

**Comment by az0** [comment]
Hmm, ideally older platforms would be supported. BleachBit 2.2 will still support XP, but soon afterwards I will drop support for some old platforms. 

Microsoft will make Windows 7  EOL on January 2020,

**Comment by Tobias-B-Besemer** [comment]
> Microsoft will make Windows 7 EOL on January 2020,

I know...

**Comment by az0** [comment]
What if you try this?

````
<action command="process" cmd="cmd.exe /c Cleanmgr.exe"/>
````

Or you could try start: https://ss64.com/nt/start.html

**Comment by Tobias-B-Besemer** [comment]
> What if you try this?
> 
> ```
> <action command="process" cmd="cmd.exe /c Cleanmgr.exe"/>
> ```
Yeah! This works! :-)

**Comment by az0** [comment]
Great
