### ISSUE TITLE
Erasing the Recycler with CleanerML and an external tool

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#458]
I wanted to find for my windows.xml a solution to erasing the Recycler with CleanerML and an external tool...
I found this page: https://www.intowindows.com/how-to-quickly-empty-recycle-bin-from-all-user-accounts/
Using command: rd /s c:\$Recycle.Bin
But I get this msg in BleachBit:
![2019-02-27 15_35_52-bleachbit](https://user-images.githubusercontent.com/11881073/53497870-78ab0700-3aa5-11e9-9c13-fbd3b59b9a53.jpg)
...also with: cmd.exe /c rd /s c:\$Recycle.Bin
In command line it works:
![2019-02-27 15_31_09-administrator_ c__windows_system32_cmd exe - rd _s c__ recycle bin](https://user-images.githubusercontent.com/11881073/53497970-a85a0f00-3aa5-11e9-8d60-436932460fed.jpg)
I guess I get this msg in BB because "rd" is no EXE?
Any idea to it?

**Comment by Tobias-B-Besemer** [comment]
![2019-02-27 15_39_31-administrator_ c__windows_system32_cmd exe - bleachbit_console exe --gui --debu](https://user-images.githubusercontent.com/11881073/53498107-f1aa5e80-3aa5-11e9-9721-da7dff5828d3.jpg)
Btw., error msg says in German: The system can't find the file.

**Comment by Tobias-B-Besemer** [comment]
I tried now walk.all + glob, and this works, too! :-D

**Comment by az0** [comment]
Yes, RD is not its own executable. RD is part of CMD.exe.

You mentioned you found a solution, so is it OK to close this issue?

By the way, there are various issues when emptying the recycle bin. For example, BleachBit resets the recycle bin icon (on the desktop) to show it's empty. BleachBit is also careful to not follow symlinks.

**Comment by Tobias-B-Besemer** [comment]
Yes, you can close this issue!

I tested with rd on Win7... Deletes just the files that existed before deletion on drive C:... Recycle bin (folder) got created on the system immediately again... Recycle bin (system) including after that the files from the other drives...

c:\ $Recycle.Bin is the "hard address" of the RC Bin...

With the "More" cleaner I delete all RC Bins on all drives _and_also_ the regkeys to them... ;-)
