### ISSUE TITLE
bleachbit not doing free space clean win 10 

### ISSUE THREAD

**Issue by ray561** [bleachbit/bleachbit#459]
go to do a free space clean and it doesn't do the clean two errors are present enclosed is log file for help
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/2923130/bleachbit.exe.log)

**Comment by az0** [comment]
1. Is the E: drive a network drive or local removable drive? Or what kind of drive is E:?

2. Which version of BleachBit? Check the Help menu.

3. Which kind of antivirus/security software do you have?

**Comment by az0** [comment]
No response for one year
