### ISSUE TITLE
Internet Explorer not cleaned with non-English folder name

### ISSUE THREAD

**Issue by PiotrMP006** [bleachbit/bleachbit#460]
BleachBit - Unable to Delete Internet Temporary Files IE8 in Windows XP

After cleaning Internet Temporary Files IE8 in Windows XP the directories and desktop.ini files are not deleted.

ex.
C:\Documents and Settings\username\Local Settings\Temporary Internet Files\Content.IE5\2IW1KED4\desktop.ini
C:\Documents and Settings\username\Local Settings\Temporary Internet Files\Content.IE5\LS10OW75\desktop.ini

C:\Documents and Settings\username\Local Settings\Temporary Internet Files\Content.IE5\desktop.ini
C:\Documents and Settings\username\Local Settings\Temporary Internet Files\Content.IE5\index.dat

The error occurs in the BleachBit version 2.0 and 2.1 Beta

Help

**Comment by az0** [comment]
While BleachBit is running, are these files marked with the word "Deleted" or "Mark for deletion"?

**Comment by PiotrMP006** [comment]
Hi

See the error

[image: BleachBit_v2.1_IE8_Error.png]



Pozdrawiam / Regards,
Piotr Przeklasa
3D Artist / Programmer


wt., 5 mar 2019 o 03:38 Andrew Ziem <notifications@github.com> napisał(a):

**Comment by az0** [comment]
Sorry, in GitHub I don't see the image. Please try again to upload to GitHub

**Comment by PiotrMP006** [comment]
See the error

![bleachbit_v2 1_ie8_error](https://user-images.githubusercontent.com/39049428/53821401-04bda280-3f6e-11e9-8eb6-282b0469280e.png)

**Comment by Tobias-B-Besemer** [comment]
I guess C:\Documents and Settings\username\Local Settings\Temporary Internet Files\Content.IE5\ can be completely deleted...

**Comment by Tobias-B-Besemer** [comment]
I'm not sure if WinXP & IE8 should be really still supported...
...but here is a other try.
Plz test it and give feedback!
Thx in advance!
https://github.com/bleachbit/bleachbit/pull/464/files
https://raw.githubusercontent.com/bleachbit/bleachbit/9eff8901b64841b841092a927913ddd5d4ed99df/cleaners/internet_explorer.xml

**Comment by Tobias-B-Besemer** [comment]
Here is my latest version - try this file:
https://raw.githubusercontent.com/bleachbit/bleachbit/02bf3603deb4b92fec34e1ef2450f5b04f237f53/cleaners/internet_explorer.xml

**Comment by Tobias-B-Besemer** [comment]
New version:
https://raw.githubusercontent.com/bleachbit/bleachbit/603ff8ca3b6d417fd8cc64826883d23b317e4448/cleaners/internet_explorer.xml

**Comment by PiotrMP006** [comment]
Hi

The BleachBit does not scan the path "C:\Documents and Settings\Piotr\Ustawienia lokalne\Temporary Internet Files\Content.IE5\" !!!!
The BleachBit does not see the hidden folder Temporary Internet Files\Content.IE5\*

**Comment by PiotrMP006** [comment]
Hi

The BleachBit does not scan the path "C:\Documents and Settings\Piotr\Ustawienia lokalne\Temporary Internet Files\Content.IE5\" !!!!
The BleachBit does not see the hidden folder Temporary Internet Files\Content.IE5\*

**Comment by PiotrMP006** [comment]
I found the reason for the error

The BleachBit can not find the path% USERPROFILE%\Local Settings in non-English versions of Windows XP.

The path in Polish Windows XP looks like this:
%USERPROFILE%\Ustawienia lokalne


The path must be read from the registry key:

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurentVersion\Explorer\User Shell Folders\Cache

Cache 	REG_EXPAND_SZ 	%USERPROFILE%\Local Settings\Temporary Internet Files

When you change the link to the "Polish Local Settings -> Ustawienia lokalne" script, "internet_explorer.xml" works perfectly.

    <action command="delete" search="walk.files" path="%APPDATA%\Microsoft\Windows\IETldCache\"/>
    <action command="delete" search="walk.files" path="%USERPROFILE%\AppData\Local\Microsoft\Windows\Temporary Internet Files\"/>
    <action command="delete" search="walk.files" path="%USERPROFILE%\Ustawienia lokalne\Temporary Internet Files\"/>
    <action command="delete" search="walk.files" path="%LOCALAPPDATA%\Microsoft\Feeds Cache\"/>
    
;)

You have to add options to read the "Cache" variable from the registry and convert it into the program's memory.

![bleachbit_v2 1_ie8_erro3](https://user-images.githubusercontent.com/39049428/54026937-ea6b0b00-419f-11e9-88f8-3491121e94f4.png)

**Comment by az0** [comment]
@PiotrMP006  Great troubleshooting! Dziękuję!

**Comment by PiotrMP006** [comment]
Will the error be corrected in version 2.1?

2.4 :(

**Comment by az0** [comment]
I agree this is important, but it has been 13 months since a full release of BleachBit (2.0), so I'd like to not delay it any more with development and testing. Perhaps this can be fixed soon afterwards, and then it will be available immediately at http://ci.bleachbit.org/ . In other words, you won't have to wait until the final release of 2.4. Also please keep in mind the odd releases (2.1 and 2.3) are beta releases.

**Comment by PiotrMP006** [comment]
Automatic translation of the folder path address is easy to write.

You do not need to change any scripts. The path conversion will be changed by the script in .py

**Comment by Tobias-B-Besemer** [comment]
Please read: https://blogs.msdn.microsoft.com/oldnewthing/20031103-00/?p=41973/

@az0, fixing this would be "Windows XP (only [local]) Support" and I thought you will drop "Windows XP Support"... (???)

@PiotrMP006, Windows XP is really old and a long time EOF from Microsoft... Have you considered to by a new PC ???

**Comment by Tobias-B-Besemer** [comment]
@PiotrMP006, can you give me/us a complete list of your environment variables?

You can do the following to archive this:
> To get a list of system variables, open a command window (Start->Run: cmd)
> and type "set".

**Comment by Tobias-B-Besemer** [comment]
I really wonder that BleachBit is translated to ~60 languages and no one recognized this before...

...but indeed this seems to be a "(Only) Windows XP Local Bug"...
https://www.winhelponline.com/blog/add-localappdata-environment-variable-in-windows-xp/

**Comment by Tobias-B-Besemer** [comment]
IMHO the easiest fix will be to add some local support to the cleaners... I done this now for IE...
@PiotrMP006, can you test this cleaner I attach?
https://raw.githubusercontent.com/bleachbit/bleachbit/3ea8009ea409f96d9e9a879e01facd7b6fe80a64/cleaners/internet_explorer.xml

**Comment by PiotrMP006** [comment]
Hi
The last version

https://raw.githubusercontent.com/bleachbit/bleachbit/3ea8009ea409f96d9e9a879e01facd7b6fe80a64/cleaners/internet_explorer.xml

 works perfectly !!! :)

You still need to improve one file:

miro.xml
-----------------------------
    <action command="delete" search="file" path="$USERPROFILE\Local Settings\Temp\Miro-downloader.log"/>
    <action command="delete" search="file" path="$USERPROFILE\Local Settings\Temp\Miro.log"/>
    <action command="delete" search="file" path="$USERPROFILE\Local Settings\Temp\Miro.log.1"/>
    <action command="delete" search="file" path="$USERPROFILE\Local Settings\Temp\Miro_Download_Daemon_a.txt"/>
-----------------------------

**Comment by Tobias-B-Besemer** [comment]
Will do that! Just give me some time for it...

**Comment by Tobias-B-Besemer** [comment]
Here is a new miro.xml:
https://raw.githubusercontent.com/bleachbit/bleachbit/d4499e67362b4a101ce1403207b74d20cfc7dd6f/cleaners/miro.xml

Please give us a feedback if it works!

**Comment by PiotrMP006** [comment]
Works perfectly !!! :)

but there is a problem with the winapp2.ini file.

Only the converter in the program can solve the problem.

**Comment by Tobias-B-Besemer** [comment]
No! If you tell me with which cleaner in WinApp2.ini do you have problems, then I write you a CleanerML file with Polish support! ;-)

**Comment by az0** [comment]
This is fixed by merging the changes from @Tobias-B-Besemer

**Comment by az0** [comment]
If you want, you could re-test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

**Comment by Tobias-B-Besemer** [comment]
@PiotrMP006, we have released the BB3.0 cleaners only for e.g. WinXP users.
You can find the download here: https://www.bleachbit.org/download/old
