### ISSUE TITLE
Make ability to disable some startup apps and ability to uninstall apps and browser addons

### ISSUE THREAD

**Issue by mobtechpd** [bleachbit/bleachbit#479]
Make ability to disable some startup apps and ability to uninstall apps and browser addons

and i will say goodbye to ccleaner

**Comment by az0** [comment]
Thanks for the idea.

This request would fit better as three wishlist items over here: https://github.com/az0/wishlist

Each tool (start ups, uninstall apps, uninstall browser addons) is a non-trivial effort.
