### ISSUE TITLE
BB should in options dialog only re-scan cleaners when "close" gets pressed

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#482]
BB should in options dialog only re-scan cleaners when "close" gets pressed - others it's interrupt the user to long, app hangs, user gets confused.

**Comment by az0** [comment]
Is this the same as https://github.com/bleachbit/wishlist/issues/40 ?

**Comment by Tobias-B-Besemer** [comment]
Yeah, seems so! Maybe I didn't found my old one because he was in the wishlist? IDK!

**Comment by Tobias-B-Besemer** [comment]
No, new one is in the wishlist...
