### ISSUE TITLE
Glitch: BB calls its name 2 times

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#500]
Just a glitch: If you run BleachBit with `bleachbit_console.exe --gui --debug-log=bleachbit.log`, it calls its name 2 times. See screenshot.

![2019-03-19 08_57_54-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/54616025-5af70f00-4a5f-11e9-9678-1e63ca52a55d.jpg)

**Comment by az0** [comment]
Fixed
