### ISSUE TITLE
CLI: (German) translation incomplete - strings missing?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#509]
At CLI, the (German) translation is incomplete - are there strings missing?

![2019-03-26 04_57_02-Administrator_ C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/11881073/54970869-37aef100-4f84-11e9-8406-b4d93a77f9d1.jpg)

**Comment by az0** [comment]
Here is how to translate: https://www.bleachbit.org/contribute/translate

And the actual translation page: https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/

**Comment by Tobias-B-Besemer** [comment]
Andrew, I will try to have a look on it... You can assign me, if you like...

**Comment by Tobias-B-Besemer** [comment]
As far as I can see it, is "Usage:" and "Options:" part of OptionParser and can't be translated.
Also: "optparse" is deprecated since version 2.7 and should be replaced by "argparse".
https://docs.python.org/2/library/optparse.html
https://docs.python.org/2/library/argparse.html

**Comment by Tobias-B-Besemer** [comment]
@az0: https://docs.python.org/2/library/argparse.html#upgrading-optparse-code

**Comment by Tobias-B-Besemer** [comment]
https://stackoverflow.com/questions/22951442/how-to-make-pythons-argparse-generate-non-english-text

**Comment by Tobias-B-Besemer** [comment]
@az0 do you recognized my comments ??? Do you will fix it ??? Can you re-open this issue ???

**Comment by az0** [comment]
You are asking about the change from optparse to argparse? I agree it is best to change to argparse, but I don't have capacity to do it now. I'd like to save this change after changing from Python 2 to Python 3. That won't soon, and it is difficult to manage so many open issues, I'd like to keep this closed.

**Comment by Tobias-B-Besemer** [comment]
K, was just because the CLI can't be full translated with optparse...

**Comment by az0** [comment]
Yes, that is bad, but I need time soon for some big, important changes that are long overdue.

**Comment by Tobias-B-Besemer** [comment]
K
