### ISSUE TITLE
Update error message for timeout during update check

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#510]
I got an timeout by the version check and a "not so nice" error message to it.

![2019-03-25 17_14_35-BleachBit](https://user-images.githubusercontent.com/11881073/54970916-6a58e980-4f84-11e9-80f2-32a0149d42b7.jpg)

**Comment by az0** [comment]
Is the error about the timeout itself or about the message? Please keep each issue ticket focus on one issue. This me helps manage them.

**Comment by Tobias-B-Besemer** [comment]
Normally the version check should work, right? It's just a timeout, right? So I would improve it with a GTK+ Message.

**Comment by az0** [comment]
Yes, normally it should work. 

A timeout could be caused by many things: the user's computer, update server, and the networks in between.

**Comment by az0** [comment]
Changes
- Removed traceback
- Removed URL

![Screenshot-error checking](https://user-images.githubusercontent.com/933680/56430198-d62c2a80-6282-11e9-8e39-78c72aa12214.png)

**Comment by Tobias-B-Besemer** [comment]
Thx! :-)
