### ISSUE TITLE
"Shred Paths from Clipboard" not translated into German (strings missing?)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#515]
"Shred Paths from Clipboard" not translated into German (strings missing?)

![2019-03-26 06_01_05-Missing strings 'Cancel', 'Delete'   'Close' in translation files · Issue #429 ·](https://user-images.githubusercontent.com/11881073/54972641-c3c51680-4f8c-11e9-9cda-0cb68a605ae3.jpg)

I can do some German translation work, if needed...

**Comment by az0** [comment]
Here is how to translate: https://www.bleachbit.org/contribute/translate

And the actual translation page: https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/

**Comment by Tobias-B-Besemer** [comment]
Andrew, I will try to have a look on it... You can assign me, if you like...

**Comment by Tobias-B-Besemer** [comment]
It's already translated! Seems the last changes to the German translation didn't get checked in...

**Comment by Tobias-B-Besemer** [comment]
OK, I'm not at 100%-1line: #521 ^^
