### ISSUE TITLE
GtkWarning: inner_clipboard_window_procedure: assertion 'success' failed

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#516]
GtkWarning: inner_clipboard_window_procedure: assertion 'success' failed

![2019-03-26 14_55_16-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui](https://user-images.githubusercontent.com/11881073/55002999-cac54680-4fd7-11e9-8077-295c2c313161.jpg)

**Comment by az0** [comment]
I don't have capacity to look at this soon, and the next major thing is to replace GTK+ v2 with v3. If this happens with GTK+ v3, then open an issue
