### ISSUE TITLE
bleachbit.nsi should have multi-language support

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#524]
IMHO, bleachbit.nsi should have multi-language support.

**Comment by az0** [comment]
I am not sure what you mean. There is a section starting on line 120 that loads translations for many languages

https://github.com/bleachbit/bleachbit/blob/master/windows/bleachbit.nsi#L118

**Comment by Tobias-B-Besemer** [comment]
And what does then line 121 ???
https://github.com/bleachbit/bleachbit/blob/e181c85c52bcb00926c312667793bed535934e18/windows/bleachbit.nsi#L121

**Comment by Tobias-B-Besemer** [comment]
All msgs hardcoded in bleachbit.nsi aren't translated (at least into German). E.g.:
https://github.com/bleachbit/bleachbit/blob/e181c85c52bcb00926c312667793bed535934e18/windows/bleachbit.nsi#L301

**Comment by Tobias-B-Besemer** [comment]
> And what does then line 121 ???
> 
> [bleachbit/windows/bleachbit.nsi](https://github.com/bleachbit/bleachbit/blob/e181c85c52bcb00926c312667793bed535934e18/windows/bleachbit.nsi#L121)
> 
> Line 121 in [e181c85](/bleachbit/bleachbit/commit/e181c85c52bcb00926c312667793bed535934e18)
>  !ifndef NoTranslations

Ah, I get it! The script if for the english-only installer, too. ... ^^

Anyway: The hardcoded part should be done with variables...

**Comment by Tobias-B-Besemer** [comment]
If translation is done, this can be fixed, too:
https://github.com/bleachbit/bleachbit/blob/e181c85c52bcb00926c312667793bed535934e18/windows/bleachbit.nsi#L272

Think I read before that this was requested, too.

**Comment by az0** [comment]
Yes, there is a system to disable all NSIS translations to build a Windows-only installer.

I agree the whole NSIS installer should be enhanced for translations. Ideally the translations would be integrated with Launchpad the way several other translation systems already are (Python code, CleanerML, and bleachbit.desktop), so translators need only to translate in one system (i.e., Launchpad).

However, I don't have capacity to do this soon. To make it more efficient for me to manage the issues that I can address, I would like to close this issue.

I would welcome a pull request to fix this, especially if it were a robust system that integrated with  `bleachbit.pot`, which I upload to Launchpad.

**Comment by Tobias-B-Besemer** [comment]
I can try to do it like in NsisMultiUserLang.nsh...
https://raw.githubusercontent.com/bleachbit/bleachbit/master/windows/NsisInclude/NsisMultiUserLang.nsh

**Comment by az0** [comment]
That's half-way to the ideal scenario because it would be translated but not integrated with bleachbit.pot/Launchpad, though the second part could come later.

How about starting with a single string? If this works well, then do the rest.

By the way, maybe you saw this documentation https://nsis.sourceforge.io/Reference/LangString

**Comment by Tobias-B-Besemer** [comment]
Thx 4 feedback!

The file have just two strings and the string for the explorer context menu, as far as I saw it...

**Comment by Tobias-B-Besemer** [comment]
> I would welcome a pull request to fix this, especially if it were a robust system that integrated with `bleachbit.pot`, which I upload to Launchpad.

@az0, I can't find `bleachbit.pot`... :-/

**Comment by az0** [comment]
The `po/makefile`  automatically generates `bleachbit.pot` from two other .pot files, one of which is generated from Python code. Look in the Makefile for more information, and if does not make sense, let me know.

**Comment by az0** [comment]
FYI: The next release has much better translation support for strings in NSIS (Windows installer)
