### ISSUE TITLE
Keep getting time out error by update check in BB2.2

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#525]
I keep getting the time out error by update check (for WinApp2.ini?) in BleachBit v2.2.

![2019-03-31 03_21_07-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/55283470-710ca580-5364-11e9-88bd-f3efcaa8583f.jpg)

**Comment by az0** [comment]
The same system checks for new BleachBit releases and for Winapp2.ini updates. 

Do you have security, firewall, or antivirus software that might be blocking the network connection?

**Comment by Tobias-B-Besemer** [comment]
No special security, firewall, or antivirus software.

Do you have changed something to it in the latest builds ??? Didn't get that before v2.2 official...

**Comment by az0** [comment]
There was a major change in the update check system from BleachBit version 1.8 to 2.0, but not much changed in the update system from version 2.0 to 2.2.

I am not sure what's wrong. I just tried it, and the update system works for me. Perhaps for troubleshoooting you can test with another computer, another network, another operating system (Linux), or temporarily downgrade to BleachBit version 2 (using the portable version).

**Comment by Tobias-B-Besemer** [comment]
K, as long it effects just me, I can life with it (on this machine)...
