### ISSUE TITLE
sf.net suggests for download BB1.11.3

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#526]
sf.net suggests for download BleachBit-1.11.3-setup.exe.

AFAIK gets "the latest" upload auto-detected by sf.net and suggested to the user...
I had the experience that this doesn't work if you e.g. sync with GitHub...
Solution: Upload the latest EXE again to sf.net...

**Comment by az0** [comment]
The binaries at SF are always one version behind because I use SF now as a historical archive, and I'd like people to come to www.bleachbit.org to get the binaries.  Version 1.11 is old, so I pointed SourceForge to suggest version 2.0. 

Thanks!
