### ISSUE TITLE
could you make a flatpak for bleachbit?

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#530]
Hi, I really appreciate your work , is a very good application

could you make a flatpak for bleachbit?
in this way, users can install the application in any linux distribution

https://flatpak.org/
please , thank you.

**Comment by Tobias-B-Besemer** [comment]
IMHO a duplicate of issue #342.

**Comment by az0** [comment]
Looks ok

**Comment by mkhon** [comment]
See #851

However flatpak seems to be not feasible as the app is run in a sandboxed environment and does not have full access to the host filesystem (not mentioning root access) - only user home cleaning seems to be working properly.

**Comment by soredake** [comment]
> However flatpak seems to be not feasible as the app is run in a sandboxed environment and does not have full access to the host filesystem (not mentioning root access) - only user home cleaning seems to be working properly.

https://flathub.org/apps/details/org.worldpossible.ScriptLauncher is an example of app that can run root script on host while being flatpak'ed.

**Comment by az0** [comment]
Completed https://github.com/bleachbit/bleachbit/issues/632
