### ISSUE TITLE
Encoding issue? Non-english chars don't display e.g. 'åäö'

### ISSUE THREAD

**Issue by Jon-guy30** [bleachbit/bleachbit#533]
So I changed the "National settings" in the control panel in Windows briefly to US settings, and then I changed it back to the default. Now when bleachbit encounters characters such as "åäö" (Swedish vowels) it's replaced by the "Encoding error", you know the square "?" symbol. 

It's a cosmetic issue but it bothers me, I want it to display them correctly again, like it used to. 

I reinstalled it with Swedish language, clean installed it (removed bleachbit from appdata folder), reinstalled it again with English language, then I saw there was an ini file in appdata, but I don't think it would do anything.  

I hope you don't mind me asking, I don't know how to fix this. 

EDIT: Bleachbit portable works fine, those special characters are displayed correctly there.

EDIT 2: How odd. When I preview files to be deleted in the application itself it displays correctly. But when I do it through the context menu it shows the replacement character. 

Uuuuuuuuuh.

**Comment by az0** [comment]
So it fails only when using the Context Menu, right? It works correctly when it is installed or portable, as long as you don't use the context menu?

**Comment by Jon-guy30** [comment]
Correct. I have a second computer which is a laptop where I recently reinstalled Windows on, it has the same issue.

**Comment by az0** [comment]
@Jon-guy30 
I have a contractor working on a fix for this and related issues. When the fix is ready, would you be willing to test it and let us know?

**Comment by az0** [comment]
@Jon-guy30 

Would you please test a potential fix from here: [build 2.3.1148](https://ci.appveyor.com/project/az0/bleachbit/builds/26073328/artifacts) ? The fix is not yet merged, so it won't be in other builds for now, so please use this link for 2.3.1148.

**Comment by az0** [comment]
@Jon-guy30 I'm hoping you can test the fix. Let me know

**Comment by Tobias-B-Besemer** [comment]
@az0, as far as I understand it, this issue should be fixed... So close this issue, now ???

**Comment by az0** [comment]
@Tobias-B-Besemer 
OK, I am closing for lack of response. I assume this was fixed in 3.0.
