### ISSUE TITLE
[Issue] The category description automatically scrolls down

### ISSUE THREAD

**Issue by libalis** [bleachbit/bleachbit#550]
## Issue
If you start Bleachbit the first thing I see is Chromiums Info Page scrolled down.
It does not look good and I think it is not intended.
This is the case for all Categories which are to "long".
So it is the same case with Google Chrome on my system.
## Example
![Bildschirmfoto von 2019-04-27 23-43-45](https://user-images.githubusercontent.com/45124869/56855380-861a2b80-6946-11e9-9379-f31a378ca14d.png)
## Ending
Thank you so much for adressing this issue in advance and keep up the great work!

**Comment by az0** [comment]
OK, so you want it just to scroll to the top?

**Comment by libalis** [comment]
I think it would look much more professional if it would not scroll at all.
It should just stay at the top so if the user wants to read more, he can just scroll down on his own.
This would also fix the weird broken animation bar at the bottom.
Sorry if that sounded too ruff, but I would really appreciate that change.
And thank you so much for even caring.

**Comment by az0** [comment]
Fixed.

**Comment by az0** [comment]
You could test the fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
