### ISSUE TITLE
[Issue] Missing menu

### ISSUE THREAD

**Issue by libalis** [bleachbit/bleachbit#551]
## Issue
The application does not seem to have a Hamburger Menu or a depriciated AppMenu.
So there is no possibility to sew the amazing author or change the settings after the first start.
Therefore I think you should add a GNOME hamburger menu with a settings and an about button below.
## Example
![Bildschirmfoto von 2019-04-27 23-55-29](https://user-images.githubusercontent.com/45124869/56855510-6c79e380-6948-11e9-8187-8f97431f45b5.png)
## Ending
Thank you so much for adressing this issue in advance and keep up the great work!

**Comment by az0** [comment]
In the screenshot I see a terminal, file browser, and web browser, but I don't see the BleachBit window. Maybe you could crop or highlight it to point it out to me.

Here's a video of a recent version showing the menu working on Ubuntu
https://www.youtube.com/watch?v=kWM4-7X5_1g

On Windows 10 the menu works a bit differently (not shown in the video). It's another icon to the left of the preview button.

**Comment by libalis** [comment]
Thats the thing: the GNOME guidlines have changed in the terminal the new Hamurger Menu is shown and I don't know why, but the AppMenu used in the Video was broken on my systen (couldn't see it).
In GNOME/GTK 3 devs oppinion the applications schould use such a hamburger menu on the right.
This would fix the windows/linux diversity too.
Sorry for my indistinctness.

**Comment by az0** [comment]
Which version of GNOME do you have? I did not have the problem with Ubuntu 18.10 (GNOME 3.30): the menu appeared at the top of the GNOME Shell (by the clock), but now when I upgraded to Ubuntu 19.04 (GNOME 3.32), the menu entries are missing.

**Comment by az0** [comment]
Fixed in cb2a4f0. Here is a screenshot on Ubuntu 19.04 with GTK 3.24.8

![Screenshot from 2019-06-05 21-40-01](https://user-images.githubusercontent.com/933680/59005424-b1602800-87da-11e9-8211-e71cccbc9d42.png)

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
