### ISSUE TITLE
Microsoft Visual C++ Runtime Error when checking running processes

### ISSUE THREAD

**Issue by DEHughes** [bleachbit/bleachbit#557]
Bleachbit V2.2 (plus earlier versions)

Microsoft Visual C++ Rutime Error!
Program D:\BleachBit\bleachbit.exe
This application has requested the Runtime to terminate it in an unusual way.  Please contact the application's team for more information

This happens for VLC media player, Firefox (no problem with Firefox/Mozilla), Google Chrome (both)

Windows 10 pro 64 bit version 1809

**Comment by plgs** [comment]
Same for me with new install v2.2 (on Win10 pro v1809), attempting a free space wipe only.  Using the debug console version I get:

![image](https://user-images.githubusercontent.com/1505344/58924764-8220cb00-8788-11e9-8aa7-07d308a6b9b9.png)

and in the debug console:

![image](https://user-images.githubusercontent.com/1505344/58924800-a2e92080-8788-11e9-968f-43e8449d8331.png)

**Comment by az0** [comment]
To both: try reinstalling the Visual C++ 2008  (9.0) runtime 32-bit (required by Python 2.7.16). I think it's this download: [vcredist_x86.exe](https://www.microsoft.com/en-us/download/details.aspx?id=26368).

To both: which antivirus/security software do you have? Does this happen if it is temporarily disabled or put into game mode? Before trying this, be sure the application is digitially signed with my name Andrew Ziem. 

@DEHughes How far does BleachBit get before crashing? For example, does its normal window open? Are you able to click anything?

**Comment by DEHughes** [comment]
It runs fine if no VLC items are checked.  With them checked, it runs for a few seconds after I click clean and then crashes.  Same with/without Vipre antivirus enabled.

I have Visual C++ 2008 9.0.21022 & 9.0.30729.6161, 32 and 64 bit.

**Comment by DEHughes** [comment]
No change after updating 208 C++ or after removing older version.

**Comment by az0** [comment]
@DEHughes  You mentioned VLC. Do you mean the native VLC cleaner, which has only one option (MRU), or do you mean the Winapp2.ini VLC cleaner?

Does it happen with only VLC checked? Does it happen with both preview mode and cleaning mode?

If you mean the native cleaner, please try any of these native cleaners: Adobe Apythoncrobat, Chromium, Firefox, Google Chrome, pythonLibreOffice or Waterfox. Like VLC, they all check whether a process (executable) is running.

**Comment by DEHughes** [comment]
Native VLC.
Only in cleaning mode.
This happens for VLC media player, Firefox (no problem with Firefox/Mozilla), Google Chrome (both)
I do not have Adobe, Apythoncrobat, pythonLibreOfffice, or Waterfox

**Comment by az0** [comment]
This seems to be related to BleachBit's function for checking whether an application is running. I will check into it

**Comment by az0** [comment]
@DEHughes  Do you have Python (separately from BleachBit) installed on your system?

**Comment by DEHughes** [comment]
No.

-- 
Don Hughes
DHughes@DxLHughes.email
PH: +1 914 997 0911
WhatsApp: +19143098497
Los Cabezos, Boquete, Panama

Date sent:	Wed, 26 Jun 2019 20:22:32 -0700

**Comment by az0** [comment]
Would you please mind testing [CI Build 2.3.1233](https://ci.appveyor.com/project/az0/bleachbit/builds/26711687) or newer? (The build will show up in a few minutes.) A few days ago I put in a fix related to psutils, which is the system used to check for running processes, so it might help. It was causing a DLL load error on other systems.

**Comment by az0** [comment]
@DEHughes  Are you able to test? Build [1241](https://ci.bleachbit.org/?prefix=dl/2.3.1241/) has the fix too.

**Comment by az0** [comment]
I am closing for lack of response, and also I fixed a related issue

**Comment by az0** [comment]
You could test [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta). Let me know how it goes

**Comment by DEHughes** [comment]
I have been meaning to report this for some time.  When running bleachbit on a Linux 
platform with no GUI you get the following:

***@***.***:sbin >
***@***.***:sbin > bleachbit
(bleachbit:15512): Gdk-CRITICAL **: 12:45:25.615: gdk_screen_get_root_window: assertion 
'GDK_IS_SCREEN (screen)' failed
(bleachbit:15512): Gtk-WARNING **: 12:45:25.620: cannot open display:

The selected cleaner does run, but the messages are mildly annoying.


-- 
Don Hughes
***@***.***
PH: +1 914 997 0911
WhatsApp: +19143098497

**Comment by az0** [comment]
@DEHughes  
That is not related to issue 557, which is about the Microsoft Visual C++ runtime error, so please open a new issue ticket. This will make it easier to manage the issue.
