### ISSUE TITLE
Crash on startup (ValueError when using Chocolately)

### ISSUE THREAD

**Issue by notdexterslab** [bleachbit/bleachbit#560]
Running Windows 10 Home version 1809.
Crashes on startup (normal or as admin) and presents error message pointing to log file.
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3225081/bleachbit.exe.log)

**Comment by az0** [comment]
1. Which version of BleachBit is this?
2. Can you think of any application that would have modified BleachBit's configuration in the file `%AppData%\BleachBit\BleachBit.ini`?
3. Go to the folder `%AppData%\BleachBit` and rename `BleachBit.ini` to another name. Then start BleachBit. It should work. If you need more detailed instructions, let me know.
 
If #3 works, please send me the .ini file. To attach it here, zip it first. Alternatively, you could email it to me directly

**Comment by notdexterslab** [comment]
v2.2.0.20190520
I install and update Bleachbit through its [Chocolatey package](https://chocolatey.org/packages/bleachbit), so that could possibly cause an issue.
Renaming the .ini file worked, the program now opens correctly.

I've attached both .ini files in a zip file, the old one starts with an "_".
[BleachBit.zip](https://github.com/bleachbit/bleachbit/files/3237535/BleachBit.zip)

**Comment by az0** [comment]
The configuration was clearly mangled, and I assume that Chocoately somehow corrupted it. I made a change to detect the corruption and then reset the configuration.

**Comment by az0** [comment]
@notdexterslab 

I am not sure this has to do with Chocolately.

Are you using BleachBit in English, or is BleachBit translated?

**Comment by notdexterslab** [comment]
I included the mention of Chocolately just in case it had something to do with the issue.

I'm using the English BleachBit.

**Comment by az0** [comment]
I haven't been able to reproduce the cause of the corruption, but you could test the workaround in  the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta). A few users reported this, and not all used Chocolately
