### ISSUE TITLE
PyPI sdists

### ISSUE THREAD

**Issue by jayvdb** [bleachbit/bleachbit#561]
Would it be possible to upload sdists to PyPI.

This reserves the name on PyPI, preventing any funny business caused by someone else registering it, and also integrates better with distro packaging.  I am currently looking at packaging this for openSUSE.

**Comment by az0** [comment]
@jayvdb I think of PyPI as a place to find Python packages to use import from Python applications, but I see there are some end-user applications too.

Tell me more about the better integration with distro packinag. Do you maintain packages for OpenSUSE? It seems to me the distro packaging system works OK without this.

**Comment by jayvdb** [comment]
openSUSE has a Python 2 package, under utilities
https://build.opensuse.org/package/show/utilities/c

I maintain a variety of packages https://build.opensuse.org/user/show/jayvdb , but I am more usually a contributor of new Python packages to openSUSE ; ones in progress usually at https://build.opensuse.org/project/show/home:jayvdb:py-new

I would like to move the bleachbit package to be a more traditional Python package, but for that we need a PyPI reserved name.  See naming policy at

https://en.opensuse.org/openSUSE:Packaging_Python

Then it would look more like https://build.opensuse.org/package/show/devel:languages:python/python-yamllint , but with some extra bits to handle the translations, menu items, etc.

That will allow building a Python 2/3 package, and also allows it to be more easily used as a library as well as a utility.  And the Python area has more maintainers and tools to support it, as those packages have a more standardised and automate-able structure.

**Comment by az0** [comment]
I've had discussions with Michael who has helped maintain BleachBit for openSUSE, and it is working OK. We no longer need a Python 2/3 package, and I haven't heard demand for use as a library. If I notice a problem, I will reconsider for now, it seems PyPI is not a big priority
