### ISSUE TITLE
Minor errors in Windows 10, 1089 and BB 2.2

### ISSUE THREAD

**Issue by ineuw** [bleachbit/bleachbit#563]
These 4 errors are repeatable. I just thought it should be reported, even though they don't affect me
[bleachbit system information.txt](https://github.com/bleachbit/bleachbit/files/3253819/bleachbit.system.information.txt)
.
1Error: system.tmp: Command to delete C:\Users\ineuw\AppData\Local\Temp\_MEI86482\resources\fonts
2 Error: system.tmp: Command to delete C:\Users\ineuw\AppData\Local\Temp\_MEI86482\resources
3 Error: system.tmp: Command to delete C:\Users\ineuw\AppData\Local\Temp\_MEI86482
4 Error: system.tmp: Command to delete C:\Windows\temp\_avast_

Attached is the system info.

**Comment by az0** [comment]
Would you please run [BleachBit Debugging Terminal](https://docs.bleachbit.org/doc/troubleshooting.html)? This will open a black window that might have more information. If there is a multi-line message that starts like `Traceback (most recent call last)`, then please paste it here.

**Comment by ineuw** [comment]
[Bleachbit activity.txt](https://github.com/bleachbit/bleachbit/files/3255959/Bleachbit.activity.txt)
[bleachbit.log](https://github.com/bleachbit/bleachbit/files/3255960/bleachbit.log)

**Comment by az0** [comment]
Why installed in AppData? BleachBit 2.2 allows installation system-wide or for current user, and it seems you chose current user.

As for the error, I think it's the same as https://github.com/bleachbit/bleachbit/issues/508 . It was fixed. If you want to test the fix, please try any version from https://ci.bleachbit.org/ . Let me know.

**Comment by ineuw** [comment]
Between the last time, 19 days ago, when I reported the issue and now, I was using BB 2.1 with no errors, Removed this completely and fresh installed 2.2, for everyone, even though I am the only account on the desktop.

It still came up with four errors: 
3 times Error: system.tmp: Command to delete C:\Users\ineuw\AppData\Local\Temp\_MEI87562
1 time Error: system.tmp: Command to delete C:\Windows\temp\_avast_

I only wanted to let you know in case it helps, I am fine with the "errors" and I can always install 2.1
 

[bleachbit.log](https://github.com/bleachbit/bleachbit/files/3319809/bleachbit.log)

**Comment by az0** [comment]
@ineuw Have you had this same problem in BleachBit 3.0?

**Comment by ineuw** [comment]
Thanks for checking. Just now installed it on Windows 10 Home laptop and it
runs fine without problems. Next I am installing it in Desktop Linux Mint
19.2 and will let you know the results.

ineuw

**Comment by ineuw** [comment]
Just used BB 3.0 in Linux Mint 19.2 and it works well. No problems.

https://www.bleachbit.org/download/file/t?file=bleachbit_3.0_all_ubuntu1804.deb
On this download site it cannot be downloaded, only installed fro the web.
I prefer to have a copy of the software but I don't know where is the
package download page. To be honest, you have too many webpages for
downloading and also outdated versions. Can't this be simplified?

ineuw

**Comment by az0** [comment]
Thanks for testing, @ineuw 

In my browser (Google Chrome), the default action on the download page is to download the .deb package. If this isn't working for you, you can try direct access to the download site https://download.bleachbit.org/bleachbit_3.0_all_ubuntu1804.deb

**Comment by ineuw** [comment]
You're most welcome.

My comment about the webpages that there should be a single main download page, and all other pages where download is mentioned, should point to it and not offer their own downloads.
