### ISSUE TITLE
Chrome Downloads Not Cleaned

### ISSUE THREAD

**Issue by JLuke2600** [bleachbit/bleachbit#565]
Google Chrome, Version 74. BleachBit 2.2.

Google Chrome downloads list/history (Ctrl + J) is not being cleaned, where every Google Chrome option is selected to be cleaned in BleachBit, and everything else (as far as I can tell) is being cleaned successfully.

I'm experiencing this issue on multiple machines.

Edit: Windows 10

**Comment by az0** [comment]
I confirm on Google Chrome 75.0.3770.80 64-bit on Windows 10. I enabled all Google Chrome options

**Comment by az0** [comment]
Would you please check something?

1. Go t the directory `C:\Users\(your username)\AppData\Local\Google\Chrome\User Data\Default`
2. Is there a file called `000018.ldb`?
3. Do you have other `*.ldb` files?

If these steps do not make sense, let me know.

**Comment by Crunch2600** [comment]
Hi, I don't have a file called 000018.ldb in that directory you mentioned, but I do have it in "C:\Users\(my username)\AppData\Local\Google\Chrome\User Data\Default\Session Storage".

In "C:\Users\John-Luke\AppData\Local\Google\Chrome\User Data\Default", I have the following: 

000923.ldb
001065.ldb
001078.ldb

**Comment by Crunch2600** [comment]
Hi, I don't have a file called 000018.ldb in that directory you mentioned, but I do have it in "C:\Users\(my username)\AppData\Local\Google\Chrome\User Data\Default\Session Storage".

In "C:\Users\(my username)\AppData\Local\Google\Chrome\User Data\Default", I have the following: 

000923.ldb
001065.ldb
001078.ldb

**Comment by az0** [comment]
@Crunch2600 

You mentioned three .ldb files. With Google Chrome closed, please delete them or move them to another directory. Then run BleachBit to clean the download history. Then check whether it came back.

What I'm seeing on my machine is there are two copies of the download history: the old SQLite location plus the new LevelDB (.ldb) location.

**Comment by az0** [comment]
The history stills shows (CTRL+J) with Google Chrome 80 as of latest BleachBit git revision 802baf3b840377c68c4827f23a84da945065466d.

**Comment by rados** [comment]
@az0 I can take care of this one.

**Comment by rados** [comment]
@JLuke2600, @az0 
Hey guys, what I've found till now is that if I have a non ascii symbol in my bookmarks I receive this trace back while deleting history and this prevents the deletion of the download history. In Special.py-> get_chrome_bookmark_urls we have "with open(path, 'r') as f:" in version 4.0.0 tag but in the current code it is fixed like "with open(path, 'r', encoding='utf-8') as f:". So could you try the latest build and see if the problem persists?

Error: google_chrome.history: Function: Clean file: C:\Users\hp\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1538: character maps to <undefined>

**Comment by abitrolly** [comment]
@rados are you saying that the latest version of BB successfully cleans Chrome Downloads history?

**Comment by rados** [comment]
@abitrolly
With the latest source code - yes, just double checked it.

**Comment by abitrolly** [comment]
https://github.com/bleachbit/bleachbit/pull/1062 fixed that for you. Let's @JLuke2600 finds the time to report with newer BleachBit. I don't have Windows to replicate the setup.

**Comment by rados** [comment]
@abitrolly 
You know, while tracing it some time ago I noticed that under my Ubuntu some strange things happened - on some of the tries the download history was cleaned, on some partially cleaned or not cleaned at all, but I didn't systematize those observations. You can check also if you have the time...

**Comment by abitrolly** [comment]
@rados I bet that Linux users who care about privacy are not using Chrome. ) I can check with Chromium on Fedora if nobody responds in a few days, but that still won't be sufficient to close this ticket.

**Comment by az0** [comment]
I tested this with the latest Git revision (e5076cf63ef0535fa4d629565580d6a08710c15f), and it works fine on Ubuntu and Windows with Google Chrome 87. @JLuke2600  hasn't responded in a month, but it seems to be fixed based on the other info.

@rados @abitrolly thank you

**Comment by az0** [comment]
>  in the current code it is fixed like `with open(path, 'r', encoding='utf-8') as f`:

Fixed by PR https://github.com/bleachbit/bleachbit/pull/951
