### ISSUE TITLE
Error when enabling options that show a pop-up warning

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#567]
Windows 8 SL 64 bit
Run bleachbit.exe as administrator. Impossible to mark many points. Here is what can be marked.
<a href='https://postimg.cc/1fMdCNz2' target='_blank'><img src='https://i.postimg.cc/1fMdCNz2/1.png' border='0' alt='1'/></a>
<a href='https://postimg.cc/8jT3mbTL' target='_blank'><img src='https://i.postimg.cc/8jT3mbTL/2.png' border='0' alt='2'/></a>
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3317252/bleachbit.exe.log)
[BleachBit.ini.txt](https://github.com/bleachbit/bleachbit/files/3317253/BleachBit.ini.txt)

**Comment by az0** [comment]
Under Firefox, are you able to check any of the individual options except for password? From the error attached, it seems you would get the error when (1) choosing Passwords under Firefox and (2) when choosing everything under Firefox

**Comment by az0** [comment]
In BleachBit click the menu and then **Diagnostics**. Please copy that and paste it here. If you would like, you can skip all the rows that refer to directories. I am looking for information about your language settings and operating system.

**Comment by ediowar** [comment]
invalid UTF-8
<a href='https://postimg.cc/5jHxJnwb' target='_blank'><img src='https://i.postimg.cc/5jHxJnwb/invalid-UTF-8.png' border='0' alt='invalid-UTF-8'/></a>
BleachBit version 2.3
Git revision d660bbad
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
locale.getdefaultlocale = ('ru_RU', 'cp1251')
platform.win32_ver[1]() = 6.2.9200
platform.platform = Windows-8-6.2.9200-SP0
platform.version = 6.2.9200
sys.version = 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True

**Comment by ediowar** [comment]
Took screenshots when choosing everything.

**Comment by az0** [comment]
@ediowar I have a contractor working on a fix for this and related issues. When the fix is ready, would you be willing to test it and let us know?

**Comment by az0** [comment]
@ediowar 


Would you please test a potential fix from here: [build 2.3.1148](https://ci.appveyor.com/project/az0/bleachbit/builds/26073328/artifacts) ? The fix is not yet merged, so it won't be in other builds for now, so please use this link for 2.3.1148.

**Comment by ediowar** [comment]
Good work.
There is an error: Ошибка во время выполнения операции 'firefox': 'cannot import name _common' and Invalid UTF-8
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3411807/bleachbit.exe.log)
![Invalid UTF-8_2](https://user-images.githubusercontent.com/44164186/61548998-a7774900-aa57-11e9-8e34-e7e40a1d90fb.png)

**Comment by az0** [comment]
@ediowar 
The contractor developed another build: [2.3.1190](https://ci.appveyor.com/project/az0/bleachbit/builds/26428439/artifacts). Would you please test it? Please make sure it's 2.3.1190 because other builds (even newer builds) don't have this fix.

**Comment by ediowar** [comment]
Invalid UTF-8 fixed. Still errors:
Ошибка во время выполнения операции 'firefox': 'cannot import name _common'
Ошибка во время выполнения операции 'windows_explorer': ''ascii' codec can't encode characters in position 55-65: ordinal not in range(128)'
Ошибка во время выполнения операции 'skype': 'cannot import name _common'

**Comment by az0** [comment]
@ediowar Thanks so much for testing! Would you please test again with [build 2.3.1206](https://ci.appveyor.com/project/az0/bleachbit/builds/26541062/artifacts)?

**Comment by ediowar** [comment]
Ошибка во время выполнения операции 'firefox': 'cannot import name _common'
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3481672/bleachbit.exe.log)

**Comment by az0** [comment]
@ediowar  The log is helpful to determine where there error is coming from. Do you have Python installed on your system (besides the Python that comes with BleachBit)?

**Comment by ediowar** [comment]
No, Python is not installed. If necessary, I will install

**Comment by az0** [comment]
@ediowar No, it's not necessary. I am wondering why the psutil DLL is failing to load. Someone recently reported the  same issue, and he had Python installed, so it seemed like a DLL conflict.

The original issue is fixed, so would you please open a new GitHub ticket for the DLL issue?
