### ISSUE TITLE
Installed GTK themes for Pidgin on Windows, now BleachBit is affected

### ISSUE THREAD

**Issue by RoseTheFlower** [bleachbit/bleachbit#568]
How do I switch back to the default Windows-like theme? There are no signs of anything GTK-related on the list of installed software.

**Comment by az0** [comment]
Which BleachBit version do you have?

BleachBit on Windows ships with a private GTK+ installed under BleachBit's folder, so that's odd that Pidgin would affect it.

**Comment by RoseTheFlower** [comment]
Version 2.2. I don't think the GTK themes were for Pidgin only, but they also were never copied to the BleachBit folder.

**Comment by az0** [comment]
Try this

1. Find the directory where `bleachbit.exe` is
2. Edit `etc/gtk-3.0/settings.ini`
3. Add this line for the default theme `gtk-theme-name = Adwaita`
4. Save the file and close it

**Comment by RoseTheFlower** [comment]
gtk-2.0 is the only GTK-related folder in etc. There's no settings file inside.

**Comment by az0** [comment]
Sorry, that was for BleachBit verison 2.3, not 2.2.

Did you use [Example 1 here](https://developer.pidgin.im/wiki/ThemingPidgin) to install Pidgin themes? If so, does the preferences tool affect both Pidgin and BleachBit?

In the `gtk-2.0` directory is a filed called `gtkrc` which sets the theme. You can edit it with Notepad. The default includes the following lines. Are you able to check yours?

```
gtk-theme-name = "MS-Windows"
gtk-icon-theme-name = "Tango"
````

**Comment by RoseTheFlower** [comment]
Those are the strings inside the file.
Resetting or changing the theme in the Pidgin program gtk2_prefs.exe did sort it out though.

**Comment by az0** [comment]
Ok, so I will close the issue because you fixed the theme
