### ISSUE TITLE
[Linux] Thunderbird cache is in a different path

### ISSUE THREAD

**Issue by pitsi** [bleachbit/bleachbit#569]
As seen in lines 28 to 37 in cleaners/thunderbird.xml, bleachbit looks for thunderbird's (tb for short) cache somewhere inside ~/.thunderbird/, depending on the distro.
Nowadays, with tb 60+, the cache is in
`~/.cache/thunderbird/????????.default/cache2`
where "????????.default" is the profile name, so please update where it is needed.

Checked on debian, arch, ubuntu, mint, solus and gentoo (my installation and friends') and I have no way to check it on windows, so I can not verify if the problem exists there too.

On top of the above, it seems that bleachbit cleans only what is inside the default profile (????????.default) for tb, ommiting the others. E.g. if my tb profile is "12345678.pitsi", it will be ommited by bleachbit. 

So please fix it.
Thank you in advance

**Comment by az0** [comment]
@pitsi  

I might be able to squeeze this in before the next release. If I provide you with a new `thunderbird.xml` file, would you be able to replace the file on your system and test it soon?

**Comment by pitsi** [comment]
Soon as in? I am on vacations that started today and will end next Sunday, September 1st.

**Comment by pitsi** [comment]
Where can I find the new and patched thunderbird.xml file? The one inside the cleaners folder is 5 months old.

**Comment by az0** [comment]
New XML is here: https://github.com/bleachbit/bleachbit/blob/master/cleaners/thunderbird.xml

To use it, just drop in the new file. It requires BleachBit version 2.2 or later because it uses multi-value variables, a newer feature.

**Comment by pitsi** [comment]
Why did you close my issue report, since I did not verify it works?

Anyway, it does not work. Every single file inside ~/.cache/thunderbird/????????.default/cache2 is still there. Here is the output of ncdu as proof

```
ncdu 1.13 ~ Use the arrow keys to navigate, press ? for help                    
--- /home/moi/.cache/thunderbird/qomn9ph6.default ------------------------------
                         /..                                                    
   20.5 MiB [##########] /cache2
    3.4 MiB [#         ] /startupCache
    8.0 KiB [          ] /safebrowsing
```

Inside cache2 lies another folder, named entries. Clearing the cache through thunderbird (tools > clear recent history > select "everithing" on the top and "cache" from the drop down menu) deletes the contents of that folder. 

Please reopen it.

**Comment by az0** [comment]
@pitsi Are you running BleachBit as root? If so, try running it as a normal user.

**Comment by pitsi** [comment]
Obviously not. I am on linux for the last 12 years, I know what I am doing.

Here is the output from the terminal, when running only the cache cleaner for tb
```
$ bleachbit -c thunderbird.cache
Disk space recovered: 0
Files deleted: 0
```
And here is the output of ncdu on the cache2 folder
```
ncdu 1.13 ~ Use the arrow keys to navigate, press ? for help                    
--- /home/moi/.cache/thunderbird/qomn9ph6.default/cache2 -----------------------
                         /..
  224.0 KiB [##########] /entries                                               
e   4.0 KiB [          ] /doomed
    4.0 KiB [          ]  index.log
    4.0 KiB [          ]  index

```
The entries folder is small in size because I cleaned it up last time through tb's settings for my example and it has not accumulated much stuff since.

**Comment by az0** [comment]
Would you please run `bleachbit --sysinfo` and send me the results?

**Comment by pitsi** [comment]
There you go
https://pastebin.com/iZTSsge6

The username was changed to xxx for security reasons and the paste will be available for 1 month.

**Comment by az0** [comment]
I tested the new `thunderbird.xml` with your version BleachBit version 2.2 (Git revision 4e1f2717), and it worked for me.

Which one of these did you do? (Or something else?)
1. Put the new `thunderbird.xml` in `/usr/share/bleachbit/cleaners`
1. Delete `/usr/share/bleachbit/cleaners/thunderbird.xml` and put the new one in `/home/xxx/.config/bleachbit/cleaners`

**Comment by pitsi** [comment]
I put the new thunderbird.xml file in /home/xxx/.config/bleachbit/cleaners. Just that. Isn't the newer file supposed to override the old one inside /usr/share/bleachbit/cleaners/? I will delete the old one if needed and I will check again.

After putting the file in /home/xxx/.config/bleachbit/cleaners, bleachbit asked me to achnowledge that a new cleaner file was installed, so I thought it would use this one instead of the old one.

---edit
Long story short, the cleaner seems to be working properly now
```
$ bleachbit -c thunderbird.cache
Delete 3.5MB /home/xxx/.cache/thunderbird/qomn9ph6.default/startupCache/startupCache.8.little
Delete 4.1kB /home/xxx/.cache/thunderbird/qomn9ph6.default/safebrowsing/google4
Delete 4.1kB /home/xxx/.cache/thunderbird/qomn9ph6.default/cache2/entries/980C94CFDB701BED199E571B6F114539C082FB00
...
,,,
,,,
Delete 4.1kB /home/xxx/.cache/thunderbird/qomn9ph6.default
Disk space recovered: 4.3MB
Files deleted: 72
```
Issue closed and thanks for your work. It would be be a lot better though if the presence of a new cleaner file made the old one to be ignored, so please consider implementing that behaviour in bleachbit executable.

p.s. It would also be nice that the cleaner would not delete the entire profile folder, as seen on the last line.
`Delete 4.1kB /home/xxx/.cache/thunderbird/qomn9ph6.default`
