### ISSUE TITLE
[Feature request] Stop Scan Button

### ISSUE THREAD

**Issue by shellaaaron** [bleachbit/bleachbit#571]
No way to stop scan once start it, it would be better if there is a stop button.

**Comment by az0** [comment]
Until this is implemented, you can safely abort BleachBit by clicking the "X" to close the application window.

**Comment by az0** [comment]
Fixed in Git commit 60eb46d333397daa720e2ed4e20b6b247255ee35

If you are on Windows, you can test CI build 2.3.1135 or later from https://ci.bleachbit.org

**Comment by az0** [comment]
You could test the fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
