### ISSUE TITLE
BleachBit deletes bluetooth folder ~/.cache/obexd on linux

### ISSUE THREAD

**Issue by iromeister** [bleachbit/bleachbit#572]
The linux bluetooth daemon obexd uses the folder ~/.cache/obexd for transferring files. This folder gets deleted by BleachBit by default and has to be manually recreated each time.

Workaround: Add the folder to the whitelist in bleachbit.ini with the following lines:

[whitelist/paths]
0_type = folder
0_path = /home/[your username]/.cache/obexd

This had been fixed in 2.0 but got reintroduced, see launchpad https://bugs.launchpad.net/bleachbit/+bug/1700767

**Comment by az0** [comment]
Thanks. I'll check into it

**Comment by az0** [comment]
I tried, but I am not able to reproduce this. Could you please help answer a few questions?

1. When you do not add the extra whitelist and you do have this problem, are you cleaning using the option "cache" under the "system" category?

2. Which version of Linux do you use? (Example: Ubuntu 19.04)

3. Did you install BleachBit from the Linux distribution's repository or from https://www.bleachbit.org/ ?

4. In the BleachBit menu, please open up "diagnostics." Please copy either all the lines and paste them here---_or_ the first line plus all the "sys" lines and "platform" lines

**Comment by iromeister** [comment]
@az0 
1. yes, I'm cleaning using the option "cache" under the "system" category
2. Gentoo amd64
3. I installed from the repository, https://packages.gentoo.org/packages/sys-apps/bleachbit
4. here you go:

BleachBit version 2.2
GTK+ version 2.24.32
SQLite version 3.28.0
FSE = UTF-8
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/stardust/.config/bleachbit
personal_cleaners_dir = /home/stardust/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('de_DE', 'UTF-8')
os.getenv('DESKTOP_SESSION') = /usr/share/xsessions/plasma
os.getenv('LOGNAME') = stardust
os.getenv('USER') = stardust
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/stardust
platform.linux_distribution() = ('Gentoo Base System', '2.6', '')
platform.platform = Linux-4.19.52-gentoo-x86_64-Intel-R-_Core-TM-_i5-3230M_CPU_@_2.60GHz-with-gentoo-2.6
platform.version = #1 SMP Fri Jun 21 19:49:04 CEST 2019
sys.argv = ['/usr/lib/python-exec/python2.7/bleachbit']
sys.executable = /usr/bin/python2.7
sys.version = 2.7.15 (default, Sep 17 2018, 12:40:54) 
[GCC 7.3.0]
__file__ = /usr/lib64/python2.7/site-packages/bleachbit/Diagnostic.pyc

I'm not using any personal cleaners.

btw, I did a diff between `ls ~/.cache/` before and after running BleachBit:
1,7d0
< babl
< chromium
< filezilla
< fontconfig
< gegl-0.4
< gstreamer-1.0
< icon-cache.kcache
39,46d31
< kio_http
< krunner
< ksmserver-logout-greeter
< ksplashqml
< ksycoca5_de_8_khySRD8XU5hxCO3c0CJrO9oUI=
< kwin
< mc
< mesa_shader_cache
48,58d32
< obexd
< plasmashell
< plasma-svgelements-default_v5.56
< plasma_theme_default_v5.56.kcache
< qt_compose_cache_little_endian_1e702e1359df72e66ba81e27536d49a5
< qtshadercache
< spectacle
< systemsettings
< thumbnails
< thunderbird
< zoom

You clearly see obexd in there.

**Comment by az0** [comment]
Any chance obexd was empty during the test? Could you please make sure there is something in in it before running the test? A preview is fine because BleachBit's whitelist affects the preview too.

There are other directories in the cache that should be whitelisted. Would you please try making one of these, put anything in it, and try the preview?
````
~/.cache/wallapaper/
~/.cache/evolution/
~/.cache/ibus/
````

**Comment by iromeister** [comment]
@az0, the directory is empty most of the time, as it is only used during actual file transfers. Still it has to be there in the first place for bluetooth file transfers to work.
Anyway, the exclusion of it worked in v2.0, so what changed in v2.2?

**Comment by az0** [comment]
@iromeister  I see the issue now. Thanks

**Comment by az0** [comment]
It's fixed, and I improved the unit tests to cover the scenario of an empty obexd directory.

You can get the fix various ways, including

1. Apply the patch for the commit
2. Get the latest BleachBit from Git
3. Wait for the next release

**Comment by iromeister** [comment]
Thanks - I'm trying to apply the patch to the source of v2.2 but it fails (the Cleaner.py part, TestCleaner.py works). Probably Cleaner.py has changed since release 2.2?!

**Comment by az0** [comment]
How about this?  It's just a few characters difference

1. Find the text `~/.cache/obexd/`
2. Change it to `~/.cache/obexd($|/)`

**Comment by iromeister** [comment]
Hmm, still struggling with the diff/patch syntax. Now I managed to create a working patch myself:

--- a/bleachbit/Cleaner.py      2019-03-20 03:37:10.000000000 +0100
+++ b/bleachbit/Cleaner.py      2019-07-31 14:38:12.461548886 +0200
@@ -639,15 +639,16 @@
             '^/var/tmp/kdecache-',
             '^' + expanduser('~/.cache/wallpaper/'),
             # Clean Firefox cache from Firefox cleaner (LP#1295826)
-            '^' + expanduser('~/.cache/mozilla'),
+            '^' + expanduser('~/.cache/mozilla/'),
             # Clean Google Chrome cache from Google Chrome cleaner (LP#656104)
-            '^' + expanduser('~/.cache/google-chrome'),
+            '^' + expanduser('~/.cache/google-chrome/'),
             '^' + expanduser('~/.cache/gnome-control-center/'),
             # iBus Pinyin
             # https://bugs.launchpad.net/bleachbit/+bug/1538919
             '^' + expanduser('~/.cache/ibus/'),
-            # Linux Bluetooth daemon obexd
-            '^' + expanduser('~/.cache/obexd/')]
+            # Linux Bluetooth daemon obexd directory is typically empty, so be careful
+            # not to delete the empty directory.
+            '^' + expanduser('~/.cache/obexd($|/)')]
         for regex in regexes:
             self.regexes_compiled.append(re.compile(regex))

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta). No need to make a patch :)
