### ISSUE TITLE
Error cleaning ~/.cache/doc/by-app FUSE mount point related to Flatpak

### ISSUE THREAD

**Issue by Ub3rZ4cH** [bleachbit/bleachbit#573]
Using 2.3 running from source from git clone.
Username was omitted. 

> Error: system.cache: Command to delete /home//.cache/doc/by-app
> Traceback (most recent call last):
>   File "/home//bleachbit/bleachbit/Worker.py", line 83, in execute
>     for ret in cmd.execute(self.really_delete):
>   File "/home//bleachbit/bleachbit/Command.py", line 84, in execute
>     FileUtilities.delete(self.path, self.shred)
>   File "/home//bleachbit/bleachbit/FileUtilities.py", line 265, in delete
>     os.rmdir(delpath)
> OSError: [Errno 38] Function not implemented: '/home//.cache/doc/by-app'
> Error: system.cache: Command to delete /home//.cache/doc
> Traceback (most recent call last):
>   File "/home//bleachbit/bleachbit/Worker.py", line 83, in execute
>     for ret in cmd.execute(self.really_delete):
>   File "/home//bleachbit/bleachbit/Command.py", line 84, in execute
>     FileUtilities.delete(self.path, self.shred)
>   File "/home//bleachbit/bleachbit/FileUtilities.py", line 265, in delete
>     os.rmdir(delpath)
> OSError: [Errno 16] Device or resource busy: '/home//.cache/doc'

**Comment by az0** [comment]
Do you know if `~/.cache/doc/by-app` and `~/.cache/doc` are normal objects? Do you know which application made them? 

Could you please run the `stat` command on them?

**Comment by Ub3rZ4cH** [comment]
`~/cache/doc/by-app` doesn't exist so either never did exist or has been removed now. However running `~/cache/doc` I get...

>@pc:~$ sudo stat ~/.cache/doc
  File: /home//.cache/doc
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 801h/2049d      Inode: 2121742     Links: 2
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2019-07-01 17:47:41.919775870 +0100
Modify: 2019-07-01 17:47:41.919775870 +0100
Change: 2019-07-01 17:47:41.919775870 +0100
 Birth: -

**Comment by az0** [comment]
Same issue here
https://www.bleachbit.org/forum/error-execution-command-delete-rootcachedocby-app

It seems this is a special FUSE object for Flatpak
https://www.thegeekdiary.com/rm-cannot-remove-doc-by-app-function-not-implemented-centos-rhel-7/

I'll look into a solution

**Comment by az0** [comment]
The fix was pushed to Git. You can test it various ways, including

1. Update to the latest Git version (see: [run from source](https://docs.bleachbit.org/dev/running-from-source-code.html))
2. Just replace `FileUtilities.py` with the latest version
3. Wait for the next beta or final release

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

**Comment by Ub3rZ4cH** [comment]
I can confirm I now longer get this issue, with the latest git version build from source :)

**Comment by az0** [comment]
@Ub3rZ4cH  Thanks for confirming
