### ISSUE TITLE
Bleachbit crashes (OSError: [Errno 1])

### ISSUE THREAD

**Issue by WPFilmmaker** [bleachbit/bleachbit#574]
I don't know what causes the crash and I don't think it has been reported before.
When I start BB from terminal I get this when it crashes:
------------------------------------------------------------------------------------
OSError: [Errno 1] Operation not permitted: '/var/lib/apt/lists/ppa.launchpad.net_jfi_ppa_ubuntu_dists_xenial_InRelease'
Error: apt.package_lists: Command to delete /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-i386_Packages
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 286, in delete
    wipe_contents(path)
  File "/usr/share/bleachbit/FileUtilities.py", line 699, in wipe_contents
    f = wipe_write()
  File "/usr/share/bleachbit/FileUtilities.py", line 651, in wipe_write
    os.chmod(path, 0o200)  # user write only

Any idea?

I am on Lubuntu 16.04.3 BB 2.2 (and not ran as administrator).

**Comment by az0** [comment]
By crash, you mean the BleachBit application window closes prematurely?

Please try experimenting with disabling some check boxes. Try disabling all the APT related checkboxes. The error message suggests BleachBit is trying to delete a system file, but it does not have permissions to do so. Do not wipe APT unless you are running with root/administrator permissions.

Let me know

**Comment by az0** [comment]
@WPFilmmaker Have you had a chance to try my suggestions?

**Comment by az0** [comment]
Closing because no response since July. If you have more info about the same issue, please reopen this same ticket.
