### ISSUE TITLE
This 'for' statement has a redundant 'else' as no 'break' is present in the body.

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#578]
Problem report
https://lgtm.com/projects/g/bleachbit/bleachbit/rev/pr-59686d1e68928ad7338ec334ae943c837d790d72

Introduced here
https://github.com/bleachbit/bleachbit/pull/577

**Comment by XhmikosR** [comment]
@az0 have you thought about adding lgtm to the repo? I see many alerts https://lgtm.com/projects/g/bleachbit/bleachbit?mode=list

Not sure if you use another tool, but this should help a bit with code maintenance :)

Also, do note that lgtm is owned by GitHub and GitHub announced the successor to LGTM on this year's GitHub Satellite: https://githubsatellite.com/security/
