### ISSUE TITLE
Updates are failing without p80 outgoing?

### ISSUE THREAD

**Issue by asvc** [bleachbit/bleachbit#579]
BleachBit v2.2, installed via "chocolatey"
Windows 10 Pro, 10.0.18362 Build 18362

Looking at https://github.com/bleachbit/bleachbit/blob/2f7f3ac0fd471b971e76da7ab345904dcd3d51e9/bleachbit/__init__.py#L341
It should be possible to update with the firewall allowing outgoing connections on 443 only, however this seems to be not the case.

Here is the _working_ rule in "Windows Defender Firewall", removing port 80 prevents BleachBit from updating:
![image](https://user-images.githubusercontent.com/300146/61204106-8fd45380-a72b-11e9-9053-689d704dd6e0.png)

**Comment by az0** [comment]
Please wait an hour or so for the caches to clear, and then try again. Let me know how it goes

**Comment by az0** [comment]
@asvc  Have you had a chance to test the fix?

It's a server side fix, so you don't need to download a new version of the application

**Comment by asvc** [comment]
Works/looks fine:
![image](https://user-images.githubusercontent.com/300146/61432247-ee3d4400-a96e-11e9-877c-5532a4a33561.png)
