### ISSUE TITLE
Bleachbit won't run - Errors occurred Window - See the logfile ...bleachbit.exe.log for details

### ISSUE THREAD

**Issue by cnaxw1** [bleachbit/bleachbit#580]
When I try to run Bleachbit 2.2 on Windows 10 64-bit (use to work fine in past), I get a windows titled "Errors occurred". The message says: See the logfile 'C:\Program Files (x86)\BleachBit\bleachbit.exe.log' for details. When I open the log file, listed below are the contents. How do I fix this problem?

Traceback (most recent call last):
  File "bleachbit\Options.pyo", line 192, in get_tree
  File "ConfigParser.pyo", line 370, in getboolean
ValueError: Not a boolean: ['True']
Traceback (most recent call last):
  File "bleachbit.py", line 49, in <module>
  File "bleachbit\CLI.pyo", line 246, in process_cmd_line
  File "bleachbit\GUI.pyo", line 920, in __init__
  File "bleachbit\GUI.pyo", line 850, in create_window
  File "bleachbit\GUI.pyo", line 487, in create_operations_box
  File "bleachbit\GUI.pyo", line 71, in __init__
  File "bleachbit\GUI.pyo", line 101, in refresh_rows
  File "bleachbit\Options.pyo", line 130, in get
  File "ConfigParser.pyo", line 370, in getboolean
ValueError: Not a boolean: ['True']

**Comment by az0** [comment]
1. Do you use AVG or Avast antivirus?

2. Did you install BleachBit using Chocolately?

3. You mentioned it used to work. Do you know when was the last time it worked and the first time it failed?

**Comment by cnaxw1** [comment]
1. I do not use AVG or Avast antivirus. I use Malwarebytes. Nothing detected or in quarantine.

2. I downloaded the latest version from https://www.bleachbit.org/download/windows and picked "BleachBit installer .exe: best option for most people"

3. Yes, it use to work and I ran it about a month prior when it worked. I did not update or install a different version and when I tried it a few days ago, it gave the error I enclosed before. I then went to bleachbit.org and downloaded the latest version, did an uninstall and a reinstall, and the same error occurred.

**Comment by az0** [comment]
The symptom is that the `bleachbit.ini` configuration is corrupt, but I am not sure why. @cnaxw1 Do you know of any software you have that might modify its configuration?

I put in a workaround to automatically detect and delete corrupt configuration, so BleachBit will start. You can try it out with a recent [CI build](https://ci.bleachbit.org/). Alternatively, delete `%appdata%\bleachbit\bleachbit.ini`. Please me know how it goes.

Related issues: https://github.com/bleachbit/bleachbit/issues/378 , https://github.com/bleachbit/bleachbit/issues/562

**Comment by cnaxw1** [comment]
I am not sure what could have modified it's configuration other than CCleaner.  I downloaded the CI build and that solved my problem (in addition to deleting the bleachbit.ini file). Thanks. Bleachbit is working now.

**Comment by az0** [comment]
If you come across the `bleachbit.ini` file being corrupt again, let me know and send me a copy by attaching it here** or by private email. I'd like to research this more.

** To attach a .INI file to GitHub, you will need to either ZIP it or rename it to .TXT.

**Comment by az0** [comment]
I haven't been able to reproduce the corruption, but you could test the workaround in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta).
