### ISSUE TITLE
unit test error in test_locatization_paths

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#593]
Travis CI [Build #1428](https://travis-ci.org/bleachbit/bleachbit/builds/562407887) and many previous builds on Ubuntu Trusty succeeded
Travis CI [build #1433 ](https://travis-ci.org/bleachbit/bleachbit/builds/563368290)on Ubuntu Xenial failed

``` 
======================================================================
FAIL: test_localization_paths (tests.TestUnix.UnixTestCase)
Unit test for localization_paths()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/TestUnix.py", line 145, in test_localization_paths
    'This may be an error unless you really deleted all the files.')
AssertionError: Zero files deleted by localization cleaner. This may be an error unless you really deleted all the files.
```

**Comment by az0** [comment]
@tstenner 
I wonder if you please could have a chance to look at this soon? If not, I'll try

**Comment by tstenner** [comment]
Could it be that the new VMs run the build/tests without root permissions by default? If so, a simple `sudo` before the test invocation could fix this.

**Comment by az0** [comment]
@tstenner The new test on Travis Xenial is running as uid=2000 without sudo mode. I'm not sure what it was before, but when I run the test on my laptop with sudo, it still fails the same way. Also, it's not actually deleting anything. This test is just searching.
