### ISSUE TITLE
environment variables set with Unicode characters are corrupt

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#601]
Below are examples from the system information via GTK dialog. (It doesn't print in the console, which is another issue.)

This happened when the username included Unicode characters.

System: Windows 10.0.18362.145
Git revision: 23decebcf33192b52b4acee43c0d5be00f880e48

```
os.getenv('APPDATA') = C:\Users\meiða\AppData\Roaming
os.getenv('cd') = None
os.getenv('LocalAppData') = C:\Users\meiÃ°a\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\meiÃ°a\AppData\LocalLow
```

**Comment by DimitarTerzov** [comment]
Hi Andrew, I am Dimiter (rados's friend). I want to work on this issue. Regards.

**Comment by az0** [comment]
@DimitarTerzov  OK

**Comment by az0** [comment]
This was fixed along the way.

I tested Windows 10 and Python 3.4 with revision 788f28a91, and the environment variables printed correctly in both the GUI (diagnostics window) and console (`--sysinfo`).
