### ISSUE TITLE
DLL issue (see #567)?

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#604]
Windows 8 SL 64 bit
Ошибка во время выполнения операции 'firefox': 'cannot import name _common'
[bleachbit.exe.log](https://github.com/bleachbit/bleachbit/files/3481932/bleachbit.exe.log)

**Comment by az0** [comment]
I put in a fix in [build](https://ci.bleachbit.org) 2.3.1213 for a DLL conflict. It will take about five minutes to build. Then, would you please test?

**Comment by ediowar** [comment]
Good. No errors.
