### ISSUE TITLE
error when clicking checkboxes in tree view with Unicode characters

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#605]
When clicking any checkbox in the tree view (cleaning option) that has non-ASCII or its parent has non-ASCII, I get this traceback. Also, the state of the checkbox does not change.

This is the "log" branch in Git

Application is running in portable mode. Python is not installed.

```
Traceback (most recent call last):
  File "bleachbit\GUI.pyo", line 453, in col1_toggled_cb
  File "bleachbit\GUI.pyo", line 422, in set_cleaner
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

system
```
BleachBit version 2.3
Git revision ccfb0cdc
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
locale.getdefaultlocale = ('es_ES', 'cp1252')
platform.platform = Windows-10-10.0.18362
sys.version = 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
```

**Comment by az0** [comment]
_Not_ seen on same Windows 10 Spanish system on branch rados-ms1 (Git revision 54351574)

**Comment by mkhon** [comment]
Can not reproduce: Windows 10, Russian locale, latest master (~3.9.0)

**Comment by az0** [comment]
OK, let's call it fixed, then.
@mkhon  thanks for checking
