### ISSUE TITLE
Bleaching wipe out Quickling 

### ISSUE THREAD

**Issue by lutzd** [bleachbit/bleachbit#608]
Hallo,
not shure if a bug, but every time when bleaching, all my Quicklink inside taskbar is removed by wiper. I have no iddeea, which properties must be unchecked to protect quicklink on taskbar.
if bug, OK, if not pls tell me which radiobutton is to uncheck
many thanks for your extraordinary project
lutz

**Comment by az0** [comment]
@lutzd Do you have every option enabled?  When enabling options, watch for the pop-up warnings that look like this screenshot. Try disabling all options, and then re-enable them one at a time to read the warnings. Does this help?

![Screenshot from 2019-08-12 BleachBit warning](https://user-images.githubusercontent.com/933680/62900359-30139d00-bd17-11e9-9894-c9f30a3a8089.png)

**Comment by az0** [comment]
I am closing for lack of response. If you have more info about this and still have a problem, please reopen the same issue ticket.
