### ISSUE TITLE
Can not run bleachbit.py on Kubuntu 19.04

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [bleachbit/bleachbit#613]
I'm getting the following error:
ImportError: No module named scandir

![image](https://user-images.githubusercontent.com/38154154/63532567-98892800-c528-11e9-8d50-57a94e5b8657.png)

**Comment by az0** [comment]
Try this command
`sudo apt-get install python-scandir`

**Comment by Ashutosh-Kukreti** [comment]
I'm getting this error:

![image](https://user-images.githubusercontent.com/38154154/63609698-406c2780-c5f5-11e9-89f6-e33c03bd78b3.png)

**Comment by az0** [comment]
That's weird because it works for me on Ubuntu 19.04 (Disco).

How about `apt-cache search scandir` ?

**Comment by Ashutosh-Kukreti** [comment]
![image](https://user-images.githubusercontent.com/38154154/63611668-09e4db80-c5fa-11e9-9ead-10f206c89ba8.png)

**Comment by az0** [comment]
That looks like a contradiction, and it does not make sense. Maybe something is wrong with the APT configuration on your system.

In any case, I published commit 039500e5419baa5bfbe4042c3c26bb1bbcab7611 that will fall back to the slower os.walk() when scandir is not available.

**Comment by Ashutosh-Kukreti** [comment]
Thank you 😊

**Comment by az0** [comment]
You could test this fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
