### ISSUE TITLE
BB should have better/other EXE description

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#617]
IMHO BB should have better/other EXE description.

Description is ATM: "Free space and maintain privacy"

Here you see the actual description in the Resourcesmonitor:
![2019-05-04 16_13_48-Ressourcenmonitor](https://user-images.githubusercontent.com/11881073/63953349-7724c080-ca81-11e9-8c5b-90443d9db057.jpg)

The problem is, this description gets used by Windows e.g. when the task hangs, too.
Then you get a msg without BB, just with "Free space and maintain privacy".
This looks in German then like this:
![2019-08-11 05_04_07-BleachBit (Keine Rückmeldung)](https://user-images.githubusercontent.com/11881073/63953516-c2d76a00-ca81-11e9-8721-8f6babcbe9b2.png)

The normal use of the EXE description is on Windows normally, that at least the name of the prog gets repeated.
Here is a SS of the Task-Manager of my Testing-Machine with some samples how other progs use the description:
![2019-07-19 07_26_11-Windows Task-Manager](https://user-images.githubusercontent.com/11881073/63953682-147ff480-ca82-11e9-82c1-d0476048d2b1.jpg)

So possible solution would be e.g.:
BleachBit - Free space and maintain privacy
BleachBit - The Cleaner
BleachBit Cleaner
...
...something like that maybe...

**Comment by az0** [comment]
Please try version 3.0.1.1338

**Comment by az0** [comment]
Two options to try for anyone having this issue

[Build 2584](https://ci.bleachbit.org/?prefix=dl/4.6.1.2584-processname/). This is the latest version of BleachBit (4.6.x) using the old framework (Python 3.4, GTK 3.24).

[Build 2467](https://ci.bleachbit.org/?prefix=dl/4.4.2.2467-mkhon-python310/) uses the new framework (Python 3.10.7), but it has an old build date July 2023. This build has known issues, so it's just for testing, so I recommend portable (zip) over installer (exe).  Once ready, this will be BleachBit 5.0.

Each build may have an improved process name in a different way.

Google Chrome may show safety warnings for the site ci.bleachbit.org . This is a false positive, but they won't give me details on the issue.

For cross referencing, here are related issues:  https://github.com/bleachbit/bleachbit/issues/617 https://github.com/bleachbit/bleachbit/issues/1000 https://github.com/bleachbit/bleachbit/issues/1109 https://github.com/bleachbit/bleachbit/issues/1134 https://github.com/bleachbit/bleachbit/issues/1655
