### ISSUE TITLE
VIM Cleaner have a typo?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#625]
I guess the VIM Cleaner have a typo. Think this should be "Clipboard", not "Clipboead", or?

![2019-09-11 07_24_36-BleachBit](https://user-images.githubusercontent.com/11881073/64680383-f9e44d00-d47d-11e9-919d-13c5c04ed264.jpg)

**Comment by az0** [comment]
This is in the German translation, not the original English.

English:  "Swap files under user profile"
Translated and reviewed by Stephan Woidowski on 2019-05-27

https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/de/97/+translate

**Comment by Tobias-B-Besemer** [comment]
I have fixed this, ATM.
I have translated the missing 6 strings, too.
Can you re-import the German translation?
