### ISSUE TITLE
GUI glitches in Win7

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#626]
Think there are some GUI glitches in Win7.
- There's at the bottom (and at least in some cases on the top) a dashed line visible;
- The main menu button and buttons for minimize, maximize & close window are not always visible. (Don't know how it looks on Win10, but think at least the menu button should be visible as button.)

![2019-09-11 10_23_42-BleachBit](https://user-images.githubusercontent.com/11881073/64681078-55630a80-d47f-11e9-8fee-e437818c0a3d.jpg)

![2019-09-11 10_24_55-VIM Cleaner have a typo_ · Issue #625 · bleachbit_bleachbit](https://user-images.githubusercontent.com/11881073/64681096-5bf18200-d47f-11e9-875f-288b9f699272.jpg)

![2019-09-11 10_25_42-VIM Cleaner have a typo_ · Issue #625 · bleachbit_bleachbit](https://user-images.githubusercontent.com/11881073/64681102-601d9f80-d47f-11e9-8d3a-35b6ca6def9a.jpg)

**Comment by Tobias-B-Besemer** [comment]
Also: The Abort Button looks like pressed - don't know if this is intended.

**Comment by az0** [comment]
The Abort button looks weird because the setup script deletes its icon called `process-stop.{svg,png}`. I see this too.. I'll fix this.

Dashed line looks like an unused widget, maybe the progress bar, that needs to be hidden. I see this too. I'll fix this.

The application menu and min/max buttons on the title bar should be visible, and in the screenshot, they look visible to me.

**Comment by az0** [comment]
I figured out the dashed bar. It just means there are items there. When scrolled to the top, the bar shows on the bottom to show there are more items below. When scrolled to the bottom, the bar shows at the top. When scrolled in the middle, it shows on both sides.  This is a GTK 3 feature, not a bug. :)

I'll check into the Abort icon

**Comment by Tobias-B-Besemer** [comment]
BB SS of my system:
![2019-09-13 20_15_01-BleachBit](https://user-images.githubusercontent.com/11881073/64885226-d24ed980-d663-11e9-96c7-04236e6151f4.jpg)

**Comment by Tobias-B-Besemer** [comment]
Maybe the dashed lines can be hidden or replaced with a "^"-Bar ???

**Comment by az0** [comment]
Do you see a GTK option to hide or replace the bar in a ScrollWindow?

**Comment by Tobias-B-Besemer** [comment]
> Do you see a GTK option to hide or replace the bar in a ScrollWindow?

I'm nor a programmer in extended programming languages, nor into the possibilities of GTK. But the dashed line looks unusual for me, I never saw it in any GTK program and I think a overlay with a button should be possible. This would give the possibility to scroll the list with a press of the mouse too, if the button gets this functionality programmed.

**Comment by Tobias-B-Besemer** [comment]
Here seems to be the solution:
https://unix.stackexchange.com/questions/251743/dashed-line-on-top-and-below-a-window-when-window-scrolling-is-required

Looks simple to me, but haven't it tested, yet ...

**Comment by az0** [comment]
I expect that is how to remove the overlay scroll indicators. The next part is determining whether they are really so bad. They were good enough to include as a default in GTK, but bad enough for someone to to ask how to remove them. The stackexchange question doesn't look remarkably popular, so I am guessing most people either like them or don't mind. In any case, let's please treat this as a separate issue. It's hard to manage one issue ticket about multiple issues.

**Comment by Tobias-B-Besemer** [comment]
Think best is to let it for the moment as it is, but keep in mind there would be a solution, if someone else ask about the dashed lines, too.
