### ISSUE TITLE
Cannot install Bleachbit 2.3 on Linux

### ISSUE THREAD

**Issue by EGStein** [bleachbit/bleachbit#629]
So here's my install log, gentoo uses the python2 command for python 2.7 related stuff 

>  [ethan@ethangentoo bleachbit]$ sudo python2 setup.py install
> 
> Password: 
> running install
> running bdist_egg
> running egg_info
> writing bleachbit.egg-info/PKG-INFO
> writing top-level names to bleachbit.egg-info/top_level.txt
> writing dependency_links to bleachbit.egg-info/dependency_links.txt
> reading manifest template 'MANIFEST.in'
> warning: no files found matching 'MANIFEST'
> warning: no files found matching 'windows/setup_py2exe.bat'
> writing manifest file 'bleachbit.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> running build_py
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Special.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Winapp.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/GUI.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/RecognizeCleanerML.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/GuiPreferences.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/__init__.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/GuiChaff.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/GuiBasic.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Cleaner.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/WindowsWipe.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Diagnostic.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/CLI.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/CleanerML.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/DeepScan.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Options.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/General.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Unix.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Windows.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Command.py -> build/bdist.linux-x86_64/egg/bleachbit
> creating build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/splitters.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/text.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/__version__.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/__init__.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/chain.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/markovify/utils.py -> build/bdist.linux-x86_64/egg/bleachbit/markovify
> copying build/lib/bleachbit/Chaff.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Action.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Update.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Log.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/FileUtilities.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Memory.py -> build/bdist.linux-x86_64/egg/bleachbit
> copying build/lib/bleachbit/Worker.py -> build/bdist.linux-x86_64/egg/bleachbit
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Special.py to Special.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Winapp.py to Winapp.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/GUI.py to GUI.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/RecognizeCleanerML.py to RecognizeCleanerML.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/GuiPreferences.py to GuiPreferences.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/GuiChaff.py to GuiChaff.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/GuiBasic.py to GuiBasic.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Cleaner.py to Cleaner.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/WindowsWipe.py to WindowsWipe.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Diagnostic.py to Diagnostic.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/CLI.py to CLI.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/CleanerML.py to CleanerML.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/DeepScan.py to DeepScan.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Options.py to Options.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/General.py to General.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Unix.py to Unix.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Windows.py to Windows.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Command.py to Command.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/splitters.py to splitters.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/text.py to text.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/__version__.py to __version__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/__init__.py to __init__.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/chain.py to chain.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/markovify/utils.py to utils.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Chaff.py to Chaff.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Action.py to Action.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Update.py to Update.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Log.py to Log.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/FileUtilities.py to FileUtilities.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Memory.py to Memory.pyc
> byte-compiling build/bdist.linux-x86_64/egg/bleachbit/Worker.py to Worker.pyc
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying bleachbit.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying bleachbit.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying bleachbit.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying bleachbit.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> bleachbit.Diagnostic: module references __file__
> bleachbit.__init__: module references __file__
> creating 'dist/bleachbit-2.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing bleachbit-2.3-py2.7.egg
> removing '/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg' (and everything under it)
> creating /usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg
> Extracting bleachbit-2.3-py2.7.egg to /usr/lib64/python2.7/site-packages
> bleachbit 2.3 is already the active version in easy-install.pth
> 
> Installed /usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg
> Processing dependencies for bleachbit==2.3
> Finished processing dependencies for bleachbit==2.3
> [ethan@ethangentoo bleachbit]$ bleachbit
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 250, in do_startup
>     self.build_app_menu()
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 98, in build_app_menu
>     builder.add_from_file(bleachbit.app_menu_filename)
> gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/data/app-menu.ui”: No such file or directory (4)
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 284, in do_activate
>     application=self, title=APP_NAME, auto_exit=self._auto_exit)
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 466, in __init__
>     self.populate_window()
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 972, in populate_window
>     self.headerbar = self.create_headerbar()
>   File "/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/bleachbit/GUI.py", line 915, in create_headerbar
>     builder.add_from_file(bleachbit.app_menu_filename)
> gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/lib64/python2.7/site-packages/bleachbit-2.3-py2.7.egg/data/app-menu.ui”: No such file or directory (4)
>

**Comment by az0** [comment]
I know `setup.py` should now how to do the install, but currently it does not. Please try `sudo make install`, and let me know how it goes.

**Comment by EGStein** [comment]
Sorry for delayed response,  I had emergency appendectomy. This is what happens when I install via makefile and run "bleachbit".

> [ethan@ethangentoo bleachbit]$ sudo make install
> # "binary"
> mkdir -p /usr/local/bin
> install -m 644 bleachbit.py /usr/local/bin/bleachbit
> chmod 0755 /usr/local/bin/bleachbit
> # .desktop
> mkdir -p /usr/local/share/applications
> install -m 644 bleachbit.desktop /usr/local/share/applications/
> # .desktop
> mkdir -p /usr/local/share/appdata
> install -m 644 bleachbit.appdata.xml /usr/local/share/appdata/
> # Python code
> mkdir -p /usr/local/share/bleachbit
> install -m 644 bleachbit/*.py /usr/local/share/bleachbit
> cd /usr/local/share/bleachbit && \
> python -O -c "import compileall; compileall.compile_dir('.')" && \
> python -c "import compileall; compileall.compile_dir('.')"
> Listing '.'...
> Compiling './Action.py'...
> Compiling './CLI.py'...
> Compiling './Chaff.py'...
> Compiling './Cleaner.py'...
> Compiling './CleanerML.py'...
> ***   File "./CleanerML.py", line 53
>     mylist = list(set([x for x in os.getenv(v1), os.getenv(v2) if x]))
>                                                ^
> SyntaxError: invalid syntax
> 
> Compiling './Command.py'...
> Compiling './DeepScan.py'...
> Compiling './Diagnostic.py'...
> Compiling './FileUtilities.py'...
> Compiling './GUI.py'...
> Compiling './General.py'...
> Compiling './GuiBasic.py'...
> Compiling './GuiChaff.py'...
> Compiling './GuiPreferences.py'...
> Compiling './Log.py'...
> Compiling './Memory.py'...
> Compiling './Options.py'...
> Compiling './RecognizeCleanerML.py'...
> Compiling './Special.py'...
> Compiling './Unix.py'...
> Compiling './Update.py'...
> Compiling './Winapp.py'...
> Compiling './Windows.py'...
> Compiling './WindowsWipe.py'...
> Compiling './Worker.py'...
> Compiling './__init__.py'...
> Listing '.'...
> Compiling './Action.py'...
> Compiling './CLI.py'...
> Compiling './Chaff.py'...
> Compiling './Cleaner.py'...
> Compiling './CleanerML.py'...
> ***   File "./CleanerML.py", line 53
>     mylist = list(set([x for x in os.getenv(v1), os.getenv(v2) if x]))
>                                                ^
> SyntaxError: invalid syntax
> 
> Compiling './Command.py'...
> Compiling './DeepScan.py'...
> Compiling './Diagnostic.py'...
> Compiling './FileUtilities.py'...
> Compiling './GUI.py'...
> Compiling './General.py'...
> Compiling './GuiBasic.py'...
> Compiling './GuiChaff.py'...
> Compiling './GuiPreferences.py'...
> Compiling './Log.py'...
> Compiling './Memory.py'...
> Compiling './Options.py'...
> Compiling './RecognizeCleanerML.py'...
> Compiling './Special.py'...
> Compiling './Unix.py'...
> Compiling './Update.py'...
> Compiling './Winapp.py'...
> Compiling './Windows.py'...
> Compiling './WindowsWipe.py'...
> Compiling './Worker.py'...
> Compiling './__init__.py'...
> # cleaners
> mkdir -p /usr/local/share/bleachbit/cleaners
> install -m 644 cleaners/*.xml /usr/local/share/bleachbit/cleaners
> # icon
> mkdir -p /usr/local/share/pixmaps
> install -m 644 bleachbit.png /usr/local/share/pixmaps/
> # translations
> make -C po install DESTDIR=
> make[1]: Entering directory '/home/ethan/Git/bleachbit/po'
> echo "* Installing in /usr/share/locale"
> * Installing in /usr/share/locale
> for MO in hy.mo uk.mo pt.mo sk.mo lt.mo sq.mo se.mo id.mo sr.mo te.mo et.mo ru.mo fo.mo eo.mo ky.mo sl.mo hu.mo ku.mo pl.mo th.mo nl.mo uz.mo zh_TW.mo eu.mo bn.mo de.mo be.mo gl.mo fi.mo en_CA.mo bs.mo ms.mo es.mo cs.mo lv.mo ro.mo it.mo he.mo ja.mo ia.mo sv.mo pt_BR.mo el.mo ast.mo ko.mo si.mo nb.mo fr.mo my.mo nds.mo zh_CN.mo bg.mo ta.mo en_AU.mo fa.mo da.mo ca.mo tr.mo en_GB.mo hr.mo af.mo ar.mo vi.mo nn.mo ug.mo hi.mo; do \
> 	lang=`basename $MO .mo`; \
> 	DST=/usr/share/locale/$lang/LC_MESSAGES/; \
> 	mkdir -p $DST; \
> 	cp $MO $DST/bleachbit.mo; \
> done
> make[1]: Leaving directory '/home/ethan/Git/bleachbit/po'
> # PolicyKit
> mkdir -p /usr/local/share/polkit-1/actions
> install -m 644 org.bleachbit.policy /usr/local/share/polkit-1/actions/
> [ethan@ethangentoo bleachbit]$ bleachbit
> Traceback (most recent call last):
>   File "/usr/local/bin/bleachbit", line 38, in <module>
>     import bleachbit.GUI
> ImportError: No module named bleachbit.GUI
> [ethan@ethangentoo bleachbit]$ 
>

**Comment by az0** [comment]
Info you sent was helpful, so I made a change. Please grab the latest Git and try again.

Also, please note you can run from source with installing like this https://docs.bleachbit.org/dev/running-from-source-code.html

**Comment by az0** [comment]
Closing for no response in 14 days. If the change did not allow you to install, please reopen this ticket.

**Comment by az0** [comment]
On October 1 I made some improvements to the installation.  You could test [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta).
