### ISSUE TITLE
Add package for Flatpak

### ISSUE THREAD

**Issue by amrmsaraya** [bleachbit/bleachbit#632]
This application is a must have, if it has a flatpak support it would be awesome

**Comment by az0** [comment]
I am open to creating a Flatpak package downloadable from the bleachbit.org site, but I would rather not provide it through Flathub. I know that's inconvenient, but visits to the site provide revenue to support development of the project.

**Comment by az0** [comment]
By the way, I assume the original intent of the issue was to provide a Flatpak packager and not provide support for cleaning Flatpak.

**Comment by ubluish** [comment]
Yes, Actually that was my intention to provide a flatpak package

**Comment by zero77** [comment]
What about a snap package as well

**Comment by az0** [comment]
> What about a snap package as well

Please let's keep this issue about the original topic, Flatpak. There was some discussion earlier about snap here https://github.com/bleachbit/bleachbit/issues/342 . If you think the concerns there are resolved, maybe open a new issue dedicated to the topic

**Comment by dngray** [comment]
Seems this was also wish list feature https://github.com/bleachbit/wishlist/issues/101

**Comment by abitrolly** [comment]
@dngray it is better to open a separate issue for Flatpak cleanup.

**Comment by az0** [comment]
Based on the comment yesterday, I am closing this as completed.

As it is open source software, you are of course free to do distribute via Flathub, but I would be shooting myself (the project) in the foot if I were to encourage it (explained in comment at top).
