### ISSUE TITLE
Support for cleaning android-studio files

### ISSUE THREAD

**Issue by erlanger** [bleachbit/bleachbit#633]
Could you please add support for cleaning android-studio files? It does use a lot of space.

Thanks for such a great work!

**Comment by az0** [comment]
Have you considered making your own cleaner using [CleanerML](https://docs.bleachbit.org/cml/cleanerml.html)?

**Comment by erlanger** [comment]
Thanks, didn't know about it!

**Comment by Tobias-B-Besemer** [comment]
@erlanger, if you can't write a CleaneML file, you should provide more detailed info on what should be cleaned, that a other person can write the cleaner file.
So info about folders & files that should be cleaned are necessary... Best: Provide screenshots to prove it...

**Comment by Tobias-B-Besemer** [comment]
Btw.: I started a much more detailed doc about CleanerML. You can find it here, if you wanna have a look:
https://github.com/LV-Crew/bleachbit-docus/blob/CleanerML-v2.0-Docu/_posts/cleanerml_v2.0.md

When your cleaner file is finished, you can push it into the CleanerML repo under @az0 user, that it will finally included into BleachBit when it is stable & tested...

**Comment by erlanger** [comment]
Thanks!
