### ISSUE TITLE
unused cleaner 'vim' is not hidden

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#636]
[2.3.1292diagnostics.txt](https://github.com/bleachbit/bleachbit/files/3688487/2.3.1292diagnostics.txt)

**Comment by ediowar** [comment]
After unchecking "Download and update community cleanup templates (winapp2.ini)" and applying "Reset settings and exit", community cleanup templates (winapp2.ini) remain.

**Comment by Tobias-B-Besemer** [comment]
For me too on Windows!
Just didn't found the time to analyze and report...

**Comment by Tobias-B-Besemer** [comment]
https://github.com/bleachbit/bleachbit/blob/master/cleaners/vim.xml

It's a Deep Scanner... Guess BB don't check at startup if the Cleaner is really needed because it would need to much time... A check if the prog exist on the system (EXE check in default location) is missing...

**Comment by az0** [comment]
@Tobias-B-Besemer  You are correct. In commit 6c3f40042e (April 2019), the deep scan was added to the VIM cleaner. When BleachBit sees that the cleaner has a deep scan option, it does not take the long time to verify there is anything to clean, so it will not auto-hide it. This behavior is normal, though I agree it would be nice if it could check whether VIM is installed. Currently there is not a way to do this.

For now, you can ignore VIM, or you can delete the `vim.xml` file.

**Comment by Tobias-B-Besemer** [comment]
@az0, I confused the "EXE is running" check with a "EXE exist" check... but think a "EXE exist" check would maybe be helpful for other cleaners, too... Think I was planning to suggest it for the "Vuze Case" too, but you solved it with speeding BB up... what is better!
A other solution would IMHO be, to move the deep scan to the deep system scanner, that it gets a general deep scanner like the one for MacOS files...
...workarounds would be to remove the VIM Scanner from this release or make the CleanerML file "Unix-like-Systems only" 'cause VIM is a rarly used prog on Windows and can maybe ne hidden there...

**Comment by az0** [comment]
I implemented Tobias's suggestion to move the options to `deepscan.xml`. In the future when CleanerML has an auto-hide option that works better for VIm with deep scan, I would move the VIM deepscan back to `vim.xml`

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta)
