### ISSUE TITLE
"Shred settings and quit" doesn't delete Winapp2.ini

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#637]
After unchecking "Download and update community cleanup templates (winapp2.ini)" and applying "Reset settings and exit", community cleanup templates (winapp2.ini) remain.

**Comment by az0** [comment]
I can confirm

My environment:
Git revision 7f3605d
Windows 10
BleachBit in portable mode

**Comment by mkhon** [comment]
This happens because portable currently removes only bleachbit.ini
