### ISSUE TITLE
The option "Check for new beta versions" does not work

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#638]
Portable build 2.3.1291 for Windows.

**Comment by az0** [comment]
When you write "does not work," do you mean it is impossible to check the option? Or do you mean you see an error message? Or do you mean you checked it, but you never get an alert of a new beta version?

**Comment by ediowar** [comment]
I checked it, but never get an alert of a new beta version.

**Comment by az0** [comment]
Last beta version was in February
https://www.bleachbit.org/news/bleachbit-21-beta

Next one will be soon

**Comment by ediowar** [comment]
I thought beta versions is unstable builds https://ci.bleachbit.org/
How about adding option "Check for new unstable versions"?

**Comment by az0** [comment]
You could find a wishlist ticket about the unstable builds. (It's on another repo.) 

It would take a bit of work, but I think some people would appreciate it.  

An easier option could be to subscribe to the repo on GitHub because most  commits trigger a new build.
