### ISSUE TITLE
Runtime error when cleaning Chrome, Firefox on Windows

### ISSUE THREAD

**Issue by pdklein88** [bleachbit/bleachbit#639]
Running version 2.2 on Windows 10 1809.

Whenever any boxes for Chrome, Firefox, or Adobe are checked, it will throw a "Runtime Error! C:\Program Files (x86)\BleachBit\bleachbit_console.exe This application has requested the runtime to terminate in an unusual way. Please contact the application's support team for more information.

When running the debugger, it says "Fatal Python error: Interpreter not initialized (version mismatch?).

**Comment by az0** [comment]
This is a good description and good troubleshooting, so thank you.

This looks like issue #557 . Would you please mind testing a recent [CI Build](https://ci.bleachbit.org) such as 2.3.1294? This build and many of the newer builds on that page have a fix related to checking for running processes. 

BleachBit is checking whether Firefox and the other applications are running. If this is what was causing the crash, it would _not_ crash when running a preview for Firefox or Chrome, but it would crash when trying to clean them.

**Comment by az0** [comment]
Instead of the CI builds, I recommend testing [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta). Let me know how it goes, so I know whether to close the bug or look into it more.

**Comment by pdklein88** [comment]
Thanks for following up! I have been at a conference, but will test 2.3 beta when I'm back in the office on Monday.

**Comment by az0** [comment]
@pdklein88 I hope your conference went well. Would you please test [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)?

**Comment by pdklein88** [comment]
Sorry again for the delay. Everything is working well!
