### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#640]
In a program running from latest source by a command with sudo, instead of the menu, a vertical black bar. The diagnostic file is obtained from a program running by a command without sudo.
[Diagnostic.txt](https://github.com/bleachbit/bleachbit/files/3694246/Diagnostic.txt)

**Comment by az0** [comment]
Would you please attach a screenshot? GitHub allows .png attachments

**Comment by ediowar** [comment]
![no menu](https://user-images.githubusercontent.com/44164186/66274255-40fb0d80-e885-11e9-954b-3e0c0fb22f4b.png)

**Comment by ediowar** [comment]
Bug appears after Merge branch 'modernization2016' [https://github.com/bleachbit/bleachbit/commit/7f61a9caab30773bdc7108d135291891782c3008](url)

**Comment by az0** [comment]
A few questions

1. Did you install from source **or** [run from source without installation](https://docs.bleachbit.org/dev/running-from-source-code.html)? By install, I mean running `make install`.

1. If you are running from source: relative to the `bleachbit.py` file, is there a file called `data/app-menu.ui`?

1. If installing with `make install`, is your source  newer than October 1? This date is when there was a related bug fix to `Makefile` (commit 792b0fb2c8f928fe9891ee8e15ae50f7eee283fa).

1. Does this happen when running as a normal user (in other words, _not_ sudo)?

1. Does it happen when the window is unmaximized?

**Comment by ediowar** [comment]
1. sudo python bleachbit.py
2. Yes
3. 
4. No
5. Yes

**Comment by ediowar** [comment]
Workaround :)
![Screenshot from 2019-10-12 12-34-48](https://user-images.githubusercontent.com/44164186/66699195-37423180-eced-11e9-9a9d-1e6c47494776.png)

**Comment by az0** [comment]
This functionality is consistent with GNOME's  declaration of the  [application menu retirement](https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement)

>* Remove their app menu and move any menu items to the primary menu
>* Where necessary, split their primary menus into primary and secondary menus (see menu organisation guidance below)
