### ISSUE TITLE
Checking/unchecking all options for one cleaner only inverts selected options

### ISSUE THREAD

**Issue by Lennylord** [bleachbit/bleachbit#645]
BleachBit 2.3.1304 Beta
Windows 10 64-bit

Instead of selecting all the cleaners, which was the expected behavior, clicking to select or deselect all of the options for a cleaner while only some of the options are still checked inverts the selection to the cleaners which were not already selected.

![bleachbit-23beta_prob](https://user-images.githubusercontent.com/19417931/66533965-503bbe80-eb04-11e9-9b2e-2f4e097acb3b.gif)

**Comment by ediowar** [comment]
The same thing on Ubuntu.

**Comment by az0** [comment]
@Lennylord 
Thanks for the report. You can try the fix in [CI Build 2.3.1306](https://ci.bleachbit.org) or later. (Build 1306 will need a few minutes to finish building.)

@ediowar 
Thanks for confirming. For now, you can get the [fix from Git](https://docs.bleachbit.org/dev/running-from-source-code.html). I'm not sure whether I will release another beta (with rpm/deb packages), or the next release (with rpm/dev packages) might be the final release.
