### ISSUE TITLE
BB write ANSI files back with wrong encoding

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#650]
Saw this bug shortly after the PR landed that fixed the Total Commander case... guess it's still there...
BB can now read the ANSI file without crashing, but does't write the file back with the right encoding!
Means: Some special characters get "coverted" to others!
Think, BB must save the encoding standard when analyze the file, work on it and then use the saved encoding to write the file back.
Can deliver later more info and samples, but maybe the line above are enough info when looking at the code...

**Comment by az0** [comment]
At quick glance, the .ini cleaner in BleachBit 3.0 should be writing back with the same encoding it used for reading. (It automatically detects encoding, as much as it can.) So I will need to do more research.

Do you have an .ini file for testing? Perhaps you could attach both the original and the managed files.

**Comment by Tobias-B-Besemer** [comment]
I found out that this is a "displaying error" of Notepad++ and it seems to be intended. :-/
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7510

**Comment by az0** [comment]
@Tobias-B-Besemer 
Thanks! :)
