### ISSUE TITLE
Version 3 upgrade does not work!

### ISSUE THREAD

**Issue by Merlote** [bleachbit/bleachbit#652]
Installation failed with 3 attempts - see attached for error.

Window 10 
64 bit 
![b bit 1](https://user-images.githubusercontent.com/57051510/67627874-a435f980-f89f-11e9-8a5b-98126e45adaa.JPG)

Downloaded via Mozilla Firefox

**Comment by az0** [comment]
@Merlote Nice screenshot. Thanks.

Did you install for **Current User** or **All Users**? For troubleshooting purposes, would you please be willing to try the other option?

**Comment by Merlote** [comment]
Thanks for the prompt reply, I opted for 'All Users'

No worries...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Merlote** [comment]
Also F Y I, If the option of ignore is used, there are plenty similar errors...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Redcat54** [comment]
I'm getting the same error messages. Unfortunately the earlier version was already deleted so now I don't have bleachbit on my computer at all. The earlier version worked fine but I can't find a link to download it again.

**Comment by az0** [comment]
@Merlote what is you install only for the current user? It looks like a permissions issue.

@redcat54 are you on Windows 10 too?


Old downloads here:
https://www.bleachbit.org/download/old

**Comment by Merlote** [comment]
All good using the single user option, (Me)

Many thanks for the prompt replies and great service.

My donation via PayPal is on the way!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Merlote** [comment]
Oh by the way, could you software include and deal with the "Brave' browser software?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by az0** [comment]
@Merlote  Thank you for confirming that your issue is solved. I suspect that you could use the "install for all users" if you right clicked on `BleachBit-3.0-setup.exe` and chose the option "Run as administrator." Normally it should do this. In case, your issue is solved. :)

You mentioned the Brave browser. If you are a bit technical, you could probably get it working by making a one-line change to the file `chromium.xml` to give it the profile directory to that browser. I'll provide more info, if you want to try it. Otherwise, please file a wishlist ticket here https://github.com/bleachbit/wishlist/

**Comment by Tobias-B-Besemer** [comment]
@az0, you should maybe keep an issue open for "BB doesn't evaluate by 'All Users' Install, when admin rights are missing".

**Comment by az0** [comment]
@Tobias-B-Besemer Do you think that's an upstream issue for https://github.com/Drizin/NsisMultiUser ?   It seems like the installer either failed to ask for upgraded permissions, or it didn't correctly handle the situation when upgrading permissions failed.

**Comment by Tobias-B-Besemer** [comment]
I think it's a bug in the old installer.
Not sure, but I guess the parameters for the plugin are not configured right...
You should test the alternative installer to see if the issue happens there, too.

**Comment by Tobias-B-Besemer** [comment]
With a quick look, elevation of user rights look good in the old NSIS installer, but the plugin DLL was outdated! I did a PR here: https://github.com/bleachbit/bleachbit/pull/687
If anybody like, test it after the landing, again!

**Comment by az0** [comment]
The BleachBit build with the updated NSIS plugin DLL will be available as [build 3.0.1368](https://ci.bleachbit.org/). Testing is welcome
