### ISSUE TITLE
Use 4 digit versioning ("required" by NSIS)

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#656]
Think you should use the by Microsoft default 4 digit versioning at least internal.
This is necessary for show Version in File Properties or Details tab with NSIS.
I would use [main].[minor].[maintenance].[build(from CI)].
So the next release would be internal e.g.: 3.0.0.1234
More info: https://nsis.sourceforge.io/Docs/Chapter4.html#versioninfo

**Comment by az0** [comment]
Checklist for Windows

[ ] edit `__init__` to have version a.b.c
[ ] alter `windows/setup_py2exe.py` to pass the a.b.c.d version to NSIS
[ ] check the file properties of the installer
[ ] check the file properties of the installed .exes
[ ] check the about dialog

**Comment by Tobias-B-Besemer** [comment]
I would suggest that you catch "d" from the build enviroment (build number), but I don't know if this is (easily) possible...

**Comment by az0** [comment]
I can do that when it run on appveyor

**Comment by Tobias-B-Besemer** [comment]
Sounds great! :)

**Comment by az0** [comment]
Please try version 3.0.1.1338

**Comment by Tobias-B-Besemer** [comment]
Yeah, one after "leet" (1337)... ^^

**Comment by Tobias-B-Besemer** [comment]
Had just a quick look at it, but I think it should look as follows:
![Screenshot_20191103-072419_Firefox Beta](https://user-images.githubusercontent.com/11881073/68081242-2d52b080-fe0b-11e9-9e0f-c6a780aa0ad3.jpg)

**Comment by Tobias-B-Besemer** [comment]
...but to be honest: I would avoid do any changes to the installer by now!
It makes just the lading of my installer more difficult, 'cause we need track changes done and sync them...

**Comment by Tobias-B-Besemer** [comment]
Just FYI: My installer reads the version and handle a version change as a upgrad - uninstalls & reinstalls... Same version: Repair or change feature of BB... ;)
