### ISSUE TITLE
Update warning error;

### ISSUE THREAD

**Issue by Ub3rZ4cH** [bleachbit/bleachbit#657]
Bleachbit warns me upon opening that there is a new version yet I am on the latest git source (3.1)

It says;

> A new version is available. Update to version 3.0

Is this intended? due to stable version not sure thought I would highlight it.

Solution:
Disable check for update in Preferences >> General >> "Check periodically for software updates".

**Comment by az0** [comment]
You updated quickly! No, that's not intended. It should be fixed now
