### ISSUE TITLE
Add labels below icon on toolbars 

### ISSUE THREAD

**Issue by rbrito** [bleachbit/bleachbit#662]
With the release of bleachbit 3.0, the user interface has changed drastically and, for people with low visual acuity (my case), it is much harder to use than before.

It seems that bleachbit now uses GTK "Header bars" instead of the more familiar "Title Bars" with menus and clearly labeled buttons with words (like it used to be).

I am attaching a screenshot showing how hard it is to decide which buttons should be pressed (I actually have to wait for the tooltips to appear to decide which button is the right one).

Can some change be made to avoid this situation in the next few releases?

Thanks in advance,

Rogério Brito.

![Screenshot at 2019-11-01 01-03-42](https://user-images.githubusercontent.com/212145/68001964-3abe3e00-fc45-11e9-921f-c5eb857c573b.png)

**Comment by 2635599** [comment]
same here have to wait for the tooltip to know which icon to press.

**Comment by az0** [comment]
@rbrito Which version of Linux is that? It's odd you have both the application icon on the left and the hamburger menu on the right.

@2635599 You are suggesting to put the clean and delete buttons into the existing drop-down menu? 

It sounds like both of you would want the text like "Clean" next to the toolbar icons.

**Comment by rbrito** [comment]
Hi, Andrew.

On Nov 01 2019, Andrew Ziem wrote:
> @rbrito Which version of Linux is that? It's odd you have both the
> application icon on the left and the hamburger menu on the right.

I'm using Debian testing (with bleachbit 3.0 from the Debian repositories)
and Mate as my desktop environment.

> It sounds like both of you would want the text like "Clean" next to the
> toolbar icons.

The "old" user interface was very good and was self-evident (in the sense of
discoverability).

It would rock if it were restored. But, of course, text would be very nice
to have instead of the icons only.


Thanks,

Rogério Brito.

-- 
Rogério Brito : rbrito@{ime.usp.br,gmail.com} : GPG key 4096R/BCFCAAAA
http://cynic.cc/blog/ : github.com/rbrito : profiles.google.com/rbrito
DebianQA: http://qa.debian.org/developer.php?login=rbrito%40ime.usp.br

**Comment by az0** [comment]
>The "old" user interface was very good and was self-evident (in the sense of
discoverability).

The change in BleachBit 3 was to update the toolkit from GTK 2 to GTK 3. Going back is not really possible because GTK 2 is on "life support," and the last update for Windows was February 2012. I expect GTK 2 won't be supported much longer on Linux either.

Even with GTK 3, I can check into adding a label under the toolbar icon.

**Comment by 2635599** [comment]
i can't speak to others but yes what i'd like to see is a icon for the dropdown file menu, next to that a button that says analyse and a button next to that says either delete or clean

**Comment by Tobias-B-Besemer** [comment]
I suggested here https://github.com/bleachbit/wishlist/issues/54 to bring the functionality of the cleaner and abort button together. Think that should make the look & feel simpler, too.

**Comment by az0** [comment]
I changed the title to "Add labels below icon on toolbars "

**Comment by Tobias-B-Besemer** [comment]
Would it be much work to do that with aoption in the settings ???

**Comment by az0** [comment]
>Would it be much work to do that with a option in the settings ???

Adding the label below icon on toolbars or combining the clean and abort button?

**Comment by Tobias-B-Besemer** [comment]
Adding the labels... Many progs have it as option in the settings...

**Comment by az0** [comment]
@Tobias-B-Besemer  How about the labels are always there (i.e., without an option)? No one complained about having the labels. Removing the labels wasn't intentional. There were just many changes and side effects related to updating from GTK 2 to GTK 3.

**Comment by Tobias-B-Besemer** [comment]
Was just a idea because other progs have it too this way and I know people like to customize a bit... But no need to do it! Works for me in any way!

Mhhmmm... Don't know... Maybe you can let "some space for improvements" in your coding to do it later? People like customizing, other skins, turn things on & off... Don't know, but maybe you can code it this way, that it gets later a bit easier to do it... Just a suggestion...

**Comment by rbrito** [comment]
Hi, Andrew and others,

> The change in BleachBit 3 was to update the toolkit from GTK 2 to GTK 3. Going back is not really possible because GTK 2 is on "life support," and the last update for Windows was February 2012. I expect GTK 2 won't be supported much longer on Linux either.

Yes, I know pretty well the state of GTK 2 and GTK 3 (and the same with Python 2 vs. Python 3).

Despite that, I know that some programs (can't recall off the top of my head right now, but I can look for it if you really want me to) know if a compositing window manager is running and, then, they use a Header Bar, otherwise, they use a more traditional title bar + menu bar.

Doing this kind of thing is way too laborious and I would like to see something simpler, with the usual title bar + menu bar, just like it was before.

IMVHO, a very usable interface was like this screenshot:

![bleachbit-large](https://user-images.githubusercontent.com/212145/68078575-5ea19100-fdb7-11e9-919c-8ef874596245.png)

(Taken from: https://screenshots.debian.net/screenshots/000/013/603/large.png and attached just for the post to be self-contained).

> Even with GTK 3, I can check into adding a label under the toolbar icon.

How do you envision that?


Thanks,

Rogério Brito.

**Comment by az0** [comment]
>>Even with GTK 3, I can check into adding a label under the toolbar icon.

>How do you envision that?

I could try to match the style of the toolbar from the  screenshot you posted. For the three buttons preview, clean, and abort, I would put the text label below the icon or off to the side of the icon.

**Comment by az0** [comment]
How is this ? I increased icon size from 16px to 24px, and I added the label below.

![Screenshot from 2019-11-02 22-34-20](https://user-images.githubusercontent.com/933680/68080444-1f783d80-fdc1-11e9-98f7-fca34b644eb3.png)


Alternatively, label is on the right, as with the older version of BleachBit.
![Screenshot from 2019-11-02 22-38-26](https://user-images.githubusercontent.com/933680/68080461-87c71f00-fdc1-11e9-8331-8e99563f6a32.png)

I like the second option because it avoids making the toolbar too tall.

Your thoughts?

**Comment by Tobias-B-Besemer** [comment]
I'm back on the point that some GUI options in the settings would be really cool... Just wanna say that... ^^

**Comment by rbrito** [comment]
Hi, @az0.

For some unknown reason, I didn't receive any mails from this thread, but the screenshot that you posted looks much more usable than the current situation.

I will try the current version with my system after this weekend (way too much work, unfortunately) and will let you know how things go (if you want screenshots of how it appears on my system, feel free to ask).


Thanks again,

Rogério.

**Comment by Tobias-B-Besemer** [comment]
Had a look on the latest build...
Seems you use now a new string "Abort" that is missing on Launchpad in translation by now... (???)

**Comment by az0** [comment]
> Seems you use now a new string "Abort" that is missing on Launchpad in translation by now

Good catch. I uploaded it now, and it will show after finishing the upload queue

**Comment by rbrito** [comment]
Thank you. Just tried the version from master. Besides having text, it now also has increased the size of the button, which makes it easier to click on it.

Thanks!

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.
