### ISSUE TITLE
Importing unknown module

### ISSUE THREAD

**Issue by CraigUr1** [bleachbit/bleachbit#670]
Traceback (most recent call last):
	File "/usr/bin/bleachbit", line 38, in <module>
		import bleachbit.GUI
	File "/usr/share/bleachbit/GUI.pr", line 34, in <module>
		import gi
ImportError: No module named gi

bleachbit version: 3.0-1.1.fc28.noarch.rpm
os type: fedora 31

sequence of events:
	tried to run from the icon... did not run
	ran bleaachbit from the command line and got the import error.

**Comment by CraigUr1** [comment]
the /usr/share file should be:
File "/usr/share/bleachbit/GUI.py", line 34

**Comment by CraigUr1** [comment]
Device:  Firefox Fedora 31

**Comment by CraigUr1** [comment]
I ran python2:  version 2.7.17  and inquired about modules.  Module gi  does not exist.

**Comment by az0** [comment]
Please try one of two things. First, you could install the package indicated in the [BleachBit 3.0 release notes](https://www.bleachbit.org/news/bleachbit-30): look under _Known Issues_.  Second, you could try installing the pre-release of [version 3.0.1](https://github.com/bleachbit/bleachbit/issues/658#issuecomment-549160992).

**Comment by az0** [comment]
@CraigUr1 Have you had a chance to try one of these two suggestions?

**Comment by CraigUr1** [comment]
I found where bleachbit was installed (3.0). deleted the files. and installed the previous version (2.2) and everything is ok!

________________________________

**Comment by az0** [comment]
@CraigUr1 Do you want to try to get BleachBit 3.0 working, or are you fine using the older version? It's up to you

**Comment by CraigUr1** [comment]
I'm fine with the older version.  Thanks for asking.

________________________________

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.
