### ISSUE TITLE
Better handling of parsing error when occured because of malformed WinApp2.ini file

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#673]
Get since some days the parsing error attached.
@az0, did you roll out a new version of WinApp2.ini ??? Some probs there ???
Think,
- this error should get fixed, ASAP;
- the error should get better handled!

![2019-11-06 04_33_29-BleachBit](https://user-images.githubusercontent.com/11881073/68269935-e60f2e80-005b-11ea-8bf6-b46074d115ce.jpg)

**Comment by az0** [comment]
This looks like https://github.com/bleachbit/bleachbit/issues/675 . As I mentioned there, I tried to reproduce it, but the new Winapp2.ini works fine for me.

**Comment by Tobias-B-Besemer** [comment]
I get this error in the installed version...

**Comment by Tobias-B-Besemer** [comment]
Guess I found the prob...

This is how WinApp2.ini looks in Notepad++ with UTF-8 encoding:
![2019-11-11 10_52_10-C__Users_Administrator_AppData_Roaming_BleachBit_cleaners_winapp2 ini - Notepad+](https://user-images.githubusercontent.com/11881073/68578202-d6d01c80-0471-11ea-8185-13bb50c0c920.jpg)

This is how the same part looks if I switch to ASCII:
![2019-11-11 10_53_06-C__Users_Administrator_AppData_Roaming_BleachBit_cleaners_winapp2 ini - Notepad+](https://user-images.githubusercontent.com/11881073/68578243-ebacb000-0471-11ea-8b34-a4b9040fc0dd.jpg)

Normally this is a WinApp2.ini issue, but I think BB...
- should handle the prob, too.
- should give a better error out.

Btw.: Mentioned this a long time ago in an other issue:
You make always an empty line in WinApp2.ini!
I investigated that issue long time ago, and it seems to come because you convert the file on an old May, if I be right...

**Comment by Tobias-B-Besemer** [comment]
Dup of https://github.com/bleachbit/bleachbit/issues/424 ???

**Comment by az0** [comment]
I pushed out an updated `Winapp2.ini`. It might take a short time for it to clear the cache, and then you will see the update. Does this help?

**Comment by Tobias-B-Besemer** [comment]
> Does this help?

Solved the actual error caused by it, but don't prevent that this error can't happend in future anymore!

**Comment by az0** [comment]
I can't reproduce the Spybot error, so I can't do much about it now. How about this: if it comes back, I will take another look?

**Comment by Tobias-B-Besemer** [comment]
Can't you check for illegal characters the file and let pop up a nice error msg that explain, zhat the WinApp2.ini file is mailformed?

Btw., as I have written before:
I'm pretty sure you can't reproduce the issue because you have a other Windows Codepage then the German and BB should open & interpret the INI file by system codepage... Right?

**Comment by az0** [comment]
I could improve this, but there are other issues that have great impacts. It's an administrative burden to have many open issues because it slows down development, so I would prefer to close the issues that with relatively smaller impacts. 

As far as the codepage, yes. The winapp2.ini file is read using the platform's default encoding, and one solution would be to make it read the file always with the same encoding. It's a good assumption that 99.9%+ of the time, users are using the unmodified file that is automatically downloaded.

**Comment by Tobias-B-Besemer** [comment]
K, you can let this issue closed!

I just learned from "Aviation accident analysis" and like to fix occurred errors at least on two points...

Btw.: I had this prob with the WinApp2.ini file downloaded by BB and here is the doc to there ussue: https://github.com/MoscaDotTo/Winapp2/issues/418
