### ISSUE TITLE
Make right line-breaks in INI files

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#678]
Mentioned this long time ago at least in a other bug:
BB makes Linux line-breaks when writing back INI files after cleaning!
IMHO a no-go!
So please make Windows line-breaks in INI files when writing them back!
And sorry, but I think this bug should get fixed ASAP, 'cause it's IMHO really a no-go!

**Comment by peter-marshall** [comment]
I'll work on this one.

**Comment by az0** [comment]
On BleachBit build 1835 (a recent commit), the bleachbit.ini file is this format

$ file bleachbit.ini 
bleachbit.ini: UTF-8 Unicode (with BOM) text, with CRLF line terminators
