### ISSUE TITLE
Rephrase string that explains shredding settings and exit

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#679]
I think the string that explains shredding settings and exit should be a bit rephrased.

String is ATM:
"This  function deletes all BleachBit settings and then quits the application.  Use this to hide your use of BleachBit or to reset its settings. The  next time you start it, the settings will initialize to default values."

Problem: "The next time you start it" is difficult to translate" Better would be to use the string "The next time you start BleachBit".

Also: There seem to be two spaces between "The" and "next" in "The  next time you start it"!

**Comment by Tobias-B-Besemer** [comment]
I have checked the German translations and translated the two missing strings. You can import it again...

**Comment by az0** [comment]
@Tobias-B-Besemer 
OK. I will do that.

FYI, I usually import any language change within a few days
