### ISSUE TITLE
Cleaning Internet Explorer history deletes volume mixer settings

### ISSUE THREAD

**Issue by tonedev** [bleachbit/bleachbit#680]
Version: 3.0
Windows 10 Enterprise 64 bit

Cleaning with Internet Explorer -> History option selected resets the Windows Volume mixer settings, clearing any stored application specific volume setting.

It was introduced in commit 90ec13c, pull request #464, file cleaners/internet_explorer.xml and is due to the following registry key being deleted:
`HKCU\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore`

If clearing the mixer settings is intentional, I'd suggest it would probably be worth having a checkbox for it.

Happy to submit a pull request to make it optional if it just wants adding to the Internet Explorer section (or some other simple XML cleaner). Would need feedback on where to put it as it maybe seems out of place in the Internet Explorer section.

**Comment by az0** [comment]
@tonedev 
Nice troubleshooting. So far it seems we might want to just get rid of this line.

@Tobias-B-Besemer 
Any thoughts on this issue, as it would revert one line of your earlier pull request?

**Comment by Tobias-B-Besemer** [comment]
Yes, think removing the line was right!
Will do that on my local copy of the file later, too!
Think it should go into the Windows OS cleaner...
Will do that later, too!
Any chance to land the Windows OS CleanerML file in BB3.2 ???
https://github.com/az0/cleanerml/pull/170

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.

**Comment by tonedev** [comment]
The "Test BleachBit 3.1 beta" link (to https://www.bleachbit.org/bleachbit-31-beta) is 404 page not found but I grabbed 3.1.0.1484 from the downloads page and it looks to be fixed. Thanks.

**Comment by az0** [comment]
Oops, the URL should be  https://www.bleachbit.org/news/bleachbit-31-beta

Glad to hear it's fixed! Thanks for letting me know.
