### ISSUE TITLE
dpkg: dependency problems prevent configuration of bleachbit

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#682]
[sudo dpkg.txt](https://github.com/bleachbit/bleachbit/files/3821339/sudo.dpkg.txt)
![Screenshot from 2019-11-07 02-23-20](https://user-images.githubusercontent.com/44164186/68420749-e4955180-0194-11ea-926e-911bee01e507.png)
![Peek 2019-11-07 16-53](https://user-images.githubusercontent.com/44164186/68420788-02fb4d00-0195-11ea-9953-f4d4b97a56da.gif)

**Comment by az0** [comment]
Package is available for 18.04, 18.10, 19.04 but not Ubuntu 16.04. Apparently you use 16.04
https://packages.ubuntu.com/search?keywords=python-scandir

I'll change the package from _depends_ to _suggests_ because BleachBit works without it

**Comment by ediowar** [comment]
[https://www.bleachbit.org/download/file/t?file=bleachbit_3.0_all_ubuntu1604.deb](https://www.bleachbit.org/download/file/t?file=bleachbit_3.0_all_ubuntu1604.deb) will not be replaced with fixed?

**Comment by az0** [comment]
Not immediately. I'd like to go through the development cycle first.

Would you like me to provide a package you can use until the official release?  Otherwise you can ask dpkg to bypass the dependency. (I haven't researched whether that has side effects.)

**Comment by ediowar** [comment]
After `sudo dpkg -i --ignore-depends=python-scandir bleachbit_3.0_all_ubuntu1604.deb`:
![err](https://user-images.githubusercontent.com/44164186/68532572-cb1c1300-0316-11ea-861b-112d142e81e4.jpg)

Error: apt.autoremove: Function: apt-get autoremove
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 144, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 608, in apt_autoremove
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get --yes autoremove':
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 bleachbit : Depends: python-scandir but it is not installable
E: Unmet dependencies. Try using -f.

**Comment by az0** [comment]
I built a .deb package with the dependency removed. It's just a suggestio now. There are also some other fixes, as of yesterday. Could you please try it?

 http://download.opensuse.org/repositories/home:/andrew_z/xUbuntu_16.04/all/bleachbit_3.0.1_all.deb

**Comment by ediowar** [comment]
I tried, there are no errors.

**Comment by github1963** [comment]
Here is the fix you're looking for in Ubuntu 16.04 LTS for Bleachbit 3.0  ...........
Download and install from here:
https://ubuntu.pkgs.org/18.04/ubuntu-universe-amd64/python-scandir_1.7-1_amd64.deb.html

Then:
https://www.bleachbit.org/download/linux
to download the latest version for 16.04

**Comment by az0** [comment]
@github1963 So you mean the scandir package for 18.04 works on the older Ubuntu 16.04?

**Comment by ediowar** [comment]
I checked it works on Ubuntu 16.04. But I think it's better to leave the newer version of BB with the dependency removed.

**Comment by github1963** [comment]
I did this myself and it is working fine. As long as the dependencies are met there should be no problems. I was receiving error messages with v.2.2 and now, with 3.0, they are gone. It is working like it used to with v1.2..... NO ISSUES. 

I tried sudo dpkg -i --ignore-depends=python-scandir bleachbit_3.0_all_ubuntu1604.deb, but the * was missing, I added a * (sudo dpkg -i --ignore-depends=python-scandir bleachbit_3.0_all_ubuntu1604*.deb) and it still had missing dependencies. I tried the "new" package (3.0.1) still no go.........
My solution is the one that works....

**Comment by ediowar** [comment]
Before installing the newer version of BB with the dependency removed, did you delete the old one?

**Comment by Tobias-B-Besemer** [comment]
People with e.g. Ubuntu >= v18.04LTS can also add the backports sources to APT to get python-scandir!
https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=python-scandir
How to add backport sources to APT I explained a bit more in this issue: https://github.com/bleachbit/wishlist/issues/72
But be carefull: This will probably update other progs & libs to latest versions, too, and can rise into other issues !!!
(...but I would do it!)

@ediowar, even Ubuntu v16.04LTS isn't EOL by now... https://wiki.ubuntu.com/Releases ... (EOL after April 2021) ... I would especially on a "Desktop System" (e.g. a normal PC or a Workstation for daily work) consider a "in distry upgrade" to Ubuntu v18.04LTS to get latest versions of other apps (daily used), too...
(To get e.g. latest version of Thunderbird Email prog, too, if you use it... https://packages.ubuntu.com/search?suite=xenial&searchon=names&keywords=thunderbird ... https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=thunderbird)

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.

**Comment by ediowar** [comment]
Still need fix https://www.bleachbit.org/bleachbit-31-beta — Page not found (404)

**Comment by az0** [comment]
Oops, the URL should be  https://www.bleachbit.org/news/bleachbit-31-beta

**Comment by ediowar** [comment]
On the page https://www.bleachbit.org/download URL is I wrote.

**Comment by ediowar** [comment]
On the page https://www.bleachbit.org/download URL is such as I wrote.

**Comment by az0** [comment]
> On the page https://www.bleachbit.org/download URL is such as I wrote.

Oh, I see. That's the sidebar. OK, I fixed that now.
