### ISSUE TITLE
The new version deletes the .htpasswd files without making it clear

### ISSUE THREAD

**Issue by ZerooCool** [bleachbit/bleachbit#683]
The new version deletes the .htpasswd files without making it clear. Even if that could be justified, it is radical and that poses problem! A webmaster with one or more local copies (or in production) will make the .htpasswd files disappear. In my opinion, it is a bad thing not to have the option clearly defined!

Are you able to please narrow this down to a single checkbox option?

https://www.bleachbit.org/comment/3272#comment-3272

**Comment by az0** [comment]
@ZerooCool 
OK, I found the problem was the VIM cleaner, so the easy option is to not enable that.

I put in a fix. If you still want to use VIM before the next release, you can get the patch from GitHub. Then modify/replace your vim.xml file.

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.

**Comment by ZerooCool** [comment]
I would have to test, on a virtual machine, with an .htpasswd file in the content. I note that, and, would test, ASAP.

**Comment by az0** [comment]
A safe way to test is to run just a preview. If it doesn't show up in
a preview, then it won't show up in delete mode. It's up to you. :)
Thanks for testing

**Comment by ZerooCool** [comment]
I install the 3.2.0 version.
I launch bleachbit with all option enabled.
My .htpasswd file was not delete.

Then, i mean this problem it's now resolved.

Installer bleachbit depuis le dépôt officiel :
Depuis le site officiel : https://www.bleachbit.org/download/linux

C'est la version bleachbit_3.2.0_all_debian10.deb qui est actuellement disponible : https://download.bleachbit.org/bleachbit_3.2.0_all_debian10.deb

wget https://download.bleachbit.org/bleachbit_3.2.0_all_debian10.deb
sudo dpkg -i bleachbit_3.2.0_all_debian10.deb

[Resolved]

**Comment by az0** [comment]
Thank you for confirming, @ZerooCool
