### ISSUE TITLE
Customize the system.localizations target invoking without GUI?

### ISSUE THREAD

**Issue by graysky2** [bleachbit/bleachbit#684]
Is there a way to specify on the CLI to preserve both en and en_GB when running `bleachbit --clean system.cache system.localizations`?

**Comment by az0** [comment]
No, there is not a command line option. Are you doing a mass deployment that you need automation?

You can configure it by editing the `bleachbit.ini` file. There is a section called `[preserve_languages]` that on your system might look like this

```
[preserve_languages]
en = True
en_GB = True
```
Try this

```
echo '[preserve languages]'>> ~/.config/bleachbit/bleachbit.ini
echo 'en_GB = True'>> ~/.config/bleachbit/bleachbit.ini
```

This assumes you already had `en=True`. It doesn't seem to cause a problem if this section is split up by other sections.

Does this help?

**Comment by graysky2** [comment]
Yes, thank you.
