### ISSUE TITLE
strip.exe errors in AppVeyor! A prob?

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#690]
I saw some strip.exe errors in AppVeyor! Is this a problem?

![2019-11-11 18_05_56-bleachbit 3 0 1 1363 - AppVeyor](https://user-images.githubusercontent.com/11881073/68606221-46fc9380-04ae-11ea-8cb8-fa77c48252e1.jpg)

**Comment by az0** [comment]
There might be an opportunity to shrink these 6 .dll files.
