### ISSUE TITLE
Bleachbit on Fedora 31 does not start without pygobject3

### ISSUE THREAD

**Issue by TheJuli** [bleachbit/bleachbit#696]
Starting Bleachbit from the shell shows no signs of life, and no single error popup.

Starting it then from the terminal, the error thats displayed is:

`Traceback (most recent call last):
File "/usr/bin/bleachbit", line 38, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/GUI.py", line 34, in <module>
    import gi
ImportError: No module named gi
`

After installing `pygobject3` package, bleachbit starts succesefully.

**Comment by az0** [comment]
This looks like the bug documented in the [known issues ](https://www.bleachbit.org/news/bleachbit-30#known)section of the release notes.

Did installing pygobject3 also install python2-gobject?

**Comment by TheJuli** [comment]
Yes, it did

**Comment by az0** [comment]
OK, no worries.

I am working on getting a maintence release out soon to avoid more confusion, and for now you have a workaround

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.
