### ISSUE TITLE
BleachBit-3.0.1.1383-portable zlib.error

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#704]
bleachbit.exe.log:
`Traceback (most recent call last):
  File "bleachbit.py", line 40, in <module>
zlib.error: Error -3 while decompressing data: too many length or distance symbols`

**Comment by az0** [comment]
I confirm with build 1383 on Windows 10. Thanks for the report.

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta)
