### ISSUE TITLE
Fedora31 installation documentation - dependencies

### ISSUE THREAD

**Issue by klslz** [bleachbit/bleachbit#710]
Hi..

I'd appreciate if somebody could update the Wiki or installation instructions for Fedora31 regarding required dependencies. 

I couldn't find any hints anywhere. Therefore I'm bringing it up.

The required packages are:

pygtk2 python2-gobject python2-scandir

The installation command would be:

sudo dnf install pygtk2 python2-gobject python2-scandir

THX

**Comment by az0** [comment]
There a note here in the release notes: https://www.bleachbit.org/news/bleachbit-30

I hope soon to release a maintenace release that will require python2-gobject, so I think it doesn't require a permament documentation like a wiki.

I did not require python-scandir because CentOS 7 doesn't have it. While it's possible to be more specific, it didn't seem worth it because (1) it works without out (2) speed difference on Linux is not as big as Windows and (3) BleachBit 4 won't require the scandir package anymore.

Do you think that covers it?

**Comment by klslz** [comment]
The key issue: Fedora31 has taken Bleachbit out of the repositories.

One of the reasons for it is python3.x becoming default.
Therefore, as you can see in my initial post, all the packages I had to install are python2-xxx .
All python-xxx wouldn't work anymore.

As long as Bleachbit doesn't come as python3 app, I'm wondering if it makes it back into the
Fedora Repos.

Until then you could somewhere explain how to install it manually. That might help a lot of people.
The Fedora package names are different then debian/Ubuntu/Arch asf. It took me, as advanced user,  a while to get it done.

I installed scandir because bleachbit did throw out  a related message.

**Comment by az0** [comment]
Yes, BleachBit will complaina about scandir, but it will still run well without it.


How about this https://github.com/bleachbit/docs/commit/07e4e372803532a288a4a4b00d9a1f06be61b404 ?

**Comment by terrycloth** [comment]
I'll be taking over the BleachBit package in the Fedora repositories, just as soon as the transition to Python 3 finishes. I see BleachBit v3.0 completed the transition to GTK3, and [v3.1.0 _beta_](https://github.com/bleachbit/bleachbit/releases/tag/v3.1.0) was recently tagged here on GitHub, so now seems like a good time to start updating and testing the package.

How's the move to Python 3 coming along? I don't think there's a single GitHub issue tracking overall progress on this, and without v3.1.0 beta release notes, it's hard tell...

**Comment by terrycloth** [comment]
Ah, never mind. I thought I'd try assuming Python 3 while building the package, just to see how far it gets --- and when looking for instructions for that I noticed the [Install On Linux](https://docs.bleachbit.org/doc/install-on-linux.html) page mentions that BleachBit will require Python 3 in v4.0...

**Comment by az0** [comment]
> How's the move to Python 3 coming along? I don't think there's a single GitHub issue tracking overall progress on this, and without v3.1.0 beta release notes, it's hard tell...

There's nothing in v3.1.0 from the master branch, but there's a separate py3 branch plus an open pull request that have major progress.

**Comment by az0** [comment]
Please try [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta). It's based on Python 3, and it should work nicely again on modern versions of Fedora.
