### ISSUE TITLE
Not a bug.  Questions. Detached signature key; & Logging in forum

### ISSUE THREAD

**Issue by bendover22** [bleachbit/bleachbit#711]
Sorry, not a bug - just questions about the "new signing key" & the forum & the "reset PW process."
What type of a detached gpg signing key has a **.key** for an extension, as the one linked to on www.bleachbit.org?  I've never seen a detached signing key w/ an extension "key."  Anyway, it won't work in verifying the D/L of BB 3.0, using gpg in linux.

The only detached signing keys extensions I've seen are *.sig (binary) or *.asc (ASCII armored).  
To verify a file, there needs to be a detached signature file (used to sign the specific package being downloaded). 
The new 2019 key may be your new "Public Key," (which **I have** on my keyring) but it appears the signature key used to sign the BB 3.0 (linux mint 18.x) package is missing.

Your "key" is identified by Linux as an "Apple keynote 5 presentation" file. 
It may be valid, but it's a 1st for me.  

Can't log in on the forum to ask this.  I'm a bit confused.
The forum says "No new registrations" due to users spamming you.  But **existing** members can still use it & request new PW, if needed? 
If NO one can login there anymore to post, maybe it should say that.
If that's so, why still send PW reset links?

And the link on bleachbit.org **login** page, that says "**use Github instead"** is actually https://www.bleachbit.org/help
I just reset my PW in Feb 2019, so not sure why I'd need it reset so soon.  

When I try logging in the forum, the page sort of blinks, then looks as if nothing was entered.  No msg or error.  I got a PW reset link thru email, but it didn't work.  Another "you're not authorized" msg.  Cookies & scripts were allowed.
  
It allowed me to C&P my UN, PW to the fields & after entering it **showed my user name** in the URL, but I couldn't access anything to make a post.

I had notes about the last time the exact same thing happened last Feb.  & what I did to overcome.  But not today.

**Comment by az0** [comment]
> Sorry, not a bug - just questions about the "new signing key" & the forum & the "reset PW process."
> What type of a detached gpg signing key has a **.key** for an extension, as the one linked to on [www.bleachbit.org](http://www.bleachbit.org)? I've never seen a detached signing key w/ an extension "key." Anyway, it won't work in verifying the D/L of BB 3.0, using gpg in linux.

> The only detached signing keys extensions I've seen are *.sig (binary) or *.asc (ASCII armored).
> To verify a file, there needs to be a detached signature file (used to sign the specific package being downloaded).
> The new 2019 key may be your new "Public Key," (which **I have** on my keyring) but it appears the signature key used to sign the BB 3.0 (linux mint 18.x) package is missing.
> 
> Your "key" is identified by Linux as an "Apple keynote 5 presentation" file.
> It may be valid, but it's a 1st for me.

Did you read https://docs.bleachbit.org/doc/install-on-linux.html  ? There is documentation specifically on how to to verify the signatures.

> Can't log in on the forum to ask this. I'm a bit confused.
> The forum says "No new registrations" due to users spamming you. But **existing** members can still use it & request new PW, if needed?

Yes

> If NO one can login there anymore to post, maybe it should say that.
> If that's so, why still send PW reset links?
> 
> And the link on bleachbit.org **login** page, that says "**use Github instead"** is actually https://www.bleachbit.org/help

OK, I edited to clarify.

> I just reset my PW in Feb 2019, so not sure why I'd need it reset so soon.

Hmm. Normally you don't need to reset the BleachBit forum password, unless you forgot it.

> When I try logging in the forum, the page sort of blinks, then looks as if nothing was entered. No msg or error. I got a PW reset link thru email, but it didn't work. Another "you're not authorized" msg. Cookies & scripts were allowed.

> It allowed me to C&P my UN, PW to the fields & after entering it **showed my user name** in the URL, but I couldn't access anything to make a post.

Do you have a browser extension that might be altering how the site works? It works for me, and I haven't heard of other people having this issue.

**Comment by az0** [comment]
I am closing because I made changes on November 17, and there was no response since then
