### ISSUE TITLE
BB 3.0 is launched but has no window

### ISSUE THREAD

**Issue by LifeIsADeflatingVest** [bleachbit/bleachbit#712]
I'm opening a new issue to differentiate from https://github.com/bleachbit/bleachbit/issues/663

Both on Windows 7 (desktop) and Windows 10 (laptop), both with the portable and the .exe versions, when BB 3.0. is launched, I can see the process in task manager, but there is no window (not even minimized). 

> @LifeIsADeflatingVest can you run bleachbit_console.exe (may be with --debug) and attach the log here?

BleachBit version 3.0
Git revision c32a0365
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
local_cleaners_dir = C:\Users\User\Desktop\BleachBit-Portable\cleaners
locale_dir = C:\Users\User\Desktop\BleachBit-Portable\share\locale\
options_dir = C:\Users\User\Desktop\BleachBit-Portable
personal_cleaners_dir = C:\Users\User\Desktop\BleachBit-Portable\cleaners
system_cleaners_dir = C:\Users\User\Desktop\BleachBit-Portable\share\cleaners\
locale.getdefaultlocale = ('en_GB', 'cp1252')
os.getenv('APPDATA') = C:\Users\User\AppData\Roaming
os.getenv('cd') = C:\Users\User\Desktop\BleachBit-Portable
os.getenv('LocalAppData') = C:\Users\User\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\User\AppData\LocalLow
os.getenv('Music') = C:\Users\User\Music
os.getenv('USERPROFILE') = C:\Users\User
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\User\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\User\
platform.win32_ver[1]() = 6.1.7601
platform.platform = Windows-7-6.1.7601-SP1
platform.version = 6.1.7601
sys.argv = ['bleachbit_console.exe', '--debug-log=DEBUG_LOG']
sys.executable = C:\Users\User\Desktop\BleachBit-Portable\bleachbit_console.exe
sys.version = 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = C:\Users\User\Desktop\BleachBit-Portable\library.zip\bleachbit\Diagnostic.pyo

**Comment by mkhon** [comment]
@LifeIsADeflatingVest what happens when you add --no-uac to the invocation?

In my case the next line after Diagnostic.pyo is:

```
__file__ = C:\Users\Max\work\bleachbit\BleachBit-Portable\library.zip\bleachbit\Diagnostic.pyo
elevate_privileges() exe=C:\Users\Max\work\bleachbit\BleachBit-Portable\bleachbit_console.exe, parameters=--gui --no-uac --debug --gui --debug-log x
ShellExecuteEx={'hInstApp': 42, 'hProcess': <PyHANDLE:0>}
```

**Comment by mkhon** [comment]
@LifeIsADeflatingVest additionally, you should use --gui so full command line should be

```
bleachbit_console --gui --debug-log bleachbit.log
```

or

```
bleachbit_console --gui --debug-log bleachbit.log --no-uac
```

**Comment by mkhon** [comment]
@LifeIsADeflatingVest additionally, which antivirus do you have and does it have anything related to bleachbit in the log?

**Comment by LifeIsADeflatingVest** [comment]
Well, this took me by surprise… After running `bleachbit_console --gui --debug-log bleachbit.log --no-uac`, and while going through the log file (output was identical to the one I pasted earlier), BB was launched normally—that is, with a window. I then removed the entire folder (portable version), downloaded anew, and double-clicked bleachbit.exe. It opened normally.

I'm not sure why this happened, but hopefully you can draw a useful conclusion.

(Parenthetically, I use Kaspersky Internet Security, which didn't have anything related to BB)

**Comment by Tobias-B-Besemer** [comment]
Anyhow I have the feeling that this issue belongs to what I had reported here: https://github.com/bleachbit/bleachbit/issues/512#issuecomment-518030084

**Comment by mkhon** [comment]
@Tobias-B-Besemer I also have the impression that your issue (window not appearing at all) is different to "minimized" issue. Can you share your bleachbit.ini?

**Comment by Tobias-B-Besemer** [comment]
@mkhon, sorry, you got me wrong!
My BB comes up!
It just can take minutes... ;)
And I guess some people don't wait so long, see in task manager that it seems the task doesn't respond anymore and kill them... ;)
