### ISSUE TITLE
Clipboard doesn't seem to do anything?

### ISSUE THREAD

**Issue by SenpaiSharp** [bleachbit/bleachbit#714]
Windows 8.1 64-Bit
Copy something, run the cleaner with Clipboard selected under System or run it individually. Paste, copied stuff is still there.

**Comment by az0** [comment]
@SenpaiSharp thanks for the report

I can reproduce with BleachBit 3.0.1 (562b18e56691401adcc2fa1251045c20e560b720) on Windows 10

**Comment by az0** [comment]
Please try the fix in [CI build 3.0.1.1408](https://ci.bleachbit.org/). It will be uploaded in a few minutes.

**Comment by SenpaiSharp** [comment]
Yeah, seems to work.

**Comment by az0** [comment]
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta)
