### ISSUE TITLE
Linux Mint 19.3 downgrades BB 3 to BB 2.02 which generates errors

### ISSUE THREAD

**Issue by ineuw** [bleachbit/bleachbit#733]
The Linux Mint 19.2 upgrade process to 19.3 downgraded Bleachbit 3.0. to 2.0.2. 

This works with  errors but that is not what concerns me.

I tried the BB 3.0 online installer, and it fails because it cannot find the existing python-chardet,  

**"Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (3.0.4)"** 

I don't know that this is the reason of the downgrade, and perhaps you want to look into it

**Comment by az0** [comment]
I set up a clean install of Linux Mint 19.3 (Cinnamon) and installed [BleachBit 3.0 using the Ubuntu 19.10 package](https://www.bleachbit.org/download/file/t?file=bleachbit_3.0_all_ubuntu1910.deb). It required installing three packages, including python-chardet, and it worked fine.

Please try the .deb for Ubuntu 19.10. Does this help?

**Comment by ineuw** [comment]
Thanks Andrew,

On installation, I am advised that this is identical to the install copy,
but it's not a problem and it works perfectly well.

**Comment by az0** [comment]
The .deb package for BleachBit 4.0 had many changes to dependencies that affect this, and I think it is working well now. There is a week-old version available to [download from OBS](https://software.opensuse.org//download.html?project=home%3Aandrew_z&package=bleachbit). To get .deb for Linux Mint 19.3, choose the option for Ubuntu 18.04.

If you have the same issue, please reopen this ticket.

**Comment by az0** [comment]
The RPM and DEB packages are now available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)
