### ISSUE TITLE
gPodder cleaner problem

### ISSUE THREAD

**Issue by velcroskids3** [bleachbit/bleachbit#735]
saved gpodder.xml to AppData\Local\BleachBit\share\cleaners\ but it does not show up when running BB like other stable and bets cleaners do.

**Comment by az0** [comment]
The current version of `gpodder.xml` (that comes with BleachBit 3.0) is designed to work only with Linux.  For example, it assumes the cache is under `$XDG_CONFIG_HOME/gpodder/cache/*xml`. If you know where the cache and sqlite databases files are on Windows, then we can enhance it to work on Windows too.

**Comment by az0** [comment]
Test the fix with [CI build](https://ci.bleachbit.org/) 3.9.0.1560 or newer. It will be published in ~10 minutes.

**Comment by az0** [comment]
The digitally-signed Windows installer is now available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)
