### ISSUE TITLE
MX-18.3 Linux, Error in libreoffice.history

### ISSUE THREAD

**Issue by v17564** [bleachbit/bleachbit#736]
Hello.
I use MX-18.3 based in Debian 9 and found this errors when run Bleachbit 3.0

Python versions installed:
python      python2     python2.7   python3     python3.5   python3.5m  python3m    

Errors:
Error: libreoffice.history: Function: Limpiar: /home/myuser/.config/libreoffice/4/user/registrymodifications.xcu
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 233, in delete_office_registrymodifications
    dom1.writexml(open(path, "w"))
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1749, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 814, in writexml
    node.writexml(writer, indent+addindent, addindent, newl)
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 810, in writexml
    self.childNodes[0].writexml(writer, '', '', '')
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1038, in writexml
    _write_data(writer, "%s%s%s" % (indent, self.data, newl))
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 298, in _write_data
    writer.write(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 3: ordinal not in range(128)

**Comment by az0** [comment]
@v17564 
Thanks for the bug report. The VLC and LibreOffice errors don't seem related. For administrative purposes, would you please consider closing this ticket and replacing it with two tickets, one for each issue? This makes it easier to manage, especially when I can't close both bugs at the same time.

Please include follow up information
1. BleachBit 3.0 uses only Python 2, so Python3 info is not needed
2. How did you install BleachBit? Was it a .deb from bleachbit.org? From GitHub?
3. For the VLC error, please run the command `pip2 freeze | grep chardet` and include the output
4. For the LibreOffice error, would you please attach the file `/home/myuser/.config/libreoffice/4/user/registrymodifications.xcu` or email it directly to me? I can give you the address.
5. Open BleachBit. In the hamburger menu, click Diagnostics. Then please include the line that looks like this: `locale.getdefaultlocale = ('en_US', 'UTF-8')`

**Comment by v17564** [comment]
Hello @az0 
I use .deb from bleachbit.org for installation over the previous version 2.2.

I change the file extension from .xcu to .txt
[registrymodifications.txt](https://github.com/bleachbit/bleachbit/files/4012706/registrymodifications.txt)

Bleachbit diagnostic:
locale.getdefaultlocale = ('es_ES', 'UTF-8')

**Comment by v17564** [comment]
Sorry, i push the erroneous button.

**Comment by v17564** [comment]
Hello @az0 
After open other .odt files, the error disappear. Perhaps an error in the file registrymodifications.xcu, i don't know. I close the issue.
Thanks.
