### ISSUE TITLE
MX-18.3 Linux, Error in vlc.mru

### ISSUE THREAD

**Issue by v17564** [bleachbit/bleachbit#737]
Hello.

I use .deb from bleachbit.org for installation over the previous version 2.2.

$ pip2 freeze | grep chardet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
chardet==2.3.0

Error: vlc.mru: Command to clean .ini path=/home/myuser/.config/vlc/vlc-qt-interface.conf, section=General, parameter=filedialog-path
Traceback (most recent call last):
File "/usr/share/bleachbit/Worker.py", line 88, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/Command.py", line 212, in execute
FileUtilities.clean_ini(self.path, self.section, self.parameter)
File "/usr/share/bleachbit/FileUtilities.py", line 220, in clean_ini
detector = chardet.universaldetector.UniversalDetector()
AttributeError: 'module' object has no attribute 'universaldetector'

Error: vlc.mru: Command to clean .ini path=/home/myuser/.config/vlc/vlc-qt-interface.conf, section=RecentsMRL, parameter=None
Traceback (most recent call last):
File "/usr/share/bleachbit/Worker.py", line 88, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/Command.py", line 212, in execute
FileUtilities.clean_ini(self.path, self.section, self.parameter)
File "/usr/share/bleachbit/FileUtilities.py", line 220, in clean_ini
detector = chardet.universaldetector.UniversalDetector()
AttributeError: 'module' object has no attribute 'universaldetector'

Error: vlc.mru: Command to clean .ini path=/home/myuser/.config/vlc/vlc-qt-interface.conf, section=OpenDialog, parameter=netMRL
Traceback (most recent call last):
File "/usr/share/bleachbit/Worker.py", line 88, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/Command.py", line 212, in execute
FileUtilities.clean_ini(self.path, self.section, self.parameter)
File "/usr/share/bleachbit/FileUtilities.py", line 220, in clean_ini
detector = chardet.universaldetector.UniversalDetector()
AttributeError: 'module' object has no attribute 'universaldetector'

**Comment by v17564** [comment]
Hello. I install the new version 3.2.0 and the error persist, only change the number of the error line:

  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 212, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/usr/share/bleachbit/FileUtilities.py", line **236**, in clean_ini
    detector = chardet.universaldetector.UniversalDetector()
AttributeError: 'module' object has no attribute 'universaldetector'

I uninstall completely the VLC and Bleachbit: erase all directories and files of both applications and reinstall the applications but the error it's the same.

**Comment by az0** [comment]
@v17564  
Which Linux distribution and version?

Did you install from a rpm/deb package, from a source tarball, or from Git?

**Comment by v17564** [comment]
@az0 

Is the same distribution and version: MX-Linux 18.3, based on Debian stretch. I installed with the .deb package that i download from bleachbit.org.

BleachBit version 3.2.0
Git revision 2e9c779a
GTK version 3.22.11
SQLite version 3.16.2
FSE = UTF-8
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/myuser/.config/bleachbit
personal_cleaners_dir = /home/myuser/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('es_ES', 'UTF-8')
os.getenv('DESKTOP_SESSION') = lightdm-xsession
os.getenv('LOGNAME') = myuser
os.getenv('USER') = myuser
os.getenv('SUDO_UID') = None
os.path.expanduser('') = /home/myuser
platform.linux_distribution() = (**'MX', '18.3', 'Continuum'**)
platform.platform = Linux-4.19.0-8-amd64-x86_64-with-MX-18.3-Continuum
platform.version = 1 SMP Debian 4.19.98-1~mx17+1 (2020-02-08)
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python2
sys.version = 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by Tobias-B-Besemer** [comment]
@v17564, please look at #788, I analiyzed the errors there.
Do BB crash by this error ???
How fast do you need a fix/workaround ???
How good you in IT/Git/etc.? Do you want to help fix it? ^^

**Comment by v17564** [comment]
@Tobias-B-Besemer 
Hello.
The Bleachbit don't crash, only show this error message and an final message that said "3 errors".
I am not in any hurry in the accuracy of the error, only I notify it so that the developers are informed.
I am technical in computer science, programmer and electronics, but already it has been many years since I don't develop software because I have dedicated to another technical aspects: repair and installations (telephony and data networks). But if i can help you in simple tasks (test) there are not problem.

**Comment by v17564** [comment]
Sorry, i closed by error.

**Comment by az0** [comment]
While you reported it first, I fix the bug that causes the message `AttributeError: 'module' object has no attribute 'universaldetector'` under issue https://github.com/bleachbit/bleachbit/issues/788

You reported you use Linux Mint 18.3, which is based on Ubuntu 16.04, and this is consistent with what I found in #788. The root cause was that Ubuntu 16.04 has an old version of the chardet module. Now there is a workaround.

You can grab the fix from Git or wait for me to post a new .deb package (later)

**Comment by v17564** [comment]
@az0 Hello. I don't report to use Linx Mint, I report used MX-Linux 18.3 based on Debian 9 Stretch. My chardet is "chardet==2.3.0" and I don't know is old or not but if it's solved then good.

**Comment by az0** [comment]
@v17564 
Yes, you're right. You don't use Linux Mint.

The problem is the same, though. I think chardet 2.x (like you have) caused `AttributeError: 'module' object has no attribute 'universaldetector'`, but now this should be fixed.

**Comment by az0** [comment]
The RPM and DEB packages are now available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)

**Comment by v17564** [comment]
Hello @az0 
I test the new version and received 3 errors, all are the same error but in different section, in VLC and  different from the previous ones.

I use the deb package for Debian 9.
[bleachbit 3.9.0 error.txt](https://github.com/bleachbit/bleachbit/files/4399392/bleachbit.3.9.0.error.txt)
