### ISSUE TITLE
Make chaff doesn't works, no module download_url_to_fn

### ISSUE THREAD

**Issue by felipeaf** [bleachbit/bleachbit#738]
The make chaff menu open a dialog asking for download chaff data ("Download data needed for chaff generator?"), but click ok or cancel doesn't do anything. This is the console output: 

```
Downloading https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download to /home/felipe/.config/bleachbit/clinton_subject_model.json.bz2
Traceback (most recent call last):
  File "/usr/share/bleachbit/GuiChaff.py", line 160, in on_make_files
    if not self.download_models_dialog():
  File "/usr/share/bleachbit/GuiChaff.py", line 140, in download_models_dialog
    ret = self.download_models_gui()  # True if successful
  File "/usr/share/bleachbit/GuiChaff.py", line 130, in download_models_gui
    return download_models(on_error=on_download_error)
  File "/usr/share/bleachbit/Chaff.py", line 179, in download_models
    if not download_url_to_fn(url, fn):
  File "/usr/share/bleachbit/Chaff.py", line 112, in download_url_to_fn
    import requests
ImportError: No module named requests
```

Bleachbit 3.0, Ubuntu 19.10, installed from deb https://download.bleachbit.org/bleachbit_3.0_all_ubuntu1910.deb.

**Comment by az0** [comment]
@felipeaf 
Thanks for concisely putting relevant info into your bug report.

Please try running this command from the terminal `sudo pip install requests`

**Comment by az0** [comment]
@felipeaf 
Have you had a chance to try one of the commands?

**Comment by az0** [comment]
I am closing because of lack of response since January 4.

@felipeaf 
If you have more information, good or bad, about this issue, please add it here.
