### ISSUE TITLE
VLC: vlc-qt-interface.conf not written correctly

### ISSUE THREAD

**Issue by BrendonIrwan** [bleachbit/bleachbit#740]
On BleachBit 3.0, cleaning VLC breaks `vlc-qt-interface.conf` such that VLC itself no longer parses the file correctly. For some reason, keys (and probably values) are case sensitive. For example:

`fsctoolbar="43-4;"` is not equivalent to `FSCtoolbar="43-4;"`

To reproduce this, start from a fresh VLC setup, customize the interface to your liking, play a video, exit VLC, run BleachBit, then start VLC again.

**Comment by az0** [comment]
Yes, BleachBit treats the keys as case insensitive. I noticed this can eventually cause BleachBit to complain about duplicate keys.

**Comment by az0** [comment]
@BrendonIrwan 
If you are on Windows, you can test a [recent CI build](https://ci.bleachbit.org/). If you are on Linux, you can [run from source](https://docs.bleachbit.org/dev/running-from-source-code.html), or soon I will publish RPM and DEB packages.t

**Comment by BrendonIrwan** [comment]
Confirmed working now, though running from source erased my old `bleachbit.ini` file (I have a backup).
