### ISSUE TITLE
BleachBit version 3 application window is hidden (Microsoft Windows)

### ISSUE THREAD

**Issue by emilsvfx** [bleachbit/bleachbit#743]
bleachbit opens only in task manager and that's all.

bleachbit 3.0
Windows 10 1909

**Comment by emilsvfx** [comment]
https://i.imgur.com/DTqCD71.png

**Comment by az0** [comment]
@emilsvfx 

0. FYI: This seems similar to https://github.com/bleachbit/bleachbit/issues/663

1. Have you ever installed BleachBit on this computer before? 

2. Try [build 3.1.0.1466](https://ci.bleachbit.org/?prefix=dl/3.1.0.1466/). Does it work better

**Comment by emilsvfx** [comment]
0: issue looks the same.
1: use only portable app
2:Dont work, only appears in task manager.

**Comment by az0** [comment]
@emilsvfx 

Thanks for the reply.

One more question: do you have dual monitors?

This is important for me to fix. Until then, you can [downgrade to BleachBit version 2.2](https://www.bleachbit.org/download/old).

**Comment by Mrfiregem** [comment]
Happens to me as well, using version 3.9.0.1540. I only have one monitor, and Windows' "Display Settings" detects just one as well. The program just appears in the "background processes" list on the Task Manager and does nothing.

**Comment by az0** [comment]
@emilsvfx  and @Mrfiregem 
**Would you please test Max's new fix today**? In a few minutes, there will be a 3.9.1.x build available on the [CI site](https://ci.bleachbit.org/). Please test and let us know whether it helped.

**Comment by Mrfiregem** [comment]
Actually, I recently installed this again, through Scoop this time, and it works completely fine. `--version` gives 3.2.0. Not sure what I changed since now and the last time.

**Comment by az0** [comment]
@emilsvfx 
I haven't heard back from you, and I hope you can confirm the latest fix.  The latest package is available here for testing:[ BleachBit 3.9.2 beta](https://www.bleachbit.org/news/bleachbit-392-beta)

**Comment by emilsvfx** [comment]
@az yes it works perfectly. Only start slowly  but it `s importing  winapp2ini liberty
