### ISSUE TITLE
error messages after update Opera

### ISSUE THREAD

**Issue by fluntelion** [bleachbit/bleachbit#746]
Since the next-to-last update of Opera, BleachBit displays the following (error) messages:

error: opera.history: Function: clean file: /home/NAME/.config/opera/HistoryTraceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 199, in delete_chrome_history
  FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 406, in execute_sqlite3 '%s: %s' % (bleachbit.decode_str(exc), path))
OperationalError: no such column: lower_term: /home/NAME/.config/opera/History

BaseException.message has been deprecated as of Python 2.6
BaseException.message has been deprecated as of Python 2.6
BaseException.message has been deprecated as of Python 2.6

**Comment by az0** [comment]
Thank you. This looks like a clear, actionable bug report. I'll check into it.

**Comment by az0** [comment]
Here's a bug report for Google Chrome also complaining `no such column: lower_term`
https://github.com/bleachbit/bleachbit/issues/744

**Comment by az0** [comment]
@fluntelion 

I added two fixes. One way to test is to download the new [Special.py](https://raw.githubusercontent.com/bleachbit/bleachbit/3903e32baad2c7edede71383919238de72fb5363/bleachbit/Special.py) and overwrite the old version.

The old version might be under `/usr/local/share/bleachbit`

Let me know how it goes

This assumes you installed BleachBit 3.0 using a .deb or .rpm package from www.bleachbit.org

**Comment by az0** [comment]
Please test the fix here
https://www.bleachbit.org/news/bleachbit-31-beta

Then please add a comment in GitHub to let me know how it goes

**Comment by fluntelion** [comment]
Yes, I'm using Bleachbit 3.0, installed from bleachbit_3.0_all_ubuntu1804.deb

In LM, the path is not /usr/local/share/bleachbit, but /usr/share/bleachbit/. Just in case it matters.

As you recommended, I replaced the old Special.py by the new one. BleachBit works perfectly well now. :-)

Thank you very much for the work and the time you have put into it.
