### ISSUE TITLE
Build 3.1 & Release for bleachbit.org

### ISSUE THREAD

**Issue by Chaython** [bleachbit/bleachbit#751]
3.1 Source was pushed as a release nearly 2 days ago[?] Who moderates bleachbit.org? When will you release a build there for the plebs who don't want to install old python extensions and visual studio

**Comment by az0** [comment]
I am still working out some bugs affecting the Linux packages, so it's not
ready to publish. When it is, I will publish it on www.bleachbit.org

Without installing Python extensions or anything, you can try builds for
Windows any time from  https://ci.bleachbit.org/ . There are easy-to-use
installers.



Andrew

**Comment by fkru** [comment]
Regarding Build 3.1 I presume that it still requires Python 2. Since openSUSE Tumbleweed recently removed BleachBit from the distro, because of dropping Python 2, is there a chance to see an update to Python 3 soon? Thx.

**Comment by az0** [comment]
BleachBit 3.x requires Python 2.

There is major progress on migrating to Python 3. In Git, it's available in a branch called py3, and I hope to make a release soon for Linux distributions that are dropping Python 2. It's not just openSUSE.
