### ISSUE TITLE
BleachBit-3.1.0.1484-setup.exe false positive in eGambit

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#754]
https://www.virustotal.com/gui/file/74f5252b29e2ac55d1cef28035a99bbfa9282f8806ea0e15525142491c5b0251/detection

eGambit
Unsafe.AI_Score_100%

**Comment by az0** [comment]
I triggered a rescan, but the false positive is still there

**Comment by az0** [comment]
I triggered a rescan, but the problem persists.

**Comment by ediowar** [comment]
Why is the file size equal to 11.39 MB?
https://www.virustotal.com/gui/file/c306aa24819e20c387b7c897209ee9aae03e6fee4c1efca56b36a364344276e5/detection

**Comment by az0** [comment]
> Why is the file size equal to 11.39 MB?
> https://www.virustotal.com/gui/file/c306aa24819e20c387b7c897209ee9aae03e6fee4c1efca56b36a364344276e5/detection

That's normal for the installer. Compare to here
https://ci.bleachbit.org/?prefix=dl/3.1.0.1484/

**Comment by ediowar** [comment]
I downloaded the BleachBit-3.1.0.1484-setup.exe and fed it to virustotal. My link is different from yours.

**Comment by az0** [comment]
For beta and final releases, I digitally sign them, so the hashes are different than the CI site

**Comment by Tobias-B-Besemer** [comment]
Guess with AI in string is ment, that machine learning is used...
Tried several years ago to fix such a case for Firefox... Based on my experience I would say you never get an answer and canbsloee this issue in favour of #771.

**Comment by az0** [comment]
I am closing because version 3.1.0 is old, and I tried to resolve this by contacting the vendor.

**Comment by Tobias-B-Besemer** [comment]
Just FYI & amusement:
https://bugzilla.mozilla.org/show_bug.cgi?id=1089178
^.^
