### ISSUE TITLE
Error message (no disk in the drive) is back

### ISSUE THREAD

**Issue by sionstar** [bleachbit/bleachbit#756]
The error message "There is no disk in the drive. Please insert a disk into drive E:. has come back with the new update 3.0 Running on a Windows 8.1 computer.

**Comment by az0** [comment]
You wrote 3.0. BleachBit 3.0 final has the error, but the new update with the fix is version [3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta).  

Please click the "hamburger" menu, click the Diagnostics option, and please check the first line, which has the version.

**Comment by sionstar** [comment]
Just tried 3.1.0 - works without any issues.
Greatly appreciated.
