### ISSUE TITLE
Tested 3.1.0 Beta

### ISSUE THREAD

**Issue by dex1d** [bleachbit/bleachbit#762]
Linux Mint 19.03(trica) / latest Kernel / downloaded bleachbit_3.1.0_all_ubuntu1910.deb
1. Start the GUI. The toolbar should have text and larger icons.  OK
2. Clean Google Chrome history.  Not Used
3. VIM, verify it is automatically hidden from the list of cleaners. OK
4. Copy information to the system clipboard. Use BleachBit to clean the system clipboard. OK
5. New distributions: Fedora 30, Fedora 31. No Used
6. Install from .rpm, and it should require the package python-gobject - Not Used
7. Install from .deb on Ubuntu 16.04. OK
8. Verify there is a launcher to start BleachBit. OK
9. Run BleachBit in CLI mode where an X session is not available. Not Used
10. Verify there are translations on RHEL and CentOS. Not Used
11. Preview the VIM swap cleaners, and verify it does not list ~/.htpasswd. OK
12. Clean the DNF package manager. OK

**Comment by az0** [comment]
@dex1d 
Thank you for testing and for posting your test results. It looks like everything worked just fine, so I'm going to close the ticket.
