### ISSUE TITLE
Permissions denied on Linux Mint

### ISSUE THREAD

**Issue by Palladini** [bleachbit/bleachbit#768]
I am running Linux Mint 19.3 Tricia Cinnamon and when I run BleachBit I get the following erors

> [Errno 13] Permission denied: '/usr/share/locale/de/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/de/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/de/LC_MESSAGES': Command to delete /usr/share/locale/de/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/de': Command to delete /usr/share/locale/de
[Errno 13] Permission denied: '/usr/share/locale/id/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/id/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/id/LC_MESSAGES': Command to delete /usr/share/locale/id/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/id': Command to delete /usr/share/locale/id
[Errno 13] Permission denied: '/usr/share/locale/lt/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/lt/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/lt/LC_MESSAGES': Command to delete /usr/share/locale/lt/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/lt': Command to delete /usr/share/locale/lt
[Errno 13] Permission denied: '/usr/share/locale/nl/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/nl/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/nl/LC_MESSAGES': Command to delete /usr/share/locale/nl/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/nl': Command to delete /usr/share/locale/nl
[Errno 13] Permission denied: '/usr/share/locale/ta/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ta/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ta/LC_MESSAGES': Command to delete /usr/share/locale/ta/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ta': Command to delete /usr/share/locale/ta
[Errno 13] Permission denied: '/usr/share/locale/pl/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/pl/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/pl/LC_MESSAGES': Command to delete /usr/share/locale/pl/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/pl': Command to delete /usr/share/locale/pl
[Errno 13] Permission denied: '/usr/share/locale/uk/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/uk/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/uk/LC_MESSAGES': Command to delete /usr/share/locale/uk/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/uk': Command to delete /usr/share/locale/uk
[Errno 13] Permission denied: '/usr/share/locale/sr/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/sr/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/sr/LC_MESSAGES': Command to delete /usr/share/locale/sr/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/sr': Command to delete /usr/share/locale/sr
[Errno 13] Permission denied: '/usr/share/locale/be/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/be/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/be/LC_MESSAGES': Command to delete /usr/share/locale/be/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/be': Command to delete /usr/share/locale/be
[Errno 13] Permission denied: '/usr/share/locale/fa/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/fa/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/fa/LC_MESSAGES': Command to delete /usr/share/locale/fa/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/fa': Command to delete /usr/share/locale/fa
[Errno 13] Permission denied: '/usr/share/locale/gl/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/gl/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/gl/LC_MESSAGES': Command to delete /usr/share/locale/gl/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/gl': Command to delete /usr/share/locale/gl
[Errno 13] Permission denied: '/usr/share/locale/nn/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/nn/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/nn/LC_MESSAGES': Command to delete /usr/share/locale/nn/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/nn': Command to delete /usr/share/locale/nn
[Errno 13] Permission denied: '/usr/share/locale/bg/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/bg/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/bg/LC_MESSAGES': Command to delete /usr/share/locale/bg/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/bg': Command to delete /usr/share/locale/bg
[Errno 13] Permission denied: '/usr/share/locale/th/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/th/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/th/LC_MESSAGES': Command to delete /usr/share/locale/th/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/th': Command to delete /usr/share/locale/th
[Errno 13] Permission denied: '/usr/share/locale/tr/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/tr/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/tr/LC_MESSAGES': Command to delete /usr/share/locale/tr/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/tr': Command to delete /usr/share/locale/tr
[Errno 13] Permission denied: '/usr/share/locale/fi/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/fi/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/fi/LC_MESSAGES': Command to delete /usr/share/locale/fi/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/fi': Command to delete /usr/share/locale/fi
[Errno 13] Permission denied: '/usr/share/locale/en_AU/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/en_AU/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/en_AU/LC_MESSAGES': Command to delete /usr/share/locale/en_AU/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/en_AU': Command to delete /usr/share/locale/en_AU
[Errno 13] Permission denied: '/usr/share/locale/ko/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ko/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ko/LC_MESSAGES': Command to delete /usr/share/locale/ko/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ko': Command to delete /usr/share/locale/ko
[Errno 13] Permission denied: '/usr/share/locale/el/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/el/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/el/LC_MESSAGES': Command to delete /usr/share/locale/el/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/el': Command to delete /usr/share/locale/el
[Errno 13] Permission denied: '/usr/share/locale/se/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/se/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/se/LC_MESSAGES': Command to delete /usr/share/locale/se/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/se': Command to delete /usr/share/locale/se
[Errno 13] Permission denied: '/usr/share/locale/nb/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/nb/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/nb/LC_MESSAGES': Command to delete /usr/share/locale/nb/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/nb': Command to delete /usr/share/locale/nb
[Errno 13] Permission denied: '/usr/share/locale/ar/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ar/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ar/LC_MESSAGES': Command to delete /usr/share/locale/ar/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ar': Command to delete /usr/share/locale/ar
[Errno 13] Permission denied: '/usr/share/locale/pt_BR/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/pt_BR/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/pt_BR/LC_MESSAGES': Command to delete /usr/share/locale/pt_BR/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/pt_BR': Command to delete /usr/share/locale/pt_BR
[Errno 13] Permission denied: '/usr/share/locale/ro/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ro/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ro/LC_MESSAGES': Command to delete /usr/share/locale/ro/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ro': Command to delete /usr/share/locale/ro
[Errno 13] Permission denied: '/usr/share/locale/fr/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/fr/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/fr/LC_MESSAGES': Command to delete /usr/share/locale/fr/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/fr': Command to delete /usr/share/locale/fr
[Errno 13] Permission denied: '/usr/share/locale/en_GB/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/en_GB/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/en_GB/LC_MESSAGES': Command to delete /usr/share/locale/en_GB/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/en_GB': Command to delete /usr/share/locale/en_GB
[Errno 13] Permission denied: '/usr/share/locale/hr/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/hr/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/hr/LC_MESSAGES': Command to delete /usr/share/locale/hr/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/hr': Command to delete /usr/share/locale/hr
[Errno 13] Permission denied: '/usr/share/locale/zh_TW/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/zh_TW/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/zh_TW/LC_MESSAGES': Command to delete /usr/share/locale/zh_TW/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/zh_TW': Command to delete /usr/share/locale/zh_TW
[Errno 13] Permission denied: '/usr/share/locale/te/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/te/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/te/LC_MESSAGES': Command to delete /usr/share/locale/te/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/te': Command to delete /usr/share/locale/te
[Errno 13] Permission denied: '/usr/share/locale/cs/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/cs/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/cs/LC_MESSAGES': Command to delete /usr/share/locale/cs/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/cs': Command to delete /usr/share/locale/cs
[Errno 13] Permission denied: '/usr/share/locale/ms/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ms/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ms/LC_MESSAGES': Command to delete /usr/share/locale/ms/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ms': Command to delete /usr/share/locale/ms
[Errno 13] Permission denied: '/usr/share/locale/lv/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/lv/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/lv/LC_MESSAGES': Command to delete /usr/share/locale/lv/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/lv': Command to delete /usr/share/locale/lv
[Errno 13] Permission denied: '/usr/share/locale/zh_CN/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/zh_CN/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/zh_CN/LC_MESSAGES': Command to delete /usr/share/locale/zh_CN/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/zh_CN': Command to delete /usr/share/locale/zh_CN
[Errno 13] Permission denied: '/usr/share/locale/vi/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/vi/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/vi/LC_MESSAGES': Command to delete /usr/share/locale/vi/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/vi': Command to delete /usr/share/locale/vi
[Errno 13] Permission denied: '/usr/share/locale/uz/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/uz/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/uz/LC_MESSAGES': Command to delete /usr/share/locale/uz/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/uz': Command to delete /usr/share/locale/uz
[Errno 13] Permission denied: '/usr/share/locale/sq/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/sq/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/sq/LC_MESSAGES': Command to delete /usr/share/locale/sq/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/sq': Command to delete /usr/share/locale/sq
[Errno 13] Permission denied: '/usr/share/locale/da/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/da/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/da/LC_MESSAGES': Command to delete /usr/share/locale/da/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/da': Command to delete /usr/share/locale/da
[Errno 13] Permission denied: '/usr/share/locale/sk/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/sk/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/sk/LC_MESSAGES': Command to delete /usr/share/locale/sk/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/sk': Command to delete /usr/share/locale/sk
[Errno 13] Permission denied: '/usr/share/locale/ku/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ku/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ku/LC_MESSAGES': Command to delete /usr/share/locale/ku/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ku': Command to delete /usr/share/locale/ku
[Errno 13] Permission denied: '/usr/share/locale/bs/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/bs/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/bs/LC_MESSAGES': Command to delete /usr/share/locale/bs/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/bs': Command to delete /usr/share/locale/bs
[Errno 13] Permission denied: '/usr/share/locale/it/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/it/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/it/LC_MESSAGES': Command to delete /usr/share/locale/it/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/it': Command to delete /usr/share/locale/it
[Errno 13] Permission denied: '/usr/share/locale/eu/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/eu/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/eu/LC_MESSAGES': Command to delete /usr/share/locale/eu/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/eu': Command to delete /usr/share/locale/eu
[Errno 13] Permission denied: '/usr/share/locale/ky/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ky/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ky/LC_MESSAGES': Command to delete /usr/share/locale/ky/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ky': Command to delete /usr/share/locale/ky
[Errno 13] Permission denied: '/usr/share/locale/pt/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/pt/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/pt/LC_MESSAGES': Command to delete /usr/share/locale/pt/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/pt': Command to delete /usr/share/locale/pt
[Errno 13] Permission denied: '/usr/share/locale/ia/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ia/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ia/LC_MESSAGES': Command to delete /usr/share/locale/ia/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ia': Command to delete /usr/share/locale/ia
[Errno 13] Permission denied: '/usr/share/locale/eo/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/eo/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/eo/LC_MESSAGES': Command to delete /usr/share/locale/eo/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/eo': Command to delete /usr/share/locale/eo
[Errno 13] Permission denied: '/usr/share/locale/hi/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/hi/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/hi/LC_MESSAGES': Command to delete /usr/share/locale/hi/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/hi': Command to delete /usr/share/locale/hi
[Errno 13] Permission denied: '/usr/share/locale/he/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/he/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/he/LC_MESSAGES': Command to delete /usr/share/locale/he/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/he': Command to delete /usr/share/locale/he
[Errno 13] Permission denied: '/usr/share/locale/my/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/my/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/my/LC_MESSAGES': Command to delete /usr/share/locale/my/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/my': Command to delete /usr/share/locale/my
[Errno 13] Permission denied: '/usr/share/locale/bn/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/bn/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/bn/LC_MESSAGES': Command to delete /usr/share/locale/bn/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/bn': Command to delete /usr/share/locale/bn
[Errno 13] Permission denied: '/usr/share/locale/ast/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ast/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ast/LC_MESSAGES': Command to delete /usr/share/locale/ast/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ast': Command to delete /usr/share/locale/ast
[Errno 13] Permission denied: '/usr/share/locale/ca/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ca/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ca/LC_MESSAGES': Command to delete /usr/share/locale/ca/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ca': Command to delete /usr/share/locale/ca
[Errno 13] Permission denied: '/usr/share/locale/ru/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ru/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ru/LC_MESSAGES': Command to delete /usr/share/locale/ru/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ru': Command to delete /usr/share/locale/ru
[Errno 13] Permission denied: '/usr/share/locale/sl/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/sl/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/sl/LC_MESSAGES': Command to delete /usr/share/locale/sl/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/sl': Command to delete /usr/share/locale/sl
[Errno 13] Permission denied: '/usr/share/locale/et/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/et/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/et/LC_MESSAGES': Command to delete /usr/share/locale/et/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/et': Command to delete /usr/share/locale/et
[Errno 13] Permission denied: '/usr/share/locale/nds/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/nds/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/nds/LC_MESSAGES': Command to delete /usr/share/locale/nds/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/nds': Command to delete /usr/share/locale/nds
[Errno 13] Permission denied: '/usr/share/locale/af/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/af/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/af/LC_MESSAGES': Command to delete /usr/share/locale/af/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/af': Command to delete /usr/share/locale/af
[Errno 13] Permission denied: '/usr/share/locale/ug/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ug/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ug/LC_MESSAGES': Command to delete /usr/share/locale/ug/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ug': Command to delete /usr/share/locale/ug
[Errno 13] Permission denied: '/usr/share/locale/sv/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/sv/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/sv/LC_MESSAGES': Command to delete /usr/share/locale/sv/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/sv': Command to delete /usr/share/locale/sv
[Errno 13] Permission denied: '/usr/share/locale/hu/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/hu/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/hu/LC_MESSAGES': Command to delete /usr/share/locale/hu/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/hu': Command to delete /usr/share/locale/hu
[Errno 13] Permission denied: '/usr/share/locale/ja/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/ja/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/ja/LC_MESSAGES': Command to delete /usr/share/locale/ja/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/ja': Command to delete /usr/share/locale/ja
[Errno 13] Permission denied: '/usr/share/locale/es/LC_MESSAGES/bleachbit.mo': Command to delete /usr/share/locale/es/LC_MESSAGES/bleachbit.mo
[Errno 13] Permission denied: '/usr/share/locale/es/LC_MESSAGES': Command to delete /usr/share/locale/es/LC_MESSAGES
[Errno 13] Permission denied: '/usr/share/locale/es': Command to delete /usr/share/locale/es
Recent documents list 0 
Error: apt.autoclean: Function: apt-get autoclean
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 144, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 616, in apt_autoclean
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get autoclean':
E: Could not open lock file /var/cache/apt/archives/lock - open (13: Permission denied)
E: Unable to lock the download directory

Error: apt.autoremove: Function: apt-get autoremove
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 144, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 608, in apt_autoremove
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get --yes autoremove':
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

Error: apt.clean: Function: apt-get clean
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 144, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 626, in apt_clean
    (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get clean':
E: Could not open lock file /var/cache/apt/archives/lock - open (13: Permission denied)
E: Unable to lock directory /var/cache/apt/archives/
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

[Errno 13] Permission denied: '/var/lib/apt/lists/lock': Command to delete 

> /var/lib/apt/lists/lock

Is there anything I can do to make it work right?  When I had Linux Mint 19.2 running, it worked fine, but ever since I have 19.3 on my Computer, it shows this error every time I run BleachBIT.

**Comment by az0** [comment]
Please see the [FAQ: Why do I see permissions denied errors on Linux?](https://docs.bleachbit.org/doc/frequently-asked-questions.html). Does this help?

**Comment by nutta-git** [comment]
I am also facing the same issue on Fedora 31 
```
[nutta@nutta ~]$ sudo bleachbit
[sudo] password for nutta: 
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit:3750): Gdk-CRITICAL **: 21:06:22.292: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit:3750): Gtk-WARNING **: 21:06:22.297: cannot open display: :0

```
```
[nutta@nutta ~]$ sudo bleachbit-root
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit-root:3756): Gdk-CRITICAL **: 21:06:45.718: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
No protocol specified
Unable to init server: Could not connect: Connection refused

(bleachbit-root:3756): Gtk-WARNING **: 21:06:45.722: cannot open display: :0

```

**Comment by az0** [comment]
The issue here is about errors like this
>[Errno 13] Permission denied: '/usr/share/locale/ug': Command to delete /usr/share/locale/ug

@nutta-git 
Your issue looks like it is related to the X session, and it seems to be unrelated. Let's please open a new ticket to not confuse the issue.
