### ISSUE TITLE
Installer installs BleachBit with unwanted translation

### ISSUE THREAD

**Issue by MPeti1** [bleachbit/bleachbit#770]
The installer offered to install BleachBit with English language, and althoguh I'm not a native English speaker, I was fine with that because I assume every time that the translation is faulty or not complete.
After installation, the program hardly opened after a few minutes (Process Hacker showed high IO usage (~30-40 MB/s) without any disk usage), and it had the translation for my language active. I did not want that, I requested English to be used. Also, the translation is not complete, it has a lot of missing pieces.

I have no idea why was it installed in my language. My system (Windows 10 1903) has English as the default language, but it has my language installed too.
I feel like I need to mention that I have my language set up as the default for non unicode programs, and also that the input language is set to my language.

**Comment by az0** [comment]
When the installer pops up, it has a drop-down list of languages like below. This choice affects _only the installer_.
![bleachbit_320_installer_choose_language](https://user-images.githubusercontent.com/933680/73909376-c4dff900-4869-11ea-8c11-3f25df3257c2.png)

Later is a choice of components to install, like below. If you disable the translations components, then no translations will be installed.
![bleachbit320_installer_components](https://user-images.githubusercontent.com/933680/73909402-d3c6ab80-4869-11ea-9715-a739cefe938b.png)

This is also explained briefly in the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html#q-how-do-i-see-bleachbit-in-my-own-language-on-microsoft-windows).


To localize BleachBit into your language, see the [translator's guide](https://www.bleachbit.org/contribute/translate).

Does this all help?

**Comment by MPeti1** [comment]
I think I unchecked the translations option in the component chooser

**Comment by az0** [comment]
@MPeti1 

Would you please check? In BleachBit 3.2 there is a new option to modify components without fully uninstalling and reinstalling. I think you can access it by starting an uninstall. Use this to remove the translations component.

Alternatively, please fully uninstall and then reinstall without the translations component.

Another third alternative is to delete the `locale` directory. I think it's `c:\program files(x86)\bleachbit\share\locale\`

**Comment by az0** [comment]
I am closing because of no response. If you have the information, re-open this ticket

**Comment by HugoRosado08** [comment]
Hello, i found the same issue with the installer (BleachBit v4.0.0), where unchecking the "Translations" box still gets the "..\share\locale\" files installed.
Tried twice and same result.

Cheers

**Comment by az0** [comment]
My mistake. Yes, this is still an issue, and it's the same as https://github.com/bleachbit/bleachbit/issues/864

**Comment by az0** [comment]
@MPeti1 
@HugoRosado08 

Would you please test the fix? It will be published in 10 minutes at https://ci.bleachbit.org/ . Please test version 4.0.1.1668 or newer

**Comment by HugoRosado08** [comment]
Hi, tested sucessfully and no issue found.
Tested both options and succes (installing with translations and without them)
Cheers, thk

**Comment by az0** [comment]
> Hi, tested sucessfully and no issue found.
> Tested both options and succes (installing with translations and without them)

@HugoRosado08 
Thank you for confirming!
