### ISSUE TITLE
bleachbit.exe (BleachBit-3.1.0.1507-portable.zip) false positive with ratio 29/70

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#771]
Starting from BleachBit-3.1.0.1496-portable
https://www.virustotal.com/gui/file/821f953c72ebfabaa4247caf7c0aa86cb90cd96b2df8e915910605326cbf04a2/detection

**Comment by ediowar** [comment]
Can using a different version of UPX help?

**Comment by az0** [comment]
Wow, that is a lot of red flags.

> Can using a different version of UPX help?

Do you have a version in mind?

These executables are built on Python 3, which is different from what BleachBit has used for Windows since 2009, so they don't have a reputation yet. It could help for me to digitally sign them, send them to vendors for whitelisting, and have users download and use them.

**Comment by ediowar** [comment]
Why use UPX for unstable builds at all?

**Comment by az0** [comment]
1: For consistency. It's easier to do the same thing every time.
2: A while ago, I tried turning off UPX, and the application wouldn't start. It was easier to re-enable it than to debug the issue.
3: Users are testing a build that is more similar to the final build

As an experiment, I downloaded build 1507, uncompressed it with UPX, and uploaded to virustotal for analysis. Did you do this? It [already had the file](https://www.virustotal.com/gui/file/a208234b7900c1e6520cf7eb638e06d901ee0a5c8962da5d58be062c098e554a/detection). As you implied, there was a big difference in the false positives. There were only 4 instead of 21.

Then I re-compressed it with just the `-9` setting, and there were [11 false positives](https://www.virustotal.com/gui/file/1b38e04741ba1deb399ef03baf05938dbab28fcd44c5a12a5e646ac31f3791e8/detection).

**Comment by ediowar** [comment]
Yes, I did it.

**Comment by ediowar** [comment]
Yes, I did this.

**Comment by ediowar** [comment]
Detection ratio increased from 19/71 to 29/71.

**Comment by ediowar** [comment]
Detection ratio increased from 19/71 to 29/71.

**Comment by Tobias-B-Besemer** [comment]
Sorry, but I don't think that this have anything to do with reputation, or how many user use the app...
AV Vendors use more and more heuristic and start to go to machine learning...
Don't know if they would white list BB and then still the prob that every build differ...

**Comment by Tobias-B-Besemer** [comment]
https://medium.com/bugbountywriteup/antivirus-evasion-with-python-49185295caf1
Maybe they got nervous lately ??? ^^

As far I can see it in CI, you use UPX 3.94, latest is 3.96,.released 27 days ago...
I would first update, then test again and then look further...

**Comment by Tobias-B-Besemer** [comment]
Score is ATM 28/70, 21/70 & 23/68.

Details of one file says build 2014, by the two other 2018!
Do you maybe have issues with the clock in the CI ???

**Comment by Tobias-B-Besemer** [comment]
If you want, then you can add the VT Scan to CI... ^^

https://github.com/VirusTotal/vt-cli

**Comment by az0** [comment]
> As far I can see it in CI, you use UPX 3.94, latest is 3.96,.released 27 days ago...
> I would first update, then test again and then look further...

I just pushed the commit to update UPX and SQLite. Once it builds, maybe @ediowar  or @Tobias-B-Besemer  wants to upload it to VT?

**Comment by Tobias-B-Besemer** [comment]
I check the CI and upload...

**Comment by az0** [comment]
I know I just broke CI... I will look into it

**Comment by Tobias-B-Besemer** [comment]
Seems you have a old path in, too.

![2020_02_19_05_24_14](https://user-images.githubusercontent.com/11881073/74801861-4dce4a00-52d8-11ea-9cd7-00a53bcf508d.jpg)

**Comment by ediowar** [comment]
> 
> 
> Score is ATM 28/70, 21/70 & 23/68.
> 
> Details of one file says build 2014, by the two other 2018!
> Do you maybe have issues with the clock in the CI ???

Bleachbit.exe (BleachBit-3.2.0-portable) creation time -- 2015.
https://www.virustotal.com/gui/file/fb92f21940288757b813fb829901476ea709d5986de00ce3dbf5c9a4e4c133ee/detection

**Comment by Tobias-B-Besemer** [comment]
I saw you fixed the build, so I downloaded the artifacts and check them.
Here the first results!

Direct check of the Download URL incl. content seems to unfortunately don't work and isn't a possible solution for further auto-analysis of artifacts, too!
Notable: One scanner even detects this URL as malicious!
But never heard of that scanner... ;)
But maybe we should at any later point dig into it anyway...

![2020_02_20_21_03_16](https://user-images.githubusercontent.com/11881073/74974583-cee72780-5425-11ea-8a5e-2a5ab0a78683.jpg)

**Comment by Tobias-B-Besemer** [comment]
The normal installer looks great so far !!! :)

Only prob I see: You should fix that time prob! Guess at least in future any AV will flag you as "possible malicious" 'cause your builds "travel through time"... ^^

![2020_02_20_21_03_16](https://user-images.githubusercontent.com/11881073/74975282-1c17c900-5427-11ea-9eb7-768a3f30a04b.jpg)

![2020_02_20_21_03_45](https://user-images.githubusercontent.com/11881073/74975242-0c988000-5427-11ea-8199-abe4a10f0dc1.jpg)

![2020_02_20_21_04_15](https://user-images.githubusercontent.com/11881073/74975331-30f45c80-5427-11ea-881d-186faacefc88.jpg)

![2020_02_20_21_04_44](https://user-images.githubusercontent.com/11881073/74975380-4073a580-5427-11ea-8a06-b796f3e5090f.jpg)

![2020_02_20_21_06_19](https://user-images.githubusercontent.com/11881073/74975414-4d909480-5427-11ea-9ef5-b672282b7758.jpg)

...and then maybe sign the CI Nightly Builds, too... ^^

**Comment by Tobias-B-Besemer** [comment]
Btw., about CRDF:
https://en.m.wikipedia.org/wiki/CRDF_Global
https://www.crdf.fr/
https://threatcenter.crdf.fr/false_positive.html
https://threatcenter.crdf.fr/criteria.html

![2020_02_20_21_35_51](https://user-images.githubusercontent.com/11881073/74976723-98131080-5429-11ea-97c4-ca24210bef90.jpg)

![2020_02_20_21_36_17](https://user-images.githubusercontent.com/11881073/74976767-aeb96780-5429-11ea-973f-4751453e30e0.jpg)

;)

**Comment by Tobias-B-Besemer** [comment]
![2020_02_20_22_01_34](https://user-images.githubusercontent.com/11881073/74978425-db22b300-542c-11ea-89e5-80ef8a24b677.jpg)

![2020_02_20_22_01_58](https://user-images.githubusercontent.com/11881073/74978458-ed9cec80-542c-11ea-816b-320163a649b2.jpg)

Was fast !!! ^^

😁

**Comment by ediowar** [comment]
And the remaining 18?
bleachbit.exe (BleachBit-3.9.0.1528-portable.zip) has 18/71 ratio
https://www.virustotal.com/gui/file/ff4c104406ddc9af67a491f94809fb911b98823026efe6407664473657a78d8b/detection

**Comment by Tobias-B-Besemer** [comment]
That fast with checking wasn't possible for me... ^^

**Comment by Tobias-B-Besemer** [comment]
To make my research short, I guess here should be the solution for our prob:
https://github.com/upx/upx/issues/337#issuecomment-590109620

**Comment by ediowar** [comment]
Recompressed  bleachbit.exe (ZIP extraced from BleachBit-3.9.0.1528-portable.zip) [**23/70**](https://www.virustotal.com/gui/file/ff4c104406ddc9af67a491f94809fb911b98823026efe6407664473657a78d8b/detection) with options: -1 --compress-exports=0 --compress-resources=0 [**6/69**](https://www.virustotal.com/gui/file/6f19760b499e339c0724fa732c0c75bcb6ba175f452a8903b2fc6f52caad3a47/detection)

**Comment by az0** [comment]
> Recompressed bleachbit.exe (ZIP extraced from BleachBit-3.9.0.1528-portable.zip) [**23/70**](https://www.virustotal.com/gui/file/ff4c104406ddc9af67a491f94809fb911b98823026efe6407664473657a78d8b/detection) with options: -1 --compress-exports=0 --compress-resources=0 [**6/69**](https://www.virustotal.com/gui/file/6f19760b499e339c0724fa732c0c75bcb6ba175f452a8903b2fc6f52caad3a47/detection)

What's the impact on the size?

**Comment by ediowar** [comment]
36.50 KB ->40.00 KB

**Comment by Tobias-B-Besemer** [comment]
The EXE gets even after extraction as UPX detected! Can we get a none UPX packed EXE ???

Suggestion: Keep in future for case of prob and analiyze an unpacked and a packed EXE as artifact, too.

**Comment by ediowar** [comment]
All UPX supported file formats can be unpacked using the **-d** switch, see upx.doc

**Comment by Tobias-B-Besemer** [comment]
You mean that F-Prot and PEiD doesn't mean with "UPX", that they have the use of it detected?

There is still the prob with the clock... 2014... :-/

"Bahavior" detects "cmd.exe"... Guees that's an execution in a cleaner... Hope that is not the only reason! :-/

The "Full report" says a lot... but I don't understand it... :-/
https://vtbehaviour.commondatastorage.googleapis.com/6f19760b499e339c0724fa732c0c75bcb6ba175f452a8903b2fc6f52caad3a47_VirusTotal%20Jujubox.html?GoogleAccessId=758681729565-rc7fgq07icj8c9dm2gi34a4cckv235v1@developer.gserviceaccount.com&Expires=1582501928&Signature=vEvNw%2BLC7Tvt0zw0I1WNAJdRhHeaz9PvRfB82ZG4CtLDWDVLF%2FrMNGvP826JSYKdVJa1lG%2B3UjCq%0AUEu11KzdWkQE%2BztNkjn5xzoe1NwDqTwRsh4rsuOzujTk4D44dEva5eV7xD1B70vNww%2FOlAjWUwBK%0ArBT8EGIhMwE%2BGpCgQeM%3D&response-content-type=text%2Fhtml;

**Comment by ediowar** [comment]
Invalid link.

**Comment by ediowar** [comment]
Invalid link.

**Comment by Tobias-B-Besemer** [comment]
I took the "3/69" link.

**Comment by az0** [comment]
I digitally signed 3.9.0 beta and uploaded it to virustotal. Since then, I filed one issue per vendor (starting with major vendors), and I worked with individual vendors for whitelisting. This has helped.

I tried decompressing bleachbit.exe, but the application will not start after decompression, so I filed https://github.com/bleachbit/bleachbit/issues/827 to fix this aspect
