### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode

### ISSUE THREAD

**Issue by nutta-git** [bleachbit/bleachbit#774]
```
[nutta@nutta bleachbit]$ python bleachbit.py
Traceback (most recent call last):
  File "bleachbit.py", line 45, in <module>
    import bleachbit.GUI
  File "/home/nutta/Git/bleachbit/bleachbit/__init__.py", line 69, in <module>
    __file__.decode(sys.getfilesystemencoding())))
AttributeError: 'str' object has no attribute 'decode'
```
System: 
Fedora 31 
kernel: 5.5.0-fsync.rc6.git0.1.fc31.x86_64
Python 3.7.6

**Comment by az0** [comment]
@nutta-git 

Which version of BleachBit?

**Comment by nutta-git** [comment]
Didn't really see a version number
but I used this:` git clone https://github.com/bleachbit/bleachbit.git`

**Comment by az0** [comment]
This version (BleachBit 3.2.0) requires Python 2. On Fedora 31, the default Python is 3, so you can try `python2 bleachbit.py`. Alternatively, switch to the py3 branch and use Python 3.

**Comment by nutta-git** [comment]
`python2 bleachbit.py` has fixed the issue, this also fixed the permission issue of ruining bleach bit as an admin user by using: `sudo python2 bleachbit.py`
