### ISSUE TITLE
Require explicitly versioned Python 2 or 3 for all package dependencies and shebangs

### ISSUE THREAD

**Issue by terrycloth** [bleachbit/bleachbit#777]
Continuing the conversation started in [here](https://github.com/bleachbit/bleachbit/pull/747#issuecomment-576053126) (sorry, I got busy with my dayjob...)

Building for Fedora 29+ fails with error

> `/var/tmp/rpm-tmp.rZABtM: line 31: /usr/bin/python: No such file or directory`

because f29 is about the point that the Fedora Project began gradually phasing out Python 2. First, packages needed to start specifying whether they used either Python 2 or Python 3. A package acting like a shim, called `python-unversioned-command`, provided the _unversioned_ `/usr/bin/python` command, for compatibility. Initially this was just a symlink to `python2`, then at some point became a symlink to `python3`, making Python 3 the new default. In the upcoming distro release, Fedora 32, Python 2 itself will still be available, but [all libraries and applications will have been removed from the distribution](https://fedoraproject.org/wiki/Changes/RetirePython2#FESCo_exceptions). After that, legacy users will need to get Python 2 packages from PyPI, or directly from the upstream, or other sources.

So basically, for Fedora and EPEL-based packages, you would want to add the `2` to all Python shebangs and package dependencies --- and then change it to `3` when the Python conversion is complete.

This might be a little more pedantic than is needed for other Linux distros. Hopefully specifying either `python2` or `python3` would not _break_ anything on other operating systems... But I could understand if this seems a little tedious, especially since we would have to make basically all the same edits again after porting to Python 3 finishes.

Depending on how long that will take, the Fedora packages built on f28 may still be good enough for now --- or the package will break for future users anyway. Since f32 will include python2 but no libraries, Fedora users would need to get any python2 dependencies from pip2 or something instead. Depending on how long the conversion has to go, users of Fedora 32+ could:

- compile BleachBit and its dependencies themselves (more work for the users).
- install BleachBit itself and all its python2 dependencies with pip2, and GTK and such dependencies with DNF (more work for BleachBit project). Or, I assume BleachBit would need to be installed via pip2, since DNF/RPM would not be able to detect the python2 dependencies installed via pip2. But I don't know where that package would go, since PyPI probably won't be accepting new python2 packages anymore.
- install a BleachBit RPM with all libraries bundled together into a single package (also more work for BB team, but at least doesn't require adding a new package to a legacy repo).

Personally, in my own RPM spec, I decided keep it simple by starting from scratch --- and also waiting till _after_ BleachBit is ready for Python 3 before I bother much with local test builds. BleachBit was retired from the main Fedora repositories, and I decided not to "unretire" it again till after.

**Comment by az0** [comment]
These files already reference python2

* `./bleachbit.py`
* `bleachbit/GUI.py`
* `bleachbit/CLI.py`

Example: `./bleachbit.py:#!/usr/bin/env python2`

And the `bleachbit.spec` file does too. For example:

```
%if 0%{?fedora} || 0%{?centos_version} >= 800
# Since Fedora 30, the variable __python refers to Python 3,
# so explicitly use Python 2.
%define python_bin %{__python2}
# In Fedora 30 and CentOS 8, the package prefixes changed from "python" to "python2".
%define python_pkg_pre python2
%endif
```

So where do you suggest to make the change?

**Comment by terrycloth** [comment]
There _are_ other .py files whose shebangs do not specify `python2`. It may be better for _all_ shebangs to use `python2`, since, depending on the version of Fedora, the unversioned `python` command may point to the Python 3 binary instead... But I notice at least some of these unversioned .py shebangs are also in files which are not marked as executable, so I suppose they may not make a difference. 

For what's causing the package to fail to build, probably the main thing is the dependencies list in the RPM spec. You have `Requires` and `BuildRequires` tags calling for `%{python_pkg_pre}`, which the spec defines as simply `python`. And Fedora's internal requirements to explicitly version all references to Python also applies to package names. So those dependencies should be named `python2`, `python2-devel`, `python2-setuptools`, etc.

**Comment by az0** [comment]
For Fedora, I redefine `%{python_pkg_pre}` to Python 2 like this

```
%if 0%{?fedora} || 0%{?centos_version} >= 800
%define python_bin %{__python2}
%define python_pkg_pre python2
%endif
```

So on Fedora, the dependencies are `python2-devel`, etc.

**Comment by az0** [comment]
I think it's working OK, so I will close it.

Also, I added code that aborts the program if it runs under Python 2 with a clear error message, instead of an obscure error message.

>$ python2 bleachbit.py 
BleachBit no longer supports Python 2.x.
