### ISSUE TITLE
Traceback File "bleachbit\GUI.pyo", line 715, in worker_done

### ISSUE THREAD

**Issue by muessli** [bleachbit/bleachbit#778]
Hi,
I'm using Windows 10 Home, version 1909.
The following messages always appear at the end of bleachbit:
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 317, in run
  File "bleachbit\GUI.pyo", line 715, in worker_done
  File "gi\module.pyo", line 139, in __getattr_
What does that mean?

**Comment by az0** [comment]
Thanks for reporting the Windows version and the traceback.

Would you also please check which version of BleachBit?

**Comment by muessli** [comment]
sorry, I forgot that. 
in both versions 3.0 and 3.2

**Comment by az0** [comment]
Do you have the option enabled to close BleachBit when it's done cleaning? You could try enabling or disabling that option, to check if it affects the error. That's what the GUI.py line 701 is about, though it's not obvious to me why an error would happen there.



This is related to https://github.com/bleachbit/bleachbit/issues/727 , but I haven't reproduced it yet.

**Comment by muessli** [comment]
Usually, I have the option disabled to close BleachBit when it's done cleaning.
So i can see the messages. Perhaps I should mention that Bleachbit works fine.
When I have the option enabled to close BleachBit when it's done cleaning, no messages will show up.

**Comment by muessli** [comment]
Please don't be surprised, I am using Github for the first time!

**Comment by az0** [comment]
I figured out the cause of this and described it here: https://github.com/bleachbit/bleachbit/issues/727#issuecomment-586637416

Later I will work on a solution. Until then, please note this is a harmless error message

**Comment by lemmy04** [comment]
I'm having the same issue:
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 317, in run
  File "bleachbit\GUI.pyo", line 715, in worker_done
  File "gi\module.pyo", line 139, in __getattr__
Quit on finish is disabled as well.

**Comment by az0** [comment]
Please test the fix in build 3.9.0.1534, which will be available soon at the[ BleachBit CI](https://ci.bleachbit.org/) site. 

To reproduce the bug, do a preview or scan that either (1) takes longer than 10 seconds or (2) finishes when the BleachBit window is not focused (e.g., minimized).

**Comment by az0** [comment]
The digitally-signed Windows installer is now available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)
