### ISSUE TITLE
make chaff ImportError

### ISSUE THREAD

**Issue by vandpurnama** [bleachbit/bleachbit#779]
Hi i just install bleachbit in my computer and i found new feature "make chaff" but i tried this feature nothing happen when i asked to download data for chaff generator i already click download button and cancel button but nothing happen and i run bleachbit in konsole and i got error message 
also i already tried to re-install but got same problem

Bleachbit Diagnostic : 

BleachBit version 3.2.0
Git revision 2e9c779a
GTK version 3.24.13
SQLite version 3.31.1
FSE = UTF-8
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/vandpurnama/.config/bleachbit
personal_cleaners_dir = /home/vandpurnama/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = /usr/share/xsessions/plasma
os.getenv('LOGNAME') = vandpurnama
os.getenv('USER') = vandpurnama
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/vandpurnama
platform.linux_distribution() = ('', '', '')
platform.platform = Linux-5.5.2-1-MANJARO-x86_64-with-glibc2.2.5
platform.version = #1 SMP PREEMPT Tue Feb 4 19:22:35 UTC 2020
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python2
sys.version = 2.7.17 (default, Oct 22 2019, 09:14:09) 
[GCC 9.2.0]
__file__ = /usr/share/bleachbit/Diagnostic.py

Error Message :
Downloading https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download to /home/vandpurnama/.config/bleachbit/clinton_subject_model.json.bz2
Traceback (most recent call last):
  File "/usr/share/bleachbit/GuiChaff.py", line 160, in on_make_files
    if not self.download_models_dialog():
  File "/usr/share/bleachbit/GuiChaff.py", line 140, in download_models_dialog
    ret = self.download_models_gui()  # True if successful
  File "/usr/share/bleachbit/GuiChaff.py", line 130, in download_models_gui
    return download_models(on_error=on_download_error)
  File "/usr/share/bleachbit/Chaff.py", line 179, in download_models
    if not download_url_to_fn(url, fn):
  File "/usr/share/bleachbit/Chaff.py", line 112, in download_url_to_fn
    import requests
ImportError: No module named requests

**Comment by vandpurnama** [comment]
i tried your suggestion on issue #738 but still got the problem

![Screenshot_20200213_152738](https://user-images.githubusercontent.com/33601181/74415201-7d62f980-4e75-11ea-9fc2-651ca663d276.png)

**Comment by az0** [comment]
On your system the "pip" command refers to Python 3, while BleachBit 3.2.0 uses Python 2, so please try this

`sudo pip2 install requests`

**Comment by az0** [comment]
Similarly, with pacman you could try to install `python2-requests` instead of `python-requests`.

**Comment by vandpurnama** [comment]
thanks work like charm
