### ISSUE TITLE
Linting issues flagged on AppStream metainfo

### ISSUE THREAD

**Issue by terrycloth** [bleachbit/bleachbit#780]
There seem to be some minor issues:
```
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
• style-invalid         : <caption> is too long [BleachBit 3.0 in dark mode showing discovered Google Chrome files];longest allowed is 50 chars
```

Otherwise looks good, thanks!

_Originally posted by @AsciiWolf in https://github.com/bleachbit/bleachbit/pull/747#issuecomment-583737534_

**Comment by terrycloth** [comment]
@AsciiWolf, what linter threw these warnings for you?

[`<content_rating>`](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-content_rating) wasn't mentioned in the AppStream "quickstart" so I hadn't noticed this was an option. I think it could be safely omitted, since the spec calls it optional, and BleachBit is a tool, not a game, and so is very unlikely to include blood and gore... But I guess the single tag -- `<content_rating type="oars-1.0" />` -- generated by the OARS questionnaire wouldn't be difficult to add either.

On the other hand, the fact that the official URL (<https://odrs.gnome.org/oars>) redirects to <https://hughsie.github.io/oars/> makes me wonder if this is _actually_ supposed to be an official part of the specification yet... The AppStream documentation for `<content_rating>` doesn't even list all the relevant child tags and attributes.

I'm also curious what the 50-character limit for screenshot captions is based on. The AppStream documentation recommends that captions be "short" but doesn't recommend a hard limit. Is 64 characters going to get truncated? Because if the text is not chopped off, I would personally be inclined to leave the flagged caption as it is --- BleachBit's UI is focused around text, without graphical visualizations of the data it finds, so I think this slightly more detailed caption is useful for explaining to new users what exactly they're looking at in the screenshot.

**Comment by AsciiWolf** [comment]
@terrycloth I used standard `appstream-util validate` cli tool.

**Comment by terrycloth** [comment]
@AsciiWolf Do you see the screenshot caption getting truncated in your software center? Or is there documentation stating that that's what will happen? Because looking again [at the documentation about the `<caption>` element](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html), it now says the maximum caption length should actually be _180_ characters, and we're well within _that_ limit.

**Comment by terrycloth** [comment]
For Fedora, the packaging guidelines actually suggest linting with `appstream-util validate-relax --nonet ./FILE`, presumably because the stricter version complains about "mandatory" elements which the official documentation describes as optional. For example, the stricter validate command also flags the missing `<releases>` element for listing updates from the application changelog. But I don't know if I would be worth the extra effort here unless it could be automated.

**Comment by AsciiWolf** [comment]
@terrycloth It seems that BleachBit is not in repository on Fedora 31 so I am unfortunately not able to check the screenshot.

**Comment by terrycloth** [comment]
Yeah, I'll be adding it back to the Fedora repos after the conversion to Python 3 finishes.

**Comment by terrycloth** [comment]
I guess when it's in the Fedora repos, I'll be able to see how it appears in the GNOME Software "app store" and can adjust the caption length if it's getting cropped. I'll make a note to check back here at that time.

**Comment by terrycloth** [comment]
I just remembered this issue exists and is still open :stuck_out_tongue_closed_eyes:

I managed to figure out a shorter caption without sacrificing much information -- and while I was at it, updated the screenshot.
