### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by pmraps** [bleachbit/bleachbit#781]
Hi,

I noticed two dialogs without translation:
- Make chaff
- About dialog
The main menu (top left corner under windows) entries are also untranslated.

And, under '**_Preferences_**' '**_Show debug messages_**' is also not translatable.

Regards

**Comment by az0** [comment]
"Make chaff" looks like it is translated to some languages. For example, here it is translated to Spanish

https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/es/+translate?batch=10&show=all&search=make+chaff

Likewise, "Show debug messages" is also translated to Spanish
https://translations.launchpad.net/bleachbit/trunk/+pots/bleachbit/es/+translate?batch=10&show=all&search=show+debug

Here is a screenshot showing the translation (BleachBit build 1500 on Windows 10 Spanish)

![BleachBit 320 preferenes Spanish](https://user-images.githubusercontent.com/933680/74594335-78778480-4ff2-11ea-9afd-dd4458fc6ee7.png)


Please help explain what is the difference you are seeing.

**Comment by pmraps** [comment]
Hi,

I don't use Launchpad, the translations there use some kind of dialect I dislike.
I just grabbed pt.po from here (github) and fixed it to be real Portuguese. Maybe there is a new pot file and I should do a msgmerge and complete what is missing?.

How do I create it, please? Do I have to build everything from source? I wouldn't know how on Windows.

This is happening with a version created by [PortableApps](https://portableapps.com/). Here are a few screen shots, again, under Windows. :
[beachbit.zip](https://github.com/bleachbit/bleachbit/files/4209428/beachbit.zip)

**Comment by az0** [comment]
Please see the [BleachBit translator's guide](https://www.bleachbit.org/contribute/translate). I highly recommend editing the translations only in Launchpad and not locally on your system. No, you don't need to build from source. Launchpad will let you download .MO files, and the translation guide has some steps.

**Comment by pmraps** [comment]
Ok, thank you for tour feedback and all your work.
