### ISSUE TITLE
Custom folders not being deleted

### ISSUE THREAD

**Issue by Hyde233** [bleachbit/bleachbit#783]
In the "Custom" menu in the preferences menu, I've specified a custom folder to be deleted. Every time I try to clean, it doesn't delete the files inside that folder nor does it delete the folder. All it does is rename the folder to some random name.

I've pinpointed the cause of this issue to be due to the "Overwrite contents of files" setting. Disabling the setting fixes it, but the thing is, I don't want it to just delete the files; I want it to overwrite them as well.

I've also tried running as administrator. It still doesn't work.

**Comment by az0** [comment]
Which version of BleachBit?

Which operating system (for example, Windows 10 or Ubuntu 19.04)?

If you like, you can paste this information from the BleachBit "diagnostics" window.

**Comment by ediowar** [comment]
Unable to add a custom folder to be deleted.
BleachBit-3.9.0.1513-portable.zip
Windows 8 SL
`Traceback (most recent call last):`
 ` File "C:\projects\bleachbit\bleachbit\GuiPreferences.py", line 382, in add_custom_folder_cb`
  `File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 976, in append`
  `File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 967, in _do_insert`
  `File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 875, in _convert_row`
  `File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 893, in _convert_value`
  `File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 218, in __init__`
  `File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 274, in set_value`

**Comment by Hyde233** [comment]
BleachBit version 3.2.0
Build number 1509
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\Hyde\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\Hyde\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_US', 'cp1252')
os.getenv('APPDATA') = C:\Users\Hyde\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\Hyde\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\Hyde\AppData\LocalLow
os.getenv('Music') = C:\Users\Hyde\Music
os.getenv('USERPROFILE') = C:\Users\Hyde
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\Hyde\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\Hyde\
platform.win32_ver[1]() = 6.3.9600
platform.platform = Windows-8.1-6.3.9600
platform.version = 6.3.9600
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by az0** [comment]
Thanks for the extra info. I'll take a look.

**Comment by az0** [comment]
@Hyde233 

Do you think this folder has any special files such as: executables, DLLs, special system files, or files that might be opened by a running process, or a file that might be locked, or a file that might be restricted against modifications?

**Comment by az0** [comment]
I could not reproduce with Ubuntu 19.10 and BleachBit 3.9 (3dd33e91e72127deb69e94ec424d48757d07cd85) with a simple folder with one file. I enabled overwriting.  Later I will do more testing

**Comment by Hyde233** [comment]
@az0 
It shouldn't have any restrictions. It was an arbitrary folder I created on my desktop filled with PNGs, TXTs, and ZIPs.

**Comment by az0** [comment]
I tested with Windows 10 and BleachBit 3.2.0 (same as your system). I enabled overwrite, added a a custom folder, and cleaned it. It worked normally.

@Hyde233 
Is this folder on your C: drive? If not, is it a network drive or removable drive? Is it an NTFS or FAT file system?

**Comment by ediowar** [comment]
Same prob.
```
BleachBit version 3.2.0
Build number 1509
platform.win32_ver[1]() = 6.2.9200
platform.platform = Windows-8-6.2.9200-SP0
platform.version = 6.2.9200
sys.version = 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
```
Folder is on my C: drive. NTFS file system.

> All it does is rename the folder to some random name.

Name consists of one random character.

**Comment by Hyde233** [comment]
@az0 Yes, it's in my C: drive.

If it makes any difference at all, I did just recently update from 3.0.0.

**Comment by az0** [comment]
Thank you @Hyde233  and @ediowar for the bug report and troubleshooting. This problem existed since at least BleachBit version 2.0. Today I put in two ways of fixing it.

To test the fix on Windows, try [CI Build 1559](https://ci.bleachbit.org/) or later. It will be available for download in ~10 minutes.

**Comment by Hyde233** [comment]
@az0 It's working for me now. Thanks for fixing it.

**Comment by ediowar** [comment]
> This problem existed since at least BleachBit version 2.0.
at least 1.10
