### ISSUE TITLE
clarify BleachBit 4 does not work with Python 2

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#785]
Ubuntu 16.04.6 LTS, latest commit https://github.com/bleachbit/bleachbit/commit/83f3498a945ca3c42e95c8488bb676de92dfef1e
```
$ sudo python bleachbit.py
Traceback (most recent call last):
  File "bleachbit.py", line 43, in <module>
    import bleachbit.GUI
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/__init__.py", line 32, in <module>
    from configparser import RawConfigParser, NoOptionError, SafeConfigParser
ImportError: No module named configparser
$
```

**Comment by az0** [comment]
Change your command from python to python3

**Comment by ediowar** [comment]
With the command python3 starts. Need to add to [Running from source code](https://docs.bleachbit.org/dev/running-from-source-code.html)

**Comment by az0** [comment]
Ok, good idea

**Comment by ediowar** [comment]
And [github page](https://github.com/bleachbit/bleachbit)
