### ISSUE TITLE
vlc.mru errors

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#788]
Ubuntu 16.04.6 LTS, BleachBit version 3.9.0
Running from source code, Git revision https://github.com/bleachbit/bleachbit/commit/29a1ee5f0689b65c92e19f0e3cb5430c43ce6866
```
Clean file ?B /home/dzmitry/.config/vlc/vlc-qt-interface.conf
Clean file ?B /home/dzmitry/.config/vlc/vlc-qt-interface.conf
Clean file ?B /home/dzmitry/.config/vlc/vlc-qt-interface.conf

Disk space to be recovered: 0
Files to be deleted: 0
Special operations: 3
```
```
clean_operation('vlc'), options = '['mru']'
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=General, parameter=filedialog-path 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 234, in clean_ini
    detector = chardet.universaldetector.UniversalDetector()
AttributeError: module 'chardet' has no attribute 'universaldetector'
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=RecentsMRL, parameter=None 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 234, in clean_ini
    detector = chardet.universaldetector.UniversalDetector()
AttributeError: module 'chardet' has no attribute 'universaldetector'
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=OpenDialog, parameter=netMRL 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 234, in clean_ini
    detector = chardet.universaldetector.UniversalDetector()
AttributeError: module 'chardet' has no attribute 'universaldetector'

Disk space recovered: 0
Files deleted: 0
Errors: 3
elapsed time: 0 seconds
```

**Comment by Tobias-B-Besemer** [comment]
I'm a bit confused from your post.

You refer to a new commit.
In this commit get the path fixed for the new EXE Packer version.

Your headline is VLC Memory Dump.
But VLC have nothing to do with EXE Packer.

The headline is VLC Memory Dump.
The crash log is from VLC.
But I read it as a prob by INI Cleaning.

I had a log on the Git Histoty of the VLC Cleaner which changes I done in the last year on it.
But there was no change by cleaning INI.

You refer to Ubuntu 16.
Is this the CI Machine and therfor the reference to the last changes on EXE Packer?

It not, which version of BB do you run ???
Have you maybe updated the cleaner later manual e.g. from repro ???
Maybe the Cleaner File (Version) don't fit to BB ???
IDK! To many questions open...

**Comment by Tobias-B-Besemer** [comment]
OK, I just guess you run latest build...

It looks for me, that Andrew have somehow a "universaldetector" detector written/included, that maybe on different places in BB a "universal" syntax detection should do...

I see now two probs in this log...

First this line:
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=RecentsMRL, parameter=None

Means: In the liner, there is no "parameter" given!
But: We haven't changed that in the last year!
Now is the question: Allow definition of CleanerML an execution without parameter, or is this wrong CleanerML Code, that is linger then a year included.

So... late me save this so far... I hwad over to the doc and look if I have noted something to the "must haves" and the "options"... ^^

**Comment by Tobias-B-Besemer** [comment]
Here is the CleanerML Doc I did:
https://github.com/LV-Crew/bleachbit-docs/blob/CleanerML-v2.0-Docu/_posts/cleanerml_v2.0.md

And here the part with INI Cleaning:
https://github.com/LV-Crew/bleachbit-docs/blob/CleanerML-v2.0-Docu/_posts/cleanerml_v2.0.md#503-commandini

Means: There is an error in the cleaner !!! But since a long, long time !!! ^^

The second prob is this error that always in the log appear:
AttributeError: module 'chardet' has no attribute 'universaldetector'

Seems the new "Universal Detector" is an attribute that get used.
But the module "chardet" didn't got updated till now and just don't know this new Universal Detector! ^^

And a third problem I see is the following:
Beside the prob with the module chardet, the syntax for the cleaner file was wrong!
Normally not that big prob, if the app can handle it anyhow!
Guess Andrew include now the Universal Detector to at least "find" such problems and make them then anyhow manageable!

But this prob will maybe keep open:
UNHO should the user never run into any "cryptic" log !!! If an error acour at all, the app should at least produce an "eye friendly" and anyhow for the user "readable & understandable" error shown!
And if it is just a red pop-up that asks the user to send the created log file to the developer for further analysis...

**Comment by ediowar** [comment]
When I uncheck the box for VLC media player/Most recently used, there are no errors.

**Comment by ediowar** [comment]
I think, universaldetector is a module under the library chardet, not a property of the class chardet, so the module universaldetector must be imported, see Example: Detecting encodings of multiple files at [Usage — chardet 3.0.4 documentation](https://chardet.readthedocs.io/en/latest/usage.html)

**Comment by az0** [comment]
After cleaning vlc.mru, I don't get any error in this case
- Ubuntu 19.04
- Python 3.7.5
- python3-chardet 3.0.4-4
- BleachBit latest Git revision  (c8fe5d0889b74)

I'll try another way

**Comment by az0** [comment]
The problem was an old version of python3-chardet module, so I added a fallback. It's commited to Git.

**Comment by ediowar** [comment]
Git revision https://github.com/bleachbit/bleachbit/commit/047c4c5ceb10999a1132bfa8128b0390e8fe8f41
```
clean_operation('vlc'), options = '['mru']'
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=General, parameter=filedialog-path 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=RecentsMRL, parameter=None 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=OpenDialog, parameter=netMRL 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists

Disk space recovered: 0
Files deleted: 0
Errors: 3
elapsed time: 0 seconds
```

**Comment by az0** [comment]
@ediowar 

Thanks for testing. The error `configparser.DuplicateOptionError` is caused by a lack of case sensitivity in the ini parser. It lowercases the keys, and then VLC adds a mixed case key. Then BleachBit reads it again, and now there are duplicate keys. Because it's not related to chardet, please file a new issue for this problem.
