### ISSUE TITLE
"Wiping free disk space" does not work when configured to be run as part of the stardard cleaning process

### ISSUE THREAD

**Issue by liar666** [bleachbit/bleachbit#790]
When I check "Free Disk Space" in the left pane and click the top "Clean" button, I get the following error:

"Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.[Error 3] The system cannot find the path specified: 'C:\\Users\\user\\AppData\\Local\\Temp\\BleachBitPortableTemp': Function: Overwrite free disk space C:\Users\user\AppData\Local\Temp\BleachBitPortableTemp"

When I Go to the menu and select "Wipe free disk space", it works perfectly

**Comment by az0** [comment]
Which version of BleachBit? 

Did you download BleachBit from www.bleachbit.org, the PortableApps site/system, or somewhere else?

**Comment by az0** [comment]
I could not reproduce with Windows 10 and BleachBit 3.9.0  (revision 1a0c53e95a25)

**Comment by az0** [comment]
I could not reproduce with Windows 10 and BleachBit 3.1.0 build 1511 portable (similar to 3.2.0 final release available on www.bleachbit.org)

@liar666  Are you using the PortableApps.com version?

**Comment by liar666** [comment]
Thanks for the responses.

I tried again, directly asking to run BleachBit as Admin and it works...

I was apparently fooled by the fact the running it as normal user raises a UAC warning, and I thought this was sufficient to grant the correct rights to the app.

Sorry for the wasted time.
