### ISSUE TITLE
BleechBit was pulled off the system in openSuse-Tumbleweed

### ISSUE THREAD

**Issue by NumDeP** [bleachbit/bleachbit#796]
I read somewhere that because BB wasn't updated to python 3 so it was deleted. I was wondering could you please fix this and make it similarly available as in the Leap version of openSuse. Seeing as it's practically the exact same OS perhaps it wouldn't be too difficult of a task. 

**Update:**

Running BB with most of the features ON, except Data Wipe of course, on the occasion it does cause a small crash after completion.

I don't know if you're familiar with Brave Browser but it's slowly becoming even more popular and because it use the Chromium codebase I think BB sort of does pick it up. I thought I'd just mention their link just in case you wanted to cc them to avoid any kind of mishaps because it's a browser based around crypto and some stored data may be not ideal to delete - https://github.com/brave/brave-browser/issues

Thanks

**Comment by az0** [comment]
Try this [Tumbleweed rpm package](https://build.opensuse.org/package/binaries/home:andrew_z/bleachbit/openSUSE_Tumbleweed). It has the Python 3 version of BleachBit. Is this what you meant by "fix this"?

**Comment by NumDeP** [comment]
Hi @az0 yeah sure that is what I meant, sorry I wasn't clear enough. I didn't know if you aware of the fact that BB could be wiped off the system on a simple update because of an outdated language.

**Comment by NumDeP** [comment]
@az0 Do you seriously have to login to that site to download rpm package?

**Comment by az0** [comment]
No. Try [this URL ](https://software.opensuse.org//download.html?project=home%3Aandrew_z&package=bleachbit#directopenSUSE )instead, or here is [the RPM](https://download.opensuse.org/repositories/home:/andrew_z/openSUSE_Tumbleweed/noarch/bleachbit-3.9.0-1.4.noarch.rpm).

**Comment by NumDeP** [comment]
Hi @az0 this was the result:

```
@linux-lsni:~> sudo zypper install bleachbit
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides python3-gnome needed by bleachbit-3.9.0-1.4.noarch
 Solution 1: do not install bleachbit-3.9.0-1.4.noarch
 Solution 2: break bleachbit-3.9.0-1.4.noarch by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2

 
Resolving dependencies...
Resolving package dependencies...

The following 2 NEW packages are going to be installed:
  bleachbit python3-scandir

2 new packages to install.
Overall download size: 530.8 KiB. Already cached: 0 B. After the operation, additional 2.5
MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
```

Firstly how do I fix this and why is it that unlike `python3-scandir`, `python3-gnome` can't also be provided as an additional package if it isn't installed?

Thanks

**Comment by az0** [comment]
I will look into the dependencies.

Until then, would you please try running it from a terminal? There might be important information printed to the console to explain why it doesn't show when you click on it.

**Comment by NumDeP** [comment]
@az0 I got this 

```
@linux-lsni:~> bleechbit
If 'bleechbit' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf bleechbit
Nightingale@linux-lsni:~> bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/GUI.py", line 25, in <module>
    from bleachbit import GuiBasic
  File "/usr/share/bleachbit/GuiBasic.py", line 29, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by az0** [comment]
That is helpful. It seems a dependency related to GTK is not installed. I will check into it.

**Comment by az0** [comment]
I set up a clean OpenSUSE Tumbleweed machine that runs KDE, so it didn't have the GTK packages originally needed.   Then I fixed the dependencies and tested it on this system. It worked for me.

Please try on your system.  Try [this URL ](https://software.opensuse.org//download.html?project=home%3Aandrew_z&package=bleachbit#directopenSUSE ) and choose OpenSUSE, then grab packages directly, then pick the noarch RPM.

**Comment by NumDeP** [comment]
Thank you for the quick fix @az0. It's working alright now.

**Comment by az0** [comment]
I think your package is old, so please remove the bleachbit package using zypper or RPM.  Then install the latest BleachBit version, which is [currently 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta).  I tested this on Tumbleweed, and the `sudo zypper dup` command succeeded.

**Comment by ediowar** [comment]
openSUSE Tumbleweed official release 4.0.0 https://software.opensuse.org/package/bleachbit?search_term=bleachbit Old error. Is this a mistake of yours or the maker of the package?
```
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/GUI.py", line 25, in <module>
    from bleachbit import GuiBasic
  File "/usr/share/bleachbit/GuiBasic.py", line 29, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 3.0
```

**Comment by az0** [comment]
> Is this a mistake of yours or the maker of the package?

It looks like the RPM package is missing a dependency. Recently I agreed to maintain the openSUSE package, but I haven't started yet. Feel free to open an issue for that (either at openSUSE or here), and I will look into it.

**Comment by ediowar** [comment]
Posted  at https://build.opensuse.org/package/show/openSUSE%3AFactory/bleachbit It's all right?

**Comment by az0** [comment]
> Posted at https://build.opensuse.org/package/show/openSUSE%3AFactory/bleachbit It's all right?

That's the production package. You can post a bug report at the development package here https://build.opensuse.org/package/show/utilities/bleachbit .

I have the fix ready, and I'm working on submitting it. The fix is simply to add a dependency for the missing package `typelib-1_0-Gtk-3_0` .
