### ISSUE TITLE
Dark mode for Windows 10 theme

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#801]
I can toggle it, but toggling has no effect on how it the theme looks.
```
BleachBit version 3.9.0
Build number 1545
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
platform.win32_ver[1]() = 6.2.9200
platform.platform = Windows-8-6.2.9200-SP0
platform.version = 6.2.9200
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
```

**Comment by az0** [comment]
In build 1545 the theme shown is Windows 10, so that diagnostic information is misleading because it shows the GTK-level default theme. The Windows 10 theme does not have a dark mode variant.

Build 1547 adds an option to toggle the Windows 10 theme. When the Windows 10 theme is disabled, then the dark mode will work because Adwaita has a dark mode variant.

The way to fix this bug is to disable the dark mode option when the Windows 10 theme is enabled.

**Comment by ediowar** [comment]
Fixed in build 1545.

**Comment by az0** [comment]
I added a change to disable the button for dark mode when the Windows 10 theme option is checked.

**Comment by WildByDesign** [comment]
> In build 1545 the theme shown is Windows 10, so that diagnostic information is misleading because it shows the GTK-level default theme. The Windows 10 theme does not have a dark mode variant.

@az0  I was playing around with these new builds and new theme the other day and realized that it does, in fact, have a very nice dark theme. However, it was a trick to enable it properly.

In the `\BleachBit-Portable\themes\windows10` directory, I simply had to rename `gtk.css` to some sort of backup name, then rename `gtk-dark.css` to `gtk.css` and then start BleachBit again and the Dark theme matches Windows 10 dark mode apps quite well.

Therefore, somehow the switch between Dark mode on the Windows 10 theme needs to take into account the `gtk-dark.css` file as well and all is good. Cheers!

**Comment by az0** [comment]
@WildByDesign 

Thanks for pointing that out. I believe you did it, and I am curious what it looks like. Until I have a chance to work on it, would you please post a screenshot?

**Comment by WildByDesign** [comment]
@az0  You're welcome. Yes, of course. I will attach screenshot to this comment.

![bb-dark](https://user-images.githubusercontent.com/26308319/76088405-00173a00-5f86-11ea-8d31-4d10c28871e5.png)

So it seems as though, whoever designed this GTK3 theme, has done a pretty good job of matching the UWP specific designs for Windows 10 apps, not so much Win32 apps though. Similar to UWP apps, it's a borderless design with flat black or flat white/light colour options. It's quite nice.

**Comment by az0** [comment]
I am targeting this to 4.2 instead of 4.0 because in 4.0 there is a workaround to avoid confusion. (The workaround is the ineffective dark mode option is disabled.) In 4.2, I will investigate how to enable the dark mode with the checkbox.
