### ISSUE TITLE
Wipe Free Space function freezes BleachBit

### ISSUE THREAD

**Issue by gitthepie** [bleachbit/bleachbit#802]
I'm running BleachBit 3.2.0 on Linux. Choosing "Wipe Free Space" from the BleachBit menu, then picking a location to wipe causes BleachBit to freeze. After I force quit BleachBit, I was unable to reopen the app. System Monitor shows no process with the word "BleachBit" in it. Perhaps the process is under another name?

**Comment by az0** [comment]
Which kind of Linux?

Is the location special, like a removable drive or network location?

Before forcing it to quit, how long did you wait?

The process could also be under python or python2

**Comment by gitthepie** [comment]
I have to admit I wasn't keeping track, but it felt like around 5 minutes. The location was a removable flash drive, and it should take only about 5 minutes to finish wiping. I can get an exact time for you if it's important, but I'm back on version 2.2 right now because downgrading fixed the problem.

Thank you for the tip on the process name. I do see python 2 as the process name for version 2.2 of BleachBit.

If needed, I'm willing to do further testing for 3.2 if it would help isolate the problem. I'm running Linux Mint 19.1 Tessa 64-bit (Mate).

**Comment by az0** [comment]
About the timing, I was wondering whether it was more than 30 seconds, so that answered my question.

How long does it take to wipe the same removable drive with BleachBit 2.2?

Note to self, Linux Mint 19.01 is based on Ubuntu 18.04.

**Comment by gitthepie** [comment]
Sorry for the delay. Since I still had both installers lying around, I did formal testing with both, on the same computer (I reinstalled the newer version to make it happen). It turns out the bug is of a different nature than I initially believed.

On version 2.2 of BleachBit, the wipe free space function took 7 minutes and 45 seconds to finish. With version 3.2 of BleachBit running on the same drive, the wipe free space function _appeared_ frozen up as soon as I started it, but just to make sure BleachBit 3.2 wasn't just appearing nonresponsive while doing work in the background, I checked again after waiting about 9 minutes. I believe the wipe actually finished, though the message displayed was ambiguous: "Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space." Under the message though, BleachBit 3.2 showed this:

Disk space recovered: 0
Files deleted: 0
Special operations: 1

If I'm correct in believing that the above message means BleachBit 3.2 actually finished its wipe, then I was wrong that BleachBit 3.2 was frozen while I attempted the wipe.

This behavior is definitely still a problem. BleachBit 2.2 always informed me of its progress with an ETA every time I switched back to the window; it was never completely nonresponsive as BleachBit 3.2 is. The responsiveness and ETA help me to get a better idea of roughly how long the task will finish, but I'm deprived of this information in 3.2. Because of this limitation, I'll have to stick with 2.2 for now.

**Comment by az0** [comment]
@gitthepie 
Would you please test a potential fix? 

I just pushed a new version to OBS, and it should be built in a few minutes.

1. Go to the [OBS download page](https://software.opensuse.org//download.html?project=home%3Aandrew_z&package=bleachbit)
2. Click Ubuntu
3. Click grab package directly
4. Pick the package for Ubuntu 18.04 (the base for Linux Mint 19.1)
5. Install it
6. Run it
7. Open the diagnostics window from the hamburger menu
8. Verify the revision is c96e4e87
9. Re-run the wiping test

I expect it will be more responsive like BleachBit 2.x.

**Comment by az0** [comment]
Now the RPM packages are available from the page [BleachBit 3.9.0 beta](https://www.bleachbit.org/news/bleachbit-390-beta)

**Comment by gitthepie** [comment]
Thanks for the update! Is the BleachBit 3.9.0 beta equivalent to the version you wanted me to test, or do you still want me to test the Opensuse one?

**Comment by az0** [comment]
They're basically the same, but I would use the second one I mentioned because it's a little newer

**Comment by gitthepie** [comment]
I have odd results to report. I tested all 3 versions of BleachBit (2.2, 3.2, and 3.9) across 2 different machines. One machine was virtual while the second was physical. The physical machine is the same on I initially experienced this bug on. My results on the virtual machine reflect testing on overwriting of the virtual hard drive rather than on the flash drive. Both machines were running Mint 19.1.

For BleachBit 2.2, testing on both machines was uneventful. The window responded normally.

For BleachBit 3.2, the results diverged. In the virtual machine, the window responded normally, while on the physical machine, the window was unresponsive until the wipe had been completed. These results are to be expected based on my prior test.

For BleachBit 3.9, testing failed to complete on both machines due to this error:

`Error: _gui.free_disk_space: Function: Overwrite free disk space /media/xxxxx/xxxxx (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 145, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Cleaner.py", line 744, in wipe_path_func
    for ret in FileUtilities.wipe_path(path, idle=True):
  File "/usr/share/bleachbit/FileUtilities.py", line 978, in wipe_path
    truncate_f(f)
  File "/usr/share/bleachbit/FileUtilities.py", line 678, in truncate_f
    f.truncate(0)
  File "/usr/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 28] No space left on device

Disk space recovered: 0
Files deleted: 0
Errors: 1`

The error was almost instant in the virtual machine, preventing me from doing much testing of window behavior. However, on the physical machine, it appeared unresponsive as in version 3.2 until after the error had forced an end to testing.

**Comment by mkhon** [comment]
Which 3.9 build have you tested? I believe this is fixed in the latest 3.9.0 builds

**Comment by gitthepie** [comment]
The file I tested was https://download.bleachbit.org/beta/3.9.0/bleachbit_3.9.0_all_ubuntu1804.deb

When you say "this is fixed" did you mean the unresponsiveness or the new error I posted in code lines?

**Comment by mkhon** [comment]
I mean both

**Comment by az0** [comment]
I did not get OSError 28 on Ubuntu with BleachBit Git revision 12523a76cd18134ee0c19006ccc3fa98212d61d3 . 

@gitthepie 
I'd appreciate you testing a newer version. You can either [run from source](https://docs.bleachbit.org/dev/running-from-source-code.html) now, or soon I will post a new .deb package.

**Comment by gitthepie** [comment]
Is the right command to clone the respository git clone https://github.com/bleachbit/bleachbit.git or is it git clone https://github.com/bleachbit/bleachbit?

**Comment by mkhon** [comment]
@gitthepie 

<img width="1286" alt="Screen Shot 2020-04-07 at 10 03 41 " src="https://user-images.githubusercontent.com/3022749/78625821-3e6e8480-78b7-11ea-90df-7eb13751e06a.png">

So it's https://github.com/bleachbit/bleachbit.git

**Comment by gitthepie** [comment]
All right, I managed to do the test by running BleachBit from source (version 3.9.1). The version in the virtual machine worked perfectly. No errors, and it was responsive for at least the first 30 seconds into the test. Only towards the end of the test did the window stop responding. This might be normal though; the test finished shortly thereafter.

On the physical machine, 3.9.1 can't be unminimized while the test is running. The test does finish without error though. And on the physical machine, 2.2 does respond normally while the test is running.

What could account for the difference between 2.2 and 3.9.1 on the same physical machine?

**Comment by mkhon** [comment]
@gitthepie 

1) how much free space do you have in the VM (where the window stopped responding towards the end of the test). Also, which filesystems do you have in the VM (is it ext3 by any chance?)

2) on the physical machine - does it respond while the test is running (is the behavior the same as in VM)? Additionally, which filesystems (types) do you have on the physical machine?

@az0 so there is no error anymore, but BleachBit is not responsive sometimes during free space cleaning.

**Comment by gitthepie** [comment]
1. The virtual machine has 13 GB free space total. Its virtual hard drive is Ext4.

2. On the physical machine, BleachBit ran from source cloned to an Ext4 partition on the hard drive, but I wasn't wiping the hard drive during the test; I instructed BleachBit to wipe a FAT32 flash drive. The tests described below are both from running BleachBit version 3.9.1 from source:

On the physical machine, BleachBit wasn't responsive during the wipe when I ran the wipe on the physical machine (directing it to wipe the flash drive), but after the wipe was done, BleachBit responded normally again.

On the virtual machine, which I ran only on the virtual machine's hard drive (not the physical flash drive I used to test the physical machine), BleachBit did respond normally for most of the wipe process. When I said that it became unresponsive near the end, it was only for a few seconds and those few seconds could have been from the system itself being unresponsive due to deleting a massive file. I would say the behavior on the virtual machine was normal. It's the physical machine that exhibited abnormal behavior (by being unresponsive for the entire wiping process).

**Comment by az0** [comment]
In the current versions (BleachBit 3.9.2 and soon 4.0.0) some degree of unresponsiveness is expected because the GUI and cleaning happen in the same process, but the GUI shouldn't freeze for more than two seconds.

>When I said that it became unresponsive near the end, it was only for a few seconds and those few seconds could have been from the system itself being unresponsive due to deleting a massive file

Good observation. I see in the code that during this phase, there is an opportunity to improve responsiveness by yielding to the GUI between file deletes, when there are many files to delete. Let's try this after BleachBit 4.0.0 is released.

**Comment by ediowar** [comment]
I have tested. Fixed.

**Comment by az0** [comment]
I am closing because this seems to be fixed

**Comment by gitthepie** [comment]
Agreed! The problem is fixed for sure.
