### ISSUE TITLE
Using BleachBit as a component of an app

### ISSUE THREAD

**Issue by Atrate** [bleachbit/bleachbit#803]
Hello!

I am thinking of integrating BleachBit into my app by downloading the latest portable version on program run and executing it.

My questions are:
- What attribution is required to comply with the license? Can I just mention that BB is used in the "About" section of my app?
- Is there any way to automatically download the latest version or do I need to bump the DL link each time a new version of BB comes out?

Thanks in advance!

**Comment by az0** [comment]
>I am thinking of integrating BleachBit into my app

What is the app?

The method of integration is significant for the license. 

>What attribution is required to comply with the license? Can I just mention that BB is used in the "About" section of my app?

Please see the [Frequently Asked Questions about the GNU Licenses](https://www.gnu.org/licenses/gpl-faq.en.html).

>Is there any way to automatically download the latest version or do I need to bump the DL link each time a new version of BB comes out?

There is not one link that downloads the latest version

**Comment by Atrate** [comment]
> What is the app?
The method of integration is significant for the license.

It's an app "for dummies" that would perform simple tasks on Windows computers with an easy UI. It would run BleachBit's cleaning in the background after the user presses a button. It's a Qt project if it's important.

**Comment by az0** [comment]
What is the name of the app?

Again, the method of integration is not clear to me. 

I am assuming your application is not licensed under the GNU GPL and you do not want it to be.  If you create a combined work, then application will be licensed under the GNU GPL, so I recommend carefully reading the whole GNU FAQ and in particular the question: [I'd like to incorporate GPL-covered software in my proprietary system. I have no permission to use that software except what the GPL gives me. Can I do this? ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem).

I cannot give you legal advice. In case of any ambiguity, you might want to consult a knowledgeable attorney.

Is it OK to close this issue?

**Comment by Atrate** [comment]
So I presume that if I release the app under the GPLv3 i should not have problems?

(it's only a concept now, no name yet)

**Comment by az0** [comment]
Using the same license helps, and I think a command line integration avoids a "combined work," so they will be considered separate software. Again, I am not a lawyer, but what I see here is that you should provide attribution and equivalent access to the source code. I guess the access to the source code could be a link.

Best wishes on your application.
