### ISSUE TITLE
Issue: wrong permissions after .bash_history cleaning as root

### ISSUE THREAD

**Issue by klslz** [bleachbit/bleachbit#808]
BleachBit version 3.9.0
Fedora 31 (Workstation Edition)

I ran a cleaning on .bash_history as root

ISSUE1: This cleaned also all other users .bash_history.

ISSUE2: All file ownerships changed to root.

I guess the .bash_history gets removed and regenerated instead of cleared (cat /dev/null > .bash_history). 
Clearing would protect the ownership. This should be easy to solve.

And perhaps root should clear JUST root anyhow. 
All other users should be in charge of cleaning their own bash_history.

**Comment by az0** [comment]
I tested it like this
1. I logged in to Fedora 31 as a normal user (uid=1000)
1. I installed BleachBit version 3.9.0 (Git revision f0f93b44) via rpm
1. I used `stat ~/.bash_history` to verify the permissions of the file (uid=1000)
1. I ran 'sudo bleachbit -c bash.history`. It deleted `/root/.bash_history`.
1. I used `stat ~/.bash_history` to verify the permissions of the file (uid=1000)

I could not reproduce the problem.

The [bash cleaner](https://github.com/bleachbit/bleachbit/blob/master/cleaners/bash.xml) simply deletes the `~/.bash_history` file. It doesn't recreate the file or anything like that. 

Any hints on how I could reproduce it?

**Comment by klslz** [comment]
Ok. I found the issue.

bleachbit deletes the .bash_history instead of emptying it.

I had another (my own) cleaner cron job running in the background as "root", that also cleaned
the .bash_history. I've been using  "cat /dev/null > /home/1234/.bash_history"

As soon as beachbit got the bash_history removed, my root cron job generated a new one during night with. Since it was new it got root permissions.

That's of course easy to solve from my side.

However. You might consider to empty the file instead of removing it.
 
The case can be closed.

Sorry for the confusion.
