### ISSUE TITLE
Title bar with gtk3-nocsd

### ISSUE THREAD

**Issue by luigifab** [bleachbit/bleachbit#809]
GTK 3 removed the title bar, but with [gtk3-nocsd](https://github.com/PCMan/gtk3-nocsd), we can re-add it.

But this does not work with Bleachbit 3.0.1 on Debian testing with gtk 3.24.13.

**Comment by az0** [comment]
So is this a problem with gtk3-nocsd then? On Linux, BleachBit uses the system's GTK themes. (In other words, BleachBit on Linux doesn't use a custom theme.)

**Comment by luigifab** [comment]
Okay! I found somethings.

In [bleachbit/GUI.py](https://github.com/bleachbit/bleachbit/blob/master/bleachbit/GUI.py), there is: `self.set_titlebar(self.headerbar)`

When I remove it, the standard window decoration appear, but the toolbar is lost. But the GTK inspector of the bleachbit window start without standard window decoration.

**Comment by luigifab** [comment]
The problem is fixed with [gtk3-classic](https://github.com/lah7/gtk3-classic).
gtk3-classic replace gtk3-nocsd.

![image](https://user-images.githubusercontent.com/31816829/152691873-d4fc9dcc-ab19-4219-8dc9-d861f4ebdf24.png)

**Comment by MorsMortium** [comment]
There is also my library for all GTK versions, which also works for Bleachbit https://codeberg.org/MorsMortium/GTK-NoCSD
