### ISSUE TITLE
bleachbit doas error,

### ISSUE THREAD

**Issue by FrostKnight** [bleachbit/bleachbit#811]
This error specifically happens when i use doas to load bleachbit,

Invalid MIT-MAGIC-COOKIE-1 key/usr/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)

https://github.com/slicer69/doas

Although it is an older version of bleachbit so I am not sure if this matters to you, I am just curious if there is an easy fix for it. That I could do on my end,

its 1.12 the version,  does bleachbit auto rely on sudo in linux?
Well anyways let me know if you have an answer that is helpful.

**Comment by az0** [comment]
Which Linux distribution do you use?

BleachBit version 1.12 was released 4 years ago, and it is no longer supported. Would you please try a new release? There are [installation packages for many Linux distributions](https://www.bleachbit.org/download). Let me know how this goes.

**Comment by FrostKnight** [comment]
Sure, but my linux distro is a bit odd. Also, I am curious if you need sudo to use bleachbit in root. 

aka, sudo bleachbit or su then bleachbit 

rather than well you know.

But i will try compiling from source.  

ill let you know if i can.

**Comment by FrostKnight** [comment]
got this error when i did the second step in compiling it. :/

**Comment by FrostKnight** [comment]
Actually, editing this as, it is solved now, 

Doing this helps me install the latest:  make -C po 
then:  python3 bleachbit.py

if i did make -C po local 

it would result in that weird error. So I will close this.

**Comment by az0** [comment]
I think BleachBit works with sudo, su, gksu, pkexec, and other similar privilege escalation systems. 

I think the problem you are having with doas is not related specifically to BleachBit. Try doing a [Google search for the error message](https://www.google.com/search?q=Invalid+MIT-MAGIC-COOKIE-1+keyUnable+to+init+server) and read some of the results.

**Comment by FrostKnight** [comment]
I haven't seen any related issues so its kind of odd...

**Comment by abitrolly** [comment]
@FrostKnight because BleachBit works with `sudo` I guess the bug is in `doas` then. Most likely it doesn't pass some environment variable or other data which GTK needs. I suggest trying other GTK apps, such as `meld` and raising the issue on their tracker if that repeats for them as well.

As for BleachBit side, please post the output of `python3 bleachbit.py --sysinfo` with the latest source here. Could be useful for future reference, at least to see the version of Gnome used.

**Comment by FrostKnight** [comment]
Hmm...  yeah, this happens with nitrokey-app, lxtask, this, and other things.  So I guess, this issue is your bug at all. 

So I guess this should be closed since its a much larger issue...

**Comment by FrostKnight** [comment]
Meant to say, "isn't... your bug at all... 
Can't edit my reply btw, because github is going all webcomponents.  

Aka, I use palemoon... ;)

I hope its okay, but I will lock for now.

**Comment by abitrolly** [comment]
@FrostKnight feel free to raise an [issue with `doas`](https://github.com/Duncaen/OpenDoas) and link it here. Maybe it will get fixed one day. )
