### ISSUE TITLE
eGambit false positive for BleachBit 3.9.0 build 1570

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#816]
This version was digitally signed

[BleachBit-3.9.0.1570-setup.exe](https://www.virustotal.com/gui/file/9123783b35fabad1f6ba45932aa986bdb16dab0cc6ed76b3fa66f8cfea80c179/detection)

BleachBit-3.9.0.1570-portable.zip: Unable to process file type

[BleachBit-3.9.0.1570-setup-English.exe](https://www.virustotal.com/gui/file/ceefdd92ce3ebf023b221804158a77ce1ae87accfaa7ca30fa3b495d485c5309/detection)

**Comment by az0** [comment]
I reported the two hashes to the vendor via their web form

**Comment by az0** [comment]
BleachBit-3.9.0.1570-setup.exe: Unsafe.AI_Score_100%

**Comment by az0** [comment]
I am waiting on the vendor. Problem continues

BleachBit-3.9.0.1570-setup.exe: Unsafe.AI_Score_100%

**Comment by az0** [comment]
Still an issue... Waiting on vendor

**Comment by az0** [comment]
Still an issue...
BleachBit-3.9.0.1570-setup.exe: Unsafe.AI_Score_100%

**Comment by az0** [comment]
It's up to the vendor now, and 3.9.0 will soon be obsolete

**Comment by ediowar** [comment]
BleachBit-3.9.2.1624-setup.exe [2/70](https://www.virustotal.com/gui/file/c90a823bd4f05f942c7998745131f44ffae5d97e8000008339cc0824d20b149c/detection)
Will there be a false positive for this file if not using UPX?

**Comment by az0** [comment]
UPX is just one of a hundred factors that the antivirus vendors use to flag software. Even without UPX there will sometimes be false positives

**Comment by ediowar** [comment]
Creation Time 2025-12-20 04:05:01  https://www.virustotal.com/gui/file/a7606ced583e1662a4f048833c09dac1a4e0c243f15937047b2101b67da44f8f/detection

**Comment by az0** [comment]
>Creation Time 2025-12-20 04:05:01 https://www.virustotal.com/gui/file/a7606ced583e1662a4f048833c09dac1a4e0c243f15937047b2101b67da44f8f/detection


Yes, I confirm unicodedata.pyd has a creation time in 2025. It's a timestamp embedded inside the executable (not the metadata on the regular file itself). The unicodedata.pyd that comes with Python  3.4.4 is dated 2015:12:20.

During the build process, it is modified by strip and UPX. I tried it on my Linux system (which is different than the Windows build process), and it didn't advanced the date.

I'm not sure. It's weird, but I'm not sure it hurts anything. Soon I'd like to update the Windows build from Python 3.4.4 to Python 3.8. This will involve some deeper changes. If it still happens then, maybe it's worth another look.
