### ISSUE TITLE
64-bit Bleachbit

### ISSUE THREAD

**Issue by Bamajon1974** [bleachbit/bleachbit#820]
Where are native 64-bit Bleachbit binaries? If none, when are they expected to be available?
Thanks in advance!

**Comment by az0** [comment]
BleachBit has always supported 64-bit on Linux, so I assume you mean for Windows?

What advantages do you see? 

Here are some thoughts

* The 32-bit BleachBit executables run on Windows 64-bit WoW64
* The 32-bit executables are smaller than 64-bit executables
* 32-bit BleachBit can clean 64-bit applications
* BleachBit does not need to allocate gigabytes of memory (a major benefit of 64-bit systems)
* BleachBit is not CPU-intensive, so users would not notice a benefit from 64-bit operations

**Comment by az0** [comment]
I am closing because no response in 312 days. I don't see a major benefit of the 64-bit version, but it's worth revising after resolving this issue: https://github.com/bleachbit/bleachbit/issues/848

**Comment by Bamajon1974** [comment]
Thank you!

**Comment by Bamajon1974** [comment]
Just wanted to throw out a new reason to compile 64-bit BleachBit binaries...to ensure compatibility with future Win OS's. 
Apparently MS won't release a Win11 32-bit OS (but apparently will support 32-bit programs) 
https://www.neowin.net/news/here-are-the-official-minimum-system-requirements-for-windows-11/

**Comment by az0** [comment]
GTK, which powers the BleachBit GUI, remains challenging to build on Windows. However, several options now exist for running BleachBit as 64-bit :

1. An experimental [wxWidgets GUI with a 64-bit Windows build](https://ci.bleachbit.org/?prefix=dl/5.1.2.3501-wx-gui-mvp/) is available.
2. [Run from source with vanilla 64-bit Python on Windows](https://docs.bleachbit.org/dev/running-from-source-code.html) (CLI only).
3. [Run from source with 64-bit MSYS on Windows](https://docs.bleachbit.org/dev/running-from-source-code.html) with GTK support.
4. A [text user interface](https://www.bleachbit.org/news/bleachbit-text-user-interface) offers a 64-bit Windows build with both CLI and TUI.
