### ISSUE TITLE
Still won't open window (problem since 2.3)

### ISSUE THREAD

**Issue by sjudenim** [bleachbit/bleachbit#821]
I have the same issue reported here https://www.bleachbit.org/forum/bleachbit-unstable-builds-wont-open-windows

Program is running in the background but the window is never visible. Console is blank

Windows 8.1
Latest portable version of BB

**Comment by az0** [comment]
Does latest portable mean latest stable (3.2.0) or latest beta (3.9.0)?

Do you have multiple monitors?

When you write that the console is blank, do you mean you ran bleachbit_console.exe instead of bleachbit.exe?

**Comment by sjudenim** [comment]
Stable (I've actually had this problem since the same version release mentioned in that forum link.

Single monitor.

Yes, the bleachbit_console.exe is blank.

**Comment by az0** [comment]
This looks like issue #663 .

**Comment by az0** [comment]
@sjudenim 


Would you please mind testing [ BleachBit 3.9.2 beta](https://www.bleachbit.org/news/bleachbit-392-beta) ?

**Comment by sjudenim** [comment]
Tested v.3.9.2.1624 (portable)

First start had the same problem.

Task manager showed it using a lot of resources with no window showing.

Forced closed it and opened the console, and it loaded up.

Closed that and opened the regular exe, and it worked.

Seems to be okay now but that first start has me a little worried. I will keep testing over the next few days and get back to you. 

Thanks

**Comment by mkhon** [comment]
I see a delay during first start too but it is about 10-20 seconds.

**Comment by ediowar** [comment]
Ran bleachbit_console.exe. The delay is about 4-5 seconds if Windows Defender is enabled. If Windows Defender is disabled, there is practically no delay. Who has which antivirus?
Windows 8 SL 64-bit
BB v.3.9.2.1624 (portable)

**Comment by az0** [comment]
@sjudenim 

> Tested v.3.9.2.1624 (portable)
> 
> First start had the same problem.
>
> Task manager showed it using a lot of resources with no window showing.

For another chance at a first start, try deleting the configuration file `%appdata%\bleachbit\bleachbit.ini`

Another way to reproduce it might be to reboot. This might make your antivirus software forget that it scanned BleachBit. (This is my guess combined with ediowar's observation.)

> Forced closed it and opened the console, and it loaded up.
> 
> Closed that and opened the regular exe, and it worked.
> 
> Seems to be okay now but that first start has me a little worried. I will keep testing over the next few days and get back to you.

After reading ediowar's comment, I am wondering whether this could be explained by intensive scanning of your security software. If the antivirus remembers that it scanned BleachBit, it would be faster the second time you start it (maybe until you reboot).

Which antivirus do you use? 

If you had the problem consistently, we could do a  troubleshooting experiment in which you disable the antivirus, but it sounds like now BleachBit consistently starts quickly.

**Comment by sjudenim** [comment]
@az0 

Windows Defender is all that is on my system and I have "Real time protection" turned off. I only use it periodically to scan. With that said, there is a process running that I can't disable that seems like real time protection "Antimalware Service Executable - Windows Defender Service"

**Comment by ediowar** [comment]
@sjudenim but you can add Antimalware Service Executable to Windows Defender’s exclusion list and check for malware infections. [How to fix ‘Antimalware Service Executable’ high CPU usage](https://blog.emsisoft.com/en/28620/antimalware-service-executable/)

**Comment by az0** [comment]
> Seems to be okay now but that first start has me a little worried. I will keep testing over the next few days and get back to you.

I will close because we've made some code fixes and you wrote "seems to be okay now." 

The slow start could be a separate issue, so if you continue having that after trying ediowar's suggestion about the exclusion list, please open a new issue.  Please do that after BleachBit version 4.0.0 is out for at least a week. Part of the antivirus vendor's safety formula (e.g., Windows Defender [SmartScreen](https://en.wikipedia.org/wiki/Microsoft_SmartScreen#Criticism)) includes popularity. BleachBit alpha and beta versions are not as popular as the stable release, when it's been out for a while. Another factor in the safety formula is the digital certificate: the alpha versions (from ci.bleachbit.org) are not digitally signed, while the beta and final versions are digitally signed, so they are generally considered safer by antivirus software.
