### ISSUE TITLE
Bad free space wiping

### ISSUE THREAD

**Issue by mavileo** [bleachbit/bleachbit#825]
Hi, when I want to wipe free space it dosent takes 2 or 3 hours like before (500go ssd with 350go space left) but its takes 10 min and all recent deleted files can be recovered with testdisk, someone know what's happen ?

**Comment by az0** [comment]
Are you on Windows or Linux?

Which version of BleachBit are you using now?

**Comment by az0** [comment]
There was no response for one year, so I am closing this issue. If you want to continue this discussion, feel free to add a comment to this issue.
