### ISSUE TITLE
Compatibility with https://github.com/MoscaDotTo/Winapp2 (Winapp2.ini)

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#828]
Is it possible to make BleachBit compatible (or at least run error-free) with https://github.com/MoscaDotTo/Winapp2 so that the latest Winapp2.ini can always be used?

See https://github.com/MoscaDotTo/Winapp2/issues/699 for a current discussion over there.

The issues reported in #241 and #369 seem to have resurfaced.

**Comment by az0** [comment]
> Is it possible to make BleachBit compatible (or at least run error-free) with https://github.com/MoscaDotTo/Winapp2 so that the latest Winapp2.ini can always be used?

This is too broad for an issue ticket, so I plan to close this ticket. We can still discuss the general topic in the closed issue, if you want.

The background is their Winapp2.ini  often had many serious syntax errors: [here are some examples](https://github.com/MoscaDotTo/Winapp2/issues?q=author%3Aaz0), and this was a major reason for me creating a separate Winapp2.ini repository. 

My Winapp2.ini repository isn't a for. It's a buffer. I fetch their latest Winapp2.ini file, check it for errors, and remove any entries that BleachBit doesn't support: right now that's one entry (shellbags).

> The issues reported in #241 and #369 seem to have resurfaced.

Do you mean using "their" Winapp2.ini or "mine"? If the problem exists in "my" version, please open a new ticket for each individual case. I just updated "my" Winapp2.ini, and I don't see any errors.

**Comment by az0** [comment]
This issue is like https://github.com/bleachbit/wishlist/issues/66

**Comment by Gitoffthelawn** [comment]
Thanks for your reply, and for offering to continue our discussion.

After reading your comments, I think I actually prefer your Winapp2.ini because it has an extra set of eyes on it checking for errors. :eyes:  Errors in a Winapp2.ini could cause massive data loss.

Can you add support for `ExcludeKey#=REG` in BleachBit?  Seems simple enough, but maybe I'm not thinking of something.

Regarding the resurfacing of #241 and #369, that was in regard to "their" Winapp2.ini, not yours.
