### ISSUE TITLE
Windows Security false positive for BleachBit 3.9.1

### ISSUE THREAD

**Issue by muessli** [bleachbit/bleachbit#842]
I wanted to install BleachBit-3.9.1.1589-setup.exe on a second computer and got a virus alarm:
Trojan:Win32/Wacatac.Clml

**Comment by az0** [comment]
muessli :Please let me know the name of the antivirus/security product that
reported the problem, so I can work with the vendor on resolving the false
positive.

Thank you for including the exact filename.

Andrew

**Comment by az0** [comment]
I see this with Windows Security and https://ci.bleachbit.org/dl/3.9.1.1612/BleachBit-3.9.1.1612-setup.exe

**Comment by az0** [comment]
I submitted bleachbit.exe to https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by az0** [comment]
@muessli 

Microsoft told me they whitelisted it. If you see the exact same issue soon because it was not resolved, reopen this ticket. (If you have a different issue, open a new ticket.)
