### ISSUE TITLE
"system cannot find the file specified" using shell integration

### ISSUE THREAD

**Issue by silentshotghost** [bleachbit/bleachbit#845]
When selecting multiple files 3-8 below 5mb in size bleachbit crashes and only deletes the first file loading, I consistently have to singly delete the files I can’t mass do it

**Comment by silentshotghost** [comment]
So i select multiple files to delete then right click and press shred then it gives me this https://imgur.com/a/QxoT6fR error i'm on windows 10 1909 build and here's bleachbit diagnostics
BleachBit version 3.2.0
Build number 1509
GTK version 3.18.9
SQLite version 3.28.0
FSE = mbcs
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\silent\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\silent\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_US', 'cp1252')
os.getenv('APPDATA') = C:\Users\silent\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\silent\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\silent\AppData\LocalLow
os.getenv('Music') = C:\Users\silent\Music
os.getenv('USERPROFILE') = C:\Users\silent
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\silent\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\silent\
platform.win32_ver[1]() = 10.0.18362
platform.platform = Windows-10-10.0.18362
platform.version = 10.0.18362
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 2.7.17 (v2.7.17:c2f86d86e6, Oct 19 2019, 20:49:36) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by ediowar** [comment]
> Build number 1509

Try latest build 1613 https://ci.bleachbit.org/

**Comment by silentshotghost** [comment]
same issue https://imgur.com/a/IbUXrGh

**Comment by az0** [comment]
>So i select multiple files to delete then right click and press shred 

The Windows shell context menu has an option "Shred files with BleachBit." This integration supports only a single file at a time.

Here is one workaround that supports many files
1. In Windows Explorer, copy the files to the clipboard
1. Open BleachBit
1. Click the application menu
1. Click the option _Shred Paths from Clipboard_

Another method is 
1. Open BleachBit
1. Click the application menu
1. Click _Shred Files_ and then choose the files you want gone

**Comment by silentshotghost** [comment]
yes i was using the "Shred files with BleachBit" ill try these methods

**Comment by silentshotghost** [comment]
option 1 works great thanks

**Comment by az0** [comment]
> option 1 works great thanks

OK, so I will close the issue
