### ISSUE TITLE
application menu is not translated

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#847]
Command run on Ubuntu 19.10
`LANG=hi_IN.UTF-8 python3 bleachbit.py`
Code revision 2d8a7f3abf85da7f44aa7f1cdf27afe4ab24b28f

The Hindi translation is 99.4% complete (missing two strings), so it is not a matter of missing translations.

![BleachBit 391 untranslated menu](https://user-images.githubusercontent.com/933680/78453303-09132e00-764e-11ea-8a58-e7adf3f30975.png)

This issue looks similar to https://github.com/bleachbit/bleachbit/issues/564 , but when I run `LANG=es_MX.UTF-8 python bleachbit.py`, the Spanish menu is translated.

**Comment by mkhon** [comment]
Is there the following warning in the console?

```
(bleachbit.py:4084): Gtk-WARNING **: 16:43:25.854: Locale not supported by C library.
	Using the fallback 'C' locale.
```
Looks like the locale is not configured (you need to do "dpkg-reconfigure locales" and tick "hi_IN.UTF-8" there.

**Comment by az0** [comment]
@mkhon 
Yes, you're exactly right
