### ISSUE TITLE
Update Python 3 in Windows installer

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#848]
For BleachBit 4.0, we updated Python 2.7 to Python 3.4. This was major progress and allowed a quicker release by keeping py2exe. However, Python 3.4 is EOL, and py2exe does not support Python 3.5+. The goal of this issue is to update the Windows installer to use a new version of Python---preferably Python 3.8.

Candidates for replacing py2exe include pyInstaller and cx_Freeze.

A related issue is the [GTK installer on Sourceforge](https://sourceforge.net/projects/pygobjectwin32/files/) also does not support Python 3.5+. An alternative is to install the msys32 environment and its package mingw-w64-i686-gtk3 .

**Comment by abitrolly** [comment]
The [official way](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started) to use PyGObject on Windows is through MSYS2.

However, this project https://github.com/wingtk/gvsbuild might provide replacement libs for newer Python.

**Comment by az0** [comment]
> The [official way](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started) to use PyGObject on Windows is through MSYS2.

I'd like to try this first. It looks simpler than gvsbuild

**Comment by Marvin0401** [comment]
Let me try on this.

**Comment by Marvin0401** [comment]
Hi @az0 , I've used pyinstaller to upgrade python version in windows, but I did not get it works yet. This is my result by using the python3.8 and pyinstaller (https://we.tl/t-Qu7S81E4ly). It seems runing, but I can not see any UI so I am tracking the issue now. I think I can fix it this week.

**Comment by az0** [comment]
> Hi @az0 , I've used pyinstaller to upgrade python version in windows, but I did not get it works yet. This is my result by using the python3.8 and pyinstaller (https://we.tl/t-Qu7S81E4ly). It seems runing, but I can not see any UI so I am tracking the issue now. I think I can fix it this week.

@Marvin0401  
The file is unavailable at that link because "the transfer expired."  The best way to share code is through GitHub forks and pull requests, which automatically build binaries for Windows.

**Comment by az0** [comment]
Update for Max on July 10th

>I've got py2exe partially working with a few hacks which I need to sort out:
>- not all required libs and files (new gtk3 layout) are copied
>- ssl certificates location need to be fixed
>- py2exe hangs sometimes when collecting dependencies (py2exe bug)
>- win32com.shell module crashes py2exe for some reason (works ok without py2exe) - this is the major issue which needs to be sorted out

Update from Max on August 26th

>Small status update: build now works out of the box from my devel branch.

>However, the issue with win32com.shell is still not resolved.

**Comment by abitrolly** [comment]
>  However, the issue with win32com.shell is still not resolved.

Can it be isolated to standalone example and reported upstream?

**Comment by az0** [comment]
There was some activity three days ago here https://github.com/microsoft/vcpkg/pull/22201

**Comment by abitrolly** [comment]
https://github.com/microsoft/vcpkg/pull/27026 is the fresh PR for the same change.

**Comment by kenrap** [comment]
Since that PR had merged recently, would building the Windows installer with vcpkg be a cakewalk now?

**Comment by abitrolly** [comment]
Somebody needs to try to gain the knowledge.

**Comment by kenrap** [comment]
Welp, it was a cakewalk to build the `gtk3` and `gobject-introspection` vcpkg ports on my Windows VM (along with the help of using [Chocolatey](https://chocolatey.org/) for installing `git` and `visualstudio2022-workload-vctools`). It's also faster to get up to speed than using gvsbuild. However, getting pip to install `pyobject` has been a total **PITA** during both cases.

```
gi\gimodule.c: fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory
```

I tried searching for solutions, but this stackoverflow post seems to be the "closest" to it, but I can't figure how to use `poetry` here for Bleachbit.

https://stackoverflow.com/questions/65830354/file-msvc-recommended-pragmas-h-missing-while-installing-pygobject-via-pip

**Comment by kenrap** [comment]
@abitrolly 
I appreciate the quick response! I've been tied up and haven't got around to replying sooner. I got this problem earlier after trying to build `cibuildwheel`. It's probably due to using Windows 11 with its unique quirks to finding third party Python modules. I've already installed `pypiwin32` and other related Windows-related modules based on the appveyor.yml file. So I'm lost once again unfortunately.

```
PS C:\Users\User\bleachbit> python -m cibuildwheel --platform windows

     _ _       _ _   _       _           _
 ___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|

cibuildwheel version 2.10.2

Build options:
  platform: 'windows'
  architectures: {<Architecture.x86: 'x86'>, <Architecture.AMD64: 'AMD64'>}
  build_selector: {'build_config': '*', 'skip_config': '', 'requires_python': None, 'prerelease_pythons': False}
  container_engine: 'docker'
  output_dir: WindowsPath('C:/Users/User/bleachbit/wheelhouse')
  package_dir: WindowsPath('C:/Users/User/bleachbit')
  test_selector: {'skip_config': ''}
  before_all: ''
  before_build: ''
  before_test: ''
  build_frontend: 'pip'
  build_verbosity: 0
  config_settings: ''
  dependency_constraints: DependencyConstraints(WindowsPath('C:/Python310/Lib/site-packages/cibuildwheel/resources/constraints.txt'))
  environment: {'assignments': []}
    cp36-win32: ParsedEnvironment([])
    cp36-win_amd64: ParsedEnvironment([])
    cp37-win32: ParsedEnvironment([])
    cp37-win_amd64: ParsedEnvironment([])
    cp38-win32: ParsedEnvironment([])
    cp38-win_amd64: ParsedEnvironment([])
    cp39-win32: ParsedEnvironment([])
    cp39-win_amd64: ParsedEnvironment([])
    cp310-win32: ParsedEnvironment([])
    cp310-win_amd64: ParsedEnvironment([])
    cp311-win32: ParsedEnvironment([])
    cp311-win_amd64: ParsedEnvironment([])
    pp37-win_amd64: ParsedEnvironment([])
    pp38-win_amd64: ParsedEnvironment([])
    pp39-win_amd64: ParsedEnvironment([])
  manylinux_images: None
  musllinux_images: None
  repair_command: ''
  test_command: ''
  test_extras: ''
  test_requires: []
Cache folder: C:\Users\User\AppData\Local\pypa\cibuildwheel\Cache

Here we go!


Building cp36-win32 wheel
CPython 3.6 Windows 32bit

Installing Python cp36...


                                                                       ✓ 0.00s
Setting up build environment...

+ 'C:\Python310\python.exe' -sS 'C:\Users\User\AppData\Local\pypa\cibuildwheel\Cache\virtualenv-20.16.5.pyz' --activators= --no-periodic-update --pip=21.3.1 --setuptools=59.6.0 --wheel=0.37.1 --python 'C:\Users\User\AppData\Local\pypa\cibuildwheel\Cache\nuget-cpython\pythonx86.3.6.8\tools\python.exe' 'C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\build\venv'
created virtual environment CPython3.6.8.final.0-32 in 339ms
  creator CPython3Windows(dest=C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\build\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=21.3.1, setuptools=59.6.0, wheel=0.37.1, via=copy, app_data_dir=C:\Users\User\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
+ python -m pip install --upgrade pip -c 'C:\Python310\Lib\site-packages\cibuildwheel\resources\constraints-python36.txt'
Requirement already satisfied: pip in c:\users\user\appdata\local\temp\cibw-run-r4r7rfok\cp36-win32\build\venv\lib\site-packages (21.3.1)
+ where python
C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\build\venv\Scripts\python.exe
C:\Python310\python.exe
C:\Users\User\AppData\Local\Microsoft\WindowsApps\python.exe
+ python --version
Python 3.6.8
+ python -c '"import struct; print(struct.calcsize('"'"'P'"'"') * 8)"'
+ where python
+ where pip
+ pip --version
pip 21.3.1 from C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\build\venv\lib\site-packages\pip (python 3.6)

                                                                       ✓ 3.18s
Installing build tools...

+ pip install --upgrade setuptools wheel -c 'C:\Python310\Lib\site-packages\cibuildwheel\resources\constraints-python36.txt'
Requirement already satisfied: setuptools in c:\users\user\appdata\local\temp\cibw-run-r4r7rfok\cp36-win32\build\venv\lib\site-packages (59.6.0)
Requirement already satisfied: wheel in c:\users\user\appdata\local\temp\cibw-run-r4r7rfok\cp36-win32\build\venv\lib\site-packages (0.37.1)

                                                                       ✓ 1.21s
Building wheel...

+ python -m pip wheel 'C:\Users\User\bleachbit' '--wheel-dir=C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\built_wheel' --no-deps
Processing c:\users\user\bleachbit
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\AppData\Local\Temp\cibw-run-r4r7rfok\cp36-win32\build\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\bleachbit\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\bleachbit\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-8fen7hou'
       cwd: C:\Users\User\bleachbit\
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\User\bleachbit\setup.py", line 37, in <module>
      __import__(m)
  ModuleNotFoundError: No module named 'pywintypes'
  ----------------------------------------
WARNING: Discarding file:///C:/Users/User/bleachbit. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

                                                                       ✕ 0.99s
Error: Command ['python', '-m', 'pip', 'wheel', 'C:\\Users\\User\\bleachbit', '--wheel-dir=C:\\Users\\User\\AppData\\Local\\Temp\\cibw-run-r4r7rfok\\cp36-win32\\built_wheel', '--no-deps'] failed with code 1. None
```

**Comment by mkhon** [comment]
@kenrap vcpkg gtk3 port that just got finally merged is missing introspection patch, which has not been merged ye

you can not build pygobject without introspection support enabled

**Comment by kenrap** [comment]
@mkhon Ah, that's explains it. And thank you for your work btw!

I suppose I should downgrade the f-string usage to `str.format` in my refactoring PR, since that's the only thing holding it back since I need at least 3.6 support.

**Comment by az0** [comment]
Python 3.10 alpha builds are here: https://ci.bleachbit.org/?prefix=dl/4.4.2.2265-mkhon-python310/

You may see a security error when visiting the ci.bleachbit.org site because Google Search flagged the Python 3.10 English-only installer without much explanation, so the whole site gets flagged in Chrome. I removed the file and am waiting on Google to review it.

There are some [known issues with 3.10 build](https://github.com/bleachbit/bleachbit/issues?q=is%3Aopen+is%3Aissue+label%3Amodernization), and please report any other issues. 

Based on the progress so far, I am closing the issue.
