### ISSUE TITLE
Using positional arguments with the GObject constructor has been deprecated.

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#850]
Windows 10 without Python environment/developer tools
BleachBit version 3.9.1
Build number 1612

This error showed once after cleaning. I will look for more details to reproduce it.

`Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "title, transient_for" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations`

**Comment by mkhon** [comment]
I can not reproduce this

**Comment by az0** [comment]
I cannot reproduce this

**Comment by abitrolly** [comment]
I suggest closing until it appears again.

**Comment by az0** [comment]
@abitrolly 
Good call
