### ISSUE TITLE
Not all cleaners in BB 3.9.0 beta with sudo

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#855]
[bleachbit_3.9.0_all_ubuntu1604.deb](https://download.bleachbit.org/beta/3.9.0/bleachbit_3.9.0_all_ubuntu1604.deb)
![Screenshot from 2020-04-04 22-48-25](https://user-images.githubusercontent.com/44164186/78500348-650cae00-7745-11ea-8488-6e26e3acad8c.png)

Without sudo there are all cleaners
![Screenshot from 2020-04-04 22-56-54](https://user-images.githubusercontent.com/44164186/78500480-30e5bd00-7746-11ea-937c-da6a50f9b028.png)

**Comment by az0** [comment]
When you first start as sudo, is there a message, "You are running BleachBit with administrative privileges for cleaning shared parts of the system, and references to the user profile folder will clean only the root account"?

**Comment by ediowar** [comment]
Yes, a message there is.

**Comment by az0** [comment]
I made a few changes that will help

1. After the "You are running BleachBIt..." message, I added a line break

2. I rearranged the start-up messages to show after the cleaners are loaded, so they show after the "automatically hiding" messages 

Good?

**Comment by ediowar** [comment]
Good.
