### ISSUE TITLE
Error when checking for updates in Ubuntu Mate 20.04

### ISSUE THREAD

**Issue by guifar** [bleachbit/bleachbit#857]
I installed on my laptop Ubuntu Mate 20.04 Beta, that include both Python 2.7.17 and 3.8.2. After restarted it, I downloaded and installed Bleachbit 3.9 Beta.
When executed "_sudo apt update_", Bleachbit show upgrade to 3.9.0-1 available, so when executed "_sudo apt upgrade_" the following error was shown:
_Setting up bleachbit (3.9.0-1) ...
/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if msgctxt is not None and msgctxt is not "":_
however Bleachbit was upgraded. I opened it and the following error message appeared:
Error when checking for updates: 
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 1160, in check_online_updates
    updates = Update.check_updates(options.get('check_beta'),
  File "/usr/share/bleachbit/Update.py", line 155, in check_updates
    opener.addheaders = [('User-Agent', user_agent())]
  File "/usr/share/bleachbit/Update.py", line 87, in user_agent
    dist = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'

**Comment by mkhon** [comment]
This is fixed in the latest master

**Comment by az0** [comment]
@guifar 

There is a package available here for testing:[ BleachBit 3.9.2 beta](https://www.bleachbit.org/news/bleachbit-392-beta)

**Comment by az0** [comment]
I am closing because we made a code fix. It's nice to have the reporting user confirm it, but it's been a while.

@guifar 
if the exact same issue remains, please reopen this issue. If you have a related problem or different problem, open a new issue.
