### ISSUE TITLE
leaves behind files named gdbus-nonce-file-[six characters]

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#858]
It's a little bit ironic (cue Alanis...), but I've determined that it is apparently BleachBit leaving temporary files behind.

Tested with BB portable v3.2.0 on Win7 64-bit.

BB creates files with the name `gdbus-nonce-file-[six characters]` in the current user's temp folder and does not delete them when it terminates.

It's actually kind of funny, because I've never seen other applications leave files behind with that name, so it leaves a fingerprint behind that BleachBit was run on the machine.

Can you fix please?

**Comment by ediowar** [comment]
I confirm. BB portable v3.2.0 and 3.9.1 build 1620 on Win8 64-bit. Run BleachBit as a regular user.

**Comment by az0** [comment]
Please test the fix in [CI build 1692](https://ci.bleachbit.org/) or later

**Comment by ediowar** [comment]
I tested, now there is no issue.
