### ISSUE TITLE
Something not clear

### ISSUE THREAD

**Issue by Yakleyn** [bleachbit/bleachbit#859]
Good day. A very incomprehensible and big problem arose. Conducted a scheduled computer cleaning using the Bleachbit program, as usual. Program version 3.2.0 for windows 10 64-bit. Carried out a full cleaning. At the stage: cleaning the system files, the Bleachbit program on my laptop (Acer aspire A515-51G-532B) hung, did not respond. I decided not to wait long and tried to go into the task manager (Ctrl + alt + delete). A message appeared: loading security settings. This message hung for a long time, so I decided to forcibly restart the laptop by holding the power button. The laptop shuts down. And now the essence itself. After switching on, the only thing that appears is the ACER logo. The system does not boot, first a dark blue screen, and then at the top left on a black background a white hyphen blinks - and that's all. The system does not boot. But that is not all. I can’t even enter the BIOS. No way. Not included, just a black screen. The laptop works, but nothing happens. The operating system is installed on the SSD. There is also a HDD, but temporary files were stored on it. That's how it is somehow. Maybe someone knows what is the reason? I damn just cleaned the laptop with this program.

**Comment by ediowar** [comment]
Have you tried [factory reset using Alt + F10](https://us.answers.acer.com/app/answers/detail/a_id/38202/)?

**Comment by Yakleyn** [comment]
No, I have not tried it. The laptop was handed over for repair, since Bios even starts up.

**Comment by ediowar** [comment]
[bios didn't open acer a515-51g](https://community.acer.com/en/discussion/575737/bios-didnt-open-acer-a515-51g)
[How do I get into the BIOS menu on A515-43-R19L (Aspire 5 Slim Laptop)?](https://community.acer.com/en/discussion/572584/how-do-i-get-into-the-bios-menu-on-a515-43-r19l-aspire-5-slim-laptop)
[Acer Aspire A515-51G-53JT keyboard problem](https://community.acer.com/en/discussion/536155/acer-aspire-a515-51g-53jt-keyboard-problem)

**Comment by Yakleyn** [comment]
No, I have not tried it. The laptop was handed over for repair, since Bios even starts up.

**Comment by Yakleyn** [comment]
thank you ediowar for your help, but they told me in the service center that some settings in the system were lost, they made a diagnosis, I still did not understand what this means, the cause of the incident also remains unclear to me. Because I could not even enter the BIOS, although I am sure of the correctness of the action. They said that it was necessary to apply some settings. Generally, thanks
