### ISSUE TITLE
"Shred Settings and Quit" vs. portable mode

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#862]
Windows 10
Build 1622 

In portable mode, the menu option "Shred Settings and Quit" correctly deletes the bleachbit.ini file. However, it should recreate a stub file, so next time the application starts in portable mode. It doesn't create the file despite this code, so this code isn't running at all or not running correctly.

```
# in portable mode, rebuild a minimal bleachbit.ini
bleachbit.Options.init_configuration()
```

**Comment by mkhon** [comment]
Fixed in #953
