### ISSUE TITLE
English installer installs localizations

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#864]
The installer `BleachBit-3.9.1.1623-setup-English.exe` installed 126 files worth 1.59MB in `C:\Program Files (x86)\BleachBit\share\locale`

The English installer is supposed to be smaller for people who don't want this, but the size is about the same.

BleachBit-3.9.1.1623-setup-English.exe (12,617,676 bytes)
BleachBit-3.9.1.1623-setup.exe (12,729,819 bytes)

**Comment by Gitoffthelawn** [comment]
I recommend using BleachBit to remove these unwanted files. ;)

**Comment by az0** [comment]
This issue is the same as https://github.com/bleachbit/bleachbit/issues/770

>All kidding aside, where are these other builds located?

Look for bleeding-edge builds at https://ci.bleachbit.org/ . Sometimes there are updates more than once daily.
