### ISSUE TITLE
The app take significantly longer to perform clean

### ISSUE THREAD

**Issue by NumDeP** [bleachbit/bleachbit#865]
I'm currently using the beta version 3.9.1xx on oS Tumbleweed and I've noticed that it takes significantly longer than it did on the much older versions. **Preview** is quicker but before or after pressing **Clean** it still takes around or perhaps over five minutes to perform clean even though there isn't much data to be cleaned.

Here are the features I've got enabled. I should also mention the only thing I've disabled other than vim is Wipe disk space in the main menu

![Screenshot_20200410_211338](https://user-images.githubusercontent.com/31957540/79020429-b4514500-7b70-11ea-9add-d754d8589a14.png)

**Comment by ediowar** [comment]
> look at the option Edit - Preferences - General - Overwrite Contents. Enabling this option makes BleachBit slower because more work is required to make files unrecoverable.

[Frequently Asked Questions ](https://docs.bleachbit.org/doc/frequently-asked-questions.htmll)

**Comment by NumDeP** [comment]
I understand that but in the much older versions this wasn't the case with the same features enabled. It seems in addition to the **Preview** files, additional attempts are made to continue clean but not many things get cleaned and it just parses through a rather large list.

**Comment by ediowar** [comment]
> I'm currently using the beta version 3.9.1xx on oS Tumbleweed and I've noticed that it takes significantly longer than it did on the much older versions. 

Do you run BB with the command `python3 bleachbit.py` ?
Tried [bleachbit-3.9.0-5.1.opensuseTumbleweed.noarch.rpm](https://download.bleachbit.org/beta/3.9.0/bleachbit-3.9.0-5.1.opensuseTumbleweed.noarch.rpm)?

**Comment by NumDeP** [comment]
I don't run BB via command and I'm sure the python3 issue is fixed considering I wasn't able to use launch the app before 

Right now, I get **Grab binary packages directly** from openSuse as the older versions don't work on openSuse anymore and the system updates usually removes it off the system. I had this conversation here #796 but that part of it was fixed thank to Andrew rapid fix.

**Comment by NumDeP** [comment]
I did not intentionally close this.

**Comment by ediowar** [comment]
What is the first digit of the much older version number, 0, 1 or 2?

**Comment by NumDeP** [comment]
Sorry I can't tell you exactly, but it was the one on the official openSuse repository which wasn't updated in over a year which has since been updated at least on Tumbleweed. It was on python2. 

Nevertheless, in comparison to the latest beta version it performed much more efficiently.

**Comment by ediowar** [comment]
Do you use сustom folders extensively? [Custom folders not being deleted #783](https://github.com/bleachbit/bleachbit/issues/783)

**Comment by ediowar** [comment]
Do you use custom folders extensively? [Custom folders not being deleted #783](https://github.com/bleachbit/bleachbit/issues/783)

**Comment by NumDeP** [comment]
No.

**Comment by az0** [comment]
@NumDeP 
I am not sure how to reproduce this or what could have caused this. Are you able to help with some more troubleshooting? First, make sure you are updated to the latest release, which right now is[ BleachBit 4.2.0](https://www.bleachbit.org/news/bleachbit-420). Then would you please try to narrow down the slowness to one option?

One way to do this is to disable all options, and then enable one group at a time. For example, clean Google Chrome. If it is fast, move on to the next group (for example Firefox). If it is slow, then uncheck all the Google Chrome options except for one option. Please continue this until it's narrowed down.

**Comment by NumDeP** [comment]
Hi @az0 I've included a couple a screenshots indicating the time it usually takes. I am on 4.2.0-2.11 but the result are always similar.

Now the second one would make sense considering quite a bite of disk space is recovered, however, the time is almost identical to the first one as you can see and I think those actual files are deleted sooner.

Now to be quite frank with you I'm basing my experiences based on my use of PrivaZer and CCleaner on Win10 as they're quite efficient and those solutions as one would assume with BleachBit as well that it cleans files and unnecessary thing in general intelligently that need to be deleted because you would also notice there seems to be lot of errors as well. I hope you don't consider that a dig because I do appreciate your efforts on BleachBit.

As for you method of selecting on item at a time on the app, I feel this would take a lot of time and I would naturally need to have files to be deleted.

![Screenshot_20200608_030242](https://user-images.githubusercontent.com/31957540/111084521-b521f200-850a-11eb-9bf3-8aae3eb2929e.png)

![Screenshot_20200607_171901](https://user-images.githubusercontent.com/31957540/111084525-b6ebb580-850a-11eb-8175-1e5165696e68.png)

**Comment by az0** [comment]
> Hi @az0 I've included a couple a screenshots indicating the time it usually takes. I am on 4.2.0-2.11 but the result are always similar.

Thank you

> Now the second one would make sense considering quite a bite of disk space is recovered, however, the time is almost identical to the first one as you can see and I think those actual files are deleted sooner.

There can be some reasons for the time being similar, even though the delete counts differ. At least for troubleshooting, please make sure these are disabled

- The whole section called Deep Scan
- System:  Localizations
- System: Memory
- System: Free disk space
 
> Now to be quite frank with you I'm basing my experiences based on my use of PrivaZer and CCleaner on Win10 as they're quite efficient and those solutions as one would assume with BleachBit as well that it cleans files and unnecessary thing in general intelligently that need to be deleted because you would also notice there seems to be lot of errors as well. I hope you don't consider that a dig because I do appreciate your efforts on BleachBit.

I am not offended the way you expressed this.

> ![Screenshot_20200608_030242](https://user-images.githubusercontent.com/31957540/111084521-b521f200-850a-11eb-9bf3-8aae3eb2929e.png)
> 
> ![Screenshot_20200607_171901](https://user-images.githubusercontent.com/31957540/111084525-b6ebb580-850a-11eb-8175-1e5165696e68.png)

The high count of errors is interesting. There are a few ways to troubleshoot this.

One: In the hamburger menu (three horizontal lines) please click Diagnostics. Please either copy and paste all that info or at least the lines beginning with `os`.

Two: In the log window, right click anywhere and choose "select all." Then copy to the clipboard, paste to text file, save it with the .txt extension, and attach it to the issue. Alternatively, just copy and paste a few lines that have error messages, so I can see the pathnames.

Three: Disable the options I mentioned above.
