### ISSUE TITLE
Yandex false positive for BleachBit 3.9.2 (signed)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#866]
[BleachBit-3.9.2.1624-setup.exe](https://www.virustotal.com/gui/file/c90a823bd4f05f942c7998745131f44ffae5d97e8000008339cc0824d20b149c/detection): Trojan.Agent!VYp5knkVGaA

[BleachBit-3.9.2.1624-portable.zip](https://www.virustotal.com/gui/file/31ea21ae625db8a80e83d9f4923e2ee521f13180cb755d564de6ee5d7eaee252/detection): Trojan.Agent!VYp5knkVGaA

**Comment by az0** [comment]
I emailed yandex-antivir@support.yandex.ru

**Comment by ediowar** [comment]
Maybe it's better to completely abandon the use of UPX?

**Comment by az0** [comment]
> Maybe it's better to completely abandon the use of UPX to antivirus scanners really relax?

UPX reduced size of the installation by 17,394,176 B from 40,602,300 B to 23,208,124 B, so that is a big improvement. For users with spinning HDDs, it improves the speed of loading the application on a cold start.

The false positives are most common with the less popular antivirus software, so they affect few users, and working with a few vendors is a mangeable issue. 

Even if UPX were abandoned, there would still be false positives. First, BleachBit uses Python, which itself seems to trigger a false positive. Second, it's just how these security systems work. Here is an  article on how a ["hello world" program](https://www.csoonline.com/article/3216765/heres-why-the-scanners-on-virustotal-flagged-hello-world-as-harmful.html) got flagged

**Comment by ediowar** [comment]
> For users with spinning HDDs, it improves the speed of loading the application on a cold start.

By what percent?

**Comment by az0** [comment]
> > For users with spinning HDDs, it improves the speed of loading the application on a cold start.
> 
> By what percent?

Based on past experience, the bottleneck for starting an application like this is disk I/O (not CPU, memory, or network). UPX reduced the size by half, so I guess the speed improvement is close to half too.

**Comment by ediowar** [comment]
> I emailed [yandex-antivir@support.yandex.ru](mailto:yandex-antivir@support.yandex.ru)

@az0 How did you find their mail address?

**Comment by az0** [comment]
@ediowar

I think I found their email address here
https://straighttips.blogspot.com/2019/12/virustotal-report-false-positives.html

I haven't yet gotten any response, and the false positive still exists
today for BleachBit-3.9.2.1624-setup.exe

**Comment by ediowar** [comment]
I also reported [bleachbit.exe](https://www.virustotal.com/gui/file/fdf73d98560669854de6b86bfe04fdae699a63f6ecf1354bf18227b94211d290/detection) false positive via [feedback form](https://tech.yandex.com/safebrowsing/doc/quickstart/troubleshooting/troubleshooting-docpage/) (see [Virustotal Contributors](https://support.virustotal.com/hc/en-us/articles/115002146809-Contributors)).

**Comment by az0** [comment]
@ediowar  Thank you for reporting that

The two original files plus bleachbit.exe (from ediowar's link) are now undetected, so I will close this.
