### ISSUE TITLE
HTTP Error 500: Internal Server Error

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#869]
Ubuntu 16.04  without Python environment/developer tools
BleachBit 3.9.2 beta
Git revision 99472dc

Error message happens on startup
> Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: HTTP Error 500: Internal Server Error

**Comment by az0** [comment]
@ediowar 
Thank you again for another good bug report.

I made a fix on the update server. (It affected all BleachBit versions from the last few years.) Please try again.

**Comment by ediowar** [comment]
I tried, now there is no error.
