### ISSUE TITLE
QUESTION: Is It Ok To Install New Over Old?

### ISSUE THREAD

**Issue by 0pLuS0** [bleachbit/bleachbit#876]
Hello,

For Windows users, is it ok to install new versions over old versions, or should we uninstall first?

THANKS

**Comment by az0** [comment]
While there may be no harm, I recommend uninstalling first. Even if you forget, the installer will remind you as shown in this screenshot:

![2020-04-20 uninstall BleachBit](https://user-images.githubusercontent.com/933680/79763226-0ae12080-82e1-11ea-9280-d4a7d1e6331d.png)

**Comment by 0pLuS0** [comment]
Thanks!
