### ISSUE TITLE
BleachBit 4.0.0 has no version number

### ISSUE THREAD

**Issue by MusiqueGraeme** [bleachbit/bleachbit#879]
I installed BleachBit 4.0.0. I have a program that checks the version against the current one and it told me I still needed to install another... 
I found that if I look at the details of the files BleachBit.exe and BleachBit_console.exe there is no version information.

This is very irritating though I suppose it will still work!

**Comment by az0** [comment]
I believe it was there in 3.2.0, but it's not there now in 4.0.0:

![2020-04-20 BleachBit 400 missing version](https://user-images.githubusercontent.com/933680/79763807-c73ae680-82e1-11ea-997f-148a4f36d7ba.png)

**Comment by MusiqueGraeme** [comment]
It was definitely there in 3.2.0.

**Comment by Gitoffthelawn** [comment]
@MusiqueGraeme What tool are you using to check for current versions?  Just curious.

**Comment by peter-marshall** [comment]
I'll work on this one.

**Comment by az0** [comment]
@peter-marshall 
Background: BleachBit 3.2.0 and all previous versions used Python version 2 with py2exe. BleachBit 4.0.0 introduced Python 3.4 (for Windows), and it still used py2exe. I think py2exe was responsible for adding the metadata to the .exe file

@Gitoffthelawn 
I checked the metadata using the regular Windows Explorer. Just right click on the file to view properties.

**Comment by az0** [comment]
@MusiqueGraeme 
Please visit https://ci.bleachbit.org/ , download version 4.0.1.1662 or newer, test, and post a message here to let me know how it goes.

Please allow a few minutes for the new version to build and upload.

**Comment by MusiqueGraeme** [comment]
I installed the above file and it worked - there is now a version number. Well done!

**Comment by az0** [comment]
@MusiqueGraeme 
Thanks for checking
