### ISSUE TITLE
KeyError: 'win10_theme'

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [bleachbit/bleachbit#880]
Hi,
I'm getting following errors in the terminal after running bleachbit as root and the dark mode is not working.I'm using Manjaro KDE and bleachbit v4.

``
(bleachbit:2362): Gtk-WARNING **: 15:58:57.634: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(bleachbit:2362): Gtk-WARNING **: 15:58:57.634: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(bleachbit:2362): Gtk-WARNING **: 15:58:57.635: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
closest monitor (0) geometry = (0, 0)+(1366, 768), window geometry = (450, 72)+(800, 600)

(bleachbit:2362): Gtk-WARNING **: 15:58:58.131: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(bleachbit:2362): Gtk-WARNING **: 15:58:58.131: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(bleachbit:2362): Gtk-WARNING **: 15:58:58.131: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(bleachbit:2362): Gtk-WARNING **: 15:58:58.131: Theme parsing error: gtk.css:83:29: The style property GtkStatusbar:shadow-type is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'win10_theme'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/GuiPreferences.py", line 98, in __toggle_callback
    if options.get('win10_theme'):
  File "/usr/share/bleachbit/Options.py", line 163, in get
    return self.config.get(section, option)
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'win10_theme' in section: 'bleachbit'
Traceback (most recent call last):
  File "/usr/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.8/collections/__init__.py", line 891, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 883, in __missing__
    raise KeyError(key)
KeyError: 'win10_theme'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/GuiPreferences.py", line 98, in __toggle_callback
    if options.get('win10_theme'):
  File "/usr/share/bleachbit/Options.py", line 163, in get
    return self.config.get(section, option)
  File "/usr/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'win10_theme' in section: 'bleachbit'
``

**Comment by az0** [comment]
Thank you for the report, @Ashutosh-Kukreti 
I see three problems.

1. On Linux, BleachBit doesn't come with a theme, and support for dark mode depends on your GTK system theme. For example, Yaru and Adwaita support a dark theme.  You can check your them in BleachBit's diagnostics window, and if you change your system theme to a GTK theme that supports dark mode, I think it will work.

2. `Theme parsing error`

3. `KeyError: 'win10_theme'`

It is unwieldy to handle multiple, unrelated issues, so I am changing the title to focus on KeyError: 'win10_theme'.  If you want to file a separate issue for #2, I will look into it, but I think it's like related to your system theme (like number 1 above).

**Comment by ediowar** [comment]
What are the requirements for BleachBit 4? [Install on Linux](https://docs.bleachbit.org/doc/install-on-linux.html)
From _usr_bin_bleachbit.0.crash:
```
.....
Title: bleachbit crashed with configparser.NoOptionError in get(): No option 'win10_theme' in section: 'bleachbit'
Uname: Linux 4.15.0-97-generic x86_64
UnreportableReason:
 You have some obsolete package versions installed. Please upgrade the following packages and check if the problem still occurs:
 
 libpython3.5-minimal, libpython3.5-stdlib, python3.5, python3.5-minimal
```

**Comment by Ashutosh-Kukreti** [comment]
@ediowar I'm using Manjaro (arch based) and I've already installed python 3.8 and I can't find libpython and my system is up to date. Kerenl : 5.4.33-3-MANJARO
