### ISSUE TITLE
File "bleachbit_4.0.0_all_debian10. deb" SHA256 wrong

### ISSUE THREAD

**Issue by acmatl** [bleachbit/bleachbit#882]
The SHA256 number of the file "bleachbit_4.0.0_all_debian10. deb" has to be a56665081769ed52a2f4913a014039ec9d807e7839260862017a3a0b90ae94fc but I get a different one 22ac38b863f5916af56893bea8f18c2f96c4af12359daac2969b9c6883f1dac4 I downloaded it from https://www.bleachbit.org/download/linux

What's wrong?

**Comment by az0** [comment]
I downloaded Debian 10 and got the correct hash `a56665081769ed52a2f4913a014039ec9d807e7839260862017a3a0b90ae94fc` .

Your hash `22ac38b863f5916af56893bea8f18c2f96c4af12359daac2969b9c6883f1dac4` perfectly matches another file `bleachbit_4.0.0_all_ubuntu1910.deb`.

Does this help?

**Comment by acmatl** [comment]
Yes of course, I got the wrong hash, thank you very much
