### ISSUE TITLE
McAfee false positive for BleachBit 4.0.0

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#883]
[BleachBit-4.0.0-setup.exe](https://www.virustotal.com/gui/file/03fb4dcede9843a22f5c488de6124d80c0427d9a80c0f6e21466bd83c39ee360/detection)

- McAfee-GW-Edition: RDN/Generic.grp
- McAfee: RDN/Generic.grp

[BleachBit-4.0.0-portable.zip](https://www.virustotal.com/gui/file/1d27d3828e258981ddabeb3a2427983d3deb2efb8d9c4c7369d2610d6d55b305/detection)

- McAfee-GW-Edition: RDN/Generic.grp
- McAfee: RDN/Generic.grp

[BleachBit-4.0.0-setup-English.exe](https://www.virustotal.com/gui/file/8e21ac85a28409e372c870555fdf3fc33829d92d28d31c1352cf981343394f06/detection)

- McAfee-GW-Edition: RDN/Generic.grp
- McAfee: RDN/Generic.grp

**Comment by az0** [comment]
I submitted two files by FTP

BleachBit-4.0.0-portable.zip
BleachBit-4.0.0-setup.exe

**Comment by az0** [comment]
Reply from McAfee
>We have reviewed your submission for whitelisting so status will get updated in 24 hours.

**Comment by az0** [comment]
For BleachBit-4.0.0-setup.exe, McAfee is "undetected" though McAfee-GW-Edition still has the false positive

**Comment by ediowar** [comment]
Fixed/

**Comment by az0** [comment]
@ediowar Thank you again
