### ISSUE TITLE
[WinError 5] Acess Denied.: Command to delete C:\Windows\Logs\waasmedi

### ISSUE THREAD

**Issue by j0taDasFestas** [bleachbit/bleachbit#884]
Getting this error when trying delete those logs using last winapp2.ini

`[WinError 5] Acess Denied .: Command to delete C:\Windows\Logs\waasmedic\waasmedic.20200420_205024_218.etl` 
and rest of folder files

Thanks great software !

**Comment by j0taDasFestas** [comment]
Last one 4.0

**Comment by az0** [comment]
@j0taDasFestas 
This issue looks like https://github.com/bleachbit/bleachbit/issues/337 which also has "access denied. Please see this [recent comment ](https://github.com/bleachbit/bleachbit/issues/337#issuecomment-626233719) there and try that solution. Then, please post a comment here to let me know whether that helped.

**Comment by j0taDasFestas** [comment]
This version you say ?
https://ci.bleachbit.org/
Thanks

**Comment by az0** [comment]
Yes. Currently, the newest version is [build 1642](https://ci.bleachbit.org/?prefix=dl/4.0.1.1642/)

**Comment by j0taDasFestas** [comment]
False- positive ?
MD5 d75466f2fba0d35326dcdb19f040ed17
Avast -FileRepMalware
AVG - FileRepMalware
Bkav - HW32.Packed

**Comment by az0** [comment]
> False- positive ?
> MD5 d75466f2fba0d35326dcdb19f040ed17
> Avast -FileRepMalware
> AVG - FileRepMalware
> Bkav - HW32.Packed

Yes, I think it's a FP. I reported `BleachBit-4.0.1.1642-setup.exe`  to AVG as a FP. When they whitelist it, it will [show up on VirusTotal](https://www.virustotal.com/gui/file/a837e167a050220e0233208d4ee9b3bcb25fee24cb4fbc58c0adb42ffb7b2f71/detection)

**Comment by j0taDasFestas** [comment]
working good no error on log

Andrew Ziem <notifications@github.com> escreveu no dia domingo, 17/05/2020
à(s) 18:15:

**Comment by j0taDasFestas** [comment]
No error on log with that ver.

**Comment by az0** [comment]
AVG replied, "We have analyzed the submitted file and we can confirm that it is not infected." I assume that means they will whitelist it.

>No error on log with that ver.

OK, so I will close it as fixed. Thanks for confirming.

**Comment by az0** [comment]
FYI, there is a digitally-signed Windows installer with this fix available via the [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) page. The digital signature reduces problems with false positives
