### ISSUE TITLE
BleachBit 4.0.0 with nonworking built-in languages

### ISSUE THREAD

**Issue by fkru** [bleachbit/bleachbit#886]
Given openSUSE Tumbleweed with a German environment and bleachbit-4.0.0, I always get English as default language, even though "de" is the only one ticked under "Languages". Installing bleachbit-lang works as expected. Do I miss something? Thx.

**Comment by fkru** [comment]
I have just noticed that bleachbit 4.0.0 from
https://build.opensuse.org/package/binaries/home:andrew_z/bleachbit/openSUSE_Tumbleweed works fine. So it seems to be a downstream issue.

**Comment by az0** [comment]
The package in the OBS andrew_z repository and the package on www.bleachbit.org includes the translations and software application in one  installation package, while I think the official openSUSE package requires you two install two installation packages. They are different styles of packaging.
