### ISSUE TITLE
Also delete Winapp.py when building for Unix

### ISSUE THREAD

**Issue by terrycloth** [bleachbit/bleachbit#888]
A pretty minor issue, but... The `delete_windows_files` make target deletes Windows-specific files when building for Unix-like OSes, right.

``` sh
rm -f bleachbit/Windows*.py
```

But this leaves the file `Winapp.py` intact. And skimming that file, it looks sorta like it is also Windows-specific, so it should probably be removed too.

**Comment by peter-marshall** [comment]
I'll work on this one.

**Comment by az0** [comment]
good catch
