### ISSUE TITLE
Error after upgrading to v4.0.0

### ISSUE THREAD

**Issue by gzu88bv** [bleachbit/bleachbit#891]
BleachBit v4.0.0
Windows 10 Pro
see enclosed file
upgraded from v3.0.0
![2020-04-24_144236](https://user-images.githubusercontent.com/26356673/80189642-2d569f00-863d-11ea-9469-45e6a2e99600.png)

**Comment by az0** [comment]
This is a duplicate of https://github.com/bleachbit/bleachbit/issues/890
