### ISSUE TITLE
BleachBit window disappears (launched from context menu)

### ISSUE THREAD

**Issue by thejoker3000** [bleachbit/bleachbit#893]
After right click and clean with bleachbit option is selected, the window (after confirmation) will disappear but when checking the size of a file, it is decreasing meaning that the program is deleting files but no window is shown either during the process or after. I don't know if this was some kind of feature or if it is a bug.

**Comment by az0** [comment]
@aawheatley 
This does not sound like a feature. Are you on Windows 10? Which version of BleachBit?

**Comment by aawheatley** [comment]
Yes, Windows 10 latest and here is some more info:

> BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.31.1

**Comment by aawheatley** [comment]
Also, been looking for a log file but can't find any logs for bleachbit.

**Comment by az0** [comment]
You mentioned you have a problem with BleachBit disappearing when you start it from the Windows context menu (right click---shred with BleachBit). Do you have any trouble with BleachBit disappearing when you start BleachBit normally (like by left clicking on its icon)?

**Comment by aawheatley** [comment]
No. I also open bleachbit - selected clean folders - selected the folder I wanted to remove and it worked fine. No disappearing. So I believe it is a function when doing right click---shred with BleachBit

**Comment by az0** [comment]
Thank you for the clarification. We will look into it

**Comment by Marvin0401** [comment]
Let me check this issue.

**Comment by Marvin0401** [comment]
Hi @az0 , In my view, when we start it from the windows context menu (right click --- Shred with BleachBit), the following shell command would be executed. 
 : "$INSTDIR\bleachbit.exe" --gui --no-uac --shred "file or folder path"

In this case, the app is set to quit automatically and I think it is a not bug. You can check it on the line 362 of the GUI.py file.
 :      if self._shred_paths:
            GLib.idle_add(GUI.shred_paths, self._window, self._shred_paths)
            self._auto_exit = True

I think it is a good idea to automatically close the program when it is started from the context menu.
The only opinion is that it would be nice to just call the confirmation dialog and status dialog without running on the application GUI.

**Comment by thejoker3000** [comment]
erm, I actually think it would be best if we could see the GUI for if there are errors.

**Comment by az0** [comment]
@Marvin0401 
>
> In this case, the app is set to quit automatically and I think it is a not bug. You can check it on the line 362 of the GUI.py file.
> : if self._shred_paths:
> GLib.idle_add(GUI.shred_paths, self._window, self._shred_paths)
> self._auto_exit = True
> 
> I think it is a good idea to automatically close the program when it is started from the context menu.
> The only opinion is that it would be nice to just call the confirmation dialog and status dialog without running on the application GUI.

When launched by the Windows context menu ("shred with BleachBit"), the application is expected to close automatically after cleaning is done. Normally it works like this

1. User clicks "shred with BleachBit" from Windows context menu
2. BleachBit launches and shows a preview
3. It shows a confirmation dialog
4. User accepts the confirmation
5. BleachBit deletes the files
6. BleachBit quits

**Comment by az0** [comment]
In BleachBit 4.2.0 (official release), I found this traceback that explains part of the problem

```
C:\temp>"c:\Program Files (x86)\BleachBit\bleachbit_console.exe" --shred --no-uac --gui c:\temp\deleteme.txt
Success
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 260, in run
  File "bleachbit\Worker.pyo", line 336, in run_operations
KeyError: '_gui'
```
So this has the same traceback as the issue https://github.com/bleachbit/bleachbit/issues/993

**Note to users who want a workaround**

1. Downgrading to BleachBit before 4.0.0 might help, but it's not recommended
2. You can drag and drop. However, the Windows security model does not allow a non-elevated process to drop onto an elevated process. BleachBit shreds best when elevated, so unless you elevate Windows explorer, this is not a good option.
3. Copy files to the clipboard in explorer. Then, in BleachBit click the application menu and choose option to shred files from clipboard.

**Comment by az0** [comment]
I am assigning this to @rados because has committed a change related to it.

**Comment by az0** [comment]
@thejoker3000  thank you for the bug report

This is now fixed, and you can try it out by downloading build 4.2.0.1838 or later from the [CI build site](https://ci.bleachbit.org/). Please allow a few minutes for it to upload. If you are able to test, please add a comment here to confirm it's fixed.

**Comment by thejoker3000** [comment]
Hey,

OK, I will check up on this and let you know. Thanks!

**Comment by thejoker3000** [comment]
Ok, so it worked. The program closed only after it was done but the setting is set to not close when done shredding.

**Comment by thejoker3000** [comment]
Ignore the previous comment. I had changed something in it.

It worked fine with this version you mentioned.
