### ISSUE TITLE
ModuleNotFoundError: No module named 'gtk' on Debian 10.3

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#894]
Tried to install BleachBit through package manager in Debian 10.3 today and it doesn't start with the error mentioned above:

`~$ bleachbit

Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 38, in <module>
    import gtk
ModuleNotFoundError: No module named 'gtk'
`

_Originally posted by @topas-rec in https://github.com/bleachbit/bleachbit/issues/540#issuecomment-619364818_

**Comment by az0** [comment]
@topas-rec


When you wrote you installed through package manager, do you mean from the Debian repository Which version of BleachBit is that?

Assuming you have BleachBit 3.0 or 3.2, install the Debian packages libgtk-3-0, and gir1.2-gtk-3.0 .

Debian and other Linux distributions often have old (sometimes ancient) versions of BleachBit. The latest stable release is BleachBit 4.0.0. Please try it. There is an easy-to-install Debian package available at www.bleachbit.org

**Comment by topas-rec** [comment]
Thanks for creating this issue.
I installed it through the gui package manager "Software" not apt this time. In the GUI the source repository is shown which is debian-stable-main and bleachbit is version 2.0-3 (Updated 25.04.2020 says the repo).

I thought I could get the Debian minor release out of `lsb_release` but unfortunetely not:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

That bleachbit version is one and a half years old - should that work (with specific packages installed by pip or so) or should Debian 10 users install it from somewhere else than the stable repo?

**Comment by topas-rec** [comment]
I'll try your suggestions later and come back to this.

**Comment by az0** [comment]
>That bleachbit version is one and a half years old - should that work (with specific packages installed by pip or so) or should Debian 10 users install it from somewhere else than the stable repo?

BleachBit 2.0 was released February 2018, though Debian may have made a tweak later. This version requires that you install GTK 2. I forget the package names needed, but because of so many improvements, I recommend installing the latest BleachBit (currently 4.0.0) from www.bleachbit.org . Let me know how that goes.

>I'll try your suggestions later and come back to this.


OK, sounds good.

**Comment by topas-rec** [comment]
The suggested packages are already installed (Tried them though they might only help above version 2)
Installing the package manually from www.bleachbit.org helps - no issue starting the app.

I usually don't like manually installed packages. In this case it is okay, since Bleachbit seems to check for updates automatically. It would be better to be able to use the software store even if the app is old. (I think debian is responsible for the old version of bleachbit)

**Comment by topas-rec** [comment]
> This version requires that you install GTK 2

Should be installed.

**Comment by topas-rec** [comment]
```
python-gtk2/stable,now 2.24.0-5.1+b1 amd64 [installed,auto-removable]
  Python bindings for the GTK+ widget set
```

Some other GTK related packages might solve the issue - but don't mind. In this case (automatic updates) I'm happy with the manual install and other Debian 10 users should benefit from this discussion. Maybe Debian packages will be updated some day.

**Comment by topas-rec** [comment]
Issue can be closed in my eyes.
Thanks for everyone who reads this and is part of the development team. Your app is very helpful and I use it since years!

**Comment by az0** [comment]
> Maybe Debian packages will be updated some day.

Debian and Ubuntu follow a "no rolling release policy," so they update BleachBit only with new releases of the Linux distribution. For example, Ubuntu 19.10 will never get a newer version of BleachBit in Ubuntu 19.10, but Ubuntu 20.04 can have a newer version of BleachBit.



> Issue can be closed in my eyes.

OK. 

> Thanks for everyone who reads this and is part of the development team. Your app is very helpful and I use it since years!

:)
