### ISSUE TITLE
Microsoft false positive for BleachBit 4.0.0

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#895]
BleachBit-4.0.0-portable.zip
[VirusTotal link](https://www.virustotal.com/gui/file/1d27d3828e258981ddabeb3a2427983d3deb2efb8d9c4c7369d2610d6d55b305/detection)

Microsoft detects it as PUA:Win32/Presenoker

**Comment by ediowar** [comment]
Undetected. You can close it.

**Comment by az0** [comment]
@ediowar 
Thank you

**Comment by ediowar** [comment]
Again PUA:Win32/Presenoker :)

**Comment by az0** [comment]
Hmm. A few days ago I scanned the individual files, and I couldn't find any that Microsoft detected

**Comment by ediowar** [comment]
AI has changed its mind.

**Comment by az0** [comment]
Fixed
