### ISSUE TITLE
BB 4.0 Portable takes much longer to open (at least for first launch)

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#896]
Coming from v3.2.0 Portable, BleachBit v4.0 Portable takes very approximately 20-30 times longer to open on the first run.

After about 30 seconds, I assumed it crashed.  But I'm patient, so I just waited it out.  After about 45 seconds (very approximate), the BleachBit UI appeared.  There was no indication it was running until that time (except in Task Manager / Process Explorer).

Version 3.2.0 did take a couple seconds to start up, but nothing like this.

The second run of v4 (without rebooting) took about 5 seconds to open.

The third run of v4 (without rebooting) took about 1-2 seconds to open.

Tested on Win7 with no other applications running.

Your version of Winapp2.ini was in the `shared\cleaners` folder during all launches.

If I have more info, I'll let you know.

**Comment by ediowar** [comment]
https://github.com/bleachbit/bleachbit/issues/821#issuecomment-612558244

**Comment by Gitoffthelawn** [comment]
Actually, it wasn't my machine.  But that box had Avira running on it.

**Comment by az0** [comment]
@Gitoffthelawn 
Do you know if this is consistently a problem?

**Comment by Gitoffthelawn** [comment]
@azo I don't think it is.  I had access to that machine the other day, and BB took about 5-8 seconds to open.  Definitely not the 45 seconds it took before.

**Comment by az0** [comment]
@Gitoffthelawn 
Thanks for the reply. Because it's not consistently a problem, are you okay with me closing the issue?

One guess on the root cause is the antivirus was getting accustomed to the new application.

**Comment by Gitoffthelawn** [comment]
@az0 Yes, thanks for asking! :smiley: 

I'll close it now, and if it becomes a big problem or if you or others experience this issue, it can be re-opened.

**Comment by Gitoffthelawn** [comment]
@az0 I received another report of this happening on a Windows box.  Unfortunately, I don't have more details at this time.

I'm fine if you reopen, or not.

I'll definitely let you know if I receive more details.
