### ISSUE TITLE
BB 4.0 displays a "monitor" debug message

### ISSUE THREAD

**Issue by Gitoffthelawn** [bleachbit/bleachbit#897]
In BB 4.0, the first line when opening reads:

`closest monitor (0) geometry = (0, 0)+(####, ####), window geometry = (####, ####)+(####, ####)`

It looks like a debug message that's accidentally getting displayed.  Debug mode is off.

Tested on Win7 on a multi-monitor system when only 1 of the 2 monitors was enabled.

**Comment by ediowar** [comment]
https://github.com/bleachbit/bleachbit/commit/7d348ce63aded3d130a0f9a2d5c9947437b25697#commitcomment-38355790

**Comment by az0** [comment]
This shows up at the "info" level, but it should show up only at the "debug" level to make it usually hidden

**Comment by mkhon** [comment]
Fixed in #949

**Comment by Gitoffthelawn** [comment]
@mkhon Thank you Max!

**Comment by mkhon** [comment]
@az0 this can be marked as fixed

**Comment by az0** [comment]
@Gitoffthelawn 

This should be fixed in any recent build on the [CI site](https://ci.bleachbit.org/)
