### ISSUE TITLE
BB 4.0 Wipe Free Space not working

### ISSUE THREAD

**Issue by gator101** [bleachbit/bleachbit#899]
BB version 4.0.0 Windows 10 errors on Wipe Free Space (see attached screenshot and data log)

![Bleachbit_screenshot_2020-04-27](https://user-images.githubusercontent.com/64414155/80370265-11970700-8890-11ea-8374-a7e497200dcc.png)

[Bleachbit_diagnostics_27_04_2020.txt](https://github.com/bleachbit/bleachbit/files/4539448/Bleachbit_diagnostics_27_04_2020.txt)

**Comment by ediowar** [comment]
Try new unstable build [1635](https://ci.bleachbit.org/?prefix=dl/4.0.1.1635/)

**Comment by gator101** [comment]
Seems to erase the free space, but with 6 errors.

![2020-04-27 (2)](https://user-images.githubusercontent.com/64414155/80379116-f16e4480-889d-11ea-8c8a-131e6b89acdf.png)
![2020-04-27 (3)](https://user-images.githubusercontent.com/64414155/80379124-f3d09e80-889d-11ea-8682-36876c940b32.png)
[Bleachbit_1605_log.txt](https://github.com/bleachbit/bleachbit/files/4539999/Bleachbit_1605_log.txt)

**Comment by ediowar** [comment]
Please correct build number in the file name.

**Comment by gator101** [comment]
Errors appeared after 11 minutes. If I run only Wipe Free Space then one error appears immediately (see attached screenshot 4).

![BB_build_1605_screenshot_2020-04-27 (4)](https://user-images.githubusercontent.com/64414155/80386425-a22d1180-88a7-11ea-92e3-47d1bae27874.png)

**Comment by ediowar** [comment]
Could you change the language to English (rename C: \ downloads \ BleachBit-Portable \ share \ locale \de) and post an error message here? Message enclose on both sides in ```

**Comment by gator101** [comment]
```Error: _gui.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmpvgouznmfmCXqnkEzaXNWx_dvoJe4gVc0kuSdepTgZDZ4EP2JOSRq6YvTCln_xv7o1Y5rbspWGIm-X-9tZb3uDo5WJcHR6Oz0LpgttOKsJynwcxSbyr9Q2fwOMCxIsmcAthCl0ylIoqRFIDj5rvKafr2-vHuYdEBlF8cH9bh.3BfaDWNmTcMf0lkaL8Id6GMpcv2czNaxDTTrwnMi1IjYv.sWDX9XQRyLF8kftcLDsdWy7V7kUxAjv3alHUn3M'```

**Comment by ediowar** [comment]
@az0 the number of characters in the file name = 257. So it should be?

**Comment by ediowar** [comment]
Same. Wndows 7 SL 64-bit. Build number 1635
```
clean_operation('_gui'), options = '[]'
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Wiping path: C:\
Creating new, temporary file for wiping free space.
Error: _gui.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmpx8mvlmj4AciqxlAl0eY.RjZbNGOM8idMAzUWl-nihG0GpuQTzA04iDdMSEZOShvgHSptKbCdT92N_Hvcuy5daud4ps91jY3GkTa9whXacPpGfu.HjZU6HQ9n-sw-W31hZZCfZR9WrAYyFUSPTIPOlU.O_3YVNLBwbIEZd3y5bTItke21FywS8hBou.UxgsARxkLkeZe4h_afL4giuc3fLWF0dwFO6uRNcX4IHoAjLYJvTH6XfzDIGT4vrlMoJ'
```
258 characters in the file name

**Comment by az0** [comment]
@gator101 @ediowar 
Thank you for the good info. Max coded a fix, but I haven't merged it yet, so it's not in the most recent builds. Would you please test [build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts)? Then please post a comment here to let me know how it went.

**Comment by ediowar** [comment]
I checked. Fixed.

**Comment by ediowar** [comment]
I have tested. Fixed.

**Comment by az0** [comment]
> I have tested. Fixed.

Thank you for checking. It works, so I will close the issue.
