### ISSUE TITLE
Which option creates a "new, temporary file for wiping free space"?

### ISSUE THREAD

**Issue by MaxWhite20062003** [bleachbit/bleachbit#900]
I'm the type of maniac who selects all BleachBit options to free up as much space as possible, however, there is an option that creates a "new, temporary file for wiping free space."

Can anyone help me find out which option enables this procedure?

It is because I think that this option would only shorten the useful life of my storage drive, since I use BleachBit frequently with all option selected.

**Comment by ediowar** [comment]
[Shred files and wipe disks ](https://docs.bleachbit.org/doc/shred-files-and-wipe-disks.htmll)

**Comment by az0** [comment]
Under the system category, there is an option "free disk space." When you enable it, there should be a warning that it's very slow. Try unchecking that box.
