### ISSUE TITLE
Syntax Error while installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by s-ankur** [bleachbit/bleachbit#902]
![image](https://user-images.githubusercontent.com/33252312/80627679-e964ff00-8a6d-11ea-83ff-d8f7dd21309e.png)
`/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if msgctxt is not None and msgctxt is not "":
`

There's an warning that appears while installing BleachBit with apt.

**Comment by s-ankur** [comment]
This is because Python has started to treat this [type of expression ](https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/)
`variable is not literal`
as a syntaxwarning beginning from python3.8

**Comment by az0** [comment]
FYI, there is an RPM package with this fix available via the [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) page
