### ISSUE TITLE
Add package for Fedora 32

### ISSUE THREAD

**Issue by marcTremblay2** [bleachbit/bleachbit#904]
Hello,
i create this issue following your message here : https://www.bleachbit.org/forum/fedora-32-bleachbit-not-available#comment-3314

Here is the issue from bleachbit support  : 

i just upgrade from fedora 31 to fedora 32 workstation.
Bleachbit was removed during this upgrade.
I have been using Bleachbit for 6 years on fedora and it is the fisrt time i meet this issue.

I tried to install from the official depository and it seems that Bleachbit is not avalaible anymore on it.
Do you know if Bleachbit will be avalaible again on it soon ?

i guess the only alternative is to download the officiel rpm from bleachbit.org. Unfortunately, only fedora 30 and fedora 31 are avalaible.
Could you put a new rpm for fedora 32 ?

Best regards

**Comment by ediowar** [comment]
@marcTremblay2 Grab binary packages directly https://software.opensuse.org/download/package?package=bleachbit&project=home%3Aandrew_z

**Comment by deekej** [comment]
Bump up. I would also welcome an official Fedora package build for F32+, especially for a kind of app that bleachbit is. Without getting too much political / philosophical, _many people (including me) prefer official Fedora builds._ (I have burned myself last time when using non-official build from OpenSUSE Build platform.)

**Comment by az0** [comment]
There is a rpm package for Fedora 32 available for [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta), and there will be a rpm package also for the 4.2.0 final release
