### ISSUE TITLE
The problem is ModuleNotFoundError: No module named 'gi' in bleachbit 4.0.0

### ISSUE THREAD

**Issue by OlideG-William** [bleachbit/bleachbit#905]
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/GUI.py", line 25, in <module>
    from bleachbit import GuiBasic
  File "/usr/share/bleachbit/GuiBasic.py", line 28, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

i have a problem i dont know how to solve it tried everything and installed python-gobject3 and nothing. Problem on LINUX Manjaro kernel 5.6.8-1.I even wrote this command in python 
>>> import bleachbit
Traceback (most recent call last):
  File " < stdin > ", line 1, in <module>
ModuleNotFoundError: No module named 'bleachbit'. Help me

**Comment by ediowar** [comment]
Exactly 4.0.0? https://github.com/bleachbit/bleachbit/issues/894

**Comment by AnaemicStar** [comment]
I also use Manjaro Linux. I use kernel 4.19. I am unable to open Bleachbit.

**Comment by az0** [comment]
Did you install BleachBit from source code or from a repository?

Dp you have the gtk3 package (like [Arch requires](https://www.archlinux.org/packages/community/any/bleachbit/))?

I am not familiar with package names on Manjaro. Please review the package names for the [RPM](https://github.com/bleachbit/bleachbit/blob/master/bleachbit.spec) and [DEB](https://github.com/bleachbit/bleachbit/blob/master/debian/debian.control) packages, and maybe you can find a similar package in Manjaro

**Comment by ediowar** [comment]
https://gitlab.manjaro.org/explore/groups
http://ftp.riken.jp/Linux/manjaro/testing/community/x86_64/

**Comment by AnaemicStar** [comment]
@az0 
From the Manjaro repository.

**Comment by az0** [comment]
@AnaemicStar  @OlideG-William 
**1**
Did you install both packages **gtk3** and **python-gobject**?

**2**
What if you run `python3 /usr/bin/bleachbit`?

**3**
Can you start any other Python3+GTK applications such as gedit, gnome-tweaks, gpodder, gramps, liferea, pychess, rhythmbox, or totem?

**Comment by ediowar** [comment]
> Had to remove \usr\share\bleachbit before update. After that, everything was OK.

https://forum.manjaro.org/t/stable-update-2019-10-10-gnome-3-34-1-plasma-5-16-5-kde-apps-framework-pamac-9-0-mesa-19-2-1/106563/13

**Comment by AnaemicStar** [comment]
@ediowar 
"Which DE?"

I use Xfce.
I deleted the .config/bleachbit in the Home folder and then reinstalled Bleachbit. This solved the problem. Bleachbit now opens.
I looked but couldn't find the solution. Thanks alot.

**Comment by ediowar** [comment]
@OlideG-William Post a link to your distribution.

**Comment by Axeltherabbit** [comment]
it seems due to the python version on arch: "python" is  3.8 and "python3" is 3.8.2.
to fix it you can just replace the first line of /usr/bin/bleachbit
`!/usr/bin/env python3` with `!/usr/bin/env python`

**Comment by az0** [comment]
I see @Axeltherabbit  and @AnaemicStar have a solution.

@OlideG-William 
Were you able to read this thread? Have you found a solution?

**Comment by ediowar** [comment]
[Bleachbit Not Opening](https://forum.manjaro.org/t/bleachbit-not-opening/140277)

**Comment by az0** [comment]
I am closing because two people have a solution and there was no reply from @OlideG-William since my message in May (~250 days ago)

**Comment by jeffscottward** [comment]
Having this issue for Mac trying to build from source.

**Comment by abitrolly** [comment]
@jeffscottward did you install PyGObject?

https://pygobject.readthedocs.io/en/latest/getting_started.html#macosx-getting-started

**Comment by jeffscottward** [comment]
I got it working after installing pyobject3 and gtk+3￼
