### ISSUE TITLE
Error 22 when wiping free space

### ISSUE THREAD

**Issue by ToddAndMargo** [bleachbit/bleachbit#906]
How can I fix this?

BleachBit-4.0.0-portable
W10-1909 x64

Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Error: _gui.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmpv82adlnjhJbH93f8zyFC7RzM-xPIRz-8C.MYKwgin2BwmSH8qRmkdyaixMdfKNofGrcPyMzqHoDtw.phe4XA59NZ9SfVvNoloSMK_rLeiwXdmhAvUWI96iiOpSCh6jT8C-iDl.ejtqC1suDMlQ5x87B7wEdE0OrnkKl7EyiCD8r3ox26sDA7GDSb15m5V4E-00I2AZ_dM101pdcrsI2bYBil_UMyx10tmhehu.GERo9jObP_QMQgy3-oc3yNV'

Disk space recovered: 0
Files deleted: 0
Errors: 1

**Comment by az0** [comment]
Thank you for the report. This is a bug in BleachBit 4.0.0. It's like issue https://github.com/bleachbit/bleachbit/issues/899 . For now, one workaround is to downgrade to BleachBit 3.2.0. When a fix is ready, I'll post a message here to ask you to try it out

**Comment by az0** [comment]
@ToddAndMargo 
Thank you for the good info. Max coded a fix, but I haven't merged it yet, so it's not in the most recent builds. Would you please test [build 4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts)? Then please post a comment here to let me know how it went.

**Comment by ToddAndMargo** [comment]
On 2020-07-06 20:20, Andrew Ziem wrote:
> @ToddAndMargo <https://github.com/ToddAndMargo>
> Thank you for the good info. Max coded a fix, but I haven't merged it 
> yet, so it's not in the most recent builds. Would you please test build 
> 4.0.1.1664 
> <https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts>? 
> Then please post a comment here to let me know how it went.

Hi Andrew,

Awesome!

I have the perfect test bed for it tomorrow.  I am
PCI (Payment Card Industry) hardening a new Point of
Salve computer and that is part of my routine, both
for security measures and to prolonged SSD life.

I will get back!

-T

**Comment by ToddAndMargo** [comment]
On 2020-07-06 20:20, Andrew Ziem wrote:
> @ToddAndMargo <https://github.com/ToddAndMargo>
> Thank you for the good info. Max coded a fix, but I haven't merged it 
> yet, so it's not in the most recent builds. Would you please test build 
> 4.0.1.1664 
> <https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts>? 
> Then please post a comment here to let me know how it went.

It is doing its thing right now (cleaning free space)
without complaining

Thank you!

**Comment by az0** [comment]
@ToddAndMargo 
Thank you for confirming it is fixed, so now I will close the issue.
