### ISSUE TITLE
Where is exe, portable (zip) files on github?

### ISSUE THREAD

**Issue by f43tgrhb35SD7633** [bleachbit/bleachbit#909]
Hello,

cannot see exe, portable (zip) files under releases. https://github.com/bleachbit/bleachbit/releases

Please add.

**Comment by az0** [comment]
Please see https://www.bleachbit.org/

**Comment by f43tgrhb35SD7633** [comment]
Why not at github? https://github.com/bleachbit/bleachbit/releases

That would be very convenient as a second source.

**Comment by az0** [comment]
I agree it would be a little more convenient, but it would significantly reduce the revenue that fuels the project, so it would slow development. There are no revenues from license, subscriptions, or support, and I don't want to "shoot myself in the foot."
