### ISSUE TITLE
v4.0.0 erase all extensions of libreoffice

### ISSUE THREAD

**Issue by sebas22** [bleachbit/bleachbit#913]
BleachBit version 4.0.0
Git revision f2093f8
GTK version 3.24.5
debian buster

When we clean LibreOffice, option "cache", BleachBit delete all the content of ~/.config/libreoffice/4/user/uno_packages/cache

namely :
~/.config/libreoffice/4/user/uno_packages/cache/registry/  (all content and the folder itself)
~/.config/libreoffice/4/user/uno_packages/cache/uno_packages/ (all content and the folder itself)
~/.config/libreoffice/4/user/uno_packages/cache/log.txt
~/.config/libreoffice/4/user/uno_packages/cache/uno_packages.pmap

So, all the information about the extensions is lost, and the next time we open LO, it comes without any extension at all. That's very problematic, because if we don't have a recent backup of home, we have to reinstall and configure again all those extensions.

Thank you for this soft !

**Comment by az0** [comment]
confirmed
