### ISSUE TITLE
Google Chrome Can No Longer Be Fully Cleaned On Windows Yet Again

### ISSUE THREAD

**Issue by Danster83** [bleachbit/bleachbit#914]
I had posted this to the author before and he made a bug fix to the problem but Alphabet Google really does not want you to wipe all their tracks so Alphabet Google's Response  is to break Bleach Bit again.  Google sadly has some poor businesses practices.  I and my business have currently switched everyone over to Microsoft Edge.  I really like Microsoft Edge's New Browser compared to the Google Browser which seems to be old and long in the the tooth.

**Comment by ediowar** [comment]
Even with activated "Download and update community cleanup templates (winapp2.ini)" in settings?

**Comment by Danster83** [comment]
Well, Surprise, Surprise --- I just updated with the latest Google Version and it allows beach bit to work again.  I was not even offered it until today.

https://chromereleases.googleblog.com/2020/05/stable-channel-update-for-desktop.html
