### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'show_uri_on_window'

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#915]
Ubuntu 16.04.6 LTS, BleachBit version 4.0.1
Running from source code, Git revision https://github.com/bleachbit/bleachbit/commit/9166c50c2a14c557d32fc8d9fde3d676ff324cf5
GTK version 3.18.9
### Steps to Reproduce
Menu - Help - Open web browser to update.bleachbit.org? - Ok
```
$ python3 bleachbit.py
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/GUI.py", line 175, in cb_help
    GuiBasic.open_url(bleachbit.help_contents_url, self._window)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/GuiBasic.py", line 197, in open_url
    Gtk.show_uri_on_window(parent_window, url, Gdk.CURRENT_TIME)
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'show_uri_on_window'
```

**Comment by abitrolly** [comment]
>  GTK version 3.18.9

@ediowar the function was added in Gtk 3.22 (https://lazka.github.io/pgi-docs/Gtk-3.0/functions.html#Gtk.show_uri_on_window) and according to https://github.com/bleachbit/bleachbit/commit/58bc93398ed378eccdd862c547aa68b5dc979f64 the latest BleachBit version without this commit is 2.2

I guess the bug is present in https://www.bleachbit.org/download/linux download for Ubuntu 16 LTS as well. Can you confirm it?

**Comment by abitrolly** [comment]
@az0 what is the support policy for LTS versions of Ubuntu that are bundled with outdated Gtk? Should BleachBit continue proposing newer versions for them? Download for Ubuntu 16.04 proposes 4.0.0.

**Comment by ediowar** [comment]
> I guess the bug is present in https://www.bleachbit.org/download/linux download for Ubuntu 16 LTS as well. Can you confirm it?

I confirm it.

**Comment by az0** [comment]
@abitrolly 
> @az0 what is the support policy for LTS versions of Ubuntu that are bundled with outdated Gtk? Should BleachBit continue proposing newer versions for them? Download for Ubuntu 16.04 proposes 4.0.0.

I'd like to support all Ubuntu versions that are not end of life, but I also wouldn't invest heroic efforts into the oldest Ubuntu versions. 

How about this: use hasattr() or similar to check whether show_uri_on_window is defined. If not, fall back to system call to xdg-open or something like that?

**Comment by abitrolly** [comment]
@az0 I can work on this one. Adding `webbrowser.open_new_tab()` seems reasonable to me.

**Comment by az0** [comment]
This will be published soon in 4.1.1 beta 

@abitrolly  Thank you for the fix

**Comment by abitrolly** [comment]
@ediowar check out new `master`. ;)

**Comment by ediowar** [comment]
@abitrolly  already checked out, ok/

**Comment by ediowar** [comment]
Already checked out, ok.

**Comment by ediowar** [comment]
@abitrolly fellow countryman, I am from Minsk. Жыве Беларусь!

**Comment by ediowar** [comment]
@abitrolly I am also from Minsk. Жыве Беларусь!

**Comment by abitrolly** [comment]
@ediowar Жыве! :D

@az0 given recent event in Belarus, I predict that BleachBit will be popular among desktop users. Although an Android version that can quickly clean up Telegram channels is more actual.
