### ISSUE TITLE
Website button fails

### ISSUE THREAD

**Issue by cliftonprince** [bleachbit/bleachbit#918]
Button in "about BleachBit" that's supposed to link to the BleachBit website doesn't work, screenshot below ...
![Annotation 2020-05-10 132313](https://user-images.githubusercontent.com/17009729/81507373-95a2b300-92c2-11ea-9d2c-84af9ffa7406.png)

**Comment by ediowar** [comment]
Same. Windows 8 SL (64-bit)
```
BleachBit version 4.0.1
Build number 1642
```

**Comment by az0** [comment]
On Windows 10 with BleachBit 4.0.0 installed, I get the error "could not show link: no application is registered as handling this file."

On a development machine with Windows 10, it runs fine. 

I think the distribution is missing a component.

**Comment by Asherathe** [comment]
I get the same error as OP when running BleachBit 4.0.0 on Windows 7 64-bit, whether running as normal user or admin.

**Comment by mkhon** [comment]
Happens in portable build (can not be reproduced if run from source)

**Comment by mkhon** [comment]
It is not a regression - gspawn-win32-helper.exe is missing and it was not included into bleachbit builds for a long time.

**Comment by az0** [comment]
> It is not a regression - gspawn-win32-helper.exe is missing and it was not included into bleachbit builds for a long time.

You're right. In BleachBit 3.2, it didn't work either. I tested it on the blue website link in the about dialog window.

**Comment by az0** [comment]
@cliftonprince 
@ediowar 
@Asherathe 

Max fixed this by adding a missing component. When you have a chance, would you please download build 4.0.1.1669 or newer from the [CI site](https://ci.bleachbit.org/), install it, test it, and write a comment here to let us know how it went?

It works when the default browser is Google Chrome or Internet Explorer, but it [does not work when the browser is Microsoft Edge](https://github.com/bleachbit/bleachbit/issues/960). Let's consider Edge as a separate issue.

**Comment by Asherathe** [comment]
I tested 4.0.1.1669, and it works now, with Pale Moon as default browser.

**Comment by az0** [comment]
Thanks for testing!

**Comment by ediowar** [comment]
I tested 4.0.1.1669, and it works with Internet Explorer, Google Chrome, Firefox as default browser.
The issue for the administrator remained. Or let's consider it as a separate issue?

**Comment by ediowar** [comment]
I tested BleachBit-4.0.1.1669-portable, and it works with Internet Explorer, Google Chrome, Firefox as default browsers.
But when running as an administrator, BB still closes without any messages. Or let's consider it as a separate issue?

**Comment by az0** [comment]
> But when running as an administrator, BB still closes without any messages. Or let's consider it as a separate issue?

Yes, this sounds like a separate issue.
