### ISSUE TITLE
AVG issue

### ISSUE THREAD

**Issue by JaneyHMR** [bleachbit/bleachbit#921]
AVG just quarantined libgio-2.0-0.dll . . .  idp.generic.
BleachBit-4.0.0 on Windows 10.
Is this a false positive?

**Comment by JaneyHMR** [comment]
I created an AVG exception and tried to re-install but got this -
![re-install](https://user-images.githubusercontent.com/65313207/81950904-6f4f8100-95fc-11ea-8364-10c6556e1123.PNG)

**Comment by az0** [comment]
@JaneyHMR 
Regarding the "error opening file" during reinstallation, make sure you are running with elevated privileges. Instead of double left clicking on the installer, right click on it and choose "run as administrator."

For troubleshooting, two alternatives that don't require admin privileges (1) choose the installer option to install for just the current user or (2) use the portable version.

**Comment by az0** [comment]
Sometimes there are false positives, but I don't see that here.

I uploaded `libgio-2.0-0.dll` from BleachBit 4.0.0 to VirusTotal. It scanned it with 70 virus scanners (including AVG), and none detected it as malware. 

Can you please confirm your file has the same checksums? (Checking any one checksum is fine.)

MD5	1de50887d2da1f9b937f1648bfc5088e
SHA-1	3c636d2c083746b23d2c978860040247c4ae1c46
SHA-256	f39a6f879c519a8a5d32910011fa716a464734769bb06f03ac2014e57c3991e4

Size 411136 bytes

**Comment by JaneyHMR** [comment]
Sorry, it got zapped..
I got rid of AVG in the end, should have done it long ago.
I've reinstalled BB now, seems to be fine.
Thanks,
J.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by az0** [comment]
> I've reinstalled BB now, seems to be fine.

Thanks for the reply. OK, so I will close the issue.

**Comment by az0** [comment]
For what it's worth, I submitted [BleachBit-4.0.1.1642-setup.exe](https://ci.bleachbit.org/?prefix=dl/4.0.1.1642/) for [whitelisting](https://github.com/bleachbit/bleachbit/issues/884#issuecomment-629830710) to AVG, and they accepted it.
