### ISSUE TITLE
It's Running in the background for a long time

### ISSUE THREAD

**Issue by Robertpuggle** [bleachbit/bleachbit#923]
I run it the first time it run normally and now it's running in the background

**Comment by az0** [comment]
Are you on Windows or Linux?

Which version of BleachBit?

What exactly did you do to check that it's running in the background? If it helps to explain, attach a screenshot

**Comment by Robertpuggle** [comment]
> Windows

I am on Windows 

My Bleach Bit was 4.0.0

I Exit the program all the times and if i click the exes and it add a other one in the background

**Comment by ediowar** [comment]
@Robertpuggle Which one? https://www.bleachbit.org/download/windows
You can record screen https://picpick.app/en/download/

**Comment by Robertpuggle** [comment]
@ediowar It was these one BleachBit installer.exe
I don't have a recording soft ware

**Comment by ediowar** [comment]
@Robertpuggle You can download the portable version from my link.
Check that no BB files are quarantined.

**Comment by Robertpuggle** [comment]
@az0 @ediowar I Finley Got fixed I had to wait for a long time

**Comment by az0** [comment]
@Robertpuggle 
Thank you for confirming.

If you think other people might have the same problem, you could post your solution here.
