### ISSUE TITLE
Loop when maximizing the window on Linux in Plasma Desktop Session

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#925]
openSUSE Tumbleweed 20200519, Desktop Session: Plasma, Plasma (Wayland), single monitor.
https://download.opensuse.org/repositories/home:/andrew_z/openSUSE_Tumbleweed/noarch/bleachbit-4.0.0-1.14.noarch.rpm and latest git revision
`Maximized window (-18, -16)+(1402, 723): monitor (0) geometry = (0, 0)+(1366, 768)`
![Peek 2020-05-22 17-52](https://user-images.githubusercontent.com/44164186/82683982-904a4e80-9c5a-11ea-99b3-cdbf46f4306b.gif)
![Peek 2020-05-22 17-59](https://user-images.githubusercontent.com/44164186/82683994-94766c00-9c5a-11ea-9a3a-6d87d5ec4903.gif)
In Openbox, Plasma (Full Wayland) there is no issue.
Three workarounds:
- System Settings - Workspace - Window Management - Window Rules - New... - Appearance & Fixes - Block compositing - Force - Yes - Ok - Continue - Apply
- System Settings - Hardware - Display and Monitor - Compositor - uncheck Enable compositor on startup - Apply
- System Settings - Hardware - Display and Monitor - Compositor - Rendering Backend: switch OpenGL 2.0  to OpenGL 3.1 or XRender - Apply

**Comment by az0** [comment]
@ediowar 

Max made a fix for this, and I merged it to Git. Could you please test from there?

**Comment by ediowar** [comment]
I tested, now there is no issue.

**Comment by az0** [comment]
Thanks
