### ISSUE TITLE
I noticed (4.0.0-1.1) update, after installing (4.0.0-1.4)

### ISSUE THREAD

**Issue by NumDeP** [bleachbit/bleachbit#926]
I recently searched for updates on my openSuse Tumbleweed system and noticed the **bleachbit (4.0.0-1.4)** update. After the update had finished downloading and installing, I then noticed another update of **bleachbit (4.0.0-1.1)**.

I don't know what the exact issue is here as I haven't installed x-1.1 but it looks like a bug.

**Comment by az0** [comment]
So you mean that openSUSE offered to "upgrade" you to an older version? This sounds like it would be a bug in the openSUSE package manager, Zypper. Do you agree?

**Comment by NumDeP** [comment]
Yeah that's right. I suppose it does look like a bug from openSuse's end. So what I basically did was `sudo zyyper dup` in command and received all the updates for the system including bleachbit (4.0.0-1.4) then in openSuse's Software Update portal on the bottom bar it showed an older version.

I should note I recently updated to the latest bleachbit (4.0.0-1.7)

**Comment by ediowar** [comment]
>That is why the consensus recommendation for Tumbleweed is to use dist-upgrade with the --no-allow-vendor-change option, regardless of whether one is an expert or not. 

[The proper way to update Tumbleweed](https://lwn.net/Articles/717489/)

**Comment by ediowar** [comment]
@NumDeP 
> I should note I recently updated to the latest bleachbit (4.0.0-1.7)

From which repository?
> "zypper dup" will try to sync your currently installed packages with the ones available from (all) the repos you have enabled. This means it will also downgrade packages if your installed version is newer than the one available in the repo. 

https://en.opensuse.org/SDB:Zypper_usage

**Comment by ediowar** [comment]
@NumDeP 
> I recently searched for updates on my openSuse Tumbleweed system and noticed the bleachbit (4.0.0-1.4) update. After the update had finished downloading and installing, I then noticed another update of bleachbit (4.0.0-1.1).

Did you add a repository or download bleachbit-4.0.0-1.4.noarch.rpm?
> "zypper dup" will try to sync your currently installed packages with the ones available from (all) the repos you have enabled. This means it will also downgrade packages if your installed version is newer than the one available in the repo. 

https://en.opensuse.org/SDB:Zypper_usage

**Comment by NumDeP** [comment]
download bleachbit-4.0.0-1.4.noarch.rpm

**Comment by az0** [comment]
I am closing because this seems to be resolved

**Comment by NumDeP** [comment]
Hi @az0 could you perhaps reopen this issue as I'm seeing it again. I've included a couple of screenshots to show that the system seems to read that version x.2.1 is obsolete and not x.1.2.

Note - The first one is from the standard openSuse software updater and the second one is via 'sudo zypper dup' which is sort of like the standard software updater but on the terminal.

![Screenshot_20210512_192332](https://user-images.githubusercontent.com/31957540/118174012-d37a7000-b41d-11eb-8758-04ddfac34d17.png)

![Screenshot_20210512_192447](https://user-images.githubusercontent.com/31957540/118174028-d7a68d80-b41d-11eb-9b03-1111a5f13bac.png)
