### ISSUE TITLE
Libgio error when running bleachbit normally.

### ISSUE THREAD

**Issue by XxJohnDoe040507xX** [bleachbit/bleachbit#927]
My version is Windows 10. I have an antivirus (avg), firewall and a vpn in my browser already that is encrypted.  

Today I was running bleachbit to clean up my pc cause it was slow upon startup cause I hadn't cleaned it in some time. I do a weekly clean usually but haven't gotten around to it cause of personal health issues. 

Anyway during the scan today, my a/v stopped bleachbit from doing the cleanup further saying I had a virus called Libgio and moved it to quarantine. 

I deleted it just in case to be safe cause it sounded like it was a virus or something to me and I uninstalled bleachbit to reinstall the latest version later just in case it was just an error instead. 

Turns out after a web search, it's an error on the program.  If this file is deleted, bleachbit will no longer run (even if you uninstall it then reinstall it from the main website to the latest version).

**Comment by ediowar** [comment]
https://github.com/bleachbit/bleachbit/issues/921

**Comment by az0** [comment]
A few weeks ago I submitted [BleachBit-4.0.1.1642-setup.exe](https://ci.bleachbit.org/?prefix=dl/4.0.1.1642/) for [whitelisting](https://github.com/bleachbit/bleachbit/issues/884#issuecomment-629830710) to AVG, and they accepted it. It included the same libgio as BleachBit 4.0.0. Because libgio has not changed between 4.0.0 and 4.0.1, I would hope this didn't happen.

Today I tried to submit libgio individually, but their web site is giving me a 504 gateway timeout, so I will try again soon.


@ediowar  Good questions. Thank you

**Comment by az0** [comment]
I am closing for two reasons

1. I successfully reported libgio from BleachBit 4.0.0 to AVG.

2. The scanner https://www.virustotal.com/gui/file/f39a6f879c519a8a5d32910011fa716a464734769bb06f03ac2014e57c3991e4/detection reports 0/71 detections for this file

Let's give AVG a few days to analyze the file. If the same problem continues, reopen this ticket

**Comment by az0** [comment]
@XxJohnDoe040507xX 

Does AVG still detect an issue? I did not see it on VirusTotal, and AVG did not see it either. They wrote me'


>Please accept our apologies for the inconvenience caused. We understand that AVG has detected the reported file as a malicious one. We are unable to reproduce this detection right now.

>We will be glad to analyze the issue, but before we can, we need to analyze the threat detection by AVG. Could you please:

>1. Attach the screenshot including the detection dialog, with See details in the bottom-right corner displayed. To create a screenshot, please refer to the following link.

>Creating a screenshot
>2. Attach a screenshot of your virus database version in AVG.

>Open AVG ▸ Menu ▸ About
>We will analyze the received files and provide you with further information as soon as possible.

If you still have the problem, please provide this information, and I can pass it along. Alternatively, you could contact them directly.
