### ISSUE TITLE
Wrong language

### ISSUE THREAD

**Issue by tmlz** [bleachbit/bleachbit#928]
I specifically downloaded the English installer, but it still installed another language and I am not able to change it to English.

**Comment by az0** [comment]
The [BleachBit FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html) states
>To force BleachBit to always show in English, download and install the English installer instead of the regular installer. If using the regular (non-English-only) installer, uncheck the option to install translations.

>The language chosen in the BleachBit installer does not affect the BleachBit application: it affects only the language of the installer.



Does this help?

**Comment by tmlz** [comment]
No, I did download the English installer

**Comment by az0** [comment]
This may be related to a [known bug ](https://github.com/bleachbit/bleachbit/issues/864)in the English installer.

For now, one option is to install the regular installer (not the English installer) and uncheck the translations.

A second option is to delete the localization (i.e., translation files). I believe they are in `c:\program files (x86)\bleachbit\share\locale`. If you don't want them, it's safe to just delete them, and the application should start in English.

**Comment by az0** [comment]
@tmlz 

Would you please test the fix? It will be published in 10 minutes at https://ci.bleachbit.org/ . Please test version 4.0.1.1668 or newer

**Comment by IgorArnaut** [comment]
How about I change language inside the program???

**Comment by az0** [comment]
> How about I change language inside the program???

Please don't reply to an old, closed issue and change the subject ("necroposting"). 

If for a bug, enhancement, or feature: Instead, please search GitHub for the same open issue or create your own new issue ticket.

For technical support: use [discussions](https://github.com/bleachbit/bleachbit/discussions)
