### ISSUE TITLE
Will not install after update

### ISSUE THREAD

**Issue by aimoon13** [bleachbit/bleachbit#929]
Hi,

I been using bleachbit for quite some time.

A few weeks ago there was an update and now whenever I try to install the latest version, I run through the .exe installer and at the end it just restarts the installation process from the beginning, following an endless loop.

OS: Windows 10

**Comment by az0** [comment]
Please go to the Windows Control Panel. Which version of BleachBit does it think you have?

Also, do you know whether you chose the option to install for all users (which installs under `c:\program files x(86)`) or just for yourself (which installs under `c:\users`)?

Either way, please uninstall it from there and try again. Let me know how it goes.

**Comment by aimoon13** [comment]
Thanks for your reply.

It is magically working now again...

Best Regards

On 27 May 2020, at 01:23, Andrew Ziem <notifications@github.com> wrote:

﻿

Please go to the Windows Control Panel. Which version of BleachBit does it think you have?

Also, do you know whether you chose the option to install for all users (which installs under c:\program files x(86)) or just for yourself (which installs under c:\users)?

Either way, please uninstall it from there and try again. Let me know how it goes.

**Comment by az0** [comment]
>  It is magically working now again... 

Thank you for the update, and because it works, I will close this issue.
