### ISSUE TITLE
Remove context menu

### ISSUE THREAD

**Issue by skjerns** [bleachbit/bleachbit#932]
BleachBit added a context menu to my files `Shred with BleachBit`, however I do not use this functionality.

How do I remove this entry? I did not find anything in the preferences. In my opinion, this should be set-able in the settings.

(Windows 10)

**Comment by az0** [comment]
It's a setting in the installer. To remove the functionality, first uninstall. Then reinstall without this option enabled.

It's not something people often want to toggle.

**Comment by az0** [comment]
Closing because this seems like a question and there was no reply in ~250 days
