### ISSUE TITLE
Clean Zoom for linux

### ISSUE THREAD

**Issue by cybercom02** [bleachbit/bleachbit#935]
Could you please add a cleanup for programs like anydesk (www.anydesk.com) and zoom (www.zoom.us), they both work on linux.

**Comment by az0** [comment]
Zoom and Anydesk are separate things, and it's best not to file them together. Because Zoom is so popular, I accept the Zoom part of this issue, so I changed the title.

**Comment by cybercom02** [comment]
I found this page, about: Finding and Viewing Recordings

https://support.zoom.us/hc/en-us/articles/206277393-Finding-and-Viewing-Recordings?mobile_site=true

**Comment by cybercom02** [comment]
I also find temporary files in: /home/propietario/Documents/Zoom/

**Comment by cybercom02** [comment]
I found these three pages that talks about log files: 

https://support.zoom.us/hc/en-us/articles/205817409-Troubleshooting-Log-for-Linux

https://support.zoom.us/hc/en-us/articles/201512326-Troubleshooting-Log-for-PC

https://support.zoom.us/hc/en-us/articles/202022288-Troubleshooting-Log-For-Mac

**Comment by az0** [comment]
> I also find temporary files in: /home/propietario/Documents/Zoom/

Which kind of files are there? Recordings?

**Comment by az0** [comment]
@cybercom02 
You can wait for a beta or final release, or right now you can copy the new file [zoom.xml](https://raw.githubusercontent.com/bleachbit/bleachbit/master/cleaners/zoom.xml) into your directory `~/.config/bleachbit/cleaners` for Linux or `%AppData%\BleachBit\cleaners` for Windows.

**Comment by cybercom02** [comment]
It works great in Linux!, thank you

________________________________
De: Andrew Ziem <notifications@github.com>
Enviado: sábado, 8 de agosto de 2020 04:52 p. m.
Para: bleachbit/bleachbit <bleachbit@noreply.github.com>
CC: cybercom02 <cybercom02@hotmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [bleachbit/bleachbit] Clean Zoom for linux (#935)


@cybercom02<https://github.com/cybercom02>
You can wait for a beta or final release, or right now you can copy the new file zoom.xml<https://raw.githubusercontent.com/bleachbit/bleachbit/master/cleaners/zoom.xml> into your directory ~/.config/bleachbit/cleaners for Linux or %AppData%\BleachBit\cleaners for Windows. Try it, and let me know how it goes.
