### ISSUE TITLE
BleachBit not deleting whole Firefox URL History

### ISSUE THREAD

**Issue by KodrosX** [bleachbit/bleachbit#939]
The option to clear URL history of Firefox does not delete *all* history.

Example:

Visit a couple URLs that are already bookmarked
Visit a couple of other URLs that are not stored as bookmarks
The URL history now shows 4 different URLs
Close Firefox
Use BB to clear Firefox URL history (places.sqlite)
Open Firefox

Firefox now has removed from the history the URLs that were visited which weren't bookmarks, but it still contains the two URLs that were visited but were also bookmarked

**Comment by KodrosX** [comment]
I did some testing to make sure and examined the sqlite database after clearing the URL history (with BB, CCleaner or directly from Firefox):

### After clearing URL history with Firefox (or CCleaner):

- The contents of the `moz_historyvisits` table (`places.sqlite`) are completely cleared

- The table `moz_places` now only contains the bookmark records (if any bookmarks are stored by the user) with their fields having reset their values (if needed): 

  - visit_count = 0
  - frecency = -1
  - last_visit_date = NULL

### After clearing URL history with BB:

- The contents of the `moz_historyvisits` table are not completely cleared (records of non-bookmarked URLs that were visited are removed, but records of any bookmarked URL that was visited still remain)

- The table `moz_places` now only contains the bookmark records but if any of these bookmarked URLs was visited the following fields are still not reset:

  - visit_count (is 1 or more)
  - frecency (is not -1)
  - last_visit_date (still shows the visit date)

Which is why (I think) the URL history is not being totally cleared in case one or more bookmarks were visited before using BB.

Tested on Windows 10
BleachBit 4.0.0

**Comment by az0** [comment]
Thank you for the good bug report. I'll check into it

**Comment by az0** [comment]
@KodrosX 
Thank you again for the good bug report.  To be honest, BleachBit had this bug for a long time. I put in a fix that you can test with build 1701 (or a newer build from the master branch) available at the [BleachBit CI build site](https://ci.bleachbit.org/). Try it out, and let me know how it goes.

While working on this, I noticed a related issue https://github.com/bleachbit/bleachbit/issues/984
