### ISSUE TITLE
Windows : Google Chrome : Save As dialog

### ISSUE THREAD

**Issue by arnstein99** [bleachbit/bleachbit#944]
I find that in Microsoft Windows, Google Chrome "Save As" dialog box location does not go away. I mean,

1. I use Google Chrome dialog box to save an image file to disk.
2. I quit out of Google Chrome.
3. I run Bleachbit and clean.
4. I launch Google Chrome again and save an image to disk.

In the last step, Google Chrome defaults to saving the image to the same location  on disk as from step 1.

**Comment by az0** [comment]
Thank you for the step-by-step instructions. Later I will check into it

**Comment by devnet1985** [comment]
I'll work on this (Sparsh)

**Comment by az0** [comment]
@arnstein99 

I can reproduce this issue with Google Chrome 83 and BleachBit 4.0.1.1663 portable on Windows 10. To reproduce, I right clicked on a hyperlink to pull up the "save as" dialog. 

The value is stored in the JSON file `Default/Preferences` in a key named `savefile`
