### ISSUE TITLE
WINDOWS XP WORKS WITH LATEST VERSION + PROOF!

### ISSUE THREAD

**Issue by MeaW1** [bleachbit/bleachbit#947]
you guys are wrong , the version you archived in the website saying "BleachBit version 2.2 is the last version to support Windows XP, and it is the last version to use GTK 2." , while i didnt care , and i installed the latest version and it worked , here a screenshot , you see its working , but the updater doesnt , its no problem for me , this time dont lie to people  .
Edit : Wait for screenshots , it still uploading here , **https://imgur.com/a/E4veyZp**

**Comment by pan93412** [comment]
Oh, thanks for testing it, but we didn't lie you.

For a developer, we can't always test if any system is working with the latest version. So,

> BleachBit version 2.2 is the last version to support Windows XP, and it is the last version to use GTK 2.

means that our recommended version for Windows XP is 2.2, but you can try your luck by trying the latest version.

**Comment by az0** [comment]
I added that message on the [old downloads page](https://www.bleachbit.org/download/old) after trying BleachBit 3.0 on Windows XP. It immediately gives a fatal error and quits.

Today I added this note to BleachBit 3.0 
>BleachBit 3.0 does not start on Windows XP.


I edited the note for 2.2
>BleachBit version 2.2 was the last version intended to run Windows XP, and it was also the last version to use GTK 2.


And added this note for 2.2
>BleachBit 4.0.0 starts on Windows XP, but some support for XP was removed in BleachBit 4.0.0, it has not been tested on XP, and XP is no longer supported.

Is this better?

**Comment by MeaW1** [comment]
Yep it childish

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
