### ISSUE TITLE
totalvirus detects Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by mpelas** [bleachbit/bleachbit#948]
the Maxsecure engine detects Trojan.Malware.300983.susgen in the latest version (windows portable zip)

https://www.virustotal.com/gui/file/1d27d3828e258981ddabeb3a2427983d3deb2efb8d9c4c7369d2610d6d55b305/detection

Please provide forensics analysis
Regards

**Comment by az0** [comment]
The file hash is correct. It seems to be a false positive, so I will contact the vendor for whitelisting.

**Comment by az0** [comment]
I reported the file via [their web form](https://www.maxsecureantivirus.com/submit_aFalse_Positive.htm), and I got the instant response
>We have received your mail, we will contact you soon..

So I will wait for their response

**Comment by mpelas** [comment]
thanks for keeping me up to date
Great professionalism!

Regards from sunny Athens Greece,
Michail PAIGNIGIANNIS
Market Surveillance Officer
Radioequipment Directive Specialist
ELEC ENG, MSC, MRes, CCNA
Athens Greece

**Comment by az0** [comment]
June 25 they wrote me
>Thank you for your valuable feedback. We have forwarded the information that you have sent to our Research Team and they will provide fix in the next updates.

However, VirusTotal still has the same false positive

> MaxSecure: Trojan.Malware.300983.susgen

I will check back with them

**Comment by az0** [comment]
I tried updating the results twice today, and MaxSecure gives a timeout. In any case, it's up to them now

**Comment by lilcsz** [comment]
maxsecure is shit
