### ISSUE TITLE
Cookies manager/exclude

### ISSUE THREAD

**Issue by XhmikosR** [bleachbit/bleachbit#961]
I really like using BleachBit especially the fact that it's an open-source program :)

One feature I've been missing is the ability to exclude specific cookies, for example `mail.google.com`.

I did a search and couldn't find a similar issue here, I hope it's not duplicate.

Keep up the good work!

**Comment by az0** [comment]
>One feature I've been missing is the ability to exclude specific cookies, for example mail.google.com.

Yes, that would be helpful.

> I did a search and couldn't find a similar issue here, I hope it's not duplicate.

It is a bit hard to find, but there is a ticket for this idea in the wishlist repository https://github.com/bleachbit/wishlist/issues/70

> I really like using BleachBit especially the fact that it's an open-source program :)

Glad to hear :)

**Comment by XhmikosR** [comment]
Ah, sorry I wasn't aware there was a dedicated repo. I'm going to close this issue then.
