### ISSUE TITLE
Pressing the button in "about BleachBit" closes BB

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#962]
BB closes without any messages. If you enable Windows 7 compatibility mode in bleachbit.exe properties, the crash does not occur for usual user.
Windows 8 SL (64-bit)
BleachBit-4.0.1.1670-portable

**Comment by mkhon** [comment]
@ediowar what is you default web browser?

**Comment by az0** [comment]
@ediowar 
Does the same happen if you click the application menu, click _help_ (below _diagnostics_), and click _ok_?

**Comment by ediowar** [comment]
@mkhon
Default web browsers -- Internet Explorer, Google Chrome, Firefox.

@az0 
No, it doesn't. This only happens if you open any link in a window "About BleachBit" (Website, Launchpad Contributions and License links).

**Comment by ediowar** [comment]
@mkhon
Default web browsers -- Internet Explorer, Google Chrome, Firefox.

@az0 
No, it doesn't. This only happens if you open any link in a window "About BleachBit" (Website, Launchpad Translations Contributions and License links).

**Comment by ediowar** [comment]
@mkhon
Default web browsers -- Internet Explorer, Google Chrome, Firefox.

@az0 
No, it doesn't. This only happens if you open any link in the window "About BleachBit": https://www.bleachbit.org, Launchpad Translations Contributions (https://launchpad.net/~ak099 etc) and License (https://fsf.org/ etc).

**Comment by mkhon** [comment]
@ediowar can you run bleachbit_console.exe in cmd.exe window and let me know what is the failed assertion or any other error message when it crashes?

**Comment by ediowar** [comment]
I am running bleachbit_console.exe in cmd.exe window and no messages when it crashes.

**Comment by ediowar** [comment]
BleachBit-3.2.0-portable. When running as an administrator
![Could not show link](https://user-images.githubusercontent.com/44164186/86271615-dee1f580-bbd5-11ea-8070-0aae5a7f21d2.png)
When running as a normal user, BB closes without any messages.

**Comment by ediowar** [comment]
For some reason, the Windows 7 compatibility mode was turned on in the bleachbit.exe properties. When disabled, the crash also occurs for a usual user.

**Comment by Marvin0401** [comment]
Let me work on this issue if we have still this one.

**Comment by abitrolly** [comment]
Hi @Marvin0401. Did you manage to repeat the error?

**Comment by Marvin0401** [comment]
Hi, @abitrolly, I am testing it on several VMs to make this issue, but I did not reproduce it yet.

**Comment by abitrolly** [comment]
@ediowar could you repeat the issue with cloned BleachBit in console? I've got the feeling that `bleachbit_console.exe` may hide the needed log outout.

**Comment by ediowar** [comment]
> could you repeat the issue with cloned BleachBit in console?

What do you mean?

**Comment by abitrolly** [comment]
@ediowar yep, running from source code in `cmd`.

**Comment by az0** [comment]
I can't reproduce with BleachBit 4.2.0 (final) on Windows 10.0.18362, but this might get fixed incidentally when https://github.com/bleachbit/bleachbit/issues/848 is fixed because it will likely update the embedded GTK framework.

> @ediowar could you repeat the issue with cloned BleachBit in console? I've got the feeling that `bleachbit_console.exe` may hide the needed log outout.

@abitrolly 
There's not an easy way for non-developers to run BleachBit from source on Windows. It's much easier on Linux.

@ediowar 
If you're up for it, perhaps you could search the Windows Event Viewer for errors. I would first look inside the "Application" event source.

**Comment by ediowar** [comment]
@az0 ,
32-bit Python 3.4.4
upgraded pip-20.3.3
![Python](https://user-images.githubusercontent.com/44164186/104903502-28870780-5991-11eb-92d5-ab6e187df15c.png)

**Comment by az0** [comment]
It looks like you are doing the right thing. What does it report if you run this?

`c:\python34\scripts\pip.exe -V`

**Comment by ediowar** [comment]
@az0 ,
Same.

**Comment by ediowar** [comment]
@az0 ,
The same as in the screenshot above.

**Comment by abitrolly** [comment]
@ediowar the problem comes from `pip`. You need version before 19.2 (2019-07-22) for Python 3.4

https://pip.pypa.io/en/stable/news/#id319

**Comment by ediowar** [comment]
@az0 ,
Then maybe you need to somehow change the line `'%PYTHON_HOME%/python.exe -m pip install --upgrade pip'` in  [appveyor.ym](https://github.com/bleachbit/bleachbit/blob/master/appveyor.yml) ?

**Comment by ediowar** [comment]
@az0 ,
I ran BleachBit from source. The result is the same: there are no messages in the console. There are no errors in the Windows Event Viewer either. Can I close the issue? Moreover, Windows 8 is no longer supported.

**Comment by ediowar** [comment]
@az0 ,
I ran BleachBit from source. The result is the same: there are no messages in the console. There are no errors in the Windows Event Viewer either. Maybe I should close issue? Moreover, Windows 8 is no longer supported.

**Comment by az0** [comment]
@ediowar 
Thanks for testing. Sure, I am OK to close the issue, but I would reopen it if it turned out to be a reproducible problem on Windows 10.

**Comment by ediowar** [comment]
After upgrading the system to Windows 8.1, there is no issue for an administrator.
