### ISSUE TITLE
Non printable characters (all letters are replaced by boxes)

### ISSUE THREAD

**Issue by k7aay** [bleachbit/bleachbit#967]
I installed BleachBit using the Windows installer version, but instead of readable characters, I get non-printable characters.
Uninstalled it, deleted the installer, redownloaded, verified the checksum, and reinstalled. Same problem.
Uninstalled, then downloaded the portable version, Same problem. 
I run Windows 10 1909. 

See https://imgur.com/a/yxTJzFM

**Comment by mkhon** [comment]
Dup of #901 

Do you have FONTCONFIG_FILE environment variable set by any chance?

**Comment by az0** [comment]
@k7aay 
Please test [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) which has a fix for this problem (thanks to Max), and post a comment here in GitHub to let me know whether it was fixed.

**Comment by az0** [comment]
There was no response, but I am pretty sure it was fixed, so I'm closing this ticket
