### ISSUE TITLE
Add cleaner for new Chromium-based Edge browser

### ISSUE THREAD

**Issue by m0lz** [bleachbit/bleachbit#969]
With Win 10 2004, a new Edge came along which is now based on Chromium

Bleachbit shows Internet Explorer options to clean (which we cant fully get rid of because Windows still needs it to be installed)

Bleachbit shows [original Chromium](https://chromium.woolyss.com/) options to clean

But nothing for the new Edge which MS is pushing onto peoples systems like a class A drug

![BB](https://user-images.githubusercontent.com/20239221/86584496-e2ca9a80-bf7c-11ea-9711-2a7a83fa0a29.PNG)

**Comment by az0** [comment]
@m0lz 

OK, so you are suggesting that BleachBit cleans Edge-based Chromium, right?

**Comment by m0lz** [comment]
No sorry you misunderstand.

Edge is not showing in the list of apps to be cleaned.

As I said in the first post ..

Internet Explorer is
Original Chrome is

Edge is not

With the update to Windows 2004 recently, the New Chromium based Edge has also installed, but I have nothing new in Bleachbit. As far as I understand the Chromium listed in the screenshot is still Original Chromium which I already had installed.

Edge based on Chromium is a new app installed recently and is not appearing in Bleachbit for cleaning.

**Comment by m0lz** [comment]
If it helps, the locations of the installation locations for Chromium versus Edge are entirely different ..

Original Chromium Installation
![chromium1](https://user-images.githubusercontent.com/20239221/86830744-f7e31e80-c08d-11ea-8907-797fedab1af6.PNG)

Original Chromium User data
![chromium2](https://user-images.githubusercontent.com/20239221/86830760-fd406900-c08d-11ea-88b8-56b0405bf679.PNG)

Edge Installation location
![edge1](https://user-images.githubusercontent.com/20239221/86830698-ea2d9900-c08d-11ea-8e50-7b6e85724d31.PNG)

Edge User data
![edge2](https://user-images.githubusercontent.com/20239221/86830679-e39f2180-c08d-11ea-95f7-25fec7f3e04f.PNG)

------------------

But note even before Edge became Chromium based, it has never appeared in Bleachbit options for cleaning

I have had Internet Explorer, and Edge, and Original Chromium installed for a few years, and in all that time using Bleachbit Edge has never appeared in Bleachbit for cleaning.

I do not use Internet Explorer, and I also do not use Edge. We are just forced by MS to have them installed whether we use them or not.
I use Chromium as my default browser.

But having all three of them installed has highlighted that Bleachbit is not picking up on the Edge browser being installed.

**Comment by m0lz** [comment]
> @m0lz
> 
> OK, so you are suggesting that BleachBit cleans Edge-based Chromium, right?

:) Sorry, yes, my previous replies misunderstood what you said.

I read your post as meaning I was suggesting that Bleachbit already cleans Edge Based on Chromium.

But what you meant was I was suggesting that it should clean Edge Based on Chromium.

Yes please, I would very much like Bleachbit to clean Edge based on Chromium

**Comment by az0** [comment]
> Yes please, I would very much like Bleachbit to clean Edge based on Chromium

I agree. Later I will add it myself and test it, but for now you can do it. The procedure is basically the same as adding the Brave browser because both are based on Chromium. If you want to try, here is an outline of the steps https://github.com/bleachbit/wishlist/issues/92

**Comment by az0** [comment]
You can download the release here: [BleachBit 4.2.0 (final)](https://www.bleachbit.org/news/bleachbit-420)

@mkhon thank you :)
