### ISSUE TITLE
Consider change  `/usr/bin/env python3` to `/usr/bin/python3` in `/usr/bin/bleachbit` ?

### ISSUE THREAD

**Issue by Jerrywang959** [bleachbit/bleachbit#972]
I use bleachbit 4.0.0 in deepin linux v20 beta. I type `bleachbit` in terminal, it shows that `ModuleNotFoundError: No module named 'gi'`.  Later, I find it's becaues I use python from anaconda. When I change the first line of `/usr/bin/bleach` from `#!/usr/bin/env python3` to `#!/usr/bin/python3`, it works. 

In my opinion, it's better to substitute `/usr/bin/python3` for  `/usr/bin/env python3` because a software needs just use python from system.

**Comment by az0** [comment]
On my Ubuntu  20.04 system there are 129 files in `/usr/bin` with a shebang interpreter directive

 `grep -IPs "^\#" -m 1 *  |grep python   |wc -l`

Of those, only 3 use `env`, so they agree with you.

**Comment by mkhon** [comment]
I don't think the fix was correct. See this for example: https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take

The user just had another python installation that he used as a default and he just needed to add gi packages there.

**Comment by Jerrywang959** [comment]
> I don't think the fix was correct. See this for example: https://stackoverflow.com/questions/6908143/should-i-put-shebang-in-python-scripts-and-what-form-should-it-take
> 
> The user just had another python installation that he used as a default and he just needed to add gi packages there.

However, It hard for me to add gi packages for python from anaconda.
I had tried 

```shell
pip install gi
```

it shows

```python
ERROR: No matching distribution found for gi
```

The version of python in my envrionment is 3.7.6 and I use deepin Linux v20. So I can just only use `#!/usr/bin/python3` to start bleachbit

**Comment by az0** [comment]
> I don't think the fix was correct.

There are a few things going on in the StackOverflow article. 
I am not using the unversioned `python` nor the `/usr/local/bin` directory.

So, you would undo change 4580240f7e86cd0732c89d5ab7dd77c4fc9b6864 , or do you mean something else?

**Comment by mkhon** [comment]
bleachbit should use default Python (this is what "#!/usr/bin/env python3" does. Other users may have reasons to use non-system Python with bleachbit.

If the user has non-system Python that he can not use with Bleachbit for some reason he should run bleachbit as "PATH=/usr/bin:$PATH bleachbit".
