### ISSUE TITLE
Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#974]
git revision https://github.com/bleachbit/bleachbit/commit/f8c3453e113e09facf2f0c83396e84c463b572bc Ubuntu 16.04
Messages appear. When running BB with sudo
```
(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
```
And when running BB without sudo
```
(bleachbit.py:5109): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5109): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
```
In addition, after BB session with sudo, issue https://github.com/bleachbit/bleachbit/issues/964 occurs when starting BB without sudo
### Steps to Reproduce

1. Run BB
2. Check the "Show debug messages" checkbox in the settings
3. Close BB
4. Run BB
5. Shred Settings and Quit

Same thing in openSUSE Tumbleweed KDE.

**Comment by gaurapanasenko** [comment]
I'll work on this one.

**Comment by br-z0** [comment]
I'll work on this one.

**Comment by az0** [comment]
I unassigned this issue because of lack of updates. If you have an update, please add a comment. Thank you

**Comment by abitrolly** [comment]
No warning for me in non-root mode after #1330.

**Comment by az0** [comment]
Fixed in https://github.com/bleachbit/bleachbit/pull/1330
