### ISSUE TITLE
whitelist .dotted directory Ubuntu?

### ISSUE THREAD

**Issue by bulgin** [bleachbit/bleachbit#976]
I cannot whitelist /home/directory/.cache/bleachbit

No option to enter a .dotted directory.

**Comment by az0** [comment]
Try this:

1. Open BleachBit
1. Go to the whitelist window
1. Click Add Folder
1. Right click
1. In the menu that pops up, choose the option "show hidden files"

Does this help?

For what it's worth, this window is part of GTK, so it's not specific to BleachBit. Many applications on Ubuntu use GTK.
