### ISSUE TITLE
Is the current version of BleachBit compatible with Ubuntu 20.04.1 LTS?

### ISSUE THREAD

**Issue by vyujitanaka** [bleachbit/bleachbit#977]
Is the current version of BleachBit compatible with Ubuntu 20.04.1 LTS? If not, is there any prediction of when we might have it? Keep working on this wonderful project!

**Comment by az0** [comment]
Yes, I use it on Ubuntu 20.04. For now, try the [.deb package](https://www.bleachbit.org/download/linux) for Ubuntu 19.10 or 19.04. Let me know how it goes.

**Comment by az0** [comment]
@vyujitanaka 

Have you given this a try? How did it go?

**Comment by vyujitanaka** [comment]
Hi there! Thank you very much for answering me. I tested. However, I noticed that after a while, my system started to get a little slow. Is this due to the number of times that I cleaned my system or could it be for another reason? I usually like to clean my system once or twice a day.

**Comment by az0** [comment]
@vyujitanaka 

I don't think this would cause slowness.

What kind of slowness is it? For example, opening an application for the first time? Opening each web page?

Under the system category, do you use the "free disk space" or "memory" options?

Do you have a HDD or a SDD?

How much RAM do you have?

**Comment by az0** [comment]
There is a deb package for Ubuntu 20.04 available for [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta), and there will be a deb package also for the 4.2.0 final release
