### ISSUE TITLE
wipe drive free space error

### ISSUE THREAD

**Issue by tolga694** [bleachbit/bleachbit#978]
Version: 4.0.0
OS: windows 7 (64-bit)
Error message:
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Error: _gui.free_disk_space: Function: Overwrite free disk space D:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'D:\\tmpv8np10bbzLJkT4yADmlAahqWvwdwBS7SFf_P7AKn-tqxLpprQcL3UG6GI4eRcYxNguYyTn0.AOFtWdZX4bFbs0ycMTI-N-CLP17-pz5HTTXo_y18oUxaquUS1rUQSJVJ_IdKuJCG7bN_BRZPlSDpSvWK-3150dKMfNYO4nozYBMjla0abcKByWP0gJ8Bubv5ovs_NCO5eZGMEY_JGTxMq2SJdARGW.aI0oIer1ITleyJV2dfgQZ3tmA7lluv5'

Disk space recovered: 0
Files deleted: 0
Errors: 1

------

No particular steps were taken to cause the issue.
Both hard drives have this issue.

**Comment by ediowar** [comment]
Seems to be a dup of https://github.com/bleachbit/bleachbit/issues/934

**Comment by tolga694** [comment]
> Seems to be a dup of #934

Thanks for the tip.
Is it better if I use 3.2.0 or one of the unstable versions?
I need wipefreespace to work very correctly. I can do without the other features.

**Comment by ediowar** [comment]
I personally have not tested Wipe Free Space in 3.2/0.

**Comment by tolga694** [comment]
> I personally have not tested Wipe Free Space in 3.2/0.
> [#899 (comment)](https://github.com/bleachbit/bleachbit/issues/899#issuecomment-655199436)

I tried [4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts) and it worked correctly.

**Comment by az0** [comment]
> I tried [4.0.1.1664](https://ci.appveyor.com/project/az0/bleachbit/builds/33732268/artifacts) and it worked correctly.

Thank you for confirming. It works, so I will close this issue
