### ISSUE TITLE
BleachBit won't delete Chrome history and cache

### ISSUE THREAD

**Issue by Ivan75** [bleachbit/bleachbit#979]
I haven't noticed this 'till recently, as you can see in the screenshot, Chrome cache and history are selected, After cleaning it reports the amount of deleted data but the data is still there when I check.
Notice the error reporting, BleacBit couldn't find some specified Windows folders too.
C/Users/USER/AppData/local/Google was marked as ''Read-only'' so I tried to unmark it and run BB again - nothing new happened.

Please help.
![Screenshot (1)](https://user-images.githubusercontent.com/39677610/89771276-59b8fd00-db00-11ea-9548-f4e07db92889.png)

BleachBit version - 4.00
Windows 10 64bit (2004)

**Comment by Ivan75** [comment]
Two weeks and no answers, not a single comment, here nor on the support forum.

**Comment by az0** [comment]
OK, I see your duplicate post over there https://www.bleachbit.org/forum/bleachbit-wont-delete-chrome-history-and-cache

The errors in red are related to Internet Explorer. If you uncheck Internet Explorer cookies and history, these errors should disappear.

Back to Google Chrome: in which way do you check the data is still there? Do you mean you look in the Google Chrome data folder for the files? Or do you mean you open the browser and hit CTRL+H to pull up your browsing history?

**Comment by Ivan75** [comment]
I do it both ways.

**Comment by zodiac-1** [comment]
Same problem with me with Chrome History Error, I'm on Windows 10 1803 Education

**Comment by Ivan75** [comment]
Ok, let's wait for the next update, BB or Chrome, I've never had any problems before

**Comment by Ivan75** [comment]
I have just tested the latest beta update, the same settings - everything is now working fine, no errors.
Thank you!

**Comment by az0** [comment]
> I have just tested the latest beta update, the same settings - everything is now working fine, no errors.

Thank you for confirming. Because it works, I will close this ticket.
