### ISSUE TITLE
BleachBit adds wildcards to winapp2.ini file masks where there should be none

### ISSUE THREAD

**Issue by MoscaDotTo** [bleachbit/bleachbit#982]
https://github.com/MoscaDotTo/Winapp2/issues/728#issuecomment-671223303

Quoted below

I have now checked it with BleachBit 4.0.0 and was able to reproduce the problem. However, the problem is not caused by the Winapp2.ini, but by a dangerous bug in BleachBit: BleachBit seems to put a wildcard before each search pattern!

Example: FileKey2=%LocalAppData%\Microsoft\Edge\User Data\Default|LOG;LOG.old|RECURSE

This FileKey should only delete files that are named exactly "LOG" or "LOG.old". BleachBit deletes however "*LOG" and "*LOG.old":
```
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBit.log
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBitlog
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBit.log.old
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBitlog.old
```
This is a very dangerous behavior for a cleanup tool and definitely a bug!

**Comment by az0** [comment]
OK, I'd like to start by creating a unit test that reproduces this and to avoid regressions.

**Comment by rados** [comment]
@az0 
I've just reproduced and started tracing the issue. I could finish it.

**Comment by az0** [comment]
@MoscaDotTo 

Rados coded a fix for this, and would you please test [BleachBit build 1950 or later](https://ci.bleachbit.org/)?

**Comment by APMichael** [comment]
I have repeated the test with version 4.4.1.1952. BleachBit now only deletes the files that are specified in the FileKey. The unwanted wildcard before each search pattern is now fixed. Thanks a lot!

**Comment by az0** [comment]
> I have repeated the test with version 4.4.1.1952. BleachBit now only deletes the files that are specified in the FileKey. The unwanted wildcard before each search pattern is now fixed. Thanks a lot!

Thank you for the quick feedback and for filing the original bug report!
