### ISSUE TITLE
DNF autoremove throws a TypeError

### ISSUE THREAD

**Issue by terrycloth** [bleachbit/bleachbit#983]
(This was first [reported to me on the Red Hat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1867383), against the RPM build of BleachBit for Fedora 32 Workstation x86_64 -- but I also tested using `bleachbit-4.0.0-1.1.fc31.noarch.rpm` from the BleachBit website, and get the same results.)

1. Launch BleachBit as root (using `sudo` from terminal).
2. Deselect all cleaners, except DNF autoremove.
3. Click Preview button. 
![image](https://user-images.githubusercontent.com/3881885/90080895-b105cb80-dcc0-11ea-9168-e04e9f21e9ae.png)
4. Click Clean button and see errors. 
![image](https://user-images.githubusercontent.com/3881885/90080922-c1b64180-dcc0-11ea-8c30-3ec05c7500d3.png)

Terminal output is mostly the same (but pasting the text will make this issue searchable).

```
  ↪ sudo bleachbit
closest monitor (0) geometry = (0, 0)+(3840, 2160), window geometry = (1520, 766)+(1441, 978)
Error: dnf.autoremove: Function: dnf autoremove
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 142, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 717, in dnf_autoremove
    line = process.stdout.readline().replace("\n", "")
TypeError: a bytes-like object is required, not 'str'
subprocess 18280 is still running

<exit code 0>
```

**Comment by az0** [comment]
Good detail for the bug report. Thank you
