### ISSUE TITLE
Wipe Free Space results in program error

### ISSUE THREAD

**Issue by ballsar** [bleachbit/bleachbit#986]
Screen shot 

![bleach error](https://user-images.githubusercontent.com/12476512/90322105-ca538580-df15-11ea-90e7-ec21b32473df.png)

**Comment by ediowar** [comment]
Another dup of https://github.com/bleachbit/bleachbit/issues/899

**Comment by az0** [comment]
@ediowar Yes, thank you

I documented this as a known issue in the [release notes for BleachBit 4.0.0](https://www.bleachbit.org/news/bleachbit-400#known_issues)
