### ISSUE TITLE
Error in execution of <bleachbit.Command.Function instance at 0x7fac0c5bd7d0>

### ISSUE THREAD

**Issue by iamabs2001** [bleachbit/bleachbit#988]
Error in execution of <bleachbit.Command.Function instance at 0x7fac0c5bd7d0>
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 138, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/bleachbit/Unix.py", line 660, in yum_clean
    run_cleaner_cmd('yum', args, '^unused regex$', invalid)
  File "/usr/share/bleachbit/bleachbit/Unix.py", line 582, in run_cleaner_cmd
    universal_newlines=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['yum', '--enablerepo=*', 'clean', 'all']' returned non-zero exit status 1

**Comment by iamabs2001** [comment]
BleachBit version 2.0
GTK+ version 2.24.32
SQLite version 3.27.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/sigma/.config/bleachbit
personal_cleaners_dir = /home/sigma/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = lightdm-xsession
os.getenv('LOGNAME') = sigma
os.getenv('USER') = sigma
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/sigma
platform.linux_distribution() = ('Parrot', '4.6', 'stable')
platform.platform = Linux-4.19.0-parrot4-28t-amd64-x86_64-with-Parrot-4.6-stable
platform.version = #1 SMP Parrot 4.19.28-2parrot4.28t (2019-04-18)
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python
sys.version = 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
[GCC 9.3.0]
__file__ = /usr/share/bleachbit/bleachbit/Diagnostic.pyc

**Comment by az0** [comment]
BleachBit 2.0 was released February 2018. It is old and no longer supported. The latest stable release is 4.0.0, and there are also newer, non-stable versions available. Please try with 4.0.0 and later. I never used Parrot OS, but I read it is based on Debian, so you may be able to use a [BleachBit .deb package](https://www.bleachbit.org/download/linux) built for Debian. If the same error happens with a new version of BleachBit, please reopen this ticket.

**Comment by iamabs2001** [comment]
BleachBit version 3.9.0
Git revision c92fae9
GTK version 3.24.10
GTK theme = Sierra-dark-solid
GTK icon theme = Mkos-Big-Sur-Night
GTK prefer dark theme = True
SQLite version 3.27.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/sigma/.config/bleachbit
personal_cleaners_dir = /home/sigma/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = lightdm-xsession
os.getenv('LOGNAME') = sigma
os.getenv('USER') = sigma
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/sigma
platform.linux_distribution() = ('Parrot', '4.6', 'stable')
platform.platform = Linux-4.19.0-parrot4-28t-amd64-x86_64-with-Parrot-4.6-stable
platform.version = #1 SMP Parrot 4.19.28-2parrot4.28t (2019-04-18)
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.7.3rc1 (default, Mar 13 2019, 11:01:15) 
[GCC 8.3.0]
__file__ = /usr/share/bleachbit/bleachbit/Diagnostic.py
