### ISSUE TITLE
Missing requirements.txt?

### ISSUE THREAD

**Issue by flyingbot91** [bleachbit/bleachbit#990]
Since this is a python project, is there any **requirements.txt** file?

Aside from **.travis.yaml**, is there any other reference about required pip packages?

Thank you for your answers.

**Comment by az0** [comment]
There is not much required that is not on a typical Linux system with a GUI.

> Since this is a python project, is there any **requirements.txt** file?

No

> Aside from **.travis.yaml**, is there any other reference about required pip packages?

1. Install the deb/rpm packages, or inspect the packages, or inspect the source of the packages
1. Run  the program and see where you get an ImportError

**Comment by az0** [comment]
Dependencies are covered here https://docs.bleachbit.org/dev/running-from-source-code.html
