### ISSUE TITLE
Verifying Signature Instructions Might Be Incorrect?

### ISSUE THREAD

**Issue by wavesurf432** [bleachbit/bleachbit#991]
Hello, I don't know whether this is an issue or not, but just wanted to mention incase it was.

In the instructions for verifying signatures on Linux (https://docs.bleachbit.org/doc/install-on-linux.html) the public key is shown as 0xd6d447b02b4d4c9d, but when I followed the instructions, D6D447B02B4D4C9D showed up in the terminal. The key for the latest version of Bleachbit on Github is D6D447B02B4D4C9D aswell, not 0xd6d447b02b4d4c9d.

The key I downloaded was from Sourceforge (andrew2019.key), as mentioned in the instructions.

Hope this helps, thanks.

**Comment by az0** [comment]
The key ID  `0xd6d447b02b4d4c9d` is basically the same as `D6D447B02B4D4C9D`. The `0x` clarifies it is a hexadecimal string. The latter part `0xd6d447b02b4d4c9d` is not case sensitive (because it is hexadecimal), so `d6d447b02b4d4c9d` is identical to `D6D447B02B4D4C9D`.

Does this help?

By the way, I made some not-exactly-related updates to the docs page you mentioned
- I changed the MIT link to point to gnupg.net
- I added a gnupg.net link
- I fixed the key ID for the old key

**Comment by wavesurf432** [comment]
> The key ID `0xd6d447b02b4d4c9d` is basically the same as `D6D447B02B4D4C9D`. The `0x` clarifies it is a hexadecimal string. The latter part `0xd6d447b02b4d4c9d` is not case sensitive (because it is hexadecimal), so `d6d447b02b4d4c9d` is identical to `D6D447B02B4D4C9D`.
> 
> Does this help?
> 
> By the way, I made some not-exactly-related updates to the docs page you mentioned
> 
> * I changed the MIT link to point to gnupg.net
> * I added a gnupg.net link
> * I fixed the key ID for the old key

Thanks for the reply bud, much appreciated!

I'm new to verifying signatures and that kind of thing, so the key showing up in the terminal as D6D447B02B4D4C9D, and not 0xd6d447b02b4d4c9d as shown in the documentation, caused a little confusion/concern. I was pretty sure they were the same thing, but wanted to make sure.

Maybe adding a little note in the documentation explaining that if D6D447B02B4D4C9D is shown in the terminal it's the same as 0xd6d447b02b4d4c9d? Would prevent other folks who are new to verifying signatures from being confused by this in the future?

**Comment by az0** [comment]
ok, done

**Comment by wavesurf432** [comment]
Sweet!

Just one more suggestion incase it helps at all; it might be nice to have something under **Checksums** on the Linux download pages like... ''Instructions for verifying: https://docs.bleachbit.org/doc/install-on-linux.html''?

**Comment by az0** [comment]
OK, I added it to the download page where you suggested, by checksums
