### ISSUE TITLE
using shred from context menu causes crash

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#993]
BleachBit version 4.0.1 build number 1695 (Git revision 3d3383a6 from 20 days ago)
Windows 10

# Steps to reproduce

1. Open Windows Explorer
1. Right click on File
1. Choose Shred with BleachBit

# Results

The GUI briefly opens. It shows the application window, the log, and the confirmation dialog. Then, before I have a chance to do anything, the application closes itself.

If done from console, it shows this too

````
C:\temp>"c:\Program Files (x86)\BleachBit\bleachbit_console.exe" --gui --no-uac --shred c:\temp\a.log
Success
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 260, in run
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 336, in run_operations
KeyError: '_gui'
````

**Comment by br-z0** [comment]
I'll work on this one.

**Comment by Marvin0401** [comment]
Is this issue resolved? If not, let me work on this one.

**Comment by Marvin0401** [comment]
Hi @az0 ,

**Comment by Marvin0401** [comment]
Could you run this command again?
C:\temp>"c:\Program Files (x86)\BleachBit\bleachbit_console.exe" --no-uac --shred c:\temp\a.log

**Comment by 229love** [comment]
Hey I am having this issue after updating bleachbit If there is a soultion please be kind enough to point it out.

Thanks.

**Comment by az0** [comment]
> Could you run this command again?
> C:\temp>"c:\Program Files (x86)\BleachBit\bleachbit_console.exe" --no-uac --shred c:\temp\a.log

With BleachBit 4.2.0 (final release), it works with console, but with GUI, it fails with KeyError

```
C:\temp>"c:\Program Files (x86)\BleachBit\bleachbit_console.exe" --shred --no-uac  c:\temp\deleteme.txt
Delete 13B c:\temp\deleteme.txt
Disk space recovered: 13B
Files deleted: 1
```

It worked in older versions of BleachBit (apparently before 4.0.0)

**Comment by az0** [comment]
> Hey I am having this issue after updating bleachbit If there is a soultion please be kind enough to point it out.

See the workarounds here: https://github.com/bleachbit/bleachbit/issues/893#issuecomment-778695797

**Comment by Marvin0401** [comment]
Hi @az0 ,

**Comment by Marvin0401** [comment]
I've found the some issue for the architecture of running command with GUI before based on my checking and testing so I asked you to run the above command. I think I can fix this issue soon.

**Comment by az0** [comment]
I am assigning this to @rados because has committed a change related to it.

**Comment by az0** [comment]
@229love 

This is now fixed, and you can try it out by downloading build 4.2.0.1838 or later from the [CI build site](https://ci.bleachbit.org/). Please allow a few minutes for it to upload. If you are able to test, please add a comment here to confirm it's fixed.

**Comment by 229love** [comment]
Yeah let me test and let you know
Thanks.

**Comment by 229love** [comment]
@az0 

The integrate shed feature via the context menu does work. And also as this version is kind of a beta release if I face any issues with it I will inform you.
