### ISSUE TITLE
Bleachbit 4.0.0 does not start with admin privileges (Linux Mint)

### ISSUE THREAD

**Issue by VAK58** [bleachbit/bleachbit#994]
I am using Linux Mint20 Cinnamon fully updated. I find Bleachbit as administrator just does not start up, but starts normally without admin rights.

**Comment by ediowar** [comment]
What's the error in the terminal?

**Comment by VAK58** [comment]
I am a newbie in Linux. I am not aware how I can see any error in terminal. But I opened Bleachbit without admin priviledges, and I saw this in diagnostics.
-------------------------------------------
BleachBit version 4.0.0
Git revision f2093f8
GTK version 3.24.20
GTK theme = Mint-X-Sand
GTK icon theme = Mint-Y-Dark-Aqua
GTK prefer dark theme = True
SQLite version 3.31.1
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/vivek/.config/bleachbit
personal_cleaners_dir = /home/vivek/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_IN', 'ISO8859-1')
os.getenv('DESKTOP_SESSION') = cinnamon
os.getenv('LOGNAME') = vivek
os.getenv('USER') = vivek
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /home/vivek
platform.linux_distribution() = ('LinuxMint', '20', 'ulyana')
platform.platform = Linux-5.4.0-42-generic-x86_64-with-glibc2.29
platform.version = #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by ediowar** [comment]
Just start BB with `sudo bleachbit` in a terminal window.

**Comment by VAK58** [comment]
I ran the command as described by you in a terminal window and did not face any issues. The problem comes when using the provided icon shortcut, to run Bleachbit under admin privileges. The below text is what appeared in the terminal window.
-------------------------------------
vivek@Inspiron-3537:~$ sudo bleachbit
[sudo] password for vivek:
closest monitor (0) geometry = (0, 0)+(1366, 768), window geometry = (283, 54)+(800, 600)
Special file type cannot be deleted: /root/.cache/keyring-1XNJP0/control
Special file type cannot be deleted: /root/.cache/keyring-1XK5P0/control
Skipping mount point: /root/.cache/gvfs
Directory is not empty: /root/.cache/keyring-1XNJP0
Directory is not empty: /root/.cache/keyring-1XK5P0
vivek@Inspiron-3537:~$

Thanks

**Comment by VAK58** [comment]
I made another discovery. I am using Cairo dock. I find that the problem comes only when I start Bleachbit with admin privileges through the icon in Cairo dock. But the program starts normally when I start it from the main menu. Strange!On Aug 29, 2020 13:54, ediowar <notifications@github.com> wrote:
What's the error in the terminal?

**Comment by az0** [comment]
@VAK58 
Are you using Wayland? If so, see https://github.com/bleachbit/bleachbit/issues/1084 and the [FAQ](https://docs.bleachbit.org/doc/frequently-asked-questions.html#:~:text=Q%3A%20How%20to%20run%20the%20GUI%20as%20root%20on%20Linux%20under%20Wayland%3F)

**Comment by az0** [comment]
@VAK58 

It has been a month. What do you think of my last comment about  issue 1084 and the FAQ?

**Comment by az0** [comment]
closing because no response, but feel free to reopen with response
